DIYgod/RSSHub

- lib/routes/discord/channel.ts
- lib/routes/discord/discord-api.ts
- lib/routes/discord/templates/message.art
- package.json
- pnpm-lock.yaml
Close #
```routes
/discord/channel/1243823540457701431
```
> fix(route): discord join event

- lib/routes/kurogames/namespace.ts
- lib/routes/kurogames/wutheringwaves/news.ts
Close #
```routes
/kurogames/wutheringwaves/news
```
> feat(route): 新增鸣潮游戏公告、新闻与活动

- lib/routes/zhihu/utils.ts
Close #
```routes
/zhihu/people/answers/diygod
```
> fix(route/zhihu): Trim characters while extracting cookies

- lib/routes/javdb/actors.ts
Close #
```routes
/javdb/actors/B8K29/d?addon_tags=212
```
如题，为 `/javdb/actors/:id/:filter?` 添加额外的 tags 筛选支持，例如 `/javdb/actors/B8K29?addon_tags=212` 可筛选 VR。
> feat(route): javdb actors addon_tags

- lib/routes/keylol/index.ts
Close #16334
```routes
/keylol/f161-1
```
> fix(route/keylol): handle lazy load image

- lib/routes/tvb/news.ts
Close #16358
```routes
/tvb/news
/tvb/news/focus
/tvb/news/instant
/tvb/news/local
/tvb/news/greaterchina
/tvb/news/world
/tvb/news/finance
/tvb/news/sports
/tvb/news/parliament
/tvb/news/weather
```
> fix(route): TVB「NEWS」返回异常

- lib/routes/google/research.ts
Close #
```routes
/google/research
```
> feat(route): add google research blog

- lib/routes/the/index.ts
- lib/routes/the/namespace.ts
- lib/routes/the/templates/description.art
- lib/routes/the/util.ts
Close #16333
```routes
/the
```
> feat(route): add The.bi

- lib/routes/nationalgeographic/latest-stories.ts
- lib/routes/nationalgeographic/templates/stories.art
Close #
```routes
/nationalgeographic/latest-stories
```
> fix(route): parse error for nationalgeographic

- lib/config.ts
Close #
```routes
NOROUTE
```
建议删除此统计功能，在此添加此功能降低了rsshub原有的鲁棒性，增加了风险点。
当前umami.rss3.io疑似处于宕机状态，在默认情况下安装的rsshub docker镜像会因此步无法执行而报错无法启动。
> fix: delete rss3.io statistics

- lib/routes/showstart/artist.ts
- lib/routes/showstart/brand.ts
- lib/routes/showstart/event.ts
- lib/routes/showstart/search.ts
- lib/routes/showstart/service.ts
- lib/routes/showstart/site.ts
- lib/routes/showstart/utils.ts
Close #
```routes
/showstart/artist/301783
/showstart/brand/34707
/showstart/site/3583
/showstart/search/site/酒球会
```
> feat(route/showstart): add route for site; add typescript types for other routes; replace got with ofetch

- lib/routes/51read/article.ts
- lib/routes/51read/namespace.ts
Close #
```routes
/51read/article/152685
```
> feat(route): add 51read.org

- lib/routes/showstart/service.ts
> fix(showstart): fix the match condition of city and style

- lib/routes/youtube/subscriptions.ts
Close #
```routes
/youtube/subscriptions
```
> chore: add link for youtube subscription

- lib/routes/techcrunch/news.ts
- lib/routes/techcrunch/templates/description.art
Close #
```routes
/techcrunch/news
```
use wp restful for techcrunch.
> fix(route): use wp api for techcrunch

- lib/routes/kaopu/news.ts
Close #16418 
```routes
/kaopu/news
/kaopu/news/zh-hans
/kaopu/news/zh-hant
```
> fix(docs): 靠谱新闻「NEWS」example 不正确

- lib/routes/imop/namespace.ts
- lib/routes/imop/tianshu.ts
Close #
```routes
/imop/tianshu
```
> feat(route): 增加对千橡游戏下天书奇谈游戏最新消息的支持

- lib/routes/hket/index.ts
Close #16430
```routes
/hket/sran001
```
> fix(route): hket url

- lib/routes/buaa/jiaowu.ts
- lib/routes/buaa/lib/space/newbook.ts
- lib/routes/buaa/lib/space/templates/newbook.art
N / A
```routes
/buaa/lib/space/newbook
```
The documentation in `description` (L24) may need to be better formatted.
> feat(route): add buaa/lib/space/newbook

- lib/routes/fediverse/timeline.ts
Close #16445
```routes
/fediverse/timeline/Mastodon@mastodon.social
```
`firstOutbox`返回的数据中不存在`item.url`字段，导致目前生成的item的link全部为空元素。
改为从`item.object.url`获取item的link。
> fix(route/fediverse): Item link is empty

- lib/routes/yicai/carousel.ts
- lib/routes/yicai/utils.ts
Close #
```routes
/yicai/carousel
/yicai/news
/yicai/latest
```
> feat(route/yicai): Add route for carousel part on front page

- lib/registry.test.ts
- lib/registry.ts
- lib/routes/healthz.ts
Close #
```routes
/healthz
```
> fix(core): healthz bypass cache

- lib/routes/devolverdigital/blog.ts
Close #
```routes
/devolverdigital/blog
```
> fix(route): devolverdigital no longer uses embedded json

- lib/routes/gov/chongqing/sydwgkzp.ts
Close #
```routes
/gov/chongqing/sydwgkzp
```
> fix(route/sydwgkzp): sync with the new website structure to fix 503

- lib/routes/infzm/hot.ts
- lib/routes/infzm/utils.ts
Close #
```routes
/infzm/2
/infzm/hot
```
> feat(route/infzm): Support hot articles list.

- lib/routes/apnews/sitemap.ts
- lib/routes/apnews/utils.ts
Close #
```routes
/apnews/sitemap/news-sitemap-content?limit=40
/apnews/sitemap/ap-sitemap-latest?limit=40
```
> feat(route/apnews): Add support for sitemap

- lib/routes/xiaohongshu/notes.ts
- lib/routes/xiaohongshu/user.ts
Close #16106
```routes
/xiaohongshu/user/52d8c541b4c4d60e6c867480/notes
/xiaohongshu/user/52d8c541b4c4d60e6c867480/notes/fulltext
```
- show the doc section correctly
- display the param table
- provide example
> fix(docs): xiaohongshu doc missing 

- lib/routes/sustainabilitymag/articles.ts
Close #
```routes
/sustainabilitymag/articles
```
Add `blockquote` widget type handling in `render` function to resolve errors.
> fix(sustainabiliymag): fix unhandled widget type on blockquote

- lib/routes/hottoys/index.ts
- lib/routes/hottoys/namespace.ts
Close #16238
```routes
/hottoys
```
> feat(route): add route /hottoys (#16238)

- lib/routes/joins/chinese.ts
- lib/routes/joins/namespace.ts
- lib/routes/joins/templates/description.art
Close #16175
```routes
/joins/chinese
```
> feat(route): add 中央日报中文网

- lib/routes/zhihu/answers.ts
- lib/routes/zhihu/utils.ts
Close #16260 
```routes
/zhihu/people/answers/L.M.Sherlock
```
路由 `/zhihu/people/activities/:id` 可以正常获得回答和文章的全文，但路由 `/zhihu/people/answers/:id` 却始终只能获得截断的回答。
检查源代码后，发现 `/zhihu/people/answers/:id` 代码中，并没有从本地读取并使用 `z_c0` ，这就导致即使配置了环境变量，在该路由下也无法获取回答的全文。
该pr中，添加了读取 `z_c0` 的代码，使路由 `/zhihu/people/answers/:id` 可以正常获得回答全文。
https://github.com/DIYgod/RSSHub/issues/16260#issuecomment-2295206323
> fix(route/zhihu): Fix bug that zhihu answers would be truncated

- lib/routes/rebase/geekdaily.ts
- lib/routes/rebase/namespace.ts
Close #
```routes
/rebase/geekdaily
```
> feat(route): add Web3 Geek Daily

- lib/routes/gisreportsonline/index.ts
Close #
```routes
/gisreportsonline/c/security-challenges/
```
> fix(route/gisreportsonlline): Restore linefeed

- lib/routes/newyorker/news.ts
Close #
```routes
/newyorker/latest
```
rss provided by New Yorker has been deprecated. need to parse the original website to fetch the data.
> fix(route): new yorker

- lib/routes/towardsdatascience/latest.ts
- lib/routes/towardsdatascience/namespace.ts
Close #
```routes
/towardsdatascience/latest
```
Use [freedium](https://freedium.cfd) as proxy to fetch full-text contents.
> feat(towardsdatascience): add route

- lib/routes/showstart/search.ts
Close #14204 
```routes
/showstart/artist/301783
/showstart/brand/34707
/showstart/site/3583
/showstart/search/dummy
```
- 原因搜索结果为空的时候没有构建一个合法的rss return.
- 更新了parameters document
- 修改parameters '/search/:type/:keyword?' 为可选参数 'search/:type?/:keyword?'
> fix(route): showstart search

- lib/routes/gov/lswz/index.ts
Close #16485
```routes
/gov/lswz
```
> feat(route): add 国家粮食和物资储备局

- lib/routes/flashcat/blog.ts
- lib/routes/flashcat/namespace.ts
Close #
```routes
/flashcat/blog
```
> feat: route of flashcat blog

- lib/routes/uber/blog.ts
Close #
```routes
/uber/blog
```
Former url `www.uber.com/blog/pittsburgh/engineering` is not a general one, uber blog now redirect itself to `www.uber.com/:language/blog`, e.g. `www.uber.com/en-HK/blog/`
> fix: rsshub radar for uber blog

- lib/routes/gov/lswz/index.ts
Close #
```routes
/gov/lswz/html/ywpd/nycb/index
```
> fix(route): 国家粮食和物资储备局能源储备

- lib/routes/galxe/index.ts
- lib/routes/galxe/namespace.ts
add Galxe route
Close #12354 
```routes
/galxe/quest/MissionWeb3
```
> feat(route): add galxe

- lib/routes/smzdm/product.ts
Close #
```routes
/smzdm/product/zm5vzpe
```
> feat: route of smzdm product

- lib/routes/telegram/channel.ts
Close #16522
```routes
/telegram/channel/vtbcyan
/telegram/channel/jia0_sub
/telegram/channel/capoo_sub
```
```
fix(route/telegram/channel): invisible images in albums and Link Preview
Some have reported that a recent upgrade of RSSHub broke the
/telegram/channel route, resulting in images from Link Preview (Instant
View) or albums not being displayed, even when showLinkPreview
explicitly or implicitly (by default) enabled.
This is a REGRESSION introduced in
edfaed1b7da1a2599dbbdcda861397b9f08101ec.
The patch fixes it.
Signed-off-by: Rongrong <i@rong.moe>
```
> fix(route/telegram/channel): invisible images in albums and Link Preview

- lib/routes/eastmoney/report/index.ts
- lib/routes/eastmoney/templates/stock_description.art
- lib/routes/eastmoney/utils.ts
Close #16504
```routes
/eastmoney/report/strategyreport
/eastmoney/report/macresearch
/eastmoney/report/brokerreport
/eastmoney/report/industry
/eastmoney/report/stock
```
> feat(route/eastmoney): 增加支持东方财富类型为个股研报的研究报告

- lib/routes/link3/events.ts
- lib/routes/link3/namespace.ts
- lib/routes/link3/profile.ts
add Link3 Route: events, profile
Close #12868 
```routes
/link3/events
/link3/profile/argongamefi
```
> feat(route): add Link3

- lib/routes/wchscu/namespace.ts
- lib/routes/wchscu/recruit.ts
Close #
```routes
/wchscu/recruit
```
> feat(route): add route for recruit notice of West China Hospital

- Dockerfile
Close #16470
```routes
NOROUTE
```
> fix: add missing curl to docker image

- lib/routes/xidian/gr.ts
None
```routes
/xidian/gr/home_zxdt
/xidian/gr/home_tzgg1
/xidian/gr/home_jzbg
/xidian/gr/yyjs_jbqk
/xidian/gr/yyjs_jbqk1
/xidian/gr/yyjs_jbqk2
/xidian/gr/yyjs_jbqk3
/xidian/gr/yyjs_jbqk4
/xidian/gr/yjsy
/xidian/gr/yjsy_yjszs
/xidian/gr/yjsy_bsyjszs
/xidian/gr/yjsy_qtlxzs
/xidian/gr/pygl
/xidian/gr/pygl_xsxw
/xidian/gr/pygl_zyxw
/xidian/gr/pygl_jxgl
/xidian/gr/pygl_jxgl1
/xidian/gr/pygl_jxgl2
/xidian/gr/pygl_jxgl3
/xidian/gr/pygl_bslc
/xidian/gr/xwsy
/xidian/gr/xwsy_tzgg
/xidian/gr/xwsy_gzzd
/xidian/gr/xwsy_swmd
/xidian/gr/xwsy_zlxz
```
> feat(route): add route for gr.xidian.edu.cn

- lib/routes/xidian/cs.ts
- lib/routes/xidian/namespace.ts
None
```routes
/xidian/cs/xyxw
/xidian/cs/tzgg
/xidian/cs/jlhz1
/xidian/cs/rsrc
/xidian/cs/bkjy_jxxw
/xidian/cs/yjsjy_yjstz
/xidian/cs/jyzhaop
```
add route for cs.xidian.edu.cn && fix url of namespace
> feat(route): add route for cs.xidian.edu.cn && fix url of namespace

- lib/routes/ustc/scms.ts
None
```routes
/ustc/scms
/ustc/scms/kydt
/ustc/scms/tzgg
/ustc/scms/xshd
/ustc/scms/ynxw
```
因为网站结构相似，大幅使用了数学与科学学院（[ustc/math.ts](https://github.com/DIYgod/RSSHub/blob/master/lib/routes/ustc/math.ts)）的代码，特此感谢@ne0-wu 同学
--------------------
Due to the similarity of the website structure, I have made extensive use of the code from the School of Mathematical Sciences USTC ([ustc/math.ts](https://github.com/DIYgod/RSSHub/blob/master/lib/routes/ustc/math.ts)). Special thanks to @ne0-wu for this.
> feat(route/ustc): add School of Chemistry and Materials Science

- lib/routes/xidian/cs.ts
- lib/routes/xidian/gr.ts
- lib/routes/xidian/jwc.ts
- lib/routes/xidian/namespace.ts
> fix: update urls for xidian

- lib/routes/twitter/api/index.ts
- lib/routes/twitter/api/web-api/api.ts
- lib/routes/twitter/api/web-api/constants.ts
- lib/routes/twitter/home-latest.ts
Close #
```routes
/twitter/home_latest
```
/twitter/home
This endpoint was for Twitter's recommended timeline, not the timeline of users you follow.
I have implemented the route to retrieve the timeline of users you follow.
> feat(twitter): add twitter getHomeLatestTimeline

- lib/routes/questn/community.ts
- lib/routes/questn/events.ts
- lib/routes/questn/namespace.ts
- lib/routes/questn/util.ts
1. Add Route: community, events
2. Add utility file to parse filter string
3. Add QuestN namespace
Close #12887 
```routes
/questn/events
/questn/events/chain_filter=1
/questn/events/chain_filter=324&reward_filter=200&status_filter=400
/questn/community/questn
```
> feat(route): add QuestN

- lib/routes/szse/rule.ts
Close #16532
```routes
/szse/rule/allrules/bussiness
```
> feat(route): add 深圳证券交易所本所业务规则

- package.json
- pnpm-lock.yaml
> revert: "chore(deps-dev): bump msw from 2.3.5 to 2.4.0"

- lib/routes/github/activity.ts
Close #
```routes
/github/activity/DIYgod
```
Try to fix the error from the Follow
```
invalid byte sequence for encoding "UTF8": 0xb7
```
> fix: clean github activity output

- lib/routes/hust/gs.ts
- lib/routes/hust/namespace.ts
Close #16582
```routes
/hust/gs/xwdt
```
> feat(route): add 华中科技大学研究生院

- lib/routes/gov/cbirc/index.ts
Close #16561
```routes
/gov/cbirc/915
```
> feat(route): add 国家金融监督管理总局

- lib/routes/picnob/user.ts
Close #
```routes
/picnob/user/bugcat_capoo
```
> fix(route/picnob/user): missing linebreak

- lib/routes/sis001/author.ts
- lib/routes/sis001/common.ts
> fix(route): tidy sis001 articles

- lib/routes/agri/index.ts
- lib/routes/agri/namespace.ts
- lib/routes/agri/templates/description.art
Close #16597
```routes
/agri/zx/zxfb
```
> feat(route): add 中国农业农村信息网

- lib/routes/sis001/common.ts
> fix(route): update chapter name style of sis001 article

- lib/routes/sis001/common.ts
> fix(route): fix wrong trimming for some sis001 articles

- lib/routes/taoguba/blog.ts
- lib/routes/taoguba/index.ts
Close #
```routes
/taoguba/blog/1278795
```
> fix(taoguba): response url is null

- lib/routes/sjtu/namespace.ts
- lib/routes/sjtu/seiee/index.ts
- lib/routes/sjtu/seiee/namespace.ts
Close #
```routes
/sjtu/seiee/xzzx_notice_gjjl
/sjtu/seiee/xzzx_notice_bks/38/xzzx_notice_bks_cat2
/sjtu/seiee/xzzx_notice_bks/38
/sjtu/seiee/xzzx_notice_yjs/39
```
> feat(route/sjtu/seiee): New site support

- lib/routes/chlinlearn/daily-blog.ts
Close #
```routes
/chlinlearn/daily-blog
```
源站添加了加密相关Header验证，更新路由
> update: source site add crypto in header

- lib/routes/xueqiu/cookies.ts
Close #
```routes
/xueqiu/user/8152922548
```
> fix(route): use acw sc v2 utils

- lib/routes/go/namespace.ts
- lib/routes/go/niid/idwr-dl.ts
Close #16639
```routes
/go/niid/idwr-dl
```
> feat(route): add 国立感染症研究所感染症発生動向調査週報ダウンロード

- lib/routes/xueqiu/favorite.ts
Close #
```routes
/xueqiu/favorite/8152922548
```
> fix(route/xueqiu): show user name instead

- lib/routes/sis001/common.ts
Close #
```routes
```
Some RSS readers such as [FreshRSS](https://github.com/FreshRSS/FreshRSS) and [Miniflux](https://github.com/miniflux/v2) remove all the inline styles from `<p>` tags. This PR wraps the tags with `<center>` for better compatibility.
> fix(route): add center tag to sis001 articles

- lib/routes/luma/index.ts
- lib/routes/luma/namespace.ts
Add lu.ma route to support 3 kind:
1. calendar
2. event
3. discover-place
Close #
```routes
/luma/warsawblockchainweek
/luma/mpw062ev
/luma/bangkok
```
> feat(route): add lu.ma

- lib/routes/bestblogs/feeds.ts
- lib/routes/bestblogs/namespace.ts
Close #
```routes
/bestblogs/feeds
/bestblogs/feeds/featured
/bestblogs/feeds/programming
/bestblogs/feeds/ai
/bestblogs/feeds/product
/bestblogs/feeds/business
```
- [x [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
> feat(route): 添加BestBlogs.dev文章路由

- lib/routes/the/index.ts
Close #
```routes
/the
/the/category/rawj7o4ypewv94
/the/category/rawbcvxkktdkq8
/the/category/rawtn8jpsc6uvv
/the/category/rawrsnh9zakqdx
/the/category/raw4krvx85dh27
```
> fix(route/the): Always use the first page to get the latest result

- lib/routes/go/mhlw/pdf.ts
Close #16638
```routes
/go/mhlw/pdf/stf/seisakunitsuite/bunya/houkokusuunosuii
```
> feat(route): add 厚生労働省PDF

- lib/routes/github/activity.ts
Close #
```routes
/github/activity/antfu
```
> fix(github activity): only replace relative link

- lib/routes/rss3/index.ts
N/A
```routes
/rss3/vitalik.eth
```
> fix: remove address in rss3 content if html render existed

- lib/routes/chikubi/index.ts
- lib/routes/chikubi/namespace.ts
- lib/routes/chikubi/utils.ts
Close #
```routes
/chikubi
/chikubi/best
/chikubi/video
/chikubi/vr
/chikubi/comic
/chikubi/voice
/chikubi/cg
```
Better categorization (than website) and content fetching.
This is my first pull request, please let me know if I've made any mistakes.
> feat(route): add route for chikubi.jp

- package.json
- pnpm-lock.yaml
N/A
```routes
/rss3/vitalik.eth
```
> chore: update rss3/sdk

- lib/routes/apnews/api.ts
Close #
```routes
/apnews/api?limit=1
/apnews/api/general-news?limit=1
```
> feat(route/apnews): Add support for API

- lib/routes/kakuyomu/namespace.ts
- lib/routes/kakuyomu/types.ts
- lib/routes/kakuyomu/works.ts
Close #
```routes
/kakuyomu/works/1177354054894027232
```
> feat(route): kakuyomu

- lib/middleware/template.tsx
Close #
```routes
/xiaoyuzhou/podcast/5e280faf418a84a0461fc02d?format=json
```
For podcasts, the cover image is not included in the JSON format.
https://github.com/RSSNext/follow-server/pull/73
> fix: fill image from itunes_item_image

- lib/errors/index.test.ts
- lib/middleware/template.tsx
- lib/views/json.ts
- package.json
- pnpm-lock.yaml
Close #
```routes
/xiaoyuzhou/podcast/5e280faf418a84a0461fc02d?format=json
```
- downgrading `msw` to 2.4.3 since 2.4.4 bumps `@mswjs/interceptors` which breaks tests. [Related issue](https://github.com/mswjs/msw/issues/2273).
- revert #16694 and implement it in JSON feed template instead. /cc: @hyoban
> test: fix tests

- lib/routes/follow/profile.ts
Close #
```routes
/follow/profile/41279032429549568
```
> fix(route/follow): add feed image and fix radar rules

- lib/routes/xiaohongshu/user.ts
Close #15631, Close #15232
```routes
```
Due to the dynamic nature of the `noteCard.cover?.infoList?.[0]?.url` in the previous guid rules, which changes based on the current request time, it may cause some software to repeatedly remind users to update, thus it needs to be removed.
由于之前的 guid 规则中的 noteCard.cover?.infoList?.[0]?.url 路径是根据当前请求的时间动态变化的，可能导致一些软件重复提醒更新，因此需要移除。
below is the noteCard JSON and the demo link is [xiaohongshu user 593032945e87e77791e03696 notes ](https://rsshub.flyneko.com/xiaohongshu/user/593032945e87e77791e03696/notes)
下面是 noteCard 的结构， demo 链接可查看  [xiaohongshu user 593032945e87e77791e03696 notes ](https://rsshub.flyneko.com/xiaohongshu/user/593032945e87e77791e03696/notes) ，每次请求的图片地址都在变化
``` json
{
"noteId": "", …
```
> ‌fix(xiaohongshu): The guid rule will dynamically update based on the request time.

- README.md
Close #
```routes
NOROUTE
```
Update readme wordings. /cc @azuic
> docs: update readme wordings

- lib/views/index.tsx
Close #
```routes
NOROUTE
```
Rewording.
> docs: rewording instance homepage

- README.md
Close #
```routes
NOROUTE
```
/cc @azuic
> docs: change special thanks layout

- lib/routes/bilibili/followings-video.ts
Add logger to handle error codes returned by the Bilibili API. If the response code is -6 or 4100000, it throws a ConfigNotFoundError. Otherwise, it throws an error with the corresponding error code and message.
Close #16716
```routes
/bilibili/followings/video/2267573
```
> fix(route/bilibili): add logger to handle error codes

- lib/routes/bilibili/bilibili-recommend.ts
Close #
```routes
/bilibili/precious
```
哔哩哔哩入站必刷
[https://www.bilibili.com/v/popular/history](https://www.bilibili.com/v/popular/history)
> feat(route/bilibili): 哔哩哔哩入站必刷

- lib/routes/bilibili/dynamic.ts
Close #
```routes
/bilibili/user/dynamic/1629347259/hideGoods=1
```
目标是从rss feed中隐藏带有“UP主的推荐”带货信息的动态，尽管不是所有广告动态都带有带货信息。
代码核心实际上只有一句`.filter(...)`，后续的改动是格式化导致的。
> feat(route/bilibili): add `hideGoods` for dynamic

- lib/routes/twitter/tweet.ts
None
```routes
/twitter/tweet/HoDaRaKe/status/1834158092986319190/original
```
When get tweet with params original, the response throw error
```json
{
"error": {
"message": "config is not defined"
}
}
```
Because the that check `config.isPackage` in the code, but config not import
> fix(twitter): tweet throw "config not defined error" when original response

- lib/routes/zaobao/util.ts
Close #16580
```routes
/zaobao/realtime/world
```
> fix(router): zaobao empty router

- lib/routes/twitter/api/mobile-api/login.ts
- lib/routes/twitter/api/web-api/login.ts
None
```routes
NOROUTE
```
The env `TWITTER_AUTHENTICATION_SECRET` is optional in document, but is required in the code, I think that can be optional, because not everyone use 2FA
> fix(twitter): twitter authentication secret is optional

- lib/routes/weibo/super-index.ts
Close #16708
```routes
/weibo/super_index/100808fd6368939ece71fad62c366cfafc250f/sort_time
/weibo/super_index/1008084989d223732bf6f02f75ea30efad58a9/sort_time
```
对比了超话返回的数据，发现rsshub给出的事例数据和我要查询的数据结构又一些不同，
在源码中解析的数据是在`card.card_group`中，但是我今天尝试使用另外一个超话，提示数据为空，需要解析的数据是在最外层
> fix: 微博超话数据解析错误

- lib/routes/people/index.ts
Close #16734
```routes
/people
/people/sc
/people/opinion/8213/49160/49219
```
> fix(route): people charset decoding (#16734)

- lib/routes/zhihu/zhuanlan.ts
Close #
```routes
/zhihu/zhuanlan/c_1682816884766998528
```
> fix(route/zhihu): Use signed header when fetching zhuanlan articles to prevent scrambled text.

- lib/routes/pku/bbs/hot.ts
Close #
```routes
/pku/bbs/hot
```
> fix: fix pku bbs url error

- lib/routes/apnews/api.ts
- lib/routes/apnews/sitemap.ts
Close #
```routes
/apnews/api
```
> feat(route/apnews): Enhance parsing when not fetching full text.

- lib/routes/meishichina/index.ts
- lib/routes/meishichina/namespace.ts
Close #16695
```routes
/meishichina/recipe/最新推荐
```
> feat(route): add 美食天下菜谱

- lib/routes/apnews/api.ts
- lib/routes/apnews/rss.ts
- lib/routes/apnews/sitemap.ts
- lib/routes/apnews/topics.ts
Close #
```routes
/apnews/api
/apnews/api?mode=fulltext
/apnews/topics/ap-top-news?mode=fulltext
/apnews/sitemap/ap-sitemap-latest
/apnews/sitemap/ap-sitemap-latest?mode=fulltext
```
> fix(route/apnews): Prevent fetching fulltext by default to alleviate 403 error.

- lib/routes/jjwxc/book.ts
Close #16759
```routes
/jjwxc/book/4411057
```
> fix(route): 增加锁章检测

- lib/config.ts
- lib/errors/index.tsx
- lib/middleware/logger.ts
- lib/utils/otel/metric.ts
Close #
```routes
NOROUTE
```
1. Due to [routePath](https://hono.dev/docs/api/request#routepath)  metrics should use `routePath` instead of `path`
2. Add `OTEL_SECONDS_BUCKET` and `OTEL_MILLISECONDS_BUCKET` to customize bucket range, it might be helpful while debug some issue
> chore: otel fix and enhancement

- lib/routes/abc/index.ts
Close #16605
```routes
/abc
```
> fix(route): 日期直接从dates对象中获取

- lib/routes/douban/movie/coming.ts
- lib/routes/douban/templates/movie_coming.art
Close #
```routes
/douban/movie/coming
```
https://movie.douban.com/coming 页面的RSS，使用API来获取信息
> feat(route): 添加豆瓣电影-即将上映

- lib/config.ts
- lib/routes/malaysiakini/index.ts
- lib/routes/malaysiakini/namespace.ts
Close #
```routes
/malaysiakini/en
/malaysiakini/en/news
/malaysiakini/en/columns
/malaysiakini/en/letters
/malaysiakini/my
/malaysiakini/my/news
/malaysiakini/my/columns
/malaysiakini/my/letters
/malaysiakini/zh
/malaysiakini/zh/news
/malaysiakini/zh/columns
/malaysiakini/zh/letters
```
> feat(route): add malaysiakini.com

- lib/routes/tju/cic/index.ts
- lib/routes/tju/news/index.ts
- lib/routes/tju/oaa/index.ts
Close #
```routes
/tju/yzb/notice
/tju/yzb/master
/tju/yzb/doctor
/tju/yzb/job
/tju/cic/news
/tju/cic/notification
/tju/cic/forum
/tju/news/focus
/tju/news/general
/tju/news/internal
/tju/news/media
/tju/news/picture
/tju/oaa/news
```
对原有TJU 天津大学路由进行bug进行修改
> fix(route): update route of TJU

- lib/routes/pixivision/index.ts
- lib/routes/pixivision/namespace.ts
- lib/routes/pixivision/utils.ts
Close #
```routes
/pixivision/en
/pixivision/zh
/pixivision/zh-tw
/pixivision/ko
/pixivision/ja
/pixivision/ja/illustration
/pixivision/ja/manga
/pixivision/ja/novels
/pixivision/ja/cosplay
/pixivision/ja/music
/pixivision/ja/goods
/pixivision/ja/how-to-draw
/pixivision/ja/draw-step-by-step
/pixivision/ja/textures
/pixivision/ja/art-references
/pixivision/ja/how-to-make
/pixivision/ja/recommend
/pixivision/ja/interview
/pixivision/ja/column
/pixivision/ja/news
/pixivision/ja/deskwatch
/pixivision/ja/try-out
```
> feat(route): add route for pixivision

- lib/routes/soundon/namespace.ts
- lib/routes/soundon/podcast.ts
- lib/routes/soundon/types.ts
Close #
```routes
/soundon/p/33a68cdc-18ad-4192-84cc-22bd7fdc6a31
```
> feat(route): soundon

- lib/routes/theinitium/app.ts
- lib/routes/theinitium/templates/description.art
Close #
```routes
```
Related to #16762, but that issue should not be closed yet as this route only provides an alternative rather than fixing the issue.
> feat(route): add /app route for 端传媒

- lib/routes/ccfa/index.ts
- lib/routes/ccfa/namespace.ts
- lib/routes/ccfa/templates/description.art
Close #16749
```routes
/ccfa/1
```
> feat(route): add 中国连锁经营协会

- lib/routes/devtrium/namespace.ts
- lib/routes/devtrium/posts.ts
Close #
```routes
/devtrium/
```
> feat(route): add route of devtrium

- lib/routes/withgoogle/explorables.ts
- lib/routes/withgoogle/namespace.ts
Close #
```routes
/withgoogle/explorables
```
> feat(route): Add PAIR - AI Exploreables

- lib/routes/sdu/cs.ts
Close #
```routes
/sdu/cs/announcement
/sdu/cs/academic
/sdu/cs/technology
/sdu/cs/undergraduate
/sdu/cs/postgraduate
```
> feat(route): add 山东大学计算机科学与技术学院相关通知

- lib/routes/weibo/oasis/user.ts
Close #
```routes
/weibo/oasis/user/1990895721
```
感觉这个名字会和另一个路由「博主」混在一起造成迷惑，看路径和 URL 应该是微博下面的一个平台「绿洲」的内容。
> chore(route/weibo): change the name from "用户" to "绿洲用户"

- lib/routes/sdu/cs/index.ts
Close #
```routes
/sdu/cs/index/announcement
/sdu/cs/index/academic
/sdu/cs/index/technology
/sdu/cs/index/undergraduate
/sdu/cs/index/postgraduate
```
山东大学计算机科学与技术学院下除首页通知外，还额外有研究生工作网站及本科生工作网站。因此将原`/sdu/cs`路径下的首页通知移至`/sdu/cs/index`
> fix(route): update route 山东大学-计算机科学与技术学院-首页通知

- lib/routes/weibo/user.ts
Close #
```routes
/weibo/user/7563181945/showRetweeted=0
```
Allow an empty RSS response when the feed is empty.
> fix(route/weibo): set allowEmpty to true in return

- lib/routes/oct0pu5/namespace.ts
- lib/routes/oct0pu5/rss.ts
Close #16804
```routes
/oct0pu5
```
> feat(route): add route of Oct的小破站

- lib/routes/swjtu/scai/bks.ts
Close #
```routes
/swjtu/scai/bks
```
> feat(route): add 西南交通大学计算机学院本科生教育

- lib/routes/asus/bios.ts
Close #16825
```routes
/asus/bios/ProArt-X670E-CREATOR-WIFI
/asus/bios/ProArt-X670E-CREATOR-WIFI/zh
/asus/bios/ProArt-X670E-CREATOR-WIFI/en
```
> feat(route/asus): 华硕 BIOS 路由增加国外访问 API 地址

- lib/routes/cls/subject.ts
- lib/routes/cls/templates/description.art
Close #16827
```routes
/cls/subject/1151
```
> feat(route): add 财联社话题

- lib/routes/weibo/user.ts
Close #
```routes
/weibo/user/6827625527
```
radar适配微博pc站域名`weibo.com`
> fix(radar): add weibo.com for weibo radar

- lib/routes/sdu/cs/yjsgz.ts
- lib/routes/sdu/qd/xyb.ts
Close #
```routes
/sdu/cs/yjsgz/zytz
/sdu/cs/yjsgz/gsl
/sdu/qd/xyb/gztz
```
网站需要校园内网环境访问，经内网部署测试正常
> feat(route): add 山东大学CS学院研究生工作网站及青岛校区学科建设与研究生教育办公室

- lib/routes/asus/bios.ts
- lib/routes/asus/templates/bios.art
Close #16825
```routes
/asus/bios/ProArt-X670E-CREATOR-WIFI
```
> fix(route): asus bios global url

- lib/routes/deeplearning/thebatch.ts
Close #16867
```routes
/deeplearning/thebatch
```
> fix(route): deeplearning

- lib/routes/obsidian/namespace.ts
- lib/routes/obsidian/publish.ts
- lib/routes/obsidian/utils.ts
Close #
```routes
/obsidian/publish/marshallontheroad
```
对于Obsidian Publish，需要Vault的作者给每一篇md的文档属性添加相关属性，否则作用不大
> feat(route): add route of obsidian publish

- lib/routes/4ksj/forum.ts
Close #
```routes
/4ksj/4k-uhd-1
```
> fix(route): 4ksj cookie check

- lib/routes/follow/profile.ts
- lib/routes/follow/types.ts
Close #
```routes
/follow/profile/41279032429549568
```
adapt the route for the `list` subscription type
> fix(route/follow): adapt the `list` subscription

- lib/routes/pku/bbs/hot.ts
原有的帖子URL拼接逻辑错误的使用了new URL函数，但少了一个/，导致结尾的v2字符串在拼接时丢失。
Close #
```routes
/pku/bbs/hot
```
> fix(route): fix URL concatenation of PKU BBS posts

- lib/routes/chikubi/category.ts
- lib/routes/chikubi/index.ts
- lib/routes/chikubi/namespace.ts
- lib/routes/chikubi/navigation.ts
- lib/routes/chikubi/nipple-video-category.ts
- lib/routes/chikubi/nipple-video-maker.ts
- lib/routes/chikubi/search.ts
- lib/routes/chikubi/tag.ts
- lib/routes/chikubi/utils.ts
Close #
```routes
/chikubi
/chikubi/best
/chikubi/video
/chikubi/vr
/chikubi/comic
/chikubi/voice
/chikubi/cg
/chikubi/tag/ドリームチケット
/chikubi/category/nipple-lesbian
/chikubi/nipple-video-category/cat-nipple-video-god
/chikubi/nipple-video-maker/nipple-video-maker-nh
/chikubi/search/ギャップ
```
> feat(route/chikubi): refactor URL fetching and add new routes

- lib/routes/deepin/thread.ts
```routes
/deepin/threads/latest
/deepin/threads/hot
```
> feat(route): add deepin thread list

- lib/config.ts
- lib/routes/uestc/bbs.ts
- lib/routes/uestc/namespace.ts
Close #
```routes
/uestc/bbs
/uestc/bbs/newthread
```
需要配置对应的环境变量
> feat: add route of uestc bbs

- lib/routes/ncku/csie.ts
Close #
```routes
/ncku/csie/_all
/ncku/csie/normal
/ncku/csie/bachelorAdmission
/ncku/csie/masterAdmission
/ncku/csie/speeches
/ncku/csie/awards
/ncku/csie/scholarship
/ncku/csie/jobs
```
update radar rules
> fix(route): update radar in ncku/csie

- lib/routes/scmp/utils.ts
Close #
```routes
/scmp/91
```
> fix(route/scmp): Replace got to obtain url from response

- lib/routes/pornhub/model.ts
- lib/routes/pornhub/pornstar.ts
- lib/routes/pornhub/users.ts
Close #
```routes
/pornhub/model/changhsumath
```
Change image url to Follow better display
> refactor: change PornHub rss image

- lib/routes/ncku/namespace.ts
- lib/routes/ncku/phys.ts
Close #
```routes
/ncku/phys/_all
/ncku/phys/24
/ncku/phys/scholarship
/ncku/phys/admission
/ncku/phys/course-announcement
/ncku/phys/bachelor-announcement
/ncku/phys/master-announcement
/ncku/phys/graduation
/ncku/phys/student-guide
/ncku/phys/honor
/ncku/phys/career
/ncku/phys/others
```
> feat(route): New Route to NCKU Phys

- lib/routes/lovelive-anime/namespace.ts
- lib/routes/lovelive-anime/news.ts
- lib/routes/lovelive-anime/schedules.ts
- lib/routes/lovelive-anime/templates/description.art
- lib/routes/lovelive-anime/templates/scheduleDesc.art
- lib/routes/lovelive-anime/topics.ts
~~Close #~~
```routes
/lovelive-anime/news
/lovelive-anime/news/detail
/lovelive-anime/news/nijigasaki
/lovelive-anime/news/nijigasaki/detail
/lovelive-anime/news/nijigasaki/goods
/lovelive-anime/news/nijigasaki/goods/detail
```
The LoveLive! Series official website has undergone significant updates since the last maintenance of this route. This PR aims to support crawling the latest version of the official website by utilizing its API, and allows specifying sub-projects and categories as optional parameters.
> feat(route): Fix and update LoveLive! Series News

- lib/routes/yande/namespace.ts
- lib/routes/yande/post.ts
Close #
```routes
/yande/post/popular_recent
/yande/post/popular_recent/1d
/yande/post/popular_recent/1w
/yande/post/popular_recent/1m
/yande/post/popular_recent/1y
```
This PR is based on commit 984448a
> fix(yande): update namespace and route details

- lib/routes/bjnews/cat.ts
Close #
```routes
/bjnews/cat/depth?limit=3
```
> fix(route/bjnews): Add concurrent request throttling

- lib/routes/zhihu/timeline.ts
Close #
```routes
/zhihu/timeline
```
> feat(route/zhihu): Remove filter from timeline

- lib/routes/fediverse/timeline.ts
Close #
```routes
/fediverse/timeline/Mastodon@mastodon.social
```
部分RSS阅读器（如Miniflux）不能正确处理title中的HTML标签，生成时将其移除。
> fix(route/fediverse): Remove html tag from title

- lib/routes/xueqiu/stock-info.ts
Close #
```routes
/xueqiu/favorite/8152922548
```
> fix(route/xueqiu): use item.target as link

- lib/routes/apple/podcast.ts
Close #16952
```routes
/apple/podcast/id1559695855
```
页面结构变更
> fix(route/apple/podcast): Fix broken apple podcast route

- lib/routes/spankbang/namespace.ts
- lib/routes/spankbang/new-videos.ts
- lib/routes/spankbang/templates/video.art
Close #16803
```routes
/spankbang/new_videos
```
> feat(route): spankbang

- lib/routes/gov/moa/moa.ts
- lib/routes/gov/moa/szcpxx.ts
- lib/routes/gov/moa/zdscxx.ts
Close #16955
```routes
/gov/moa/szcpxx
```
> feat(route): add 中华人民共和国农业农村部生猪专题重要政策

- lib/routes/spankbang/new-videos.ts
Close #
```routes
/spankbang/new_videos
```
> fix(route): spankbang use puppeteer

- lib/routes/javtiful/actress.ts
- lib/routes/javtiful/channel.ts
- lib/routes/javtiful/namespace.ts
- lib/routes/javtiful/templates/description.art
- lib/routes/javtiful/utils.ts
Close #
```routes
/javtiful/actress/akari-tsumugi
/javtiful/channel/madonna
```
> feat(route): add route of javtiful

- lib/routes/github/discussions.ts
Close #7461
```routes
/github/discussion/DIYgod/RSSHub
/github/discussion/DIYgod/RSSHub/open
```
> feat(route): add github discussions route

- lib/routes/bangumi/templates/tv/subject.art
- lib/routes/bangumi/tv/user/collections.ts
Close #
```routes
/bangumi/tv/user/collections/Sai/1/1
```
> feat: add a route to Bangumi's user favorites list

- lib/routes/douyin/types.ts
- lib/routes/douyin/user.ts
- lib/routes/douyin/utils.ts
Close #
```routes
/douyin/user/MS4wLjABAAAARcAHmmF9mAG3JEixq_CdP72APhBlGlLVbN-1eBcPqao
/douyin/user/MS4wLjABAAAA9rrLiU9g4LuErLcX2hxFyH-WQk27Kb1lO3TZfXSV5PM
```
> fix(route): douyin

- lib/routes/gov/csrc/csrc.ts
Close #16963
```routes
/gov/csrc/zfxxgk_zdgk/c101971
```
> feat(route): add 中国证券监督管理委员会政府信息公开

- lib/routes/gov/csrc/csrc.ts
Close #16987
```routes
/gov/csrc/zfxxgk_zdgk/c101972
/gov/csrc/zfxxgk_zdgk/c101927
/gov/csrc/zfxxgk_zdgk/c101970
/gov/csrc/zfxxgk_zdgk/c101928
```
> fix(route): 修复中国证券监督管理委员会详情没有链接到正确页面

- Dockerfile
Close #16997 
```routes
/test/1
```
> build(docker): use corepack before setting registry

- lib/routes/zhihu/utils.ts
> fix(route/zhihu): Repair the regex for extracting `__zse_ck`

- lib/routes/huggingface/blog-zh.ts
Close #
```routes
/huggingface/blog-zh
```
- Changed `pubDate` attribute from `item.blog.date` (which doesn't exist in the parsed JSON) to `item.blog.publishedAt` to correctly capture a blog's publication date.
> fix(route/huggingface): sanitize pubDate to capture correct blog publication date

- lib/routes/zhihu/activities.ts
> fix(route/zhihu): Sanitize the title when parsing "pins" with links.

- lib/routes/cohere/index.ts
- lib/routes/cohere/namespace.ts
Close #
```routes
/cohere/blog
```
The blog is hosted on Ghost, allowing us to fetch content via their API. However, the current API key is subject to change.
Trade-offs:
- Current method: More data, but relies on a potentially unstable API key
- Alternative: Limited data, but more stable implementation
> feat: add cohere blog route

- lib/routes/follow/profile.ts
- lib/routes/follow/types.ts
Close #
```routes
/follow/profile/41279032429549568
```
filter `inbox` subscriptions
> fix(route/follow): filter `inbox`

- lib/routes/hust/mse.ts
Close #17033
Close #17034
```routes
/hust/mse/sylm/tzgg
/hust/mse/rcpy/xsg_z
```
> feat(route): add 华中科技大学机械科学与工程学院

- lib/config.ts
- lib/routes/lorientlejour/index.ts
- lib/routes/lorientlejour/namespace.ts
- lib/routes/lorientlejour/templates/description.art
Close #
```routes
/lorientlejour/977-lebanon
/lorientlejour/1-liban
/lorientlejour/752-middle-east
/lorientlejour/7-moyen-orient-et-monde
```
> feat: Add L'Orient-Le Jour Route

- lib/routes/hellogithub/index.ts
- lib/routes/hellogithub/report.ts
Close #
```routes
/hellogithub/volume
/hellogithub/month
/hellogithub/ranking
/hellogithub/report
/hellogithub/home
```
接口变更
> fix: update route HelloGitHub

- lib/utils/cache/redis.ts
Close #
```routes
/test/1
```
Intentionally store the cache time `maxAge` of the cache key `getCacheTtlKey(key)` in the cache with expiry `maxAge` which is introduced in #9227.
https://github.com/DIYgod/RSSHub/blob/9b144a715f1dba63c508930de336c7873642f71b/lib/utils/cache/redis.ts#L70 does the actual storing of content
revert part of 9b144a715f1dba63c508930de336c7873642f71b
/cc: @DIYgod
> fix(cache): store cache TTL

- lib/routes/lorientlejour/index.ts
Close #
```routes
/lorientlejour/977-Lebanon
/lorientlejour/1-liban
/lorientlejour/977-lebanon|1-liban
```
Fixed the issue of which the limit parameter is not passed to the API and added the functionality of passing JSON-encoded array of category IDs to the API
> feat(route/lorientlejour): fix limit query and add multiple categories functionality

- lib/routes/lorientlejour/index.ts
Close #
```routes
/lorientlejour/977-Lebanon
/lorientlejour/1-liban
/lorientlejour/977-lebanon|1-liban
```
For some reason the API would not return articles in subcategories when the category parameter is an array (even with includeSubcategories parameter), added code to lookup for subcategories to add to the array before sending it to the API to match functionality
> fix(route/lorientlejour): fix subcategories

- lib/routes/news/namespace.ts
Close #
```routes
/news/xhsxw
```
> docs: news.cn namespace change to 新华社

- lib/routes/bangumi/tv/other/followrank.ts
Close #
```routes
/bangumi/tv/followrank
/bangumi/anime/followrank
/bangumi/book/followrank
/bangumi/music/followrank
/bangumi/game/followrank
/bangumi/real/followrank
```
> fix(route/bangumi): update follow rank parsing logic

- lib/routes/fanbox/index.ts
- lib/routes/fanbox/types.ts
Close #
```routes
/fanbox/official
```
> fix(route): update fanbox

- lib/routes/xueqiu/cookies.ts
Close #
```routes
/xueqiu/user/3058599833
/xueqiu/stock_info/SZ000002
/xueqiu/favorite/8152922548
/xueqiu/hots
/xueqiu/today
```
雪球相关cookie获取需要修改成
acw_sc__v2=670713f02ba34463e198158dc40a6230adb278a2; xq_a_token=dbc1dc6d13bd101dd06f18c5b7f2fb2eb276fb5a
样式才能正常获取数据
> feat(roure): fix xueqiu relateroute

- lib/routes/misskey/utils.ts
Close #
```routes
/misskey/users/notes/iggy@misskey.io
```
> feat(misskey): Include file attachments in user notes API request

- lib/middleware/template.tsx
Close #
```routes
NOROUTE
```
When using https://docs.rsshub.app/routes/other#transformation-html to convert site to html, an `Invalid Date` may be obtained, causing the content to be unable to be returned.
> fix: catch Invalid Date

- lib/routes/oncc/templates/article.art
Close #
```routes
/oncc/zh-hant/news
/oncc/zh-hans/commentary
/oncc/zh-hant/intnews
```
The existing art-template will output description with the content of HTML escaped. Fixed in accordance to https://aui.github.io/art-template/docs/syntax.html#Raw-output.
> fix(route/oncc): fix art-template

- lib/routes/uestc/gr.ts
- lib/routes/uestc/jwc.ts
Close #
```routes
/uestc/jwc
/uestc/jwc/important
/uestc/jwc/student
/uestc/jwc/teacher
/uestc/jwc/teaching
/uestc/jwc/office
/uestc/gr
/uestc/gr/important
/uestc/gr/teaching
/uestc/gr/degree
/uestc/gr/student
/uestc/gr/practice
```
- jwc 添加了 description
- jwc 更新为具体的 pubDate
- gr 添加了分类参数
> feat(route): update routes for uestc jwc and gr

- lib/routes/gmcmonline/chinacustoms.ts
- lib/routes/gmcmonline/namespace.ts
Close #17080
```routes
/gmcmonline/chinacustoms
```
> feat(route): add 国门传媒在线中国海关

- lib/routes/5eplay/index.ts
Close #17067 
```routes
/5eplay/article
```
fix #17067 
No longer needed acw_sc__v2
> fix(route/5eplay): update data acquisition method

- lib/routes/rsshub/transform/html.ts
Close #
```routes
/rsshub/transform/html/https%3A%2F%2Fbuildui.com%2Fposts/title%3DBuild%20UI%26item%3Dmain%20>%20div%20>%20div%20>%20div%26itemTitle%3Da%26itemLink%3Da%26itemContent%3Darticle
```
https://buildui.com/posts
> feat: extract content

- lib/routes/papers/index.ts
Close #
```routes
/papers/arxiv/cs.RO
```
更新了cool paper 网站的 Robotics RSS，并且 fix 了 cool paper 中 kimi 的路径由 `*/kimi/*` 变为了 `*/kimi?paper=*`
> fix(route): add cool paper Robotics RSS and fix kimi url

- lib/routes/rsshub/transform/html.ts
Close #
```routes
/rsshub/transform/html/https%3A%2F%2Fbuildui.com%2Fposts/title%3DBuild%20UI%26item%3Dmain%20>%20div%20>%20div%20>%20div%26itemTitle%3Da%26itemLink%3Da%26itemContent%3Darticle
/rsshub/transform/html/https%3A%2F%2Fwww.biquge.co%2F8_8081%2F/item%3D%23list%20%3E%20dl%20%3E%20dd%20%3E%20a%26itemContent%3D%23content%26encoding%3Dgbk
```
> feat: encoding option

- lib/routes/bilibili/video.ts
- lib/routes/weibo/user.ts
Close #
```routes
NOROUTE
```
把自己添加到了经常使用的两个 route 的维护者列表内。
> chore: add maintainer in two routes

- lib/routes/cisia/index.ts
- lib/routes/cisia/namespace.ts
Close #17113
```routes
/cisia/12
```
> feat(route): add 中国无机盐工业协会

- lib/routes/famitsu/category.ts
Close #17145
```routes
/famitsu/category/new-article
```
> fix(route): famitsu

- lib/routes/skeb/following-creators.ts
- lib/routes/skeb/following-works.ts
- lib/routes/skeb/friend-works.ts
- lib/routes/skeb/index.ts
- lib/routes/skeb/search.ts
- lib/routes/skeb/works.ts
> docs: fix Skeb route examples and description

- lib/routes/zaobao/util.ts
Close #17150
```routes
/zaobao/interactive-graphics
/zaobao/other/lifestyle/health
/zaobao/znews/china
```
> fix(route/zaobao): update list parsing logic

- lib/routes/aibase/news.ts
- lib/routes/aibase/util.ts
> feat(route): add route aibase/news

- lib/routes/the/index.ts
> fix(route/the): Adjust default limit to get the latest articles

- lib/config.ts
- lib/routes/bilibili/cache.ts
- lib/routes/bilibili/utils.ts
- lib/routes/bilibili/video.ts
Close #16979
```routes
/bilibili/user/video/3816626
```
> fix(route/bilibili): add addDmVerifyInfoWithInter to bypass the risk control mechanism

- lib/routes/twitter/api/mobile-api/login.ts
fix #17089
Close #17089
```routes
/twitter/user/elonmusk/readable=0&authorNameBold=0&showAuthorInTitle=1&showAuthorInDesc=0&showSymbolForRetweetAndReply=0&showRetweetTextInTitle=0&addLinkForPics=1&&heightOfPics=200
```
> fix(route): fix Twitter Username+password login

- lib/routes/straitstimes/index.ts
- lib/routes/straitstimes/namespace.ts
- lib/routes/straitstimes/templates/description.art
Close #
```routes
/straitstimes
/straitstimes/singapore
/straitstimes/asia
/straitstimes/world
/straitstimes/opinion
/straitstimes/life
/straitstimes/business
/straitstimes/jobs
/straitstimes/parenting-and-education
/straitstimes/food
/straitstimes/tech
/straitstimes/sport
/straitstimes/podcasts
/straitstimes/singapore/top-stories
/straitstimes/asia/top-stories
```
> feat(route): add straits times route

- lib/routes/skebetter/illust.ts
- lib/routes/skebetter/index.ts
- lib/routes/skebetter/manga.ts
- lib/routes/skebetter/namespace.ts
- lib/routes/skebetter/utils.ts
Close #
```routes
/skebetter/hot
/skebetter/week
/skebetter/month
/skebetter/latest
/skebetter/illust/hot
/skebetter/illust/week
/skebetter/illust/month
/skebetter/illust/latest
/skebetter/manga/1
/skebetter/manga/2
```
The date format in this API is like `13時間前` and `5日前`, and parseDate returned `Invalid Date`.
So I didn't return pubDate.
> feat(route): add route for skebetter

- lib/routes/ktown4u/artist-brandlist.ts
- lib/routes/ktown4u/namespace.ts
Close #
```routes
/ktown4u/artistBrandlist/234590
/ktown4u/artistBrandlist/234590/1723449
```
没有时区信息，国区网站，默认中国时间
> feat(route): ktown4u

- lib/routes/misskon/namespace.ts
- lib/routes/misskon/posts.ts
- lib/routes/misskon/tag.ts
- lib/routes/misskon/top.ts
- lib/routes/misskon/utils.ts
Close #
```routes
/misskon/tag/cosplay
/misskon/top/3
/misskon/posts
/misskon/posts/search=video&tags_exclude=353,3100&per_page=5
```
- Misskon itself, based on WordPress, provides basic feeds without item content, and this PR aims to provide feeds with content.
- Radar rule for 'search` does not work well. I dont know how to fix it.
> feat(route): MissKON

- lib/routes/infoq/presentations.ts
- lib/routes/infoq/templates/description.art
Close #17134
```routes
/infoq/presentations
```
> feat(route): add InfoQ Presentations

- lib/routes/twitter/api/web-api/utils.ts
N/A
```routes
/twitter/user/elonmusk/readable=0&authorNameBold=0&showAuthorInTitle=1&showAuthorInDesc=0&showSymbolForRetweetAndReply=0&showRetweetTextInTitle=0&addLinkForPics=1&&heightOfPics=200
```
When a cookie is not fetched, it may be due to some other errors (e.g. user-agent, risk control mechanisms), rather than the token being unavailable, so the full token needs to be masked to avoid a leak.
> fix(route/twitter): Mask the error output to avoid leak token

- lib/routes/zjut/cs/index.ts
Close #
```routes
/zjut/cs/53
/zjut/cs/54
/zjut/cs/55
```
> feat(route/zjut): Add 浙江工业大学计算机学院

- lib/routes/apnews/topics.ts
Close #
```routes
/apnews/nav?limit=8
/apnews/nav/politics?limit=8
/apnews/topics?limit=1
/apnews/topics/ap-top-news?limit=1
```
> feat(route/apnews): Expand range of application

- lib/routes/xaut/index.ts
- lib/routes/xaut/namespace.ts
Close #
```routes
/xaut/index/xxxw
/xaut/index/dzys
/xaut/index/ldsr
/xaut/index/cdsy
/xaut/index/xwzz
```
Due to the update of the school's homepage, the old routes are obsolete and need to be updated with new routes
> fix(route/xaut): update new homepage

- lib/routes/tkww/index.ts
- lib/routes/tkww/namespace.ts
Close #
```routes
/tkww
/tkww/hong_kong
/tkww/香港
/tkww/china
/tkww/china/shanghai
/tkww/china/jiangxi
```
> feat(route): add tkww 大公文匯 route

- lib/routes/coolapk/dyh.ts
- lib/routes/coolapk/hot.ts
- lib/routes/coolapk/huati.ts
- lib/routes/coolapk/namespace.ts
- lib/routes/coolapk/toutiao.ts
- lib/routes/coolapk/tuwen.ts
- lib/routes/coolapk/user-dynamic.ts
Close #16715
```routes
/coolapk/huati/iPhone
/coolapk/dyh/3616
/coolapk/hot
/coolapk/toutiao
/coolapk/user/3177668/dynamic
/coolapk/tuwen
```
- Add config `ALLOW_USER_HOTLINK_TEMPLATE` within the document to proxy images.
- Remove duplicate and deprecated route.
> docs: add require config for coolapk

- lib/routes/gov/jgjcndrc/index.ts
Close #17035
```routes
/gov/jgjcndrc/1832739866673426433
```
> fix(route): 中华人民共和国国家发展和改革委员会价格监测中心

- lib/routes/dribbble/keyword.ts
- lib/routes/dribbble/popular.ts
- lib/routes/dribbble/user.ts
- lib/routes/dribbble/utils.ts
Close #17110
```routes
/dribbble/user/google
```
> fix(route): dribbble

- lib/routes/gov/customs/list.ts
- lib/routes/gov/customs/namespace.ts
Close
```routes
/gov/customs/list/fagui
```
> fix(route): customs

- lib/routes/163/music/playlist.ts
Close #13151
```routes
/163/music/playlist/941413834
```
> fix(route): 163

- lib/routes/gameapps/index.ts
- lib/routes/gameapps/templates/description.art
Close #
```routes
/gameapps
```
> fix(route): gameapps

- lib/routes/apnews/sitemap.ts
- lib/routes/apnews/topics.ts
- lib/routes/apnews/utils.ts
Close #
```routes
/apnews/nav/today-in-history?mode=fulltext
```
> feat(route/apnews): Add `gtm` parsing method & misc refactor

- lib/routes/mingpao/index.ts
- lib/routes/mingpao/namespace.ts
Close #
```routes
/mingpao/ins/all
```
> fix(route): mingpao more fancybox

- eslint.config.mjs
- lib/routes/51read/article.ts
- lib/routes/69shu/article.ts
- lib/routes/6v123/utils.ts
- lib/routes/baidu/search.ts
- lib/routes/bangumi/tv/other/followrank.ts
- lib/routes/biodiscover/index.ts
- lib/routes/chikubi/utils.ts
- lib/routes/ecnu/contest.ts
- lib/routes/foreverblog/feeds.ts
- lib/routes/github/pulse.ts
- lib/routes/google/search.ts
- lib/routes/hameln/chapter.ts
- lib/routes/linkedin/utils.ts
- lib/routes/parliament.uk/commonslibrary.ts
- lib/routes/parliament.uk/lordslibrary.ts
- lib/routes/pixivision/index.ts
- lib/routes/smzdm/product.ts
- lib/routes/sogou/search.ts
- lib/routes/syosetu/chapter.ts
- lib/routes/wechat/ershcimi.ts
- lib/routes/withgoogle/explorables.ts
- lib/routes/yilinzazhi/index.ts
- lib/routes/yilinzazhi/latest.ts
> style(eslint): update no-restricted-syntax

- lib/routes/ps/monthly-games.ts
Close #
```routes
/ps/monthly-games
```
> fix(route/ps): monthly-games

- lib/routes/douban/other/topic.ts
Close https://github.com/RSSNext/Follow/issues/1048
```routes
/douban/topic/84494
```
> fix: douban topic item link

- lib/routes/xueqiu/cookies.ts
- lib/routes/xueqiu/favorite.ts
- lib/routes/xueqiu/hots.ts
- lib/routes/xueqiu/stock-info.ts
- lib/routes/xueqiu/today.ts
- lib/routes/xueqiu/user.ts
Close #
```routes
/xueqiu/user/8152922548
```
> fix(route): xueqiu token url

- lib/routes/apnews/api.ts
- lib/routes/apnews/rss.ts
- lib/routes/apnews/sitemap.ts
- lib/routes/apnews/topics.ts
- lib/routes/reuters/common.ts
Close #
```routes
/reuters/world/
/reuters/world/?fulltext=true
```
> fix(route): Correct misuse of `fulltext` query

- lib/routes/douban/people/status.ts
```routes
/douban/people/75118396/status
```
> feat(douban): add description

- lib/routes/alicesoft/infomation.ts
- lib/routes/alicesoft/namespace.ts
Close #
```routes
/alicesoft/information
/alicesoft/information/event
/alicesoft/information/game/cat377
```
> feat(route): add ALICESOFT

- lib/routes/beijingprice/index.ts
Close #17222
```routes
/beijingprice/jgzx/jgzb
```
> fix(route): 北京价格价格早报

- lib/routes/douban/other/topic.ts
```routes
/douban/topic/84494
```
> feat(route/douban): add topic support

- lib/routes/douban/other/topic.ts
- lib/routes/douban/people/status.ts
```routes
/douban/topic/84494
/douban/people/29449961/status
```
> fix(route/douban): remove parameter to avoid duplicate

- lib/routes/69shu/article.ts
- lib/routes/69shu/namespace.ts
Close #17168 
```routes
/69shu/article/51567
```
> fix(route): update 69shuba url

- lib/routes/douban/other/topic.ts
```routes
/douban/topic/11667
```
> fix(route): adjust author name

- lib/routes/beijingprice/index.ts
Close #17258
```routes
/beijingprice/jgzx/jgrb
```
> fix(route): 北京价格价格日报

- lib/config.ts
- lib/routes/sorrycc/index.ts
- lib/routes/sorrycc/namespace.ts
- lib/routes/sorrycc/types.ts
Close #17260 
```routes
/sorrycc
```
> feat(route): sorrycc.com

- lib/config.ts
- lib/routes/sis001/author.ts
- lib/routes/sis001/common.ts
- lib/routes/sis001/forum.ts
- lib/routes/sis001/namespace.ts
Close #
```routes
/sis001/forum/322?baseUrl=https://sis001.com
/sis001/author/13131575?baseUrl=https://sis001.com
```
> fix(route/sis001): add cookie to solve anti-crawler

- .github/workflows/issue-command.yml
Close #17151
```routes
NOROUTE
```
> feat(ci): extend `/test` command functionality for PR testing

- lib/routes/sis001/namespace.ts
> fix(route/sis001): fix namespace description

- lib/routes/zjut/www/index.ts
Close #
```routes
/zjut/www/xsdt_4662
/zjut/www/4527
/zjut/www/4528
/zjut/www/5389
/zjut/www/5390
/zjut/www/xqbc
```
> feat(route/zjut): Add 浙江工业大学首页

- lib/routes/sis001/common.ts
> fix(route/sis001): standardize guid for different base URLs

- lib/routes/sorrycc/index.ts
Close #
```routes
/sorrycc
```
> fix(route/sorrycc): add pubDate

- lib/routes/zjut/www/index.ts
Close #
```routes
/zjut/www/xsdt_4662
/zjut/www/4527
/zjut/www/4528
/zjut/www/5389
/zjut/www/5390
/zjut/www/xqbc
```
> fix(route/zjut): fix the title of 浙江工业大学首页

- lib/routes/bsky/posts.ts
- lib/routes/bsky/utils.ts
Close #
```routes
/bsky/profile/bsky.app
/bsky/profile/bsky.app/filter=posts_with_replies
/bsky/profile/bsky.app/filter=posts_no_replies
/bsky/profile/bsky.app/filter=posts_with_media
/bsky/profile/bsky.app/filter=posts_and_author_threads
```
> feat(bsky): add filter support for profile feeds

- lib/routes/macupdate/app.ts
Close #17291
```routes
/macupdate/app/36087
```
> fix(route): macupdate

- lib/routes/zjut/www/index.ts
Close #
```routes
/zjut/www/xsdt_4662
/zjut/www/4527
/zjut/www/4528
/zjut/www/5389
/zjut/www/5390
/zjut/www/xqbc
```
> fix(route/zjut): fix the date parser of 浙江工业大学首页

- lib/routes/bangumi.tv/other/followrank.ts
Close #
```routes
/bangumi.tv/anime/followrank
```
> refactor(route/bangumi): remove unnecessary type defaulting (#17293)

- lib/routes/tencent/news/author.ts
Close #
```routes
/tencent/news/author/8QMf2XpZ7oIVvzjR
```
Add avatar to tencent news author
> fix: tencent news display author avatar

- lib/utils/ofetch.ts
- package.json
> feat: log redirect

- lib/routes/oup/index.ts
- lib/routes/oup/templates/article.art
Close #12923
```routes
/oup/journals/adaptation
```
> fix(route): oup

- lib/routes/afdian/dynamic.ts
- lib/routes/afdian/explore.ts
Close #
```routes
/afdian/explore/hot/所有
/afdian/dynamic/@afdian
```
> fix(route): update base URL from afdian.net to afdian.com in afdian dynamic and explore routes

- lib/routes/qq/pd/guild.ts
- lib/routes/qq/pd/types.ts
- lib/routes/qq/pd/utils.ts
Close #
```routes
/qq/pd/guild/qrp4pkq01d
/qq/pd/guild/qrp4pkq01d/650967831/created
/qq/pd/guild/qrp4pkq01d/650967831/replied
```
添加腾讯频道路由，支持公开访客访问的频道。
> feat(route/qq): add 腾讯频道 (/qq/pd) route

- lib/routes/lovelive-anime/schedules.ts
- lib/routes/lovelive-anime/topics.ts
Close #
```routes
/lovelive-anime/schedules
/lovelive-anime/topics/otonokizaka
```
> fix(route): fix lovelive-anime topics and schedules route

- lib/routes/chinania/index.ts
- lib/routes/chinania/namespace.ts
Close #16791
```routes
/chinania/xiehuidongtai/xiehuitongzhi
```
> feat(route): add 中国有色金属工业网

- lib/routes/warthunder/news.ts
Close #
```routes
/warthunder/news
```
> fix(route): fix warthunder route pubDate parse

- lib/routes/washingtonpost/app.ts
- lib/routes/washingtonpost/index.ts
- lib/routes/washingtonpost/namespace.ts
- lib/routes/washingtonpost/templates/description.art
Close #
```routes
/washingtonpost/app
/washingtonpost/app/politics
/washingtonpost/app/world
/washingtonpost/app/national
/washingtonpost/app/national/investigations
```
> feat(route): add washingtonpost route

- lib/routes/bilibili/video.ts
Close https://github.com/RSSNext/Follow/issues/1169
```routes
/bilibili/user/video/58078997
```
> fix(bilibili/video): missing image

- lib/routes/theinitium/app.ts
- lib/routes/theinitium/templates/description.art
Close #
```routes
```
- item link is now the theinitium.com link instead of app.theinitium.com link
- will now resolve relative links before returning the item (due to the change in item link)
- will now use WHATWG URL API to …
> fix(route/theinitium): Fix item link for /app route

- lib/routes/eshukan/academic.ts
- lib/routes/eshukan/namespace.ts
- lib/routes/eshukan/templates/description.art
Close #17322
```routes
/eshukan/academic/1
/eshukan/academic/5
```
> feat(route): add 万维书刊网学术资讯

- lib/routes/dedao/articles.ts
Close #
```routes
/dedao/articles/8
/dedao/articles/9
```
新增得到相关路由
> feat(route/dedao): add new dedao route 

- lib/routes/mingpao/index.ts
Close #
```routes
/mingpao/ins/s00005
```
> fix(route): mingpao mixed media

- lib/routes/follow/profile.ts
Close #
```routes
/follow/profile/karasu
/follow/profile/41211157583651840
```
> fix(route/follow): can't search by user handle

- lib/routes/rsshub/transform/html.ts
Close #
```routes
/rsshub/transform/html/https%3A%2F%2Fui.dev%2Fblog/item%3D%23__next%20>%20main%20>%20div%20>%20ul%20>%20li%26itemContent%3D%23__next%20>%20main%20>%20div%20>%20section%20>%20main
```
> fix(transform): cache key

- lib/routes/appstare/comments.ts
- lib/routes/appstare/namespace.ts
Close #
```routes
/appstare/comments/cn/1142110895
```
> feat(route): add appstare

- lib/routes/cookbook/index.ts
- lib/routes/openai/blog.ts
- lib/routes/openai/chatgpt.ts
- lib/routes/openai/cookbook.ts
- lib/routes/openai/research.ts
```routes
/openai/cookbook
```
OpenAI Cookbook provides a wealth of example code on how to use the OpenAI API, covering common tasks such as natural language generation, language translation, and chat dialogue. These examples are suitable for developers of all skill levels, from beginners to experienced users.
> feat(route/cookbook): Add OpenAICookbook

- lib/routes/bilibili/followings-video.ts
Close #
```routes
/bilibili/followings/video/2267573
```
```json
"card": {
"desc": {
"uid": 22170787,
"type": 8,
"rid": 113395089086752,
"acl": 0,
"view": 20243,
"repost": 2,
"comment": 66,
"like": 946,
"is_liked": 0,
"dynamic_id": 994011039036080100,
"timestamp": 1730274630,
"pre_dy_id": 0,
"orig_dy_id": 0,
"orig_type": 0,
"user_profile": {
"info": {
"uid": 22170787,
"uname": "光暗杂学馆",
"face": "http://i1.hdslb.com/bfs/face/a70af92f8b9e5353f6ad5e0189979e3bcfa46a9d.jpg"
},
"card": {
"official_verify": {
"type": -1
}
},
"vip": {
"vipType": 2,
"vipDueDate": 1742140800000,
"dueRemark": "",
"accessStatus": 0,
"vipStatus": 1,
"vipStatusWarn": "",
"themeType": 0,
"label": {
"path": "",
"text": "年度大会员",
"label_theme": "annual_vip",
"text_color": "#FFFFFF",
"bg_style": 1,
"bg_color": "#FB7299", …
```
> fix(route/bilibili): fix followings video bvid path

- lib/routes/bsky/posts.ts
Close #
```routes
/bsky/profile/shud.in
```
> fix(bsky): use avatar for image

- lib/routes/twitter/utils.ts
fix #17382
Close #17382
```routes
/twitter/home_latest
```
> fix(route): 修复 部分情况下 url.expanded_url 可能为 undefined 的问题

- lib/routes/enterprisecraftsmanship/index.ts
- lib/routes/enterprisecraftsmanship/namespace.ts
Close #
```routes
/enterprisecraftsmanship/archives
```
The blog "Enterprise Craftsmanship" by Vladimir Khorikov focuses on software engineering best practices, particularly in Domain-Driven Design (DDD), testing, and architecture. Topics include DDD modeling techniques, handling complex database interactions, and approaches to clean, maintainable code. He also explores principles like encapsulation, managing state, and refining development patterns. For those interested in software craftsmanship and clean architecture, this blog provides in-depth insights and guidance.
“Enterprise Craftsmanship” 是 Vladimir Khorikov 的博客，专注于软件工程最佳实践，尤其是领域驱动设计（DDD）、测试以及架构设计。博客涵盖如何通过 DDD 建模技术来处理复杂数据库交互，优化代码的封装与可维护性。内容深入探讨状态管理、代码简洁性等，为希望提升软件开发工艺的技术人员提供实用的指导。
> feat(route): add enterprisecraftsmanship

- lib/routes/counter-strike/namespace.ts
- lib/routes/counter-strike/news.ts
Close #17366
```routes
/counter-strike/news
```
> feat(route): add Counter Strike News

- lib/routes/enterprisecraftsmanship/index.ts
https://github.com/DIYgod/RSSHub/pull/17371#discussion_r1823617085
```routes
/enterprisecraftsmanship/archives
```
> fix(route): remove `title` from description

- lib/routes/1point3acres/thread.ts
- lib/routes/1point3acres/utils.ts
- lib/routes/counter-strike/news.ts
- package.json
- pnpm-lock.yaml
Close #
```routes
/1point3acres/thread/hot
/counter-strike/news
```
`@bbob/html` allows writing custom a custom renderer for uncommon BBCode tags
> refactor: use bbob instead of bbcodejs (1point3acres)

- lib/routes/zjut/www/index.ts
Close #
```routes
/zjut/www/xsdt_4662
/zjut/www/4527
/zjut/www/4528
/zjut/www/5389
/zjut/www/5390
/zjut/www/4520
/zjut/www/xqbc
```
> fix(route/zjut): filter out items that should not included

- lib/routes/cngold/index.ts
- lib/routes/cngold/namespace.ts
Close #16779
```routes
/cngold/news-325
```
> feat(route): add 中国黄金协会

- lib/routes/nielsberglund/index.ts
- lib/routes/nielsberglund/namespace.ts
Close #
```routes
/nielsberglund/blog
```
Niels Berglund’s blog explores advanced topics in software engineering, particularly in data processing, AI, and cloud technologies. He frequently covers data streaming, Kafka, Azure, SQL Server, and .NET, presenting insights on real-time data architectures and AI applications in data-driven environments.
博客“nielsberglund.com”主要讨论数据处理、AI和云技术中的软件工程高级主题。内容涵盖数据流处理、Kafka、Azure、SQL Server和.NET，深入探讨实时数据架构和数据驱动环境中的AI应用。
> feat(route): add nielsberglund

- lib/routes/follow/profile.ts
Close #
```routes
/follow/profile/diygod
```
fix users link
> fix(route/follow): users link

- lib/routes/langchain/index.ts
- lib/routes/langchain/namespace.ts
Close #
```routes
/langchain/blog
```
The LangChain blog, located at [blog.langchain.dev](https://blog.langchain.dev/), shares insights, tutorials, and case studies on LangChain, a framework for building applications powered by large language models (LLMs). It covers updates on LangChain's ecosystem, use cases in LLM applications, and hands-on guides for implementing AI-driven workflows, making it a go-to resource for developers interested in AI agents and LLM integration.
LangChain 博客（[blog.langchain.dev](https://blog.langchain.dev/)）提供关于 LangChain 框架的见解、教程和案例研究。内容涵盖 LangChain 生态系统的更新、LLM 应用的使用场景，以及实施 AI 工作流的实用指南，是开发者学习和探索 AI 代理与LLM集成的优质资源。
> feat(route): add langchain dev blog

- lib/routes/baoyu/index.ts
- lib/routes/baoyu/namespace.ts
Close #
```routes
/baoyu/blog
```
宝玉博客是有RSS的，但是官方RSS的内容并不理想，无法满足后续的一些AI工作流。修改之后将返回全量的文章内容。
> feat(route): add baoyu's blog with complete content

- lib/routes/bilibili/reply.ts
- lib/utils/got.ts
Close https://github.com/RSSNext/Follow/issues/1390
```routes
/bilibili/video/reply/BV1FsyAY8EMe
```
> fix(bilibili): video reply

- lib/routes/yande/post.ts
Close #
```routes
/yande/post/popular_recent/1d
```
Just like konachan in the commit 2c46c71
> feat(route/yande): extend yande post route with popular category

- lib/routes/thegradient/index.ts
- lib/routes/thegradient/namespace.ts
Close #
```routes
/thegradient/posts
```
The Gradient ([thegradient.pub](https://thegradient.pub/)) is a publication that explores advancements in artificial intelligence, covering topics from research innovations and ethical considerations to AI applications and industry trends. It features in-depth articles, interviews, and editorials by AI researchers and professionals, making complex topics accessible to both technical and general audiences.
The Gradient 网站（[thegradient.pub](https://thegradient.pub/)）聚焦人工智能领域的前沿发展，内容涵盖研究创新、伦理问题、AI 应用和行业趋势。其深入的文章、访谈和评论由 AI 研究人员和专家撰写，使技术和非技术读者均能了解复杂的 AI 话题。
> feat(route): add the gradient blog

- lib/routes/coomer/artist.ts
- lib/routes/coomer/namespace.ts
- lib/routes/coomer/posts.ts
- lib/routes/coomer/utils.ts
```routes
/coomer/artist/belledelphine
/coomer/posts
```
The domain https://coomer.party no longer works, updated it to https://coomer.su, same as kemono.
> fix(route): coomer

- lib/routes/anime1/anime.ts
N/A
```routes
/anime1/anime/2024年秋季/blue-lock-藍色監獄-vs-u-20-日本代表隊
```
> fix(route): anime1 incorrect title

- lib/routes/bilibili/dynamic.ts
- lib/routes/bilibili/followings-dynamic.ts
fix #17444
Close #17444
```routes
/bilibili/user/dynamic/946974
/bilibili/user/dynamic/946974/embed=0
/bilibili/user/dynamic/946974/embed=1
```
> fix(route): 修复 bilibili UP 主动态/用户关注动态 开启内嵌视频 参数错误的问题

- lib/routes/mihoyo/bbs/official.ts
Close #
```routes
/mihoyo/bbs/official/2/3/20/
```
> fix(route): 修复 米游社官方公告 路由的接口错误

- lib/routes/buaa/lib/space/newbook.ts
- lib/routes/daily/discussed.ts
- lib/routes/daily/index.ts
- lib/routes/daily/namespace.ts
- lib/routes/daily/source.ts
- lib/routes/daily/upvoted.ts
- lib/routes/daily/user.ts
- lib/routes/daily/utils.ts
- lib/routes/espn/news.ts
- lib/routes/imdb/chart.ts
- lib/routes/jiuyangongshe/community.ts
- lib/routes/mi/utils.ts
- lib/routes/theblockbeats/index.ts
- lib/routes/vice/topic.ts
- lib/routes/wellcee/rent.ts
Close #
```routes
/daily/source/hn
/daily/user/kramer
/daily/upvoted
```
> feat(route): daily.dev sources

- lib/routes/theinitium/app.ts
> fix(route/theinitium): Fix wp-block html

- lib/routes/apnews/utils.ts
Close #
```routes
/apnews/topics/ap-top-news?filterout_category=Sports
```
> feat(route/apnews): Enhance live page post extraction.

- lib/routes/youtube/user.ts
Close #
```routes
/youtube/user/@JFlaMusic
```
> feat(route/youtube): cache handle lookup

- lib/routes/toutiao/a-bogus.ts
- lib/routes/toutiao/namespace.ts
- lib/routes/toutiao/types.ts
- lib/routes/toutiao/user.ts
Close #1887
Close #2811
Close #2930
Close #12243
```routes
/toutiao/user/token/MS4wLjABAAAAsnxVLly1u1Oucv8lcaX2LYqyCQMZU4farymb_u4v4ko
/toutiao/user/token/MS4wLjABAAAAEmbqJP2CmC8XXv1BpMvQ3sQHKAxFsq8wHxj8XVIQWja6tMcB-QEbFkzkRNgMl12M
```
> feat(route): toutiao

- lib/routes/sycl/feeds.ts
Close #
```routes
/sycl/news
/sycl/videos
/sycl/research_papers
/sycl/events
```
Fix routing Example error in documentation
> fix(route/sycl): docs example wrong

- lib/routes/freecomputerbooks/index.ts
Close #
```routes
/freecomputerbooks
/freecomputerbooks/index
/freecomputerbooks/compscAlgorithmBooks
```
Currently the feed cannot load properly (that either it times out or it only loads very old articles). I'm not sure if it relates to the incorrect `<pubDate>` elements in the generated document (locally in the development instance of mine it loads really fast but just with the corrupt `<pubDate>` elements).
> feat(route): no longer publish date available

- lib/routes/hust/gs.ts
Close #
```routes
/hust/gs/xwdt
```
> fix(route): 华中科技大学研究生院标题不完整

- lib/routes/toutiao/templates/video.art
- lib/routes/toutiao/types.ts
- lib/routes/toutiao/user.ts
Close #
```routes
/toutiao/user/token/MS4wLjABAAAAbDbqwc7SeV1OBT_iiZPKw7nBKWkfy1oWZ73Q5S5CHHU
/toutiao/user/token/MS4wLjABAAAAsnxVLly1u1Oucv8lcaX2LYqyCQMZU4farymb_u4v4ko
```
> feat(route): toutiao video

- lib/routes/caixin/utils-fulltext.ts
Close #
```routes
/caixin/latest
```
> fix(route/caixin): filter out articles that does not have ID

- lib/routes/metacritic/index.ts
Close #
```routes
/metacritic/tv/new/network=prime-video&genre=documentary
```
> fix: Update metacritic API root URL

- lib/routes/csdn/blog.ts
Close https://github.com/RSSNext/Follow/issues/1488
```routes
/csdn/blog/weixin_45886869
```
> fix: update csdn url

- lib/routes/xsijishe/rank.ts
Close #
```routes
/xsijishe/rank/weekly
/xsijishe/rank/monthly
```
> fix(route/xsijishe): update rank list parsing logic

- lib/routes/xiaoheihe/discount.ts
Close #17482
```routes
/xiaoheihe/discount/switch
/xiaoheihe/discount/pc
/xiaoheihe/discount/psn
/xiaoheihe/discount/xbox
```
同时增加了券后价以及超史低价和新史低价的显示
> fix(route/xiaoheihe): 修复小黑盒 - 游戏折扣数据抓取失败

- lib/routes/bsky/posts.ts
- lib/routes/bsky/templates/post.art
Close #
```routes
/bsky/profile/bsky.app/filter=posts_with_media
```
> feat(route/bsky): replace video thumbnail with video player

- lib/routes/zhonglun/index.ts
Close #17525 
```routes
/zhonglun/research/article/zh
/zhonglun/research/article/en
```
韩国和日本好像没有研究文章的地址了，所以暂不处理测试
> fix(route/zhonglun): 修复中伦律师事务所研究文章页面改版导致数据无法获取

- lib/routes/google/developers.ts
Close #
```routes
/google/developers
```
> feat(route): google developers blog

- lib/routes/discord/discord-api.ts
- lib/routes/discord/search.ts
Close #
```routes
/discord/search/302094807046684672/content=friendly&has=image,video
```
> feat(route/discord): add guild messages search with comprehensive parameters

- lib/routes/tongji/sem/_utils.ts
- lib/routes/tongji/sem/notice.ts
Close #
```routes
/tongji/sem
```
- Add description for articles
> feat(route/tongji/sem): Add description for articles

- lib/routes/mastodon/account-id.ts
- lib/routes/mastodon/acct.ts
- lib/routes/mastodon/timeline-local.ts
- lib/routes/mastodon/timeline-remote.ts
Close #
```routes
/mastodon/acct/Mastodon@mastodon.social/statuses
/mastodon/account_id/mas.to/109300507275095341/statuses/false
```
> fix(route/mastodon): Correct the only_media param

- lib/routes/bilibili/ranking.ts
Close https://github.com/RSSNext/Follow/issues/1541
```routes
/bilibili/ranking
/bilibili/ranking/5
/bilibili/ranking/23
```
> fix(bilibili)!: update ranking api

- lib/routes/afr/latest.ts
- lib/routes/afr/namespace.ts
- lib/routes/afr/navigation.ts
- lib/routes/afr/query.ts
- lib/routes/afr/utils.ts
Close #16710
```routes
/afr/latest
/afr/navigation/markets
/afr/navigation/property
```
> feat(route): afr

- lib/routes/bilibili/ranking.ts
https://github.com/DIYgod/RSSHub/pull/17544#issuecomment-2470081268
cc @DIYgod 
```routes
/bilibili/ranking/0/3/1/xxx
/bilibili/ranking/0/3/1
/bilibili/ranking/129/3/1
/bilibili/ranking/7
```
> fix: redirect old bilibili ranking route

- lib/routes/mittrchina/index.ts
Close #
```routes
/mittrchina/breaking
/mittrchina/hot
/mittrchina/index
/mittrchina/video
```
> fix(route/mittrchina): update api

- lib/routes/hellogithub/volume.ts
Close #
```routes
/hellogithub/volume
```
> fix(route): hellogithub 月刊路由增加 pubDate

- lib/routes/vertikal/latest.ts
- lib/routes/vertikal/namespace.ts
Close #15222
```routes
/vertikal/latest
```
> feat(route): vertikal

- lib/routes/oschina/news.ts
Close #
```routes
/oschina/news
```
> fix(route/oschina): improve cookie handling

- lib/routes/inspirehep/author.ts
Close #17573
```routes
/inspirehep/authors/983328
/inspirehep/literature/black hole
```
> fix(route/inspirehep): fix getAuthorById custom accept header

- lib/routes/javtrailers/casts.ts
- lib/routes/javtrailers/categories.ts
- lib/routes/javtrailers/namespace.ts
- lib/routes/javtrailers/studios.ts
- lib/routes/javtrailers/templates/description.art
- lib/routes/javtrailers/types.ts
- lib/routes/javtrailers/utils.ts
Close #13467
```routes
/javtrailers/categories/big-tits
/javtrailers/casts/eimi-fukada
/javtrailers/studios/s1-no-1-style
```
> feat(route): javtrailers

- lib/routes/twitter/api/mobile-api/api.ts
- lib/routes/twitter/api/web-api/utils.ts
Close #12360
Close #15531
```routes
/twitter/tweet/lookonchain/status/1788404733176373529
```
> fix(twitter)!: 修复Twitter 长文本显示不全

- lib/routes/bilibili/article.ts
Close https://github.com/RSSNext/Follow/issues/1597
```routes
/bilibili/user/article/19577966
```
> fix(bilibili)!: update article api

- lib/routes/dw/namespace.ts
- lib/routes/dw/news.ts
- lib/routes/dw/rss.ts
- lib/routes/dw/templates/description.art
- lib/routes/dw/templates/liveblog.art
- lib/routes/dw/templates/video.art
- lib/routes/dw/utils.ts
Close #
```routes
/dw/news/hi
/dw/news/ar
/dw/news/en
/dw/news/zh
/dw/rss/rss-en-all
/dw/rss/rss-chi-all
/dw/news/en/12756
/dw/news/zh-hant/68398488
/dw/news/bn/60199208
/dw/news/am/30503
```
> feat(route): add dw route

- lib/routes/scu/jwc/tzgg.ts
Close #
```routes
/scu/jwc
```
```routes
```
> feat: add icon for /scu/jwc

- lib/config.ts
- lib/routes/patreon/feed.ts
- lib/routes/patreon/namespace.ts
- lib/routes/patreon/templates/description.art
- lib/routes/patreon/types.ts
Close #12465
```routes
/patreon/straightupsisters
```
> feat(route): patreon

- lib/routes/youtube/user.ts
Close #
```routes
/youtube/user/@TheodoreLiu-dl9db
```
> fix(youtube): handle empty channel

- lib/routes/steam/search.ts
Close #
```routes
/steam/search/sort_by=Released_DESC
```
Adds a game's thumbnail as a `<media:thumbnail>` entry. Example:
> feat(route/steam/search): add thumbnails to steam search items

- lib/routes/m-78/namespace.ts
- lib/routes/m-78/news.ts
- lib/routes/m-78/types.ts
Close #17636
```routes
/m-78/news
/m-78/news/news
/m-78/news/streaming
/m-78/news/event
/m-78/news/onair
/m-78/news/broadcast
/m-78/news/goods
/m-78/news/ultraman-cardgame
/m-78/news/shop
/m-78/news/blu-ray_dvd
/m-78/news/digital
```
> feat(route): 円谷ステーション

- lib/routes/hrbust/jwzx.ts
```routes
/hrbust/jwzx
```
为该路由添加了radar规则
> fix(route): add radar rules for ‘哈尔滨理工大学教务公告’

- lib/routes/tongji/sem/notice.ts
Close #
```routes
/tongji/sem
```
1. Add the correct icon
> fix(/tongji/sem): Add the correct icon

- lib/routes/thepaper/channel.ts
- lib/routes/thepaper/factpaper.ts
- lib/routes/thepaper/featured.ts
- lib/routes/thepaper/list.ts
- lib/routes/thepaper/user.ts
Close #17607
```routes
/thepaper/user/4221423
```
> feat(route): thepaper user

- lib/routes/xueqiu/cookies.ts
Close #
```routes
NOROUTE
```
for now, xue qiu will not use acw_sc__v2 anymore. use puppeteer instead.
> fix(route/xueqiu): fix getting cookie logic

- lib/routes/pixiv/novel-api/content/common.ts
- lib/routes/pixiv/novel-api/content/nsfw.ts
- lib/routes/pixiv/novel-api/content/sfw.ts
- lib/routes/pixiv/novel-api/content/types.ts
- lib/routes/pixiv/novel-api/series/nsfw.ts
- lib/routes/pixiv/novel-api/series/sfw.ts
- lib/routes/pixiv/novel-api/user-novels/nsfw.ts
- lib/routes/pixiv/novel-api/user-novels/sfw.ts
Close #
```routes
/pixiv/user/novels/79603797
/pixiv/user/novels/79603797/true
/pixiv/user/novels/890674
/pixiv/user/novels/890674/true
/pixiv/novel/series/11824916
/pixiv/novel/series/12360103
```
This PR also removes the metadata such as likes and comments because they are updated quickly, inessential and not internationalized.
> feat(route/pixiv): add language attributes for novels

- lib/routes/linkresearcher/index.ts
- lib/routes/linkresearcher/namespace.ts
- lib/routes/linkresearcher/templates/bilingual.art
- lib/routes/linkresearcher/types.ts
Close #17609
```routes
/linkresearcher/category=theses&columns=Nature%20导读&subject=生物
/linkresearcher/category=theses&query=可视化价电子
```
> fix(route): linkresearcher

- lib/routes/syosetu/dev.ts
- lib/routes/syosetu/namespace.ts
- lib/routes/syosetu/ranking-r18.ts
- lib/routes/syosetu/ranking.ts
> docs(route/syosetu): add URLs and improve ranking docs

- .devcontainer/devcontainer.json
- .gitpod.yml
> chore: remove thunder client from devcontainer and gitpod configurations

- lib/routes/ikea/cn/low-price.ts
Close #
```routes
/ikea/cn/low_price
```
> fix: low-price.ts 修复宜家低价

- lib/routes/kcna/news.ts
Close #
```routes
/kcna/cn
```
> fix(route/kcna): Remove juche date parsing

- lib/routes/syosetu/search.ts
- lib/routes/syosetu/templates/description.art
- lib/routes/syosetu/types/search.ts
Close #
```routes
/syosetu/ranking/list/daily_total?limit=5
/syosetu/rankingr18/noc/daily_total?limit=5
/syosetu/search/mid/word=学園&notword=&type=&mintime=&maxtime=&minlen=50000&maxlen=&min_globalpoint=&max_globalpoint=&minlastup=&maxlastup=&minfirstup=&maxfirstup=&order=new?limit=5
```
- Optimized keyword display format in search results
- Restructured search-related type definitions into a dedicated types file
- Improved route parameter configuration with structured subsite options
> fix(route/syosetu): HTML escaping in novel description & some minor changes

- lib/routes/bilibili/manga-update.ts
Close #17690
```routes
/bilibili/manga/update/mc29573
```
Some cookies are now required for the relevant API
> fix(route/bilibili): fix manga updates

- lib/routes/apple/podcast.ts
Close #17720 
```routes
/apple/podcast/id1559695855
/apple/podcast/id1500839292/tw
```
Add an optional parameter `region` to retrieve podcasts in other regions.
增加可選的地區選項以搜索`cn`地區以外的podcast。
> feat(route/apple/podcast): add optional region parameter

- lib/routes/isct/namespace.ts
- lib/routes/isct/news.ts
Close #
```routes
/isct/news/ja
/isct/news/en
```
为原路由新增了分类功能。
> feat: Added <category> for Isct news.

- lib/routes/pinterest/namespace.ts
- lib/routes/pinterest/types.ts
- lib/routes/pinterest/user.ts
Close #182
Close #5445
```routes
/pinterest/user/curazycom
/pinterest/user/curazycom/_saved
```
> feat(pinterest): add pinterest

- lib/routes/bsky/posts.ts
Close #
```routes
/bsky/profile/tailwindcss.com/filter=posts_with_replies
```
Add the allowEmpty parameter to solve the problem of not being able to follow users who do not have any posts yet.
> fix(route): bluesky allow empty

- lib/routes/picnob/templates/desc.art
- lib/routes/picnob/user.ts
Close #
```routes
/picnob/user/xlisa_olivex
```
> feat: cache user metadata & video playback in img_multi

- lib/routes/fastbull/express-news.ts
- lib/routes/fastbull/namespace.ts
- lib/routes/fastbull/news.ts
Close #
```routes
/fastbull/news
```
> fix(route/fastbull): Use another site

- lib/routes/ifun/n/category.ts
- lib/routes/ifun/n/search.ts
- lib/routes/ifun/n/tag.ts
- lib/routes/ifun/n/util.ts
- lib/routes/ifun/namespace.ts
Close #17712
```routes
/ifun/n/category
/ifun/n/search/NPC
/ifun/n/tag/zhihu
```
> feat(route): add 趣集盐选故事

- lib/routes/xiaohongshu/user.ts
- lib/routes/xiaohongshu/util.ts
Close #
```routes
/xiaohongshu/user/65d32e150000000005030488/notes/displayLivePhoto=0
/xiaohongshu/user/5aa87ee2db2e60618e0f6a6e/notes/displayLivePhoto=1
/xiaohongshu/user/65d2fcda000000000401dc47/notes
```
1. xiaohongshu/notes中包含视频，现在可以直接在description中显示视频。
2. 增加了新的请求参数`:routeParams?`,目前该参数实现了 `displayLivePhoto`[区分大小写]：
- 当 `displayLivePhoto=0` 或未设置时，LivePhoto 显示为图片
- 当 `displayLivePhoto=1` 时，LivePhoto 显示为视频
- 可能以后还会实现头像/评论区
3. 示例：
- `/xiaohongshu/user/593032945e87e77791e03696/notes` - 默认显示图片
- `/xiaohongshu/user/593032945e87e77791e03696/notes/displayLivePhoto=1` - LivePhoto 显示为视频
> feat(route): 增加小红书路由 LivePhoto以及视频支持功能

- lib/routes/taiwanmobile/namespace.ts
- lib/routes/taiwanmobile/rate-plans.ts
Close #
```routes
/taiwanmobile/rate-plans
```
> feat(route): add taiwanmobile rate-plans

- lib/routes/dingshao/namespace.ts
- lib/routes/dingshao/share.ts
- lib/routes/dingshao/types.ts
Close #17764
```routes
/dingshao/share/FzFypN
```
> feat(route): dingshao

- lib/routes/hellogithub/article.ts
- lib/routes/hellogithub/index.ts
- lib/routes/hellogithub/report.ts
- lib/routes/hellogithub/volume.ts
Close #
```routes
/hellogithub/article
/hellogithub/article/last
/hellogithub/article/hot
```
> feat(hellogithub): hellogithub 添加文章路由

- lib/routes/joneslanglasalle/index.ts
Close #17789
```routes
/joneslanglasalle/en/trends-and-insights
```
> fix(route): Jones Lang LaSalle

- lib/views/index.tsx
Close #17791
```routes
/test/1
```
> fix(view/index): update logo image path to relative

- lib/routes/yna/index.ts
- lib/routes/yna/namespace.ts
Close #14332 
```routes
/yna
/yna/ko
/yna/en
/yna/cn
/yna/ar
/yna/ko/society
/yna/en/national
/yna/jp/news
```
> feat(route): add Yonhap News Agency route

- lib/routes/luogu/daily.ts
- lib/routes/luogu/user-article.ts
- lib/routes/luogu/user-blog.ts
- lib/routes/luogu/user-feed.ts
- lib/routes/luogu/utils.ts
Close #17571
```routes
/luogu/user/article/1
```
> feat(route): luogu

- lib/routes/mihoyo/bbs/timeline.ts
- 更新 timeline API URL 以匹配最新的 API 路径
Close #
```routes
/mihoyo/bbs/timeline
```
> fix(mihoyo/bbs): 修复 timeline API URL

- lib/routes/sjtu/jwc.ts
Close #
```routes
/sjtu/jwc/students
```
添加对上海交通大学教务处“面向学生的通知”的支持。
https://jwc.sjtu.edu.cn/index/mxxsdtz.htm
> feat(route): 添加 上海交通大学教务处 面向学生的通知 路由

- lib/routes/ali213/namespace.ts
- lib/routes/ali213/news.ts
- lib/routes/ali213/templates/description.art
Close #17786
```routes
/ali213/news/new
```
> feat(route): add 游侠网资讯

- lib/routes/sohu/mp.ts
Close #17836
```routes
/sohu/mp/MjM3NzE1MjQ4M0BxcS5jb20=
```
> fix(route/sohu): add image URL decryption for fetched articles

- lib/routes/follow/profile.ts
Close #
```routes
/follow/profile/DIYgod
```
Many invalid subscriptions are included and shown as “Importing”
> fix(route): follow

- lib/routes/iheima/index.ts
- lib/routes/iheima/namespace.ts
Close #
```routes
/iheima/recommend
```
> feat(route): 新增 i黑马网

- lib/routes/baijing/index.ts
- lib/routes/baijing/namespace.ts
Close #
```routes
/baijing/article/
```
> feat(route): 添加 白鲸出海

- lib/routes/qbitai/category.ts
Close #
```routes
/qbitai/category/资讯
```
为 `/qbitai/category/` 添加了全文获取。
> feat: get full text for routes/qbitai/category

- lib/routes/chinacdc/index.ts
- lib/routes/chinacdc/namespace.ts
- lib/routes/chinacdc/templates/description.art
Close #17820
```routes
/chinacdc/zxyw
```
> feat(route): add 中国疾病预防控制中心

- lib/routes/picnob/templates/desc.art
N/A
```routes
/picnob/user/zuck
```
The current Picnob route's description template (`desc.art`) does not enumerate all the possible `item.type` (from Picnob API). The most notable one is `igtv` which corresponds to Instagram Reels. This results in Reels video not being included in the RSS description. This PR apply the same logic as `video` to `igtv` and fixed the issue.
Here is a excerpt from the API endpoint `https://www.piokok.com/api/posts?userid=314216` (for user `@zuck`) that is offending: 
```
...
{
"type": "igtv",
"sum": "Last big AI update of the year. Next stop -- Llama 4 in 2025 🚀",
"sum_pure": "Last big AI update of the year. Next stop -- Llama 4 in 2025",
"shortcode": "6767645661134653405447",
"time": 1733503170,
"ftime": "2 days ago",
"count_like": 160809,
"count_comment": …
```
> feat(picnob): fix Picnob Instagram Reels video playback.

- lib/routes/chongdiantou/index.ts
- lib/routes/chongdiantou/namespace.ts
Close #
```routes
/chongdiantou
```
> feat(route): 充电头网

- lib/types.ts
> fix(types): fix route type definitions for different languages

- lib/routes/daoxuan/namespace.ts
- lib/routes/daoxuan/rss.ts
Close #
```routes
/daoxuan
```
> feat(route): 新增博客道宣的窝

- lib/routes/hrbust/namespace.ts
- lib/routes/hrbust/news.ts
None
```routes
/hrbust/news
/hrbust/news/lgyw
/hrbust/news/xwdd
/hrbust/news/zhenew
/hrbust/news/jxky
/hrbust/news/ycdt
/hrbust/news/xskc
/hrbust/news/jlhz
/hrbust/news/zsjy
/hrbust/news/djsz
/hrbust/news/zxbf
/hrbust/news/lgxb
/hrbust/news/mtlg
/hrbust/news/jzlt
```
`/hrbust/news/zhenew` This route has been tested locally and works.
> feat(route/hrbust): add 哈尔滨理工大学新闻网

- lib/routes/github/repos.ts
- 引入 `parseDate` 工具函数用于解析日期
- 根据排序类型（updated 或 pushed）动态设置发布日期
- 优化数据过滤和映射逻辑，减少嵌套层级
Close #
```routes
/github/repos/DIYgod/all/created
/github/repos/DIYgod/all/updated
/github/repos/DIYgod/all/pushed
/github/repos/DIYgod/all/full_name
```
由于 RSSHub 默认会根据 pubDate 进行排序，因此使用 updated_at 作为 pubDate 的话，在 sort 为 updated/pushed 的情况下是无效的，所以需要用 updated_at/pushed_at 作为 pubDate
> fix(github/repos): 添加日期解析功能并优化数据处理

- lib/routes/egsea/flash.ts
Close #17879
```routes
/egsea/flash
```
> fix(route/egsea): 修复e快选因部分条目没有分类导致抓取失败

- lib/routes/wabei/index.ts
- lib/routes/wabei/namespace.ts
Close #
```routes
/wabei/hot-recommend
```
> feat(route): 新增 挖贝网

- lib/routes/zaobao/util.ts
Close #
```routes
/zaobao/znews/china
```
> fix(route/zaobao): Adapt to new SG layout

- lib/routes/hexun/index.ts
- lib/routes/hexun/namespace.ts
Close #
```routes
/hexun/pe/news
```
> feat(route): 新增 和讯创投

- lib/routes/newseed/index.ts
- lib/routes/newseed/namespace.ts
Close #
```routes
/newseed/latest
```
> feat(route): 新增新芽网

- lib/routes/spglobal/namespace.ts
- lib/routes/spglobal/ratings.ts
增加标普全球评级多语言发布稿件的获取，https://www.spglobal.com/ratings/zh、https://www.spglobal.com/ratings/en等
Close #
```routes
/spglobal/ratings/zh
/spglobal/ratings/en
/spglobal/ratings/jp
/spglobal/ratings/pt
/spglobal/ratings/es
/spglobal/ratings/ru
/spglobal/ratings/ar
```
> feat(route): 增加标普全球评级

- lib/routes/apnic/index.ts
- lib/routes/apnic/namespace.ts
Close #
```routes
/apnic/blog
```
> feat(route): APNIC Blog 全文 RSS

- lib/routes/techsir/index.ts
- lib/routes/techsir/namespace.ts
Close #
```routes
/techsir
```
> feat(route): add techsir.com

- lib/routes/behance/queries.ts
- lib/routes/behance/templates/description.art
- lib/routes/behance/user.ts
Close https://github.com/RSSNext/Follow/discussions/2226
```routes
/behance/archigor012/projects
```
> fix(behance): use GraphQL instead

- lib/routes/iresearch/chart.ts
- lib/routes/iresearch/templates/chart.art
Close #
```routes
/iresearch/chart
```
> feat(route): add 艾瑞咨询研究图表

- lib/routes/behance/user.ts
Close https://github.com/RSSNext/Follow/discussions/2260
```routes
/behance/yayuniversal/projects
```
> fix(behance): fix image url

- lib/routes/bilibili/user-channel.ts
- lib/routes/bilibili/user-collection.ts
Close #
```routes
/bilibili/user/channel/2267573/396050
/bilibili/user/collection/245645656/529166
```
Related to #17357
> fix(bilibili): missing image

- lib/routes/gov/hainan/iitb/tzgg.ts
- lib/routes/gov/hainan/namespace.ts
Close #
```routes
/gov/hainan/iitb/tzgg
```
> feat(route): 添加 海南省工业和信息化厅-通知公告

- lib/routes/behance/templates/description.art
Close https://github.com/RSSNext/Follow/discussions/2260
```routes
/behance/yayuniversal/projects
```
> fix(behance): embed

- lib/routes/hket/index.ts
Close #17926
```routes
/hket/srat006
```
> fix(hket): select main listing container

- lib/routes/copernicium/index.ts
Close #
```routes
/copernicium
/copernicium/环球视角
/copernicium/专题报道
```
> feat(route/copernicium): Add default

- lib/routes/shu/global.ts
- lib/routes/shu/gs.ts
- lib/routes/shu/index.ts
- lib/routes/shu/jwb.ts
- lib/routes/shu/xykd.ts
Close #17735
```routes
NOROUTE
```
> perf(shu): 给上海大学相关 rss 添加图标

- lib/routes/moodysmismicrosite/namespace.ts
- lib/routes/moodysmismicrosite/report.ts
Close #
```routes
/moodysmismicrosite/report/企业&金融机构
/moodysmismicrosite/report/企业
/moodysmismicrosite/report
```
https://www.moodysmismicrosite.com/report
> feat(route): add 穆迪评级

- lib/routes/deepseek/namespace.ts
- lib/routes/deepseek/news.ts
> feat(route): add Deepseek news route

- lib/routes/jrj/index.ts
- lib/routes/jrj/namespace.ts
Close #
```routes
jrj/102
jrj/103
jrj/104
jrj/105
jrj/106
jrj/107
jrj/112
jrj/113
jrj/115
jrj/118
jrj/119
jrj/503
jrj/508
jrj/603
jrj/629
jrj/630
jrj/632
jrj/004
jrj/009
jrj/010
jrj/001
jrj/007
```
> feat(route): 增加 金融界

- lib/routes/cursor/changelog.ts
- lib/routes/cursor/namespace.ts
Close #
```routes
/cursor/changelog
```
> feat(route): add cursor changelog

- lib/routes/tiddlywiki/namespace.ts
- lib/routes/tiddlywiki/releases.ts
Close #
```routes
/tiddlywiki/releases
```
> feat(route): add tiddlywiki releases

- lib/routes/pixiv/user.ts
Close #
```routes
/pixiv/user/15288095
```
> fix(pixiv/user): use imgProxy for image url

- lib/routes/msn/index.ts
- lib/routes/msn/namespace.ts
Close #17582
Close #8496
```routes
/msn/zh-cn/新华社/sr-vid-769jkard8p2sjcwjkv264h2divi25i5qk62whg7yq8akhwk23p6a
/msn/zh-cn/人民网/sr-vid-jwtjursmmc5egygacdnch06pxwhgdhk4in2r85yucvdgfgyhnsbs
/msn/zh-cn/澎湃新闻/sr-vid-kr7w4fq563568erb38y3ae3gr34vqe8vt4fr4sk574d69hu9h73s
/msn/zh-cn/红星新闻/sr-vid-ed4u3ky0u6b59hu83thk3pyy0fn6dfbnsyxsb79fvvsj34d0yk0s
/msn/zh-hk/AFP/sr-vid-3kv7h73mtcdhywg28d4f9ihgi4xcniq2ubb83iikdu3qwmbd73pa
/msn/zh-tw/Bloomberg/sr-vid-08gw7ky4u229xjsjvnf4n6n7v67gxm0pjmv9fr4y2x9jjmwcri4s
```
> feat: add msn news

- lib/routes/webcatalog/changelog.ts
- lib/routes/webcatalog/namespace.ts
Close #
```routes
/webcatalog/changelog
```
> feat(route): add WebCatalog changelog

- lib/routes/bilibili/dynamic.ts
Close #
```routes
/bilibili/user/dynamic/510362725
/bilibili/user/dynamic/510362725/offset=994791894155264002
```
/bilibili/user/dynamic增加offset参数 实现用户动态翻页
> fix(bilibili/user/dynamic): bilibili dynamic offset

- lib/routes/koreaherald/index.ts
- lib/routes/koreaherald/namespace.ts
Close #
```routes
/koreaherald
/koreaherald/Opinion
/koreaherald/National/CourtsandLaw
```
> feat(route): add koreaherald route

- lib/routes/chongdiantou/index.ts
Close #
```routes
/chongdiantou
```
由于网站将 api 获取改为了直接获取 html, 因此更新代码.
> feat(route): switch to ofetch for API calls

- lib/routes/bnu/fe.ts
Close #18015
```routes
/bnu/fe/18
/bnu/fe/30
```
支持参数，https://fe.bnu.edu.cn/pc/cms1info/list/1/18 路由则对应为 /bnu/fe/18
| 分类                 | 分类号 |
|----------------------|--------|
| 招生信息             | 11     |
| 本科生招生           | 12     |
| 硕士研究生招生       | 13     |
| 博士研究生招生       | 14     |
| 在职教育硕士招生     | 15     |
| 留学生招生           | 16     |
| 教育教学             | 17     |
| 培养动态             | 18     |
| 本科生培养           | 19     |
| 硕士研究生培养       | 24     |
| 博士研究生培养       | 30     |
| INTERNATIONAL PROGRAMS | 36  |
| 全日制专业硕士       | 43     |
| 课程大纲             | 49     |
| 学生园地             | 61     |
| 通知公告             | 62     |
| 头条关注             | 63     |
| 菁菁学子             | 81     |
| 荣誉殿堂             | 80     |
| 工作团队             | 64     |
> feat(route): 添加北师大-教育学部-培养动态

- lib/routes/youtube/user.ts
Close #
```routes
/youtube/user/WholeMars
/youtube/user/@WholeMars
```
> fix(youtube): check if username exists

- lib/routes/gameapps/index.ts
Close #
```routes
/gameapps
```
> fix(gameapps): fix title

- lib/routes/hiring.cafe/jobs.ts
Close #
```routes
/hiring.cafe/jobs/sustainability
/hiring.cafe/jobs/python
```
- default `sortBy` param of the API request payload to 'date' instead of 'default'; this will force the RSS feed to be ordered by date instead of by relevance
- add default size and page value to the API request payload
> feat(hiringcafe): add new payload params

- lib/routes/oschina/column.ts
- lib/routes/oschina/namespace.ts
- lib/routes/oschina/templates/description.art
Close #
```routes
/oschina/column/14
```
> feat(route): add 开源中国专栏

- lib/types.ts
> fix(types): add logo and icon properties and change language type

- lib/routes/hdu/auto/graduate.ts
- lib/routes/hdu/auto/notice.ts
- lib/routes/hdu/auto/student.ts
- lib/routes/hdu/auto/undergraduate.ts
- lib/routes/hdu/auto/utils.ts
- lib/routes/hdu/namespace.ts
Close #
```routes
/hdu/auto
/hdu/auto/student
/hdu/auto/graduate
/hdu/auto/undergraduate
```
> feat(route): add hdu/auto

- lib/routes/sciencedirect/call-for-paper.ts
- lib/routes/sciencedirect/templates/description.art
Close #18038
```routes
sciencedirect/call-for-paper/education
sciencedirect/call-for-paper/development
sciencedirect/call-for-paper/health
```
sciencedirect.com/browse/calls-for-papers?subject=education -> /sciencedirect/call-for-paper/education
- Development
- Education
- Health
- LaW
- ...
> feat(route): Add feed for sciencedirect call for paper

- lib/routes/egsea/flash.ts
Close #18098
```routes
/egsea/flash
```
> fix(route/egsea): 修复e快选链接不正确

- lib/routes/misskey/types.ts
- lib/routes/misskey/user-timeline.ts
- lib/routes/misskey/utils.ts
Close #
```routes
/misskey/users/notes/mttb2ccp@misskey.io
```
> feat(misskey): add avatar to user timeline

- lib/routes/lhratings/namespace.ts
- lib/routes/lhratings/research.ts
Close #18101
```routes
/lhratings/research/1
```
> feat(route): add 联合资信评估股份有限公司研究报告

- lib/routes/taoguba/blog.ts
- lib/routes/taoguba/index.ts
- lib/routes/taoguba/namespace.ts
- lib/routes/taoguba/util.ts
Close #18083
```routes
/taoguba/blog/252069
/taoguba/bbs
/taoguba/zongban
/taoguba/jinghua
/taoguba/dianzan
```
> fix(route/taoguba): 修复淘股吧更换域名以及修改获取帖子详情结构

- lib/routes/google/research.ts
Close #
```routes
/google/research
```
> fix(routes/google/research): add description

- lib/routes/hrbust/news.ts
Close #
```routes
/hrbust/news
```
fix docs and logical problem
> fix(routes/hrbust/news): fix docs and logical problem

- lib/routes/zsxq/utils.ts
Close #
```routes
NOROUTE
```
路由需添加 access token 访问，效果见[个人部署](http://91.200.242.146:1300/zsxq/group/48888882551128)
> fix(route/zsxq): 为主题添加跳转链接

- lib/routes/missav/namespace.ts
- lib/routes/missav/new.ts
Close #
```routes
/missav/new
```
> fix(missav): new domain

- lib/routes/juejin/books.ts
- lib/routes/juejin/category.ts
- lib/routes/juejin/collection.ts
- lib/routes/juejin/collections.ts
- lib/routes/juejin/column.ts
- lib/routes/juejin/dynamic.ts
- lib/routes/juejin/favorites.ts
- lib/routes/juejin/pins.ts
- lib/routes/juejin/posts.ts
- lib/routes/juejin/tag.ts
- lib/routes/juejin/trending.ts
- lib/routes/juejin/types.ts
- lib/routes/juejin/utils.ts
Close #18070
```routes
/juejin/posts/3051900006845944
```
> fix(route): juejin post

- lib/routes/xmu/kydt.ts
- lib/routes/xmu/namespace.ts
Close #
```routes
/xmu/kydt
```
> feat(route): add 厦门大学经济学院科研动态

- lib/routes/pencilnews/index.ts
- lib/routes/pencilnews/namespace.ts
> feat(route): 新增铅笔道文章列表

- lib/routes/qstheory/magazine.ts
Close #18179 
```routes
/qstheory/magazine/qs
```
- origin website now use relative path
- origin website changed struct for list page(no '\<span\>')
> fix(routes/qstheory/magazine): adapt to origin site changed

- lib/routes/cccmc/index.ts
- lib/routes/cccmc/namespace.ts
Close #18150
```routes
/cccmc/ywgg/tzgg
```
> feat(route): add 中国五矿化工进出口商会

- lib/routes/oschina/event.ts
- lib/routes/oschina/templates/description.art
Close #
```routes
/oschina/event
```
> feat(route): add 开源中国活动

- lib/routes/bilibili/user-collection.ts
Close #18182 
```routes
/bilibili/user/collection/317111690/1454754/true/1
```
> https://api.bilibili.com/x/polymer/web-space/seasons_archives_list (需验证referer)
> https://api.bilibili.com/x/polymer/space/seasons_archives_list (旧接口, 不推荐使用, 无鉴权验证)
refer to https://socialsisteryi.github.io/bilibili-API-collect/docs/video/collection.html
seem like bilibili delete old api host, now changed to new api host
> fix(routes/bilibili/user-collection): user new api host

- lib/routes/hrbust/news.ts
Close #
```routes
/hrbust/news/tzgg
```
- support more column
- support author
- support attachment
> feat(routes/hrbust/news): add support for more column

- lib/routes/tongji/gs.ts
- lib/routes/tongji/yjs.ts
```routes
/tongji/yjs
/tongji/gs
```
> feat(route): Add /tongji/gs and Update /tongji/yjs

- lib/routes/ruankao/news.ts
Close #
```routes
/ruankao/news
```
> fix(route/ruankao): Remove font presetting and other details.

- lib/routes/hrbust/nic.ts
Close #
```routes
/hrbust/nic
```
> feat(routes/hrbust/nic): add route '哈尔滨理工大学网络信息中心'

- lib/routes/ce/district.ts
- lib/routes/ce/namespace.ts
Close #18189 
```routes
/ce/district
```
> feat(routes/ce/district): add route '中国经济网地方经济'

- lib/routes/ebc/namespace.ts
- lib/routes/ebc/realtime.ts
Close #
```routes
/ebc/realtime
/ebc/realtime/living
/ebc/realtime/entertainment
/ebc/realtime/society
/ebc/realtime/politics
/ebc/realtime/world
/ebc/realtime/sport
/ebc/realtime/business
/ebc/realtime/health
```
> feat(route): add 東森新聞 ebc route

- lib/routes/nhk/news.ts
Close #18214 
```routes
/nhk/news/zh
```
> fix(routes/nhk/news): fix `\n` not totally replaced to `<br>`

- lib/routes/landiannews/index.ts
- lib/routes/landiannews/namespace.ts
- lib/routes/landiannews/templates/description.art
Close #18213
```routes
/landiannews
```
> feat(route): add 蓝点网资讯

- lib/routes/neea/jlpt.ts
- lib/routes/neea/namespace.ts
Close #18202
```routes
/neea/jlpt
```
> fix(route): 日本语能力测试JLPT通知

- lib/routes/dytt/index.ts
- lib/routes/dytt/namespace.ts
Close #18198
```routes
/dytt
```
> feat(route): add 电影天堂

- lib/routes/2048/index.ts
Close #18172
```routes
/2048/15
```
> fix(route): 2048 jump logic

- lib/routes/cosplaytele/article.ts
- lib/routes/cosplaytele/category.ts
- lib/routes/cosplaytele/const.ts
- lib/routes/cosplaytele/latest.ts
- lib/routes/cosplaytele/namespace.ts
- lib/routes/cosplaytele/popular.ts
- lib/routes/cosplaytele/tag.ts
- lib/routes/cosplaytele/types.ts
Close #
```routes
/cosplaytele
/cosplaytele/category/cosplay
/cosplaytele/tag/aqua
/cosplaytele/popular/7
```
> feat(route): add route "CosplayTele"

- lib/routes/4kup/article.ts
- lib/routes/4kup/category.ts
- lib/routes/4kup/const.ts
- lib/routes/4kup/latest.ts
- lib/routes/4kup/namespace.ts
- lib/routes/4kup/popular.ts
- lib/routes/4kup/tag.ts
- lib/routes/4kup/types.ts
Close #
```routes
/4kup
/4kup/category/coser
/4kup/tag/asian
/4kup/popular/7
```
> feat(route): add route "4KUP"

- lib/routes/juejin/dynamic.ts
Close #
```routes
/juejin/dynamic/852876722177533
/juejin/dynamic/3043088413495815
```
> feat(routes): 增加对标签关注的处理逻辑

- lib/routes/gcores/articles.ts
- lib/routes/gcores/parser.ts
- lib/routes/gcores/templates/description.art
- lib/routes/gcores/util.ts
Close #
```routes
/gcores/articles
```
> feat(route): add 机核网文章

- lib/routes/bilibili/user-collection.ts
Close #18191 
```routes
/bilibili/user/collection/432438994/1458832/1/1
/bilibili/user/collection/432438994/1458832/0/1
```
> fix(routes/bilibili/user/collection): fix embed param not correct handle

- lib/routes/gcores/parser.ts
Close #
```routes
/gcores/articles
```
> fix(gcores): correct rendering of entities and optimize parsing logic

- lib/routes/nautiljon/manga-releases.ts
- lib/routes/nautiljon/namespace.ts
Close #
```routes
/nautiljon/releases/manga
```
> feat(route): add route "Nautiljon"

- lib/routes/xkb/index.ts
Close #
```routes
/xkb/350
```
> fix(route): Fix xkb.com.cn

- lib/routes/gcores/templates/description.art
Close #
```routes
/gcores/news
```
> fix(gcores): correct templates for images and videos

- lib/routes/kemono/index.ts
> fix(route/kemono): fix items parsing logic

- lib/routes/producthunt/templates/descImg.art
- lib/routes/producthunt/templates/description.art
- lib/routes/producthunt/today.ts
Close #
```routes
/producthunt/today
```
> fix(route): producthunt

- lib/routes/nautiljon/manga-releases.ts
Close #
```routes
/nautiljon/releases/manga
```
- Fix the example of the nautiljon/releases/manga route not havin a `/`
- Improve the route to only add released manga instead of all the manga that are going to be released this month
> feat(routes/nautiljon): improve the manga-releases route

- lib/routes/theinitium/app.ts
Close #
```routes
/theinitium/app
```
Follow up to #18279
> fix(route/theinitium): fix app route user agent image issue

- lib/routes/landiannews/category.ts
- lib/routes/landiannews/index.ts
- lib/routes/landiannews/tag.ts
- lib/routes/landiannews/templates/description.art
- lib/routes/landiannews/utils.ts
Close #
```routes
/landiannews
/landiannews/tag/linux-kernel
/landiannews/category/sells
```
This PR aim to change landiannews to API get information.
~~And I don't find an easy way to find the relation between ID and name, so there is no document for tag and category route, I'm working on.~~
All done, ready to merge.
> feat(routes/landiannews): use wp-api, add category and tag routes

- lib/routes/4khd/article.ts
- lib/routes/4khd/category.ts
- lib/routes/4khd/const.ts
- lib/routes/4khd/latest.ts
- lib/routes/4khd/namespace.ts
- lib/routes/4khd/types.ts
Close #
```routes
/4khd
/4khd/category/popular
/4khd/category/cosplay
/4khd/category/album
```
The funny thing is, this website's "popular" page is not used to showcase actual popular posts, but only displays posts categorized as "popular".
> feat(route): add route "4KHD"

- lib/routes/bilibili/cache.ts
- lib/routes/bilibili/live-room.ts
Close #
```routes
/bilibili/live/room/31368697
```
> feat(route): bilibili live keyframe

- lib/routes/people/index.ts
Close #
```routes
/people/japan/35468
```
This PR fixes /people's route
1. list of items so that website header items are excluded
2. item's description
> feat: fix /people route's list of items and description

- lib/routes/picnob/user.ts
Close #
```routes
/picnob/user/zuck
/picnob/user/zuck/tagged
```
> fix(route/picnob): handle string response parsing

- lib/routes/mashiro/index.ts
- lib/routes/mashiro/namespace.ts
Close #
```routes
/mashiro/en
/mashiro/zh-cn
```
This is my personal blog site, and I will be its maintainer. It will fetch all posts from the archive page and retrieve post content from each post link.
Thank you!
> feat(routes/mashiro): add route `mashiro.best`

- lib/routes/swjtu/scai/bks.ts
Close #
```routes
/swjtu/scai/bks
```
fix issue with fetching swjtu-scai-bks route
> fix(routes): fix issue with fetching swjtu-scai-bks route

- lib/routes/picnob/user.ts
Close #
```routes
/picnob/user/zuck
```
https://github.com/DIYgod/RSSHub/pull/18347#discussion_r1957142845
> feat(route/picnob): use shortcode as explicit guid for feed stability

- lib/routes/okx/index.ts
- lib/routes/okx/namespace.ts
none
```routes
/okx/latest-announcements
/okx/new-listings
/okx/delistings
/okx/trading-updates
/okx/deposit-withdrawal-suspension-resumption
/okx/p2p-trading
/okx/web3
/okx/earn
/okx/jumpstart
/okx/api
/okx/okb-buy-back-burn
/okx/others
```
Because of [a nodejs problem](https://github.com/nodejs/node/issues/46167), this new route has only been tested partially on my machine. I'll be thankful if anyone could help me to test it.
> feat(route): add okx

- lib/routes/gcores/videos.ts
Close #
```routes
/gcores/videos
```
> feat(gcores): add 机核网视频

- lib/routes/bsky/feeds.ts
- lib/routes/bsky/utils.ts
Close #
```routes
bsky/profile/jaz.bsky.social/feed/cv:cat
```
> feat(bsky): add feeds route

- lib/routes/hrbust/cs.ts
- lib/routes/hrbust/gzc.ts
- lib/routes/hrbust/jwzx.ts
- lib/routes/hrbust/lib.ts
- lib/routes/hrbust/news.ts
- lib/routes/hrbust/nic.ts
Close #
```routes
/hrbust/cs
/hrbust/gzc
/hrbust/jwzx
/hrbust/lib
/hrbust/news
/hrbust/nic
```
> feat(routes/hrbust): add 'cs' 'gzc' 'lib' routes, unified code style

- lib/routes/xsijishe/rank.ts
- lib/routes/xsijishe/utils.ts
Close #
```routes
/xsijishe/rank/weekly
/xsijishe/rank/monthly
```
> fix(route/xsijishe): implement adaptive content parsing with puppeteer fallback

- lib/routes/163/utils.ts
Close #18396 
```routes
/163/dy2/T1631770091598
```
> fix(routes/163/dy): fix post without img error

- lib/routes/szse/disclosure/listed-notice.ts
Close #18376
```routes
/szse/disclosure/listed/notice
```
> feat(routes/szse): add 深圳证券交易所上市公司公告

- lib/routes/patreon/feed.ts
- lib/routes/patreon/templates/description.art
Close #18418
```routes
/patreon/inspiringphilosophy
```
> fix(patreon): fix empty image

- lib/routes/huxiu/util.ts
Close #18417 
```routes
/huxiu/briefcolumn/1
/huxiu/briefcolumn/2
```
> fix(routes/huxiu/briefcolumn): fix when img is empty

- lib/routes/gov/moa/gjs.ts
Close #18400
```routes
/gov/moa/gjs/gzdt
```
> feat(route): add 中华人民共和国农业农村部国际合作司

- lib/routes/cmu/andypavlo/blog.ts
- lib/routes/cmu/namespace.ts
Close #
```routes
/cmu/andypavlo/blog
```
> feat(route): add Andy Pavlo Blog

- lib/routes/leagueoflegends/namespace.ts
- lib/routes/leagueoflegends/patch-notes.ts
Close #
```routes
/leagueoflegends/patch-notes
```
> feat(route): add League of Legends patch notes

- lib/routes/spotify/show.ts
Close https://github.com/RSSNext/Follow/discussions/2861
```routes
spotify/show/2g0V13H8ZqZao5uqpJJkZs
```
> fix(spotify): filter removed episodes

- lib/routes/swjtu/namespace.ts
- lib/routes/swjtu/scai.ts
- lib/routes/swjtu/sports.ts
Close #
```routes
/swjtu/scai/bks
/swjtu/scai/yjs
/swjtu/scai/xsgz
/swjtu/sports
```
新增参数type：/swjtu/scai/:type
| 分区              | 参数         |
| :-------------: | :---------: |
| 本科生教育   | bks           |
| 研究生教育   | yjs            |
| 学生工作       | xsgz         |
/swjtu/sports
> feat(route): add 西南交通大学

- lib/routes/theverge/index.ts
- lib/routes/theverge/templates/header.art
Close #18469
```routes
/theverge
```
> fix(route): theverge

- lib/routes/komiic/comic.ts
- lib/routes/komiic/namespace.ts
Close #
```routes
/komiic/comic/533
/komiic/comic/533?limit=10
```
> feat(route): add route "komiic"

- lib/routes/wainao/templates/description.art
- lib/routes/wainao/topics.ts
Close #
```routes
/wainao/topics/hotspot
```
> feat(routes/wainao): add 歪脑主题

- lib/routes/fangchan/list.ts
- lib/routes/fangchan/namespace.ts
- lib/routes/fangchan/templates/description.art
Close #18433
```routes
/fangchan/list/datalist
```
> feat(route): add 中房网

- lib/routes/juejin/collections.ts
Close #18459
```routes
/juejin/collections/1521379821759837
```
> fix(juejin/collections): filter out falsy values

- lib/routes/zaobao/util.ts
Close #
```routes
/zaobao/znews/china
```
> fix(route/zaobao): handle JSON parsing with control characters

- lib/routes/forklog/index.ts
- lib/routes/forklog/namespace.ts
Close #
```routes
/forklog/news
```
> feat(route): add forklog route

- lib/routes/grainoil/category.ts
- lib/routes/grainoil/namespace.ts
Close #18458
```routes
/grainoil/newsListHome/3
```
> feat(route): add 国家粮油信息中心

- lib/routes/decrypt/index.ts
Close #
```routes
/decrypt
```
> fix(decrypt): filter before parsing

- lib/routes/theblock/index.ts
- package.json
- pnpm-lock.yaml
Close #
```routes
/theblock/category/crypto-ecosystems
```
> fix(theblock): fix invalid date and use api to fetch posts

- lib/routes/cryptoslate/index.ts
Close #
```routes
/cryptoslate
```
> fix(cryptoslate): filter before parsing and fix contentEncoded parsing

- lib/routes/anthropic/news.ts
> fix(anthropic): article parsing

- lib/routes/blockworks/index.ts
Close #
```routes
/blockworks
```
> fix(blockworks): use next data api

- lib/routes/sohu/mp.ts
Close #
```routes
/sohu/mp/MWJmNTdjZjYtMTRiMi00NWI2LWE2ZDMtY2I1NmRhNTNmNDQ0
```
> fix(route/sohu): Revamp the logic behind `renderData`

- lib/routes/asianfanfics/namespace.ts
- lib/routes/asianfanfics/tag.ts
- lib/routes/asianfanfics/text-search.ts
```routes
/asianfanfics/tag/milklove/L
/asianfanfics/tag/milklove/N
/asianfanfics/tag/milklove/O
/asianfanfics/tag/milklove/C
/asianfanfics/tag/milklove/OS
/asianfanfics/text-search/milklove
```
添加了亚洲同人网(asianfanfics.com)的两个新路由:
1. `/asianfanfics/tag/:tag/:type` - 按标签搜索
- 支持多种排序类型:
- L: Latest 最近更新
- N: Newest 最近发布
- O: Oldest 最早发布
- C: Completed 已完成
- OS: One Shots 短篇
2. `/asianfanfics/text-search/:keyword` - 按关键词搜索
由于网站有反爬机制，使用了 puppeteer 来获取数据。路由会返回文章的标题、链接、作者和发布时间等信息。
> feat(route): add asianfanfics route

- lib/routes/likeshop/index.ts
- lib/routes/likeshop/namespace.ts
Close #18387 
```routes
/likeshop/people
/likeshop/bloombergpursuits
/likeshop/bloombergbusiness
```
closed https://github.com/DIYgod/RSSHub/pull/18486 to use this one
> feat(route): add likeshop route (#18387)

- lib/routes/anthropic/news.ts
> fix(anthropic): duplicated image

- lib/routes/collabo-cafe/category.ts
- lib/routes/collabo-cafe/index.ts
- lib/routes/collabo-cafe/namespace.ts
- lib/routes/collabo-cafe/parser.ts
- lib/routes/collabo-cafe/tag.ts
Close #
```routes
/collabo-cafe
/collabo-cafe/category/cafe
/collabo-cafe/tag/ikebukuro
```
> feat(route): Add Collabo Cafe

- lib/routes/discuz/discuz.ts
Close #17424 
```routes
/discuz/x/http%3a%2f%2fwww.u-share.cn%2fforum.php%3fmod%3dforumdisplay%26fid%3d56
/discuz/https%3A%2F%2Fwww.51kanong.com%2Fforum.php%3Fmod%3Dforumdisplay%26fid%3D169
```
Fix Cannot read properties of undefined (reading 'content-type')
Adopt the suggestion from #15765 to switch from got to ofetch.
> fix(route): discuz use ofetch

- lib/routes/stcn/index.ts
- lib/routes/stcn/kx.ts
Close #18523
```routes
/stcn/article/list/kx
```
> feat(route): add 证券时报网

- lib/routes/mashiro/index.ts
…ducing long waiting
Close #
```routes
/mashiro/en
/mashiro/zh-cn
```
Setting a upper-limit quantity for posts fetching, avoiding long time waiting.
> fix(route/mashiro): set a upper-limit quantity for posts fetching

- lib/routes/zhihu/answers.ts
Close #
```routes
/zhihu/people/answers/diygod
```
> fix(route/zhihu): Use Web API for zhihu answers

- lib/routes/xjtu/yz.ts
Close #
```routes
/xjtu/yz/zsdt
```
> feat(route): add 西安交通大学研究生招生信息网

- lib/routes/pinterest/user.ts
Close #18579
```routes
/pinterest/user/howieserious
```
> fix(pinterest): add header

- lib/routes/gcores/topics.ts
Close #
```routes
/gcores/topics/recommend
```
> feat(gcores): add 机核网机组推荐

- .github/dependabot.yml
- package.json
- pnpm-lock.yaml
> chore(deps): pin art-template to 4.13.2 due to security concerns

- lib/routes/latepost/index.ts
Close #18606
```routes
/latepost/3
```
> fix(route/latepost): incorrect pubDate

- lib/routes/szse/templates/inquire.art
Close #18611
```routes
/szse/inquire
```
> fix(route/szse): incorrect url

- lib/routes/asus/bios.ts
Close #18620 
```routes
/asus/bios/rt-be88u
/asus/bios/rt-ax88u
```
When have pdid search Parma, the remote api endpoint will return error at some time, this PR aim to delete it.
> fix(routes/asus/bios): remove pdid searchparam

- lib/routes/cherrytimes/market.ts
- lib/routes/cherrytimes/namespace.ts
Close #18586
```routes
/cherrytimes/market
```
> feat(route): add cherrytimes

- lib/routes/asiafruitchina/categories.ts
- lib/routes/asiafruitchina/namespace.ts
- lib/routes/asiafruitchina/templates/description.art
Close #18605
```routes
/asiafruitchina/categories/all
```
> feat(route): add 亚洲水果果蔬品项

- lib/routes/5music/index.ts
- lib/routes/5music/namespace.ts
Close #
```routes
/5music/new-releases
```
> feat: support 5music new releases

- lib/routes/asiafruitchina/news.ts
Close #
```routes
/asiafruitchina/news
```
> feat(route): add 亚洲水果行业资讯

- lib/routes/copymanga/comic.ts
N/A
```routes
NOROUTE
```
I'm no longer intereseted in copymanga. See https://github.com/DIYgod/RSSHub/issues/17651#issuecomment-2500872402
> chore: remove myself from copymanga maintainers

- lib/routes/mycard520/namespace.ts
- lib/routes/mycard520/news.ts
Close #18653
```routes
/mycard520/category/cardgame
```
> feat(route): add MyCard娛樂中心遊戲新聞

- lib/routes/copymanga/comic.ts
Close #18621
```routes
/copymanga/comic/dianjuren/5
```
> fix(copymanga): update domain

- lib/routes/kpopping/kpics.ts
- lib/routes/kpopping/namespace.ts
Close #
```routes
/kpopping/kpics/gender-male/category-all/idol-any/group-any/order
```
> feat(route): add kpopping pics

- lib/routes/zhihu/zhuanlan.ts
Close #18610
```routes
/zhihu/zhuanlan/jinzhouji23
```
> fix(route/zhihu): Correct API path

- lib/routes/academia/topics.ts
Close #18683
```routes
/academia/topic/Urban_History
```
The remote website has changed, and now does not provide tags. The description is also truncated.
> fix(routes/academia): adapt to new design

- lib/routes/mercari/keyword.ts
- lib/routes/mercari/namespace.ts
- lib/routes/mercari/templates/item.art
- lib/routes/mercari/templates/shopItem.art
- lib/routes/mercari/types.ts
- lib/routes/mercari/util.ts
Close #8805
```routes
/mercari/create_time/desc/default/東方プロジェクト
```
> feat(route/mercari): Add route to jp.mercari.com

- lib/routes/theinitium/app.ts
Close #
```routes
/theinitium/app
```
> fix(route/theinitium): fix css selector

- lib/routes/stcn/rank.ts
Close #
```routes
/stcn/article/rank/yw
```
> feat(route): add 证券时报网热榜

- lib/routes/hrbeu/cec/list.ts
Close # 
```routes
/hrbeu/cec/xwdt
/hrbeu/cec/tzgg
/hrbeu/cec/zhbg
/hrbeu/cec/jxgz
/hrbeu/cec/kycg
/hrbeu/cec/xsgz
```
在已有/hrbeu文件夹下新建/cec/list.ts
路径为lib/routes/hrbeu/cec/list.ts
> feat(route): add 哈尔滨工程大学航天与建筑工程学院网站

- lib/routes/iplaysoft/index.ts
Close #
```routes
/iplaysoft
```
The original scraping method for iplaysoft is no longer working due to the official API ban. Therefore, we now directly scrape new content from iplaysoft via the URL.
> fix(route/iplaysoft): Update to use URL scraping due to API deprecation

- lib/routes/idaily/index.ts
Close #18709
```routes
/idaily
```
> fix(idaily): optional tags

- lib/routes/spotify/playlist.ts
Close #18288 
(as there seems to be no further response from reporter)
```routes
NOROUTE
```
添加一些关于 [Spotify 新政策](https://developer.spotify.com/blog/2024-11-27-changes-to-the-web-api)的说明以移除困惑。
> docs(spotify/playlist): add notes on Spotify restriction

- lib/routes/sciencedirect/current-issue.ts
Close #11947
```routes
/sciencedirect/journal/journal-of-financial-economics/current
```
> feat(sciencedirect): add current issue

- package.json
- pnpm-lock.yaml
Close #18719, Close #18721, Close #18722 
```routes
/kyodonews
/bilibili/user/video/443237317
```
> chore: remove html-minifier-terser override

- lib/routes/cdu/jwgg.ts
- lib/routes/cdu/tzggcdunews.ts
```routes
/cdu/tzggcdunews
```
A new routing tzggcdunews.ts has been created
> feat(route): A new routing (tzggcdunews.ts) for https://news.cdu.edu.cn/tzgg.htm has been created

- lib/routes/transformer-circuits/index.ts
- lib/routes/transformer-circuits/namespace.ts
```routes
/transformer-circuits
```
添加了 transformer-circuits 的 RSS 路由，可以获取最新的文章列表。
> feat(route): add transformer-circuits

- lib/routes/raspberrypi/magazine.ts
- lib/routes/raspberrypi/namespace.ts
- lib/routes/raspberrypi/templates/description.art
Close #18726
```routes
/raspberrypi/magazine
```
> feat(route): add Raspberry Pi Official Magazine

- lib/routes/gamekee/namespace.ts
- lib/routes/gamekee/news.ts
Close #18638
```routes
/gamekee/news
```
> feat(route/gamekee): 增加 Gamekee 新闻路由

- lib/routes/transformer-circuits/index.ts
- lib/routes/transformer-circuits/templates/article.art
Close #18729
```routes
/transformer-circuits
```
Optimize transformer-circuits route, can fetch full text now
> fix(route): optimize transformer-circuits route

- lib/routes/cw/utils.ts
Close #
```routes
/cw/today
```
> feat(route/cw): add `waitForSelector`

- lib/routes/cupl/jwc.ts
- lib/routes/cupl/namespace.ts
Close #
```routes
/cupl/jwc
```
添加中国政法大学教务处通知公告栏目路由。
> feat(route): add 中国政法大学

- lib/routes/bullionvault/gold-news.ts
Close #18746
```routes
/bullionvault/gold-news
```
> fix(route/bullionvault): missing latest articles

- lib/routes/melonbooks/namespace.ts
- lib/routes/melonbooks/parser.ts
- lib/routes/melonbooks/search.ts
Close #
```routes
/melonbooks/search/name=けいおん
```
> feat: add melonbooks

- lib/routes/4khd/article.ts
> fix(route/4khd): update image URL processing logic

- lib/routes/baobua/article.ts
- lib/routes/baobua/category.ts
- lib/routes/baobua/const.ts
- lib/routes/baobua/latest.ts
- lib/routes/baobua/namespace.ts
- lib/routes/baobua/search.ts
Close #
```routes
/baobua
/baobua/category/network
/baobua/search/cos
```
Although this website is built on WordPress, its administrator seems to have disabled the API, so it is not possible to efficiently scrape data by requesting the corresponding JSON data.
> feat(route): add route "BaoBua"

- lib/routes/diariofruticola/filtro.ts
- lib/routes/diariofruticola/namespace.ts
Close #18585
```routes
/diariofruticola/filtro/cerezas/71
```
> feat(route): add Diario Frutícola Filtro

- lib/routes/zhihu/utils.ts
> fix(route/zhihu): Allow to set `__zse_ck` in signedHeader

- lib/routes/gov/stats/index.ts
Close #18771
```routes
/gov/stats/sj/sjjd
/gov/stats/sj/zxfb
/gov/stats/xw/szyw/zyjs
```
> fix: #18771 gov stats description error

- lib/routes/zsxq/utils.ts
Close #
```routes
/zsxq/group/88855458825252
/zsxq/user/2414218251
```
Original:
Before:
After:
> fix(route/zsxq): fix excess text when parsing link text

- lib/routes/gitcode/namespace.ts
- lib/routes/gitcode/repos/commits.ts
Close #
```routes
/gitcode/commits/jeecgboot/JeecgBoot
/gitcode/commits/jeecgboot/JeecgBoot/master
/gitcode/commits/jeecgboot/JeecgBoot/springboot3
```
> feat(route): add GitCode

- lib/routes/gitcode/repos/commits.ts
Close #
```routes
/gitcode/commits/jeecgboot/JeecgBoot
/gitcode/commits/jeecgboot/JeecgBoot/master
/gitcode/commits/jeecgboot/JeecgBoot/springboot3
```
adjust route sample
> fix(route): adjust route sample

- lib/routes/gcores/program-previews.ts
Close #
```routes
/gcores/radios/preview
```
> feat(route): add 机核网预告

- lib/routes/gov/mof/gss.ts
Close #18808
```routes
/gov/mof/gss
/gov/mof/gss/zhengcefabu
/gov/mof/gss/zhengcejiedu
```
> feat(route): tariff docs by chinese gov

- lib/routes/xjtu/zs.ts
Close #
```routes
/xjtu/zs/zsxx1/zskx
```
> feat(route): add 西安交通大学本科招生网

- lib/routes/hanime1/namespace.ts
- lib/routes/hanime1/previews.ts
Close #
```routes
/hanime1/previews/202504
```
Hanime1 新番预览
> feat(route): add Hanime1

- lib/routes/reuters/common.ts
Close #18517 
```routes
/reuters/world
/reuters/world/us
```
> fix(route): resolve issue #18517 by updating headers for Reuters API

- lib/routes/jin10/category.ts
Close #none
```routes
/jin10/category/36
/jin10/category/16
/jin10/category/12
/jin10/category/50
```
> feat: added jin10 category.

- lib/routes/adquan/index.ts
- lib/routes/adquan/namespace.ts
- lib/routes/adquan/templates/description.art
> feat(route): add 广告门最新文章

- lib/routes/geocaching/blogs.ts
Close #18853 
```routes
/geocaching/blogs/en
```
> fix(route/geocaching): handle cases where large size does not exist

- lib/routes/gov/nea/ghs.ts
Close #18851
```routes
/gov/nea/sjzz/ghs
```
> fix(route/nea): incomplete description

- lib/routes/adquan/case-library.ts
Close #
```routes
/adquan/case_library
```
> feat(route): add 广告门案例库

- lib/routes/coolpc/namespace.ts
- lib/routes/coolpc/news.ts
Close #
```routes
/coolpc/news
```
> feat(route): add coolpc

- lib/routes/nytimes/rss.ts
Close #
```routes
/nytimes/rss/Homepage
```
> feat(route/nytimes): include author information in RSS feed items

- Dockerfile
- scripts/docker/minify-docker.js
Close #
```routes
/test/1
/rsshub/routes
/bluestacks/release/5
```
> chore: minify docker

- lib/routes/anthropic/news.ts
- package.json
- pnpm-lock.yaml
> fix(route/news): use p-map to limit concurrency

- lib/routes/nikkei/asia/index.ts
Close #18909
```routes
/nikkei/asia
```
> fix(route/nikkei): Find API for asia edition

- lib/app-bootstrap.tsx
- lib/app.test.ts
- lib/app.ts
> fix: request rewriter not functioning in transpiled code

- lib/routes/anytxt/namespace.ts
- lib/routes/anytxt/release-notes.ts
Close #
```routes
/anytxt/release-notes
```
> feat(route): add Anytxt Searcher Release Notes

- lib/config.ts
- lib/routes/saraba1st/digest.ts
- lib/routes/saraba1st/namespace.ts
- lib/routes/saraba1st/templates/digest.art
- lib/routes/saraba1st/thread.ts
Close #
```routes
/saraba1st/digest/forum-6-1
/saraba1st/thread/751272
```
- 添加`SARABA1ST_HOST`配置stage1st域名
- 修复stage1st默认域名
- 更新失效的example
> fix(route/saraba1st): add host config & fix broken host

- lib/routes/zxcs/namespace.ts
- lib/routes/zxcs/novel.ts
Close #
```routes
/zxcs/novel/jinqigengxin
/zxcs/novel/dushi
/zxcs/novel/xianxia
/zxcs/novel/xuanhuan
/zxcs/novel/qihuan
/zxcs/novel/lishi
/zxcs/novel/youxi
/zxcs/novel/wuxia
/zxcs/novel/kehuan
/zxcs/novel/tiyu
/zxcs/novel/lingyi
/zxcs/novel/junshi
/zxcs/novel/erciyuan
```
> feat(route): add 知轩藏书

- lib/routes/imhcg/blog.ts
Close #
```routes
/imhcg
```
原route都是空内容，现已经修复且最小程度修改
> fix(route/imhcg): 修复

- lib/routes/4khd/namespace.ts
Close #
```routes
/4khd/category/cosplay
```
Update namespace
> fix(route/4khd): Update domain

- lib/routes/hanime1/previews.ts
Close #
```routes
/hanime1/previews
```
新增默认本月新番预览
> fix(route): update previews route to support current month preview

- lib/routes/hanime1/search.ts
Close #
```routes
/hanime1/search/tags%5B%5D=1080p
```
> feat(route): add search route for Hanime1

- lib/routes/picnob/user.ts
Close #
```routes
/picnob/user/zuck
/picnob/user/zuck/tagged
```
x
> fix(route/picnob): update picnob domain

- lib/routes/jpxgmn/search.ts
- lib/routes/jpxgmn/tab.ts
- lib/routes/jpxgmn/utils.ts
- lib/routes/jpxgmn/weekly.ts
Close #18349
```routes
/jpxgmn/weekly
/jpxgmn/tab
/jpxgmn/tab/new
/jpxgmn/tab/Xiuren
/jpxgmn/search/candy
```
> fix(route/jpxgmn): get source url automatically

- lib/routes/udn/breaking-news.ts
> fix(route/udn): Correct regex

- lib/routes/huggingface/blog-community.ts
Close #
```routes
/huggingface/blog-community
/huggingface/blog-community/trending
/huggingface/blog-community/recent
```
> feat(route): add community blogs for huggingface

- lib/routes/zaimanhua/namespace.ts
- lib/routes/zaimanhua/update.ts
Close #18879
```routes
/zaimanhua/update
```
> feat(zaimanhua): add route for recent comics zaimanhua

- lib/routes/amazfitwatchfaces/index.ts
- lib/routes/amazfitwatchfaces/namespace.ts
- lib/routes/amazfitwatchfaces/templates/description.art
Close #
```routes
/amazfitwatchfaces/amazfit-x/fresh
```
> feat(route): add Amazfitwatchfaces

- lib/routes/rfi/namespace.ts
- lib/routes/rfi/news.ts
Close #19046
```routes
/rfi/cn
```
> fix(route/rfi): fix category

- lib/routes/anthropic/engineering.ts
Close #18943
```routes
/anthropic/engineering
```
> feat(route/anthropic): add engineering

- lib/routes/chongbuluo/index.ts
- lib/routes/chongbuluo/namespace.ts
Close #18970
```routes
/chongbuluo/newthread
```
> feat(route): add 虫部落

- lib/routes/zhihu/hot.ts
Close #
```routes
/zhihu/hot
```
- Require ZHIHU_COOKIE for anti-bot
> feat(route/zhihu): require ZHIHU_COOKIES for authentication

- lib/routes/ntdm/video.ts
Close #
```routes
/ntdm/video/4309
```
fix issue of `NT动漫`
> fix(route/ntdm): fix code issue for ntdm route

- lib/routes/theinitium/app.ts
- lib/routes/theinitium/templates/description.art
Close #
```routes
/theinitium/app
```
> fix(route/theinitium): fix footer

- lib/routes/zaimanhua/comic.ts
- lib/routes/zaimanhua/template/comic.art
Close #
```routes
/zaimanhua/comic/14488
```
> feat(route): add specific comic update route

- lib/routes/chnmuseum/namespace.ts
- lib/routes/chnmuseum/xingnew.ts
- lib/routes/chnmuseum/xwzt.ts
- lib/routes/zhihu/hot.ts
Close #
```routes
/chnmuseum/zx/xingnew
/chnmuseum/zx/xwzt
```
添加路由: 
- 中国国家博物馆
> feat(route): add National Museum of China

- lib/routes/unusualwhales/news.ts
Close #19104
```routes
/unusualwhales/news
```
> fix(route/unusualwhales): update api endpoint

- lib/routes/app-sales/index.ts
- lib/routes/app-sales/mostwanted.ts
- lib/routes/app-sales/namespace.ts
- lib/routes/app-sales/templates/description.art
- lib/routes/app-sales/util.ts
Close #
```routes
/app-sales/highlights
```
> feat(route): add AppSales

- lib/routes/mihoyo/templates/ys.art
- lib/routes/mihoyo/ys/news.ts
Close #
```routes
/mihoyo/ys
/mihoyo/ys/main/latest
/mihoyo/ys/main/news
/mihoyo/ys/main/notice
/mihoyo/ys/main/activity
/mihoyo/ys/zh-tw/latest
/mihoyo/ys/zh-tw/news
/mihoyo/ys/zh-tw/notice
/mihoyo/ys/zh-tw/activity
```
> fix(route/mihoyo/ys): update api endpoint

- lib/routes/cih-index/namespace.ts
- lib/routes/cih-index/report.ts
Close #18755
```routes
/cih-index/report/list/f2022041315362473358-p1-i0-oaddtime-ddesc
/cih-index/report/list/f2022041315362473314-p1-i0-oaddtime-ddesc
/cih-index/report/list/f2022041315362473376-p1-i0-oaddtime-ddesc
```
> feat(route/cih-index): add report

- lib/routes/embassy/supported-list.ts
Close #
```routes
/embassy/de
```
> fix(route/embassy/de): Update the link of the embassy/de

- lib/routes/kurogames/wutheringwaves/constants.ts
- lib/routes/kurogames/wutheringwaves/news.ts
Close #19124
```routes
/kurogames/wutheringwaves/news/zh-tw
```
> fix(route/kurogames): handle unavailable article content property

- lib/routes/3dmgame/news-center.ts
Close #19022
```routes
/3dmgame/news/acg
/3dmgame/news/game
/3dmgame/news/next
/3dmgame/news/news_36_1
```
使用Number.isNaN判断字符串导致isArcPost永远为true
> fix(route/3dmgame): fix route error

- lib/routes/bakamh/manga.ts
- lib/routes/bakamh/namespace.ts
Close #
```routes
/bakamh/manga/没有出口
```
add route bakamh.com
> feat(route): add bakamh

- lib/routes/xiaohongshu/util.ts
> fix(xiaohongshu): 修复小红书 title/updated 字段在部分情况下缺失

- lib/routes/xiaoyuzhou/podcast.ts
Close #
```routes
/xiaoyuzhou/podcast/613753ef23c82a9a1ccfdf35
```
```json
{
"type": "EPISODE",
"eid": "682690ca1ced30a23190ff47",
"pid": "613753ef23c82a9a1ccfdf35",
"title": "No.76 和播客新主播 Eva 聊她经历的前端变化、全栈进阶和对 AI 发展的思考",
"description": "VueConf 2025 要举办啦！\nWeb Worker 播客好起来了！在节目正式开始之前，给大家推荐接下来要在深圳举办的 VueConf 技术大会，众多播客嘉宾也会参与的线下活动，web worker 播客作为活动的社区伙伴鼎力推荐。你想和 Vue.js 作者尤雨溪面对面交流吗？ 一年一度的 VueConf 来啦，7 月 12 日，VueConf 2025， 不容错过！访问 vueconf.cn 了解更多会议信息、参与购票。\nVueConf 和 Web Worker 播客奇妙的缘分！\n节目介绍\n新一期播客来了，这一次 web worker 播客有了新变化，和各位听友认识一下新的播客主播 Eva，她经历丰富，是一名优秀的全栈工程师，让我们重新认识她，和她聊聊她所经历的前端发展和对未来的看法。\n时间轴\n00:00 VueConf 要来了，快来购票！\n00:34 辛宝、Smart、小白菜和新主播 Eva\n01:50 谁是 Eva？\n06:21 前端早早聊的缘分\n13:55 从零开始的第一位全职员工、遇到的挑战\n22:50 Serverless x Nest.js\n28:14 谁是 Eva? 第二部分\n31:57 Eva/辛宝/Smart 组队和 AI 组队协作的经历\n38:57 …
```
> fix(route/xiaoyuzhou/podcast): missing description

- lib/routes/tailwindcss/blog.ts
- lib/routes/tailwindcss/constants.ts
- lib/routes/tailwindcss/namespace.ts
- lib/routes/tailwindcss/utils.ts
Close #
```routes
/tailwindcss/blog
```
> feat(route/tailwindcss): add tailwindcss blog route

- lib/routes/xiaohongshu/util.ts
> fix(xiaohongshu): 移除多余的 title

- lib/routes/cngal/entry.ts
- lib/routes/cngal/weekly.ts
- lib/routes/ff14/ff14-global.ts
Close  #19163 
```routes
/cngal/weekly
/cngal/entry/2693
```
将 CnGal 新闻概览 API 替换为 api.cngal.org
> fix(route/cngal): update API endpoint in CnGal

- lib/routes/warp/blog.ts
- lib/routes/warp/namespace.ts
Close #
```routes
/warp/blog
```
> feat(route/warp): add warp blog route

- lib/routes/apple/security-releases.ts
- lib/routes/apple/templates/security-releases.art
Close #19136
```routes
/apple/security-releases
```
> feat(route): add Apple Security releases

- lib/routes/chub/characters.ts
Close #
```routes
/chub/characters
```
> fix(route/chub): Update api url

- lib/routes/youtube/community.ts
Close #19153
```routes
/youtube/community/@TheMarketMemo
```
> fix(route/youtube/community): handle empty post title

- package.json
- patches/@bbob__core@4.2.0.patch
- patches/@bbob__parser@4.2.0.patch
- patches/@bbob__plugin-helper@4.2.0.patch
- patches/@bbob__preset-html5@4.2.0.patch
- patches/@bbob__preset@4.2.0.patch
- pnpm-lock.yaml
Close #
```routes
/counter-strike/news
```
Workaround for https://github.com/JiLiZART/BBob/issues/135
fix cannot find module in https://github.com/DIYgod/RSSHub/pull/19176#issuecomment-2902097348
> fix(patches): add patches for bbob dependencies

- lib/routes/xjtu/ee-jzxx.ts
Close #
```routes
/xjtu/ee/jzxx
/xjtu/ee/jzxx/bks
/xjtu/ee/jzxx/yjs
/xjtu/ee/jzxx/kyxs
/xjtu/ee/jzxx/cgzb
/xjtu/ee/jzxx/zpjy
/xjtu/ee/jzxx/xzbg
```
修复了原来路由当中重复标题显示的问题，并添加了附件内容
> fix(route/xjtu/ee): fix duplicate title and add appendix content

- lib/routes/yuanliao/index.ts
- lib/routes/yuanliao/namespace.ts
Close #
```routes
/yuanliao
```
> feat(route): add 猿料社区

- lib/routes/steam/news.ts
- package.json
- pnpm-lock.yaml
Close #
```routes
/steam/news/958260/schinese
/steam/news/1046480/schinese
```
> feat(route/steam/news): update BBCode rendering to match the official feed

- lib/routes/steam/news.ts
Close #
```routes
/steam/news/958260/schinese
/steam/news/1046480/schinese
```
> fix(route/steam/news): fix wrong item images & YouTube full screen

- lib/routes/picnob/user.ts
Close #19191
```routes
/picnob/user/xlisa_olivex
```
> fix(route): clean up

- lib/middleware/template.test.ts
- lib/middleware/template.tsx
- lib/registry.ts
- lib/routes/test/api-index.ts
- lib/routes/xiaohongshu/check-cookie.ts
- lib/routes/xiaohongshu/user.ts
- lib/routes/xiaohongshu/util.ts
- lib/types.ts
- scripts/workflow/build-routes.ts
> feat: api route

- lib/routes/thepaper/utils.ts
Close #
```routes
/thepaper/featured
```
Link example:
https://m.thepaper.cn/series/1120
> fix(route/thepaper): enhance pubDate handling with relative date parsing

- lib/routes/zhihu/all-collections.ts
- lib/routes/zhihu/collection.ts
- lib/routes/zhihu/topic.ts
- lib/routes/zhihu/zhuanlan.ts
Close #18758, #18636
```routes
/zhihu/posts/people/Dramaturge
/zhihu/people/allCollections/Dramaturge
/zhihu/collection/979331166
/zhihu/topic/21299817
/zhihu/zhuanlan/c_1876004568229371904
```
由于知乎反爬限制，有一些旧的route失效了，本PR将他们修复了。修复的route已经被列举在上文example中了。
> fix: repair some zhihu routes

- lib/routes/picuki/namespace.ts
- lib/routes/picuki/profile.ts
- lib/routes/picuki/utils.ts
Close #14090
```routes
/picuki/profile/tsubasakirara
```
> feat(route/picuki): update for tiktok

- lib/routes/stheadline/std/realtime.ts
Close #
```routes
/stheadline/std/realtimenews
```
> fix(route/stheadline): Adapt to website redirect

- lib/routes/everia/namespace.ts
- lib/routes/everia/tag.ts
Close #
```routes
/everia/tag/hinatazaka46-日向坂46
```
> feat: add route for everia.club

- lib/routes/radio/album.ts
- lib/routes/radio/templates/description.art
Close #14271
```routes
/radio/album/15682083075294
```
> fix(route/radio): use new api

- lib/routes/civitai/user.ts
Close #18478
```routes
/civitai/user/Chenkin/articles
```
> feat(civitai): add user article

- lib/routes/xiaohongshu/user.ts
- lib/routes/xiaohongshu/util.ts
> feat(xiaohongshu): update guid generation for user feeds and notes

- lib/routes/freewechat/profile.ts
Close #
```routes
/freewechat/profile/MzI5NTUxNzk3OA==
```
> fix(route/freewechat): add ua

- lib/routes/huawei/developer/harmonyos/samplecode.ts
- lib/routes/huawei/namespace.ts
Close #
```routes
huawei/developer/harmonyos/sample-code
```
> feat(route): 添加华为开发者联盟 HarmonyOS 示例代码路由

- lib/routes/smartlink/index.ts
- lib/routes/smartlink/namespace.ts
Close #
```routes
/smartlink/bloombergbusiness
/smartlink/bloombergpursuits
/smartlink/businessweek
/smartlink/cnbc
```
The current implementation support API in `https://smartlink.bio/api/instagram/${site}/posts` format. I haven't found any smartlink.bio with none instagram path. I can update if it is needed
> feat: add route smartlink.bio

- lib/routes/bupt/scss.ts
Close #
```routes
bupt/scss/tzgg
```
> feat(route): 添加北京邮电大学网安学院通知公告的路由

- lib/routes/aibase/daily.ts
- lib/routes/aibase/util.ts
Close #18455 
```routes
/aibase/daily
```
> feat(route): add route aibase/daily

- lib/routes/android/security-bulletin.ts
Close #19137
```routes
/android/security-bulletin
```
> feat(route): add android security bulletins

- lib/routes/njust/cs.ts
Close #
```routes
/njust/cs/xyxw
```
新增南京理工大学计算机学院路由。
> feat(route): add njust/cs

- lib/config.ts
- lib/routes/mixi2/community.ts
- lib/routes/mixi2/discovery.ts
- lib/routes/mixi2/home.ts
- lib/routes/mixi2/namespace.ts
- lib/routes/mixi2/user.ts
- lib/routes/mixi2/utils.ts
- package.json
- pnpm-lock.yaml
Close #19358 
```routes
/mixi2/home
/mixi2/discovery
/mixi2/user/@deyo
/mixi2/user/@deyo/media
/mixi2/community/62e7e813-d242-4c54-a0ee-0aab5b2bbad2
/mixi2/community/62e7e813-d242-4c54-a0ee-0aab5b2bbad2/media
```
需要登录，测试实例 https://rsshub-dev.karasu.moe
> feat(route): mixi2

- lib/routes/tver/series.ts
Close #
```routes
/tver/series/srx2o7o3c8
```
> fix(route/tver): Fix route configuration and optimize image sizes

- lib/routes/copymanga/comic.ts
Close #19227
```routes
/copymanga/comic/xiangyaochengweiyingzhishilizhe/10
```
> fix(route/copymanga): fix comic

- lib/routes/windsurf/changelog.ts
- lib/routes/windsurf/namespace.ts
Close #
```routes
/windsurf/changelog
```
> feat(route): add Windsurf Changelog

- lib/routes/augmentcode/blog.ts
- lib/routes/augmentcode/namespace.ts
- lib/routes/augmentcode/templates/description.art
Close #
```routes
/augmentcode/blog
```
> feat(route): add Augmentcode Blog

- lib/routes/mastodon/tag.ts
Close #
```routes
/mastodon/tag/mastodon.social/gochisou/true
```
> feat(route): add Mastodon hashtag timeline

- lib/routes/windsurf/blog.ts
- lib/routes/windsurf/templates/description.art
Close #
```routes
/windsurf/blog
```
> feat(route): add Windsurf Blog

- lib/routes/sjtu/seiee/icisee.ts
Close #
```routes
/sjtu/seiee/icisee/news
/sjtu/seiee/icisee/notice
```
> feat(route/sjtu): Add route for icisee

- lib/routes/cockroachlabs/blog.ts
- lib/routes/cockroachlabs/namespace.ts
No issue related
```routes
/cockroachlabs/blog/engineering
/cockroachlabs/blog
```
> feat(route): add blogs from cockroach labs

- lib/routes/chocolatey/namespace.ts
- lib/routes/chocolatey/packages.ts
Close #
```routes
/chocolatey/packages/microsoft-edge
```
> feat(route): add Chocolatey Packages

- lib/routes/metacritic/index.ts
Close #
```routes
/metacritic/tv/new/network=prime-video&genre=documentary
```
> fix: Update metacritic apiURL

- lib/routes/nifd/research.ts
Close #19460
```routes
/nifd/research/3d23ba0e-4f46-44c2-9d21-6b38df4cdd70
```
> fix(route): add pdf files of nidc papers

- lib/routes/gov/chongqing/sydwgkzp.ts
Close #19429
```routes
/gov/chongqing/sydwgkzp
/gov/chongqing/sydwgkzp/2024
/gov/chongqing/sydwgkzp/2025
```
> fix(route/sydwgkzp): 修复 重庆市人社局事业单位公开招聘 今年数据抓取异常

- lib/routes/liquipedia/cs-matches.ts
No issue related
```routes
/liquipedia/counterstrike/matches/Team_Falcons
/liquipedia/counterstrike/matches/FaZe_Clan
```
A minor fix. The tournament name is in the fifth column of the table now.
> fix(route): update tournament name

- lib/routes/udn/breaking-news.ts
> feat(route/udn): Refine `author` property

- lib/routes/makerworld/user-upload.ts
Close #19494
```routes
/makerworld/user/@Wcad00/upload
```
> fix(route): update example path for user uploads

- lib/routes/paulgraham/article.ts
Close #
```routes
/paulgraham/articles
```
> fix(route): fix root URL for paulgraham, as http was not allowed

- lib/routes/instagram/web-api/index.ts
- lib/routes/instagram/web-api/utils.ts
Close #15061
```routes
/instagram/2/user/stefaniejoosten
/instagram/2/tags/yoasobi
```
<details><summary>/instagram/2/user/stefaniejoosten</summary>
</details>
<details><summary>/instagram/2/tags/yoasobi</summary>
</details>
> fix(route/instagram): fix cookie route

- lib/routes/sehuatang/index.ts
This reverts commit 85fb1e8.
Close #19196
```routes
/sehuatang/bt/97
```
> fix(route/sehuatang): get safe id

- lib/routes/fantube/creator.ts
- lib/routes/fantube/namespace.ts
- lib/routes/fantube/templates/post.art
- lib/routes/fantube/types.ts
- lib/routes/fantube/utils.ts
Close #
```routes
/fantube/r18/creator/miyuu
```
> feat(route/fantube): add user posts

- lib/routes/udn/breaking-news.ts
Close #
```routes
/udn/news/breakingnews/4
```
> fix(route/udn): Adapt to property `publisher` change

- lib/config.ts
- lib/routes/lofter/tag.ts
Close #19357
```routes
/lofter/tag/cosplay/date
```
↑ 挂了正常，现在只能自搭
需要配置环境变量 LOFTER_COOKIE: 用于搜索标签相关内容，获取方式：
1.  登录 Lofter 并搜索任一标签，进入页面 https://www.lofter.com/tag/*
2.  打开控制台，切换到 Network 面板，刷新
3.  点击 TagBean.seach.dwr 请求，找到 Cookie
4.  获取最新标签内容只要求 `LOFTER_SESS` 开始的字段
> fix(route/lofter): fix Lofter tag route requiring cookie

- lib/routes/musify/index.ts
- lib/routes/musify/namespace.ts
Close #
```routes
/musify/en
```
> feat(route): add musify

- lib/routes/visionias/daily-news-summary.ts
- lib/routes/visionias/monthly-magazine.ts
- lib/routes/visionias/news-today.ts
- lib/routes/visionias/utils.ts
- lib/routes/visionias/weekly-focus.ts
Close #
```routes
/visionias/monthlyMagazine
/visionias/dailySummary
/visionias/newsToday
/visionias/weeklyFocus
```
> feat(visionias): add routes for vision IAS

- lib/routes/kaopu/news.ts
Close #
```routes
/kaopu/news
```
Use the latest API url
> fix: fix kaopu news api url

- lib/routes/ximalaya/album.ts
- lib/routes/ximalaya/types.ts
- lib/routes/ximalaya/utils.ts
Close #19411
```routes
/ximalaya/album/82608924/0/false
```
No audio enclosure for the time being.
> fix(route/ximalaya): fix isPaid

- lib/routes/nankai/namespace.ts
- lib/routes/nankai/yzb.ts
Close #
```routes
/nankai/yzb/2552
/nankai/yzb/5509
/nankai/yzb/2562
```
* 添加nankai命名空间
* 添加nankai/yzb路由
> feat(route): Add 南开大学研究生招生网

- lib/routes/bilibili/dynamic.ts
Close #
```routes
/bilibili/user/dynamic/353240497
```
Prevent HTML tags like `<br>` from being injected into the title by using the original description before any processing occurs.
The processed description with HTML formatting is still used for the content body, while the title remains clean.
> fix(route/bilibili): preserve original description for dynamic title

- lib/routes/taobao/mysql.ts
- lib/routes/taobao/namespace.ts
Close #
```routes
/taobao/mysql/monthly
```
> feat(route): add 数据库内核月报

- lib/routes/dnaindia/common.ts
Close #
```routes
/dnaindia/headlines
/dnaindia/topic/dna-verified
```
> fix(date parse): Dna india

- lib/routes/jamesclear/book-summaries.ts
- lib/routes/jamesclear/great-speeches.ts
- lib/routes/jamesclear/namespace.ts
- lib/routes/jamesclear/quotes.ts
- lib/routes/jamesclear/three-two-one.ts
- lib/routes/jamesclear/utils.ts
Close #
```routes
/jamesclear/3-2-1
/jamesclear/quotes
/jamesclear/great-speeches
/jamesclear/book-summaries
```
> feat(jamesclear): add jamesClear 

- lib/routes/nankai/notice.ts
- 【功能】支持抓取南开大学通知公告列表及详情内容
- 【功能】处理内网通知无法访问时的提示
Close #
```routes
/nankai/notice
```
新增南开大学通知公告路由 
支持抓取南开大学通知公告列表及详情内容
处理内网通知无法访问时的提示
> feat(route): 新增南开大学通知公告路由

- lib/routes/nankai/jwc.ts
- 添加nankai/jwc路由，抓取通知公告列表
- 支持公告详情内容获取与PDF链接处理
- 自动转换相对链接为绝对链接
- 适配发布时间和内容解析
Close #
```routes
/nankai/jwc
```
> feat(route): 新增南开大学教务处通知公告路由

- lib/routes/kiro/blog.ts
- lib/routes/kiro/namespace.ts
Close #
```routes
/kiro/blog
```
> feat(route): add Kiro Blog

- lib/routes/sicau/jiaowu.ts
Close #
```routes
/sicau/jiaowu/jxtz
/sicau/jiaowu/jxtz/detail
```
Remove white spaces from the description and add some tips
> fix(route): Remove white spaces from the description

- lib/routes/hit/hitgs.ts
- lib/routes/hit/templates/description.art
Close #19602
```routes
/hit/hitgs/tzgg
```
> fix(route): 哈尔滨工业大学研究生院

- lib/routes/sotwe/namespace.ts
- lib/routes/sotwe/user.ts
Close #
```routes
/sotwe/user/_RSSHub
/sotwe/user/DIYgod
```
A twitter alternative
> feat(route/sotwe): add sotwe

- lib/config.ts
- lib/routes/tumblr/namespace.ts
- lib/routes/tumblr/posts.ts
- lib/routes/tumblr/utils.ts
```routes
/tumblr/posts/biketouring-nearby
/tumblr/posts/biketouring-nearby?limit=10
```
Adds a Tumblr rotue to fetch posts. This complement Tumblr official routes that is not compatible with "dashboard only" blogs and requires an authenticated API call (e.g. https://magicdreamspoetry.tumblr.com/rss).
`http://127.0.0.1:1200/tumblr/posts/magicdreamspoetry.tumblr.com?key=test&limit=5`
<details>
<summary>XML Source</summary>
```xml
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
<channel>
<title>Tumblr - magicdreamspoetry.tumblr.com - Posts</title>
<link>https://www.tumblr.com/blog/view/magicdreamspoetry</link>
<atom:link href="http://127.0.0.1:1200/tumblr/posts/magicdreamspoetry.tumblr.com/limit=5?key=test" rel="self" type="application/rss+xml"/>
<description>La vida no se …
```
> feat(tumblr): Add Tumblr posts route

- lib/types.ts
> feat(types): export Language and Category for better TS type Inference

- lib/routes/upc/jwc.ts
Close #
```routes
/upc/jwc
/upc/jwc/18519
/upc/jwc/18520
/upc/jwc/544
```
When accessing /upc/jwc, the router occasionally triggers a FetchError. Because the router incorrectly complete absolute links when processing external URLs. I fixed this bug and added handling when fetching failed.
> fix(route/upc): fix FetchError bug when fetching the Full Text

- lib/routes/manus/blog.ts
- lib/routes/manus/namespace.ts
Close #
```routes
/manus/blog
```
This PR depends on #19651, please review #19651 before review this PR.
> feat(routes/manus/blog): add manus blog route

- lib/routes/newswav/latest.ts
- lib/routes/newswav/namespace.ts
Close #19570
```routes
/newswav
```
> feat(route/newswav): add latest news

- lib/routes/capitalmind/insights.ts
- lib/routes/capitalmind/namespace.ts
- lib/routes/capitalmind/podcasts.ts
- lib/routes/capitalmind/utils.ts
Close #
```routes
/capitalmind/podcasts
/capitalmind/insights
```
> feat(capitalmind): add capital mind

- lib/routes/deeplearning/the-batch.ts
No related issue yet.
```routes
/deeplearning/the-batch
/deeplearning/the-batch/data-points
```
> fix(routes/deeplearning): fix json parsing path

- lib/routes/rockthejvm/articles.ts
- lib/routes/rockthejvm/namespace.ts
- lib/routes/rockthejvm/templates/description.art
Close #
```routes
/rockthejvm/articles
```
> feat(route): add Rock the JVM Articles

- lib/routes/hanime1/search.ts
Close #
```routes
/hanime1/search/query=辣妹
```
> fix(route/hanime1): fix wrong return property

- lib/routes/expats/czech-news.ts
- lib/routes/expats/namespace.ts
Close #19670
```routes
/expats/czech-news/daily-news
```
> feat(route): add Expats.cz Czech News

- lib/routes/coomer/index.ts
- lib/routes/coomer/namespace.ts
- lib/routes/kemono/const.ts
- lib/routes/kemono/index.ts
- lib/routes/kemono/namespace.ts
Close #
```routes
/coomer/onlyfans/belledelphine
/kemono/patreon/11666662
```
> fix(routes): migrate coomer and kemono to new domains, standardize GUID generation format

- lib/routes/landiannews/category.ts
- lib/routes/landiannews/index.ts
- lib/routes/landiannews/tag.ts
Close #19684 
```routes
/landiannews
/landiannews/tag/linux-kernel
/landiannews/category/sells
```
Seem like landiannews have been update wordPress version, need add search params to fix.
> fix(routes/landiannews): fix _embed search params

- lib/routes/openai/cookbook.ts
Close #
```routes
/openai/cookbook
```
修改class选择器选中所需cookbook元素。
> fix(route/openai): tweak openai cookbook class css selector

- lib/routes/grist/utils.ts
Close #
```routes
/grist
/grist/featured
/grist/series/best-of-grist
/grist/topic/extreme-heat
```
> fix(grist): payload changed

- lib/routes/cursor/changelog.ts
- lib/routes/cursor/namespace.ts
Close #
```routes
/cursor/changelog
```
There were two RSSHub feeds.
But both were broken.
1. https://rsshub.app/cursor/changelog
- FetchError happened
2. https://rsshub.seckv.com/cursor/changelog
- Can fetch feeds, but title, link, and pubDate are broken. The site structure may be changed.
So I fixed these errors.
> fix(route): fix /cursor/changelog route

- lib/routes/zaobao/util.ts
Close #19751
```routes
/zaobao/znews/china
```
> fix(route/zaobao): Misc refactor

- lib/routes/sohu/mp.ts
Close #19732
```routes
/sohu/mp/c29odXptdGhnbjZ3NEBzb2h1LmNvbQ==
```
> fix(route/sohu): add auth token

- lib/routes/coomer/index.ts
- lib/routes/kemono/index.ts
> fix(radar): correct target paths for coomer and kemono routes

- lib/routes/neu/yz.ts
```routes
/neu/yz/master1
/neu/yz/master2
/neu/yz/phd1
/neu/yz/phd2
/neu/yz/download
```
添加了neu 研招网的硕士公告、硕士简章、博士公告、博士简章、下载中心。
> feat(routes/neu): add yz route

- lib/routes/mit/hanlab.ts
- lib/routes/mit/namespace.ts
Close #19794
```routes
/mit/hanlab/blog
```
> feat: Add RSS feed for MIT HAN Lab Blog

- lib/routes/nio/namespace.ts
- lib/routes/nio/nioradio.ts
```routes
/nio/nioradio/5
/nio/nioradio/23
```
添加 NIO Radio 播客支持
> feat(route/nio): add NIO Radio route

- lib/routes/coomer/index.ts
- lib/routes/kemono/index.ts
Close #19832
```routes
/coomer/onlyfans/projektbutt
/kemono/fanbox/3316400
/kemono/fanbox/3316400/fancards
/kemono/fanbox/3316400/announcements
```
> fix(routes): update API path to fetch post data for coomer / kemono (close #19832)

- eslint.config.mjs
- lib/routes/youtube/api/youtubei.ts
- lib/routes/youtube/utils.ts
Close #
```routes
/youtube/user/%40antfu?format=json
/youtube/user/%40linksphotograph?format=json
```
`unicorn/no-nested-ternary` rule conflicts with prettier
> fix(route/youtube): cache getSubtitles

- lib/routes/setn/index.ts
Close #
```routes
/setn
```
- timezone: Timezone error, 8-hour difference
- title: Should use complete title from content page, as some list page's title is a short version
- author: Fix data source extraction
> fix(route/setn): fix incorrect timezone & title & author

- lib/routes/gitstar-ranking/index.ts
- lib/routes/gitstar-ranking/namespace.ts
- lib/routes/gitstar-ranking/templates/description.art
Close #
```routes
/gitstar-ranking/repositories
```
> feat(route): add Gitstar Ranking

- lib/routes/immich/cursed-knowledge.ts
- lib/routes/immich/namespace.ts
Close #
```routes
/immich/cursed-knowledge
```
> feat(route/immich): add cursed knowledge

- lib/routes/elecfans/article.ts
- lib/routes/elecfans/namespace.ts
- lib/routes/elecfans/soft.ts
Close #
```routes
/elecfans/article/special
/elecfans/article/commend
/elecfans/article/hot
/elecfans/article/original
/elecfans/soft/special
/elecfans/soft/commend
/elecfans/soft/hot
```
> feat(route): add router for www.elecfans.com

- lib/routes/thegadgetflow/namespace.ts
- lib/routes/thegadgetflow/rss.ts
- lib/routes/thegadgetflow/templates/description.art
Close #
```routes
/thegadgetflow/cool-gadgets-gifts
/thegadgetflow
```
> feat(route): the gadget flow

- lib/routes/gamer/gnn-index.ts
Close https://github.com/RSSNext/Folo/issues/4387
```routes
/gamer/gnn
```
> fix(route/gnn): remove empty div, limit concurrency

- lib/routes/lovelive-anime/topics.ts
```routes
/lovelive-anime/topics/yuigaoka
/lovelive-anime/topics/nijigasaki
```
This fixes img URL for base url ending with a slash (`topics/` or `news/`)
> fix(routes/lovelive-anime): correct relative img URL resolving

- lib/routes/bilibili/cache.ts
- lib/routes/youtube/api/youtubei.ts
> fix(route): remove useless encodeURIComponent

- lib/routes/youtube/community.ts
Close #
```routes
/youtube/community/@JFlaMusic
```
> fix(route/youtube): fix community post url

- lib/routes/apple/podcast.ts
Close #19880
```routes
/apple/podcast/id1751418168/us
```
> fix(route/apple): fix paid podcast retrieval

- lib/routes/anthropic/news.ts
also fixed the type warnings
Title and pubDate not found. 
```routes
```
> fix(route): title and pubDate not found issue

- lib/routes/nicovideo/mylist.ts
- lib/routes/nicovideo/types.ts
- lib/routes/nicovideo/utils.ts
Close #
```routes
/nicovideo/mylist/2973737
```
Created this because the official feed is scheduled to be discontinued.
- Announcement: https://blog.nicovideo.jp/niconews/255055.html
- Existing official feed (example): https://www.nicovideo.jp/user/2/mylist/2973737?rss=atom
> feat(route): add Niconico Mylist

- lib/routes/koyso/index.ts
- lib/routes/koyso/namespace.ts
- lib/routes/koyso/templates/description.art
Close #
```routes
/koyso/0/latest
```
- [ x] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
> feat(route): add Koyso

- lib/routes/coolbuy/index.ts
- lib/routes/coolbuy/namespace.ts
- lib/routes/coolbuy/templates/description.art
Close #
```routes
/coolbuy
```
> feat(route): add 玩物志

- lib/routes/radio-canada/latest.ts
Close #19908 
```routes
/radio-canada/latest/fr
/radio-canada/latest/en
/radio-canada/latest/es
/radio-canada/latest/zh-hans
/radio-canada/latest/zh-hant
/radio-canada/latest/ar
/radio-canada/latest/pa
/radio-canada/latest/tl
```
> fix(route): radio-canada

- lib/server.ts
Close #14622 
```routes
NOROUTE
```
This PR fixes an issue that Vercel cannot recognize the exported app as a hono app.
I believe it will make [rsshub-vercel](https://github.com/RSSNext/rsshub-vercel) build success.
https://community.vercel.com/t/no-valid-entrypoint-found-valid-entrypoints-are-hono/21135
cc @DIYgod
> fix(vercel): sync export default hono app

- lib/routes/bilibili/cache.ts
Close #19893
```routes
/bilibili/user/video/504018708
```
> fix(route/bilibili): check empty cid

- lib/routes/theverge/index.ts
Close #
```routes
/theverge
```
> fix(route/theverge): correct block type handling and improve rendering logic

- lib/routes/pubscholar/utils.ts
Close #
```routes
/pubscholar/explore
```
> fix(route/pubscholar): add x-finger

- lib/routes/samrdprc/index.ts
- lib/routes/samrdprc/namespace.ts
Close #20037
```routes
/samrdprc/xwdt/gzdt
```
> feat(route): add 国家市场监督管理总局缺陷产品管理中心

- lib/routes/hupu/index.ts
- lib/routes/hupu/types.ts
Close #
```routes
/hupu
/hupu/nba
/hupu/cba
/hupu/soccer
```
> feat(route/hupu)!: index support

- lib/routes/letterboxd/index.ts
- lib/routes/letterboxd/namespace.ts
Close #20045 
```routes
/letterboxd/matthew/watchlist
/letterboxd/tedsmovies/watchlist
```
> feat(route): letterboxd watchlist

- lib/routes/itch/devlog.ts
Close #
```routes
/itch/devlog/caribdis/eternum
/itch/devlog/rarealexturan/secretcarecafe
```
fix the incorrect authors for itch.io devlogs
> fix(itch): incorrect devlog authors

- lib/routes/natgeo/natgeo.ts
移除右側熱門精選文章
```routes
/natgeo/explore/photo
```
> fix(route/natgeo): filter out irrelevant items

- lib/routes/google/jules.ts
Close #
```routes
/google/jules/changelog
```
> feat(route): add google jules

- lib/routes/techcrunch/news.ts
Close #
```routes
/techcrunch/news
```
cleanup content
> fix(route): remove rich block

- lib/routes/yahoo/news/utils.ts
Close #
```routes
/yahoo/news/list/tw/7e0d59b1-e084-4ca7-955e-ae582e3e973d
```
> fix(route/yahoo): update ldJson extraction

- lib/routes/baozimh/index.ts
Close #
```routes
/baozimh/comic/shidaorujinxihuanshangliaoqingmeizhuma-wanhushiming
```
> feat: extract more chapters

- lib/routes/naturalism/namespace.ts
- lib/routes/naturalism/new.ts
Close #19644
```routes
/naturalism
```
> feat(route/naturalism): add what's new

- lib/routes/cursor/blog.ts
https://cursor.com/blog
```routes
/cursor/blog
/cursor/blog/product
```
> feat: add cursor blog

- lib/routes/investor/index.ts
Close #20107
```routes
/investor/zczx/qwzx/hyxhfb
```
> fix(route): correct broken links to investor.org.cn

- lib/routes/udn/global/index.ts
- lib/routes/udn/global/tag.ts
Close #
```routes
/udn/global
/udn/global/editor
/udn/global/tag
/udn/global/tag/深度專欄
```
> fix(route/udn/global): Update selectors and add category handling

- lib/routes/anthropic/news.ts
Close #
```routes
```
This PR ensures article content is included in RSS feed items.
Currently only the article hero (illustration) is displayed.
> fix(route/anthropic): ensure news route includes article content

- lib/routes/altotrain/namespace.ts
- lib/routes/altotrain/news.ts
```routes
/altotrain/en
/altotrain/fr
```
> feat(route): add Alto Canada Train

- lib/routes/chinatimes/index.ts
- lib/routes/chinatimes/namespace.ts
Close #13385
```routes
/chinatimes/realtimenews
```
Recover from #13492
> feat(route): add chinatimes from

- lib/routes/nhk/news.ts
Close #
```routes
/nhk/news/en
/nhk/news/zh
```
Update news source.
舊有的來源已經不能使用，更新新的新聞來源。
> fix(route/nhk/news): update news source
