DIYgod/RSSHub

- .dockerignore
- Dockerfile
- docker-compose.yml
- process.json
添加 Dockerfile 和 docker-compose.yml 文件。
由于缓存方式是在 config.js 中设置的，所以不添加 redis 容器。
> add Dockerfile docker-compose .dockerignore process.json files.

- router.js
- routes/jandan/pic.js
Signed-off-by: Xuanwo <xuanwo.cn@gmail.com>
> Add jandan pic support

- index.js
- middleware/utf8.js
> fix: incorrect `utf-8` characters

- routes/ziroom/room.js
> fixed #60 自如房源返回数据处理

- router.js
- routes/biquge/chapter.js
- views/rss.art
使用方法
举例: https://rss.now.sh/biquge/novel/latestchapter/52_52542
路由: /biquge/novel/latestchapter/:id
参数: id，小说的 id，可在小说主页 URL 中找到
https://www.biquge5200.com/52_52542/
还有修改 RSS 模版文件 
添加  <image>元素
> 增加 笔趣阁 https://www.biquge5200.com/ 小说最新章节 RSS

- package.json
- routes/tucaoqq/post.js
- utils/md5.js
> refactor: remove the dependence of npm package 'js-md5'

- router.js
- routes/pixiv/api/getBookmarks.js
- routes/pixiv/api/getIllusts.js
- routes/pixiv/api/getRanking.js
- routes/pixiv/api/getUserDetail.js
- routes/pixiv/bookmarks.js
- routes/pixiv/ranking.js
> feat: pixiv bookmarks rss

- middleware/onerror.js
当前的报错信息不含有报错堆栈信息，排错只能打断点。
在这个pr中我追加了报错的堆栈信息。
> fix: error message useful for developers

- docs/README.md
- router.js
- routes/toutiao/today.js
- routes/toutiao/user.js
包括 今日头条 和 独家号
fixed #88 
closed #88
> 添加开发者头条  RSS

- routes/zhihu/activities.js
updates:
1. add images of 知乎想法
2. fix issue "关注了专栏: undefined"
> update zhihu activities features

- routes/zhihu/activities.js
- fix(zhihu activities): "关注了话题: undefined" issue
> add 'topic' feed for zhihu activities

- routes/bilibili/liveArea.js
另修正游戏/手游/绘画分区 RSS link 指向错误的问题
> 修正B站直播游戏/手游分区订阅失败

- docker-compose.yml
- docs/install/README.md
> Support Redis cache for docker

- docs/install/README.md
修改部分文案。
增加配置 RSSHub 和 使用 redis 的教程。
> docs(install): config and redis tutorial

- .travis.yml
- package.json
- yarn.lock
删除 git hook，防止 commmit changed files 混乱，避免在不知情的情况下修改代码。
在 .travis.yml 中增加 lint 检查。
> build: better ci process and git hook

- docs/README.md
- middleware/template.js
- views/json.art
https://jsonfeed.org/version/1
> app: use JSON Feed as json format

- routes/jandan/pic.js
Fixed https://github.com/DIYgod/RSSHub/issues/175
> Fix jandon pic algorithm

- routes/zhihu/daily.js
> fix: story url

- routes/zhihu/zhuanlan.js
非常抱歉做了这么多次尝试, 仍然没有把知乎返回的错误很好地显示出来.
希望这次能起作用.
> fix: throw zhihu if status is not 200

- routes/jike/user.js
增加解析即刻用户动态中的创建主题类消息
目前这类消息会以 undefined 的形式出现：
此 pr 后效果：
> 即刻用户动态中的创建主题类消息

- views/json.art
> fix: fix JSON format

- Dockerfile
手机上随便弄了一下，能跑了。
其实就是dockerfile的入口没有指定的问题
> 尝试简单修复一下Docker

- router.js
> fix: add cctv to router

- README.md
- docs/README.md
- router.js
- routes/mozilla/firefox.js
> #177 Firefox release note RSS

- routes/qidian/chapter.js
> 改变起点章节的获取方式

- routes/greasyfork/scripts.js
- routes/scnu/cs/match.js
- routes/scnu/jw.js
- routes/scnu/library.js
axios 中设置 headers 的参数应该是 `headers` 而不是 `header`
> fix axios params error

- docs/README.md
> Fix a minor typo

- docs/en/README.md
- docs/en/install/README.md
- docs/en/joinus/README.md
- docs/en/support/README.md
> Add docs in EN

- routes/bilibili/dynamic.js
- routes/bilibili/topic.js
> fix:B站动态未识别功能的条目跳转动态详情页

- routes/hopper/index.js
prevent application from throwing an error
> Skip when hopper returns no result

- docs/en/README.md
> Clarify #582

- routes/cas/sim/academic.js
> cas: fix linting violation: array-callback-return

- routes/namoc/announcement.js
- routes/namoc/exhibition.js
- routes/namoc/media.js
- routes/namoc/news.js
- routes/namoc/specials.js
Also fix `no-await-in-loop` in namoc routes.
Fix #586.
> Update namoc routes due to website updates

- routes/dongqiudi/daily.js
> dongqiudi: fix linting violation: no-await-in-loop

- routes/google/scholar.js
> googlescholar: fix linting violation: no-await-in-loop

- routes/dapenti/tugua.js
> dapenti: fix linting violation: no-await-in-loop

- routes/bjnews/news.js
> bjnews: fix linting violation: no-await-in-loop

- routes/one/index.js
> one: fix linting violation: no-await-in-loop

- routes/zhihu/daily.js
> zhihu: fix linting violation: no-await-in-loop

- routes/3dm/download.js
- routes/3dm/news.js
- routes/3dm/news_center.js
> 3dm: fix linting violation: no-await-in-loop

- routes/pixiv/token.js
> pixiv: disable lint warning

- routes/t66y/index.js
> t66y: fix linting violation: no-await-in-loop

- docs/README.md
- router.js
- routes/douban/latest_book.js
- routes/douban/latest_music.js
> douban latest book and  music support

- routes/universities/pku/eecs.js
1. fix item link 404 error 
2. add default title
> Fix PKU EECS Notification Link return 404

- docs/README.md
- package.json
- router.js
- routes/jike/topicText.js
- yarn.lock
Fix #635, partially fix / #621
> Add jike/topicText

- docs/README.md
- router.js
- routes/sspai/series.js
> Add sspai/series

- routes/weibo/utils.js
> Fix weibo/utils wrong timezone issue

- docs/README.md
- routes/atfd/index.js
- routes/hopper/index.js
- routes/jike/topicText.js
- routes/weibo/utils.js
先 merge #665, 分支的时候不小心包括了 #665,
> Improve date format handling in some routes

- docs/README.md
- router.js
- routes/universities/cqust/jw.js
- routes/universities/cqust/lib.js
> Add CQUST Notifications

- config.js
- docs/en/install/README.md
- docs/install/README.md
- middleware/template.js
> Add option to set value for limiting title length

- docs/README.md
- router.js
- routes/thepaper/featured.js
> Add 澎湃新闻 - 首页头条

- docs/README.md
- docs/en/README.md
- routes/firefox/release.js
> firefox improve

- docs/README.md
🍺修缮一下path部分错误的文档内容
```
path="/universities/...
```
> Fix the path in docs/README.md

- docs/README.md
- router.js
- routes/universities/sctu/jwc.js
- routes/universities/sctu/xgxy.js
增加四川旅游学院教务处RSS，第一次pull request，多有不足，请多指正，谢谢
> 增加四川旅游学院RSS

- routes/jike/common.js
#555 
https://github.com/DIYgod/RSSHub/issues/555#issuecomment-422837421
> Add a thorough MIME image type check

- docs/README.md
- docs/en/README.md
文档tag注意关闭 <route />
cfdbf3324cfbc4f1e49c9dccc3e6dee750c3b043
> 更新文档，修复错误文档格式

- routes/appstore/xianmian.js
Fix https://github.com/DIYgod/RSSHub/issues/673#issuecomment-422619248
> Correct the epoch timestamp

- docs/README.md
- router.js
- routes/sspai/shortcutsGallery.js
https://github.com/DIYgod/RSSHub/issues/771
> 新增少数派 Shortcuts Gallery

- routes/readhub/category.js
> 修复 Readhub 链接

- routes/appstore/price.js
Fix #777
底层 API 不支持的 app，只能做空值检查。
> Check unsupported app

- routes/atfd/index.js
> Fix atfd empty dateRanges

- docs/README.md
- router.js
- routes/kirara/news.js
- yarn.lock
> rss: add kirarafantasia

- docs/README.md
- docs/en/README.md
- router.js
- routes/bbc/chinese.js
- routes/bbc/index.js
- routes/bbc/utils.js
> 增加 BBC 中文网

- docs/README.md
- docs/en/README.md
- router.js
- routes/verge/index.js
> Add The Verge

- docs/README.md
- router.js
- routes/universities/sdu/cmse.js
- routes/universities/sdu/grad/academic.js
- routes/universities/sdu/sc.js
- 增加山东大学软件学院通知
- 增加山东大学材料科学与工程学院通知
> 增加山东大学软件学院和材料学院通知

- docs/README.md
- router.js
- routes/mi/youpin/new.js
- routes/youpin/newproduct.js
> 增加：有品-每日上新

- docs/README.md
- router.js
- routes/99percentinvisible/transcript.js
添加 99% Invisible 的对话记录，方便查看听力原文
> add: 99% Invisible Transcript

- utils/date.js
> 修复微博-方案2 日期错误

- docs/README.md
- middleware/cache-common.js
- middleware/lru-cache.js
- middleware/redis-cache.js
https://github.com/HenryQW/RSSHub/issues/6
https://github.com/HenryQW/RSSHub/issues/7
> 精简缓存逻辑，精简文档

- routes/instagram/user.js
> Instagram Video support

- docs/README.md
- middleware/parameter.js
> rss: telegram instant view mode param

- docs/README.md
- router.js
- routes/lfsyd/index.js
- 实现--> #876
- 增加文档分类：游戏资讯
将 3DMGame 和 旅法师营地 归于此类
> 增加:旅法师营地－各类游戏资讯

- docs/README.md
- routes/nhentai/util.js
* 提供更激进的例子
* 添加空行分隔图片
* 优先使用原文标题
> nhentai: little change

- docs/README.md
* `change nhentai catogory to 图片`
* `&quote; -> %22`
> catogory nhentai

- routes/solidot/main.js
- views/atom.art
- views/rss.art
also do a bit fix of [solidot] feed
> rss category support

- routes/mzitu/category.js
- routes/mzitu/home.js
- routes/mzitu/tag.js
- routes/mzitu/util.js
> Enhancement: 妹子图帖子图片汇总

- routes/nhk/news_web_easy.js
* fix real created time
* fix timezone
> fix time error of [nhk easy]

- docs/README.md
- router.js
- routes/hko/weather.js
原本的那个实在是太难用。。。
所以我就自己写了一个，可以返回现在的香港天气。
Solve #1043
> 新增香港天文台现在天气 api

- docs/en/joinus/README.md
- docs/joinus/README.md
- views/atom.art
- views/rss.art
修复 #1015 引入的 bug，~~并引入新的 bug~~。
~~顺便给 #1018 做个铺垫（？~~
> fix category support; enable language support

- routes/pixiv/bookmarks.js
- routes/pixiv/ranking.js
- routes/pixiv/user.js
* add author label in other 2 mode
* use real publish date
* remove ambiguous date string
> fix pixiv datetime

- routes/zhihu/daily.js
> zhihu daily fix big font

- docs/README.md
- router.js
- routes/a9vg/a9vg.js
- routes/gnn/gnn.js
> 增加a9vg gnn

- docs/README.md
- docs/joinus/README.md
- routes/bilibili/userChannel.js
- routes/jianshu/collection.js
- routes/jianshu/home.js
- routes/jianshu/trending.js
- routes/jianshu/user.js
- routes/jianshu/utils.js
> 提供简书全文获取，修复简书日期，更新教程文档

- docs/en/README.md
This is a logical continuation of the pull request about [support for private channels](https://github.com/DIYgod/RSSHub/pull/1094).
> Translate info about telegram private channels

- routes/hko/weather.js
> hotfix:Promise.parse() is not a function

- routes/twitter/user.js
- Closes #805 
- 具体逻辑应该是没问题的了，显示方面上的调整还是交给 diy 来吧 233
> Hotfix: Twitter quote

- docs/README.md
> fix doc: bilibili bangumi

- routes/bilibili/bangumi.js
> Hotfix: bilibili bangumi

- docs/README.md
- router.js
- routes/javbus/genre.js
- routes/javbus/home.js
- routes/javbus/star.js
- routes/javbus/uncensored/genre.js
- routes/javbus/uncensored/home.js
- routes/javbus/uncensored/star.js
- routes/javbus/util.js
- routes/javbus/western/genre.js
- routes/javbus/western/home.js
- routes/javbus/western/star.js
旁边那个AVMOO的PR（#893）好像很久没动静了，稍微弄个差不多的（逃
> ADD: J-Bus support

- docs/README.md
> Enhancement: 快递-参数说明

- docs/README.md
- router.js
- routes/nhentai/other.js
- routes/nhentai/search.js
- routes/nhentai/util.js
> nhentai: added simple mode

- docs/en/joinus/README.md
- docs/joinus/README.md
- middleware/template.js
- routes/ximalaya/album.js
> 优化播客格式需要的字段

- docs/README.md
- router.js
- routes/zongheng/chapter.js
> add zongheng.com

- docs/README.md
- router.js
- routes/universities/sjtu/seiee/bjwb/abroad.js
- routes/universities/sjtu/seiee/bjwb/major_select.js
- routes/universities/sjtu/seiee/bjwb/major_transfer.js
- routes/universities/sjtu/seiee/bjwb/postgraduate.js
收录了「阶段性工作」的四个页面：分专业、转专业、直升研究生、交换交流。
http://bjwb.seiee.sjtu.edu.cn/bkjwb/list/1503-1-20.htm
> 添加了对上海交通大学本科生教务办公室的支持

- routes/bilibili/partion-ranking.js
> Hotfix: bilibili partion ranking link

- docs/README.md
- router.js
- routes/baidu/topwords.js
> 增加：百度-搜索风云榜

- routes/weseepro/newest.js
修复 `Cannot read property 'name' of undefined` 报错
> Hotfix: weseepro newest

- routes/twitter/user.js
> Hotfix: twitter-user

- docs/README.md
- router.js
- routes/steam/news.js
- routes/steam/search.js
分類等功能都能直接透過更改 `params` 辦到，而它可以從 `https://store.steampowered.com/search/?specials=1&term=atelier` 這種 URL 取得
> Add steam #1018

- routes/thepaper/featured.js
> Hotfix: thepaper unknown title

- routes/twitter/user.js
> Enhancement: twitter 原图

- routes/jianshu/utils.js
> Hotfix: jianshu img

- docs/README.md
- router.js
- routes/tingdiantz/95598.js
> 增加：国家电网停电通知

- routes/twitter/user.js
> Enhancement: twitter gif

- routes/jianshu/utils.js
> Hotfix: jianshu style

- docs/README.md
- router.js
- routes/36kr/search/article.js
> 增加: 36kr 关键字

- docs/README.md
> fix: bilibili audio doc bug

- routes/cctv/utils/mzzlbg.js
- routes/dongqiudi/utils.js
- routes/instagram/user.js
- routes/ncm/djradio.js
- routes/twitter/utils.js
> Hotfix: video controls

- docs/README.md
- router.js
- routes/universities/nuist/bulletin.js
- routes/universities/nuist/cas.js
- routes/universities/nuist/jwc.js
- routes/universities/nuist/library/lib.js
- routes/universities/nuist/scs.js
- routes/universities/nuist/sese.js
- routes/universities/nuist/xgc.js
- routes/universities/nuist/yjs.js
> 添加对南京信息工程大学的支持

- docs/README.md
- router.js
- routes/icourse163/newest.js
> 增加: 中国大学MOOC(慕课)

- routes/juejin/pins.js
> Hotfix: juejin pin

- docs/README.md
- lib/router.js
- lib/routes/thepaper/channel.js
- lib/routes/thepaper/utils.js
> 增加: 澎湃新闻-频道

- docs/README.md
- lib/router.js
- lib/routes/nga/post.js
> 增加: nga 帖子更新

- docs/README.md
- lib/router.js
- lib/routes/github/search.js
> add: github搜索结果

- docs/install/README.md
> Hotfix: 修复拼写错误

- docs/README.md
- lib/router.js
- lib/routes/qdaily/index.js
- lib/routes/qdaily/utils.js
> Add QDaily Rss source support

- lib/routes/infzm/news.js
> Hotfix: infzm

- lib/routes/icourse163/newest.js
修复 `TypeError: Cannot read property 'reduce' of null` 报错
> Hotfix: icourse163

- lib/routes/oilprice/index.js
https://github.com/DIYgod/RSSHub/issues/818#issuecomment-451130749
> Enhancement: 修改油价标题

- lib/routes/twitter/utils.js
> Hotfix: twitter gif

- lib/routes/36kr/search/article.js
> fix 36kr search

- lib/routes/36kr/search/article.js
> Hotfix: 36kr link

- lib/routes/cctv/utils/news.js
> Enhancement: cctv video

- lib/routes/twitter/utils.js
> Hotfix: twitter wrap

- lib/routes/github/search.js
> Hotfix: github search

- docs/en/install/README.md
- docs/install/README.md
- lib/config.js
- lib/utils/axios.js
- package.json
> Add socks proxy support

- docs/README.md
- lib/router.js
- lib/routes/twitter/likes.js
> Add: twitter likes

- docs/README.md
- docs/en/README.md
- lib/router.js
- lib/routes/allpoetry/order.js
> Add All Poetry

- lib/routes/nga/post.js
Currently the NGA Thread API `/nga/post/:tid` retrieves only the first post in the thread. This PR retrieves all the posts in the last page of the given thread.  
This closes #1423 .
> Retrive latest posts from nga

- lib/routes/bilibili/liveSearch.js
> Fix bilibili live search 404

- docs/README.md
- docs/joinus/README.md
- lib/router.js
- lib/routes/ximalaya/album.js
更改了api，就算获取全部单集也只需要访问几个页面。
close: #1352
> ximalaya: get all tracks (optional)

- lib/routes/sspai/matrix.js
Follow up on #1432 to show full text description instead of summary.
> Show fulltext description for Sspai Matrix

- lib/routes/lfsyd/index.js
> Add post type detection for #1431

- docs/README.md
- lib/router.js
- lib/routes/bilibili/cache.js
- lib/routes/bilibili/danmaku.js
- package.json
由于 axios 不支持设置 Accept-Encoding 使用了 curl 来获取弹幕数据  
如果部署环境没有 curl 会出现失败
> add bilibili video danmaku

- docs/README.md
- lib/router.js
- lib/routes/d2/daily.js
- package.json
- yarn.lock
添加对 [D2 资源库日报](https://awesome.fairyever.com/daily/) 的支持。
**注意**：
引入了一个新的依赖：[sanitize-html](https://www.npmjs.com/package/sanitize-html)
用于去除 HTML 中不需要的内容
```javascript
description = sanitizeHtml(description, {
allowedTags: ['section', 'h2', 'ul', 'li', 'p', 'span', 'a'],
});
```
> Adding RSS：日报 | D2 资源库

- docs/README.md
- lib/router.js
- lib/routes/meipai/user.js
- lib/routes/meipai/utils.js
用户动态 By @ihewro
举例: https://rsshub.app/meipai/user/56537299
路由: /meipai/user/:id
参数:
id, 必选 - 用户 id, 可在 分享出去获得的用户主页 URL 中找到
> add 「美拍用户动态」

- lib/routes/readhub/category.js
> fix: Readhub cache issue

- docs/README.md
- lib/router.js
- lib/routes/github/pulls.js
add Github pull requests rss feed with `github/pull/{user}/{repo}` this pattern
> add Github Pull requests rss feed

- docs/README.md
- lib/router.js
- lib/routes/aisixiang/column.js
- lib/routes/aisixiang/ranking.js
- lib/routes/aisixiang/utils.js
close #1534
这网站特别脆弱，动不动 nginx 就给503
> route: add 爱思想 aisixiang.com

- lib/routes/rsshub/rss.js
移除了「首个中文字符被吞使 Bot 经常搞笑的」 feature
> fix: /rsshub/rss

- docs/README.md
- lib/routes/universities/hit/today.js
发现部分文章需要身份认证后才能阅读，导致RSS输出错误。调整后RSS将不输出这类文章的内容。
> fix 今日哈工大身份认证错误

- lib/middleware/template.js
- lib/routes/test/index.js
- lib/routes/weibo/user2.js
- test/middleware/template.js
more of a problem than a solution
> del: line breaker handling in middleware

- docs/README.md
> fix: update README jike href

- lib/routes/zhihu/zhuanlan.js
> 修复知乎专栏中有被ban的文章时解析失败

- lib/routes/d2/daily.js
> fix: d2/daily pubDate and title, close #1615

- lib/routes/weibo/user2.js
> fix: remove multiple <br>

- docs/README.md
- lib/router.js
- lib/routes/douban/people/status.js
> add 豆瓣用户广播 RSS

- lib/routes/douban/people/status.js
> 豆瓣广播item标题改进

- docs/README.md
- lib/router.js
- lib/routes/nytimes/index.js
- lib/routes/nytimes/morning_post.js
- lib/routes/nytimes/utils.js
> feat: 纽约时报添加英文原版及中英对照版

- lib/routes/leetcode/articles.js
> fix: filter out paid articles

- docs/README.md
- lib/router.js
- lib/routes/tencent/wechat/csm.js
由于网站很容易给 503，只取 5 篇
close #1397
> feat: 增加微信传送门输出

- docs/README.md
- lib/routes/bjp/apod.js
> fix: 每日一图根本没有图的问题

- docs/README.md
- lib/router.js
- lib/routes/universities/nuaa/yjsy/yjsy.js
第一次写JS，有很多不懂的地方，代码是仿照南航教务处RSS的改写，请大佬多多包涵！
> 增加南京航空航天大学 研究生院 RSS 订阅方式

- lib/routes/universities/seu/cse/index.js
> fix 东南大学计算机技术与工程学院

- lib/router.js
- lib/routes/universities/buaa/news/index.js
- lib/routes/universities/cpu/home.js
- lib/routes/universities/cpu/jwc.js
- lib/routes/universities/cpu/yjsy.js
- lib/routes/universities/sjtu/gs/tzgg.js
> fix: 部分大学路由

- lib/routes/tencent/dajia/index.js
- 有部分移动端的链接打开报 404 错误，现在全部改成用 PC 的链接获取，并且对 guid 和缓存的 key 做了兼容处理
- Closes #1696
> Hotfix: dajia

- docs/README.md
- lib/router.js
- lib/routes/douyin/like.js
> Add: douyin like

- lib/routes/zhihu/activities.js
> [Zhihu - Activities] Add type roundtable

- lib/routes/telegram/channel.js
- 目前只处理了非私有频道的图片(不包括图片文件)显示
- Closes #903
> Add: tg channel photo

- docs/README.md
- lib/router.js
- lib/routes/maitta/index.js
> add maitta route

- docs/README.md
- lib/router.js
- lib/routes/vgtime/news.js
- lib/routes/vgtime/release.js
- lib/routes/xiaoheihe/discount.js
- lib/routes/xiaoheihe/news.js
> :sparkles: 小黑盒新闻、打折情况，游戏时光新闻、发售表

- lib/routes/universities/hit/jwc.js
- lib/routes/universities/hit/today.js
pr #1674 中的 commit 246b1bc9f372baa258459b930cb8aa722d6d9006 "chore: 大学路由限制条数" 使用splice函数对很多大学的返回条目进行了限制，但是随之产生了bug，这里对哈工大进行了修复，但是其他大学（包括但不限于华中科技大学 山东大学等）仍存在问题。
> fix 今日哈工大 哈工大教务处 截取错误

- lib/routes/12306/zxdt.js
如你所愿
https://github.com/DIYgod/RSSHub/pull/1644#issuecomment-472272476
> update 12306 no item limit

- lib/routes/dcard/section.js
> fix: wrong Dcard parameter

- docker-compose.yml
- docs/en/install/README.md
- docs/install/README.md
1. bump redis version
1. update docs
> feat: update docker-compose.yml

- lib/routes/jinritoutiao/keyword.js
> fix 今日头条search

- lib/routes/houxu/lives.js
>  fix 后续 lives

- lib/routes/smzdm/ranking.js
>  fix 什么值得买排行榜为空报错

- docs/README.md
- lib/router.js
- lib/routes/qdaily/tag.js
查看如 https://www.qdaily.com/tags/7294.html 等tag类别的文章
> add: 好奇心日报支持 tag 路由

- docs/README.md
- lib/router.js
- lib/routes/universities/zjgsu/gsgg/scripts.js
- lib/routes/universities/zjgsu/tzgg/scripts.js
- lib/routes/universities/zjgsu/tzgg/utils.js
- lib/routes/universities/zjgsu/xszq/scripts.js
> 添加浙江工商大学教务处和学校首页通知

- lib/routes/vgtime/news.js
- lib/routes/xiaoheihe/news.js
- 修复小黑盒新闻部分undefined的问题
- 修复小黑盒新闻内容取值错误的问题
- 修复游戏时光新闻内容取值错误的问题
> 修复小黑盒、游戏时光 BUG

- lib/routes/universities/shmtu/events.js
- lib/routes/universities/shmtu/jwc.js
- lib/routes/universities/shmtu/notes.js
https://github.com/DIYgod/RSSHub/commit/1c7984272ecc75f87862d1188af84d7df9940a22
> fix shmtu $ get

- docs/README.md
- lib/router.js
- lib/routes/anitama/channel.js
#353 the official RSS feed(https://app.anitama.net/rss/google) only shows titles with one day delay.
> add anitama

- docs/README.md
- lib/router.js
- lib/routes/gamersky/news.js
- lib/routes/yystv/recommend.js
[ADD]游民星空今日推荐rss
[ADD]游研社推游栏目rss
> add gamersky and 游研社

- lib/routes/xueqiu/user.js
有问题的路由：[https://rsshub.app/xueqiu/user/1955602780](https://rsshub.app/xueqiu/user/1955602780)
> 修复雪球用户动态的标题为空以及不显示转发内容的问题

- lib/routes/9to5/utils.js
seems to be updated periodically
> chore: update ads class

- docs/README.md
- lib/routes/huxiu/author.js
- lib/routes/huxiu/search.js
- lib/routes/huxiu/tag.js
- lib/routes/huxiu/utils.js
> feat: 虎嗅网文章全文提取

- docs/README.md
- lib/router.js
- lib/routes/oschina/news.js
- lib/routes/oschina/u.js
- lib/routes/oschina/user.js
增加开源中国用户博客订阅，增加开源中国新闻rss的作者元素，便于参数过滤。
> add: OSChina blog

- docs/unclassified.md
- lib/router.js
- lib/routes/iresearch/report.js
- lib/utils/date.js
> 增加艾瑞产业研究报告

- lib/routes/bilibili/dynamic.js
- lib/routes/dysfz/index.js
- lib/routes/dytt/index.js
- lib/routes/mp4ba/index.js
> close #1831

- lib/routes/sspai/series.js
接口：https://sspai.com/api/v1/series/page/get?limit=5&sort=weight&offset=0&released_at=0
> refactor: #570 使用 axios 从接口获取数据 少数派最新上架付费专栏

- lib/utils/date.js
> 解决一分钟之内发布的微博，pubDate为'刚刚'的bug

- docs/other.md
- lib/routes/houxu/lives.js
fix: houxu/lives/new 为空的问题
refactor: houxu/lives 从后续 App 接口获取数据，增加摘要显示
docs: 调整 houxu/lives 的文档，描述更加清晰
> modify: houxu/lives

- lib/routes/manhuagui/comic.js
`.chapter-list` 下有多个 `ul`，最新的 `ul` 在最后面。
> 修复 manhuagui 排序问题

- docs/university.md
- lib/router.js
- lib/routes/universities/bupt/utils.js
- lib/routes/universities/bupt/yz.js
> 添加北京邮电大学硕士研究生招生通知

- lib/routes/zhihu/activities.js
> Hotfix: remove zhihu video space

- lib/routes/rsshub/rss.js
> Hotifx: rsshub rss link

- lib/routes/douyin/like.js
- lib/routes/douyin/user.js
- lib/routes/douyin/utils.js
- 考虑到兼容性问题，guid 仍为旧的地址链接，link 和 description 中已换成新链接
- Closes #1921
> Hotfix: douyin video url

- lib/routes/a9vg/a9vg.js
> fix a9vg feed

- docs/university.md
- lib/router.js
- lib/routes/universities/cuc/yz.js
添加 [中国传媒大学研究生招生网](http://yz.cuc.edu.cn) 通知公告
> add cuc yz rss

- docs/en/README.md
- lib/router.js
- lib/routes/instagram/tag.js
add support to fetch instagram's hashtags. eg:
* [#designertoys](https://www.instagram.com/explore/tags/designertoys/)
* [#urbantoys](https://www.instagram.com/explore/tags/urbantoys/)
> add: instagram/tag

- docs/programming.md
- lib/router.js
- lib/routes/github/branches.js
Turn an url like https://api.github.com/repos/octocat/Hello-World/branches into RSS feed
> Add GitHub branches

- docs/programming.md
- lib/router.js
- lib/routes/geektime/news.js
> 添加极客时间|极客新闻 RSS

- docs/programming.md
- lib/router.js
- lib/routes/oschina/news.js
* 兼容旧的路由
* 支持 OSChina 按板块订阅
* 去除了页面中的广告元素，用于修复订阅中出现 undefined 条目的问题
> 更新 OSChina

- lib/routes/oschina/news.js
> 修复 OSChina 可能采集到相对链接的问题

- docs/programming.md
- lib/router.js
- lib/routes/juejin/collection.js
- lib/routes/juejin/favorites.js
1. 添加掘金某个用户的所有收藏夹
2. 添加掘金用户指定的收藏夹
> feat: 添加掘金收藏夹功能

- lib/routes/nytimes/morning_post.js
> Hotfix nytimes morningpost description

- lib/routes/ifanr/index.js
> fix: 修复 iFanr 无法订阅 大声 栏目的问题

- docs/social-media.md
- lib/router.js
- lib/routes/weibo/super_index.js
> feat: 支持订阅微博超话

- docs/social-media.md
- lib/router.js
- lib/routes/saraba1st/thread.js
> feat: 支持 Saraba1st 帖子订阅

- lib/routes/laosiji/feed.js
> fix: laosiji https error

- lib/routes/github/issue.js
closes #2015 
用filter_author过滤作者
> feat: github issue add author

- docs/other.md
- lib/router.js
- lib/routes/gradcafe/result.js
第一次尝试贡献一个源,有问题随时联系.
申请季的同学应该满需要的.
> feat: add gradCafe(一个比较流行的国外研究生录取结果通知)

- lib/routes/firefox/release.js
> fix: firefox release note

- docs/traditional-media.md
- lib/router.js
- lib/routes/the-economist/gre-vocabulary.js
> Add: the-economist gre

- lib/routes/douyin/utils.js
> Hotfix: douyin type and appLink

- lib/routes/ltaaa/_article.js
- lib/routes/ltaaa/main.js
最新的路由已修复，每周每月全年页面上好像已经找不到了...
fix #2024
> fix: 龙腾网无内容

- lib/routes/oschina/news.js
- lib/utils/date.js
* OSChina 新闻抓取的时候解析时间字符串
* `lib/utils/date.js` 添加几种新的时间格式的解析
> feat: OSChina 新闻抓取的时候解析时间字符串

- docs/traditional-media.md
- lib/router.js
- lib/routes/sina/rollnews.js
> feat: Add Sina rollnews

- docs/anime.md
- docs/forecast.md
- docs/format.js
- docs/game.md
- docs/government.md
- docs/live.md
- docs/multimedia.md
- docs/other.md
- docs/picture.md
- docs/program-update.md
- docs/programming.md
- docs/reading.md
- docs/shopping.md
- docs/social-media.md
- docs/traditional-media.md
- docs/travel.md
- docs/university.md
- package.json
1. 文档左侧的路由`sidebar`按照
1. 英语 (a-z)
2. 中文 (声母先后)
排序， 方便寻找
2. `docs/format.js`根据`docs/.vuepress/config.js`的设定对Markdown文档内排序
3. `package.json`加入`pre-commit`
Before            |  After
:-------------------------:|:-------------------------:
> feat: 文档sidebar排序

- docs/anime.md
> fix: typo in docs

- lib/routes/bangumi/calendar/_base.js
- lib/routes/bangumi/calendar/today.js
- bangumi 每日放送添加id，强制阅读器每日刷新
- 修改缓存时间，只缓存到当日24点。
> refactor: bangumi 每日放送添加id 修改缓存时间

- lib/routes/qdaily/column.js
#1946 could be closed.
这应该是该栏目特别的变更导致的。新修正的效果也就是把一周精选中列出的文章再列出来，个人觉得没有必要再在这一篇文章中将其推荐的每篇文章合并到一起并输出全文了。除此以外，这个栏目看起来已经很久没有更新了？
> fix: 好奇心日报专栏 51

- docs/travel.md
- lib/router.js
- lib/routes/natgeo/natgeo.js
fix  natgeo (page structure change)
> fix  natgeo (page structure change)

- docs/other.md
- docs/social-media.md
- lib/router.js
- lib/routes/qdaily/column.js
- lib/routes/taoguba/index.js
- lib/routes/taoguba/user.js
> add 淘股吧股票论坛

- lib/routes/dongmanmanhua/comic.js
> fix: dongmanhua description

- docs/game.md
- lib/router.js
- lib/routes/nintendo/direct.js
- lib/routes/nintendo/news.js
- lib/routes/nintendo/utils.js
> feat: 任天堂香港首页资讯 / 任天堂直面会日程

- docs/other.md
- lib/router.js
- lib/routes/boc/whpj.js
> feat: 中国银行外汇牌价 多格式标题支持

- lib/routes/vocus/publication.js
- lib/routes/vocus/user.js
- lib/routes/vocus/utils.js
> refactor: 重构方格子 vocus 全文缓存

- docs/traditional-media.md
- lib/router.js
- lib/routes/asahichinese-j/index.js
修正了朝日新闻中文网繁体中文版的文档
增加了朝日新闻中文网简体中文版
> feat: 朝日新聞中文网简体中文版

- docs/other.md
> docs(guanchazhe): 修正观察者风闻话题的文档链接

- lib/routes/vocus/publication.js
- lib/routes/vocus/utils.js
> fix: 方格子请求使用 Referer

- docs/multimedia.md
- lib/router.js
- lib/routes/dsndsht23/index.js
fix: pubDate无效
fix: 图片不显示
add: 原创BT版块下所有子版块
close [#2132](https://github.com/DIYgod/RSSHub/issues/2132)
> feat: 增强 色花堂 路由 

- lib/routes/weibo/user.js
目前微博的description是用的title，现改为同步微博的description。且增加image为微博用户资料的头像
> feat: 微博的description和image

- docs/game.md
- docs/multimedia.md
- docs/other.md
- lib/router.js
- lib/routes/ningmeng/song.js
一个常年不定期推荐不错歌曲的博主。
output item:
```
{
title: song name,
author: song artist
link: mp3 url
}
```
自用配合 IFTTT 自动加入 Spotify 歌单。
> feat: 柠檬电台 私房歌

- lib/routes/twitter/user.js
- lib/routes/weibo/user.js
> feat: 增加Twitter用户时间线的image

- lib/routes/cartoonmad/comic.js
> feat: 增加动漫狂 cartoonmad 缓存

- docs/multimedia.md
- lib/routes/eztv/imdb.js
- eztv 换新地址了 eztv.io
- 加上了 enclosure_url
> feat: [eztv] Change API url && add magnet_url

- docs/multimedia.md
- lib/router.js
- lib/routes/maoyan/hot.js
- lib/routes/maoyan/upcoming.js
> feat: 增加猫眼电影

- docs/social-media.md
> fix: fix saraba1st docs

- lib/routes/xiaoheihe/discount.js
以后在文档写明先 `npm install && npm run format` 好嘛 💦
Ref: #2216 #2235
> fix: 小黑盒热门折扣

- docs/other.md
- lib/router.js
- lib/routes/sina/chuangshiji.js
* 根据 https://github.com/DIYgod/RSSHub/commit/a1a6243d75156d1d8a36ff1ca22456a69979df16#diff-4ca83690ec863517d5519bb3da2f171c 修改
> feat: 添加新浪专栏-创事记

- docs/university.md
- lib/router.js
- lib/routes/universities/sdu/cs.js
添加山东大学计算机科学与技术学院 RSS：
- 学院公告 
- 学术报告 
- 新闻动态
>  feat: 添加山东大学计算机科学与技术学院 RSS

- lib/routes/tingshuitz/guangzhou.js
> fix: 停水通知-广州

- docs/other.md
- lib/router.js
- lib/routes/dilbert/strip.js
> feat: 增加 Dilbert Daily Strip 漫画全文抓取

- lib/routes/99percentinvisible/transcript.js
> Hotfix: 99percentinvisible

- lib/routes/nintendo/eshop_hk.js
> fix: Nintendo

- lib/routes/tencent/wechat/wasi.js
> fix: wasi url

- docs/university.md
- lib/routes/universities/sjtu/seiee/xsb.js
> feat: 增加上海交通大学电院本科生综合测评

- docs/reading.md
- lib/routes/aisixiang/utils.js
- 修复路由 `/aisixiang/ranking/:type?/:range?`
- 更新文档，`type` 与排行榜类型对应关系有变
Works on my machine : )
> fix: aisixiang ranking

- docs/traditional-media.md
- lib/routes/asahichinese-f/index.js
- lib/routes/asahichinese-j/index.js
朝日新聞中文網 (包含簡體與繁體) 新增分類 最新消息，可以列出所有分類，不用再一個個添加。
> feat: add asahichinese whatsnew

- lib/routes/github/trending.js
修复github trending获取方式
Fixes #2376
> fix: Github trending

- lib/routes/gov/zhengce/zuixin.js
> fix: zhengce-zuixin

- lib/routes/oilprice/index.js
> fix: oilprice route

- docs/parameter.md
- lib/middleware/parameter.js
添加时间过滤，这里有两个怪怪的疑问：
- 是否改成`filterout_time`比较合适？
- 文档似乎还可以再改改...?(
> feat: filter time

- lib/routes/douban/people/status.js
- lib/routes/kkj/news.js
- lib/routes/un/scveto.js
fix #1338 
fix #2384 
fix #2244
> fix: #1338 and #2384 and #2244

- lib/routes/nga/forum.js
> fix: nga img and url

- docs/other.md
- lib/router.js
- lib/routes/sixthtone/news.js
>  feat: add sixthtone news 

- docs/programming.md
> fix: 标签没闭合

- lib/routes/indienova/article.js
> feat: indienova 全文

- docs/game.md
- lib/router.js
- lib/routes/indienova/article.js
> feat: iindienova添加参数 

- lib/routes/douyu/room.js
> fix: douyu allow empty

- lib/routes/bilibili/cache.js
- lib/routes/bilibili/fav.js
> fix: B站非默认收藏夹失效

- docs/other.md
- lib/router.js
- lib/routes/8btc/author.js
>  feat: add 8btc

- lib/routes/douban/playing.js
> fix: douban movie allow empty/set default score 0

- lib/routes/dockone/weekly.js
> fix: dockone weekly 404 / get fulltext

- docs/social-media.md
- lib/router.js
- lib/routes/vuevideo/user.js
> feat: add vuevlog

- docs/other.md
- lib/routes/36kr/search/article.js
> fix: 36kr search error

- lib/routes/zzz/index.js
> fix: zzz.vip 404

- docs/programming.md
- lib/router.js
- lib/routes/lwn/alerts.js
添加 Lwn.net Linux Security Alerts 订阅
> feat: add lwn.net security alerts

- lib/routes/douban/playing.js
> fix: set default score 0 when no score

- lib/router.js
- lib/routes/csrc/fashenwei.js
- lib/routes/csrc/news.js
`<Route author="chinobing" example="/csrc/news" path="/csrc/news"/>`
新增了发审委公告
获取证监会要闻的正文内容
> feat: 证监会要闻、发审委公告

- lib/routes/zhihu/activities.js
原来是api的url：`https://api.zhihu.com/topics/19565908`
改为正常浏览的url：`https://www.zhihu.com/topic/19565908`
> feat: 优化知乎话题url

- docs/social-media.md
- lib/router.js
- lib/routes/changba/user.js
close #2479
播放页有神秘力量保护，抓不到mp3地址
> feat: add changba

- lib/routes/konachan/post_popular_recent.js
> fix: konachan safe mode

- docs/game.md
- lib/router.js
- lib/routes/lolapp/recommend.js
> feat: 掌上英雄联盟-推荐新闻

- docs/social-media.md
- lib/router.js
- lib/routes/tencent/wechat/uread.js
> feat: add wechat uread channel

- docs/other.md
- lib/router.js
- lib/routes/tprtc/cqzr.js
- lib/routes/tprtc/news.js
- lib/routes/tprtc/qyzc.js
> feat: add tprtc

- docs/forecast.md
- lib/router.js
- lib/routes/earthquake/ceic.js
- lib/routes/earthquake/index.js
- package.json
> feature: ceic & fix: node env

- docs/other.md
- lib/router.js
- lib/routes/archdaily/home.js
> feat: add archdaily fulltext

- lib/middleware/parameter.js
- lib/routes/apple/appstore/price.js
- lib/routes/apple/appstore/update.js
- lib/routes/bilibili/liveRoom.js
- lib/routes/douban/playing.js
- lib/routes/douyu/room.js
- lib/routes/konachan/post_popular_recent.js
- lib/routes/test/index.js
See: https://github.com/koajs/koa/issues/1172
> fix: retain allowEmpty in ctx.state

- docs/government.md
- docs/traditional-media.md
- lib/router.js
- lib/routes/caixin/article.js
- lib/routes/gov/statecouncil/news.js
- lib/routes/gov/xinwen/gundong.js
- lib/routes/gov/xinwen/yaowen.js
增加财新网首页新闻、中国政府网滚动新闻、中国政府网新闻要闻，axios 更改为 got。
> 增加财新网首页新闻、中国政府网滚动新闻、中国政府网新闻要闻

- docs/other.md
- lib/router.js
- lib/routes/zaker/source.js
> feat: add zaker channel

- Dockerfile
- docs/other.md
- lib/router.js
- lib/routes/nba/app_news.js
> feat: 添加NBA频道

- docs/programming.md
- lib/router.js
- lib/routes/docschina/jsweekly.js
非常喜欢的印记中文周刊，没有抓取文章内容是因为源文不在本站。
> feat: add docschina weekly

- docs/en/README.md
- lib/routes/tencent/wechat/csm.js
> enhance: csm img add referrerpolicy="no-referrer"

- lib/routes/rsshub/rss.js
Condition 'list' is always true. The value of variable 'list' is originated from the array created at line 20 .
> fix: remove a redundant condition check

- lib/routes/bangumi/subject/comments.js
- lib/routes/bangumi/subject/offcial-subject-api.js
- package.json
- yarn.lock
https://github.com/you-dont-need/You-Dont-Need-Momentjs#subtract
> enhance: replace luxon to native Date

- docs/programming.md
- lib/router.js
- lib/routes/oschina/topic.js
> feat: add oschina topic

- lib/routes/geektime/column.js
- lib/routes/geektime/news.js
> fix: geektime description is [Object object] 

- lib/routes/geektime/column.js
- lib/routes/geektime/news.js
> Revert "fix: geektime description is [Object object] "

- lib/routes/pixiv/token.js
close #2446
Ref: https://github.com/DIYgod/RSSHub/issues/2446#issuecomment-510302703
> fix: fix logger typo

- docs/travel.md
- lib/router.js
- lib/routes/flyertea/creditcard.js
- lib/routes/flyertea/utils.js
- package.json
> 添加飞客茶馆信用卡模块

- docs/government.md
- lib/config.js
- lib/router.js
- lib/routes/gov/fmprc/fyrbt.js
- lib/routes/gov/fmprc/utils.js
> add 外交部发言人表态

- docs/university.md
- lib/router.js
- lib/routes/universities/cqu/news/jzyg.js
- lib/routes/universities/cqu/news/utils.js
> add重庆大学新闻网-学术预告

- docs/other.md
- lib/router.js
- lib/routes/nosetime/comment.js
- lib/routes/nosetime/home.js
> feat: add nosetime

- lib/routes/huxiu/utils.js
> fix: 修复虎嗅相关网页的抓取

- lib/routes/pixiv/token.js
> fix: pixiv refresh token error

- lib/routes/security/pulses.js
> fix: 每日安全结构变动

- docs/programming.md
- lib/router.js
- lib/routes/v2ex/post.js
> feat: add v2ex post

- docs/other.md
- lib/router.js
- lib/routes/bof/home.js
> feat: add businessoffashion

- docs/government.md
- lib/router.js
- lib/routes/csrc/news.js
> feat: add 证监会消息

- docs/picture.md
- lib/router.js
- lib/routes/gracg/user.js
[issue#2593 ](https://github.com/DIYgod/RSSHub/issues/2593#issue-465738431)
> add RSS 涂鸦王国

- docs/game.md
- lib/router.js
- lib/routes/arknights/news.js
>  Add “Arknights” game official news channel

- docs/other.md
- lib/router.js
- lib/routes/10000link/news.js
> feat: add 10000link news fulltext

- docs/other.md
- lib/router.js
- lib/routes/zcool/recommend.js
- lib/routes/zcool/top.js
- lib/routes/zcool/user.js
> feat: 新增站酷推荐、作品总榜、用户作品页 close #2683

- lib/routes/universities/njtech/jwc.js
filter out articles which require permission in NJTECH jwc
> feat: filter out articles which require permission

- lib/routes/banyuetan/index.js
> fix: banyuetan null error

- docs/government.md
- lib/router.js
- lib/routes/mofcom/article.js
> feat: add 中华人民共和国商务部

- docs/other.md
- lib/routes/apple/exchange_repair.js
> fix: apple exchange repair

- docs/social-media.md
- lib/router.js
- lib/routes/bilibili/user_bangumi.js
> 增加：用户追番列表（https://space.bilibili.com/44744006/bangumi）

- docs/reading.md
Fix some symbols in doc that cause errors when rendering.
> Fix doc symbol problem

- docs/parameter.md
- lib/middleware/parameter.js
- lib/routes/test/index.js
- lib/utils/common-utils.js
- package.json
- test/middleware/parameter.js
- test/utils/common-utils.js
- yarn.lock
> feat: 新增自动提取全文输出

- docs/anime.md
- docs/other.md
- lib/router.js
- lib/routes/hpoi/info.js
- lib/routes/zimuku/index.js
> feat: 字幕库 & 手办维基情报

- docs/multimedia.md
- lib/routes/mp4ba/index.js
fix: MP4Ba源站内容获取错误 (#2432) 
docs: 同步更新MP4Ba说明文档
> fix: MP4Ba源站内容获取错误 (#2432) 

- lib/routes/zhihu/collection.js
> fix: zhihu collection some link is #

- lib/routes/oilprice/index.js
> fix oilprice route

- lib/routes/chouti/index.js
> fix: chouti

- lib/routes/twitter/utils.js
> fix: remove `<br>` in Twitter tweet title

- lib/utils/got.js
> fix: Request path contains unescaped characters error

- lib/routes/twitter/utils.js
I screwed up everything 😭 @DIYgod Could you please hurry merge this so it won't affect too many people
I'm really sorry 🙇
> fix: fix bug introduced in #2796

- lib/routes/ximalaya/album.js
> fix: ximalaya list sort

- lib/routes/36kr/search/article.js
> fix: 36kr search can't use chinese

- docs/other.md
- lib/routes/dekudeals/index.js
> fix: dekudeals

- docs/other.md
- lib/middleware/template.js
- lib/views/atom.art
- lib/views/rss.art
#2541 
https://validator.w3.org/feed/docs/warning/MissingRealName.html
https://validator.w3.org/feed/docs/warning/MissingAtomSelfLink.html
> enhance: 2 rules for feed validation

- lib/views/rss.art
https://validator.w3.org/feed/docs/error/InvalidHttpGUID.html
> feat: 1 rule for feed validation

- lib/routes/uraaka-joshi/uraaka-joshi-user.js
- lib/routes/uraaka-joshi/uraaka-joshi.js
- lib/utils/common-config.js
@Clackz @lbwstco @DerekTso 几位大兄弟再试一下 Try it again
fix #1888
> fix: try to solve #1888

- lib/routes/boc/whpj.js
> feat: boc whpj add en_name

- docs/other.md
- lib/router.js
- lib/routes/bishijie/kuaixun.js
> feat: add bishijie

- lib/routes/hpoi/info.js
> fix: hpoi info

- docs/other.md
- lib/router.js
- lib/routes/queshu/book.js
- lib/routes/queshu/sale.js
- lib/utils/common-config.js
> feat: add queshu

- docs/shopping.md
- lib/router.js
- lib/routes/weidian/goods.js
> feat: add 微店商品上新

- lib/middleware/template.js
- test/middleware/template.js
> fix: atomlink href

- docs/other.md
- docs/shopping.md
- lib/routes/queshu/book.js
- lib/routes/queshu/sale.js
- lib/utils/common-config.js
> enhance: queshu title add book name

- docs/other.md
- lib/router.js
- lib/routes/latexstudio/home.js
> feat: add latexstudio

- lib/routes/mi/youpin/utils.js
> fix: youpin error

- lib/routes/mp4ba/index.js
> fix: mp4ba URL 错误导致无法获取内容的 Bug

- lib/routes/bilibili/utils.js
- lib/routes/gov/zhengce/govall.js
> fix: govall some link 404

- lib/routes/instagram/tag.js
- lib/routes/instagram/user.js
> fix: instagram set image as video's poster,not img tag

- docs/programming.md
- lib/router.js
- lib/routes/jskou/index.js
[前端艺术家每日资讯&飞冰早报](http://fe.jskou.com)
> feat: 新增前端艺术家每日资讯&飞冰早报

- lib/routes/jskou/index.js
> fix: 修复 飞冰title不正确

- docs/university.md
- lib/routes/universities/sysu/sdcs.js
fix #2905 
由于中山大学数据科学与计算机学院网页升级改版了，故重新写路由抓取的js，并更新了说明文档中的贡献人员名单。
> update sysu/sdcs router, fix #2905

- docs/en/install/README.md
- docs/install/README.md
- docs/other.md
- lib/config.js
- lib/router.js
- lib/routes/mail/imap.js
- package.json
- test/config.js
- yarn.lock
close #1121 
理论上支持所有 IMAP 协议的邮箱
> feat: add mail imap

- lib/routes/12306/zxdt.js
> fix: 12306 error

- lib/routes/geekpark/breakingnews.js
> fix: geekpark

- docs/other.md
- lib/router.js
- lib/routes/cfan/news.js
> feat: add cfan news

- lib/routes/bilibili/danmaku.js
- package.json
- yarn.lock
https://github.com/sindresorhus/got/issues/677#issuecomment-477273686
> refactor: replace node-fetch to got

- docs/social-media.md
- lib/router.js
- lib/routes/sohu/mp.js
> feat: add 搜狐号

- docs/university.md
- lib/router.js
- lib/routes/universities/lit/jwc.js
> feat: add lit jwc

- docs/university.md
- lib/router.js
- lib/routes/universities/lit/jwc.js
- lib/routes/universities/lit/tw.js
- lib/routes/universities/lit/xwzx.js
- lib/routes/universities/pku/rccp/mzyt.js
新增洛阳理工学院 新闻中心及团委
北京大学中国政治学研究中心 每周一推（Issues#2935）
> feat: add lit xwzx tw and pku rccp mzyt

- docs/social-media.md
- lib/router.js
- lib/routes/tencent/news/author.js
> feat: add 企鹅号

- lib/middleware/parameter.js
> fix: fuck some unstandard url

- lib/routes/duozhuayu/search.js
- package.json
- yarn.lock
> refactor: duozhuayu replace puppeteer to api

- lib/routes/douban/people/status.js
> fix: douban people status

- lib/middleware/parameter.js
> fix: if fulltext parser failed, return default description and not report error

- lib/utils/got.js
- test/utils/got.js
look https://github.com/sindresorhus/got/commit/0d534ed90f442c0955058155855ba46f311965f2
> feat: replace baseUrl to prefixUrl when got's next version

- docs/en/program-update.md
- lib/routes/mofcom/article.js
- test/middleware/onerror.js
> fix: mofcom some articles redirect

- lib/routes/weidian/goods.js
- lib/routes/youzan/goods.js
> feat: youzan/weidian title replace userid to shopname

- docs/social-media.md
- lib/router.js
- lib/routes/instagram/story.js
依赖外部 API：`https://api.storiesig.com/stories/${username}`
resolved #1188
> feat: 增加 Instagram 快拍 Stories

- assets/radar-rules.js
- lib/routes/universities/swufe/seie/index.js
- fix: /swufe/seie/: this route is empty
- feat: add /swufe/seie to radar-rules
> fix and feat: University/swufe/seie

- docs/programming.md
- jsconfig.json
- lib/router.js
- lib/routes/aliyun/notice.js
- package.json
- yarn.lock
+ 补充了类型定义，方便 VSCode 做类型提示
+ 🔔强迫症会在 VSCode 下遇到 [此问题](https://github.com/microsoft/vscode/issues/47299)
> feat: aliyun notice

- lib/routes/universities/gdut/news.js
> feat: 改进广东工业大学校内新闻网的返回内容格式。

- docs/program-update.md
- lib/router.js
- lib/routes/sketch/beta.js
#2997 
添加对sketch.com 的beta版本更新支持
@DIYgod
> feat: 添加对sketch.com 的beta版本更新支持

- lib/routes/youzan/goods.js
> fix: youzan title

- lib/routes/sohu/mp.js
> fix: sohu mp link add http://

- lib/routes/zaker/source.js
> fix: zaker

- docs/install/README.md
- docs/reading.md
- lib/config.js
- lib/router.js
- lib/routes/chuiniu/column.js
> feat: add 吹牛部落栏目更新

- docs/university.md
- lib/router.js
- lib/routes/universities/scu/xg.js
> feat: 增加四川大学学工部通知公告

- docs/new-media.md
- docs/university.md
- lib/router.js
- lib/routes/cug/graduate.js
- lib/routes/houxu/live.js
> fix: 后续live & feat: 中国地质大学(武汉) 研究生院综合通知公告

- docs/traditional-media.md
- lib/routes/cctv/utils/news.js
> hotfix: cctv api

- docs/new-media.md
- lib/router.js
- lib/routes/dongqiudi/top_news.js
> feat: add 懂球帝其他新闻栏目(#2954)

- docs/blog.md
- lib/router.js
- lib/routes/blogs/leemeng.js
> feat: add leemeng blog

- lib/routes/tencent/news/author.js
> feat: add 企鹅号全文输出

- assets/radar-rules.js
- docs/social-media.md
- lib/router.js
- lib/routes/pixiv/api/getIllustFollows.js
- lib/routes/pixiv/illustfollow.js
> feat: add pixiv illustfollows

- docs/new-media.md
- lib/router.js
- lib/routes/netease/dy.js
> feat: add 网易号

- docs/new-media.md
- lib/routes/dsndsht23/index.js
> fix: ignore_js_op in /dsndsht23/yzwmyc

- lib/routes/universities/scu/jwc.js
- lib/routes/universities/scu/xg.js
* 增加了四川大学教务处通知的时间
* 增加了四川大学学工部通知的时间
* 更换了获取四川大学学工部通知的地址
> fix: 优化四川大学通知

- docs/programming.md
- lib/router.js
- lib/routes/wechat-open/community/xcx-question.js
> feat: 微信开放平台 - 微信小程序问答

- lib/routes/jianshu/utils.js
> fix: jianshu can't get fulltext and pubDate

- docs/programming.md
- lib/router.js
- lib/routes/wechat-open/community/xyx-question.js
> feat: add 小游戏问答

- docs/social-media.md
- lib/router.js
- lib/routes/weibo/oasis/user.js
> feat: add weibo oasis

- lib/routes/mail/imap.js
发现自己傻逼了  为啥非要等它更新呢  直接传Buffer进去就可以了
> fix: mail some content garbled

- lib/routes/github/trending.js
> fix: github trending url URLencode

- docs/university.md
- lib/router.js
- lib/routes/universities/bupt/grs.js
> feat: 增加对北京邮电大学研究生院通知的支持

- lib/routes/apple/appstore/update.js
> hotfix: appstore-update

- lib/routes/hdx/explore.js
> feat: huodongxing get fulltext

- docs/bbs.md
- lib/router.js
- lib/routes/lkong/forum.js
> feat: add lkong digest

- docs/social-media.md
- lib/router.js
- lib/routes/lofter/tag.js
> feat: 添加Lofter话题

- docs/game.md
> docs: 添加TapTap区域限制说明

- docs/picture.md
- lib/router.js
- lib/routes/cnu/discovery.js
- lib/routes/cnu/selected.js
- lib/routes/cnu/utils.js
> feat: 添加CNU视觉联盟

- docs/other.md
- lib/router.js
- lib/routes/watchface/update.js
> feat: 添加米坛社区表盘更新

- docs/other.md
- lib/router.js
- lib/routes/tencent/factcheck/index.js
> feat: 添加腾讯新闻较真查证平台

- lib/middleware/parameter.js
- test/utils/got.js
> refactor: optimize parameter

- docs/social-media.md
- lib/router.js
- lib/routes/zhihu/daily_section.js
> feat: 添加知乎日报合集 RSS

- docs/anime.md
- lib/router.js
- lib/routes/dongmanmanhua/comic.js
- lib/routes/webtoons/comic.js
- lib/utils/dateParser.js
- test/utils/dateParser.js
Close https://github.com/DIYgod/RSSHub/issues/3164
1. 添加了webtoons
2. 重写了dongmanmanhua
3. 添加了`utils/dateParser`工具。 该工具会剔除时间String中的weekday，并允许用户自己提供日期的format。剔除weekday是因为依据https://github.com/iamkun/dayjs/blob/dev/docs/en/Plugin.md#customparseformat ，dayjs 并不支持parse weekday。 我看了下类似的包`moment`同样也不支持。 这个`dateParser`个人觉得可以作为 #3133 的起点
不太明白CI的codecov为什么不过。。没用过codecov
codecov 终于过了。。凎
> fea: webtoons (close #3164)

- docs/social-media.md
- lib/router.js
- lib/routes/bilibili/readlist.js
> feat: 添加哔哩哔哩专栏文集

- docs/shopping.md
- lib/router.js
- lib/routes/damai/activity.js
> feat: 添加大麦网票务更新

- lib/routes/queshu/book.js
> fix: 修复没有活动信息的书籍

- lib/routes/github/issue.js
apply suggestion from @yefoenix 
fix #3182
> fix: 允许github issue列表为空

- docs/game.md
- lib/router.js
- lib/routes/4gamers/category.js
- lib/routes/4gamers/tag.js
> feat: 添加4Gamers新闻

- docs/en/social-media.md
- docs/social-media.md
- lib/router.js
- lib/routes/telegram/blog.js
Telegarm Blog RSS. It's content is mainly about feature update.
> feat: telegram blog (CHANGELOG)

- lib/routes/universities/zju/cst/index.js
> fix: cst.zju link bug

- assets/radar-rules.js
- docs/new-media.md
- lib/routes/epicgames/index.js
> fix: graphql JSON Parse Error

- docs/university.md
- lib/router.js
- lib/routes/universities/ccnu/career.js
添加华中师范大学就业信息网
Signed-off-by: Jack Yu <jackyu1996@hotmail.com>
> feat: 添加华中师范大学就业信息

- docs/programming.md
- lib/router.js
- lib/routes/kaggle/discussion.js
> feat: add kaggle 讨论区

- lib/routes/duozhi/index.js
> fix: 修复多知网内容获取

- docs/design.md
- lib/router.js
- lib/routes/zcool/user.js
> fix: zcool支持用户id和域名前缀

- docs/university.md
- lib/config.js
- lib/router.js
- lib/routes/universities/bupt/portal.js
需要校园网环境和统一身份认证，所以只能自建。
目前已稳定运行两周，可以正常提取内容。
> feat: add support for BUPT portal

- docs/other.md
- lib/router.js
- lib/routes/pocket/trending.js
> feat: add pocket trending

- docs/university.md
- lib/router.js
- lib/routes/universities/ccnu/career.js
> fix: 修改华中师范大学路由，仅访问首页

- docs/anime.md
- lib/router.js
- lib/routes/1draw/index.js
> feat: 添加 1draw，resolves #3304

- lib/routes/kzfeed/topic.js
优化部分显示效果，如：一觉醒来世界上又发生哪些值得关注的事情 /kzfeed/topic/zE5QRX1Ok4vw
> fix: 换行符处理

- docs/university.md
- lib/routes/jiemian/list.js
- lib/routes/jiemian/utils.js
> feat: 界面快讯支持

- assets/radar-rules.js
- docs/anime.md
- docs/en/other.md
- docs/en/shopping.md
- docs/other.md
- docs/shopping.md
- lib/router.js
- lib/routes/3ycy/home.js
- lib/routes/alter-cn/news.js
- lib/routes/emi-nitta/home.js
Add 3 routs:
- 三界异次元: [http://www.3ycy.com/](http://www.3ycy.com/)
- Alter China: [http://alter-shanghai.cn/](http://alter-shanghai.cn/)
- Emi-Nitta official website
- News: [https://emi-nitta.net/contents/news](https://emi-nitta.net/contents/news)
- Updates: [https://emi-nitta.net/updates](https://emi-nitta.net/updates)
> feat: add 3 routes

- lib/routes/javbus/util.js
根据页面获取番号
获取页面的磁力链并展示，方便使用快捷指令进行下载
根据番号搜索Avgle
在线视频展示为超链接
预览视频展示为视频
> feat: Javbus增加显示番号、在线视频、下载地址、视频预览

- docs/traditional-media.md
- lib/router.js
- lib/routes/whb/zhuzhan.js
> feat: 添加文汇报

- docs/other.md
- lib/router.js
- lib/routes/clickme/index.js
> feat: 添加 clickme

- lib/routes/zhihu/activities.js
> feat: 知乎添加作者字段

- lib/routes/guokr/scientific.js
> fix: 果壳网科学人图片修复

- lib/routes/zhilian/index.js
> fix: 智联RSS链接

- docs/other.md
- lib/router.js
- lib/routes/eleduck/jobs.js
close #3449
---
<details>
<summary>
</summary>
- [#3449: RSS 需求: 电鸭 远程职位](https://issuehunt.io/repos/127769231/issues/3449)
---
</details>
> feat: add 电鸭社区

- docs/programming.md
- lib/routes/kaggle/discussion.js
> feat: 支持订阅 Kaggle 全站 discussions

- lib/routes/dongqiudi/utils.js
> fix: 懂球帝视频 CDN 证书失效

- docs/other.md
- lib/router.js
- lib/routes/network360/jobs.js
close #3448
---
<details>
<summary>
</summary>
- [#3448: RSS 需求: 好队友 远程工作职位](https://issuehunt.io/repos/127769231/issues/3448)
---
</details>
> feat: add 好队友 rss

- lib/routes/algocasts/all.js
- lib/routes/cartoonmad/comic.js
- lib/routes/clickme/index.js
- lib/routes/cnu/selected.js
- lib/routes/dekudeals/index.js
- lib/routes/dlsite/new.js
- lib/routes/lol/newsindex.js
- lib/routes/metred/fuli.js
- lib/routes/netease/dy.js
- lib/routes/sketch/beta.js
- lib/routes/sspai/tag.js
- lib/routes/taptap/topic.js
- lib/routes/tencent/factcheck/index.js
- lib/routes/universities/bupt/utils.js
- lib/routes/universities/zju/list.js
- lib/routes/whb/zhuzhan.js
- lib/routes/wineyun/index.js
- lib/routes/x-mol/paper.js
通过 https://deepscan.io/ 分析结果进行代码优化。
> refactor: 代码优化

- lib/routes/fanfou/favorites.js
> fix: 饭否用户收藏URL

- docs/game.md
- lib/router.js
- lib/routes/nintendo/system-update.js
#3417
https://docs.rsshub.app/game.html#nintendo
> feat: 添加 Nintendo Switch 本体更新情报

- assets/radar-rules.js
- docs/programming.md
- lib/router.js
- lib/routes/itslide/new.js
ITSlide-专注于PPT幻灯片的分享平台 
https://www.itslide.com/
> feat:增加ITSlide订阅源

- lib/routes/apple/appstore/in-app-purchase.js
- lib/routes/apple/exchange_repair.js
> fix: App Store iap price monitor

- lib/routes/fanfou/trends.js
> fix: Fanfou Trends Allow Empty

- lib/routes/gov/hunan/notice.js
> fix: “湖南省政府采购网”RSS源报错 #3488

- lib/routes/natgeo/dailyphoto.js
> fix:  国家地理-每日一图 接口更改

- docs/program-update.md
- lib/router.js
- lib/routes/centbrowser/history.js
> feat: 添加Cent Browser更新日志

- docs/social-media.md
- lib/router.js
- lib/routes/bahamut/creation.js
- lib/routes/bahamut/creation_index.js
- lib/routes/bahamut/utils.js
> feat: 添加巴哈姆特创作相关内容

- docs/social-media.md
- lib/router.js
- lib/routes/mastodon/timeline.js
> feat: add mastodon local public timeline

- lib/routes/apple/appstore/in-app-purchase.js
> fix: 部份 app 内购空值的问题

- lib/routes/natgeo/dailyphoto.js
> fix: natgeo null author

- lib/routes/guardian/guardian.js
- lib/routes/guardian/utils.js
> fix: guardian live page

- lib/routes/oilprice/index.js
> fix: oilprice/shanghai 源报错 #3547

- docs/social-media.md
- lib/router.js
- lib/routes/755/user.js
> feat: add 755

- lib/routes/apple/appstore/in-app-purchase.js
> fix: 内购类型为订阅时没有封面 url 导致报错的问题

- docs/en/other.md
- docs/en/shopping.md
- docs/shopping.md
- lib/router.js
- lib/routes/ikea/uk/new.js
- lib/routes/ikea/uk/offer.js
- IKEA UK new products
- IKEA UK offer
> feat: add IKEA UK routes

- docs/blog.md
- docs/programming.md
- lib/router.js
- lib/routes/aliyun-kernel/index.js
add route for <code>https://kernel.taobao.org/</code>
> feat: add aliyun kernel blog

- lib/routes/dribbble/utils.js
- include all of the content when there are multiple slides
- remove some extra HTML that shouldn't be shown
> feat: Clean up the Dribbble posts a bit more.

- lib/routes/dwnews/yaowen.js
> fix: dwnews yaowen

- lib/routes/ltaaa/_article.js
> fix: ltaaa title

- docs/social-media.md
- lib/router.js
- lib/routes/bilibili/weekly_recommend.js
https://www.bilibili.com/h5/weekly-recommend
> feat: 新增 bilibili 每周必看

- docs/university.md
- lib/router.js
- lib/routes/universities/zucc/news/index.js
add rss of zucc_news (浙江大学城市学院新闻通知)
eg: /zucc/news/latest
waiting  add other func...
> feat: 浙江大学城市学院新闻通知

- docs/university.md
- lib/router.js
- lib/routes/universities/ncwu/file.js
- lib/routes/universities/ncwu/news.js
- lib/routes/universities/ncwu/notice.js
- lib/routes/universities/ncwu/scholarship.js
新增华北水利水电大学的学校新闻、学校文件及学术动态，修复学校通知的连接问题
> feat: 添加华水的学校新闻、学校文件及学术动态

- lib/routes/douban/later.js
- lib/routes/douban/ustop.js
fix #3552 #3668 
参考：[豆瓣疑下线所有公开 API](https://www.v2ex.com/amp/t/563642)
> fix: douban ustop & later

- docs/en/traditional-media.md
- docs/traditional-media.md
- lib/routes/bbc/index.js
> feat: add Traditional Chinese for BBC news

- docs/social-media.md
- lib/router.js
- lib/routes/douban/channel/subject.js
- lib/routes/douban/channel/topic.js
- lib/routes/douban/weekly_best.js
> feat: 新增豆瓣频道专题和书影音

- docs/government.md
- docs/university.md
- lib/router.js
- lib/routes/gov/jiangsu/eea.js
- lib/routes/universities/whu/news.js
add [武汉大学新闻网](https://news.whu.edu.cn/) 的 rss 订阅功能
> feat: add 武汉大学新闻网 rss

- lib/routes/universities/hit/today.js
> fix: HIT today retrieve error #3713

- docs/en/traditional-media.md
- docs/traditional-media.md
- lib/router.js
- lib/routes/apnews/topics.js
> feat: Add The Associated Press News

- docs/bbs.md
- lib/router.js
- lib/routes/nga/forum.js
> feat: add nga recommend

- lib/routes/douyin/user.js
change douyin domain
https://www.douyin.com/  to https://www.iesdouyin.com/
> fix: Update douyin domain

- lib/routes/douyin/like.js
昨天准备改两个文件，user和like，结果只提交了一个，最重要的like修复没有提交
> fix: douyin like domain

- lib/routes/cnu/utils.js
> fix: change cnu base url

- assets/radar-rules.js
- docs/traditional-media.md
- lib/router.js
- lib/routes/nikkei/index.js
> feat: add route for nikkei

- lib/routes/pork-price/index.js
> fix: change api url of pork price

- lib/routes/universities/sjtu/seiee/academic.js
> fix: sjtu seiee academic

- lib/routes/gov/customs/list.js
> fix: gov customs list

- lib/routes/hk01/channel.js
- lib/routes/hk01/hot.js
- lib/routes/hk01/issue.js
- lib/routes/hk01/tag.js
- lib/routes/hk01/zone.js
> fix: hk01 null author

- docs/traditional-media.md
- lib/router.js
- lib/routes/dwnews/rank.js
- lib/routes/dwnews/utils.js
- lib/routes/dwnews/yaowen.js
> fix: 修复多维榜单

- docs/en/other.md
- docs/other.md
- lib/router.js
- lib/routes/coronavirus/mogov-2019ncov.js
News from:
https://www.ssm.gov.mo/apps1/PreventWuhanInfection/ch.aspx
> feat: add macau government wuhan infection news

- lib/routes/gov/news/index.js
- lib/routes/gov/statecouncil/briefing.js
- lib/routes/gov/suzhou/doc.js
修正中国政府网新闻、国务院吹风会、苏州公开政策RSS的slice
> fix: slice issue

- lib/routes/discuz/discuz.js
close #3837 
#3818 我这里访问需要登录，通用路由抓取不了
> feat: support discuz 7.x

- lib/routes/discuz/discuz.js
- 增加全文输出，支持discuz 7.x与discuz x系列
- 只抓取最新的5条消息，若源站更新频率高，可修改阅读器更新时间
- 只抓取文章页面，1楼消息
> feat: support fulltext in discuz

- docs/social-media.md
- lib/router.js
- lib/routes/piapro/public.js
- lib/routes/piapro/user.js
- lib/routes/piapro/utils.js
> feat: add piapro

- assets/radar-rules.js
- docs/study.md
- lib/router.js
- lib/routes/netease/open/latest.js
- lib/routes/netease/open/vip.js
> feat: add 网易公开课

- lib/routes/bilibili/bangumi.js
> fix: bilibili bangumi title

- lib/routes/huya/live.js
> fix: allow huya empty

- lib/routes/bbc/index.js
Fix #3898
Got v10 changed its api.
> fix: bbc feed is broken

- assets/radar-rules.js
- docs/multimedia.md
- lib/router.js
- lib/routes/ddrk/list.js
> feat: 低端影视 各作品列表页面路由

- docs/social-media.md
- lib/routes/douban/people/status.js
> feat: 添加豆瓣广播标题

- assets/radar-rules.js
- docs/game.md
- lib/router.js
- lib/routes/cowlevel/element.js
> feat: add cowlevel

- lib/routes/coronavirus/mogov-2019ncov.js
Update to the latest json data source
> fix: macau government 2019-ncov news new json data source

- lib/routes/matters/author.js
- lib/routes/matters/hot.js
- lib/routes/matters/tags.js
> fix: matters item 

- lib/routes/clickme/index.js
> fix: clickme form type due to got v10

- lib/routes/konachan/post_popular_recent.js
> fix: konachan base url due to got v10

- assets/radar-rules.js
> feat: add qidian radar

- docs/game.md
- lib/router.js
- lib/routes/pcr/news-tw.js
> feat: add 公主连结台服公告

- docs/install/README.md
- docs/picture.md
- lib/config.js
- lib/routes/nhentai/other.js
- lib/routes/nhentai/search.js
- lib/routes/nhentai/util.js
- package.json
Close #2128
不清楚N站对下载有没有配额限制，建议自建使用
> feat: add nhentai torrent support

- docs/en/traditional-media.md
- docs/traditional-media.md
- lib/router.js
- lib/routes/google/news.js
> feat: Add Google News

- docs/program-update.md
> fix: chrome store doc

- docs/reading.md
- lib/router.js
- lib/routes/p-articles/contributors.js
- lib/routes/p-articles/section.js
- lib/routes/p-articles/utils.js
close #3485
---
<details>
<summary>
</summary>
- [#3485: 希望增加 虛詞 RSS](https://issuehunt.io/repos/127769231/issues/3485)
---
</details>
> feat: add 虛詞

- docs/government.md
- docs/traditional-media.md
- lib/routes/dwnews/utils.js
- lib/routes/dwnews/yaowen.js
> fix: dwnews time & api

- lib/routes/kingkong/room.js
> fix: allow kingkong empty

- lib/routes/dcard/section.js
- lib/routes/dcard/utils.js
> fix: switch to Dcard post api

- docs/new-media.md
- lib/router.js
- lib/routes/sspai/activity.js
> feat: add ssapi user activity

- lib/routes/dsndsht23/index.js
- lib/routes/dsndsht23/pictures.js
> fix: anti-crawl of 色花堂

- docs/university.md
- lib/router.js
- lib/routes/universities/tjpyu/ooa.js
I found that “Tongji University”（同济大学）had already used 
abbreviation "tju" so I choosed "Tianjin(Peiyang) Unverisity" (天津(北洋)大学) to distinguish them.
> add: support feed for OAA of Tianjin University

- docs/social-media.md
- lib/routes/dgtle/keyword.js
- lib/routes/dgtle/trade.js
> fix: refactor dgtle trade

- lib/routes/2048/bbs.js
> fix: filter out unwanted hosts for 2048

- lib/routes/bilibili/readlist.js
> fix: bilibili readlist url

- docs/blog.md
- lib/router.js
- lib/routes/blogs/wang54.js
使用网站自带索引页面：[https://wangwusiwj.blogspot.com/2020](https://wangwusiwj.blogspot.com/2020)，未解决日期问题。
> feet: 王五四文集

- docs/university.md
- lib/router.js
- lib/routes/universities/xjtu/dean.js
> feat: add 西安交通大学教务处

- lib/routes/universities/xjtu/dean.js
> fix: xjtu dean url

- lib/routes/finviz/news.js
- lib/routes/xueqiu/stock_info.js
1. 标题格式为 代码+名字 方便阅读器排序。
1. 雪球股票新闻采用外链。
> feat: 又双叒叕更改股票路由

- lib/routes/apnews/topics.js
> feat: Add full article for AP News

- lib/routes/t66y/index.js
> fix: filter out t66y null entry

- docs/university.md
- lib/router.js
- lib/routes/universities/heu/gongxue.js
> feat: add 哈尔滨工程大学工学网-要闻 and -时讯

- docs/new-media.md
- lib/routes/sspai/author.js
> feat: add slug support for sspai author

- assets/radar-rules.js
- docs/blog.md
- docs/en/blog.md
- lib/router.js
- lib/routes/google/sites.js
> feat: add google sites

- docs/en/picture.md
- docs/picture.md
- lib/router.js
- lib/routes/loveheaven/update.js
- package.json
> feat: add loveheaven

- lib/routes/qdaily/index.js
> fix: qdaily undefined image url & remove unwanted ads

- lib/routes/caixin/article.js
> fix: caixin article json

- lib/routes/kuaidi100/index.js
- lib/routes/kuaidi100/utils.js
> feat: Error handling, cache logic

- docs/university.md
- lib/router.js
- lib/routes/universities/yzu/home.js
- lib/routes/universities/yzu/yjszs.js
close #4131
---
<details>
<summary>
</summary>
- [#4131: 【RSS需求】扬州大学 路由需求](https://issuehunt.io/repos/127769231/issues/4131)
---
</details>
> feat: add 扬州大学

- docs/reading.md
- lib/router.js
- lib/routes/chuiniu/column_list.js
> feat: add 吹牛部落专栏列表

- docs/game.md
- lib/router.js
- lib/routes/nintendo/eshop_cn.js
- lib/routes/nintendo/news_china.js
- lib/routes/nintendo/utils.js
> feat: add nintendo china

- docs/en/programming.md
- docs/programming.md
- lib/routes/github/issue.js
> docs: update github issue

- assets/radar-rules.js
- docs/university.md
- lib/router.js
- lib/routes/universities/heu/shuisheng.js
feat: add 哈尔滨工程大学 水声工程学院- 新闻动态 and -通知公告
fix: 工学网 pubDate 中的年份设置
feat: add 哈尔滨工程大学的研究生院、工学网、水声工程学院 radar-rule
> feat: add 哈尔滨工程大学：水声工程学院-新闻动态 and 通知公告 及其相关radar

- assets/radar-rules.js
- docs/en/other.md
- docs/other.md
- lib/router.js
- lib/routes/japanpost/index.js
feat(router_japanpost): add multi language support
chore(router_japanpost): split itemtitle
feat(router_japanpost): add radar support
> feat: router_japanpost

- assets/radar-rules-next.js
- assets/radar-rules.js
- docs/joinus/README.md
chore(docs_joinus): fix code & expressions
fix(radar-rules): replace 'description' with 'docs'
feat(router_japanpost): add next-gen radar-rule
> feat: add japanpost next-gen radar-rule

- assets/radar-rules.js
- docs/other.md
- lib/router.js
- lib/routes/nsfc/news.js
- lib/routes/universities/heu/shuisheng.js
feat: add 国家自然科学基金委员会 route and radar
> feat: add 国家自然科学基金委员会 route and radar

- assets/radar-rules.js
- docs/other.md
- docs/university.md
- lib/router.js
- lib/routes/csc/notice.js
- lib/routes/nsfc/news.js
- lib/routes/universities/heu/yjsy.js
feat: add 国家公派项目、国际合作与交流项目 into 研究生院 route.
> feat: add type: 国家公派项目、国际合作与交流项目（in 研究生院）&& add route: 国家留学网

- lib/routes/ft/utils.js
> fix: change ftchinese cover URL & remove comments elements

- docs/new-media.md
- lib/router.js
- lib/routes/guokr/calendar.js
Fix #4144
同时支持`https://www.guokr.com/scientific/`中其他栏目，不过鉴于果壳网要黄，不再更新文档
> fix: update guokr channel api

- lib/routes/matters/latest.js
> feat: add matters latest date

- docs/university.md
- lib/router.js
- lib/routes/guat/news.js
> feat: add 增加桂林航天工业学院RSS规则

- docs/blog.md
- docs/social-media.md
- lib/router.js
- lib/routes/xiaohongshu/board.js
- lib/routes/xiaohongshu/user.js
- lib/routes/xiaohongshu/util.js
fix #3080
---
<details>
<summary>
</summary>
- [#3080: 【RSS 需求】小红书用户动态路由需求](https://issuehunt.io/repos/127769231/issues/3080)
---
</details>
> fix: #3080 【RSS 需求】小红书用户动态路由需求

- lib/routes/github/follower.js
- lib/routes/github/pulls.js
- lib/routes/github/repos.js
- lib/routes/github/search.js
- lib/routes/github/star.js
- lib/routes/github/starred_repos.js
> fix: allow empty for github feed

- lib/routes/iqiyi/dongman.js
> fix: iqiyi dongman

- docs/live.md
- lib/router.js
- lib/routes/showroom/room.js
> feat:add showroom live

- assets/radar-rules.js
- docs/en/new-media.md
- docs/new-media.md
+ Also add English doc for matters
> feat: Add radar rules for Matters

- docs/university.md
- lib/router.js
- lib/routes/universities/wsyu/news.js
add route: 武昌首义学院-新闻中心：①学校要闻 ②综合新闻 ③媒体聚焦
close #3981
> feat: add 武昌首义学院-新闻中心：①学校要闻 ②综合新闻 ③媒体聚焦

- lib/routes/pnas/index.js
> fix: PNAS parameter & default value

- lib/routes/x-mol/paper.js
- update request to get the correct image for papers
- fix cache key for images
> fix: update x-mol paper image url

- lib/routes/leboncoin/ad.js
> fix: ensure leboncoin `accept` header

- lib/routes/krankenkassen/index.js
> fix: krankenkassen dpa news title

- .dockerignore
- Dockerfile
- clean-nm.sh
add more files to dockerignore. Many package don't make use of `files` field in package.json. So use a shell script to remove it.
> feat: smaller image

- docs/university.md
- lib/router.js
- lib/routes/universities/dlmu/news.js
> feat: add dlmu news feed.

- docs/new-media.md
- lib/router.js
- lib/routes/woshipm/latest.js
> feat: 添加woshipm的最新文章

- docs/multimedia.md
- lib/router.js
- lib/routes/agefans/detail.js
新增视频类订阅 AGE动漫新番播放列表
网站：[https://www.agefans.tv/](https://www.agefans.tv/)
页面：番剧详情播放列表 `https://www.agefans.tv/detail/20200035`
> feat: add agefans.tv detail

- docs/social-media.md
- lib/router.js
- lib/routes/douban/celebrity.js
> feat: 新增豆瓣电影人作品页订阅

- docs/social-media.md
- lib/router.js
- lib/routes/douban/celebrity.js
1. 标题改为带有电影人名字；
2. 参数描述中的半角括号改为全角。
> feat: 修改豆瓣标题和参数描述

- assets/radar-rules.js
- docs/university.md
- lib/router.js
- lib/routes/universities/heu/job.js
add 哈尔滨工程大学 - 就业服务平台
support RSSHub Rader
> feat: add 哈尔滨工程大学 - 就业服务平台

- lib/routes/gouhuo/strategy.js
> fix: gouhuo baseurl

- lib/routes/xueqiu/snb.js
> fix: add xueqiu snb guid

- docs/picture.md
- lib/router.js
- lib/routes/jdlingyu/index.js
> feat: Add 绝对领域

- lib/routes/kuaidi100/index.js
加上guid内容，方便阅读器和一些靠guid变化来识别变化的bot正常获取信息。
> fix: customize guid of kuaidi100

- lib/routes/cneb/yjxx.js
> fix: update cneb yjxx title

- lib/routes/bilibili/bangumi.js
> fix: fetch PV or CM from other section

- docs/en/social-media.md
- docs/social-media.md
> docs: update mastodon per-user feed

- lib/routes/galgame/hhgal.js
设置 Cookie 通过 YunSuoAutoJump 验证。
同时放弃 puppeteer 并使用 cloudscraper。
> fix: hhgal needs to bypass YunSuoAutoJump

- docs/en/social-media.md
- docs/social-media.md
- lib/router.js
- lib/routes/lofter/posts.js
lofter官方rss `http://**:username**.lofter.com/rss` 用不了了 
[#4423](https://github.com/DIYgod/RSSHub/issues/4423)
> feat: 增加lofter博客支持，官方rss暂时不可用

- assets/radar-rules.js
- docs/en/programming.md
- docs/programming.md
- lib/router.js
- lib/routes/github/contributors.js
> feat: add GitHub contributors

- lib/routes/zhihu/daily.js
- lib/routes/zhihu/daily_section.js
> fix: 修复知乎日报原始链接，news-at子域更换为daily子域

- assets/radar-rules.js
- docs/design.md
- lib/router.js
- lib/routes/zcool/recommend.js
- lib/routes/zcool/top.js
> feat: 添加站酷文章总榜/推荐

- lib/routes/36kr/newsflashes.js
- lib/routes/bilibili/dynamic.js
- lib/routes/jiemian/list.js
- lib/routes/segmentfault/channel.js
> fix: 修复36氪快讯, b站UP主动态, segmentfault频道, 界面新闻

- docs/traditional-media.md
- lib/router.js
- lib/routes/ifnews/column.js
> feat: 增加人民日报社-国际金融报-栏目 (#4405)

- package.json
- yarn.lock
Reverts DIYgod/RSSHub#4421
close #4512
> Revert "chore(deps): bump @koa/router from 8.0.8 to 9.0.0"

- lib/routes/facebook/page.js
> fix: facebook pages not working

- lib/router.js
Refer to https://github.com/koajs/router/pull/71 and https://github.com/pillarjs/path-to-regexp/blob/0c466b1b0944e8d0022b5b15069364a8483bf9c5/History.md#200--2017-08-23
Fix #4498
> fix: remove trailing slash

- docs/forecast.md
- lib/router.js
- lib/routes/weatheralarm/index.js
路由地址：https://rsshub.app/weatheralarm
修复全国气象预警路由不可用，并添加省份选择的功能。
> feat: 修复路由 预报预警|全国气象预警

- docs/game.md
> docs: fix link

- docs/en/install/README.md
- docs/install/README.md
- lib/config.js
- lib/router.js
- lib/routes/index.js
- lib/views/welcome.art
- test/router.js
It is useful if you don't want the self-hosted instance can be found by search engine.
> feat: robots not index config

- lib/routes/gov/customs/list.js
> fix: /gov/customs/list/paimai

- docs/game.md
- lib/router.js
- lib/routes/pcr/news-cn.js
会自动删除公告内容出现的\<div\>标签。不太清楚内联样式在客户端会怎么显示，暂时没有处理。
> feat: 添加公主连接国服公告

- lib/routes/gov/province/jiangsu/getContent.js
> fix: /gov/province/jiangsu/documentation

- lib/routes/cctv/category.js
- lib/routes/cctv/utils/xinwen1j1.js
- lib/routes/tencent/video/playlist.js
如：https://v.qq.com/detail/8/84842.html
路由：`/tencentvideo/playlist/84842`
> feat: fix tencent->video 更多链接支持

- lib/routes/instagram/user.js
> feat: add instagram private account tip

- lib/routes/coolapk/tuwen.js
> fix: remove share key from coolapk guid

- lib/routes/acfun/video.js
> fix: AcFun用户投稿

- lib/routes/huxiu/utils.js
> fix: simplify huxiu article

- .gitignore
- api/now.js
- docs/en/install/README.md
- docs/install/README.md
- lib/utils/logger.js
- now.json
Support deploy on zeit now Serverless function.
https://rsshub-now.now.sh/
example： https://rsshub-now.now.sh/bilibili/bangumi/media/9192
Related #4334
> feat: depoly on now serverless function

- lib/routes/xiaohongshu/board.js
- lib/routes/xiaohongshu/user.js
```
(node:145468) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
--> starting at object with constructor 'Node'
|     property 'children' -> object with constructor 'Array'
|     index 0 -> object with constructor 'Node'
--- property 'parent' closes the circle
at JSON.stringify (<anonymous>)
```
caused by dom object included in the description section.
`JSON5` is unnecessary.
> fix: [Xiaohongshu] remove Dom object from description

- lib/routes/2048/bbs.js
地址发布页链接格式不稳定，移除国内抓取支持，直接使用永久地址
Fix #4589
> fix: use 2048 permanent host

- lib/routes/bof/home.js
> fix: BoF article URL

- lib/routes/index.js
强迫症🤔
https://vercel.com/docs/v2/build-step#system-environment-variables
> feat: show commit on vercel deployment

- docs/en/programming.md
- docs/programming.md
> fix: cve document typo

- docs/en/program-update.md
- docs/program-update.md
- lib/router.js
- lib/routes/edge/addon.js
> feat: add microsoft edge addon

- lib/routes/mhw/news.js
> fix: mhw news irregular page

- docs/government.md
- lib/router.js
- lib/routes/gov/mohurd/policy.js
> feat: add 中华人民共和国住房和城乡建设部政策发布

- lib/utils/got.js
> fix: ingore undefined got options

- docs/new-media.md
- lib/router.js
- lib/routes/jinse/lives.js
> feat: add 金色财经快讯

- lib/routes/rs05/rs05.js
resolve: https://github.com/DIYgod/RSSHub/issues/3974
> fix: rs05 change origin and path

- docs/university.md
- lib/router.js
- lib/routes/universities/bjfu/grs.js
增加北京林业大学研究生院培养动态RSS
在自部署的阿里云上运行正常
由于本人是材料学专业
不会码代码，只能照猫画虎
如有不对的地方请您批评指正
> feat: add 北京林业大学

- docs/live.md
- lib/router.js
- lib/routes/langlive/room.js
> fix: change kingkong to langlive

- docs/bbs.md
- lib/router.js
- lib/routes/adnmb/index.js
- show forum info
- use origin image
- fix time
- allow forum name as `pid` parameters 
- remove `page` parameter which is unnecessary for RSS (breaking change)
> feat: adnmb optimization

- assets/radar-rules.js
- lib/routes/javbus/western/genre.js
- lib/routes/javbus/western/home.js
- lib/routes/javbus/western/series.js
- lib/routes/javbus/western/star.js
- add javbus radar rules
- fix javbus western url
> feat: add javbus radar rules

- docs/bbs.md
- lib/router.js
- lib/routes/nowcoder/schedule.js
> feat: add route nowcoder/schedule

- docs/university.md
- lib/router.js
- lib/routes/universities/shanghaitech/activity.js
> feat: add 上海科技大学活动通知

- lib/routes/hexo/next.js
e.g., https://xxx.github.io/blog
> feat: add hexo next context support

- lib/routes/zhihu/collection.js
> fix: update zhihu collection selector

- docs/reading.md
- lib/router.js
- lib/routes/aisixiang/thinktank.js
> feat: add aisixiang thinktank

- docs/university.md
- lib/router.js
- lib/routes/universities/xjtu/gs/tzgg.js
> feat: add 西安交通大学研究生院通知公告

- lib/routes/telegram/channel.js
> feat: /telegram/channel fwd_from, multi medi... partly fix #4777

- docs/university.md
- lib/router.js
- lib/routes/universities/dlmu/grs/zsgz.js
> feat: add 大连海事大学研究生院通知公告

- lib/routes/hpoi/info.js
> fix: add hpoi info time

- docs/install/README.md
- docs/university.md
- lib/config.js
- lib/router.js
- lib/routes/edge/addon.js
- lib/routes/universities/bupt/funbox.js
同时需要ipv6和北邮人账户才能部署（没什么用）。
Demo: [趣味盒RSS](https://rss.pka.moe/bupt/funbox?2020)
> feet: add BTBYR趣味盒

- assets/radar-rules.js
- docs/government.md
- lib/router.js
- lib/routes/gov/beijing/eea.js
执行`npm run format`时，格式化了`goverment.md`文件中其他作者的doc。
> feat:加入北京教育考试院路由

- docs/university.md
- lib/router.js
- lib/routes/universities/ahau/cs_news/index.js
- lib/routes/universities/ahau/cs_news/utils.js
- lib/routes/universities/ahau/jwc/index.js
- lib/routes/universities/ahau/jwc/utils.js
- lib/routes/universities/ahau/main/index.js
- lib/routes/universities/ahau/main/utils.js
未采用Puppeteer
RSS内容如下
- 农大官网
- 计算机学院
- 教务处
> feat: 增加安农大RSS

- docs/new-media.md
- lib/router.js
- lib/routes/aljazeera/news.js
> feat: add Aljazeera 半岛网新闻

- lib/routes/google/album.js
https://rsshub-git-fork-hoilc-fix-google-album-redirect.diy.now.sh/google/album/msFFnAzKmQmWj76EA
> fix: google album redirect url

- docs/.format/md/hierarchySlug.js
- docs/.vuepress/config.js
- docs/anime.md
- docs/traditional-media.md
fix: minor docs issue in anime.md and traditional-media.md
> docs: unique id for h3, close #4633, #4803

- docs/finance.md
- lib/router.js
- lib/routes/pbc/goutongjiaoliu.js
- lib/routes/pbc/tradeAnnouncement.js
> feat: add 中国人民银行沟通交流新闻 & 货币政策司公开市场业务交易公告

- docs/university.md
- lib/router.js
- lib/routes/universities/hitwh/today.js
- 添加哈尔滨工业大学威海校区[通知公告](http://today.hitwh.edu.cn/1024/list1.htm)
> feat: add 哈尔滨工业大学（威海）通知公告

- docs/university.md
- lib/router.js
- lib/routes/universities/cqu/youth/info.js
add 重庆大学校团委 <http://youth.cqu.edu.cn/>
> feat: add 重庆大学校团委

- lib/routes/telegram/channel.js
> feat: /telegram/channel reply, media tag, poll

- docs/design.md
- docs/university.md
- lib/router.js
- lib/routes/monotype/article.js
> feat: add monotype featured article

- docs/university.md
- lib/router.js
- lib/routes/universities/cqu/sci/info.js
Add 重庆大学数学与统计学院 <http://sci.cqu.edu.cn/>
> feat: add 重庆大学数学与统计学院

- docs/travel.md
- lib/router.js
- lib/routes/mafengwo/ziyouxing.js
> feat: add 马蜂窝自由行攻略

- docs/picture.md
- lib/router.js
- lib/routes/zhutix/latest.js
> feat: add 致美化最新主题

- docs/journal.md
- lib/router.js
- lib/routes/stork/keyword.js
ADD: 添加了 Stork 文献鸟的关键词追踪路由。已测试可生成RSS，已 format。
> feat: 添加了 Stork 文献鸟关键词追踪路由

- docs/program-update.md
- lib/router.js
- lib/routes/cpython/index.js
close #4855
<https://rsshub-git-fork-trim21-master.diy.now.sh/cpython>
<https://rsshub-git-fork-trim21-master.diy.now.sh/cpython/pre>
> feat: cpython release

- docs/multimedia.md
- lib/router.js
- lib/routes/rrys/review.js
nodejieba装不起的坑是怎么填的 WIN10和WSL都试了，node14,12,10都尝试过。
装不上没法调文档啊🤮
> feat: 新增路由人人影视-评测推荐

- docs/journal.md
- lib/router.js
- lib/routes/arxiv/query.js
> feat: add arxiv search

- docs/anime.md
- lib/router.js
- lib/routes/bangumi/user/blog.js
> feat: add bangumi user blog

- docs/other.md
- lib/router.js
- lib/routes/law/gf.js
- lib/routes/law/hq.js
- lib/routes/law/hw.js
- lib/routes/law/jh.js
- lib/routes/law/jtc.js
- lib/routes/law/ts.js
- lib/routes/law/zl.js
包括环球、海问、国枫、通商、中伦、君合、锦天城这7家律所官网的专业文章。
> feat: 新增几家律师事务所官网文章

- docs/other.md
- lib/router.js
- lib/routes/dgjyw/index.js
> feat: add 东莞教研网

- docs/new-media.md
- lib/router.js
- lib/routes/baidu/daily.js
> feat: add 百度知道-日报精选

- lib/routes/facebook/page.js
- 修復此 Issue #4552 [討論串](https://github.com/DIYgod/RSSHub/issues/4552#issuecomment-623264841)
- 修復非圖片附件的貼文
> fix: facebook title, desc, images no found

- docs/bbs.md
- lib/router.js
- lib/routes/samsungmembers/latest.js
> feat: add 三星盖乐世社区最新帖子

- docs/government.md
- docs/reading.md
- lib/router.js
- lib/routes/gov/caict/bps.js
- lib/routes/gov/caict/caictgd.js
- lib/routes/gov/caict/qwsj.js
> feat: add 中国信通院研究成果

- docs/government.md
- lib/router.js
- lib/routes/gov/chinatax/latest.js
> feat: add 国家税务总局税收政策最新文件

- docs/program-update.md
- lib/router.js
- lib/routes/mi/golden.js
> feat: add 小米应用商店金米奖

- lib/routes/sspai/activity.js
> feat: add sspai activity pubDate

- assets/radar-rules.js
- docs/social-media.md
- lib/router.js
- lib/routes/bilibili/manga_update.js
> feat: add bilibili manga

- docs/multimedia.md
- lib/router.js
- lib/routes/lizhi/user.js
> feat: add 荔枝FM电台更新

- lib/routes/universities/bupt/funbox.js
使用guid并对RSS输出内容做了正则优化。
（可能就我在用2333）
[Demo](https://rss.pka.moe/bupt/funbox/)
> feat: BTBYR update

- docs/bbs.md
- lib/router.js
- lib/routes/v2ex/tab.js
add router v2ex/tab
usage:
> v2ex/tab/tech
> v2ex/tab/hot
> feat: add router v2ex/tab

- docs/new-media.md
- lib/router.js
- lib/routes/waijiedanao/article.js
> feat: add 外接大脑

- docs/social-media.md
- lib/router.js
- lib/routes/jike/common.js
- lib/routes/jike/topic.js
- lib/routes/jike/topicText.js
- lib/routes/jike/user.js
CodeFactor报复杂性那个点不知道怎么改
具体见#4962
> feat: add 即刻

- docs/new-media.md
- lib/router.js
- lib/routes/netease/news/rank.js
> feat: add 网易新闻排行榜

- docs/new-media.md
- lib/routes/36kr/user.js
> fix: 36kr user, close #4865

- lib/routes/telegram/blog.js
> fix: telegram blog

- docs/new-media.md
- lib/routes/36kr/motif.js
- lib/routes/36kr/search/article.js
- lib/routes/36kr/user.js
Fix #4971
Fix /36kr/user 返回用户上传视频内容时报错（如 [/36kr/user/5075022](https://rsshub.app/36kr/user/5075022)）
> fix: 36kr search & user

- lib/routes/thepaper/channel.js
- lib/routes/thepaper/utils.js
> fix: 澎湃 DOM 更新

- docs/forecast.md
- lib/router.js
- lib/routes/gov/shanghai/sthj.js
> feat: add 上海市生态环境局空气质量发布

- docs/other.md
- lib/router.js
- lib/routes/szse/rule.js
> feat: add 深圳证券交易所最新规则

- lib/routes/jike/user.js
即刻圈子【一觉醒来世界发生了什么】的更新永远会迟一天，即刻咨询台的是实时的。
> feat: 优化即刻咨询台

- lib/routes/taptap/topic.js
> fix: update taptap topic selector

- docs/multimedia.md
- lib/router.js
- lib/routes/missevan/drama.js
增加了广播剧, 有声漫画.
提供每集的标题, 封面, 简介.
Close #3508
> feat: add 猫耳FM

- lib/routes/weibo/user.js
- lib/routes/weibo/utils.js
emoji 的标签加了一个换行符
```
<span class="url-icon"><img alt=[中国赞] src="https://h5.sinaimg.cn/m/emoticon/icon/others/d_chnlike-2c6f482dac.png" ↵                style="width:1em; height:1em;" /></span>1 
```
#5050
> fix: weibo emoji dom update

- docs/journal.md
- lib/router.js
- lib/routes/ieee/author.js
给 IEEE Xplore 作者发表添加了路由，支持多种排序方式 (#5038)
> feat: add a router for IEEE Xplore authors (#5038)

- lib/routes/yystv/category.js
> feat: 游研社支持抓取正文

- docs/finance.md
- lib/router.js
- lib/routes/cls/depth.js
- lib/routes/cls/telegraph.js
> fix: 财联社电报 & 深度

- docs/multimedia.md
- lib/router.js
- lib/routes/yyets/todayfilelist.js
> feat: add 人人影视 每日更新

- docs/bbs.md
- lib/router.js
- lib/routes/91ddcc/user.js
> feat: add 才府社区用户动态

- docs/new-media.md
- lib/router.js
- lib/routes/dsb/area.js
提供每个分区首页新闻(包含新闻内容)
Close #4286
> feat: add 电商报

- docs/bbs.md
- docs/game.md
- lib/router.js
- lib/routes/guanggoo/index.js
> feat: add 光谷社区

- lib/routes/google/album.js
> fix: update google album regex

- docs/finance.md
- docs/game.md
- lib/router.js
- lib/routes/gelonghui/keyword.js
- lib/routes/gelonghui/subject.js
- lib/routes/gelonghui/user.js
> feat: add 格隆汇

- docs/game.md
- lib/routes/dribbble/utils.js
移除了`shotViews`(页面上已移除)
Close  #4985
> fix: Dribbble DOM update

- docs/traditional-media.md
- lib/router.js
- lib/routes/reuters/theWire.js
> feat: 路透社 实时资讯

- docs/bbs.md
- docs/game.md
- lib/router.js
- lib/routes/nowcoder/jobcenter.js
> feat: add 牛客网求职广场

- assets/radar-rules.js
- docs/government.md
> feat: nppa.radar

- docs/university.md
- lib/router.js
- lib/routes/universities/shou/www.js
> feat: Add shou route

- docs/forecast.md
- lib/router.js
- lib/routes/12379/index.js
> feat: add 国家预警信息发布中心当前生效预警

- docs/government.md
- lib/router.js
- lib/routes/gov/chongqing/ljxq/dwgk.js
- lib/routes/gov/chongqing/ljxq/zwgk.js
> feat: add 重庆市两江新区信息公开网

- docs/bbs.md
- lib/router.js
- lib/routes/zhibo8/more.js
> feat: add 直播吧滚动新闻

- docs/new-media.md
- lib/router.js
- lib/routes/niaogebiji/cat.js
- lib/routes/niaogebiji/today.js
解决#4987 的问题
顺带一提，写了一点方便在CheerioElement中查找其属性符合要求的元素的方法（因为CheerioElement没有相关的方法）
也可能是我对Cheerio了解不深，如果有替代方法请告知一下（或直接帮我重写了吧，要期末考了），谢谢
> feat:增加订阅源'鸟哥笔记'（今日事,分类目录)

- lib/routes/universities/usst/jwc.js
看起来是最近改版了。
稍微修改了一下 css 选择器的路径
#5138 忘了删控制台指令
> fix: the problem in Issue #5137 解决上海理工大学教务网列表为空的问题

- lib/routes/coronavirus/dxy-data.js
- lib/routes/coronavirus/dxy.js
- lib/routes/dongqiudi/utils.js
- lib/routes/nintendo/utils.js
- lib/routes/producthunt/today.js
- lib/routes/tencent/egame/room.js
> fix: ProductHunt Today

- docs/new-media.md
- lib/routes/cls/depth.js
> fix: 财联社头条未推送

- docs/new-media.md
- docs/shopping.md
- lib/router.js
- lib/routes/smzdm/baoliao.js
> feat: add 什么值得买用户爆料

- .github/ISSUE_TEMPLATE/bug_report_en.md
- lib/middleware/onerror.js
- lib/routes/producthunt/today.js
> fix: producthunt URL

- lib/routes/transferwise/pair.js
> fix: TransferWise data structure change

- lib/routes/bilibili/user_bangumi.js
> fix: modify param 'ps‘

- lib/routes/xiaohongshu/user.js
> fix: update xiaohongshu note url

- lib/routes/bjp/apod.js
> fix: update bjp apod url

- lib/routes/github/search.js
> fix: update github search selector

- lib/routes/pocket/trending.js
> fix: update pocket trending DOM

- lib/routes/acfun/bangumi.js
> fix: acfun

- docs/bbs.md
- docs/program-update.md
- lib/router.js
- lib/routes/quicker/qa.js
- lib/routes/quicker/update.js
Add: 
1. Quicker - 讨论区
2. Quicker - 版本更新
> feat: add Quicker

- docs/programming.md
- lib/router.js
- lib/routes/kaggle/user.js
> feat: add kaggle user discussion

- docs/blog.md
- docs/en/traditional-media.md
- docs/multimedia.md
- docs/new-media.md
- docs/traditional-media.md
- docs/university.md
- lib/router.js
- lib/routes/reuters/channel.js
- lib/routes/reuters/utils.js
> feat: 路透社分站：CN & UK

- assets/radar-rules.js
- docs/en/social-media.md
- docs/social-media.md
- lib/router.js
- lib/routes/picuki/profile.js
> feat: add picuki

- docs/en/install/README.md
- docs/install/README.md
> doc: expand Heroku instructions

- docs/university.md
- lib/router.js
- lib/routes/universities/hfut/tzgg.js
> feat: add 合肥工业大学通知公告

- docs/en/traditional-media.md
- docs/traditional-media.md
- lib/router.js
- lib/routes/cbc/topics.js
Add RSS feed for CBC: https://www.cbc.ca
> feat: add CBC

- assets/radar-rules.js
- docs/en/program-update.md
- docs/new-media.md
- docs/program-update.md
- lib/router.js
- lib/routes/12379/index.js
- lib/routes/acfun/bangumi.js
- lib/routes/anitama/channel.js
- lib/routes/aptonic/action.js
- lib/routes/bilibili/user_bangumi.js
- lib/routes/bjp/apod.js
- lib/routes/github/search.js
- lib/routes/hanime/video.js
- lib/routes/ikea/uk/new.js
- lib/routes/ithome/ranking.js
- lib/routes/javbus/director.js
- lib/routes/javbus/label.js
- lib/routes/javbus/studio.js
- lib/routes/pocket/trending.js
- lib/routes/transferwise/pair.js
- lib/routes/xiaohongshu/user.js
- lib/utils/date.js
> revert: #5271

- docs/en/traditional-media.md
- docs/traditional-media.md
Didn't know the author is linked to Github profile. Fixed the author for
CBC routers (#5179).
> fix: update author for CBC router

- lib/routes/github/issue.js
- lib/routes/github/pulls.js
> fix: GitHub markdown with empty body

- docs/en/social-media.md
> docs: (en) fix wrong path of mastodon user feed

- docs/en/traditional-media.md
- docs/traditional-media.md
- lib/router.js
- lib/routes/bbc/index.js
Close #5302
/bbc/chinese/business
> feat: BBC 中文网子频道支持

- lib/routes/reuters/channel.js
尝试修复 #5051
- /reuters/channel/cn/analyses
- /reuters/channel/us/business
> fix: 路透社缓存问题

- docs/other.md
- lib/router.js
- lib/routes/gushiwen/recommend.js
添加 annotation 字段，用来指定是否添加翻译、注释和赏析到输出的文章中。
/gushiwen/recommend/:annotation?
> feat: 为古诗文网添加翻译、注释和赏析

- assets/radar-rules.js
- docs/university.md
- lib/router.js
- lib/routes/universities/ynu/grs/qttz.js
- lib/routes/universities/ynu/grs/zytz.js
- lib/routes/universities/ynu/home/main.js
- lib/routes/universities/ynu/jwc/zytz.js
- lib/routes/universities/ynu/utils.js
> feat: add 云南大学主页、研究生院、教务处通知公告

- assets/radar-rules.js
- docs/multimedia.md
- lib/router.js
- lib/routes/onejav/one.js
- package.json
- Format: `/onejav/:type/:key?`
- Script: lib/routes/onejav/one.js
- Doc: docs/multimedia.md
- 实现方式为使用 got 从 HTML 获取数据
- 支持 New、Popular、Random、指定演员、指定标签、指定日期分别输出
- 支持 BT 下载（主要目的，官方 Feed 不支持 BT 订阅下载）
- 支持 Radar 浏览器扩展程序
- 文档已参照相同页面项目形式进行整理
https://rsshub-git-fork-monsterxcn-master.diy.vercel.app/onejav/new
https://rsshub-git-fork-monsterxcn-master.diy.vercel.app/onejav/popular
https://rsshub-git-fork-monsterxcn-master.diy.vercel.app/onejav/popular/7
https://rsshub-git-fork-monsterxcn-master.diy.vercel.app/onejav/random
https://rsshub-git-fork-monsterxcn-master.diy.vercel.app/onejav/random/7
https://rsshub-git-fork-monsterxcn-master.diy.vercel.app/onejav/actress/Yua%20Mikami
https://rsshub-git-fork-monsterxcn-master.diy.vercel.app/onejav/tag/Adult%20Awards …
> feat: add OneJAV (supportBT)(radar)

- docs/government.md
- lib/router.js
- lib/routes/gov/shuju/index.js
> feat: add 中国政府网生猪信息 & 商品价格

- lib/routes/dongqiudi/top_news.js
Close #5247
/dongqiudi/top_news/5
> fix: 懂球帝 API 返回地址不一致的问题

- docs/new-media.md
- lib/router.js
- lib/routes/199it/category.js
- lib/routes/199it/tag.js
- lib/routes/199it/utils.js
Close #5266
/199it/category/199itdata
/199it/tag/数据早报
> feat: add 199IT分类 & 标签

- docs/traditional-media.md
- lib/router.js
- lib/routes/telecompaper/news.js
Close #5330
/telecompaper/news/mobile/2020/China/News
> feat: add telecompaper news

- docs/bbs.md
- lib/router.js
- lib/routes/newsmth/account.js
Close #5342
/newsmth/account/fef705ec94819a5a87941759e33c0982
> feat: add 水木社区用户动态

- lib/routes/amazfitwatchfaces/utils.js
Close #5353
/amazfitwatchfaces/updated/bip/Bip/zh
/amazfitwatchfaces/top/bip/Bip/month/views/zh
/amazfitwatchfaces/fresh/bip/Bip/zh
> fix: incomplete channel links for amazfitwatchfaces
