DIYgod/RSSHub

docs/new-media.md
lib/router.js
lib/routes/bioon/latest.js

feat: add 生物谷最新资讯

---

docs/social-media.md
lib/routes/bilibili/cache.js
lib/routes/bilibili/video.js

B站改了api方法，但改后可用性变高了
close #5394 
close #5397
close #5398

fix: bilibili video

---

docs/en/government.md
docs/government.md
lib/router.js
lib/routes/go.jp/mofa/main.js

feat: Japan MFA, Press conference

---

lib/routes/novel/biqugeinfo.js

Close #5370
/novel/biqugeinfo/81_81797

fix: styleless descriptions in biqugeinfo

---

lib/routes/telegram/channel.js

涉及到的路由及测试地址：
- `/telegram/channel/:username/:searchQuery?`
- `/telegram/channel/yitianshijie`
- `/telegram/channel/gravitysworm`

feat: add warnings for blocked telegram channels

---

lib/routes/juejin/books.js
lib/routes/juejin/category.js
lib/routes/juejin/collection.js
lib/routes/juejin/favorites.js
lib/routes/juejin/posts.js
lib/routes/juejin/tag.js
lib/routes/juejin/trending.js
lib/routes/juejin/utils.js

目前还有 trending 跟 shares 未修复
看了下现在的页面，没理解错的话应该可以认为热榜对应 trending 、动态对应 shares 吧 。。。

fix: juejin api

---

lib/views/atom.art

fix(template_atom.art): atom entry id not set by `ctx.state.data.item[].guid`.

fix: atom.art id

---

lib/routes/newrank/utils.js
lib/routes/newrank/wechat.js

补充了对新榜微信公众号新推文的订阅，并强制登陆信息为String
现在公众号延迟应该没那么严重了。

增加了对新榜未收录数据的订阅，并强制登陆信息为String

---

lib/routes/gov/suzhou/doc.js
lib/routes/gov/suzhou/news.js
lib/routes/gov/suzhou/utils.js

fix: 修复苏州市政府

---

docs/en/social-media.md
docs/social-media.md
lib/router.js
lib/routes/picuki/profile.js

Close #5470
https://rsshub-git-fork-hoilc-add-picuki-video-flag.diy.vercel.app/picuki/profile/lingoliyah/1

feat: add picuki video support

---

docs/social-media.md
lib/router.js
lib/routes/wukong/user.js

Close #5459
/wukong/user/5826687196/answers

feat: add 悟空问答用户回答 & 用户提问

---

lib/routes/douban/group.js

Close  #5462
<https://rsshub.app/douban/group/camera>

fix: douban apikey reponse 400

---

docs/blog.md
lib/router.js
lib/routes/justrun/index.js

feat: add JustRun职业投资者阅读记录

---

docs/en/usage.md

doc: fix link to Twitter user timeline

---

docs/programming.md
lib/routes/luogu/daily.js

feat: add 洛谷日报文章全文

---

docs/traditional-media.md
lib/router.js
lib/routes/fjnews/fznews.js
lib/routes/fjnews/jjnews.js

Close #
//福建新闻
router.get('/fjnews/fj/30', require('./routes/fjnews/fznews'));
//福州新闻
router.get('/fjnews/fz/30', require('./routes/fjnews/fznews'));
//九江新闻jjnews
router.get('/fjnews/jjnews', require('./routes/fjnews/jjnews'));

feat: add 福建及福州新闻

---

docs/bbs.md
lib/router.js
lib/routes/hupu/all.js
lib/routes/hupu/dept.js

Close #5491
/hupu/dept/nba
/hupu/all/gambia

feat: add 虎扑网子站 & 论坛分类

---

docs/government.md
lib/router.js
lib/routes/gov/xinwen/tujie.js

Close #5546
/gov/xinwen/tujie/zhengce

feat: add 中国政府网图解 & 漫画

---

docs/shopping.md
lib/router.js
lib/routes/mingjian/index.js

feat: add 消费明鉴最新新闻

---

docs/en/shopping.md
docs/shopping.md
lib/router.js
lib/routes/guiltfree/onsale.js

feat: add guiltfree onsale

---

docs/shopping.md
lib/router.js
lib/routes/tahui/rptlist.js

feat: add 它惠网线报列表

---

docs/en/multimedia.md
docs/multimedia.md
lib/router.js
lib/routes/hentaimama/monthlies.js
lib/routes/hentaimama/videos.js

Example Routes:
- /hentaimama/monthlies (https://rsshub-git-fork-everyonus-hentaimama.diy.vercel.app/hentaimama/monthlies)

feat: add hentaimama

---

docs/en/social-media.md
docs/social-media.md
lib/config.js
lib/router.js
lib/routes/fanbox/conv.js
lib/routes/fanbox/header.js
lib/routes/fanbox/main.js

new site.
```
http://127.0.0.1:1200/fanbox/
http://127.0.0.1:1200/fanbox/otomeoto
```

feat: add pixiv-fanbox

---

docs/program-update.md
lib/router.js
lib/routes/typora/changelog-dev.js

Close #5557 
/typora/changelog-dev/macOS

feat: add typora dev release changelog

---

docs/install/README.md
docs/social-media.md
lib/config.js
lib/routes/newrank/douyin.js
lib/routes/newrank/utils.js
lib/routes/newrank/wechat.js

新榜登录加了验证码，改成了cookie登录
Close #5538
需要自建并添加NEWRANK_COOKIE参数
微信公众号：/newrank/wechat/mrscience100
抖音短视频：/newrank/douyin/98680217165

feat(breaking change): 将新榜登录方式改为COOKIE登陆

---

lib/routes/pornhub/category_url.js

Close #
/pornhub/category_url/
/pornhub/category_url/popularwithwomen

fix: remove pornhub preview video

---

lib/routes/szse/rule.js

fix: add descriptions of rules in szes

---

docs/blog.md
lib/router.js
lib/routes/blogs/wordpress.js

/blogs/wordpress/`:domain`/`:https?`
e.g:
/blogs/wordpress/lawrence.code.blog
/blogs/wordpress/blog.yitianshijie.net/https
PS: WordPress 部分站点可能被 GFW。

feat: add WordPress blog

---

docs/other.md
lib/router.js
lib/routes/sse/disclosure.js

/sse/disclosure/
e.g:
/sse/disclosure/beginDate=2018-08-18&endDate=2020-09-01&productId=600696

feat: 增加上海证券交易所上市公司公告披露

---

docs/university.md
lib/router.js
lib/routes/universities/lyu/news/index.js
lib/routes/universities/lyu/news/utils.js

Signed-off-by: ueiu <bautuoyoul@gmail.com>
Close #5054 
[临沂大学 - 临大要闻地址](https://rsshub-git-fork-ueiu-feature-lyu-news.diy.vercel.app/lyu/news/ldyw)
[临沂大学 - 信息公告地址](https://rsshub-git-fork-ueiu-feature-lyu-news.diy.vercel.app/lyu/news/xxgg)

feat：增加临沂大学校园新闻RSS (#5054)

---

docs/en/other.md
docs/other.md
lib/router.js
lib/routes/mitre/publications.js

feat: add MITRE - All Publication

---

docs/en/multimedia.md
docs/multimedia.md
lib/router.js
lib/routes/pornhub/category.js
lib/routes/pornhub/search.js

Close #5569
/pornhub/category/popular-with-women
/pornhub/search/stepsister

feat: add pornhub category & search

---

assets/radar-rules.js
docs/new-media.md
lib/router.js
lib/routes/bsblog123/index.js
lib/routes/buaq/index.js
lib/routes/chuhaibiji/index.js
lib/routes/ichunqiu/index.js
lib/routes/kchuhai/index.js
lib/routes/navisec/index.js
lib/routes/secshi/index.js

新增加buaq.net站点RSS
Close #
https://rsshub.app/buaq

feat: 增加buaq.net站点RSS

---

docs/programming.md
lib/router.js
lib/routes/luogu/userFeed.js

feat: 增加洛谷用户动态 RSS

---

lib/routes/91ddcc/user.js

Close #5605
/91ddcc/user/1110644

fix: 才府社区用户动态链接

---

assets/radar-rules.js
docs/bbs.md
lib/router.js
lib/routes/wenxuecity/blog.js

Close #
`/wenxuecity/blog/:id`

feat: add wenxuecity blogs

---

docs/bbs.md
lib/router.js
lib/routes/91ddcc/stage.js

feat: add 才府社区驿站帖子

---

docs/en/picture.md
docs/picture.md
lib/router.js
lib/routes/1x/index.js

feat: add 1X photos

---

docs/university.md
lib/router.js
lib/routes/universities/tynu/tynu.js

feat: add 太原师范学院校园新闻

---

docs/en/multimedia.md
docs/multimedia.md
lib/router.js
lib/routes/pornhub/model.js
lib/routes/pornhub/pornstar.js

Close #
/pornhub/model/stacy-starando
/pornhub/pornstar/june-liu
/pornhub/pornstar/june-liu/tr

feat: add pornhub model/pornstar

---

docs/en/multimedia.md
docs/multimedia.md
lib/router.js
lib/routes/pornhub/users.js

feat: add pornhub users

---

lib/routes/oschina/news.js
lib/routes/oschina/u.js
lib/routes/oschina/user.js

Close #
http://127.0.0.1:1200/oschina/news

fix: oschina

---

docs/bbs.md
lib/router.js
lib/routes/newsmth/section.js

feat: add 水木社区分区文章

---

lib/routes/ssmh/index.js

Close #4196
https://github.com/DIYgod/RSSHub/issues/4196#issuecomment-691987984
https://rsshub.app/ssmh

fix: ssmh 图片链接获取错误

---

docs/en/shopping.md
docs/shopping.md
lib/router.js
lib/routes/appsales/index.js

Close #2512
/appsales/highlights

feat: add appsales

---

lib/routes/gcores/category.js

Close #5457
/gcores/category/articles

fix: gcores image is broken

---

lib/routes/dytt/index.js

fix: update links to dytt

---

lib/routes/twitter/list.js

Close #5421
/twitter/list/rinno_yui/%E5%A5%BD%E3%81%8D%E3%81%AA%E7%B5%B5%E6%8F%8F%E3%81%8D%E3%81%95%E3%82%93
/twitter/list/yzkoori/doll

fix: /twitter/list is broken

---

assets/radar-rules.js
docs/new-media.md
lib/router.js
lib/routes/tencent/wechat/msgalbum.js

无
/wechat/mp/msgalbum/MzA3MDM3NjE5NQ==/1375870284640911361
雷达测试地址
https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzA3MDM3NjE5NQ==&action=getalbum&album_id=1375870284640911361

feat: 添加微信公众号文章话题 Tag

---

lib/routes/kongfz/people.js

Close #5646
/kongfz/people/5032170

fix: 孔夫子旧书网用户动态

---

assets/radar-rules.js
docs/anime.md
lib/routes/manxiaosi/book.js

No related, 
1. 访问源站域名会被301重定向至新域名。
2. 具体章节页面取消手机UA限制
3. 具体章节页面结构略有调整
/manxiaosi/book/385

fix: 漫小肆 host 变更

---

docs/university.md
lib/routes/universities/zjut/design.js

Close #
/zjut/design/*                 *为  16  18  20

fix: 浙工大设计与建筑学院description部分获取不全

---

docs/other.md
lib/router.js
lib/routes/3k8/latest.js

fix: update links of 爱Q生活网

---

docs/game.md
lib/router.js
lib/routes/4gamers/topic.js

無
`/4gamers/topic/gentlemen-topic`

feat: add 4Gamers 首頁上方主題內分區

---

assets/radar-rules.js
docs/bbs.md
lib/router.js
lib/routes/wenxuecity/bbs.js
lib/routes/wenxuecity/hot.js

Close #
* /wenxuecity/hot/9
* /wenxuecity/bbs/tzlc
* /wenxuecity/bbs/tzlc/0
* /wenxuecity/bbs/tzlc/1

feat: wenxuecity bbs

---

lib/routes/hpoi/info.js

Signed-off-by: ueiu <bautuoyoul@gmail.com>
Close #5352 
/hpoi/info/all

fix: HPOI情报无法正确抓取图片(#5352)

---

docs/social-media.md
lib/router.js
lib/routes/douban/replies.js

Close #5647 
/douban/replies/xiaoyaxiaoya

feat: add 豆瓣日记最新回应

---

lib/routes/reuters/channel.js
lib/routes/reuters/utils.js

未解决图片显示问题
Close #5578
/reuters/channel/cn/analyses

fix: reuters

---

lib/routes/outagereport/service.js

Close #5636 
outagereport/ubisoft/5

fix: 修复outage.report输出RSS报错

---

docs/traditional-media.md
lib/router.js
lib/routes/cctv/special.js

feat: add 央视网新闻专题

---

docs/government.md
lib/router.js
lib/routes/gov/taiwan/mnd.js

feat: add 中華民國國防部即時軍事動態

---

lib/routes/huxiu/utils.js

fix: 虎嗅网补充文章题图

---

docs/traditional-media.md
lib/router.js
lib/routes/wallstreetcn/live.js

Close #5713
/wallstreetcn/live

feat: add 华尔街见闻实时快讯

---

lib/routes/caixin/article.js

老 API 又工作了
This reverts commit 18b58d5493b601a6592eff1ba276c49a700f1b7f.
Close #

revert: 回滚财新旧版 API

---

lib/routes/gq/tw/index.js

Close #5738
/gq/tw/entertainment/celebrities

fix: GQ台灣部分图集

---

docs/government.md
lib/routes/embassy/supportedList.js

feat: 中国驻外使领馆通知订阅源 add 驻马来西亚大使馆支持

---

lib/routes/ithome/index.js

/ithome/:caty
see https://docs.rsshub.app/new-media.html#it-zhi-jia-fen-lei-zi-xun

fix: ithome failure

---

lib/routes/pornhub/category_url.js

Close #
/pornhub/category_url/video%3Fo%3Dmv

fix: pornhub category_url dom

---

docs/university.md
lib/router.js
lib/routes/universities/uestc/cqe.js

Close #
/uestc/cqe
/uestc/cqe/hdyg
/uestc/cqe/tz
/uestc/cqe/kctz
/uestc/cqe/lrxb

feat:add uestc cqe

---

lib/routes/bilibili/followings_article.js
lib/routes/bilibili/followings_video.js

fix: bilibili Cookie overdue

---

lib/routes/juejin/utils.js

Close #
/juejin/category/frontend

fix bug: 修复掘金抓取异常

---

docs/government.md
lib/router.js
lib/routes/npc/index.js

/npc/c183
/npc/c184
/npc/c185
/npc/c189
/npc/c12435
/npc/c10134

feat: add 中国人大网

---

lib/routes/solidot/_article.js
lib/routes/solidot/main.js
lib/routes/solidot/sectigo.pem
lib/routes/solidot/wotrust.pem

It's a much safer option than #5389 
Close #5759 & Fix #5385 #5553
/solidot/www

fix: solidot chain issue 导致抓取失败

---

docs/university.md
lib/router.js
lib/routes/universities/jnu/xysx/index.js
lib/routes/universities/jnu/yw/index.js

Close #
/jnu/xysx/yxsd
/jnu/xysx/bmkx
/jnu/yw/tt
/jnu/yw/yw

feat: add 暨南大学 JNU

---

docs/other.md
lib/router.js
lib/routes/aqicn/index.js

Close #3662 
/aqicn/beijing/pm25,pm10

feat: aqicn 显示更详细的空气污染成分

---

docs/university.md
lib/router.js
lib/routes/universities/ustc/index.js
lib/routes/universities/ustc/jwc/index.js

Close #
/ustc/news
/ustc/news/gl
/ustc/news/jx
/ustc/news/ky
/ustc/news/fw
/ustc/jwc
/ustc/jwc/info
/ustc/jwc/teaching
/ustc/jwc/exam
/ustc/jwc/exchange

feat: add USTC 中国科学技术大学

---

docs/bbs.md
docs/en/install/README.md
docs/en/social-media.md
docs/install/README.md
docs/social-media.md
lib/config.js
lib/routes/nga/post.js

Cannot open bbs-thread to read. Rejected by a redirect page with response header HTTP 403.
`http://127.0.0.1:1200/nga/post/22708129`

fix: (semi-fix) login to NGA to prevent 403 error.

---

docs/university.md
lib/router.js
lib/routes/universities/cas/cg/index.js

feat: add 中国科学院成果转化

---

lib/routes/ff14/ff14_zh.js

更新api网址，之前的已不可用
<del>纯萌新第一次提交PR，如有错误希望大佬帮忙改改</del>
Close #
/ff14/ff14_zh/all

fix: FF14官网API接口更新

---

docs/new-media.md
lib/router.js
lib/routes/ofweek/news.js

feat: add route for ofweek

---

docs/traditional-media.md
lib/router.js
lib/routes/zsnews/index.js

none
/zsnews/index/35
/zsnews/index/36
/zsnews/index/37
/zsnews/index/38
/zsnews/index/39

feat: add route of 'zsnews.cn'

---

lib/routes/lol/newsindex.js

Close #5822
https://rsshub.app/lol/newsindex/ss

fix: adjust lolnews default timezone

---

lib/routes/coolapk/utils.js

Close #5819
https://rsshub.app/coolapk/huati/应用加入或更新AppShortcuts
https://rsshub.app/coolapk/huati/今天又有应用更新TargetAPI了

fix: coolapk line wrap

---

docs/design.md
docs/en/design.md
lib/router.js
lib/routes/behance/index.js

feat: add behance user appreciations

---

lib/routes/bbc/utils.js

fix: BBC 中文网图片

---

docs/en/government.md
docs/government.md
lib/router.js
lib/routes/wto/dispute-settlement.js

Close #5842
/wto/dispute-settlement

feat: add WTO dispute settlement news

---

lib/routes/vol/lastupdate.js

fix: vol cover undifined

---

lib/routes/creaders/headline.js

fix: creaders 解码错误

---

docs/bbs.md
lib/router.js
lib/routes/wenxuecity/news.js

feat: add 文学城焦点新闻

---

docs/en/social-media.md
docs/social-media.md
lib/routes/twitter/list.js

fix: update twitter list cache key and example

---

docs/university.md

doc: 补充 华南理工大学土木与交通学院学工通知 路由说明文档

---

docs/other.md
lib/router.js
lib/routes/cktest/policy.js

feat: add 中国工程科技知识中心产业政策

---

lib/routes/aiyanxishe/home.js

Close #5660
/aiyanxishe/109/hot

fix: aiyanxishe

---

assets/radar-rules.js

为
- `/bilibili/user/article/:uid`
- `/bilibili/user/fav/:uid`
- `/bilibili/user/coin/:uid`
- `/bilibili/user/followers/:uid`
- `/bilibili/user/followings/:uid`
- `/bilibili/user/bangumi/:uid`
添加 Radar 规则

feat: add more bilibili radar rules

---

lib/routes/xiaoheihe/discount.js

fix: 小黑盒PC游戏折扣信息

---

lib/routes/mofcom/article.js

fix: mofcom css selector changed (#5879)

---

lib/routes/coronavirus/dxy.js

无
https://rsshub.app/coronavirus/dxy

fix: 播报的内容是全球的

---

docs/game.md
lib/routes/douban/people/status.js
lib/routes/twitter/user.js
lib/routes/twitter/utils.js
lib/routes/weibo/user.js
lib/routes/weibo/utils.js

- 更可读的微博个人时间线、Twitter 用户时间线、豆瓣用户广播
- 可能修复了 bug
- 潜在地引入了新的 bug
无
https://rsshub.app/douban/people/113894409/status
https://rsshub.app/weibo/user/1642909335
https://rsshub.app/twitter/user/diygod

feat: more readable 微博个人时间线, Twitter 用户时间线, 豆瓣用户广播

---

docs/finance.md
lib/router.js
lib/routes/stcn/news.js

feat: add 证券时报网要闻

---

lib/routes/embassy/supportedList.js

fix: 英国大使馆通知DOM改动

---

docs/en/social-media.md
docs/social-media.md
lib/router.js
lib/routes/dev.to/top.js

Doesn't seem to be any
/dev.to/top/week
/dev.to/top/month
/dev.to/top/year
/dev.to/top/infinity
I don't know Chinese, so made the docs with google translate. Thanks for an awesome project!

fear: add dev.to top posts route

---

lib/routes/initium/full.js

This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/diygod/rsshub).

chore: apply fixes from CodeFactor

---

docs/traditional-media.md
lib/router.js
lib/routes/sina/sports.js

Close #5841
/sina/sports/volley

feat: add 新浪体育综合

---

lib/routes/npc/index.js

fix: 中国人大网

---

docs/university.md
lib/router.js
lib/routes/universities/hnust/chem/index.js

feat: add 湖南科技大学化学化工学院通知

---

docs/new-media.md
lib/router.js
lib/routes/sakurazaka46/blog.js

add 櫻坂46 公式 Blog
/sakurazaka46/blog

feat: add sakurazaka46 blog

---

docs/new-media.md
lib/routes/tencent/wechat/ershcimi.js

Close #5904
/wechat/ershicimi/813oxJOl

fix: 微信公众号二十次幂来源

---

lib/routes/cs/news.js

fix: 中证网中证快讯

---

docs/new-media.md

doc: update new-media.md sakurazaka46 author

---

lib/routes/initium/full.js

fix: 过滤端传媒 API 返回空值

---

docs/programming.md
lib/router.js
lib/routes/frontend/index.js

feat: add route of 'front-end-rss.now.sh'

---

docs/en/university.md
docs/university.md
lib/router.js
lib/routes/universities/mit/ocw-top.js

Doesn't seem to be any
/mit/ocw-top
I'd like to add a couple more routes and have a few questions. I'd be happy if someone helps me figure this out:
1. Is there anything I should change so it'll be easier to maintain them?
2. I noticed there are a bunch of university routes that aren't listed in the docs. Does it mean that all broken routes get removed until someone fix them?
3. Once I got the feed working, it started to generate a field called "guid" with "isPermaLink="false"". Is it something I should touch or just let it be?
Thanks!

feat: add mit ocw route

---

docs/programming.md

doc: update

---

docs/game.md
lib/router.js
lib/routes/ff14/ff14_global.js

Close #
New route: `/ff14/ff14_global/:lang/:type`
Examples:
* `/ff14/ff14_global/na/all`
* `/ff14/ff14_global/jp/updates`

feat: 添加 FF14 国际服新闻及通知（Lodestone）

---

lib/routes/game4399/forum.js

fix: forum4399

---

docs/en/study.md
docs/study.md
lib/routes/linkresearcher/index.js

/linkresearcher/category=theses&subject=生物

fix: add doi for linkresearcher

---

docs/finance.md
lib/router.js
lib/routes/stcn/data.js

feat: add 证券时报网数据

---

lib/routes/outagereport/service.js

Close #5636
/outagereport/ubisoft/5

fix: outagereport allowEmpty

---

lib/routes/outagereport/service.js

The default value seems to be 10, not 20(in the same line).

chore: comment in Outage.Report

---

docs/en/traditional-media.md
docs/traditional-media.md
lib/router.js
lib/routes/the-economist/download.js

Close #4861
/the-economist/download

feat: add The Economist 经济学人下载

---

docs/en/install/README.md
docs/install/README.md
lib/config.js
lib/routes/pixiv/pixiv-got.js
lib/routes/pixiv/token.js

https://github.com/DIYgod/RSSHub/issues/5916#issuecomment-713454769
/pixiv/*

fix: resolve `PIXIV_BYPASS_HOSTNAME` via DNS over HTTPS

---

docs/design.md
lib/router.js
lib/routes/zcool/discovery.js

Close #5954
/zcool/discovery/607!3!616!0!0!!!!1!-1!1

feat: add 站酷发现

---

docs/en/program-update.md
docs/program-update.md
lib/router.js
lib/routes/qnap/release-notes.js

Close #5971
/qnap/release-notes/qts

feat: add QNAP Release Notes

---

lib/routes/netease/news/rank.js

fix: 网易 encoding issue

---

docs/other.md
lib/router.js
lib/routes/sagawa/index.js

Close #5866
/sagawa/359554419420

feat: add 佐川急便快递查询

---

docs/finance.md
lib/router.js
lib/routes/stcn/kuaixun.js

feat: add 证券时报网快讯

---

docs/en/journal.md
lib/router.js
lib/routes/technologyreview/topic.js

Close #5779
/technologyreview/humans-and-technology
/technologyreview/election-2020
/technologyreview/artificial-intelligence
/technologyreview/biotechnology
/technologyreview/blockchain
/technologyreview/climate-change
/technologyreview/computing
/technologyreview/tech-policy
/echnologyreview/silicon-valley
/technologyreview/smart-cities
/technologyreview/space

feat: add MIT Technology Review

---

lib/routes/hanime/video.js

fix:hanime图片显示问题

---

lib/routes/bookwalkertw/news.js
lib/routes/erbingapp/news.js

无
/bookwalkertw/news
/erbingapp/news

fix: BOOKWALKERTW、二柄APP图片显示错误

---

lib/routes/liequtv/room.js

Close #5440
/liequtv/room/957699
/liequtv/room/203458

fix: 猎趣的开播提醒失效 #5440

---

lib/routes/zsnews/index.js

none
/zsnews/index/35
/zsnews/index/36
/zsnews/index/37
/zsnews/index/38
/zsnews/index/39

feat: 获取中山网文章全文预览

---

lib/routes/tencent/lemon/index.js

fix: 腾讯柠檬精选 Mac Apps

---

docs/government.md
lib/router.js
lib/routes/gov/harbin/kjj.js

feat: add 哈尔滨市科技局

---

lib/routes/ifeng/feng.js
lib/routes/ifeng/utils.js

fix: 修复大风号api
feat: 大风号支持内嵌视频
Close #

fix: 修复大风号api

---

docs/blog.md
lib/router.js
lib/routes/gwern/category.js

feat: add gwern

---

lib/routes/douban/replies.js

fix: 豆瓣日记最新回应

---

lib/routes/erbingapp/news.js

fix: 修复二柄APP部分图片显示问题
/erbingapp/news/

fix: 修复二柄APP部分图片显示问题

---

docs/traditional-media.md
lib/router.js
lib/routes/udn/global.js

+ `/udn/global/newest`
+ `/udn/global/過去24小時`

feat: add udn global

---

README.md

RSS readers like Feedly and Inoreader are [aggregators](https://en.wikipedia.org/wiki/Comparison_of_feed_aggregators?oldformat=true). RSSHub is a feed generator.

docs: replace aggregator with generator

---

docs/social-media.md
lib/router.js
lib/routes/douban/weekly_best.js

Close #6048
/douban/movie/weekly/tv_chinese_best_weekly

feat: add 豆瓣一周口碑榜

---

docs/finance.md
lib/router.js
lib/routes/jinshi/index.js

feat: add jin10.com

---

docs/en/traditional-media.md
docs/traditional-media.md
lib/router.js
lib/routes/wsj/index.js

feat: add wsj opinion

---

assets/radar-rules.js
docs/en/multimedia.md
docs/en/social-media.md
docs/multimedia.md
docs/social-media.md
lib/router.js
lib/routes/youtube/channel.js
lib/routes/youtube/playlist.js
lib/routes/youtube/user.js

docs: replace Youtube with YouTube

---

docs/blog.md
lib/router.js
lib/routes/benedictevans/recent.js

feat: add benedictevans

---

docs/en/traditional-media.md
docs/traditional-media.md
lib/router.js
lib/routes/chinafile/index.js

Close #5125 #5882 #5124
/chinafile
/chinafile/all
/chinafile/ngo

feat: ChinaFile

---

lib/routes/changku/index.js

fix: 场库视频播放问题 #6036

---

docs/new-media.md
lib/router.js
lib/routes/guancha/topic.js

fix: 观察者网风闻话题

---

docs/new-media.md
lib/router.js
lib/routes/twreporter/category.js
lib/routes/twreporter/fetch_article.js
lib/routes/twreporter/newest.js
lib/routes/twreporter/photography.js

(Reopen and) close #4838.
@jessejesset
- `/twreporter/newest`
- `/twreporter/photography`
- `/twreporter/category/reviews`
另外，需要注意的是：
1. 偶有极个别文章不能全文输出（即未能完整加载一些图片）
2. 当前不支持网站的 categories/infographics

feat: support twreporter

---

docs/new-media.md
lib/router.js
lib/routes/twreporter/category.js
lib/routes/twreporter/newest.js
lib/routes/twreporter/photography.js

fix: typos in twreporter

---

lib/routes/jinshi/index.js

refactor: improve readability for jinshi/index.js

---

docs/other.md
lib/router.js
lib/routes/grandchallenge/challenges.js
lib/routes/grandchallenge/user.js

Close #
/grandchallenge/challenges
/grandchallenge/user/:id
example:
/grandchallenge/challenges
/grandchallenge/user/Isensee

feat: add grand-challenge

---

docs/multimedia.md
lib/router.js
lib/routes/cntv/cntv.js

Close #
/cntv/:column
example:
/cntv/TOPC1451528971114112

feat: add cntv column

---

docs/new-media.md
lib/router.js
lib/routes/daodu/index.js

feat: add 科技島讀

---

docs/bbs.md
lib/router.js
lib/routes/tieba/user.js

无
/tieba/user/:uid
uid 为必选参数，用户 ID ，通过地址栏 `un` 字段获取。

feat: add 贴吧用户发帖

---

lib/routes/novel/biquge.js

Close #6087
/novel/biquge/95_95192

fix: 笔趣阁章节乱序

---

lib/routes/netease/news/rank.js

Close #6083
/netease/news/rank/whole/click/day

fix: 网易新闻文章内视频无效

---

docs/new-media.md
lib/router.js
lib/routes/tencent/wechat/wxnmh.js

Close #5324
/wechat/wxnmh/51798
/wechat/wxnmh/104665
/wechat/wxnmh/151445

feat: add wxnmh.com #5324

---

lib/routes/chinafile/index.js

fix: invalid date for chinafile

---

lib/routes/mi/crowdfunding.js

fix: 小米众筹无商品时报错

---

lib/routes/earthquake/ceic.js

Close #5718
/earthquake/ceic/1

fix: 中国地震台指定时间段内无地震报错

---

docs/picture.md
lib/router.js
lib/routes/8kcos/article.js
lib/routes/8kcos/cat.js
lib/routes/8kcos/const.js
lib/routes/8kcos/latest.js

Close #
1./8kcos/
2./8kcos/cat/8kasianidol

feat：add 8kcosplay

---

lib/routes/google/album.js

/google/album/msFFnAzKmQmWj76EA

fix: router 'google album'

---

docs/new-media.md
lib/router.js
lib/routes/cninfo/announcement.js

Close #6102
/cninfo/announcement/szse/000002/gssz0000002/category_ndbg_szsh

docs: fix cninfo example

---

docs/anime.md
lib/router.js
lib/routes/ssmh/category.js

Close #
/ssmh/category/:cid
Example:
/ssmh/category/6  
/ssmh/category/1

feat: add 紳士漫畫 分类更新

---

lib/routes/bilibili/dynamic.js

Close #
路由: /bilibili/user/dynamic/:uid/:disableEmbed?
/bilibili/user/dynamic/2267573

feat: 优化B站动态url

---

lib/routes/guokr/calendar.js

Close #6131
https://rsshub-git-fix-guokr-author.diy.vercel.app/guokr/calendar

fix: update guokr author field

---

lib/routes/feixuew/index.js

fix: invalid links from 飞雪娱乐网

---

lib/router.js

fix: route of 得到首页

---

docs/new-media.md
lib/router.js
lib/routes/guancha/member.js

feat: add 观察者网观学院

---

lib/routes/technologyreview/topic.js

none
/technologyreview/humans-and-technology
/technologyreview/election-2020
/technologyreview/artificial-intelligence
/technologyreview/biotechnology
/technologyreview/blockchain
/technologyreview/climate-change
/technologyreview/computing
/technologyreview/tech-policy
/technologyreview/silicon-valley
/technologyreview/smart-cities
/technologyreview/space

feat: add description for technologyreview

---

docs/new-media.md
lib/router.js
lib/routes/guancha/headline.js

feat: add 观察者网头条

---

lib/routes/thunderbird/release.js

fix: thunderbird fetch 404

---

lib/routes/huxiu/utils.js

fix: 虎嗅文章显示视频

---

docs/en/game.md
docs/game.md
lib/router.js
lib/routes/konami/pesmobile.js

feat: add Konami PES mobile

---

lib/routes/huxiu/utils.js

fix: 虎嗅网文字不显示问题 #6165

---

docs/en/install/README.md
docs/en/social-media.md
docs/install/README.md
docs/social-media.md
lib/router.js
lib/routes/instagram/index.js
package.json
yarn.lock

Close #5860
Especially useful when you need to follow private accounts.
`/instagram/user/stefaniejoosten`
The following envs are required:
-   `IG_USERNAME`: Your Instagram username
-   `IG_PASSWORD`: Your Instagram password

feat: add Instagram

---

docs/programming.md
lib/routes/juejin/collection.js
lib/routes/juejin/favorites.js

Close #6155
/juejin/posts/3051900006845944
/juejin/collections/1697301682482439
/juejin/collection/6845243180586123271

docs: update juejin.im #6155

---

lib/router.js
lib/routes/zaobao/interactive.js
lib/routes/zaobao/util.js

Close #6125 
`/zaobao/realtime/china`
`/zaobao/interactive-graphics` （仅供测试互动新闻，不建议实际使用，因为没有获取第一条新闻）

fix: zaobao.com from hk

---

docs/social-media.md
lib/router.js
lib/routes/douban/replied.js

feat: add 豆瓣最新回应过的日记

---

lib/routes/langlive/room.js

Close #6151
/langlive/room/2477024
/langlive/room/3159942

fix: play.lang.live issue #6151

---

lib/routes/ciweimao/chapter.js

Close #6170
/ciweimao/chapter/100085444

fix: 刺猬猫RSS异常 #6170

---

docs/design.md
lib/router.js
lib/routes/uisdc/topic.js

feat: add 优设网细节猎人

---

lib/routes/huxiu/utils.js

fix: wrong attribute name

---

lib/routes/universities/scut/scutyjs.js

fix: 华工研究生院添加日期

---

lib/routes/bjnews/news.js

Close #6180
/bjnews/realtime
/bjnews/news
/bjnews/point

fix: bjnews issue #6180

---

docs/design.md
lib/router.js
lib/routes/uisdc/zt.js

feat: add 优设网设计专题

---

lib/routes/juejin/trending.js

Close #6192
/juejin/trending/all/monthly
/juejin/trending/frontend/weekly
/juejin/trending/devops/weekly

fix: 掘金热门抓取失败 #6192

---

docs/new-media.md
lib/router.js
lib/routes/matters/latest.js

Close #6130
/matters/latest/
/matters/latest/heat
/matters/latest/essence

feat: Matters 熱議 & 精华 #6130

---

docs/en/traditional-media.md
docs/traditional-media.md
lib/router.js
lib/routes/wsj/index.js

Add WSJ Chinese Edition
`/wsj/zh-cn`
`/wsj/zh-tw`

feat: add wsj cn

---

docs/game.md
lib/router.js
lib/routes/yystv/docs.js

feat: add 游研社-全部文章

---

lib/routes/telegram/channel.js

feat: telegram channel, show attachment name in title

---

lib/routes/xiaoyuzhou/pickup.js

feat: 增加「小宇宙-发现」每日缓存

---

docs/social-media.md
lib/router.js
lib/routes/popiask/tapechat_questions.js

直接从Popiask的路由改出来的，反正是一家人做的产品。懒，暂时只做了文字，没有语音/图片/misc.。
Close #
`/tapechat/questionbox/:sharecode/:pagesize?` e.g. `/tapechat/questionbox/TOAH7BBH`

feat: Tapechat 小纸条提问箱

---

docs/shopping.md
lib/router.js
lib/routes/mi/youpin/new.js

fix: 小米有品按上新时间排序

---

lib/routes/pubmed/trending.js

fix: pubmed trending articles

---

docs/university.md

docs: matching end tag

---

docs/study.md
lib/router.js
lib/routes/ctfhub/search.js
lib/routes/ctfhub/upcoming.js

* `/ctfhub/search/:limit?/:form?/:class?/:title?` (renamed from `/ctfhub/calendar`)
* `/ctfhub/upcoming/:limit?`

feat: add new route for ctfhub

---

docs/multimedia.md
lib/router.js
lib/routes/subhd/newest.js

feat: add subHD.tv #6267

---

docs/en/install/README.md
docs/install/README.md
lib/config.js
lib/middleware/parameter.js

fix: sci-hub mirror address

---

lib/routes/missevan/drama.js

Close #6300
/missevan/drama/28499

feat: add 猫耳FM广播剧

---

lib/routes/hpoi/info.js

fix: hpoi 无法抓取

---

lib/routes/producthunt/today.js

Close #6296
/producthunt/today

fix: product hunt today

---

docs/traditional-media.md

docs: /traditional-media.html#nhk

docs: fixing i-CABLE breaking NHK

---

lib/routes/leetcode/articles.js
package.json
yarn.lock

Close #6009
/leetcode/articles

fix: leetcode articles

---

lib/routes/guancha/topic.js

fix: /guancha/topic/0

---

lib/routes/itjuzi/invest.js

fix: IT桔子投融资事件

---

lib/routes/universities/nuaa/yjsy/yjsy.js

fix: nuaa 研究生院

---

lib/routes/guokr/scientific.js

feat: generate description for /guokr/scientific

---

docs/multimedia.md
lib/router.js
lib/routes/missevan/latest.js

feat: add 猫耳FM最新广播剧

---

lib/routes/earthquake/ceic.js

Close #6362
/earthquake/ceic/5

fix: 地震速报报错

---

docs/en/program-update.md
docs/program-update.md
lib/router.js
lib/routes/qttabbar/change-log.js

Close #6369
/qttabbar/change-log

feat: add qttabbar change log

---

docs/new-media.md
lib/router.js
lib/routes/proletar/index.js

feat: add 无产者评论

---

docs/bbs.md
docs/en/bbs.md
lib/router.js
lib/routes/lowendtalk/discussion.js

Close #6378
/lowendtalk/discussion/168480

feat: add lowendtalk discussion

---

lib/routes/futunn/highlights.js
lib/routes/zaker/focusread.js

None
```
/zaker/channel/13
/futunn/highlights
```

feat: filter out unnecessary items (zaker & futunn)

---

assets/radar-rules.js
docs/live.md

[虎牙 - 直播间开播](https://docs.rsshub.app/live.html#hu-ya-zhi-bo-zhi-bo-jian-kai-bo)

feat: add huya radar rule

---

docs/en/government.md
docs/government.md
lib/router.js
lib/routes/us/ustr/press-releases.js

Close #6382
/ustr/press-releases

feat: add the united states trade representative press release

---

docs/picture.md
docs/reading.md
lib/router.js
lib/routes/cool18/index.js

feat: add 酷18分站 & 禁忌书屋

---

docs/en/program-update.md
docs/program-update.md
lib/router.js
lib/routes/bandisoft/index.js

Close #6390
/bandisoft/bandizip

feat: add bandisoft history

---

docs/en/government.md
docs/government.md
lib/router.js
lib/routes/us/treasury/press-releases.js

Close #6391
/treasury/press-releases

feat: add u.s. department of the treasury press releases

---

docs/program-update.md
lib/router.js
lib/routes/bilibili/app.js

Close #6388
/bilibili/app/android

feat: 哔哩哔哩更新情报

---

docs/en/new-media.md
docs/new-media.md
lib/router.js
lib/routes/thebrain/blog.js

feat: add the brain blog

---

docs/new-media.md
lib/router.js
lib/routes/ccf/news.js

feat: add 中国计算机学会新闻

---

docs/en/new-media.md
docs/new-media.md
lib/router.js
lib/routes/iea/index.js

Close #6399
/iea/news-and-events

feat: add international energy agency news and events

---

docs/study.md
lib/router.js
lib/routes/yinxiang/category.js
lib/routes/yinxiang/personal.js
lib/routes/yinxiang/tag.js

Close #6408
/yinxiang/personal/ZUhuRTmW5SKE7vvHPqI7cg

feat: add 印象识堂用户公开笔记 & 笔记分类 & 笔记标签

---

docs/new-media.md
lib/router.js
lib/routes/cmes/news.js

feat: add 中国机械工程学会学会新闻

---

lib/routes/noi/index.js
lib/routes/noi/province-news.js
lib/routes/noi/winners-list.js

NOI 全国青少年信息学奥林匹克竞赛更换了新版的网站，原先的路由已经失效。
/noi
/noi/winners-list
/noi/province-news

fix: 适配 NOI 全国青少年信息学奥林匹克竞赛新版网站

---

lib/routes/everything/changes.js
lib/routes/xyplorer/whatsnew.js

Close #6423
/everything/changes
/xyplorer/whatsnew

fix: everything changes & xyplorer what's new without newlines

---

lib/routes/universities/cqu/news/tz.js

fix: 重庆大学新闻网通知公告

---

lib/routes/instagram/utils.js

Sorry to spam on Instagram again... It is reported that the bridge could lead to account suspension. And I realize I didn't add the post login flow
````javascript
process.nextTick(async () => await ig.simulate.postLoginFlow());
````
which might lead to the case. So here is the patch. More feedbacks are welcomed.
````
/instagram/user/ladygaga
````

fix: try to fix instagram account suspension

---

lib/routes/lowendtalk/discussion.js

fix: latest comments from lowendtalk discussions

---

lib/routes/zhihu/zhuanlan.js

Close #6427
/zhihu/zhuanlan/c_1034016963944755200
/zhihu/zhuanlan/googledevelopers

fix: 知乎专栏 issue

---

lib/routes/douban/people/status.js

https://github.com/DIYgod/RSSHub/commit/ab843e4e0a7589a6755af1ef1cb3f673fe65bbe1#r45092323
为豆瓣个人广播可能出现的各种错误情况兜底
/douban/people/113894409/status
/douban/people/156428620/status
/douban/people/53803167/status

fix: douban people status: more checks in case of unstable and erroneous api response

---

lib/routes/paidai/news.js

fix: /paidai/news issue

---

lib/routes/sspai/series.js

fix: sspai series issue

---

assets/radar-rules.js
docs/shopping.md
lib/router.js
lib/routes/apple/appstore/in-app-purchase.js
lib/routes/craigslist/search.js

由于 Craigslist 关闭了对RSS的支持，本路由支持订阅Craigslist搜索结果
`/craigslist/:location/:type?querystring`
本地地址示范：
http://localhost:1200/craigslist/sfbay/sso?query=bike&sort=rel&search_distance=50&postal=95054&min_price=100&max_price=350

feat: add Craigslist search subscription

---

lib/routes/kpmg/insights.js

fix: /kpmg/insights issue

---

lib/routes/universities/slu/utils.js

Close #6432
/slu/tyyjkxy/14754
@BENDIT233 这间学校官网 HTTPS 配置好像有问题，这个 PR 实属曲线救国

fix: 上海立信会计金融学院 HTTPS

---

lib/routes/instagram/index.js

Close #6268 
`/instagram/tag/sky`

add: instagram tags

---

lib/routes/bendibao/news.js

Close #6470
/bendibao/news/heb

fix: 本地宝丢弃过期链接

---

lib/routes/v2ex/tab.js

fix: /v2ex/tab/hot returned undefined

---

docs/new-media.md
lib/router.js
lib/routes/interesting-sky/astronomical_events.js
lib/routes/interesting-sky/recent-interesting.js

Close #6462
/interesting-sky/astronomical_events
/interesting-sky/recent-interesting

feat: add 有趣天文奇观年度天象 & 近期事件专题

---

lib/routes/zhihu/zhuanlan.js

Close #6465
/zhihu/zhuanlan/-anki

fix: /zhihu/zhuanlan undefined title

---

docs/en/new-media.md
docs/new-media.md
lib/router.js
lib/routes/mathunion/fields-medal.js

Close #6457
/mathunion/fields-medal

feat: add fields medal

---

docs/en/traditional-media.md
docs/traditional-media.md
lib/router.js
lib/routes/phoronix/index.js

Close #
`/phoronix/category/Computers`

add: phoronix

---

lib/router.js

fix: remove duplicate route for udn

---

lib/routes/sciencemag/cover.js

fix: /sciencemag/cover

---

lib/routes/initium/full.js

Close #
`/initium/news-brief/zh-hant`

feat: improve initium fetching performance & fix time zone

---

lib/routes/hex-rays/index.js

fix: outdated route /hex-rays/news

---

lib/routes/amazon/ku.js

none
/amazon/ku/back
/amazon/ku/this
/amazon/ku/next

fix: kindle unlimited

---

docs/en/traditional-media.md
docs/traditional-media.md
lib/router.js
lib/routes/ft/myft.js

feat: add FT.com - myFT RSS

---

docs/university.md
lib/router.js
lib/routes/universities/uestc/gr.js

feat: 电子科技大学 - 研究生院通知公告

---

lib/routes/zhihu/zhuanlan.js

fix: 知乎专栏 pubDate 1970

---

docs/new-media.md
lib/routes/donews/index.js
lib/routes/donews/utils.js

none
/donews
/donews/company
/donews/business
/donews/ent
/donews/digital
/donews/idonews

fix: outdated route DoNews

---

docs/multimedia.md

docs: remove non-support category of javdb

---

docs/program-update.md

docs: fix table syntax

---

docs/game.md
lib/router.js
lib/routes/steam/news.js

Close #6431
/steam/news/1091500
/steam/news/271590

fix: steam news center

---

lib/routes/sketch/beta.js

fix: outdated route /sketch/beta

---

assets/radar-rules.js

feat: add juejin radar rule

---

docs/en/new-media.md
docs/new-media.md
lib/router.js
lib/routes/nace/blog.js

feat: add national association of colleges and employers blog

---

docs/forecast.md
lib/router.js
lib/routes/tingdiantz/95598.js

路由地址：`/tingdiantz/95598/:province/:city/:district?`  
必选参数：`:province` 省，2~3位拼音缩写，详情见http://www.sttcq.com/td/, `:city` 市，同上  
可选参数：`:district` 区，同上
完整路由地址：/tingdiantz/95598/hb1/wh/wc/

feat: add 95598停电查询网

---

docs/bbs.md
lib/routes/tieba/user.js

Close #6549
/tieba/user/十二月夜_鈴音

feat: add tieba users' post contents

---

docs/government.md
lib/router.js
lib/routes/gov/cppcc/index.js

Close #6545
/cppcc/zxww-newcppcc-wyjy-index

feat: add 中国政协网

---

docs/program-update.md
lib/router.js
lib/routes/yuanliao/index.js

feat: add 猿料标签

---

docs/university.md
lib/router.js
lib/routes/universities/uestc/sice.js

Close #
https://rsshub.app/uestc/sice

feat: add Uestc sice notice

---

docs/install/README.md
docs/social-media.md
lib/config.js
lib/router.js
lib/routes/zhihu/timeline.js

[https://rsshub.app/zhihu/timeline](https://rsshub.app/zhihu/timeline)
Zhihu follow timeline. Cookie is required.
知乎关注时间线。需要 cookie.

feat: add zhihu follow timeline

---

docs/en/traditional-media.md
docs/traditional-media.md
lib/router.js
lib/routes/rfa/index.js

Route: /rfa/:language?/:channel?/:subChannel?
Example: /rfa/english

feat: add Radio Free Asia

---

docs/en/program-update.md
docs/program-update.md
lib/router.js
lib/routes/microsoft-store/updates.js

Close #5544
/microsoft-store/updates/9WZDNCRFHVN5/CN

feat: add microsoft store updates

---

lib/routes/douban/later.js

fix: /douban/movie/later

---

lib/routes/idaily/index.js

fix: iDaily error

---

lib/routes/xiaoheihe/news.js

fix: 小黑盒游戏新闻原文链接

---

lib/routes/universities/cpu/home.js

fix: 中国药科大学

---

lib/routes/universities/bit/cs/cs.js
lib/routes/universities/bit/cs/utils.js
lib/routes/universities/bit/jwc/jwc.js
lib/routes/universities/bit/jwc/utils.js

fix: 北京理工大学

---

docs/en/traditional-media.md
docs/traditional-media.md
lib/router.js
lib/routes/apnews/index.js

feat: add top stories route for Associated Press News

---

lib/routes/netease/open/vip.js

fix: outdated route /open163/vip

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/pr-deploy-route-test.yml
scripts/workflow/test-route/identify.js
scripts/workflow/test-route/test.js

flow: pr auto test template

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/pr-deploy-route-test.yml
scripts/workflow/test-route/identify.js
scripts/workflow/test-route/test.js

- Update PR template
- Test against vercel deployment

[ci skip] ci: auto test pr routes

---

docs/en/bbs.md

docs: add scboy endoc

---

scripts/workflow/test-route/identify.js
scripts/workflow/test-route/test.js

Pr autotest

---

lib/router.js

docs: duplicate cgtn comments

---

lib/routes/allnow/column.js

fix allnow.com

---

lib/routes/youtube/channel.js
lib/routes/youtube/playlist.js
lib/routes/youtube/user.js

https://rsshub.app/youtube/channel/UCZGYJFUizSax-yElQaFDp5Q
https://rsshub.app/youtube/user/StarWars
https://rsshub.app/youtube/playlist/PL148kCvXk8pBViyaR1fRFfG_N54C5ApoY

Standardize the titles and descriptions for the YouTube RSS feeds.

---

lib/routes/youtube/channel.js
lib/routes/youtube/playlist.js
lib/routes/youtube/user.js

https://rsshub.app/youtube/channel/UCZGYJFUizSax-yElQaFDp5Q
https://rsshub.app/youtube/user/StarWars
https://rsshub.app/youtube/playlist/PL148kCvXk8pBViyaR1fRFfG_N54C5ApoY

Only show the YouTube thumbnail image if the video is not embedded.

---

lib/routes/manhuagui/comic.js

一些被列为限制级的漫画无法读取
https://rsshub.app/manhuagui/comic/4740

fix: manhuagui parse for the blocked comics

---

lib/routes/universities/ahut/cstzgg.js
lib/routes/universities/ahut/jwc.js
lib/routes/universities/ahut/news.js

none
/ahut/jwc
/ahut/news
/ahut/cstzgg

fix: 安徽工业大学

---

lib/routes/icity/index.js

Otherwise guid will be the same for all entries
/icity/sai

Fix icity item link

---

docs/government.md
lib/router.js
lib/routes/gov/shenzhen/xxgk/zfxxgj.js

Close #
- **如果不是, 请留空本列表**. **LEAVE BLANK** if it is not a submitting new RSS Script

增加对深圳市人民政府部分信息RSS订阅

---

docs/en/journal.md
lib/router.js
lib/routes/technologyreview/index.js

feat: add homepage route for Technology Review

---

docs/en/game.md
docs/game.md
lib/router.js
lib/routes/feed-the-beast/modpack.js

Close #
https://rsshub.app/feed-the-beast/modpack/ftb_presents_direwolf20_1_16

add: feed the beast modpack updates

---

docs/en/install/README.md
docs/install/README.md
lib/routes/instagram/index.js

`NOROUTE`
增加仅对instagram适用的代理设置

[Instagram]增加代理设置，修改抛出错误的方式

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/pr-deploy-route-test.yml
scripts/workflow/test-route/test.js

fix: core reference, template

---

docs/social-media.md
lib/router.js
lib/routes/zhihu/hot.js

Close #6626
```routes
/zhihu/hot
```

feat: add zhihu hotlist with categories

---

lib/routes/pediy/topic.js

Close #
http://127.0.0.1:1200/pediy/topic/translate

增加看雪论坛外文翻译版块rss

---

docs/bbs.md

Close #6596
```
NOROUTE
```
增加了对应的文档

增加看雪论坛外文翻译板块的文档 update pediy bbs doc

---

.github/PULL_REQUEST_TEMPLATE.md

template: make CI identifier clear

---

lib/routes/tesla/update.js

Close #
```routes
/tesla
```
修复了tesla订阅的地址不正确的问题

fix: fix tesla link path

---

lib/routes/hentai-cosplays/porn-images-xxx.js
lib/routes/hentai-cosplays/utils.js

```routes
/porn-images-xxx
```
Before this PR, the route can only show single pic of the results. This PR add ability to continue to read every single item searched by user.

feat: load pics of searched items

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/pr-deploy-route-test.yml
scripts/workflow/test-route/identify.js

Close #
```routes
NOROUTE
```
在重新开启或新commit更新时重新检查

docs: close pr on wrong format, reopen to rescan

---

lib/routes/caixin/article.js

Reverts DIYgod/RSSHub#6588 for now, more investigation required.

Revert "feat: add fulltext to the article route of caixin"

---

assets/radar-rules.js
docs/multimedia.md
lib/router.js
lib/routes/141jav/141jav.js
lib/routes/141ppv/141ppv.js

Close #
```routes
/141jav/new
/141jav/popular/7
/141jav/popular/30
/141jav/popular/60
/141ppv/new
/141ppv/popular/7
/141ppv/popular/30
/141ppv/popular/60
```
仿照onejav，只是更新了爬取地址，这2个站和onejav是一个网站模板，但内容不同,我自己已经测试成功了
我仿照onejav，修改了以下文件
lib/routes/141jav/141jav.js
lib/routes/141ppv/141ppv.js
docs/multimedia.md
assets/radar-rules.js …

新增141jav&141ppv[2个rss规则]

---

docs/multimedia.md
lib/router.js
lib/routes/newzmz/index.js

Close #6658
```routes
/newzmz
```

feat: add NEW字幕组

---

docs/blog.md
docs/en/blog.md
lib/router.js
lib/routes/phrack/index.js

add phrack magazine blog

---

lib/routes/hentai-cosplays/utils.js

improvement for #6666 , this PR enable this route to show all pics with modified url.
```routes
/porn-images-xxx
```

fix: use story path to show all pics

---

lib/routes/bde4/index.js

Close #6681
```routes
/bde4
```

fix: 哔嘀影视返回最新 BT / 磁力源

---

assets/radar-rules.js
docs/university.md
lib/router.js
lib/routes/universities/cqut/cqut-libnews.js
lib/routes/universities/cqut/cqut-news.js

Close #
```routes
/cqut/news
/cqut/libnews
```

Add CQUT news

---

docs/new-media.md
lib/router.js
lib/routes/chiculture/topic.js

Close #6656
```routes
/chiculture/topic
```

feat: add 通識·現代中國議題熱話

---

docs/en/game.md

Close #5743
```routes
NOROUTE
```
I don't speak Chinese so I can't contribute to that documentation. I've not tested if this documentation renders properly but it seems correct.

Tip people to the official RSS feeds in Steam

---

docs/new-media.md
lib/router.js
lib/routes/banyuetan/byt.js

Close #6657
```routes
/banyuetan/byt
```

feat: add 半月谈时事大事库

---

assets/radar-rules.js
docs/university.md
lib/router.js
lib/routes/universities/cqwu/news.js

Close #
```routes
/cqwu/news/notify
/cqwu/news/academiceve
```

add 重庆文理学院

---

docs/programming.md
lib/router.js
lib/routes/meituan/open/announce.js

Close #
```routes
meituan/open/announce
```

feat: add 美团开放平台公告

---

.eslintrc
assets/radar-rules.js
docs/other.md
docs/university.md
lib/routes/metred/fuli.js
lib/routes/universities/cqwu/news.js
lib/routes/universities/uestc/sice.js

Close #6703 
```routes
/metred/fuli
```
在修复 #6703 的过程中，我修改了该路由的大部分实现。原作者使用类似爬虫 + `cheerio` 解析的方式，我改成了直接抓取 API。
顺便修复了 `npm run format` 出错的问题，参见 https://github.com/DIYgod/RSSHub/actions?query=workflow%3Aformat 。

fix 'npm run format' and route '/metred/fuli' (#6703)

---

lib/routes/youtube/channel.js
lib/routes/youtube/playlist.js
lib/routes/youtube/user.js

```routes
/youtube/channel/UCZGYJFUizSax-yElQaFDp5Q
/youtube/user/StarWars
/youtube/playlist/PL148kCvXk8pBViyaR1fRFfG_N54C5ApoY
```
no
youtube-nocookie.com is a better option for embedding youtube videos, as mentioned here: https://blog.josephscott.org/2020/04/01/youtube-nocookie-com/

Use the YouTube no cookie URL for embedding.

---

docs/en/traditional-media.md
docs/traditional-media.md
lib/router.js
lib/routes/yahoo-author/index.js

```routes
/yahoo-author/hannah-keyser
/yahoo-author/frank-schwab
```

add Yahoo! by Author

---

docs/traditional-media.md

```routes
/yahoo-author/hannah-keyser
```

Fix the Yahoo! by Author docs.

---

docs/en/new-media.md
docs/new-media.md
lib/router.js
lib/routes/thrillist/index.js

```routes
/thrillist/new-york
/thrillist/food-and-drink
```

add Thrillist

---

lib/routes/bde4/index.js

Close #6732
```routes
/bde4
```

fix: 哔滴影视优先返回种子链接

---

lib/routes/universities/uestc/sice.js

修复url拼接问题：
```
<link>https://www.sice.uestc.edu.cn/index.htminfo/1139/8819.htm</link>
```
https://rsshub.app/uestc/sice
```routes
/uestc/sice
```

fix: fix url concatenation

---

README.md

Close #
```routes
NOROUTE
```
基于 Flutter 构建的 Android 平台的 RSSHub Radar

docs: add Related Projects RSSAid

---

lib/routes/zhihu/activities.js

https://github.com/DIYgod/RSSHub/issues/6686
```routes
/zhihu/people/activities/mei-you-cun-zai-gan
/zhihu/people/activities/altia
```
原API地址无法正常获取知乎动态。根据知乎网页版的请求的URL，更新获取知乎动态所用API的URL。

fix: update zhihu activity api url

---

docs/new-media.md
lib/router.js
lib/routes/mittrchina/index.js

Close #6744 
```routes
/mittrchina/hot
/mittrchina/index
```

fix MIT科技评论路由 (#6744)

---

docs/new-media.md
lib/router.js
lib/routes/netease/dy2.js

Close #
```routes
/netease/dy2/T1555591616739
/netease/dy2/T1482377048407
```
此方法是网易号的补充，有些网易号搜索页面搜不到的小众网易号（文章页面不含`data-wemediaid`）无法用api获取网页列表，可使用此法抓取。

feat: add 网易号（通用）

---

lib/routes/netease/dy2.js

Close #
```routes
/netease/dy2/T1555591616739
/netease/dy2/T1482377048407
```
现在两种情况的抓取都使用了缓存。另外之前调试为了避免触发反爬故只抓取最新3篇文章，正式使用增加为抓取5篇，应该够用了。

fix: 网易号（通用）

---

docs/new-media.md
lib/router.js
lib/routes/dxy/vaccine.js

Close #6718
```routes
/dxy/vaccine/北京
```

feat: add 新冠疫苗实时动态

---

docs/social-media.md

Close #6213
```routes
NOROUTE
```
我把看到的 status down + 返回 412 的路由都标记成了反爬严格。

chore(docs): add bilibili anticrawler (#6213)

---

assets/radar-rules.js
docs/social-media.md
lib/router.js
lib/routes/zhihu/posts.js

Close #5702
```routes
/zhihu/posts/people/gao-tian-50
/zhihu/posts/people/frederchen
/zhihu/posts/org/jiu-yue-ji-qi-ren
```
知乎的API升级了，原先的会一直爆403，无论公用的还是自建，无论是云服务商部署的还是自己家里部署的，都会报同样的错误。经检查是知乎后台的反爬机制升级，原先的通过请求API的方式获取数据行不通了，现在必须在header中加入特定的密钥才可以，否则都会被视为爬虫，被🈲掉。
网络上有部分文章讲解了破解知乎x-zse相关的算法的实现，但是我实际测试发现，知乎官方已经将该加密算法升级。原先的教程、工具都不再可用。考虑到政策法规 …

fix 知乎用户文章

---

docs/traditional-media.md
lib/router.js
lib/routes/telecompaper/search.js

Close #6730
```routes
/telecompaper/search/Nokia
```

feat: add telecompaper search

---

lib/routes/ssmh/category.js

Close #
```routes
/ssmh/category/6
/ssmh/category/1
```
修复了“紳士漫畫 分类更新”中图片链接获取错误的问题

fix: 紳士漫畫 分类更新 图片链接获取错误

---

lib/routes/douban/people/status.js

Close #6742 
```routes
/douban/people/1679535/status
```

feat: 豆瓣广播全文输出 (#6742)

---

docs/university.md

Close #6766
```routes
NOROUTE
```
Sorry, I just forget to change the author of my added route( 😅update the doc in others's base and forget to change something)
Thanks to repo manager.

fix a error of wtu route author

---

lib/routes/instagram/index.js

Close #6413
```routes
/instagram/user/deogiecomics
/instagram/tag/comics
```
When looking through the exact errors that are raised when Instagram
starts to rate-limit you, I found that they only start limiting when you
are accessing the user-account API as they consider it "unusual."
So instead of checking if you are logged in …

Fix #6413: Changed Instagram code to attempt to load content before load

---

lib/routes/caixin/article.js

Close #
```routes
/caixin/article
```
after adding route name to cache key

caixin: full text of article route

---

docs/government.md
lib/router.js
lib/routes/tingshen/tingshen.js

Close #6717
```routes
/tingshen
```

add 中国庭审公开网

---

docs/picture.md
lib/router.js
lib/routes/jandan/article.js

Close #
```routes
/jandan/article
```
Jandan is not really a pic site. previous authors only did the pic part and put it in the pic category. so I leave it there in the description

feat: add Jandan articles

---

lib/views/atom.art

conforming to RFC 4278 4.1.3.3. Processing Model
Close #6628
```routes
NOROUTE
```

fix atom feed template (#6628)

---

assets/radar-rules.js
docs/en/programming.md
docs/programming.md
lib/router.js
lib/routes/github/topic.js

Close #5803 
```routes
/github/topics/framework/l=php&o=desc&s=stars
/github/topics/cpp/o=desc&s=forks
/github/topics/nodejs/o=asc&s=updated
```

feat: implement github topics router (#5803)

---

docs/new-media.md

Close #
```routes
NOROUTE
```
最近更新正文只抓取到标题，换自建的则能正常抓取全文，故文档增加反爬说明。

chore(docs): add netease anticrawler

---

docs/bbs.md
lib/routes/tieba/user.js

Close #
```routes
/tieba/user/斗鱼游戏君
```
原路由中的 url 存在问题，访问后显示“帖子已被删除”，在这里修改为了正确的 url 。
此外修改了我自己的用户名。

Fix url error of users' posts of tieba

---

docs/government.md
lib/router.js
lib/routes/gov/mohrss/sbjm.js

Close #6695
```routes
/gov/mohrss/sbjm
```

feat: add 中华人民共和国人力资源和社会保障部社保减免

---

lib/routes/zhishifenzi/news.js

Close #6767
```routes
/zhishifenzi/news
```

fix: 知识分子资讯

---

assets/radar-rules.js
docs/en/university.md
docs/university.md
lib/router.js
lib/routes/umass/amherst/eceseminar.js

Close #
```routes
/umass/amherst/eceseminar
```
At the time of this PR, ECE department may have no coming seminars.
Please change line 7 of eceseminar.js  to "  link: 'https://ece.umass.edu/seminars/archive' " if you need additional testing.
I also changed the Chinese name of our school to "麻省大学" in documentation, because most …

feat: Adding UMASS Amherst ECE seminar

---

lib/routes/zhihu/timeline.js

Close #
```routes
/zhihu/timeline
```
路由需要自建并提供 COOKIE，修复了链接和文本内容的 bug
This route requires deployment and your cookie. Bugs in link and content have been fixed.

fix: link and content of zhihu timeline

---

docs/social-media.md
lib/routes/zhihu/collection.js

Close #5708
```routes
https://rsshub.app/zhihu/collection/53597256
```
知乎收藏夹前端页面大改，数据不再存储在HTML中。不过找到了可用的API。

fix zhihu collections

---

docs/en/social-media.md
docs/social-media.md

Close #
```routes
NOROUTE
```
新增 Youtube 官方频道 RSS 文档。

chore(docs): add official youtube channel feeds documentation

---

assets/radar-rules.js
docs/social-media.md

Close #
```routes
/weibo/user
```

feat: improve radar/rssbud support for weibo

---

docs/traditional-media.md
lib/router.js
lib/routes/cctv/jx.js

Close #6823
```routes
/cctv/photo/jx
```

feat: add 央视网图片《镜象》

---

docs/multimedia.md
lib/router.js
lib/routes/shinybbs/index.js

Close #
```routes
/shinybbs
```

feat: add 深影译站首页 & 剧集

---

docs/other.md
lib/router.js
lib/routes/tianyancha/hot.js

Close #6835
```routes
/tianyancha/hot
```

feat: add 天眼查热门搜索

---

docs/en/other.md
lib/router.js
lib/routes/kingarthur/index.js

```routes
/kingarthur/story
/kingarthur/recipes
/kingarthur/tips-and-techniques
```

add King Arthur

---

lib/routes/nyaa/search.js

route's domain changed.
```routes
/nyaa/search/:keyword
```

nyaa domain update

---

assets/radar-rules.js

Close #
```routes
/weibo/user
```
修复了若 `match` 返回了 `null`，下标操作报错导致下面的检测不会被运行的 bug
最新版的 Chrome, Firefox 和 JavascriptCore 均支持 [可选链](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/%E5%8F%AF%E9%80%89%E9%93%BE)

fix: radar/rssbud support for weibo.com

---

docs/multimedia.md
lib/router.js
lib/routes/av01/actor.js
lib/routes/av01/tag.js

Close #
```routes
/av01/actor/七沢みあ
/av01/tag/中出し
```

feat:add av01

---

lib/routes/icable/category.js

Close #
```routes
/icable/all
```

fix: i-CABLE new URL scheme

---

lib/routes/noi/index.js
lib/routes/noi/province-news.js
lib/routes/noi/winners-list.js

Close #
```routes
/noi
/noi/winners-list
/noi/province-news
```
因 NOI 官网改版导致原 routes 失效，修复了相关 routes

fix: NOI 全国青少年信息学奥林匹克竞赛新闻 & 获奖名单 & 各省新闻

---

lib/routes/novel/zhaishuyuan.js

Close #6877 
```routes
/novel/zhaishuyuan/17858
```
该网站做了防抓取，正文内容尾部有几段内容需要触发一个js点击事件才能正常渲染。

fix: zhaishuyuan content incomplete (#6877)

---

lib/routes/t66y/index.js

Close #6861
```routes
/t66y/16
```
看起来t66y为了防爬改了tag名字

Fix: t66y DIYgod/RSSHub#6861

---

docs/en/multimedia.md
docs/multimedia.md
lib/router.js
lib/routes/pornhub/category_url.js
lib/routes/pornhub/model.js
lib/routes/pornhub/pornstar.js
lib/routes/pornhub/users.js

Close #
```routes
/pornhub/users/pornhubmodels
/pornhub/cn/users/pornhubmodels
/pornhub/model/yuzukitty
/pornhub/cn/model/yuzukitty
/pornhub/pornstar/june-liu
/pornhub/cn/pornstar/june-liu
/pornhub/category_url/video%3Fc%3D15%26o%3Dmv%26t%3Dw%26cc%3Djp
/pornhub/cn/category_url/video%3Fc%3D15%26o%3Dmv%26t%3Dw%26cc%3Djp
```
同时更新了 …

feat: improve pornhub routes by introducing a `language` option

---

docs/multimedia.md
lib/router.js
lib/routes/shinybbs/p.js

Close #6849
```routes
/shinybbs/p/1790
```

feat: add 深影译站指定剧集

---

docs/traditional-media.md
lib/routes/cna/index.js

Close #
```routes
/cna
/cna/aipl
/cna/1501
```
CNA maintains news topics besides categories. Available news topics can
be found at https://www.cna.com.tw/list/newstopic.aspx

feat: support newstopic in /cna/ route

---

docs/finance.md
lib/router.js
lib/routes/cls/depth.js
lib/routes/cls/telegraph.js

Close #5875
```routes
/cls/telegraph/watch
/cls/telegraph/announcement
/cls/telegraph/explain
/cls/telegraph/red
/cls/telegraph/jpush
/cls/telegraph/remind
/cls/telegraph/fund
```

feat: add 财联社电报分类

---

docs/finance.md
docs/traditional-media.md
lib/router.js
lib/routes/nbd/index.js

Close #6889
```routes
/nbd
```

feat: add 每经网分类

---

docs/university.md
lib/router.js
lib/routes/universities/sustech/bidding.js
lib/routes/universities/sustech/newshub-zh.js

Close #
```routes
/sustech/newshub-zh
/sustech/bidding
```
添加了南方科技大学新闻网与南方科技大学采购与招标管理部招标信息的RSS支持

feat: add 南方科技大学新闻网 and 南方科技大学采购与招标管理部

---

docs/en/install/README.md
docs/install/README.md
lib/config.js
lib/routes/pixiv/bookmarks.js
lib/routes/pixiv/illustfollow.js
lib/routes/pixiv/ranking.js
lib/routes/pixiv/search.js
lib/routes/pixiv/token.js
lib/routes/pixiv/user.js

Close #6883
```routes
NOROUTE
```

Pixiv support refresh token login

---

lib/routes/novel/zhaishuyuan.js

Close #6877 
```routes
/novel/zhaishuyuan/39399
```
去除该路由的puppeteer依赖，从html中提取加密的正文内容，对正文内容进行复原。

fix: zhaishuyuan js decode

---

assets/radar-rules.js
docs/multimedia.md

fix: add 网易云音乐/腾讯视频 Radar 规则

---

docs/en/install/README.md
docs/install/README.md
lib/routes/pixiv/api/getIllusts.js

Close #6879
```routes
NOROUTE
```

manga support for pixiv user activity

---

lib/routes/furaffinity/journal_comments.js
lib/routes/furaffinity/journals.js
lib/routes/furaffinity/submission_comments.js

This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/diygod/rsshub).

Apply fixes from CodeFactor

---

assets/radar-rules.js
docs/new-media.md

fix: 为少数派添加 radar="1" 以及修复部分radar规则

---

README.md
docs/README.md
docs/en/README.md

feat: 在介绍页面加入RSSAid相关信息

---

app.json

use pixiv refresh token env instead since basic auth is deprecated
Close #
```routes
NOROUTE
```

fix: Update app.json pixiv env config for Heroku

---

assets/radar-rules.js
docs/bbs.md

feat: add tieba Radar rules

---

assets/radar-rules.js
docs/new-media.md

feat: 添加少数派sspai标签订阅的 Radar 规则

---

assets/radar-rules.js
docs/en/social-media.md
docs/social-media.md

fix: update social-media for Fur Affinity

---

lib/routes/dlsite/campaign.js

Close #6761
```routes
/dlsite/campaign/home
```

fix: dlsite campaign params

---

lib/routes/xiaoheihe/news.js

Close #6965
```routes
/xiaoheihe/news
```

fix: xiaoheihe news duplicate entries

---

lib/routes/bilibili/dynamic.js

Close #
```routes
/bilibili/user/dynamic/1522918113
```
Error message: Cannot convert object to primitive value

fix: bilibili UP 主动态

---

.github/workflows/pr-lint.yml
package.json

Not applicable.
```routes
NOROUTE
```
This is a workflow change. Adding ESLint for every PR & Push.

ci: add linter for every PR & commit

---

lib/routes/bjx/huanbao.js

文章主题不再有#content包裹，修改为使用.newsrand选择器
Close #
```routes
https://rsshub.app/bjx/huanbao
```

fix: 更新北极星环保网新闻详情页面结构

---

.github/workflows/docker-test.yml

Close #
```routes
/rsshub/routes
```
fix .github/workflows/docker-test.yml, replace double quotes with single quotes.
修复.github/workflows/docker-test.yml中在workflows expression中允许使用的字符串引号。

fix(workflow): use single quote in expression.

---

Dockerfile

Close #
```routes
/755/user/akimoto-manatsu
/bilibili/bangumi/media/9192
/bilibili/user/dynamic/2267573
/pixiv/user/bookmarks/15288095
/infoq/recommend
/21caijing/channel/readnumber 
/acm/amturingaward
```
node.js v10即将结束维护，升级node.js到v14。
ref: #6928

upgrade node.js to v14

---

docs/en/social-media.md
docs/social-media.md
lib/routes/furaffinity/user.js

Close #
```routes
/furaffinity/user/dreammerchant
```
麻烦维护者再Merge一下，谢谢啦

fix(route): furaffinity user

---

docs/en/university.md
docs/university.md
lib/router.js
lib/routes/universities/mit/csail/news.js

Close #6986
```routes
/mit/csail/news
```

feat(route): add mit csail news

---

assets/radar-rules.js
lib/routes/zhihu/zhuanlan.js

Close #6945
Close #6983
```routes
/zhihu/zhuanlan/c_1034016963944755200
```
1. 新增对知乎专栏新增的以 'c_' 结尾的链接格式的支持
2. 当专栏里面只有视频没有文字时就会报错，返回的api缺少 content 键值。解决办法：将此类专栏文章返回空字符串处理。

fix(route): 支持更多的知乎专栏url格式 和 Bug Fix

---

docs/en/university.md
docs/university.md
lib/router.js
lib/routes/universities/bjtu/gs/index.js

Close #
```routes
/bjtu/gs/all
/bjtu/gs/noti
/bjtu/gs/news
/bjtu/gs/zsxc
/bjtu/gs/py
/bjtu/gs/xw
/bjtu/gs/zs
/bjtu/gs/sszs
/bjtu/gs/bszs
/bjtu/gs/zsjz
/bjtu/gs/zcfg
/bjtu/gs/ygbtzgg
/bjtu/gs/ygbnews
```

feat(route): add 北京交通大学研究生院通知公告

---

assets/radar-rules.js
docs/new-media.md

feat(radar): add Gcores radar rules

---

docs/multimedia.md
lib/router.js
lib/routes/newzmz/view.js

Close #7006
```routes
/newzmz/view/qEzRyY3v
```

feat(route): add NEW字幕组指定剧集

---

lib/routes/zhihu/collection.js

Close #
```routes
/zhihu/collection/206143906
```
如果收藏夹收藏了*想法(pin)*, 會找不到 title，例如：
Route requested: /zhihu/collection/206143906
Error message: Cannot read property 'title' of undefined

fix(route): 知乎 收藏夹

---

.github/workflows/test.yml

Close #
```routes
NOROUTE
```
https://github.com/DIYgod/RSSHub/pull/7012#issuecomment-789208202

chore(workflow): no longer testing under node 10.x

---

docs/new-media.md
lib/router.js
lib/routes/allnow/index.js
lib/routes/allnow/tag.js
lib/routes/allnow/user.js

Close #7061
```routes
/allnow
/allnow/tag/678
/allnow/user/1891141
```

feat(route): add 全现在首页 & 话题 & 用户

---

lib/routes/neea/index.js

Close #
```routes
/neea/ncre
```

fix(route): add pubDate for 中国教育考试网

---

lib/routes/furaffinity/search.js

Close #
```routes
/furaffinity/search/tiger
```

fix(route): furaffinity search parameter

---

lib/middleware/template.js

Close #
```routes
NOROUTE
```
https://github.com/DIYgod/RSSHub/commit/19a219e0762d9cbcb15bdd7cbc6969a270a87f66 @HenryQW 在执行这个改动之前想要先问问为什么有这个操作
#7017 提到设定这样的pubdate可能会导致意外的情况，在rss2.0规范中这个元素也是可选的。所以，在路由无法提供日期的时候可以选择留空
https://validator.w3.org/feed/docs/rss2.html

fix(core): do not add optional pubdate when it is not available

---

docs/en/install/README.md
docs/install/README.md

无
```routes
NOROUTE
```
更新了文档中 SOCKS5 代理的使用方式。为防止域名污染和 DNS 查询泄露，所有 SOCKS5 用户都应首先考虑使用 socks5h（传域名的 SOCKS5）。

fix(docs): add socks5h in install docs

---

lib/routes/bjnews/news.js

Close #6795
```routes
/bjnews/news
```
修复了 #6795 中部分新京报相关的问题，我会在其他 PR 中继续修复 issue 中提到的其他路由。

fix(route): bjnews wrong pubDate

---

docs/en/programming.md
docs/programming.md
lib/router.js
lib/routes/react/react-native-weekly.js

Close #
```routes
/react/react-native-weekly
```

feat(route): add react-native-weekly

---

lib/routes/juejin/books.js
lib/routes/juejin/category.js
lib/routes/juejin/collection.js
lib/routes/juejin/favorites.js
lib/routes/juejin/posts.js
lib/routes/juejin/tag.js
lib/routes/juejin/trending.js

Close #
```routes
/juejin/category/frontend
/juejin/tag/架构
/juejin/trending/ios/monthly
/juejin/books
/juejin/pins/6824710202487472141
/juejin/posts/3051900006845944
/juejin/collections/1697301682482439
/juejin/collection/6845243180586123271
```

fix(route): change juejin api host

---

docs/bbs.md
lib/router.js
lib/routes/guanggoo/index.js

Close #7089
```routes
/guanggoo/index
```

fix(route): 光谷社区重复帖子

---

docs/new-media.md
lib/router.js
lib/routes/wainao/index.js

Close #
```routes
/wainao-reads/all-articles
```
目标网站需要【翻墙】

feat(route): add 歪脑读

---

docs/en/other.md
lib/router.js
lib/routes/hackerone/search.js

Close #
```routes
/hackerone/search/rocket_chat
```

feat(route): search hacktivities

---

lib/routes/ifnews/column.js

Close #6795 
```routes
/ifnews/48
```

fix(route): ifnews wrong pubDate

---

lib/routes/yicai/brief.js

Close #6795 
```routes
/yicai/brief
```

fix(route): yicai wrong pubDate

---

lib/routes/21caijing/channel.js

Close #6795 
```routes
/21caijing/channel/readnumber 
```

fix(route): 21caijing wrong pubDate

---

docs/social-media.md

doc typo
Close #
```routes
/twitter/user/:id/:routeParams?
```

fix: Update social-media.md (doc typo)

---

lib/routes/matataki/site/posts/author.js
lib/routes/matataki/site/posts/favorite.js
lib/routes/matataki/site/posts/scoreranking.js
lib/routes/matataki/site/posts/tag.js
lib/routes/matataki/site/posts/timeranking.js
lib/routes/matataki/site/posts/token.js
lib/routes/matataki/utils/matataki-utils.js

Close #
```routes
/matataki/posts/hot
/matataki/posts/hot/ipfs
/matataki/posts/latest
/matataki/posts/latest/ipfs
/matataki/users/9/posts
/matataki/users/9/posts/ipfs
/matataki/tokens/22/posts/3
/matataki/tokens/22/posts/3/ipfs
/matataki/tags/150/区块链/posts
/matataki/tags/150/区块链/posts/ipfs
/matataki/users/3017/favorites/155/posts
/matataki/users/3017/favorites/155/posts/ipfs
``` …

fix(route): change matataki api host

---

docs/blog.md
docs/en/blog.md
lib/routes/hexo/next.js

Close #7120 
```routes
/hexo/next/diygod.me
```

fix: hexo next theme

---

docs/new-media.md
lib/routes/gamegrape/index.js

Close #7097
```routes
/gamegrape
/gamegrape/13
```

fix: 游戏葡萄获取文章全文

---

docs/new-media.md
lib/router.js
lib/routes/niaogebiji/index.js

feat: add 鸟哥笔记首页

---

docs/en/new-media.md
docs/new-media.md
lib/routes/matters/author.js

Close #
```routes
/matters/author/az
```

refactor: replace author of Matters with GraphQL

---

assets/radar-rules.js
docs/anime.md
docs/bbs.md

Close #
```routes
/bangumi/subject/315069
/bangumi/topic/361913
/bangumi/subject/214265/blogs
/saraba1st/thread/1842868
```
添加了 Bangumi 的 RSSHub Radar 支持。修改了文档中 Bangumi RSS 的一处错误。上述两项修改均已亲自测试。
下面有两个问题
- ~~发现疑似失效路由两个，我不确定是否需要移除~~
- ~~/bangumi/subject/:id/blogs 文档： https://docs.rsshub.app/anime.html#bangumi-tiao-mu-di-ping-lun~~
- …

fix(radar)(route): Bangumi & Radar rules

---

lib/routes/nga/forum.js

Close #6775
```routes
/nga/forum/-7
```
获取帖子内容的route之前已经有cookie了，部分板块帖子列表及摘要也需要cookie获取。
😂，不是我想刷屏，这个自动检查模版实在有点不友好，也没法edit。两次都把route填错了位置，填到了注释那里。

fix(route): add cookie to nga forum route

---

docs/en/install/README.md
docs/install/README.md

在 docker-compose 更新操作的指示中加入拉取新镜像的操作提示，对新手更友好。否则新手直接 docker-compose up -d 可能导致没有更新镜像。
Close #
```routes
NOROUTE
```

fix(docs): 修改用 docker-compose 更新 rsshub 的文案，对新手更友好

---

assets/radar-rules.js

docs: fix typo

---

lib/routes/eztv/imdb.js

Close #7465
```routes
/eztv/torrents/6048596
```

fix(route): eztv using new domain

---

lib/routes/guancha/personalpage.js

Close #
```routes
/guancha/personalpage/344
```
当前观察者网风闻社区的 rss 项时间戳在出现 `刚刚`、`昨天 hh:mm`、`X 小时前` 等非标准时间格式时会报 Invalid Date，本 PR 修复了该问题。
**注：生成的时间戳不会受到时区影响，不适用于 #6795**
出现错误的例子（原文时间为 `3小时前`）：
```xml
<item>
<title>睡前消息【2021-4-30】终于离婚</title>
<description>
1.湖南女子5年4次起诉离婚被驳，今天第五次判离婚据湖南衡阳县人民法院4月30日网站公告，4月30日，衡阳县人民法院开庭审理了原告宁某花诉被告陈某华离婚纠纷一案。原告 …
```

fix(route): 修复观察者网风闻社区出现 Invalid Date 的错误

---

lib/routes/facebook/page.js

Close #
```routes
/facebook/page/cnn
```
將原本連結中的 facebook 追蹤網址取代為原始網址

fix(facebook): replace facebook tracking link with original link

---

docs/bbs.md
lib/routes/liyuan-forums/threads.js

None
```routes
/liyuan-forums/threads
/liyuan-forums/threads/forum/5
/liyuan-forums/threads/topic/9,11
/liyuan-forums/threads/user/2
```
* 添加了指定多个板块/专题/用户的支持
* 修复先前文档中的示例错误

fix(docs, route): 梨园添加功能 & 修复文档示例

---

lib/routes/mittrchina/index.js

无
```routes
/mittrchina/:type
```

fix(route): MIT科技评论文章链接

---

lib/routes/douban/people/status.js

Close #
```routes
/douban/people/53803167/status
```
如果转发的广播被删除/不可用，系统仍然会试图去请求，然后就吃到 HTTP 404 使抓取崩溃。修复了这种情况。

fix(route): douban 404 from resharing a deleted status

---

docs/government.md
lib/router.js
lib/routes/gov/guangdong/eea.js

Close #
```routes
/gov/guangdong/eea/kszs
/gov/guangdong/eea/shks
/gov/guangdong/eea/zkgs
/gov/guangdong/eea/bkzn
```

feat(route): add 广东省教育考试院

---

lib/routes/bde4/index.js

Close #7492
```routes
/bde4
```

fix(route): 哔嘀影视种子文件地址

---

lib/routes/arknights/news.js

无
```routes
/arknights/news
```
修复明日方舟新闻获取。

fix(route): update arknights news fetch

---

lib/routes/smzdm/article.js
lib/routes/smzdm/baoliao.js
lib/routes/smzdm/haowen.js
lib/routes/smzdm/haowen_fenlei.js
lib/routes/smzdm/keyword.js
lib/routes/smzdm/ranking.js

#6795
```routes
/smzdm/keyword/女装
/smzdm/ranking/pinlei/11/3
/smzdm/haowen/1
/smzdm/haowen/fenlei/shenghuodianqi
/smzdm/article/6902738986
/smzdm/baoliao/7367111021
```

fix(route): migrate smzdm to new time parser, re #6795

---

lib/routes/meipai/user.js
lib/routes/weibo/keyword.js
lib/routes/weibo/user.js

#6795 
```routes
/weibo/keyword/DIYgod
/meipai/user/56537299
```

fix(route): migrate weibo routes to new `timezone` (#6795)

---

docs/university.md
lib/router.js
lib/routes/universities/uestc/is.js

Close #
```routes
/uestc/is/
/uestc/is/latest
/uestc/is/xsk+jwc
```

feat(route): 新增 电子科技大学 信软学院 通知公告

---

docs/en/program-update.md
docs/program-update.md
lib/router.js
lib/routes/hugo/releases.js

Close #
```routes
/hugo/releases
```

feat(route): add Hugo 更新日志

---

lib/routes/gamersky/ent.js

修复游民星空部分文章url格式不规范的问题
Close #
```routes
NOROUTE
```

fix(route): 修复游民星空部分文章url格式不规范的问题

---

lib/routes/dcard/section.js

Close #6697
```routes
dcard/popular
```
Dcard 官方 api url 棄用 `_api` 更新成 `service/api/v2` 導致 #6697 發生。

fix(route): update dcard api url DIYgod#6697

---

docs/install/README.md

Close #7159
```routes
NOROUTE
```

fix(docs): 修正邮箱配置 Update README.md

---

docs/joinus/pub-date.md
lib/routes/blogs/diygod/animal-crossing.js
lib/routes/blogs/wangyin.js
lib/routes/etoland/board.js
lib/routes/gov/guangdong/eea.js
lib/routes/lfsyd/tag.js
lib/routes/smzdm/article.js
lib/routes/smzdm/haowen.js
lib/routes/smzdm/haowen_fenlei.js
lib/routes/smzdm/keyword.js
lib/routes/zaker/focusread.js
lib/routes/zaker/source.js
lib/utils/parse-date.js

#6795 
```routes
/blogs/diygod/animal-crossing
/blogs/wangyin
/etoland/star01
/gov/guangdong/eea/kszs
/lfsyd/1
/smzdm/article/6902738986
/smzdm/haowen/1
/smzdm/haowen/fenlei/shenghuodianqi
/smzdm/keyword/女装
/zaker/source/12291
/zaker/channel/13
/zaker/focusread
```
- 如果有, 请说明原因. If yes, …

chore(utils): `parse-date` supports relative time & fix routes

---

lib/routes/eztv/imdb.js

如果eztv没有对应的种子，返回的数据是没有`torrents`这个属性的。
```routes
/eztv/torrents/6048596
/eztv/torrents/10712866
```

fix(route): eztv empty response

---

lib/routes/github/trending.js

Close #
```routes
/github/trending/weekly
```

fix(route): github trending css selector changed

---

lib/routes/reuters/channel.js

Close #
```routes
/reuters/channel/cn/investing
/reuters/channel/cn/life
```
`/reuters/channel/cn/investing` 发现异常，检查发现是`link = homePage;`会导致后续处理栏目`investing`参数跟域名之间缺了分隔符`/`。

fix(route): reuters/channel/life and investing

---

docs/install/README.md
docs/university.md
lib/config.js
lib/routes/universities/bupt/news.js
lib/routes/universities/bupt/portal.js

Close #7167
```routes
/bupt/portal
/bupt/news
```
`/bupt/portal` 和 `/bupt/news` 使用的api现在都需要登录使用，所以添加了cookie配置

fix(route): bupt

---

docs/en/traditional-media.md
docs/traditional-media.md
lib/router.js
lib/routes/nytimes/book.js

Close #
```routes
/nytimes/book/combined-print-and-e-book-fiction
/nytimes/book/combined-print-and-e-book-nonfiction
```

feat(route): add nytimes book bestseller

---

lib/routes/coolapk/utils.js

Close #7599 
```routes
/coolapk/tuwen
```
see  #7599

fix(route): [Coolapk] Wrong html tag wrapping

---

docs/traditional-media.md
lib/router.js
lib/routes/eeo/index.js

Close #7609
```routes
/eeo
/eeo/15
/eeo/yaowen/dashi
```

feat(route): add 经济观察网

---

lib/routes/bookwalkertw/news.js

Close #
```routes
/bookwalkertw/news
```

feat: update bookwalkertw

---

scripts/ansible/rsshub.yaml

Close #
```routes
NOROUTE
```
This PR changes the Ansible script so that it uses npm to install repo dependencies instead of yarn (in according to the new manual deployment guide)

chore(script): use npm to install repo deps in ansible script

---

docker-compose.yml

fix(core): 禁止browserless生成核心转储文件

---

docs/traditional-media.md
lib/router.js
lib/routes/bookwalkertw/news.js
lib/routes/coolapk/utils.js
lib/routes/eeo/index.js

Close #
```routes
https://rss-evan.herokuapp.com/leetcode/todayrecord/cn
https://rss-evan.herokuapp.com/leetcode/todayrecord/en
```

feat: Leetcode Today Record（每日一题）

---

docs/university.md
lib/router.js
lib/routes/hainanu/ssszs.js

Close #
```routes
/hainanu/ssszs
```
添加了海南大学研究生招生的动态，但仅包括第一页的内容。

feat(route): add添加海南大学研究生招生动态

---

docs/other.md
lib/router.js
lib/routes/macau-bolsas/index.js

Close #
```routes
/macau-bolsas
/macau-bolsas/pt
/macau-bolsas/ch
```

feat(route): 澳門特別行政區政府各公共部門獎助貸學金服務平台

---

.github/workflows/docker-release.yml
docs/en/install/README.md
docs/install/README.md

chore(build): add tag for docker build release

---

docs/study.md
lib/router.js
lib/routes/mubu/explore.js

Close #7688
```routes
/mubu/explore/16/读书笔记
```

fix(route): 幕布精选社区

---

lib/routes/dongqiudi/utils.js

Close #7719
```routes
/dongqiudi/daily
```
源站数据结构小修改

fix: 懂球帝早报报错

---

lib/middleware/onerror.js
lib/routes/pixiv/constants.js
lib/routes/pixiv/token.js

Close #
```routes
/pixiv/user/bookmarks/:id
/pixiv/user/illustfollows
/pixiv/user/:id
/pixiv/ranking/:mode/:date?
/pixiv/search/:keyword/:order?/:r18?
```
一些路由的异常没有 message
pixiv 验证代码有问题，虽然貌似能跑（奇妙）

fix(route): pixiv login

---

docs/social-media.md
lib/router.js
lib/routes/bilibili/manga_followings.js

Close #7757
```routes
/bilibili/manga/followings/26009
```
每本漫画为RSS中的一个`item`，`title`为“漫画名称 - 最近更新的章节名称”，`pubDate`为最近的章节更新时间

feat(route): Bilibili用户追漫列表

---

docs/multimedia.md
lib/router.js
lib/routes/mp4er/index.js

Close #7743
```routes
bde4/0/all/all/2021/1
```

fix(route): 哔嘀影视种子链接

---

lib/routes/novel/shuquge.js

Close #
```routes
/novel/shuquge/3478
```
该网站最近切换了域名，此后一直拉取失败。
奇怪的是原网站做了301 redirect，但是`got`发起网络请求时在处理`followRedirect`时遇到了异常。

fix(route): 书趣阁域名切换后访问失败

---

docs/new-media.md
lib/router.js
lib/routes/sznews/press.js
lib/routes/sznews/ranking.js

Close #
```routes
/sznews/press
```

feat(add): 深圳新闻网深圳市政府新闻发布厅

---

lib/routes/universities/dlu/jiaowu/news.js

Close #
```routes
/dlu/jiaowu/news
```

feat(route): dlu add fulltext

---

lib/routes/bilibili/coin.js
lib/routes/bilibili/fav.js
lib/routes/bilibili/userFav.js

Close #
```routes
/bilibili/user/coin/502884
/bilibili/fav/502884/56543584
```

feat(route): bilibili route add author and date

---

lib/routes/soul/hot.js
lib/routes/soul/index.js

Close #7716 
```routes
/soul/posts/hot
```

fix(route): 更新 soul 地址

---

lib/routes/whb/zhuzhan.js

Close #
```routes
/whb/rd
```
This commit fixed the timezone issue. The time published on the web pages is GMT+8 despite visitors' locations, which is not handled previously.

fix(route): whb published timezone

---

docs/university.md
lib/router.js
lib/routes/universities/ustc/job.js

Close #
```routes
/ustc/job
```

feat(route): add 中国科学技术大学就业信息网

---

docs/.format/sortByHeading.js
docs/.vuepress/config.js
docs/anime.md
docs/game.md
docs/government.md
docs/new-media.md
docs/other.md
docs/traditional-media.md
docs/university.md
package-lock.json
package.json

Close https://github.com/DIYgod/RSSHub/issues/6785#issuecomment-800222011
```routes
NOROUTE
```
为了干掉node-gyp, 解决 https://github.com/DIYgod/RSSHub/issues/6785#issuecomment-800222011 …

chore(core)(docs): drop pinyin

---

docs/university.md
lib/router.js
lib/routes/universities/xjtu/job.js

Close #
```routes
/xjtu/job
/xjtu/job/zxtg
/xjtu/job/xdsgwy
/xjtu/job/gjzzsx
/xjtu/job/xwzx
/xjtu/job/hdyjz
```
添加了西安交通大学就业创业中心官方网站发布的实习、招聘等公告

feat(route): add 西安交大就业服务中心路由

---

assets/radar-rules.js
docs/anime.md
lib/router.js
lib/routes/mhgui/comic.js
lib/routes/twmanhuagui/comic.js

Close #
```routes
/mhgui/comic/5201
/twmanhuagui/comic/23411
```

feat(route): add 看漫画镜像站

---

docs/university.md
lib/router.js
lib/routes/universities/xjtu/job.js
package-lock.json
package.json

Close #
```routes
/leetcode/todayrecord/cn/cn
/leetcode/todayrecord/cn/en
/leetcode/todayrecord/us/cn
/leetcode/todayrecord/us/en
```

feat: 增加路由：leetcode 每日一题

---

docs/university.md

Close #
```routes
NOROUTE
```
更新哈尔滨工业大学（深圳）-新闻中心路由信息中的作者github账号

chore(docs): 更新作者信息 哈尔滨工业大学（深圳）-新闻中心

---

lib/routes/erbingapp/news.js

修复二柄APP路由错误
Close #
```routes
/erbingapp/news
```

fix(route): 二柄APP

---

lib/routes/gamer/gnn_index.js

Close #7713
```routes
/gamer/gnn
/gamer/gnn/1
/gamer/gnn/3
/gamer/gnn/4
/gamer/gnn/5
/gamer/gnn/9
/gamer/gnn/11
/gamer/gnn/13
/gamer/gnn/ns
/gamer/gnn/ps5
/gamer/gnn/ps4
/gamer/gnn/xbone
/gamer/gnn/xbsx
/gamer/gnn/pc
/gamer/gnn/olg
/gamer/gnn/ios
/gamer/gnn/android
/gamer/gnn/web
/gamer/gnn/comic
/gamer/gnn/anime
```
- 如果有提供日期，但是没有提供解析，请说明原因 If there is a date but this script does not parse, …

fix(route): /gamer/gnn original page elements changed

---

docs/traditional-media.md
lib/routes/yomiuri/news.js

Close #
```routes
/yomiuri/news
/yomiuri/national
/yomiuri/politics
/yomiuri/economy
/yomiuri/sports
/yomiuri/world
/yomiuri/science
/yomiuri/election
/yomiuri/culture
/yomiuri/igoshougi
/yomiuri/life
/yomiuri/local
/yomiuri/editorial
```
- 如果有, …

fix(route): /yomiuri/news fetching error due to frame changed

---

docs/university.md
lib/router.js
lib/routes/universities/xjtu/ee.js

Close #
```routes
/xjtu/ee
/xjtu/ee/1124
/xjtu/ee/1115
/xjtu/ee/1007
/xjtu/ee/1010
```
添加西安交大电气学院官网路由

feat(route): add 西安交通大学电气学院官网路由

---

docs/en/programming.md
docs/programming.md
lib/router.js
lib/routes/gitlab/explore.js
lib/routes/gitlab/release.js
lib/routes/gitlab/tag.js

N/A
```routes
/gitlab/explore/all/gitlab.com
/gitlab/release/pleroma/pleroma/git.pleroma.social
/gitlab/tag/rluna-open-source%2Ffile-management%2Fowncloud/core
```
- 增加了订阅 Gitlab release 的特性
- 为现有的 …

feat(route): Add gitlab releases & tags

---

lib/routes/tieba/user.js

Close #7677
```routes
/tieba/user/琴軒居士
```

fix(route): 贴吧用户帖子

---

lib/routes/ff14/ff14_zh.js

Close #
```routes
/ff14/ff14_zh/news
/ff14/ff14_zh/announce
/ff14/ff14_zh/events
/ff14/ff14_zh/advertise
/ff14/ff14_zh/all
```
* description 格式调整
* 添加 pubDate

fix(route): 最终幻想14 国服新闻

---

assets/radar-rules.js

feat(radar): add radar rules for netease cloud music (mobile)

---

docs/university.md
lib/routes/universities/thu/career.js

Close #7767
```routes
/thu/career
```

fix(route): thu-career

---

docs/new-media.md
lib/router.js
lib/routes/zzz/index.js

Close #7881
```routes
/zzz
```

fix(route): 紫竹张先生

---

docs/new-media.md

Close #
```routes
/hkepc/
/hkepc/price
/hkepc/review
/hkepc/coverStory
/hkepc/news
/hkepc/press
/hkepc/member
/hkepc/digital
/hkepc/entertainment
/hkepc/latest
/hkepc/ocLab
```
Fix doc as required …

fix(docs): HKEPC doc

---

lib/routes/tencent/factcheck/index.js

fix(route): 腾讯较真查证平台

---

docs/social-media.md
lib/router.js
lib/routes/bilibili/userChannel.js

未发现
```routes
/bilibili/user/channel/168598/210432
/bilibili/user/channel/168598/1031
/bilibili/user/channel/168598/1031/disableEmbed
```
Bilibili 新出 ctype=1 的频道，似乎是直播回放专用的，如果没带 ctype=1 参数，请求 json …

fix(route): 修复 Bilibili 频道链接，并支持 ctype=1

---

docs/social-media.md
lib/router.js
lib/routes/soul/hot.js

Close #7954
```routes
/soul/posts/hot
```
+ soul 的请求链接里强制新加了一个 postIdEcpt 的新参数，现已补上
+ 删除了请求链接里无效的 pageIndex 参数
+ 路由加了可选参数 `pid`

fix(route): 修复 soul 请求链接

---

lib/utils/got.js
test/utils/got.js

N/A
```routes
NOROUTE
```
Before this fix, timeout messages are not quite useful
> error: Request undefined fail, retry attempt #1: TimeoutError: Timeout awaiting 'request' for 5000ms

fix(core): make sure timeout error messages include URLs

---

docs/university.md
lib/router.js
lib/routes/universities/nwafu/54youth.js
lib/routes/universities/nwafu/cie.js
lib/routes/universities/nwafu/gs.js
lib/routes/universities/nwafu/jcc.js
lib/routes/universities/nwafu/jiaowu.js
lib/routes/universities/nwafu/lib.js
lib/routes/universities/nwafu/news.js
lib/routes/universities/nwafu/nic.js
lib/routes/universities/nwafu/yjshy.js

Close #
```routes
/nwafu/news
/nwafu/jiaowu
/nwafu/gs
/nwafu/lib
/nwafu/nic
/nwafu/54youth
/nwafu/jcc
/nwafu/yjshy
/nwafu/cie
```

feat(route): add 西北农林科技大学

---

lib/routes/japanpost/track.js
lib/routes/japanpost/utils.js

Close #
```routes
/japanpost/track/217556396934/ja
```
Improve timezone parse for Japanpost local package.

feat(route): japanpost improve timezone parse

---

docs/university.md
lib/router.js
lib/routes/universities/cqu/jwc/announcement.js

无 
```routes
/cqu/jwc
/cqu/jwc/index/tzgg
```

fix(route): 重庆大学本科教学信息网 (原重庆大学教务网)

---

lib/router.js
lib/routes/juejin/column.js
lib/routes/juejin/utils.js

Close #
```routes
/juejin/column/6960559453037199391
```

feat(route): add 掘金专栏

---

docs/install/README.md

Close #
```routes
NOROUTE
```
heroku补充描述
heroku additional description
vercel 补充描述
vercel additional description

docs(install): README.md

---

lib/routes/bilibili/dynamic.js
lib/routes/bilibili/followings_dynamic.js

Close #7960 #7959
```routes
/bilibili/user/dynamic/2267573
/bilibili/followings/dynamic/87052411
```
路由 `/bilibili/followings/dynamic/[uid]` 需 cookie 访问。

fix(route): 修复 bilibili 动态无法获取问题

---

lib/routes/zcool/discover.js

Close #8034
```routes
/zcool/discover/home
```

fix(route): 站酷发现有视频条目

---

docs/blog.md
lib/router.js
lib/routes/fontstory/tw.js
lib/routes/hket/index.js

Close #
```routes
/leetcode/todayrecord/us/en
/leetcode/todayrecord/us/cn
/leetcode/todayrecord/cn/en
/leetcode/todayrecord/cn/cn
```

feat: add routes for leetcode today record

---

docs/university.md
lib/routes/universities/shmtu/jwc.js

Close #
```routes
/shmtu/jwc/jwgg
```
页面改版

fix(route): shmtu jwc routes

---

lib/middleware/onerror.js

Fix #8009
```routes
NOROUTE
```
RT.

perf: lazyload sentry sdk for faster cold start speed

---

docs/university.md
lib/router.js
lib/routes/universities/xmu/aero.js

Close #
```routes
/xmu/aero/tzgg
/xmu/aero/bksjw
/xmu/aero/yjsjw
```

feat(route): add 厦门大学航院

---

docs/university.md

fix(docs): fix the missing # in the university.md

---

docs/en/multimedia.md
docs/multimedia.md
lib/router.js
lib/routes/s-hentai/index.js

Close #7854
```routes
/s-hentai
```

feat(route): add s-hentai

---

lib/routes/greasyfork/scripts.js

Close #8143 
```routes
/greasyfork/zh-CN/bilibili.com
/greasyfork/all
```

fix(route): greasyfork link

---

lib/routes/juejin/utils.js

Close #
```routes
/juejin/category/frontend
```

fix(route): 修复掘金文章详情获取

---

docs/new-media.md

fix(docs): add 全现在首页

---

docs/install/README.md

#7225
```routes
NOROUTE
```
`SESSDATA` 字段仅适用于”用户关注视频动态路由“；若获取”用户关注动态路由“，需复制整段 Cookie 字段。故修改文档使其更具有普适性。

fix(docs): update configuration document for bilibili

---

docs/university.md
lib/middleware/onerror.js
lib/router.js
lib/routes/universities/shmtu/jwc.js
lib/routes/universities/xmu/aero.js

Close #
```routes
/asoulcnki
```

feat(route): 枝江作文展

---

lib/routes/dapenti/utils.js

Close #7343 
```routes
/dapenti/tugua
```

fix(route): dapenti/tugua pubDate and author

---

lib/routes/javdb/utils.js

fix(route): typo in JavDB

---

lib/routes/fontstory/tw.js

Close #
```routes
/fontstory
```

fix(route): `pubDate` for `fontstory`

---

lib/routes/allnow/column.js
lib/routes/allnow/index.js
lib/routes/allnow/tag.js
lib/routes/allnow/user.js
lib/routes/allnow/utils.js

Close #8136
```routes
/allnow
```

fix(route): 全现在首页

---

lib/routes/netease/dy2.js

```routes
/netease/dy2/T1555591616739?limit=1
```

fix(route): netease

---

docs/new-media.md
lib/v2/aamacau/index.js
lib/v2/aamacau/maintainer.js
lib/v2/aamacau/radar.js
lib/v2/aamacau/router.js

Close #8178
```routes
/aamacau
```

feat(route): add 論盡媒體 AllAboutMacau Media

---

lib/routes/universities/njfu/jwc.js

无
```routes
/njfu/jwc/tzgg
/njfu/jwc/xjfw
/njfu/jwc/sjfw
/njfu/jwc/xzzq
```
更新源URL，修复文档一处笔误。

fix(route): update url & fix a typo

---

docs/en/traditional-media.md
docs/traditional-media.md
lib/router.js
lib/routes/abc/documentId.js
lib/routes/abc/id.js
lib/routes/abc/index.js

Close #8104
```routes
/abc
/abc/chinese
```

fix(route): ABC News

---

lib/routes/universities/thu/index.js

```routes
/thu/zhongyao
```
修复了文章 URL 错误的问题。

fix(route): fix URL for THU

---

docs/university.md

```routes
/thu/zhongyao
```
更新文档说明路由情况。

fix(docs): add info for THU

---

docs/new-media.md
lib/v2/8world/index.js
lib/v2/8world/maintainer.js
lib/v2/8world/radar.js
lib/v2/8world/router.js

Close #8252
```routes
/8world
```

feat(route): add 8视界

---

docs/new-media.md
lib/v2/ruancan/index.js
lib/v2/ruancan/maintainer.js
lib/v2/ruancan/radar.js
lib/v2/ruancan/router.js

Close #8230
```routes
/ruancan
```

feat(route): add 软餐

---

radar-rules.js

Reverts DIYgod/RSSHub#8278 wrong location

Revert "Update radar-rules.js"

---

lib/routes/zimuku/index.js

Close #
```routes
/zimuku/tv
/zimuku/mv
```
字幕库启用了新域名 `www.zimuku.org`

fix(route)(zimuku) 字幕库新域名

---

docs/.format/format.js

Close #8346
```routes
NOROUTE
```

fix(core)(docs): Can't commit some changes in docs folder

---

lib/routes/firefox/addons.js

`versionInfo.platformFiles` key no longer exists. Date is available in `versionInfo.file` key.
```routes
/firefox/addons/ublock-origin
/firefox/addons/tetrio-plus
```
Existing implementation fails with `Error message: Cannot read property 'all' of undefined`

fix(route)(firefox): route for firefox addons

---

docs/live.md
lib/v2/qq/live.js
lib/v2/qq/maintainer.js
lib/v2/qq/radar.js
lib/v2/qq/router.js

Close #8197
```routes
/qq/live/10012045
```

feat(route): add 企鹅直播直播间开播

---

docs/new-media.md
lib/v2/focustaiwan/index.js
lib/v2/focustaiwan/maintainer.js
lib/v2/focustaiwan/radar.js
lib/v2/focustaiwan/router.js
lib/v2/focustaiwan/templates/article.art

Close #8317
```routes
/focustaiwan
```

feat(route): add Focus Taiwan

---

docs/game.md
lib/routes/curseforge/files.js

Close #
```routes
/curseforge/files/242223
```
原有 route 无法使用，访问403。我所使用的 api 是从 https://github.com/Mondanzo/mc-curseforge-api 这个项目中找到的。

fix(route): minecraft forge mod 使用新 api

---

docs/en/other.md
lib/v2/fisher-spb/maintainer.js
lib/v2/fisher-spb/news.js
lib/v2/fisher-spb/radar.js
lib/v2/fisher-spb/router.js
lib/v2/fisher-spb/templates/image.art
lib/v2/fisher-spb/templates/video.art

Close #
```routes
/fisher-spb/news
```

feat(route): add fisher spb news

---

docs/en/new-media.md
docs/new-media.md
lib/router.js
lib/routes/researchgate/publications.js

Close #7526
```routes
/researchgate/publications/Somsak-Panha
```

feat(route): add Research Gate Publications

---

docs/new-media.md
lib/router.js
lib/routes/odaily/activity.js

Close #
```routes
/odaily/activity
```

feat(route): add Odaily星球日报活动

---

docs/government.md
lib/router.js
lib/routes/dykszx/news.js

Close #
```routes
/dykszx/news
```
德阳考试中心内容

feat(route): add 德阳考试中心

---

lib/routes/dsndsht23/index.js

Close #7726 
```routes
/dsndsht23
```

fix: undefined error when no magnet & torrent

---

lib/routes/apnews/topics.js

Fix AP News article's title

---

docs/university.md
lib/router.js
lib/routes/universities/ynnu/edu/base64.js
lib/routes/universities/ynnu/edu/news.js

Close #
```routes
/ynnu/edu/news
```

feat(route): add yunnan normal university

---

lib/routes/gov/beijing/eea.js

无
```routes
/gov/beijing/bjeea/bjeeagg
/gov/beijing/bjeea/zkzc
/gov/beijing/bjeea/zkkd
```
适配新的页面

fix(route): 修正北京教育考试院内容提取错误

---

docs/traditional-media.md
lib/v2/people/liuyan.js
lib/v2/people/maintainer.js
lib/v2/people/radar.js
lib/v2/people/router.js

Close #8188
```routes
/people/liuyan/539
```

feat(route): add 人民网领导留言板

---

docs/new-media.md
lib/v2/ithome/maintainer.js
lib/v2/ithome/radar.js
lib/v2/ithome/router.js
lib/v2/ithome/zt.js

Close #8310
```routes
/ithome/zt/xijiayi
```

feat(route): add IT之家专题

---

docs/new-media.md
lib/v2/hotchina/index.js
lib/v2/hotchina/maintainer.js
lib/v2/hotchina/radar.js
lib/v2/hotchina/router.js

Close #8352
```routes
/hotchina
```

feat(route): add 辛華社

---

docs/en/reading.md
docs/reading.md
lib/v2/literotica/category.js
lib/v2/literotica/maintainer.js
lib/v2/literotica/radar.js
lib/v2/literotica/router.js

Close #
```routes
/literotica/category/anal-sex-stories
```

feat(route): add Literotica Category

---

.github/PULL_REQUEST_TEMPLATE.md

Close #
```routes
NOROUTE
```
Partially revoke 9bc99cefb4d9491ed5268d57ab23207ff7876cb1
Not every contributor needs to read through #8002.
Avoid #7671 (and #8376 #8377).

misc: add NOROUTE instruction back to template

---

lib/routes/jandan/pic.js

Close #
```routes
/jandan/pic
/jandan/top
/jandan/top-4h
/jandan/zoo
```
After this change, you don't have to go to the origin URL to see the gif anymore
before change
```
<item>
<title>
<![CDATA[ 暧昧/5053916 ]]>
</title>
<description>
<![CDATA[ <a href="https://wx3.sinaimg.cn/large/006acpdhgy1gvg4wioifdg60a00bg1ld02.gif" target="_blank" class="view_img_link" referrerpolicy="no-referrer">[查看原图]</a><br><img src="https://wx3.sinaimg.cn/thumb180/006acpdhgy1gvg4wioifdg60a00bg1ld02.gif" org_src="//wx3.sinaimg.cn/mw1024/006acpdhgy1gvg4wioifdg60a00bg1ld02.gif" referrerpolicy="no-referrer"> ]]>
</description>
<pubDate>Mon, 18 Oct 2021 03:54:35 GMT</pubDate>
<guid isPermaLink="false">5053916</guid>
<link>
https://jandan.net/t/5053916</link>
<author>
<![CDATA[ 暧昧 ]]>
</author>
</item>
```
after …

feat(route): jandan use the origin gif instead the thumbs

---

lib/v2/furstar/utils.js

Close #
```routes
/furstar/characters
```
Fix pic link returned by utils.

fix(route): fix furstar pic href

---

docs/en/journal.md
docs/journal.md
lib/v2/sciencedirect/journal.js
lib/v2/sciencedirect/maintainer.js
lib/v2/sciencedirect/radar.js
lib/v2/sciencedirect/router.js

Close #8392
```routes
/sciencedirect/journal/research-policy
```

feat(route): add ScienceDirect Journal

---

lib/router.js
lib/v2/netease/maintainer.js
lib/v2/netease/radar.js
lib/v2/netease/rank.js
lib/v2/netease/router.js

Close #7945
```routes
/netease/news/rank/whole/click/day
```

fix(route): 网易新闻排行榜

---

docs/university.md
lib/v2/bnu/bs.js
lib/v2/bnu/maintainer.js
lib/v2/bnu/radar.js
lib/v2/bnu/router.js

Close #8367
```routes
/bnu/bs/bshzs
```

feat(route): add 北京师范大学经济与工商管理学院

---

docs/university.md
lib/v2/uibe/hr.js
lib/v2/uibe/maintainer.js
lib/v2/uibe/radar.js
lib/v2/uibe/router.js

Close #8370
```routes
/uibe/hr/tzgg
/uibe/hr/jszp/zpxx
```

feat(route): add 对外经济贸易大学人力资源处

---

docs/new-media.md
lib/v2/startuplatte/index.js
lib/v2/startuplatte/maintainer.js
lib/v2/startuplatte/radar.js
lib/v2/startuplatte/router.js

Close #8375
```routes
/startuplatte
```

feat(route): add 創新拿鐵

---

docs/journal.md
lib/v2/mvm/index.js
lib/v2/mvm/maintainer.js
lib/v2/mvm/radar.js
lib/v2/mvm/router.js

Close #8384
```routes
/mvm
```

feat(route): add 管理世界

---

docs/new-media.md
lib/v2/getdr/index.js
lib/v2/getdr/maintainer.js
lib/v2/getdr/radar.js
lib/v2/getdr/router.js

Close #8388
```routes
/getdr
```

feat(route): add 趨勢科技防詐達人最新詐騙情報

---

docs/game.md
lib/router.js
lib/routes/arknights/japan.js

Close #
```routes
/arknights/japan
```

fix(route): アークナイツ(明日方舟日服)

---

docs/university.md
lib/v2/bit/maintainer.js
lib/v2/bit/radar.js
lib/v2/bit/router.js
lib/v2/bit/rszhaopin.js

Close #8422
```routes
/bit/rszhaopin
```

feat(route): add 北京理工大学人才招聘

---

docs/university.md
lib/v2/bupt/maintainer.js
lib/v2/bupt/radar.js
lib/v2/bupt/rczp.js
lib/v2/bupt/router.js

Close #8435
```routes
/bupt/rczp
```

feat(route): add 北京邮电大学人才招聘

---

docs/university.md
lib/v2/ruc/hr.js
lib/v2/ruc/maintainer.js
lib/v2/ruc/radar.js
lib/v2/ruc/router.js

Close #8423
```routes
/ruc/hr
```

feat(route): add 中国人民大学人事处

---

docs/program-update.md

This route does not exist and no user called AngUOI has ever contributed to this repository.
Close #
```routes
NOROUTE
```

Delete 厚墨 from the docs

---

docs/programming.md
lib/router.js
lib/routes/github/trending.js

Close #
```routes
/github/trending/daily/javascript/zh
```

feat(route): add spoken_language for GitHub Trending

---

docs/university.md
lib/v2/pku/hr.js
lib/v2/pku/maintainer.js
lib/v2/pku/radar.js
lib/v2/pku/router.js

Close #8425
```routes
/pku/hr/rczp-js-jxkyry
```

feat(route): add 北京大学人事处

---

docs/en/traditional-media.md
docs/traditional-media.md
lib/v2/pts/dailynews.js
lib/v2/pts/maintainer.js
lib/v2/pts/radar.js
lib/v2/pts/router.js

Close #
```routes
/pts/dailynews
```

feat(route): add 公視新聞網即時新聞

---

docs/reading.md
lib/router.js
lib/routes/wenku8/volume.js

Close #
```routes
/wenku8/volume/1163
```
[轻小说文库](https://www.wenku8.net/index.php)获取最新卷全文rss，小说 id可在对应小说页 URL 中找到

add router /wenku8/volume

---

docs/traditional-media.md
lib/v2/eastday/find.js
lib/v2/eastday/maintainer.js
lib/v2/eastday/portrait.js
lib/v2/eastday/radar.js
lib/v2/eastday/router.js

Close #
```routes
/eastday/find
/eastday/portrait
```

feat(route): 东方网热点搜索 & 原创

---

docs/new-media.md
lib/v2/mygopen/index.js
lib/v2/mygopen/maintainer.js
lib/v2/mygopen/radar.js
lib/v2/mygopen/router.js

Close #
```routes
/mygopen
```

feat(route): add MyGoPen

---

docs/en/programming.md
docs/programming.md
lib/v2/distill/index.js
lib/v2/distill/maintainer.js
lib/v2/distill/radar.js
lib/v2/distill/router.js

Close #8490
```routes
/distill
```

feat(route): add Distill

---

docs/new-media.md
lib/v2/watchout/index.js
lib/v2/watchout/maintainer.js
lib/v2/watchout/radar.js
lib/v2/watchout/router.js

Close #8495
```routes
/watchout
```

feat(route): add 沃草

---

docs/new-media.md
lib/v2/qm120/maintainer.js
lib/v2/qm120/news.js
lib/v2/qm120/radar.js
lib/v2/qm120/router.js

Close #7551
```routes
/qm120/news
```

feat(route): add 全民健康网

---

lib/routes/dongqiudi/utils.js

```routes
dongqiudi/team_news/50000516
```

fix(route): 修正懂球帝球队&球员新闻获取地址

---

docs/multimedia.md
lib/v2/rfi/maintainer.js
lib/v2/rfi/news.js
lib/v2/rfi/radar.js
lib/v2/rfi/router.js

Close #
```routes
/rfi/news
```

feat(route): add 法国国际广播电台滚动新闻

---

docs/finance.md

None
```routes
/xueqiu/snb/ZH1288184
```
fix a typo in doc

fix(doc): correct path in doc

---

lib/routes/yahoo-news/index.js

None
```routes
/yahoo-news/hk
```
Crawl article image in yahoo news

fix(route): yahoo news - crawl image in article

---

lib/routes/universities/njtech/jwc.js

Close #
```routes
https://rsshub.app/njtech/jwc
```

fix(route): fix njtech jwc host

---

docs/game.md
lib/v2/gameapps/index.js
lib/v2/gameapps/maintainer.js
lib/v2/gameapps/radar.js
lib/v2/gameapps/router.js
lib/v2/gameapps/templates/description.art

Close #
```routes
/gameapps
```

feat(route): add gameapps

---

docs/anime.md
lib/v2/mox/index.js
lib/v2/mox/maintainer.js
lib/v2/mox/radar.js
lib/v2/mox/router.js

Close #8538
```routes
/mox
```

feat(route): add Mox.moe

---

docs/university.md
lib/v2/sicau/maintainer.js
lib/v2/sicau/radar.js
lib/v2/sicau/router.js
lib/v2/sicau/zsjy.js

Close #
```routes
/sicau/zsjy/bkszs
```

feat(route): add 四川农业大学招生就业

---

lib/router.js
lib/v2/news/maintainer.js
lib/v2/news/radar.js
lib/v2/news/router.js
lib/v2/news/whxw.js

Close #8511
```routes
/news/whxw
```

fix(route): 新华社新闻

---

docs/multimedia.md
lib/router.js
lib/routes/ncm/userplayrecords.js

Close #
```routes
/ncm/user/playrecords/45441555/0
```

feat(route): 网易云 - 用户听歌排行

---

assets/radar-rules.js
docs/multimedia.md
lib/radar-rules.js
lib/router.js
lib/routes/ximalaya/album.js

Close #8516
```routes
/ximalaya/shangye/299146
```

fix(route): 喜马拉雅(#8516)

---

docs/en/shopping.md
docs/shopping.md
lib/v2/shopback/maintainer.js
lib/v2/shopback/radar.js
lib/v2/shopback/router.js
lib/v2/shopback/store.js

Close #8564
```routes
/shopback/shopee-mart
```

feat(route): add ShopBack

---

docs/en/government.md
docs/government.md
lib/v2/hongkong/chp.js
lib/v2/hongkong/maintainer.js
lib/v2/hongkong/radar.js
lib/v2/hongkong/router.js

Close #
```routes
/hongkong/chp
```

feat(route): add 香港衛生防護中心

---

docs/government.md
lib/v2/mohw/clarification.js
lib/v2/mohw/maintainer.js
lib/v2/mohw/radar.js
lib/v2/mohw/router.js

Close #8203
```routes
/mohw/clarification
```

feat(route): add 台灣衛生福利部即時新聞澄清

---

docs/multimedia.md
lib/routes/instagram/utils.js
lib/routes/maoyan/hotComplete.js
package.json

Close #
```routes
/maoyan/hotComplete
```
目前已有的获取猫眼电影列表只会加载第一页，这个版本可以获取所有，并可以根据发布时间或评分排序，并可自定义需要的条数

add 猫眼电影正在热播完整列表

---

docs/anime.md
lib/v2/18comic/album.js
lib/v2/18comic/blogs.js
lib/v2/18comic/index.js
lib/v2/18comic/maintainer.js
lib/v2/18comic/radar.js
lib/v2/18comic/router.js
lib/v2/18comic/search.js
lib/v2/18comic/utils.js

Close #8581
```routes
/18comic
/18comic/search/photos/all/NTR
/18comic/album/292282
/18comic/blogs
```

feat(route): add 18comic

---

docs/en/new-media.md
docs/new-media.md
lib/v2/swissinfo/index.js
lib/v2/swissinfo/maintainer.js
lib/v2/swissinfo/radar.js
lib/v2/swissinfo/router.js

Close #8465
```routes
/swissinfo/eng/latest-news
```

feat(route): add swissinfo

---

docs/install/README.md
lib/config.js
lib/routes/infzm/news.js

Support fulltext acquirement in infzm

---

docs/en/journal.md
docs/journal.md

Close #
```routes
NOROUTE
```
修改 @TonyRL 提出的修改内容

fix: (docs) modify space and chinese/english comma

---

assets/radar-rules.js
lib/router.js
lib/v2/csc/maintainer.js
lib/v2/csc/notice.js
lib/v2/csc/radar.js
lib/v2/csc/router.js

Close #
```routes
/csc/notice/lxtz
/csc/notice/xmzl
/csc/notice/wtjd
/csc/notice/lqgg
/csc/notice/xwzx
/csc/notice/xwgg
```
因为是迁移旧路由，所以说明文档部分未变动，故在上述check框中勾选上了说明文档选项。

feat(route): change csc to v2

---

docs/en/journal.md
docs/journal.md
lib/v2/elsevier/maintainer.js

Close #
```routes
NOROUTE
```
更正路由作者的ID

fix: author name

---

Dockerfile

Close #8715 
```routes
NOROUTE
```
顺便改了一下 Dockerfile 的命令顺序，在仅更改路由而不改动 package.json 的情况下，利用缓存 Docker 层的优势[^1]
[^1]:[Building Efficient Dockerfiles - Node.js](http://bitjudo.com/blog/2014/03/13/building-efficient-dockerfiles-node-dot-js/)

fix(build):change npm ci to yarn

---

lib/routes/gelonghui/user.js

修改格隆汇用户文章
Close #
```routes
/gelonghui/user/14573
```

fix(route):格隆汇用户文章列表 

---

docs/en/programming.md
docs/programming.md
lib/v2/nodejs/blog.js
lib/v2/nodejs/maintainer.js
lib/v2/nodejs/radar.js
lib/v2/nodejs/router.js

Close #8901
```routes
/nodejs/blog
```

feat(route): add Node.js News

---

lib/router.js
lib/v2/bendibao/maintainer.js
lib/v2/bendibao/news.js
lib/v2/bendibao/radar.js
lib/v2/bendibao/router.js

Close #8888
```routes
/bendibao/news/cd
```

fix(route): 本地宝焦点资讯

---

docs/multimedia.md
lib/v2/ajmide/index.js
lib/v2/ajmide/maintainer.js
lib/v2/ajmide/radar.js
lib/v2/ajmide/router.js

Close #8882
```routes
/ajmide/10603594
```

Add(route): add ajmide

---

docs/journal.md
lib/v2/cnki/debut.js
lib/v2/cnki/journals.js
lib/v2/cnki/maintainer.js
lib/v2/cnki/radar.js
lib/v2/cnki/router.js
lib/v2/cnki/templates/desc.art

Close #8876
```routes
/cnki/journals/WGJG
/cnki/journals/LKGP
/cnki/journals/SXCJ
/cnki/journals/debut/WGJG
/cnki/journals/debut/LKGP
/cnki/journals/debut/SXCJ
```

Add(route): add cnki

---

lib/routes/hackerone/hacktivity.js

N/A
```routes
/hackerone/hacktivity
```
有时候会有明明不是公开的漏洞出现在公开的漏洞列表里，加了一个 filter 过滤掉不是公开漏洞的漏洞
（绕口令）

fix(route)(hackerone): make sure report is disclosed

---

docs/en/new-media.md
docs/new-media.md
lib/v2/line/maintainer.js
lib/v2/line/radar.js
lib/v2/line/router.js
lib/v2/line/today.js

Close #8030
```routes
/line/today
```

feat(route): add Line Today

---

docs/en/new-media.md
docs/new-media.md
lib/router.js
lib/routes/kbs/today.js

Close #
```routes
/kbs/today
```

feat(route): add KBS today

---

docs/anime.md
docs/en/anime.md
lib/v2/kemono/index.js
lib/v2/kemono/maintainer.js
lib/v2/kemono/radar.js
lib/v2/kemono/router.js

Close #8637
```routes
/kemono
/kemono/patreon/143690
/kemono/fanbox/3316400
```

feat(route): add Kemono

---

docs/new-media.md
lib/v2/filmdeepfocus/index.js
lib/v2/filmdeepfocus/maintainer.js
lib/v2/filmdeepfocus/radar.js
lib/v2/filmdeepfocus/router.js

Close #8616
```routes
/filmdeepfocus
```

feat(route): add 深焦

---

docs/government.md
lib/v2/cbirc/index.js
lib/v2/cbirc/maintainer.js
lib/v2/cbirc/radar.js
lib/v2/cbirc/router.js

Close #
```routes
/cbirc/
```
添加 银保监 资讯订阅源

add cbirc repo

---

lib/v2/uibe/hr.js

Close #
```routes
/uibe/hr/jszp/zpxx
```

fix(route): 对外经济贸易大学人力资源处

---

lib/v2/ruc/hr.js

Close #
```routes
/ruc/hr/tzgg
```

fix(route): 中国人民大学人事处

---

docs/reading.md
lib/v2/chaoxing/maintainer.js
lib/v2/chaoxing/qk.js
lib/v2/chaoxing/radar.js
lib/v2/chaoxing/router.js
lib/v2/chaoxing/templates/description.art

Close #8614
```routes
/chaoxing/qk/6b5c39b3dd84352be512e29df0297437
```

feat(route): add 超星期刊

---

docs/new-media.md
lib/v2/leiphone/index.js
lib/v2/leiphone/maintainer.js
lib/v2/leiphone/newsflash.js
lib/v2/leiphone/radar.js
lib/v2/leiphone/router.js
lib/v2/leiphone/utils.js

Close #
```routes
/leiphone
/leiphone/category/industrynews
/leiphone/newsflash
```
adapted to V2 specifications

feat(route): add leiphone

---

docs/reading.md
lib/router.js
lib/routes/novel/axdzs.js

fix(route): 爱下电子书 axdzs

---

lib/routes/dilbert/strip.js

```routes
/dilbert/strip
```
Vercel 的 Preview：

fix(route): Dilbert Strip

---

docs/new-media.md
lib/v2/netease/maintainer.js
lib/v2/netease/radar.js
lib/v2/netease/router.js
lib/v2/netease/today.js

Close #8730
```routes
/netease/today
/netease/today/f
```

feat(route): add 网易新闻今日关注

---

docs/reading.md
lib/v2/qidiantu/index.js
lib/v2/qidiantu/maintainer.js
lib/v2/qidiantu/radar.js
lib/v2/qidiantu/router.js

Close #8722
```routes
/qidiantu/shouding
/qidiantu/1/1
/qidiantu/1/1/t
```

feat(route): add 起点图

---

docs/other.md
lib/v2/shmeea/index.js
lib/v2/shmeea/maintainer.js
lib/v2/shmeea/radar.js
lib/v2/shmeea/router.js

feat(route):add 上海市教育考试院 - 消息速递

---

docs/en/game.md
docs/game.md
lib/v2/gamersecret/index.js
lib/v2/gamersecret/maintainer.js
lib/v2/gamersecret/radar.js
lib/v2/gamersecret/router.js

Close #8711
```routes
/gamersecret
/gamersecret/pc
/gamersecret/category/general
```

feat(route): add Gamer Secret

---

README.md
docs/en/README.md

None
```routes
NOROUTE
```
😅 Forget to update the new blog's URL

docs: update sponsor blog's URL

---

docs/blog.md
docs/en/blog.md
lib/router.js
lib/routes/hexo/fluid.js

Close #
```routes
/hexo/fluid/:url
```

Add Route for hexo theme fluid

---

lib/middleware/parameter.js

Close #8699
```routes
NOROUTE
```
Updated parameter cleaning of `item.description` in `lib/middleware/parameter.js`

fix: remove entity decoding for item html description

---

docs/university.md
lib/v2/ahjzu/maintainer.js
lib/v2/ahjzu/news.js
lib/v2/ahjzu/radar.js
lib/v2/ahjzu/router.js

Close #
```routes
/ahjzu/news
```
(*≧▽≦)

add 安徽建筑大学 通知公告

---

lib/v2/swissinfo/index.js

Close #8803
```routes
/swissinfo/chi/afp
```

fix(route): add swissinfo guid

---

docs/traditional-media.md
lib/v2/nikkei-cn/index.js
lib/v2/nikkei-cn/maintainer.js
lib/v2/nikkei-cn/radar.js
lib/v2/nikkei-cn/router.js

Close #8800
```routes
/nikkei-cn/cn/china/ceconomy
/nikkei-cn/zh/china/ceconomy
```

feat(route): add 日本经济新闻中文版

---

docs/finance.md
lib/router.js
lib/routes/youzhiyouxing/materials.js

Close 无
```routes
/youzhiyouxing/materials
```

路由添加 金融：有知有行 

---

lib/router.js
lib/v2/cool18/index.js
lib/v2/cool18/maintainer.js
lib/v2/cool18/radar.js
lib/v2/cool18/router.js

Close #8761
```routes
/cool18/bbs4/gold
```

fix(route): 酷18

---

lib/routes/aeon/category.js

hotfix: aeon

---

docs/social-media.md
lib/router.js
lib/routes/weibo/super_index.js

无
/weibo/super_index/:id/:type?/:routeParams?
新增的type见下表
| type      | 备注     |
| --------- | -------- |
| soul      | 精华     |
| hot_sort  | 热门     |
| sort_time | 最新帖子 |
| feed(default)     | 最新评论 |
```routes
```
微博超话新增按类型获取，如最新帖子、精华、视频、相册、最新评论

微博超话新增按类型获取，如最新帖子、最新评论、热门、精华等

---

docs/government.md
lib/v2/cpcey/index.js
lib/v2/cpcey/maintainer.js
lib/v2/cpcey/radar.js
lib/v2/cpcey/router.js

Close #8741
```routes
/cpcey
/cpcey/xwg
/cpcey/xfzx
```

add 台灣行政院消費者保護會

---

lib/routes/novel/biquge.js

Close #
```routes
/novel/biquge/142_142152
```
改用 http 以避免证书过期问题

fix: expired SSL certificate of biquge

---

lib/routes/bookwalkertw/news.js

Close #
```routes
/bookwalkertw/news
更新bookwalkertw书籍图片地址

更新bookwalkertw书籍图片地址

---

lib/routes/vgn/index.js

fix: 游戏动力详情链接

---

lib/routes/futunn/highlights.js

Close #
```routes
/futunn/highlights
```

Fix futunn parser issue

---

docs/new-media.md
lib/v2/blockbeats/index.js
lib/v2/blockbeats/maintainer.js
lib/v2/blockbeats/radar.js
lib/v2/blockbeats/router.js

Close #8857
```routes
/blockbeats/flash
/blockbeats/news
```

Add(route): add 律动BlockBeats

---

lib/routes/gamer/gnn_index.js

Close #7730
```routes
/gamer/gnn/4
/gamer/gnn/5
```
fix(route): 巴哈姆特文章標題亂碼修復

fix(route): 巴哈姆特文章標題亂碼修復

---

docs/en/other.md
docs/other.md
lib/v2/firefox/index.js
lib/v2/firefox/maintainer.js
lib/v2/firefox/radar.js
lib/v2/firefox/router.js
lib/v2/firefox/templates/description.art

Close #8679 
```routes
/firefox/breaches
```

feat(route): add firefox monitor

---

lib/router.js
lib/v2/gamer/hot.js
lib/v2/gamer/maintainer.js
lib/v2/gamer/radar.js
lib/v2/gamer/router.js

Close #8638
```routes
/gamer/hot/47157
```

fix(route): fix gamer anti crawl

---

docs/en/programming.md
docs/programming.md
lib/v2/atcoder/contest.js
lib/v2/atcoder/maintainer.js
lib/v2/atcoder/post.js
lib/v2/atcoder/radar.js
lib/v2/atcoder/router.js

Close #8824
```routes
/atcoder/contest/en/upcoming
/atcoder/post
```

feat(route): add AtCoder

---

docs/traditional-media.md
lib/v2/appledaily/index.js
lib/v2/appledaily/maintainer.js
lib/v2/appledaily/radar.js
lib/v2/appledaily/router.js
lib/v2/appledaily/templates/content.art

Close #8817
```routes
/appledaily/home
/appledaily/new
/appledaily/recommend
/appledaily/hot
/appledaily/life
/appledaily/entertainment
/appledaily/local
/appledaily/property
/appledaily/international
/appledaily/politics
/appledaily/gadget
/appledaily/supplement
/appledaily/sports
/appledaily/forum
/appledaily/micromovie
```

Add(route): add 蘋果新聞網

---

docs/design.md
lib/v2/logonews/index.js
lib/v2/logonews/maintainer.js
lib/v2/logonews/radar.js
lib/v2/logonews/router.js
lib/v2/logonews/templates/description.art

Close #8788
```routes
/logonews
/logonews/category/news/newsletter
/logonews/tag/china
/logonews/work
/logonews/work/categorys/hotel-catering
/logonews/work/tags/旅游
```

feat(route): add LogoNews

---

lib/v2/ithome/zt.js

Close #
```routes
ithome/zt/xijiayi
```
参考路由`ithome/it`，替换img.src

fix: 修复路由xijiayi图片显示

---

docs/journal.md
lib/v2/mvm/index.js

Close #
```routes
/mvm/wlsf
```
@fredericky123

feat(route): add 管理世界杂志社网络首发

---

docs/en/journal.md
docs/en/new-media.md
docs/journal.md
docs/new-media.md
lib/v2/informs/index.js
lib/v2/informs/maintainer.js
lib/v2/informs/radar.js
lib/v2/informs/router.js
lib/v2/informs/templates/content.art

Close #8868
Close #8869
```routes
/informs/mnsc
/informs/orsc
```

Add(route): add informs

---

docs/university.md
lib/v2/ecust-jxjy/maintainer.js
lib/v2/ecust-jxjy/news.js
lib/v2/ecust-jxjy/radar.js
lib/v2/ecust-jxjy/router.js

Close #
```routes
/ecust-jxjy/news/
```

feat: add 华东理工继续教育学院新闻公告;

---

.github/workflows/dependabot-fork.yml

Close #
```routes
NOROUTE
```
Replacement of #8378

Ignore dependabot on forks

---

lib/routes/mi/youpin/new.js

Close #7389
```routes
/mi/youpin/new
```

fix: 小米有品每日上新

---

lib/routes/dsndsht23/index.js

Close #
```routes
/dsndsht23
/dsndsht23/36/368
```
如 https://github.com/DIYgod/RSSHub/pull/3968#issue-374655896 所说，每个页面含有 30 个文章，每日更新大约 20 个，增加切片数量至 25 更合理

增加色花堂文章切片数量

---

lib/routes/who/news-room.js

#6795 
```routes
/who/news-room/feature-stories
```

fix(route): migrate WHO routes to new time parser

---

docs/new-media.md
lib/v2/storm/index.js
lib/v2/storm/maintainer.js
lib/v2/storm/radar.js
lib/v2/storm/router.js

Close #8299
```routes
/storm
```

feat(route): add 風傳媒

---

docs/blog.md
lib/v2/whoscall/index.js
lib/v2/whoscall/maintainer.js
lib/v2/whoscall/radar.js
lib/v2/whoscall/router.js

Close #8476
```routes
/whoscall
```

feat(route): add Whoscall

---

lib/routes/dongqiudi/result.js

Close #8468
```routes
/dongqiudi/result/50000516
```

fix(route): 懂球帝赛果失效

---

docs/anime.md
lib/v2/qq/ac/comic.js
lib/v2/qq/ac/rank.js
lib/v2/qq/ac/templates/description.art
lib/v2/qq/ac/utils.js
lib/v2/qq/maintainer.js
lib/v2/qq/radar.js
lib/v2/qq/router.js

Close #8598
```routes
/qq/ac/rank
```

feat(route): add 腾讯动漫

---

docs/new-media.md
lib/v2/consumer/index.js
lib/v2/consumer/maintainer.js
lib/v2/consumer/radar.js
lib/v2/consumer/router.js

Close #8740
```routes
/consumer
/consumer/life
```

feat(route): add 消費者委員會

---

lib/v2/jandan/index.js

fix(route): 煎蛋打赏广告移除

---

lib/routes/yxdzqb/index.js

Close #
```routes
/yxdzqb/new
/yxdzqb/hot
/yxdzqb/hot_chinese
/yxdzqb/low
/yxdzqb/low_chinese
```
游戏打折情报 path 更新，老 path 很久没动静了

fix(route): 游戏打折情报

---

lib/v2/epicgames/router.js

Close #8941
```routes
/epicgames/freegames 
```

Fix(route): fix route address

---

lib/routes/zhihu/posts.js

无
```routes
/zhihu/posts/org/zhi-shi-fen-zi-68-1
```
修正了该 route 的时间显示

fix(route): zhihu posts pubDate

---

lib/routes/ehentai/ehapi.js

Close #
```routes
/ehentai/tag/artist:allenes/0/1
```
如题

feat(route): 在E站获取最新的种子下载链接而不是最旧的

---

docs/en/programming.md
docs/programming.md
lib/v2/hackernews/index.js
lib/v2/hackernews/maintainer.js
lib/v2/hackernews/radar.js
lib/v2/hackernews/router.js

```routes
/hackernews/newcomments/comments_list/
/hackernews/threads/comments_list/dang
/hackernews/submitted/source/dang
```
Add route to subscribe to a certain user in hacker news.

Add(route): add hacker news user follow

---

docs/en/program-update.md
docs/program-update.md
lib/v2/app-center/maintainer.js
lib/v2/app-center/radar.js
lib/v2/app-center/release.js
lib/v2/app-center/router.js
lib/v2/app-center/templates/description.art

Close #
```routes
/app-center/release/gameonline/baitomobile/baito
/app-center/release/cloudflare/1.1.1.1-windows/beta
/app-center/release/rdmacios-k2vy/microsoft-remote-desktop-for-mac/all-users-of-microsoft-remote-desktop-for-mac
/app-center/release/rafalense-70ux/plus-release/public
```

feat(route): add App Center Release

---

.github/workflows/docker-release.yml

ci: release docker in source only

---

.github/workflows/build-assets.yml
.github/workflows/docker-release.yml
.github/workflows/docker-test.yml
.github/workflows/format.yml
.github/workflows/test.yml
package.json

chore(misc): multiple enhancement to github actions

---

docs/en/journal.md
docs/journal.md
lib/router.js
lib/v2/bioone/featured.js
lib/v2/bioone/journal.js
lib/v2/bioone/maintainer.js
lib/v2/bioone/radar.js
lib/v2/bioone/router.js

Close #6979
```routes
/bioone/featured
/bioone/journals/acta-chiropterologica
```

feat(route): add BioOne

---

lib/v2/zaobao/index.js
lib/v2/zaobao/maintainer.js
lib/v2/zaobao/realtime.js
lib/v2/zaobao/router.js
lib/v2/zaobao/templates/zaobao.art

Close #8998
```routes
/zaobao/realtime
/zaobao
```

fix(route): 联合早报

---

docs/new-media.md
lib/v2/cdi/index.js
lib/v2/cdi/maintainer.js
lib/v2/cdi/radar.js
lib/v2/cdi/router.js

Close #9008
```routes
/cdi/102
/cdi/152
/cdi/150
/cdi/153
/cdi/154
/cdi/151
```

feat(route): add 国家高端智库 / 综合开发研究院

---

docs/blog.md

无
```routes
NOROUTE
```
remove unnecessary  code `</Route>` from `blog.md`

docs: remove unnecessary `</Route>`

---

docs/new-media.md
lib/v2/wyzxwk/article.js
lib/v2/wyzxwk/maintainer.js
lib/v2/wyzxwk/radar.js
lib/v2/wyzxwk/router.js

Close #7200
```routes
/wyzxwk/article/shushe
/wyzxwk/article/jingji
/wyzxwk/article/guoji
/wyzxwk/article/lixiang
/wyzxwk/article/lishi
/wyzxwk/article/qingnian
/wyzxwk/article/gonggao
```

feat(route): 乌有之乡栏目

---

docs/government.md
lib/v2/gov/huizhou/zwgk/index.js
lib/v2/gov/maintainer.js
lib/v2/gov/radar.js
lib/v2/gov/router.js

Close #9035
```routes
/gov/huizhou/zwgk/zwyw
/gov/huizhou/zwgk/jgdt
/gov/huizhou/zwgk/xqyw
```

feat(route): add 惠州市政府惠州时政

---

Dockerfile

Update https://registry.npm.taobao.org to https://registry.npmmirror.com, Please refer to https://zhuanlan.zhihu.com/p/430580607.
```routes
NOROUTE
```

fix: update https://registry.npm.taobao.org to https://registry.npmmirror.com

---

.eslintignore
docs/.vuepress/config.js

Close #
```routes
NOROUTE
```
fix slug pinyin in https://github.com/DIYgod/RSSHub/commit/b4ec4af7add0a7f9e135eda1526ca4e4b5c8b38e
https://docs.rsshub.app/social-media.html#ba-ha-mu-te -> https://docs.rsshub.app/social-media.html#ba-ha-ha-ha-he-he-ta-sha-mu-te

docs: fix slug pinyin

---

lib/v2/telegram/channel.js
lib/v2/telegram/templates/video.art

Close #7938
```routes
/telegram/channel/pincongessence
```

fix(route): telegram channel videos

---

.github/workflows/docker-release.yml

```routes
NOROUTE
```
fix per https://github.com/DIYgod/RSSHub/pull/8971#discussion_r799414419

ci: release docker in source only, take 2

---

docs/new-media.md
lib/v2/panewslab/column.js
lib/v2/panewslab/index.js
lib/v2/panewslab/maintainer.js
lib/v2/panewslab/newsflash.js
lib/v2/panewslab/radar.js
lib/v2/panewslab/router.js
lib/v2/panewslab/topic.js

Close #9111
```routes
/panewslab
/panewslab/newsflash
/panewslab/column/N7042814
/panewslab/topic/1582623288184036
```

feat(route): add PANews

---

.github/workflows/build-assets.yml
.github/workflows/docker-test.yml
.github/workflows/format.yml
.github/workflows/npm-publish.yml
.github/workflows/pr-deploy-route-test.yml
.github/workflows/pr-lint.yml
.github/workflows/test.yml

chore: name actions

---

docs/programming.md
lib/v2/gocn/maintainer.js
lib/v2/gocn/radar.js
lib/v2/gocn/router.js
lib/v2/gocn/topics.js

Close #
```routes
/gocn
```
添加GOCN站点RSS源

feat(router):添加GOCN站点RSS订阅源

---

lib/v2/telegram/templates/video.art

Close #
```routes
/telegram/channel/NewlearnerChannel
```

fix(route)(telegram): redundant backtick in template

---

docs/new-media.md
lib/v2/nogizaka46/blog.js
lib/v2/nogizaka46/maintainer.js
lib/v2/nogizaka46/radar.js
lib/v2/nogizaka46/router.js

Close #
```routes
/nogizaka46/blog
```
官网不再提供博客 RSS 链接。

feat: add nogizaka46 blog

---

lib/routes/jike/user.js

Close #
```routes
/jike/user/EDAE807D-B2A3-4C00-9B4F-1D4726584778
```

fix(route)(jike/user): improper linebreak

---

lib/router.js
lib/routes/wsj/index.js
lib/v2/wsj/index.js
lib/v2/wsj/maintainer.js
lib/v2/wsj/radar.js
lib/v2/wsj/router.js

Close #7378
```routes
/wsj/en-us/world_news
```

fix(route): wsj

---

lib/v2/javlibrary/utils.js

Close #
```routes
/javlibrary/stars/aegeq
```

fix(route): video previews for JAVLibrary

---

docs/new-media.md
lib/router.js
lib/routes/tencent/wechat/tgchannel.js

https://github.com/DIYgod/RSSHub/pull/7648#issuecomment-1048150847
```routes
/wechat/tgchannel/lifeweek
/wechat/tgchannel/efb_rsshub
/wechat/tgchannel/efb_rsshub/123%20测试
/wechat/tgchannel/efb_rsshub/123%20测试/0
/wechat/tgchannel/efb_rsshub/123%20测试/1
/wechat/tgchannel/efb_rsshub/123%20测试/2
/wechat/tgchannel/efb_rsshub/测试，测试
/wechat/tgchannel/efb_rsshub/测试，测试/0
/wechat/tgchannel/efb_rsshub/测试，测试/1
/wechat/tgchannel/efb_rsshub/测试，测试/2
/wechat/tgchannel/efb_rsshub/Metro%20Bay
/wechat/tgchannel/efb_rsshub/Metro%20Bay/0
/wechat/tgchannel/efb_rsshub/Metro%20Bay/1
/wechat/tgchannel/efb_rsshub/Metro%20Bay/2
/wechat/tgchannel/efb_rsshub/轨道世界
/wechat/tgchannel/efb_rsshub/轨道世界/0
/wechat/tgchannel/efb_rsshub/轨道世界/1
/wechat/tgchannel/efb_rsshub/轨道世界/2
```

feat(route)(wechat/tgchannel): efb-patch-middleware format support; using search to filter mpName

---

.github/workflows/pr-lint.yml

chore: eslint with reviews

---

lib/routes/nowcoder/discuss.js

Close #
```routes
/nowcoder/discuss/:type/:order
```
之前会将简介也提取为title，更新后只提取标题。
之前：
```
<item>
<title>
<![CDATA[ 叠纸游戏是不是投了秋招就不能投春招啊？ 叠纸游戏我春招想投同一个职位，但是系统总说我重复申请。 我秋招也只投了一个职位，没超过六个月内只能投3个职位... ]]>
</title>
<description>
<![CDATA[ <div> <img alt="" src="https://uploadfiles.nowcoder.com/images/20220224/922784249_1645708747419/6577B5713EDFDA36285305A38FD0ED64" referrerpolicy="no-referrer"> </div> <div> <br> </div> <div> <span> 我<a class="content-link js-post-content-keyword" href="https://www.nowcoder.com/jump/super-jump/word?word=%E6%98%A5%E6%8B%9B" target="_blank">春招</a>想投同一个职位，但是系统总说我重复申请。 </span> </div> <div> 我秋招也只投了一个职位，没超过六个月内只能投3个职位的限制。 </div> <div> 为什么这样啊？ </div> <div> &nbsp;&nbsp; </div> ]]>
</description>
<guid isPermaLink="false">https://www.nowcoder.com/discuss/845607</guid> …
```

fix(route): 修复牛客网讨论将简介提取到 title

---

lib/routes/weibo/utils.js

Close #
```routes
/weibo/user/2612249974
```

feat(route)(weibo): add article pic

---

docs/university.md
lib/router.js
lib/v2/sysu/cse.js
lib/v2/sysu/maintainer.js
lib/v2/sysu/radar.js
lib/v2/sysu/router.js

Close #8332
```routes
/sysu/cse
```

fix(route): 中山大学计算机学院

---

docs/social-media.md
lib/routes/weibo/timeline.js
lib/routes/weibo/user.js
lib/routes/weibo/utils.js

Close #7245
```routes
/weibo/user/2612249974/displayArticle=1
/weibo/user/5822055366/displayArticle=1
```
我不使用微博，无法测试个人时间线路由，理论上应该是可用的，就算不可用也不会出错。
若文章限制登录后查看，则无法抓取。
(文字的白底是博主设置的格式，不是 bug)
(`试读` 和 `原创` 是为了测试输出特意加的，这篇文章既不是收费文章也不是原创文章)

feat(route)(weibo): display article

---

lib/routes/weibo/timeline.js
lib/routes/weibo/user.js
lib/routes/weibo/utils.js

Close #
```routes
/weibo/user/2131970111/displayArticle=1
```

fix(route)(weibo): retweeted video/article; article background color

---

.eslintrc
.github/workflows/docker-test.yml
.github/workflows/pr-deploy-route-test.yml

style(eslint): no empty line before comments for yml

---

docs/new-media.md
lib/v2/wikinews/index.js
lib/v2/wikinews/maintainer.js
lib/v2/wikinews/radar.js
lib/v2/wikinews/router.js
package.json
yarn.lock

Close #8194 
```routes
/wikinews/latest
```
在```package.json```添加了```xml2js```这个包。
说是添加其实也没有添加，```rss-parser```有依赖这个包

feat(route): wikinews

---

docs/study.md
lib/v2/ielts/index.js
lib/v2/ielts/maintainer.js
lib/v2/ielts/radar.js
lib/v2/ielts/router.js

Close #9094
```routes
/ielts
```
---
<details>
<summary>
</summary>
- [#9094: IELTS雅思最新消息](https://issuehunt.io/repos/127769231/issues/9094)
---
</details>

feat(route): add ielts

---

docker-compose.yml
scripts/ansible/rsshub.yaml

Close #6680
```routes
NOROUTE
```
Chrome 98.0.4758.102 Chromium 99.0.4844.0 and Chrome dev 100.0.4896.12 gives `navigator.webdriver=undefined`. Pinning chrome version is no longer needed.

dep: revert chrome version pinning

---

lib/routes/mofish/index.js
lib/routes/mofish/templates/description.art

```routes
/mofish/136
```
- 修复鱼塘热榜时间错误
- 优化鱼塘热榜每日动图的显示方式

fix(route): 鱼塘热榜修复与优化

---

docs/new-media.md
lib/v2/hellobtc/information.js
lib/v2/hellobtc/kepu.js
lib/v2/hellobtc/maintainer.js
lib/v2/hellobtc/news.js
lib/v2/hellobtc/radar.js
lib/v2/hellobtc/router.js
lib/v2/hellobtc/topic.js

Close #9231
```routes
/hellobtc/information/latest
/hellobtc/news
/hellobtc/kepu/latest
/hellobtc/topic/276
```

feat(route): add 白话区块链

---

docs/traditional-media.md
lib/v2/wallstreetcn/live.js
lib/v2/wallstreetcn/router.js

```routes
```
/v2/wallstreetcn/live/global/2
只看重要的

feat(route): 华尔街见闻-只看重要的

---

.github/workflows/codeql.yml

chore: add codeql

---

lib/v2/app-center/templates/description.art

Close #
```routes
/app-center/release/gameonline/baitomobile/baito
/app-center/release/cloudflare/1.1.1.1-windows/beta
/app-center/release/rdmacios-k2vy/microsoft-remote-desktop-for-mac/all-users-of-microsoft-remote-desktop-for-mac
/app-center/release/rafalense-70ux/plus-release/public
```

fix(route)(app-center/release): improper linebreak

---

lib/routes/hentaimama/videos.js

Fix parsing, now return valid image url

fix(route): hentaimama Image Parsing

---

lib/v2/ielts/index.js

fix(route): ielts window.$ is not a function

---

lib/v2/ielts/index.js

This reverts commit 0b4ea2ee6777592217097cb591674b94f5259c35.
Close #
```routes
NOROUTE
```

revert: "fix(route): ielts window.$ is not a function (#9255)"

---

lib/v2/ff14/ff14_global.js

Close #
```routes
/ff14/ff14_global/jp/all
```
由于上游api调用格式更新，当前设置地区无效，全部变成na
更新后可以正常获取所选地区的内容

fix(route): 最终幻想 14 国际服 Lodestone 内容api调用格式更新

---

docs/finance.md
lib/v2/bigquant/collections.js
lib/v2/bigquant/maintainer.js
lib/v2/bigquant/radar.js
lib/v2/bigquant/router.js

Close #9244
```routes
/bigquant/collections
```

feat(route): add BigQuant专题报告

---

docs/en/picture.md
docs/picture.md
lib/v2/35photo/actual.js
lib/v2/35photo/author.js
lib/v2/35photo/genre.js
lib/v2/35photo/interesting.js
lib/v2/35photo/maintainer.js
lib/v2/35photo/map.js
lib/v2/35photo/new.js
lib/v2/35photo/radar.js
lib/v2/35photo/router.js
lib/v2/35photo/utils.js

Close #9258
```routes
/35photo/new
/35photo/actual
/35photo/interesting
/35photo/map
/35photo/genre/99
/35photo/author/mariuszsix
```

feat(route): add 35PHOTO

---

docs/new-media.md
lib/v2/foresightnews/index.js
lib/v2/foresightnews/maintainer.js
lib/v2/foresightnews/radar.js
lib/v2/foresightnews/router.js

Close #9268
```routes
/foresightnews
/foresightnews/news
/foresightnews/column/1
```

feat(route): add Foresight News

---

docs/traditional-media.md
lib/v2/sputniknews/index.js
lib/v2/sputniknews/maintainer.js
lib/v2/sputniknews/radar.js
lib/v2/sputniknews/router.js

Close #9265
```routes
/sputniknews/news
/sputniknews/china
/sputniknews/russia
/sputniknews/category_guoji
/sputniknews/russia_china_relations
/sputniknews/opinion
```

feat(route): add 俄罗斯卫星通讯社

---

docs/en/joinus/quick-start.md
docs/joinus/quick-start.md
lib/middleware/template.js
lib/routes/guancha/member.js
lib/routes/lizhi/user.js
lib/routes/missevan/drama.js
lib/routes/missevan/latest.js
lib/routes/ncm/djradio.js
lib/routes/radio/radio.js
lib/routes/ximalaya/album.js
lib/routes/yyets/todayfilelist.js
lib/v2/ajmide/index.js
lib/v2/telegram/channel.js
lib/v2/test/index.js
lib/v2/xiaoyuzhou/pickup.js
lib/v2/xiaoyuzhou/podcast.js
lib/views/rss.art
test/middleware/template.js

Close #9287 
```routes
/ximalaya/album/299146/0/shownote
/ximalaya/album/299146
/telegram/channel/PubTChannel
/ncm/djradio/347317067
/missevan/drama/28499
/missevan/drama/latest
/ajmide/10603594
/test/enclosure
/guancha/member/huodongs
/xiaoyuzhou/podcast/6021f949a789fca4eff4492c
/radio/2/520767
/lizhi/user/27151442948222380
```

fix(route): migrate invalid `enclosure_length` usages to `itunes_duration`

---

docs/en/install/README.md
docs/install/README.md
lib/config.js

refactor: config.js

---

lib/routes/universities/hitwh/today.js

None
```routes
/hitwh/today
```
网站改版

fix(route): 哈尔滨工业大学（威海）通知公告

---

docs/en/programming.md
docs/programming.md
lib/v2/gitpod/blog.js
lib/v2/gitpod/changelog.js
lib/v2/gitpod/maintainer.js
lib/v2/gitpod/radar.js
lib/v2/gitpod/router.js
lib/v2/gitpod/templates/description.art
lib/v2/gitpod/utils.js

Close #
```routes
/gitpod/blog
/gitpod/changelog
```

feat(route): add gitpod
