DIYgod/RSSHub

- middleware/utf8.js
如果请求的是静态资源，则 `ctx.body` 为 `undefined`.那么该处会报错
比如：启动服务之后，打开首页会请求`/favicon.ico` ,就回报错
`error: Promise error: TypeError: Cannot read property 'replace' of undefined`
所以该处应该加一个容错判断
> fix middleware/utf8.js file bug

- docs/install/README.md
只有 GitHub Readme 才可以省略 `template` 参数...
[see also](https://devcenter.heroku.com/articles/heroku-button)
> Fix deploy to Heroku button

- routes/jike/user.js
1. fix REPOST link not correct issue: it will show **"内容不存在"** message when openning the wrong repost link
2. fallback the REPOST template, coz the rss reader didn't render it correctly
3. add `<br>` for better layout post
> fix(jike user): ref link not correct issue

- docs/install/README.md
> docs(install): update tutorial

- routes/iqiyi/dongman.js
今天发现爱奇艺动漫会在剧集列表中更新预告(- - !)，所以题目错误地显示“第18话”而不是“第18话预告”，于是稍作修改。
> rss:fix iqiyi dongman

- routes/zhihu/activities.js
- routes/zhihu/answers.js
修复抓取知乎用户动态、知乎用户回答过程中，出现的401错误。
如：抓取 `/zhihu/people/answers/diygod` 出现 `RSSHub 发生了一些意外: Error: Request failed with status code 401`
> fix:zhihu return HTTP401 "ZERR_NO_AUTH_TOKEN"

- routes/bilibili/blackboard.js
> fix:更新B站主站话题接口链接

- docs/README.md
- router.js
- routes/zhihu/hotlist.js
Mentioned at https://github.com/DIYgod/RSSHub/issues/17#issuecomment-417828181
最后实际采用了上述issue中提到的第一个API
即 https://www.zhihu.com/api/v3/explore/guest/feeds?limit=15
虽然从路径上看，后两个更加语义化，但是只有第一个提供了全文
> Zhihu hot list support

- Dockerfile
已知 `ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 /usr/local/bin/dumb-init`时需要访问 GitHub Release 资源被墙。
> Dockerfile 增加 puppeteer 依赖

- api_router.js
- docs/README.md
- docs/en/README.md
- index.js
方便其他项目如 https://github.com/idealclover/Easy-to-RSS
> 添加 API: 返回可用公共路由列表

- routes/jike/topic.js
即刻 Feed 里使用原文链接。这样当你使用 RSS reader （如 reeder）时，可以直接使用 mercury view 阅读原文。
> Use source URL for jike feed item link

- router.js
- routes/jike/topicDev.js
测试中，完善后替代 `/jike/:id`
采用WebP #555
包含了 #692
目标关闭 #621
> 添加即刻新版路由 /jike/dev/:id

- docs/.vuepress/components/Route.vue
- docs/README.md
1. 统一文档格式。
2. 简化文档，解放开发者。
3. 通过修改后的文档格式，为 API 作准备。
新文档格式如下：
- name:  路由名称
- author: 路由作者
- example: 路由举例
- path: 路由路径
- :paramsDesc: 路由参数说明，数组，组件自动检测路由路径中的可选与必选参数，如缺少说明将会导致报错。说明支持 markdown，但是需要注意说明中的 `'` `"` 必须为 `\'` `\"`
多参数：
```vue
<route name="仓库 Issue" author="HenryQW" example="/github/issue/DIYgod/RSSHub" path="/github/issue/:user/:repo" :paramsDesc="['用户名', '仓库名']"/>
```
支持 markdown:
```vue
<route name="应用更新" author="HenryQW" example="/appstore/update/cn/id444934666" path="/appstore/update/:country/:id" :paramsDesc="['App Store 国家, 如 QQ 的链接为 https://itunes.apple.com/cn/app/qq/id444934666?mt=8, 则 country 为 `cn`', 'App Store app id, 如 QQ 的链接为 https://itunes.apple.com/cn/app/qq/id444934666?mt=8, 则 id 为 `id444934666`']"/>
```
复杂说明支持 slot: 
```vue
<route name="即时新闻" author="lengthmin" …
```
> 文档改为 Route.vue 组件

- docs/README.md
> fix github trending link

- package.json
- yarn.lock
```
npm WARN deprecated crypto@1.0.1: This package is no longer supported.
It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's
built-in.
```
> Remove deprecated npm package crypto

- routes/zhihu/activities.js
同时订阅多个 id 时不能区分是谁的状态，这个 PR 用来解决这个问题。
> 修复：知乎动态增加 owner

- index.js
- middleware/lru-cache.js
- middleware/redis-cache.js
本补丁主要解决了以下两个问题：
1. 在 a1f060f3d2205fbe5cfc1672ad2bb0212e350c65 提交时，缓存get方法发生了变化。
**cache的get方法未正确返回值**，这将导致所有使用自定义缓存的地方缓存丢失！
2. 同时修正了未设置缓存时系统报`tryGet`方法未定义的问题。
> fix: can not get cache

- routes/tencent/video/playlist.js
原来的代码为了获取总集数（如[名侦探柯南](http://v.qq.com/detail/5/53q0eh78q97e4d1.html)），会通过 jQuery 解析页面。但是在部分播放列表中（如[SSSS.Gridman](https://v.qq.com/detail/o/o28lfr4elqppz6q.html)），相应的解析方法会出现错误：
```
RSSHub 发生了一些意外:
TypeError: Cannot read property 'split' of undefined
at module.exports (/app/routes/tencent/video/playlist.js:12:9)
at process.internalTickCallback (internal/process/next_tick.js:77:7)
```
经实验，相应的 API 中 `range` 参数其实只需要随意填一个数字，就会 fallback 到全部集数。因此这里用这个方法修复了相应的 BUG。
> :bug: 修复了腾讯视频部分情况下出错的 bug

- routes/douban/book/rank.js
> Hotfix: 豆瓣热门图书评分

- routes/t66y/post.js
由于之前的规则，可能会被t66y当做爬虫被ban掉ip，因此现在做了点限制，以降低被ban的风险。
> fix: 增加没有读到楼主回复时候的重试次数限制

- routes/baidu/topwords.js
修复某些 `description` 为 `undefined` 的问题
> Hotfix: baidu topwords

- routes/baidu/topwords.js
> Hotfix: baidu topwords content

- routes/douyin/user.js
- Closes #1256 
- 有些用户主页会有三个 tab，这种情况下**作品**变成了第二个 tab，默认不会加载也就不会触发到代码里 `resolve`的逻辑，因此改成手动触发一次点击**作品** tab
> Hotifx: douyin

- routes/jike/common.js
- 翻车的图片是 https://cdn.ruguoapp.com/FmPwBqyD-hbbTUTxSC_UsmmDD-jR?imageMogr2/auto-orient/heic-exif/1/format/jpeg/thumbnail/1329336@ 这种格式，`?imageMogr2` 前并没有 `.后缀名` 这样的跟着，直接 `split('?imageMogr2/')` 后图片无法访问。试了下也找不到原始的文件是怎样的，因此目前的处理方式是判断到 `?imageMogr2` 前有  `.后缀名` 才进行 `split` 操作，没有的话直接使用不带 `thumbnail` 的部分
- Closes #1282
> Hotfix: jike img

- docs/README.md
- 搜了下好像是 3a30d5d5a3731150c9ed08d6d8342b52a364ba88 这个提交导致的`route`标签嵌套/闭合错误会使本地`npm run docs:dev`飘红~
- 顺便调整了下提示文案位置，放到最开头的地方
> Hotfix: 修复文档标签闭合错误

- lib/routes/manhuagui/comic.js
如果漫画话数不多的情况下用原方案是可以的，
但是如果话数多了之后会分页，
div 的 id 会变为 `#chapter-list-1` 就不可用了
直接修改成 class `.chapter-list` 就同时兼容了这两部分了。
> Fix manhuagui close #1381

- lib/routes/twitter/utils.js
- `media.type` 为 `animated_gif` 时自动循环播放视频，普通视频（`video`）维持原状
- 具体表现与阅读器（或者说是浏览器内核）有关，有些确实不支持自动播放，可以参考[这个](https://imququ.com/post/new-video-policies-for-ios10.html)
- Closes #1421
> Enhancement: twitter animated_gif autoplay

- lib/routes/jike/topic.js
修改即刻 Feed，对两个新闻主题 [一觉醒来世界发生了什么](https://web.okjike.com/topic/553870e8e4b0cafb0a1bef68/official) 和 [今天网上都在热议什么](https://web.okjike.com/topic/55963702e4b0d84d2c30ce6f/official) 进行特殊处理：
- 标题改为 `${主题名称} ${日期}` 如 `一觉醒来世界发生了什么 01月30日`
- 为每个新闻添加源文链接
Reader 中效果如下：
> :sparkles: 即刻：对两个新闻主题做特殊处理

- lib/routes/readhub/category.js
对 ReadHub 下的不同分类做特定的处理：
1. [科技动态](https://readhub.cn/news)、[https://readhub.cn/tech](开发者咨询) 和 [区块链快讯](https://readhub.cn/blockchain)：这三个分类没有细分内容，直接显示概要。 Reeder 下表现：
2. [热门话题](https://readhub.cn/topics) 和 [每日早报](https://readhub.cn/daily) 显示包括媒体报道、相关事件、事件追踪、原文链接在内的细分内容。Reeder 下表现如下：
> :zap: 增强 ReadHub

- lib/routes/dockerhub/build.js
Fetch build stats via `tags` api
> fix: handle docker images without build history

- docs/README.md
- lib/router.js
- lib/routes/dongqiudi/special.js
- lib/routes/dongqiudi/top_news.js
- lib/routes/tencent/wechat/wasi.js
详细解释一下增加瓦斯公众号历史文章的原因：
* 目前的瓦斯公众号抓取（阅读器为Inoreader为例）：想要抓取某微信公众号的“日报”栏目时，利用瓦斯源，加上参数过滤，理想状态下是可以抓取到想要的内容的；但是，Inoreader刚添加订阅源时，很大可能订阅源是空的（即该公众号上一次所发布的文章中不含“日报”关键字），此时阅读器会把抓取间隔设置为比较大的值（假设为6小时）。而6小时内，公众号发布了两次内容，第一次含“日报”，第二次不含“日报”，这样的话，阅读器再次抓取时，订阅源仍然为空，抓取间隔继续加大……最终导致根本抓取不到想要的内容。（叙述可能有些混乱，实际测试中确实如此，测试使用之一是“央视新闻”公众号的“早啊！新闻来了”栏目，几天（不含周末）下来，并未抓到一篇文章，其他例子中情况类似）
* 抓取历史文章的情况下：条数限制为20，通常情况下很少公众号一天能发布超过20篇文章，因此首次理论上能抓到几篇想要的文章（“日报”等），然后接下来阅读器抓取频率并不会降低（最终会稳定在栏目发布间隔这个时间）。实际测试中确实有比较好的效果，而且不加参数过滤的话也完全不受影响。
> add 懂球帝头条&专题新闻 optimize 瓦斯公众号历史文章

- lib/routes/nowcoder/discuss.js
目前抓取的description数据，包含赞数和收藏数等，且会不断更新。这个 PR 把这些变化的数字去掉。
原先每个帖子都有
```html
收藏(43)</a></li><li class="oprt-item-share"><a class="oprt-item oprt-share js-share-oprt-item" href="javascript:void(0);">分享</a><div class="tooltip top js-share-tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"><span class="q-share-to"><a href="javascript:void(0);" class="js-share-link share-wb" data-share="weibo"></a><a href="javascript:void(0);" class="js-share-link share-tx" data-share="qzone"></a><a href="javascript:void(0);" class="js-share-wx share-wx"></a></span></div></div></li><li><a href="javascript:void(0);" class="js-post-like nc-req-auth oprt-item oprt-like">赞(0)
```
全都去掉了。
> 修改牛客网帖子内容（description）解析方案

- lib/routes/dytt/index.js
let list = $('.co_content8 table tr').get();
list.splice(0, 1);
原因如下：
页面内含有两个 .co_content8 table
仅第一个 table内 第一个 tr 元素是广告
const list = $('.co_content8 table tr:not(:first-child)').get();
会丢失第二个table的第一个tr元素
> 对电影天堂增加全文抓取

- lib/routes/dockerhub/build.js
1. 原来的 `pubDate` 为 `2019-03-08T04:10:53.381143Z` 格式，现修改成 UTC 格式
2. 原来的 `guid` 为 link ，每次有新的 build 都是返回同一个 link ，现从接口中找了个不会重复的参数即 `pubDate` 作为 guid
> [Dockerhub] Fix date and guid

- Dockerfile
Debian jessie has been archived.
Fix #1833.
> chore: update base docker image

- docs/social-media.md
- lib/router.js
- lib/routes/matters/author.js
- lib/routes/matters/hot.js
- lib/routes/matters/latest.js
- lib/routes/matters/tags.js
- lib/routes/matters/topics.js
有關獲取主頁中的最新訊息（`matters/latest`），因網站未能提供相應接口，且需模仿 click button，故只能採用 `puppeteer`。
> 支援 Matters.News

- docs/traditional-media.md
- lib/routes/infzm/news.js
- 由于源站页面结构(包括 url)变更，导致页面链接/guid、参数均与之前不对应。这是一个**破坏性/不兼容**变更
- 另外链接全部更改为 https
- Closes #1866
> Hotfix: infzm

- lib/router.js
由于先前的路由的注册顺序是**先**`/nytimes/:lang?`**后**`/nytimes/morning_post`，且`lang`参数为可选。当访问`/nytimes/morning_post`时实际上是走到了第一个路由也就是`/nytimes/:lang?`里(这种情况下第二个路由其实并没有起作用)，导致输出内容不符合预期
因此调换两个路由的注册顺序可以解决这个问题
Closes #1886
> Hotfix: nytimes route

- lib/routes/mp4ba/index.js
原来的 www.mp4ba.com 进行了改版，新站地址不变，旧站变为 ww.mp4ba.com。
> fix: #1982 修正mp4ba 旧站404错误

- lib/routes/jike/topic.js
- lib/routes/jike/topicSquare.js
- lib/routes/jike/topicText.js
- lib/routes/jike/user.js
尝试使用更新的版本号时，返回的结果不单纯按照时间排序，而经过推荐分发。
目前网页版的使用的版本号为`5.3.0`。
Reeder 本地订阅了 `npm run dev` 似乎没什么问题。
> fix: 修复了个人/圈子动态不返回第三张以后的图片的问题

- docs/other.md
- docs/traditional-media.md
- lib/router.js
- lib/routes/caixin/blog.js
同时更改了原财新网的路由，不知道有没有问题。
**Development**:
文档部分：本地 `npm run docs:dev` 跑起来后，`localhost:8080` 没有相应的返回结果，路由是目测写的。不知道是不是本地环境的问题。
希望加入 `feed.description`，只能通过解析页面获得，看了一下 `ctx.cache.tryGet()` 的实现，手动设置缓存是为了避免引入额外的信息。
> feat: 增加财新博客全文输出

- docs/social-media.md
- lib/router.js
- lib/routes/bilibili/ranking.js
feat: 哔哩哔哩排行榜 功能的添加 支持(全部投稿和近期投稿的选择)
fix:title和description的完整化
docs:添加功能描述
before
after
> feat: 哔哩哔哩排行榜功能添加

- lib/routes/apple/exchange_repair.js
多语言日期格式很难全部照顾到，想过用 regex 处理：
```js
date = date.replace(/\D+/g, '-').replace(/^-?|-?$/g, '');
```
kr: 2019년 4월 25일 返回：2018-04-25
ru: 9 ноября 2018 г. 返回：9-2018
moment 也无法解析，只能暂时移除。
Close #2141.
> fix: remove pubDate due to i18n date string parsing issue

- docs/forecast.md
- lib/routes/tingdiantz/95598.js
原来的抓取网址不翻墙打不开且参数已修改，修复抓取时间为前一天的错误。
> fix: 修复国家电网通知

- lib/routes/tencent/wechat/wasi.js
之前fix的url是瓦斯的feed url，修改成了api url，直接链接到微信文章
> fix: wasi url again

- lib/routes/tencent/wechat/wasi.js
之前的author页面跳转到了主页，改成了最新的author页面链接
> fix: 瓦斯author链接更改

- docs/forecast.md
- lib/router.js
- lib/routes/outagereport/service.js
> https://outage.report/ 是个监控互联网公共服务/本地基础设施可用性的网站, 数据来源为用户报告｡ 
当某项服务被用户报告停止工作, 且 20  分钟内次数超过一定数量 (默认为 10 次) 时, 会被 RSS 记录｡ 
使用场景举例: 某某家的土豆服务器又炸了｡ 
因为网站原文为英文, 所以输出的相关信息, 也用英文书写｡ 但考虑 RssHub 多为中文用户, 可以考虑将来增加多语言选项｡
> feat: add Outage.Report 在线服务/本地设施停服通知

- lib/routes/appstore/update.js
修复了路由 appstore/update 不能正确判断应用平台 (iOS / macOS) 的问题。
问题源于 cheerio 的 `.text()` 将 `&nbsp;` 转换为 No-Break Space (U+00A0) 而不是普通空格。
> fix: route appstore/update platform detection

- lib/routes/apple/appstore/update.js
APPstore的更新没有发布时间，在很多时候更新的发布时间还是很重要的，给接收方进行比对。
appstore lack the published time. For user, the time always is useful.
> feat: add pubDate in appstore update

- lib/routes/sexinsex/index.js
Condition 'false === result' is always false. The value of variable 'result' is originated from the return value of 'parseContent()' defined at line 22
> fix: remove a redundant if block

- lib/routes/universities/swust/cs.js
Value assigned to variable 'type' at this point is not used afterwards.
> fix: remove a redundant variable assignment

- lib/routes/douban/event/hot.js
fix #2754 
不管从网页里还是接口里都没找到发布时间，索性把字段删了 各个阅读器会把抓取时间定义成发布时间 虽然还有误差 但总比原来误差那么大好
> fix: remove douban event error pubDate

- lib/routes/novel/wenxuemi.js
`html()` method returns HTML Entities, which can't include chinese characters.
So I use `text()` instead.
> fix: conditional cache in wenxuemi router

- docs/other.md
- lib/router.js
- lib/routes/guokr/calendar.js
增加了物种日历订阅源。
尝试过 #2738 ，发现Mercury不能正确解析全文页，因此我自己实现了全文输出。
我不太清楚项目中的缓存机制，所以如果全文输出实现有误，还请指出。
> feat:果壳 物种日历

- lib/routes/twitter/utils.js
非常抱歉再次打扰 😂 没有 Twitter 开发者帐号所以无法跑一个 RSSHub 实例测试代码，一个 PR 能解决的事因为粗心变成了三个 PR
#2796 开的比较随便，没注意到其他地方也调用了 `formatText`，第二天发现弄出了一堆 `undefined`，吓得赶紧开了 #2803 修复
但是推文标题中的 `<br>` 还是没有去掉，再仔细看了看发现 `item.full_text` 之前已经被 `formatText` 过，里面没有 `\n` 只有 `<br>` 了，这个 PR 应该能真正解决问题了。
> fix: fix replacing logic in #2796

- docs/README.md
为了确保带锚点的链接结果不会因为后续 commit 改变，也可以在页面上[按`y`获得永久链接](https://help.github.com/en/articles/getting-permanent-links-to-files)：
<https://github.com/DIYgod/RSSHub-Radar/blob/d8fb35447588cf51f4b4e797c171f541ebe2573c/src/js/content/utils.js#L25>
> docs: fix url anchor

- lib/routes/github/starred_repos.js
修复当 GitHub 仓库 description 和 primary language 为 null 时的异常
> fix: 修复当仓库 description 和 primary language 为 null 时的异常

- Dockerfile.arm32v7
- Dockerfile.arm64
使用原来的dockerfile文件编译失败，发现dumb-init的存储库已经没了，于是直接改用基于alpine的node镜像来打包，安装更简单明了，而且发现最后打的镜像包的大小也减少了，因为我有个树莓派是基于64位系统的，于是顺便也添加了个arm64的。
> chore: 修改Dockerfile.arm32v7，添加Dockerfile.arm64

- lib/routes/3dm/news_center.js
```html
<li class="selectpost">
<a href="https://www.3dmgame.com/news/201910/3772636.html" target="_blank" class="img">
</a>
<div class="text">
<a href="https://www.3dmgame.com/news/201910/3772636.html" target="_blank" class="bt">丧子之母哭啸化身
《仁王2》新女妖“姑获鸟”介绍</a>
<div class="bq">
<a href="/news/26126/" target="_blank" class="a">仁王2</a>
<span class="time">2019-10-02 17:50:20</span>
</div>
<div class="miaoshu">
又到了光荣特库摩旗下动作游戏大作《仁王2》官方的每日挤牙膏时间。今（10月2日）日官方推特带来了妖怪“姑获鸟”的介绍，让我们来看看吧。《仁王2》姑获鸟：妖怪“姑获鸟”是由不能接受婴孩死亡的母亲变幻而来的存在，将头发四散成鸟翅一般飞翔，因此得名。这是一个非常棘手的敌人，其发出的刺耳绝叫会大幅削减气力。从配图中也可以看到，姑获鸟的头发变化成双翼，而四肢则全部爪化，具有和鸟类一样的关节构造。除了尖叫以外，锋利的爪击一定也会给玩家带来麻烦。仁王2》是由黑暗风格的战国动作动作游戏《仁王》的最新续作，背景是以日本战国时代末期为蓝本的世界。玩家需要回到烽火连天的战国时代，握紧屠刀斩断黑暗，讨伐无数被黑暗缠身的妖怪。《仁王2》将于11月1日至11月10日举行为期10天的Beta公测，所有玩家均能够参加，感兴趣的小伙伴们不妨留意
</div>
</div>
</li>
``` …
> fix: 修复3DM新闻的标题，添加了分类字段

- lib/routes/twitter/list.js
- lib/routes/twitter/utils.js
fix #3205 
twitter来源本身已支持在标题和内容中显示作者，只需打开即可。
但个人觉得这样子标题显得过于冗长，而使用普遍支持的author字段似乎没什么不好。
> feat: 推特列表时间线添加author字段

- lib/routes/kzfeed/topic.js
kzfeed 的 API 返回的 text 是带换行符的纯文本，如果只用 `<p>` 的话不是很易读，加上 `pre-line` 以后就好多了
> feat(routes/kzfeed): improve item description style

- lib/routes/zhihu/activities.js
1. 之前没有处理收藏夹。
2. api 提供了id，不需要从 url 间接获取。
> fix type:collection & get id directly

- lib/routes/douban/people/status.js
豆瓣给出的时间是 `2019-10-04 08:54:59` 格式，不含有时区信息，被 rss 阅读器抓取之后默认是标准时区。但是这个时间是默认的GMT+8，所以需要附带时区。
（还好豆瓣时间格式简单，不然 js 还真难处理时区，不知道会默认使用标准时区，还是本地时区。）
> fix: douban pubDate

- docs/new-media.md
- lib/routes/dockone/weekly.js
> fix: 去除Dockone标题中无效信息

- lib/routes/kzfeed/topic.js
* 在 `description` 里添加一个链接用于打开快知中间页
* 修复快知条目里的 a 标签
* 如果快知的条目里有图片的话要渲染图片
> feat: 优化快知的 feed 条目展示效果

- lib/routes/xueqiu/fund.js
@HenryQW 
**目前命中缓存的时候 RSS 结果会 undefined**
然后我顺便看了下 content cache 的代码，如果命中 cache 会继续给这个缓存增加缓存时间，那样的话极端情况如果在 cache 失效前一直被访问的话，这个 RSS 可能一直不会更新？要不然就干脆把这个脚本里 content cache 的逻辑删了，只依赖下 router cache 是不是问题也不是太大。
> fix: xueqiu fund cache issue

- lib/routes/x-mol/paper.js
当一篇文章预览没有相关图片时，图片id为空，图片获取失败于是报错，
增加图片存在判断。
> fix: X-mol 期刊 修复文章没有相关图片时报错的情况

- docs/university.md
因为`npm run format`自动移动 桂电部分docs时，插入的
`</Route>` 和 `## 哈尔滨工程大学`之间**没有空行**
导致## 标题失效
> fix: 哈尔滨工程大学 docs 标题

- docs/programming.md
- docs/study.md
- lib/router.js
- lib/routes/manong-weekly/issues.js
码农周刊：https://weekly.manong.io/issues/
由于【unable to verify the first certificate】问题（详见：https://github.com/DIYgod/RSSHub/issues/304 ），所以在请求时设置了 `rejectUnauthorized: false`
> feat: 添加码农周刊

- lib/routes/pork-price/index.js
现在 [/pork-price](https://rsshub.app/pork-price) 路由的 guid 都设置成了 `https://zhujia.zhuwang.cc/`，改为日期加名称
> fix: pork-price guid

- docs/university.md
- lib/router.js
- lib/routes/universities/upc/jsj.js
- lib/routes/universities/upc/main.js
具体添加内容包括：
1. 中国石油大学（华东）主页中的通知公告以及学术动态的信息抓取
2. 计算机科学与技术学院网站中的学院新闻、通知公告、学术关注和学工动态的信息的抓取
> feat: 添加中国石油大学（华东）的路由

- docs/university.md
- lib/router.js
- lib/routes/universities/bupt/news.js
主要改动：
1. 添加校园新闻RSS
2. 修改信息门户的来源，使其不需要登录
> feat: 增加北京邮电大学的路由

- lib/routes/kaiyan/index.js
> fix: 开眼RSS URL为空

- docs/anime.md
- docs/en/anime.md
- lib/router.js
- lib/routes/webtoons/naver.js
> feat: add naver webtoon

- docs/install/README.md
Telegram - 频道路由不再需要 Token, 仅贴纸包路由需要
> docs: 更新 Telegram 模块配置说明

- lib/routes/dribbble/keyword.js
- lib/routes/dribbble/popular.js
- lib/routes/dribbble/user.js
- lib/routes/dribbble/utils.js
Completely rewrite the Dribbble route, to better conform to standard practices and to fix some issues.
- rewrote to acquire data via HTML page using got, as recommended in the Join Us documentation.  Also reformatted to be structured like the jianshu example.
- fixed the `pubDate` for each item
- show the full-size media in each item
- better formatted the `author` for each item
> feat: Rewrite the Dribbble route.

- docs/en/new-media.md
- docs/new-media.md
- lib/router.js
- lib/routes/9to5/subsite.js
Added a new param `:tag` to provide optional tag support for 9to5 sites, e.g. `https://9to5mac.com/guides/aapl/`.
Changed param name `:type` to `:subsite` to prevent confusion.
> feat: Add tag support for 9to5

- lib/config.js
`export LISTEN_INADDR_ANY=0`  does not work as `0` is equal to false in node.  
Simply keeping it as string works, and it is later cast to integer in `index.js` anyway.
> fix: `LISTEN_INADDR_ANY` environment variable

- lib/routes/maoyan/upcoming.js
fix #3562 
cookie中_lxsdk_cuid等于任何长于两个字符的东西好像都行，不明白它的具体作用是什么，不过问题解决了。
另外还修复了名称上的错误。
> fix: maoyan upcoming

- lib/routes/github/pulls.js
The link to the PR list is: https://github.com/DIYgod/RSSHub/pulls
But the link to an individual PR is: https://github.com/DIYgod/RSSHub/pull/{PRnumber}
If the "s" is left, insted of redirecting to 
https://github.com/DIYgod/RSSHub/pull/1
it redirects to
https://github.com/DIYgod/RSSHub/pulls/1
> feat: Fix link in Github's PR

- docs/en/social-media.md
- docs/social-media.md
- lib/router.js
- lib/routes/twitter/user.js
close #3808 
路由改为 `/twitter/user/:id/:type?`
额外选项 `exclude_replies`去除回复，`exclude_rts`去除转推，`exclude_rts_replies`去除回复和转推，默认包含全部回复和转推。
不会影响原本的订阅。
> feat: twitter 回复和转推

- Dockerfile
Fix #3793
默认使用bash以支持带`.`的环境变量
> fix: switch default sh to bash

- lib/routes/bangumi/group/topic.js
描述文本拼写错误。回复的英文是reply，或者直接用中文'回复：'。
> fix: typo bangumi/group/topic.js

- lib/routes/discuz/discuz.js
- 增加对正文页面内容获取失败进行判断，防止获取失败导致路由故障
- 修复对UTF-8编码的正文内容获取失败
> fix: full text error in discuz

- lib/routes/nowcoder/discuss.js
close #3873
原路由`link` 使用正则匹配过滤，部分正确`link`不匹配正则表达式，导致空指针异常。
使用CSS选择器限定正确链接元素
> fix: error in nowcoder/discuss

- docs/en/parameter.md
- docs/parameter.md
- lib/middleware/parameter.js
- test/middleware/parameter.js
filter_case_sensitive 过滤是否区分大小写，filter 和 filterout 同时适用
默认为 true （即现状），区分大小写
举例 1: <https://rsshub.app/bilibili/user/coin/2267573?filter=diyGOD|RSShub&filter_case_sensitive=false>
> feat: add filter_case_sensitive url parameter

- lib/routes/hackerone/hacktivity.js
> fix: hackerone hacktivity replace null severity

- lib/routes/novel/axdzs.js
> fix: ignore the latest chapter when not updated

- docs/other.md
- lib/router.js
- lib/routes/coronavirus/sg-moh.js
This PR adds another 2019 coronavirus feed about Singapore's local situation.
> feat: add route coronavirus/sg-moh

- lib/routes/github/file.js
Fix #3962
https://github.com/DIYgod/RSSHub/commit/120d1ed38a6f36835191122b0a81e9641bba9983#diff-7bf72f9bacdd99e5af9323d22819a61aL14
> fix: restore github api querystring

- lib/routes/dsndsht23/index.js
close #3966 
- 修复分区参数错误
- 修改`css选择器`提升效率，原先切片20个文章链接，除去置顶与分割线后剩余约12个左右
PS: 单个页面含有30个文章，有需求可自行增加单次获取量
> fix: some bugs in 色花堂

- docs/university.md
- lib/router.js
- lib/routes/universities/thu/index.js
由于[清华信息门户](http://info.tsinghua.edu.cn/)屏蔽非校内网访问，因此使用了一个反向代理（见https://psmoe.com/474.html）。
[清华大学新闻网](https://news.tsinghua.edu.cn/)由于没有需求，暂时未加入。
> feat: add 清华大学

- docs/bbs.md
- docs/en/bbs.md
- docs/en/install/README.md
- docs/install/README.md
- lib/config.js
- lib/router.js
- lib/routes/discuz/discuz.js
根据 #4030 #1562 #4024 #3818 等需求，增加 `Cookie` 支持
使用方法：
1.  在环境变量中添加 `DISCUZ_COOKIE_{cid}`=`某论坛登录后的Cookie`, 其中`cid`可为任意数值，取值范围 [00, 99]
2.  使用路由`/discuz/:ver/:cid/:link` 通过指定`cid`来使用对应论坛的`Cookie`
已知问题：
不支持：https://www.hd.club.tw/
原因：魔改后的论坛，去除了一个关键定位标签，无法抓取到文章链接
> feat: add cookie support for discuz

- docs/other.md
- lib/router.js
- lib/routes/kuaidi100/index.js
- lib/routes/kuaidi100/supported_company.js
- lib/routes/kuaidi100/utils.js
📖 快递100 查询接口
基于 #2261 实现
交代几点事项：
- 缓存时间
- 公司列表：一个月
- 单个单号：4小时（错误查询结果也会缓存，避免反复且不必要的查询）
- 已经完成的单号：1年
- Cookie：5分钟/30次，达到即刷新，防止错误
Cookie 使用次数需要更多数据点，但是30次目测没有问题
尽管做了尽可能多的检查避免无用的查询，但是在使用的时候应当还是尽量小心，及时取消订阅
祝大家用的开心🎉
> feat: add kuaidi100

- lib/views/rss.art
There is a redundant `>` before `<channel>` tag
see https://rsshub.app/ximalaya/album/32820143/
> fix: remove redundant `>`

- lib/routes/universities/zju/cst/index.js
修复了浙江大学软件学院所有项目链接bug
修复前：
修复后：
这个fix或许可以解决「当前页面上的 RSS不显示」的问题。
> fix: 浙江大学软件学院项目链接bug

- docs/new-media.md
- docs/programming.md
- lib/router.js
- lib/routes/luogu/contest.js
- lib/routes/luogu/daily.js
- lib/routes/universities/thu/index.js
**fix: url does not exist in 清华大学**
解决清华新闻列表的不规范引发的Bug，在新闻缺少链接时会使用板块链接替代。
**add 洛谷近期比赛**
由于找不到[洛谷比赛页面](https://www.luogu.com.cn/contest/list)的解析方式故从[洛谷首页](https://www.luogu.com.cn/)获取最近比赛信息（我太菜了）
**fix: 洛谷日报**
将“洛谷”从“新媒体”移动至“编程”页面。
解决目前洛谷日报获取不到标题的问题。
将默认切换至2020年日报。
> fix: url does not exist in 清华大学 & feet: add 洛谷近期比赛 & fix: 洛谷日报

- lib/routes/dockerhub/build.js
> fix: docker hub get tag api directly

- lib/routes/agefans/detail.js
1. title typo: `ACG动漫` should be `AGE动漫`.
1. double slash: `$(item).attr('href')` already starts with slash.
> fix: agefans title typo and link double slash

- docs/en/install/README.md
Hi, this here fxes an 404 on the docs page to pm2
Thanks
> fix: 404 for pm2 docs

- lib/routes/novel/wenxuemi.js
The message, which hints the article is not ready, is like this:
```
看最快更新无错小说，请记住 https://www.wenxuemi6.com/！章节内容正在手打中，请稍等片刻，内容更新后，请重新刷新页面，即可获取最新更新！
```
The router check if there is a "正在手打中" in the first ten chars of text, so the check doesn't work as expected.
I remove the `slice` to fix the problem.
> fix: wenxuemi remove slice for cache check

- lib/routes/universities/tjpyu/ooa.js
I forgot to change the trouble shooting URL to this github repo's issues URL before, and sometimes rsshub can not response the request from my feedom client in time, it lists baidu's URL and looks very strange...
> fix: route to github website instead of baidu when error

- lib/routes/ximalaya/album.js
- lib/views/rss.art
支持提交到 itunes podcast 审核，需要再添加这两个标签
其中 itunes_explicit 标记内容是 true 则是露骨成人内容，如果是 clean 或者 false 则代表清洁版
参考地址：
https://rfwilmut.net/notes/itunestags.html
> feat: Support itunes_category and itunes_explicit

- docs/social-media.md
- lib/router.js
- lib/routes/douban/book/rank.js
> **docs**: https://docs.rsshub.app/social-media.html#re-men-tu-shu-pai-hang
允许将虚构类 `/douban/book/rank/fiction` 与非虚构类 `/douban/book/rank/nonfiction` 合并到一个路由 `/douban/book/rank`，方便同时关注两类热门图书排行的读者订阅。
> feat: 改进豆瓣热门图书排行路由

- lib/routes/tencent/wechat/ce.js
- lib/routes/tencent/wechat/csm.js
这两个微信公众号的路由中，`<img>`的`src`属性都没有给出图像的真实URI。
- 公众号路由（传送门来源）图像的真实URI储存在`<img>`标签的`data-original`属性中，并且需要将传送门的域名更换为腾讯域名；
- 公众号路由（CareerEngine来源）图像的真实URI储存在`<img>`标签的`data-src`属性中。
> fix: 修正微信公众号路由（传送门来源以及CareerEngine来源）中的图片链接

- docs/game.md
- lib/routes/mihoyo/bh3.js
崩坏3作战资讯 [原网址](https://www.bh3.com/index.php/news) 更换为 [新网址](https://www.bh3.com/news)（原网址访问404）且原五个类目有小改动：
* 最新 /latest
* 新闻 /news -> 动态
* 公告 /notice
* 活动 /activity
* 攻略 /strategy -> 补给
原路由暂不改动，仅在文档中更新公告种类。
> fix: 崩坏3游戏公告

- lib/routes/universities/swust/cs.js
- lib/routes/universities/swust/helper.js
- lib/routes/universities/swust/jwc_news.js
- lib/routes/universities/swust/jwc_notice.js
外网访问学校的页面时会有一个中转网页做跳转，但是是使用 `meta` 标签让浏览器跳转。
利用 got 的 `afterResponse` 模拟了解析 `meta` 标签。
> feat(swust): follow meta redirect

- lib/routes/tencent/wechat/wemp.js
> fix: wemp 一次抓取过多文章导致超时

- docs/install/README.md
- lib/config.js
- lib/utils/request-wrapper.js
- package.json
- test/utils/request-wrapper.js
- yarn.lock
支持 URI 格式的代理设置。
* 通过环境变量 `PROXY_URI` 设置代理
examples:
- `PROXY_URI=http://localhost:8080`
- `PROXY_URI=http://username:pwd@localhost:8080`
- `PROXY_URI=socks5://localhost:1080`
- `PROXY_URI=socks5://username:pwd@localhost:1080`
* 此代理设置方式支持了 SOCKS 代理认证
* 未破坏原有代理设置方式的兼容性
> feat: Support Proxy URI

- lib/middleware/debug.js
- lib/middleware/onerror.js
- test/middleware/debug.js
resolve: https://github.com/DIYgod/RSSHub/issues/4672
> fix: only collect errors which route path was matched

- .github/workflows/docker-release.yml
- .github/workflows/docker-test.yml
The version input will not be supported after May 30, 2020. Use buildx-version instead.
> chore: update buildx version input

- docs/en/social-media.md
- docs/social-media.md
- lib/routes/twitter/keyword.js
resolve: #4670 
Twit 库本身会对URI编码一次，所以这里重复编码了
> fix: twitter advanced search by duplicate encode

- lib/utils/request-wrapper.js
resolve: #4655 
resolve: #4631 
302、301 转发的时候 由于headers里定义了host导致最终请求的时候以原始host请求，加上 Got 库并没有对此做处理导致请求部分网站时会无限跳转，就是目前发现以上的两个issues
正常情况下 host 都不应该被主动定义在headers里
@DIYgod  这里定义referer 和 host 是有什么特别的原因吗？
> fix: host in headers after redirecting request

- lib/routes/konachan/post_popular_recent.js
Fix "Error: `input` must not start with a slash when using `prefixUrl`"
> fix: fix konachan rss

- assets/radar-rules.js
- lib/routes/lofter/posts.js
- show lofter user title
- add radar rule for lofter tag
The rule for lofter user (e.g., `tingtingtingtingzhi.lofter.com`) is ignored since RSSHub Radar doesn't support wildcard subdomain.
> fix: show lofter user title

- docs/install/README.md
The documentation of PM2 had moved to a new location.
> docs: update the link of PM2 docs

- lib/routes/hackerone/hacktivity.js
当提交者用户名为空时，目前的程序会报错
本 PR 修改用户名为空时（参考 https://hackerone.com/reports/891267 ）显示 `Someone`
> fix: hackerone hacktivity fix username empty

- docs/new-media.md
- lib/router.js
- lib/routes/tencent/wechat/wjdn.js
- lib/routes/waijiedanao/wechat.js
目前的外接大脑rss只支持根据文章种类获取内容，修改之后，rss允许根据id获得不同公众号内容
> feat: 添加外接大脑作为获取公众号途径

- lib/routes/weibo/utils.js
当微博存在超话链接和外部链接时，链接之间的内容会缺少。
例子：
```html
<a  href="https://m.weibo.cn/p/index?containerid=100808054f524244becd4ba886e3fd3ebaf410&extparam=Fate%2FGrandOrder&luicode=10000011&lfid=1076033489213692" data-hide=""><span class='url-icon'><img style='width: 1rem;height: 1rem' src='https://h5.sinaimg.cn/upload/100/959/2020/05/09/timeline_card_small_super_default.png'></span><span class="surl-text">Fate/GrandOrder超话</span></a>丢失的内容<a data-url="http://t.cn/A6Ljb9zZ" href="https://t.co/PcprFYuoRY?luicode=10000011&lfid=1076032401250425&u=https%3A%2F%2Ft.co%2FPcprFYuoRY" data-hide=""><span class='url-icon'><img style='width: 1rem;height: 1rem' src='//h5.sinaimg.cn/upload/2015/09/25/3/timeline_card_small_web_default.png'></span><span class="surl-text">网页链接</span></a>
```
> fix: weibo 内容缺失

- docs/install/README.md
- lib/config.js
- lib/routes/initium/full.js
See #5047 .
暂时以用户手动提供自己的token的方式来解决登陆故障的问题。~~登陆故障我不大会修，所以原issue暂时还关不了~~
其实这样也挺好的，毕竟端有5台的登陆token数限制，因此和本地共用不失为帮助用户节省限额的一个良方。
顺带修正`install/README.md`里的一处段落位置错乱。
> fix: set initium's bearer token manually (#5047)

- docs/other.md
- lib/router.js
- lib/routes/amazfitwatchfaces/fresh.js
- lib/routes/amazfitwatchfaces/search.js
- lib/routes/amazfitwatchfaces/top.js
- lib/routes/amazfitwatchfaces/updated.js
- lib/routes/amazfitwatchfaces/utils.js
> feat: add Amazfit Watch Faces

- lib/routes/leboncoin/ad.js
Previously only "department and near" [1] search location selector was supported.
This PR introduces support of "department" [2] selector.
[1] https://www.leboncoin.fr/recherche/?category=19&text=table&locations=dn_83
RSSHub route : `/leboncoin/ad/category=19&text=table&locations=dn_83`
[2] https://www.leboncoin.fr/recherche/?category=19&text=table&locations=d_83
RSSHub route : `/leboncoin/ad/category=19&text=table&locations=d_83`
> feat: support department location selector in leboncoin

- docs/government.md
- lib/router.js
- lib/routes/gov/nppa/channels.js
- lib/routes/gov/nppa/contents.js
- lib/routes/gov/sapprft/7026.js
添加国家新闻出版署
原国家新闻出版广电总局(www.sapprft.gov.cn)停用并预备下线
> feat: add nppa

- docs/en/traditional-media.md
- docs/traditional-media.md
- lib/router.js
- lib/routes/scmp/index.js
Scmp dynamically loads articles. Article content is stored in the HTML from the very beginning as Apollo state. But I don't figure out a convinient way to restore that back to HTML. So it has to use puppeteer.
To optimize performance, the followings are applied:
* Loads mobile page instead of the desktop version
* Prohibits images and webfonts from loading
* Introduces PuppeteerBlocker to block ads
* Switches to offline mode as long as the Apollo state is loaded
> feat: scmp

- lib/routes/un/scveto.js
For example: `14-15 March 2020` from the page results in a wrong date.
> fix: special date handling

- lib/routes/bilibili/dynamic.js
Fix #5062 
Use field `dynamic` instead of `desc` to get the content of a user's dynamic.
> fix: bilibili dynamic, close #5062

- lib/routes/bilibili/dynamic.js
Fix issue #5306 
`item.cover` could be JSON object after Bilibili add short video support in user's post content. Fix a bug that could result in feed exceptions when user's post contains a short video. RSSHub feed now can display video content if user uploads short video in his post.
> Add short video support for Bilibili user posts

- assets/radar-rules.js
#5298 Patch: Radar 规则路径生成缺少 `%2F`
匹配 `/:type/:key/:morekey` 当 `type` 为 `tag` 时 `key` `morekey` 拼接时中间需要 `%2F` ，其余规则正常。
`/onejav/tag/`
- https://onejav.com/tag/3D
预期返回 `/onejav/tag/3D`
- https://onejav.com/tag/Hospital%20/%20Clinic
预期返回 `/onejav/tag/Hospital%20%2F%20Clinic`
- https://onejav.com/2020/07/30
预期返回 `/onejav/day/20200730`
> fix: OneJAV Radar path (#5298 Patch)

- lib/router.js
- lib/routes/engadget/home.js
- Add RSS Language Tag for Engadget;
- Allow empty language argument in Engadget path, which is handled in `lib/routes/engadget/home.js` at line 6 but is not allowed in libs/router.js
- At line 6 in `lib/routes/engadget/home.js`, empty `ctx.params.lang` is accepted and deemed as `cn`. 
```javascript
const lang = ctx.params.lang === 'us' ? 'www' : ctx.params.lang || 'cn';
```
- However, in `lib/router.js`, we do not have a corresponding rule to handle empty language argument.  At line 2061:
```javascript
// engadget中国版
router.get('/engadget-cn', require('./routes/engadget/home'));
// engadget
router.get('/engadget/:lang', require('./routes/engadget/home'));
```
None
`/engadget/:language` -> `/engadget/:language?`
> fix: RSS Language Tag for Engadget

- docs/government.md
- lib/router.js
- lib/routes/gov/moa/sjzxfb.js
#5260
没办法把路由放在在同一 `/moa` 下，因为原本的` 新闻` 路由覆盖掉了所有的子目录，因为不会搞所以另开了路由……等一个有缘人看看能不能帮忙改到同一路由下。
> feat:add 中华人民共和国农业农村部-数据-最新发布

- lib/routes/initium/full.js
通过伪装Google Bot不付费获得全文
原路由功能不变
close #5376
> feat: 端传媒全文获取

- lib/routes/mastodon/account_id.js
- lib/routes/mastodon/acct.js
- lib/routes/mastodon/timeline.js
- lib/routes/mastodon/utils.js
涉及到的路由及测试地址：
- `/mastodon/acct/:acct/statuses/:only_media?` （此路由需配置 API）
- ([profile(toots)](https://mastodon.social/@meina)) `/mastodon/acct/meina@mastodon.social/statuses`
- ([profile(media)](https://mastodon.social/@meina/media)) `/mastodon/acct/meina@mastodon.social/statuses/only_media`
- `/mastodon/account_id/:site/:account_id/statuses/:only_media?`
- ([profile(toots)](https://mastodon.social/@meina)) https://rsshub-git-fork-notofoe-mastodon-format.diy.vercel.app/mastodon/account_id/mastodon.online/10037/statuses 
- ([profile(media)](https://mastodon.social/@meina/media)) https://rsshub-git-fork-notofoe-mastodon-format.diy.vercel.app/mastodon/account_id/mastodon.online/10037/statuses/only_media
-----
- `/mastodon/timeline/:site/:only_media?`
- …
> refactor: mastodon

- lib/routes/mastodon/utils.js
N/A
涉及到的路由及测试地址：
- `/mastodon/acct/:acct/statuses/:only_media?`
- `/mastodon/account_id/:site/:account_id/statuses/:only_media?`
- \[[profile 1(media)](https://mastodon.online/@Akillusion/media)\] `/mastodon/account_id/mastodon.online/62270/statuses/only_media`
- \[[profile 2(media)](https://pawoo.net/@torot/media)\] `/mastodon/account_id/mastodon.online/33105/statuses/only_media`
- `/mastodon/timeline/:site/:only_media?`
- `/mastodon/timeline/pawoo.net/only_media`
- `/mastodon/remote/:site/:only_media?`
- `/mastodon/remote/pawoo.net/only_media`
> fix: mastodon broken local image

- lib/router.js
> fix: 福建新闻路由参数

- lib/routes/tencent/wechat/csm.js
修正搜狗搜索图片路径为真实的微信公众号路径
无
https://rsshub.app/wechat/csm/FeZaoDuKe
> fix: (tencent/wechat/csm)图片路径

- lib/routes/adnmb/index.js
https://adnmb2.com has been DNS poisoned [since August 2020](https://en.greatfire.org/https/adnmb2.com).
- `/adnmb/:pid`
- `/adnmb/-1`
- `/adnmb/欢乐恶搞`
> fix: change adnmb domain to adnmb3.com

- assets/radar-rules.js
- docs/blog.md
- docs/reading.md
- lib/router.js
- lib/routes/blogs/jianning.js
> feat: add jian-ning blog

- lib/routes/bbc/utils.js
fix: bbc chinese has no full text.
```
http://127.0.0.1:1200/bbc/chinese
http://127.0.0.1:1200/bbc/traditionalchinese
```
> fix: bbc chinese changed it's structure

- lib/routes/github/follower.js
- lib/routes/github/pulls.js
- lib/routes/github/search.js
- lib/routes/github/star.js
- lib/routes/github/starred_repos.js
- lib/routes/github/trending.js
- lib/routes/gitlab/explore.js
Missing author field in few github routes and gitlab explore route. For stars and followers, I figure adding interactor as the author would be suitable. Let me know if there is any problem.
Changed Routes: 
https://rsshub.app/github/search/RSSHub/bestmatch/desc
https://rsshub.app/github/starred_repos/DIYgod
https://rsshub.app/github/pull/DIYgod/RSSHub
https://rsshub.app/github/user/followers/HenryQW
https://rsshub.app/github/stars/DIYGod/RSSHub
https://rsshub.app/gitlab/explore/trending
> fix: add missing author field in github and gitlab routes.

- docs/traditional-media.md
- lib/router.js
- lib/routes/initium/full.js
9月29日，theinitium.com 网站升级改版，接口相应从v1升级至v2。从这两天开始，~~新的文章似乎已经不再给v1的接口同步推送；因此需要紧急先修一下~~ 啊不，不是旧接口停用，而是似乎今后更新的深度文章都不再使用feature频道了，因此至少要修改一下默认路由使用feature的逻辑。
新的接口有很多新feature，比如增加了作者信息的数据结构，读者可以对自己需要作者自主订阅，在这边也能实现 ~~（然而拖延症+js苦手导致拖到现在还没弄好）~~ 。但是文章不更新了这个比较要命，所以需要赶紧先上再说【
> fix: 端传媒网站接口升级

- lib/routes/telegram/channel.js
`/telegram/channel/:username`
试用泛用型播客客户端订阅路由：
- `/telegram/channel/notobjective`
> feat: telegram channel audio & podcast support

- lib/routes/douban/book/rank.js
路由 `/douban/book/rank` 接口有变化，导致原路由失效。
> fix: broken route /douban/book/rank

- docs/install/README.md
- lib/config.js
- lib/routes/initium/full.js
Close #
/initium/*
说明：新增一个新的环境变量 `INITIUM_IAP_RECEIPT` 用于 iOS 内购付费情况。测试通过可用并更新了说明文档。
> feat: 端传媒 iOS IAP 内购凭证

- docs/university.md
- lib/router.js
- lib/routes/universities/shu/index.js
- lib/routes/universities/shu/jwc.js
1. 修复了上海大学教务处获取的错误
2. 增加了上海大学官网 (www.shu.edu.cn) 的三个信息栏目
3. 文档路由地址更新
Close #
`/shu/:type` (新增)
其中`:type`可以为`news`, `research`, `notice`
`/shu/jwc/:type` (修复)
其中`:type`可以为`news`, `notice`
> feat: 上海大学相关

- docs/install/README.md
- lib/config.js
- lib/routes/pixiv/api/getBookmarks.js
- lib/routes/pixiv/api/getIllustFollows.js
- lib/routes/pixiv/api/getIllusts.js
- lib/routes/pixiv/api/getRanking.js
- lib/routes/pixiv/api/getUserDetail.js
- lib/routes/pixiv/api/searchIllust.js
- lib/routes/pixiv/api/searchPopularIllust.js
- lib/routes/pixiv/pixiv-got.js
- lib/routes/pixiv/token.js
- package.json
- yarn.lock
It's a workaround for DIYgod/RSSHub#5916
/pixiv/*
It uses 2 environment variables:
* PIXIV_BYPASS_CDN: Whether to enable CDN bypassing, defaults to false.
* PIXIV_BYPASS_HOSTNAME: A hostname or an IP address indicating Pixiv gateway server ip, defaults to `public-api.secure.pixiv.net`.
Credit: https://github.com/upbit/pixivpy/commit/bcceffc7e1ba73be300ceb339b59b0e84290dae3
> feat: bypass Pixiv Cloudflare by directly accessing Pixiv gateway server IP

- Dockerfile
This image is built from the official Debian image as upstream, so there
is no need to do apt-get clean manually.
Ref:
- https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#apt-get
> Official Debian and Ubuntu images automatically run apt-get clean, so
> explicit invocation is not required.
> chore: remove unnecessary apt-get clean in Dockerfile

- docs/en/install/README.md
- docs/install/README.md
A `NODE_ENV` configuration is used to control displaying error
messages. #5982
Close #5982
> docs: add `NODE_ENV` to the deployment docs

- lib/routes/coolapk/utils.js
> fix: keep coolapk sharekey in url

- lib/routes/twitter/keyword.js
> fix: allow empty in twitter keyword

- docs/en/traditional-media.md
The English doc had tag `<Route>` which is an error.
/wsj/:lang/:category
e.g.
/wsj/en-us/opinion
> fix: wsj english doc's tag

- lib/routes/weibo/keyword.js
解决了[该 PR 下的评论](https://github.com/DIYgod/RSSHub/commit/e44064d40db32468415cda9bf2e535b99028ab90#commitcomment-43772031)提出的问题，添加了 `/weibo/keyword` 路由下的作者信息
`/weibo/keyword/%E8%BD%AC%E5%8F%91`
> fix: weibo keyword: add author metainfo

- docs/social-media.md
- lib/routes/weibo/keyword.js
解决了[该 PR 下的评论](https://github.com/DIYgod/RSSHub/commit/e44064d40db32468415cda9bf2e535b99028ab90#commitcomment-43772031)提出的问题，用户提供的 `showAuthorInTitle` 和 `showAuthorInDesc` 应能覆盖默认值而非反过来
`/weibo/keyword/%E8%BD%AC%E5%8F%91/readable=1&authorNameBold=1&showAuthorAvatarInDesc=1&showEmojiForRetweet=1&showRetweetTextInTitle=0&addLinkForPics=1&showTimestampInDescription=1&showTimestampInDescription=1&heightOfPics=150`
`/weibo/keyword/%E8%BD%AC%E5%8F%91/readable=1&authorNameBold=1&showAuthorInTitle=0&showAuthorInDesc=0&showAuthorAvatarInDesc=1&showEmojiForRetweet=1&showRetweetTextInTitle=0&addLinkForPics=1&showTimestampInDescription=1&showTimestampInDescription=1&heightOfPics=150`
`/weibo/keyword/%E8%BD%AC%E5%8F%91/readable=1&authorNameBold=1&showAuthorInTitle=0&showAuthorInDesc=0&showAuthorAvatarIn …
> fix: weibo keyword: default showAuthorInTitle & showAuthorInDesc should not override routeParams

- lib/routes/github/issue.js
- lib/routes/github/pulls.js
(no issue)
I subscribe to this feed: https://rsshub.app/github/issue/Microsoft/TypeScript/all/Design%20Notes
The URLs for related issues come out looking like this:
This change will turn them into clickable links (as they are on GitHub).
After: (https://rsshub-git-linkify-github.diy.vercel.app/github/issue/Microsoft/TypeScript/all/Design%20Notes)
> feat: linkify GitHub markdown

- lib/middleware/parameter.js
Hello,
In the file parameter.js, the variable `isFilter` is being assigned to `true` on various occasions. On 2 of these occasions, it is then immediately reassigned in the form of:
`isFilter = isFilter && ...`
Since isFilter is `true` at the time of the reassignments, the AND-operation can be removed and the reassignments replaced with the second operand.
---
Not applicable.
Not applicable.
为方便测试，请附上完整路由地址，包括所有必选与可选参数，否则将导致 PR 被关闭。
To simplify the testing workflow, please include the complete route, with all required and optional parameters, otherwise your pull request will be closed.
Not applicable.
----
Kind regards,
Florian
> refactor: update isFilter in parameter.js

- docs/live.md
- lib/router.js
- lib/routes/heibaizhibo/room.js
Close #6092 
/heibaizhibo/room/205173
/heibaizhibo/room/13984
> feat: add heibaizhibo.com

- docs/new-media.md
- lib/routes/netease/dy.js
无
- 相关代码中向 `ctx.cache` 中存了一个 `Buffer`，导致之后取出时出错；此处将其按 GBK 解码为字符串后再存入缓存
- 修复了全文 CSS 选择器
- 更新了文档中网易 ID 的获取办法
`/netease/dy/W1966190042455428950`
> fix: 网易号获取缓存出错 & 修复全文 CSS 选择器

- lib/routes/clickme/index.js
中文参数被误编码
https://rsshub.app/clickme/default/tag/%E6%AD%A3%E5%A6%B9
https://rsshub-git-fix-clickme-subtype.diy.vercel.app/clickme/default/tag/%E6%AD%A3%E5%A6%B9
> fix: remove unnecessary URIEncoding from clickme route

- lib/routes/facebook/page.js
無
`facebook/page/ykohmk` (p.s 幾乎每個貼文都有圖片，debug 起來比較方便)
修復前
修復後
> fix: facebook page attach cover image

- lib/routes/facebook/page.js
無
`/facebook/page/FGOwarehouse`
`/facebook/page/ykohmk`
原先使用 `content.text()` 的方法，只顯示需要的 html，但裡面連結時就不好做 parse，索性把全部 html 結構放出
> feat: facebook html content

- lib/routes/ncm/artist.js
- lib/routes/ncm/playlist.js
此前网易云歌单只返回前六七首甚至两三首歌曲，现在修复这一问题。
同时修复了歌手专辑路由的pubDate缺失 ~~导致部分RSS Parser不能正常工作~~ 的问题
Close #
`/ncm/playlist/*` 及 `/ncm/artist/*`
> fix: 网易云歌单曲目过少 & 歌手专辑更新日期错误

- lib/routes/gcores/category.js
> fix: 修复机核文章中多图没有显示的问题

- assets/radar-rules.js
> fix: mobile subdomain for ximalaya and zhaishuyuan

- lib/routes/instagram/index.js
The epoch time (in miliseconds) wasn't multiplied by 1000 (to seconds). So it always became in 1970.
`/instagram/user/ladygaga`
> fix: instagram timestamp

- lib/routes/xiaoyuzhou/pickup.js
Fixes #6356.
`/xiaoyuzhou`
想明白了为什么这个路由会有缓存问题。一般来说用于缓存的 `(Key, Value)` 应该是固定的，但是目前的设计是使用固定的 Key，Value 会固定在每天零点更新。其他类似的路由一般都储存的是 `(item_link, content)`，不会有 stale cache 的问题。
有两种设计思路：
1. 每天使用不同的 Key，如`xiaoyuzhou_items_20201215`
2. 使用固定的 Key，取回 Value 时如果发现过期则手动刷新缓存。
二者的时间复杂度和实现难度、可读性都差不多，这次 PR 采用的是第二种。同时修复了输出的时区不正确的问题，增加了编辑推荐的评论。
> fix: 修复「小宇宙 - 发现」缓存

- lib/middleware/header.js
使用 Safari 打开任意地址，如https://rsshub.app/github/repos/DIYgod ，原本 RSS 连接会被提示跳转到 Apple News，现在与 Chrome 保持一致，直接可以浏览 XML
https://discussions.apple.com/thread/251925510
> feat: 支持在 Safari 中直接浏览 XML 格式的 RSS

- lib/middleware/template.js
使用 Reeder for mac 时，输入**本地订阅地址** http://localhost:1200/amazon/ku/next 时不添加协议结尾，Reeder 会自动添加 `.com`，导致无法订阅。
> feat: better Reeder support

- docs/en/picture.md
- docs/picture.md
- lib/middleware/template.js
- lib/router.js
- lib/routes/dailyart/index.js
route: /dailyart/:language?
example: /dailyart/zh
- language: optional, indicating the text language. Languages supported include en, es, fr, de, it, zh, jp, etc. English by default.
> feat: added DailyArt & fix: error occurred when without user-agent

- lib/routes/pixiv/bookmarks.js
- lib/routes/pixiv/illustfollow.js
- lib/routes/pixiv/ranking.js
- lib/routes/pixiv/search.js
- lib/routes/pixiv/user.js
[https://rsshub-qf259m6en.vercel.app/pixiv/user/bookmarks/15288095](https://rsshub-qf259m6en.vercel.app/pixiv/user/bookmarks/15288095)
[https://rsshub-qf259m6en.vercel.app/pixiv/user/11](https://rsshub-qf259m6en.vercel.app/pixiv/user/11)
[https://rsshub-qf259m6en.vercel.app/pixiv/ranking/week](https://rsshub-qf259m6en.vercel.app/pixiv/ranking/week)
[https://rsshub-qf259m6en.vercel.app/pixiv/search/麻衣/popular/2](https://rsshub-qf259m6en.vercel.app/pixiv/search/麻衣/popular/2)
[https://rsshub-qf259m6en.vercel.app/pixiv/user/illustfollows](https://rsshub-qf259m6en.vercel.app/pixiv/user/illustfollows)
> fix: use the new version of pixiv link

- docs/en/install/README.md
- docs/install/README.md
- lib/config.js
Changed default debugInfo config to false to avoid potential privacy leakage.
RSSHub displays client IP within debug information when debugInfo is set to true, and since all pull request will be automatically deployed with Vercel, anyone, including contributors, who uses the deployment for any purpose would passively disclose their IP addresses to the instance in public. As per the principle of least privilege, therefore, users should not be granted the access to the information by default. Instead, this configuration should be manually changed for debugging purposes where needed.
> fix: disable default debug info

- docs/en/install/README.md
- docs/install/README.md
- scripts/ansible/.gitignore
- scripts/ansible/README.md
- scripts/ansible/Vagrantfile
- scripts/ansible/rsshub.Caddyfile
- scripts/ansible/rsshub.env
- scripts/ansible/rsshub.service
- scripts/ansible/rsshub.yaml
- scripts/ansible/try.sh
This PR adds instructions on how to use [an Ansible playbook](https://github.com/k-t-corp/RSSHub-ansible) that I wrote to deploy RSSHub on bare-metal with Redis, browserless and Caddy 2
Close #
> Add ansible deployment

- lib/routes/caixin/article.js
None
/caixin/article
Although most of the articles are not free, the free part of each article is still informative. I'd like to have it in the RSS. If people don't like it, I can add a switch and return without the text by default.
> feat: add fulltext to the article route of caixin

- docs/live.md
修正 哔哩哔哩直播分区不存在导致的文档示例api不可用的问题
/bilibili/live/area/:areaID/:order
/bilibili/live/area/207/online
> 修正 文档:live.md

- docs/reading.md
在 78829dfe6367ba6ec5b30585d5d0e81c98b69fc9 删除，在 61009b2efee276698bfa9f17067495b1e3946097 被意外添加回来
> docs: delete guanzhi

- lib/routes/instagram/index.js
```
NOROUTE
```
修复使用`path.join`导致的BUG
`path.join`会将`://`替换为`:\`，从而导致生成的URL不是有效的URL。
> [Instagram] 修复使用path.join导致的URL不正确的BUG

- docs/en/social-media.md
- docs/social-media.md
```routes
NOROUTE
```
Instagram 有非常严格的反爬限制，服务器IP访问很有可能会直接取得HTTP 429。
> [Instagram]增加严格反爬标记

- lib/routes/pixiv/pixiv-got.js
Close #6584
```routes
NOROUTE
```
修复了同时使用`PROXY_URI`和`PIXIV_BYPASS_CDN`导致#6141, #6584中的问题，
#6141中的
>(node:7356) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. 
警告是由于使用socks代理时， socks-proxy-agent 会将 `tls.connect(options)` 的 `options.servername` …
> fix: add custom certificate validation to pixiv-got

- lib/routes/ixigua/userVideo.js
Close #7247
```routes
/ixigua/user/video/382219740527758
```
构建预览 https://rsshub-do-not-use-git-fork-yunyu950908-yunyu950908-patch-2-diy.vercel.app/ixigua/user/video/382219740527758
西瓜视频 API 更新.
```curl
curl --location --request GET 'https://www.ixigua.com/api/videov2/author/new_video_list?to_user_id=67676281639&offset=0&limit=2&orde …
```
> fix: userVideo.js ixigua api

- lib/routes/bilibili/video.js
Close #7404
```routes
/bilibili/user/video/240788688
```
看起来是b站的api有变化了，不清楚以前是怎样的，现在pic给的就是完整链接
> fix(route): bilibili video pic

- docs/en/picture.md
- docs/new-media.md
- docs/picture.md
- lib/router.js
- lib/routes/tencent/wechat/feeds.js
无
```routes
/wechat/feeds/MzIwMzAwMzQxNw==
```
> feat(route): 微信公众号新增 wechat-feeds 来源

- docs/picture.md
- lib/routes/jandan/pic.js
Close #
```routes
/jandan/girl
```
跟随煎蛋版面修改，增加了女装路由并完善了文档中的对应部分
> feat(route): jandan add 煎蛋女装图

- lib/routes/nytimes/index.js
- lib/routes/nytimes/morning_post.js
- lib/routes/nytimes/utils.js
fix morning post url, using official rss
#7442 #7418 
Close #
```routes
/nytimes
/nytimes/en
/nytimes/dual
/nytimes/dual-traditionalchinese
/nytimes/traditionalchinese
```
`got` 所获取的数据中，只有封面图片能获取到 src，其他图片都是无法获取到对应的 src 的，若使用旧的方式获取数据，会出现很多图片无法显示的问题
> fix(route): nytimes

- docs/reading.md
- lib/router.js
- lib/routes/tongli/news.js
Close #
```routes
/tongli/news/2
/tongli/news/6
/tongli/news/0
```
- x] 如果全文获取中需要访问文章链接, 是否使用了缓存? If fulltext requires to fetch detail pages, is cache used in the process?
> feat(route): add 东立出版

- lib/router.js
Fix #8009
```routes
/
/test/1145141919
```
Do not `require` any route handler on the cold start and only `require` when there is a coming request, which can improve the performance of the RSSHub cold start for *A LOT*.
> DO NOT MERGE. This change could break `@vercel/nft`. Tests needed.
> feat(route): load route handler on the first request

- lib/routes/zimuxia/portfolio.js
好像是cheerio的api发生了变化？`$.reverse()` 被移除了
```routes
/zimuxia/portfolio/假如marvel
```
> fix(zimuxia-portfollo): `$.reverse` is removed

- docs/traditional-media.md
- lib/router.js
- lib/routes/hket/index.js
Close #
```routes
/hket
/hket/sran001
/hket/sran008
/hket/sran010
/hket/sran011
/hket/srac002
/hket/srat006
```
> feat(route): add hket

- lib/middleware/cache.js
- lib/middleware/parameter.js
- lib/utils/request-wrapper.js
```routes
NOROUTE
```
Only require proxyagent, `ioredis` when explicitly enabled in the config, and only require `mecuri_parser` on the first `fulltext` mode request. This improve RSSHub cold start performance by another 35%.
> perf: lazy require dependencies

- lib/routes/hket/index.js
Close #
```routes
/hket
/hket/sran001
/hket/sran008
/hket/sran010
/hket/sran011
/hket/srac002
/hket/srat006
```
Fix 
```bash
...Missing url property...
```
in https://github.com/DIYgod/RSSHub/pull/8050
> fix(route): hket Missing `url` property

- docs/en/install/README.md
- docs/install/README.md
- lib/routes/mail/imap.js
Close #8064 
```routes
/mail/imap/:email
```
将环境变量命名中出现的 `.` 都替换成 `_`，避免 docker-compose 部署时无法获取环境变量。
本地测试通过。
> fix(route): 修复IMAP邮箱环境变量命名

- lib/routes/novel/ptwxz.js
No reletaed issue
```routes
/novel/ptwxz
```
- [] Use Cache: not sure
* original route does not show full text for each link/new chapter
* now it will return the latest 9 chapters of a novel
* use async and cheerio to get content
* inspired by [biquge.js](https://github.com/DIYgod/RSSHub/blob/436197e685bf746c320ecee9c70118db0e83ed30/lib/routes/novel/biquge.js)
> fix(route)(ptwxz): ptwxz add fulltext

- lib/routes/infzm/news.js
Close #
```routes
/infzm/5
```
This commit fixed the previously unhandled timezone issue.
> fix: infzm timezone

- lib/routes/caixin/latest.js
Close #
```routes
/caixin/latest
```
> fix: exclude datanews to prevent `pubDate` error (`/caixin/latest`)

- docs/university.md
- lib/router.js
- lib/routes/universities/scut/jwc/school.js
Close #
```routes
/scut/jwc/school
/scut/jwc/school/all
/scut/jwc/school/course
/scut/jwc/school/exam
/scut/jwc/school/info
```
与 `/scut/jwc/notice` 基本相同，只是修改了一些参数
境外访问被限制，自动测试可能不能通过。
> feat(route): add 华南理工大学教务处学院通知

- lib/routes/yuzu-emu/entry.js
Close #8107
```routes
/yuzu-emu/entry
```
> fix(route): incorrect source links in yuzu emulator

- lib/routes/initium/full.js
#6795
```routes
/initium/latest/zh-hans
```
不过解析出来的时间似乎本身就有一些问题，比如 https://theinitium.com/article/20210901-opinion-govern-fanquan/ 这一篇解析出来的时间是 "datePublished" datetime="2021-09-01T18:57:00+08:00"
> fix(route): migrate initium routes to new timezone

- docs/en/other.md
- docs/other.md
- lib/router.js
- lib/routes/coronavirus/yahoo-japan.js
新增 Yahoo 日本疫情新闻整合
```routes
/coronavirus/yahoo-japan/:tdfk?
```
> feat(route): add yahoo japan covid19 news collection 日本疫情消息汇总

- lib/routes/dekudeals/index.js
N/A
```routes
/dekudeals/most-wanted 
```
An ad on the page causes an error when generating the feed. This changes the selector to only get the game items and ignore the ad.
Ad in middle of page:
Error:
> fix(route): dekudeals error due to ad

- docs/new-media.md
- lib/v2/timednews/maintainer.js
- lib/v2/timednews/news.js
- lib/v2/timednews/radar.js
- lib/v2/timednews/router.js
Close #8271
```routes
/timednews/news
/timednews/news/all
/timednews/news/currentAffairs
/timednews/news/finance
/timednews/news/technology
/timednews/news/social
/timednews/news/sports
/timednews/news/international
/timednews/news/usa
/timednews/news/cn
/timednews/news/europe
/timednews/news/comments
```
时刻新闻 - 新闻
支持子分类
> feat(router): timednews 时刻新闻

- docs/en/government.md
- docs/government.md
- lib/v2/ccac/maintainer.js
- lib/v2/ccac/news.js
- lib/v2/ccac/radar.js
- lib/v2/ccac/router.js
- lib/v2/ccac/utils.js
- lib/v2/icac/news.js
- lib/v2/icac/utils.js
Close #8251
```routes
/ccac/news/all
```
1. Added Macau ICAC `router`. Since the page data is stored directly in `js` and the specific category cannot be determined by `url`. Use `puppeteer` to get the data of the list, and then parse the article details by `cheerio`.
2. Fixed the documentation content of `/icac/news/:lang?`router. And cleaned up the way to get `title` for this route. Thanks to @TonyRL .
> feat(router): ccac 澳门廉政公署

- docs/new-media.md
- lib/v2/hkjunkcall/index.js
- lib/v2/hkjunkcall/maintainer.js
- lib/v2/hkjunkcall/radar.js
- lib/v2/hkjunkcall/router.js
Close #8397
```routes
/hkjunkcall
```
> feat(route): add HKJunkCall資訊中心

- lib/middleware/cache/index.js
```routes
NOROUTE
```
当路由发生错误而没有捕获时，请求flag将不会重置，从而阻塞余下的所有请求。因上次pr格式不对，重启pr。
When a routing error occurs and is not caught, the request flag will not be reset, thus blocking all remaining requests.
> fix: cache next error not catch

- lib/routes/instagram/index.js
Close #
```routes
/instagram/user/jolin_cai
```
The upstream changes the api property naming. This PR does so accordingly.
> fix: instagram logo url error due to upstream change

- docs/new-media.md
- lib/v2/newsmarket/index.js
- lib/v2/newsmarket/maintainer.js
- lib/v2/newsmarket/radar.js
- lib/v2/newsmarket/router.js
Close #8320
```routes
/newsmarket/news-policy
```
> feat(route): add 上下游 News&Market

- docs/en/multimedia.md
- docs/multimedia.md
- lib/v2/bandcamp/live.js
- lib/v2/bandcamp/maintainer.js
- lib/v2/bandcamp/radar.js
- lib/v2/bandcamp/router.js
Close #
```routes
/bandcamp/live
```
> feat(route): add Bandcamp Upcoming Live Streams

- lib/routes/douban/people/status.js
- lib/routes/douban/topic.js
Close #
```routes
/douban/topic/3298608
/douban/people/62759792/status
```
最近他这个`status.sharing_url`字段返回的URL，在最后会多出形如`?_i=12345678`的随机追踪参数（自然是每次返回都不同），影响部分抓取器正常判断是否有条目。
> fix(route): remove douban status url tracker

- lib/router.js
Close #
```routes
NOROUTE
```
This should fix `build assets` workflow failure from multiple PR merges.
- Duplicated route entries in https://github.com/DIYgod/RSSHub/pull/8587 by @song-zhou
- https://github.com/DIYgod/RSSHub/pull/7638 by @nczitzk
- https://github.com/DIYgod/RSSHub/pull/7666
- https://github.com/DIYgod/RSSHub/pull/7603
Also moved the route v1 deprecation warning back to the end of the file.
> fix(route): lazyloadRouteHandler

- scripts/docker/minify-docker.js
N/A
```routes
NOROUTE
```
In commit ad1a09597f19db6adecd6d04f6e8ceaed5dd0026, @vercel/nft is
updated to 0.17.0, and in this version fileList from nft is a set
instead of an array [1].
[1] https://github.com/vercel/nft/pull/240
> fix: update minify-docker.js for newer @vercel/nft

- .github/PULL_REQUEST_TEMPLATE.md
- scripts/workflow/test-route/identify.js
- scripts/workflow/test-route/test.js
Close #
```routes
NOROUTE
```
- Fix `pr-deploy-route-test` workflow not working due to https://github.com/DIYgod/RSSHub/pull/8602
- `github.issues.*` becomes `github.rest.issues.*`
- More info on <https://github.com/actions/github-script#breaking-changes-in-v5>
- Fix `/scripts/workflow/test-route/identify.js` not identifying correct route(s) due to https://github.com/DIYgod/RSSHub/pull/8379 ~~introduced by @SukkaW~~
> fix(ci): `pr-deploy-route-test` workflow

- docs/install/README.md
- docs/multimedia.md
- lib/config.js
- lib/routes/ccdi/scdc.js
- lib/routes/douban/people/status.js
- lib/routes/gov/fmprc/fyrbt.js
- lib/routes/ncm/playlist.js
- lib/routes/ncm/userplayrecords.js
Close #
```routes
/ncm/playlist/390676073
/ccdi/scdc
/gov/fmprc/fyrbt
```
1. 网易云部分歌单需要登陆后才能查看，故允许用户在部署时提供Cookie。
2. 中纪委网站更新迁移至新路径 `/scdcn`，原 `/scdc` 不再更新；同时该站反爬严格，并发抓取全文基本都会返回420异常，为了让路由仍然工作所以mute了异常。
3. 外交部发言人表态网页小变动
> fix: 网易云音乐提供Cookie，抓取需要登陆才可见的歌单 && 中纪委、外交部网站小变动

- lib/routes/picuki/profile.js
Close #7974
```routes
/picuki/profile/humansofny
/picuki/profile/humansofny/1
/picuki/profile/krisztinatina_
/picuki/profile/krisztinatina_/1
```
本路由目前直接爬取 profile 页的预览图，不进入 media 页（除非设置了 `displayVideo` 则会在检测到视频时进入 media 页爬取，但如果一条含视频 post 存在多于一条媒体，则不能被检测到），导致不能爬取到多图片/视频 post。（Instagram 允许最多 10 条图片/视频任意混合于一条 post）
**这个 PR 使得本路由可以进入 media 页爬取 post 包含的所有图片/视频，并缓存爬取结果。** 由于 media 页的图片清晰度高于 profile 页的预览图，这同时也提升了爬取到的图片的清晰度。
尽管如此实现下，`displayVideo` 参数已经没有太大的存在价值，但为了不带来 breaking change，保留了这一参数，并继续保留只有它被设置时才输出视频的行为。
> feat(route)(picuki/profile): 支持多图片/视频解析

- docs/en/journal.md
- docs/journal.md
- lib/v2/heu/job/list.js
Close #
```routes
/heu/job/list/tzgg
/heu/job/list/rdxw
```
`/heu/job/list/tzgg`中有一个链接也是以`.shtml`结尾的，但是该链接所指其他单位网页，故不适用于`tryGet`获取缓存，故导致路由出现错误。通过替换关键词，解决该问题。
> fix(docs): change en comma to cn in journal.md(cn); fix(route): /heu/job/list/tzgg

- docs/new-media.md
- lib/router.js
- lib/routes/tencent/wechat/tgchannel.js
Close #
```routes
/wechat/tgchannel/lifeweek
/wechat/tgchannel/rsswiki
/wechat/tgchannel/rsswiki/大洋网
/wechat/tgchannel/rsswiki/盖世汽车每日速递
```
公众号（Telegram 频道来源）原先需要筛选公众号时只能通过 RSSHub …
> feat(route): 公众号（Telegram 频道来源）增加筛选

- lib/routes/weibo/user.js
Close #8336
```routes
/weibo/user/1750790343
/weibo/user/5270401459
/weibo/user/2675284423
```
获取博主微博的 API `https://m.weibo.cn/api/container/getIndex?containerid=${containerid}` 返回的 `cards` 里，第一个 card 会是固定的格式，不含有 `mblog` ，与后面的不同，因此会被 filter 掉。第一个 card 会含有一个 `card_group` ，里面有且仅有一个 card，可能存放博主的置顶微博，也可能存放**博主最新的微博**（如果没有置顶微博）。这个 PR 会把这个嵌套的 card 取出来（当它不是置顶微博时），这样就不会漏掉它。
示例路由中，第一个是有置顶微博的，第二个没有。
> fix(route)(weibo/user): 无置顶微博时不遗漏第一条微博

- docs/new-media.md
- lib/router.js
- lib/routes/mirror/entries.js
Close #8567
```routes
/mirror/mcdao
/mirror/tingfei.eth
```
Solved problems mentioned in https://github.com/DIYgod/RSSHub/pull/8641. 
Alter to DOM node hierarchy rather than className.
Now it works properly for both *.eth and *.mirror.xyz.
I tried to contact @fifteen42 these days to contribute but no reply, so I create this PR.
> Add rss feed for mirror (fix bugs in previous PR for this site)

- docs/new-media.md
- lib/v2/wechat/feeddd.js
- lib/v2/wechat/maintainer.js
Close #
```routes
/wechat/feeddd/6131e1441269c358aa0e2141
/wechat/feeddd/61512ab61269c358aa13b69c
```
* `author`
* 文章标题 -> 文章作者（从文章页元数据提取，可为空）
* `pubDate`
* feeddd 提供的 `pubDate`（抓取时间，晚于文章实际发布时间） -> 文章实际发布时间（从文章页提取，提取失败则为 feeddd 抓取时间）
* 允许 empty feed
* feeddd 收录公众号后就会产生一个 empty feed, 抓取到文章后才会填充内容。我们应当允许一个 empty feed, 这样就不必等到 feed 被填充才能订阅
* 文档中增加选取正确的 id 的提示
* > 在 URL 中找到 id; 注意不是公众号页的 id, 而是订阅的 id
> fix(route): 公众号 (feeddd 来源)

- lib/middleware/parameter.js
Close #8946
```routes
/bilibili/user/article/334958638?mode=fulltext
/weatherAlarm?mode=fulltext
```
This is possibly caused by a breaking change of cheerio in `1.0.0-rc.4` in efa0018b3fe1a2426c804a4fa12dcc381eda2252.
cheerio will now return U+FFFD
<details>
<summary>bad html entities</summary>
```xml
<item>
<title>
<![CDATA[ 陕西省延安市洛川县气象台发布大雾黄色预警信号 ]]>
</title>
<description>
<![CDATA[ <div><div id="alarmtext"><p>&#x77F;a&#xFFFD;2022t0127&#xFFFD;21&#xFFFD;40&#xFFFD;&apos;&#xFFFD;&#xFFFD;r&#xFFFD;f&#xFFFD;&#xFFFD;&#xFFFD;&#xFFFD;*e12&#xFFFD;&#xFFFD;&#xFFFD;&#xFFFD;$G&#xFFFD;4G&#xFFFD;G&#xFFFD;G&#xFFFD;&#xFFFD;G&#xFFFD;WS8aG&#xFFFD;G&#xFFFD;&#xFFFD;G&#xFFFD;&#xFFFD;&#xFFFD;&#xFFFD;&#xFFFD;&#xFFFD;500s&#xFFFD;&#xFFFD;&#xFFFD;&#xFFFD;2</p></div><div …
```
> fix(core): fix fulltext

- docs/en/traditional-media.md
- docs/traditional-media.md
- lib/v2/nikkei-asia/index.js
- lib/v2/nikkei-asia/maintainer.js
- lib/v2/nikkei-asia/radar.js
- lib/v2/nikkei-asia/router.js
Close #
```routes
/nikkei-asia
```
Full text rss for Nikkei Asia (English)
> Add(route): add Nikkei Asia

- app.json
- docs/en/install/README.md
- docs/en/multimedia.md
- docs/install/README.md
- docs/multimedia.md
- lib/config.js
- lib/v2/spotify/artist.js
- lib/v2/spotify/maintainer.js
- lib/v2/spotify/playlist.js
- lib/v2/spotify/radar.js
- lib/v2/spotify/router.js
- lib/v2/spotify/saved.js
- lib/v2/spotify/top.js
- lib/v2/spotify/utils.js
fixes #6601
```routes
/spotify/playlist/4UBVy1LttvodwivPUuwJk2
/spotify/artist/31zCA3lKnObwtGBbDNnNAt
/spotify/saved/25
/spotify/top/tracks
/spotify/top/artists
```
* Spotify 的 API 需要 token，因此 GHA 的测试应该会失败。生成这些 token 需要 clientId/clientSecret，但不一定需要用户登录。
* Spotify 专辑的 `release_date` 只能精确至日、月或年。 [src](https://developer.spotify.com/documentation/web-api/reference/#/operations/get-track)
* 对于与用户相关的端点，可能需要让用户填入 `refresh_token` 来获取。其它端点只需要 clientId/clientSecret。 [src](https://developer.spotify.com/documentation/general/guides/authorization/code-flow/)
* [Spotify Developer Terms](https://developer.spotify.com/terms/).
> feat: /spotify/*

- lib/v2/app-center/release.js
Close #
```routes
/app-center/release/gameonline/baitomobile/baito
/app-center/release/cloudflare/1.1.1.1-windows/beta
/app-center/release/rdmacios-k2vy/microsoft-remote-desktop-for-mac/all-users-of-microsoft-remote-desktop-for-mac
/app-center/release/rafalense-70ux/plus-release/public
```
Fixed this bug:
<table>
<tr>
<td>
<td>route cache miss
<tr>
<td>content cache miss
<td>feed title, description and icon are correct 😀
<tr>
<td>content cache hit
<td>feed title, description and icon are missing 🥵
</table>
A suggestion: maybe the route test workflow should cover this if the route support caching?
> fix(route): App Center Release

- docs/anime.md
- lib/routes/copymanga/comic.js
Close #
```routes
/copymanga/comic/woliyubaiwanshengmingzhishang/5
/copymanga/comic/woliyubaiwanshengmingzhishang/0
/copymanga/comic/woliyubaiwanshengmingzhishang
```
This fix mirrors manhuagui logic updated in [1] - returns all items
when chapterCnt is 0 or not specified.
/cc @marvolo666
[1] https://github.com/DIYgod/RSSHub/pull/8670
> fix(route): fixes "this route is empty" for copymanga

- docs/multimedia.md
- lib/v2/javdb/utils.js
Close #9083
```routes
/javdb/censored/2/2
```
javdb7.com域名失效，更换为javdb36.com
> fix(route): JavDB Domain

- docs/government.md
- lib/routes/gov/suzhou/doc.js
- lib/routes/gov/suzhou/news.js
- lib/routes/gov/suzhou/utils.js
Close #
```routes
/gov/suzhou/news/news
```
新闻栏目新增便民公告
新闻栏目名称、顺序、链接与苏州市政府官网保持一致
改用https
更新文档，由于栏目过长改为竖排
> fix(route): 更新苏州市政府新闻栏目

- lib/routes/weibo/utils.js
Close #
```routes
/weibo/user/5347795977/1
```
* 原本的匹配已经过时，不能再匹配到 720P 视频，更新匹配后，能够取得 720P 视频。
* 增加视频的回落，高画质无法播放时可回落至低画质。若视频过期（从微博的 API 获得的视频 URL 有时间限制），则可显示一段提示（取决于阅读器如何渲染 <video> tag）。
> feat(route)(weibo): 720P video, video fallback

- lib/routes/weibo/utils.js
#7827 破坏了标题，让所有图标和表情都变成 `[图片]` 加入到标题里，这显然是不对的。
#9117 破坏了链接图标的清理，我不能观察到任何链接以该格式呈现。
原先 (e44064d) 的 regex 只能在已经完成微博表情转换的前提下正常工作，而 #7827 把这个 prereq 破坏了，导致微博表情和链接图标连续出现时，微博表情和链接都会被去掉。
然而 #9117 对这个问题的修复实在令人哭笑不得，恐怕根本没有仔细观察，竟然创造了一个在微博表情和链接图标连续出现时才能匹配成功的 regex，破坏了链接图标的清理。
我修正了所有不安全的 regex，但也把链接图标清理注释掉了，因为这会清理掉所有链接的图标，包括超话等有意义的图标，这也不合适。反正链接图标清理已经被破坏这么久了，也没人觉得不合适来提 issue。
```routes
/weibo/user/6228221165
/weibo/user/2214257545
```
> fix(route)(weibo): title, icon, regex

- lib/v2/xiaoyuzhou/maintainer.js
- lib/v2/xiaoyuzhou/podcast.js
Close #
```routes
/xiaoyuzhou/podcast/:id
```
Fix xiaoyuzhou podcast route issue: `Cannot read property 'smallPicUrl' of undefined` , caused by `image` property is not in episode.
e.g. https://rsshub.app/xiaoyuzhou/podcast/613753ef23c82a9a1ccfdf35
> fix(route): 修复小宇宙播客路由

- lib/routes/zhihu/hot.js
Close # N/A
```routes
NOROUTE
```
API返回的是类似https://api.zhihu.com/questions/518218927的URL。无法用rss客户端打开。
> fix(route): 修复知乎分类热榜链接

- lib/routes/fdroid/apprelease.js
Close #
```routes
/fdroid/apprelease/com.termux
```
previosly, breaks some RSS readers:
```xml
<channel>
<title><![CDATA[
Termux
releases on F-Droid]]></title>
<description><![CDATA[
Termux
releases on F-Droid - Made with love by RSSHub(https://github.com/DIYgod/RSSHub)]]></description>
</channel>
```
fixed:
```xml
<channel>
<title><![CDATA[Termux releases on F-Droid]]></title>
<description><![CDATA[Termux releases on F-Droid - Made with love by RSSHub(https://github.com/DIYgod/RSSHub)]]></description>
</channel>
```
> fix(route)(fdroid/apprelease): invalid feed title

- lib/routes/touhougarakuta/index.js
- lib/routes/touhougarakuta/json2html.js
Close #9271
```routes
NOROUTE
```
源站点的 interviews 迁移到了 tags/interviews
/touhougarakuta/ja/index 有部分文章 type 为 column/report，返回数据跟已有的类型大同小异
/touhougarakuta/cn/interviews 有部分文章不存在 interviewContents/linkToIndex
> fix(route): touhougarakuta

- lib/routes/novel/biqugeinfo.js
Close #
```routes
/novel/biqugeinfo/18_18905
```
针对该路由(/noval/biqugeinfo)
- 当使用 redis 作为 cache 并通过 [ctx.cache.tryGet](https://github.com/DIYgod/RSSHub/blob/master/lib/middleware/cache/index.js#L58) 获取/设置缓存时，会调用 [getCacheTtlKey](https://github.com/DIYgod/RSSHub/blob/196a951fe2ecf4eb586f6e9cdebf58db75735ae5/lib/middleware/cache/redis.js#L26) 方法。而 getCacheTtlKey 中会使用 startsWith 来判断缓存的 key 是否符合要求。这需要 key 的类型必须为 string。因此将缓存的 key 改为 URL string 来修复使用 redis 缓存时该路由出错的问题。
- 按照规范 `ctx.state.data.link` 也应该是一个 string，但之前则是一个 URL 对象。这会导致首次访问路由时 [parameter middleware](https://github.com/DIYgod/RSSHub/blob/196a951fe2ecf4eb586f6e9cdebf58db75735ae5/lib/middleware/parameter.js#L53) 无法处理而抛出错误，顺便修复了这个问题。
> fix(route): novel/biqugeinfo 在使用 redis 作为缓存时无法正常工作

- lib/v2/baidu/tieba/forum.js
None
```routes
/baidu/tieba/forum/RSSHub
```
尝试修复贴吧防盗链更新后trim参数导致的图片无法正确显示问题。
修复前：http://tiebapic.baidu.com/forum/w%3D580/sign=9ed26586f01190ef01fb92d7fe1a9df7/16f6be3eb80e7bec4f00b68a382eb93899506bff.jpg
修复后：
http://tiebapic.baidu.com/forum/w%3D580/sign=9ed26586f01190ef01fb92d7fe1a9df7/16f6be3eb80e7bec4f00b68a382eb93899506bff.jpg?tbpicau=2022-09-30-05_fdae48fb3e104b55217d2d8c95726197
> fix(route): tieba/forum image display error

- docs/en/programming.md
- docs/programming.md
- lib/v2/github/trending.js
Not applicable.
```routes
/github/trending/daily/any/en
/github/trending/weekly/javascript
/github/trending/monthly/unknown
```
Follow-up from #10189. GitHub now returns `openGraphImageUrl` correctly. Uses GraphQL to get desired repository data instead of attempting to query it from the repository page.
> fix(route): use GraphQL query in GitHub trending

- lib/v2/36kr/index.js
Close #11183 
```routes
/36kr/information/web_news
/36kr/user/747305693
/36kr/motif/452
/36kr/topics/1818512662032001
/36kr/search/articles/ofo
/36kr/search/newsflashes/ofo
```
36kr 路由所获取到的的 `itemList` 中会出现 `itemType: 0` 的元素，该种元素结构与其他的元素结构不同 ，如下
```json
{
"itemId": 16598,
"itemType": 0,
"templateMaterial": {
"positionId": 933,
"planId": 16598,
"adSdk": "ZV5L0R2osQao_XC4QkxsjnDapfDVXT4kzJCgEiF9V9BJ_T7L8-OPX504da4Ta53Dhf8aX8euucCid_ZUYsgLug",
"adExposureUrl": "https://adx.36kr.com/api/ad/exposure?sign=dbd383a37955308e98d8bd24b949ba0d&param.adsdk=ZV5L0R2osQao_XC4QkxsjnDapfDVXT4kzJCgEiF9V9BJ_T7L8-OPX504da4Ta53Dhf8aX8euucCid_ZUYsgLug",
"adJsonContent": "{\"description\":\"数字增效，驱动未来。\",\"href\":\"https://adx.36kr.com/api/ad/click?sign=053708d1c026a95d6d1fd8acf232c145&param.redirectUrl=aHR0cHM6Ly …
```
> fix(route): 36kr dom parse errors

- lib/v2/reuters/templates/description.art
Close #
```routes
/reuters/world
```
The origal routes for /reuters request raw news pictures, which have sizes up to 5mb each. This means a single refresh of one reuters channel in an RSS reader can easily consume 100+mb data, and extreme lags can be noticed in some readers who do not optimize thumbnails when scrolling. So this pull request fixes the issue by requesting downsized images from Reuters itself. The default long side of each image is limited to 1080px (`1080w` in `/templates/description.art`), which can be adjusted to 60, 120, 240, 480, 960, 1200 and 1920 if you prefer different resolutions.
> perf(route/reuters): use downsized pictures from Reuters

- docs/new-media.md
- lib/v2/eet-china/maintainer.js
- lib/v2/eet-china/mp/index.js
- lib/v2/eet-china/mp/tags.js
- lib/v2/eet-china/mp/util.js
- lib/v2/eet-china/radar.js
- lib/v2/eet-china/router.js
Close #12922
```routes
/eet-china/mp
/eet-china/mp/tags/36806
```
> feat(route): add 电子工程专辑芯语

- lib/router.js
- lib/routes/boc/whpj.js
- lib/v2/boc/maintainer.js
- lib/v2/boc/radar.js
- lib/v2/boc/router.js
- lib/v2/boc/whpj.js
- lib/v2/icbc/maintainer.js
- lib/v2/icbc/radar.js
- lib/v2/icbc/router.js
- lib/v2/icbc/whpj.js
- website/docs/routes/other.md
Close #
```routes
/icbc/whpj
/icbc/whpj/zs
/icbc/whpj/xh
/icbc/whpj/xc
/icbc/whpj/xhmr
/icbc/whpj/xhmc
/icbc/whpj/xcmr
/icbc/whpj/xcmc
```
> feat(route): Add ICBC; Fix BOC Date & trimming space

- lib/v2/discourse/maintainer.js
- lib/v2/discourse/notifications.js
- lib/v2/discourse/router.js
- website/docs/routes/bbs.md
Close #
```routes
/discourse/0/notifications/1
```
> feat(route): Add Discourse notifications fulltext support.

- lib/v2/iqiyi/maintainer.js
- lib/v2/iqiyi/video.js
Close #12916 
```routes
/iqiyi/user/video/1462574210099259
```
I have to use `Puppeteer` because the `got` method cannot get contents due to iqiyi delay load.
All images in description is this invalid one, and I have no idea.
> fix(route): fix `/iqiyi/user/video`

- assets/radar-rules.js
- lib/radar-rules.js
- lib/router.js
- lib/v2/japanpost/maintainer.js
- lib/v2/japanpost/radar.js
- lib/v2/japanpost/router.js
- lib/v2/japanpost/templates/track_item_desc.art
- lib/v2/japanpost/track.js
- lib/v2/japanpost/utils.js
Close #
```routes
/japanpost/track/225296644860/jp
```
fix(route): japanpost: fix cheerio custom methods
fix(route): japanpost: fix manual timezone parse
> feat(route): migrate japanpost to v2

- lib/v2/bilibili/followings_dynamic.js
Close #
```routes
/bilibili/followings/dynamic/2267573
```
当用户关注动态填充默认作者名时，可能会造成作者信息显示错误；
同时该接口不再显示已订阅的番剧推送，故删去。
~~By the way 这种随机出现的内容该怎么关掉呢，我没在bilibili官网上找到相关订阅设置。~~
找到了，在推送的视频页面里取消“订阅合集”。
> fix(route): 用户关注动态不再预填充作者名

- lib/v2/github/maintainer.js
- lib/v2/github/pulse.js
- lib/v2/github/radar.js
- lib/v2/github/router.js
- lib/v2/github/templates/pulse-description.art
- website/docs/routes/programming.md
Not Applicable.
```routes
/github/pulse/ziglang/zig
/github/pulse/DIYgod/RSSHub/daily
/github/pulse/DIYgod/RSSHub/halfweekly
/github/pulse/DIYgod/RSSHub/weekly
/github/pulse/DIYgod/RSSHub/monthly
/github/pulse/DIYgod/RSSHub/should-default-to-weekly
```
For [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date), I use the current date / time the pulse page was called since the page records details from the current date. If there are other suggestions on what to do here, I welcome all feedback. Thanks! Excited to be contributing this ☺️
> feat(route): add GitHub Pulse

- lib/v2/141ppv/index.js
Close #
```routes
/141ppv/popular/7
```
原来抓取的`src`值似乎是私有媒体存储库地址，无论是在本机访问还是通过RSS服务访问都会返回”Link expired“，其网页代码为
```
```
现在改为直接获取`onerror`，然后正则匹配URL，将该值给`image`，如果没有则返回`null`。
> fix(route): 修正141ppv中image获取问题

- lib/v2/gxmzu/lib.js
- lib/v2/gxmzu/maintainer.js
- lib/v2/gxmzu/radar.js
- lib/v2/gxmzu/router.js
- website/docs/routes/university.md
Close #
```routes
/gxmzu/libzxxx
```
- 添加广西民族大学图书馆最新消息RSS的支持。
> feat: 添加广西民族大学图书馆最新消息RSS的支持

- lib/v2/bilibili/cache.js
- lib/v2/bilibili/utils.js
- lib/v2/bilibili/video-all.js
Close #13334
Close #13315
```routes
/bilibili/user/video/25151282
/bilibili/user/video-all/25151282
```
在访问频率超出限制时，Bilibili 对单个会话要求输入验证码而非同一 IP 的所有会话
现在获取数据时随机返回配置中的一个 Cookie 用于查询来降低单 Cookie 访问频率
预添加的 Cookie 可以是游客状态
可以使用类似于
```py
import sys
import time
import requests_html
def cookieToString(cookie):
l = []
for each in cookie.get_dict().items():
l.append(each[0] + '=' + each[1] + '; ')
return ''.join(l)
number = int(sys.argv[1])
for i in range(0, number):
session = requests_html.HTMLSession()
res = session.get('https://www.bilibili.com', headers={'user-agent': 'Your UA'})
print('set BILIBILI_COOKIE_data%d=%s' % (i, cookieToString(res.cookies)))
time.sleep(0.2)
```
的脚本来大量获取 Cookie
值得注意的是，当请求频率非常大时，此方法会失效，因为此时这个 IP 下的所有会话都会被要求输入验证码
> fix(route): 通过在配置中预添加大量 Cookie 来绕过 Bilibili 反爬

- lib/v2/caixinglobal/latest.js
- lib/v2/caixinglobal/maintainer.js
- lib/v2/caixinglobal/radar.js
- lib/v2/caixinglobal/router.js
- website/docs/routes/traditional-media.md
Close #10999
```routes
/caixinglobal/latest
```
> feat(route): caixin global

- lib/v2/segmentfault/blogs.js
- lib/v2/segmentfault/channel.js
- lib/v2/segmentfault/user.js
- lib/v2/segmentfault/utils.js
- website/docs/routes/programming.md
Close #13578
```routes
/segmentfault/channel/frontend
/segmentfault/user/minnanitkong
/segmentfault/blogs/javascript
```
> fix(route): segmentfault

- lib/middleware/parameter.js
- lib/v2/test/index.js
- test/middleware/parameter.js
Close #13451 
```routes
/test/filter-illegal-category?filter_category=CategoryIllegal
```
The issue doesn't provide a route, so I use the test one.
This is meant to keep only string-type categories, so that the program doesn't crash with null category.
> fix(core): string-type categories only

- lib/v2/epicgames/index.js
- lib/v2/epicgames/templates/description.art
Close #
```routes
/epicgames/freegames
```
fix items containing non-free games
> fix(route): Epic Games Store - items containing non-free games

- lib/v2/epicgames/index.js
- website/docs/routes/game.md
Close #13548 
```routes
/epicgames/freegames
/epicgames/freegames/zh_CN
/epicgames/freegames/zh_CN/CN
```
See #13548 , when item.catalogNs.mappings and item.offerMappings are null, it wouldn't be able to tell if the length of the value was greater than 0 and report an error, so I put an extra judgement in front of the
> fix(route): Epic Games Store - Cannot read properties of null (reading 'length')

- lib/middleware/parameter.js
- test/middleware/parameter.js
Close #
```routes
/test/filter-limit?filterout_title=2&limit=2
```
https://github.com/DIYgod/RSSHub/discussions/13674#discussioncomment-7457216
> fix(parameter): adjust to filter before limit.

- lib/v2/cbc/topics.js
Close #
```routes
/cbc/topics/canada-toronto
```
CBC feed has "Social Sharing" in its feed. This PR removes it since it's not needed in RSS feed.
> fix(route): Remove share widget from CBC route

- lib/v2/ehentai/ehapi.js
#6795
```routes
/ehentai/tag/language:chinese
/ehentai/search
/ehentai/search/f_search=artist%3Ahiten%24
```
The posted time returned by e-hentai is always GMT. This PR is aimed to fix the wrong timezone for non-GMT servers.
> fix(route): fix pubDate timezone for route e-hentai

- lib/v2/kemono/index.js
- lib/v2/kemono/radar.js
Every kemono route, but:
```routes
/kemono/patreon/44261000
```
There is no new route in this PR.
kemono.party redirects to kemono.su now, and the website was proactively telling people to update their bookmarks for a while.
> fix(route): Update the kemono route to point at the new canonical URL

- lib/v2/kemono/index.js
Any non-discord kemono URL (discord URLs leave the image as `undefined`):
```routes
/kemono/patreon/26889925
```
> feat(route): Retrieve avatars from kemono pages and use them as feed images

- lib/v2/bilibili/video.js
Close #
```routes
/bilibili/user/video/2267573
```
```js
var ha, va, _a = ["ZG1faW1nX2xpc3Q=", "ZG1faW1nX3N0cg==", "ZG1fY292ZXJfaW1nX3N0cg=="].map((function(t) {
return atob(t)
}
)), ba = new fa.a({
activityEvents: ["mousemove", "click"],
logStackMaxLength: 50,
samplingTime: 100,
obfuscate: !0,
logConfig: {
valueMap: {
userLogStr: _a[0],
webglStr: _a[1],
webglVendorAndRenderer: _a[2]
}
}
})
```
```js
{
key: "getUserWebglInfo",
value: function() {
var t = document.createElement("canvas")
, e = t.getContext("webgl");
if (!e)
return this.webglVendorAndRenderer = "no webgl",
void (this.webglStr = "no webgl");
this.webglStr = e.getParameter(e.VERSION);
var n = null == e ? void 0 : e.getExtension("WEBGL_debug_renderer_info");
if (n) {
var r = e.getParameter(n.UNMASKED_RENDERER_WEBGL)
, o = …
```
> fix(route): bilibili webgl signature

- lib/v2/showstart/const.js
- lib/v2/showstart/event.js
- lib/v2/showstart/maintainer.js
- lib/v2/showstart/radar.js
- lib/v2/showstart/router.js
- lib/v2/showstart/search.js
- lib/v2/showstart/service.js
- lib/v2/showstart/utils.js
- website/docs/routes/shopping.mdx
Close #12489
```routes
/showstart/event/571
/showstart/search/live
```
> feat(route): add 秀动网 (#12489)

- lib/v2/instagram/web-api/utils.js
Close #
```routes
/instagram/2/user/stefaniejoosten
```
fix: Use `undefined` instead of `null` to delete the `x-ig-www-claim` header
cache.get() return `null` in redis
> fix: Fix X-IG-WWW-Claim header in getUserInfo function

- lib/v2/sse/disclosure.js
Close https://github.com/DIYgod/RSSHub/issues/13981
```routes
/sse/disclosure/beginDate=2023-08-18&endDate=2023-09-01&productId=600696
/sse/disclosure/beginDate=2023-08-18&endDate=2023-09-01&productId=600133
```
> fix: fix sse disclosure

- website/i18n/zh/docusaurus-plugin-content-docs/current/install/README.md
No Issue.
```routes
NOROUTE
```
在文档看到[手动安装添加配置](https://docs.rsshub.app/zh/install/#%E6%B7%BB%E5%8A%A0%E9%85%8D%E7%BD%AE-2)时发现路由跳转失效，找了一会才发现需要点左侧导航栏里的[配置](https://docs.rsshub.app/zh/install/config)，于是想开个 PR 改一下。
但本地运行 website 时，zh 部分是 404，也没找到什么地方能看到效果，于是先 push 上来看看会不会有测试用的部署。
顺带一问，文档问题我从 [discussions](https://github.com/DIYgod/RSSHub/discussions/9944) 看到 [issue](https://github.com/DIYgod/RSSHub/issues/6198)，但之后貌似没有 i18n 的进度了。这部分的进度是另有重要的特性而搁置了还是？
最后一个问题是，#pei-zhi-bu-fen-rss-mo-kuai-pei-zhi 这玩意在哪?
> docs: fix path of zh configuration

- lib/v2/papers/index.js
- lib/v2/papers/maintainer.js
- lib/v2/papers/radar.js
- lib/v2/papers/router.js
- lib/v2/papers/templates/description.art
- website/docs/routes/journal.mdx
Close #14118
```routes
/papers/arxiv/cs.CL
```
> feat(route): add Cool Papers

- lib/v2/shmeea/index.js
- lib/v2/shmeea/maintainer.js
- lib/v2/shmeea/radar.js
- lib/v2/shmeea/router.js
- website/docs/routes/study.mdx
```routes
/shmeea/08000
/shmeea/09000
/shmeea/02200
/shmeea/03200
/shmeea/05100
/shmeea/04100
/shmeea/05400
```
因[当前 shmeea 路由](https://rsshub.app/shmeea)不工作![](https://img.shields.io/website.svg?label=&url=https%3A%2F%2Frsshub.app%2Fshmeea&cacheSeconds=7200)，修复路由的同时为其添加 id 参数。
- 添加 id 参数，完成相应 Radar 规则
- 尝试获取精确发布时间，并校正时区
- 修复 L41 不精确的 `link: baseURL`
CC @jialinghui
> feat(route): id param for shmeea

- lib/config.js
- lib/v2/bilibili/cache.js
- lib/v2/bilibili/hotSearch.js
- lib/v2/bilibili/liveSearch.js
- lib/v2/bilibili/router.js
- lib/v2/bilibili/utils.js
- lib/v2/bilibili/video-all.js
- lib/v2/bilibili/video.js
Close #
```routes
/bilibili/user/video/12590
/bilibili/user/video-all/12590
```
我在请求参数中添加了非空的 `dm_img_list` 字段
`/bilibili/user/video-all` 仍然可用，我重新添加了它
代码中 `'[{"x":2721,"y":615,"z":0,"timestamp":29,"type":0}]'` 是我从浏览器中获取的一串可能的数据
也可以通过 `BILIBILI_DM_IMG_LIST` 环境变量自行添加
尽管它可以工作，我仍然不清楚 `dm_img_list` 的含义
它也许和鼠标移动有关，因为当我不移动鼠标时其值为 `[]` (空列表)
我无法随机生成它来欺骗系统，Bilibili 也许引入了机器学习来分辨人类与机器
> feat(route): 添加 dm_img_list 字段防止被 Bilibili 识别

- website/docs/joinus/new-rss/start-code.md
- website/i18n/zh/docusaurus-plugin-content-docs/current/joinus/new-rss/start-code.md
Close #
```routes
NOROUTE
```
The existing example for HTML retrieval documentation uses 'item' variable to store array of the retrieved articles, but the final rss output refers to the 'items' variable. This results in undefined variable 'items' for anyone who directly uses the example code.
> docs: change html example to use items variable instead of item

- lib/v2/zhihu/timeline.js
```routes
/zhihu/timeline
```
This PR fix the following error:
```
Route requested: /zhihu/timeline
Error message: Cannot read properties of undefined (reading 'substring')
Helpful Information to provide when opening issue:
Path: /zhihu/timeline
Node version: v20.10.0
Git Hash: 3bf9dd2
```
Caused by modules taking following html (as example) as text node:
```html
some text <span>123</span> some text
```
It also:
- deal with `content` inside an array
- adopts `content_html` if exists.
Looks good to me.
> fix: zhihu timeline

- lib/config.js
- lib/utils/pac-proxy.js
- lib/utils/request-wrapper.js
- package.json
- pnpm-lock.yaml
- test/utils/pac-proxy.js
- test/utils/request-wrapper.js
- website/docs/install/config.md
- website/i18n/zh/docusaurus-plugin-content-docs/current/install/config.md
Close #14178
```routes
NOROUTE
```
Add PAC script support. Now self-hosted RSSHub can use `PAC_URI` or `PAC_SCRIPT` in the config to set proxy with PAC script.
Added package `pac-proxy-agent`.
> feat(proxy): add PAC script support

- lib/v2/pornhub/utils.js
```routes
/pornhub/users/pornhubmodels
/pornhub/model/stacy-starando
/pornhub/pornstar/june-liu
/pornhub/category_url/video%3Fc%3D15%26o%3Dmv%26t%3Dw%26cc%3Djp
```
PornHub 时间解析出错，替换为封面图片 URL 中携带的时间参数
更改前
更改后
> fix: PornHub pubDate

- lib/v2/luogu/daily.js
RSSHub will throw thi error while fetch `/luogu/daily`.
```
Error message: Missing `url` property: target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
```
After check the response, now it will send a encode string to client for decode, like this.
```javascript
<head><script>
window._feInjection = JSON.parse(decodeURIComponent("%7B%22code%22%3A200%2C%22currentTemplate%22%3A%22DiscussShow%22%2C%22currentData%22%3A%7B%22forum%22%3A%7B%22name%22%3A%22%5Cu5b66%5Cu672f%5Cu7248%22%2C%22type%22%3A1%2C%22slug%22%3A%22academics%22%2C%22color%22%3A%22purple-3%22%7D%2C%22post%22%3A%7B%22id%22%3A47327%2C%22title%22%3A%22%5Cu3010%5Cu65e5%5Cu62a5%23463%5Cu3011%5Cu57fa%5Cu4e8eCYaRon%5Cu7684%5Cu6570%5Cu636e%5Cu5236%5 …
```
> fix: luogu route parse error

- lib/v2/tradingview/pine.js
- lib/v2/tradingview/radar.js
- lib/v2/tradingview/router.js
- website/docs/routes/program-update.mdx
Close #14053
```routes
/tradingview/pine
```
> feat(route): add TradingView Pine Script™ Release notes

- lib/v2/twitter/utils.js
Close #
```routes
/twitter/user/aboutrss/readable=1&authorNameBold=1&showAuthorInTitle=1&showEmojiForRetweetAndReply=1&showRetweetTextInTitle=0&addLinkForPics=1&showQuotedInTitle=1?filter_title=🔁
```
1. Trim link pointing to the tweet itself (usually appears when the tweet is truncated).
2. Only insert `<hr>` when both `showTimestampInDescription` and `readable` are enabled.
3. Make RT links point to the RT itself, instead of the original tweet.
> fix(route/twitter): readability and RT link

- lib/v2/twitter/web-api/twitter-api.js
Close #
```routes
/twitter/user/jia0kelvin/excludeReplies=1
```
Without `legacy.id_str`, reply URLs would be constructed with conversion IDs, resulting in:
- wrong URLs: pointing to the first tweet in the conversion (thread)
- multiple items with the same guid: each tweet in a conversion (thread) had the same URL and thus guid
The bug was caused by the widely used temporary fix (legacy.id_str || legacy.conversation_id_str) after Twitter had upgraded their API. Thus, it is quite easy to fix it:
Refill legacy.id_str using the rest_id that resides in the container of legacy.
With it fixed, take a step further to include threads when excludeReplies=1 (simulating the behavior of Twitter Web/App).
> fix(route/twitter): reply URL; threads when excludeReplies=1

- lib/middleware/anti-hotlink.js
- lib/v2/weibo/utils.js
Close #12314 
```routes
/weibo/user/1401527553
```
例子如下，之前只能匹配最后一个，目前微博大部分是第一个
```
"https://weibo.cn/sinaurl?u=http://xx"
"https://weibo.cn/sinaurl/?u=http://xx"
"https://weibo.cn/sinaurl?q=xx&u=http://xx"
"https://weibo.cn/sinaurl/?q=xx&u=http://xx"
```
内容中会出现`a`链接的`查看图片`，这里面的链接希望被替换，以绕过防盗链
```html
<a href="https://tvax4.sinaimg.cn/large/53899d01gy1hmckcfvlh1j20soc4je82.jpg" data-hide=""><span class="url-icon"><img style="width: 1rem;height: 1rem" src="https://api.xlab.app/img-proxy/?url=https%3A%2F%2Fh5.sinaimg.cn%2Fupload%2F2015%2F01%2F21%2F20%2Ftimeline_card_small_photo_default.png" referrerpolicy="no-referrer"></span><span class="surl-text">查看图片</span></a>
```
> 原始href是如上的外部链接，被替换后得到真实图片链接
单独在微博处理时给`a`标签加属性，以便在hotlink替换时处理
> fix: 微博内容中[查看图片]的链接支持被HOTLINK_TEMPLATE替换

- lib/v2/weibo/user.js
- website/docs/routes/social-media.mdx
> feat(route): Optimize Weibo blogger routing | 优化微博博主路由

- lib/v2/pwc/maintainer.js
- lib/v2/pwc/radar.js
- lib/v2/pwc/router.js
- lib/v2/pwc/sustainability.js
- website/docs/routes/other.mdx
add PwC Strategy& Sustainability route
```routes
/pwc/strategyand/sustainability
```
PwC Strategy& Sustainability is a blog on the thought leadership about subjects like sustainability or ESG.
> feat: add PwC Strategy& Sustainability route

- lib/v2/douban/other/list.js
在此之前，豆瓣电影Top250只能返回部分电影。修改后可以返回全部250部电影。
测试路由：`/douban/list/movie_top250`。
Close #
```routes
/douban/list/movie_top250
```
> fix: 豆瓣榜单与集合支持分页处理

- lib/v2/lofter/tag.js
```routes
/lofter/tag/i
/lofter/tag/i/new
/lofter/tag/边狱巴士
/lofter/tag/边狱巴士/new
```
The name must be encoded in request's form, otherwise Chinese characters won't be recognized.
> fix: encode tag name in lofter request's form

- lib/v2/2048/index.js
```routes
/2048/23
```
fix 
Route requested: /2048/23
Error message: Cannot read properties of undefined (reading 'attribs')
Helpful Information to provide when opening issue:
Path: /2048/23
Node version: v20.11.1
Git Hash: 51f79ef
> fix(route): 2048/:type

- lib/routes/npm/package.js
- lib/routes/npm/router.js
#9575, #9578
```routes
/npm/package/lodash
/npm/package/lodash?key=access_key
/npm/package/@package/copy
```
1.  Don't include query params like `?code` in the package name.
2.  Handle special cases when the org name of the package ends with `package`, i.e. the package name is something like `@*package/*`.
> fix: use path param with regex for npm package feed

- lib/routes/mastodon/timeline-local.js
- lib/routes/mastodon/timeline-remote.js
- lib/routes/mastodon/utils.js
```routes
/mastodon/acct/CatWhitney@mastodon.social/statuses
```
获取 account statuses 以及 timeline 时也使用 Mastodon access token，且只向设置的 API host 发送 token。
> fix: use access token for all Mastodon routes

- lib/index.ts
- lib/utils/common-utils.test.ts
- lib/utils/common-utils.ts
Close #
```routes
NOROUTE
```
```
having to manually enter the address in the browser every time you start the project is inconvenient, isn't it?
this PR enables the direct exposure of all available server URLs from within the CLI.
offering some development conveniences.
```
> feat: expose server URLs in the CLI

- lib/routes/telegram/channel.ts
Close #
```routes
/telegram/channel/telegram/showViaBot=false
/telegram/channel/telegram/showReplyTo=false
```
> fix(route): telegram parameters showReplyTo and showViaBot

- website/docs/usage.md
Previously the modified field leads to a broken link: 
https://docs.rsshub.app/(https://github.com/DIYgod/RSSHub/blob/gh-pages/build/radar-rules.json)
Now I follow the style of other functioning link to remove the redundant parenthesis.
> fix: doc link

- lib/routes/telegram/channel.ts
```routes
/telegram/channel/thisismegatest
```
Now t.me supports videostickers and I've added it to rsshub
Here is parsed example
first message is video and another is videosticker:
https://pastebin.com/raw/46XX4rWr
> feat(route)(telegram/channel): support for video stickers

- lib/routes/gov/stats/index.ts
Close #https://github.com/DIYgod/RSSHub/issues/14794
```routes
/gov/stats/sj/zxfb/
```
> fix(route): fix redundant '/' in stats.gov.cn

- lib/routes/18comic/templates/description.art
- lib/routes/18comic/utils.ts
Close #
```routes
/18comic/all/a/mv
/18comic/all/a/mv?domain=jmcomic1.me
/18comic/all/a/mv?domain=jm-comic3.art
/18comic/all/a/mv?domain=jm-comic.club
/18comic/all/a/mv?domain=jm-comic2.ark
/18comic/all/a/mv?domain=18comic.org
/18comic/all/a/mv?domain=18comic.vip
```
> fix(route): 18comic add cover image

- lib/routes/bilibili/dynamic.ts
Close #14952
```routes
/bilibili/user/dynamic/31009079/disableEmbed=1
/bilibili/user/dynamic/5017882/disableEmbed=1
/bilibili/user/dynamic/40366538
```
It seems like `v1` is a deprecated API, and they removed it today.
Replacing it with `v2` could get a valid response, but some fields have minor changes. It shouldn't cause problems with RSSHub. However, I haven't tested it, hopefully the CI can do it for me (if there is one?).
> fix: update bilibili dynamic API to v2 from v1

- lib/registry.ts
Close #14997
```routes
/douban/explore
```
The modules imported with `directory-import` on Windows is in format `\zyshow\namespace.ts`, which splits with `\` instead of `/`, so all routes will throw "wrong path" error. This PR fixes it.
> fix(core): fix wrong path on Windows deploy

- lib/routes/minecraft/version.ts
```routes
/minecraft/version
/minecraft/version/all
/minecraft/version/all/zhwiki
/minecraft/version/release/official
/minecraft/version/snapshot/enwiki
/minecraft/version/old_beta/zhwiki
```
- Switch to `piston-meta.mojang.com` (2022 June 15 (UTC+8), Mojang changed the host for version manifests to the new one)
- Switch to version manifest V2 (`sha1` and `complianceLevel` are added, though they are not used by RSSHub)
- Change "过时的预览版" to "Beta版"
- Change "过时的测试版" to "Alpha及更早的版本"
- Add version type filter
- Allow set links to EN/ZH Minecraft Wiki version pages
> feat(route): /minecraft/version, add version type filter and wiki link generator

- lib/config.ts
- lib/middleware/cache.test.ts
- lib/middleware/template.tsx
Close #
```routes
NOROUTE
```
```
fix(core): false RSS <ttl> when cache unavailable
Some RSS readers may probe <ttl> to determine the minimum interval of
polling. However, it is always set to `config.cache.routeExpire / 60`
even when cache is unavailable. This may not be expected when the cache
is explicitly disabled.
Set it to 1 (minute) under such a circumstance. The minimum <ttl> (when
cache is available) is also limited to 1 to avoid potential misuse.
The Cache-Control header remains untouched as caching can be done by a
reverse proxy.
Signed-off-by: Rongrong <i@rong.moe>
fix(core): CACHE_TYPE='' does not disable cache
The documentation of config always states that CACHE_TYPE being empty
will disable the cache.
The regression was introduced in 847724ca. The corresponding test case
was …
```
> fix(core): misc fixes of disabling cache

- lib/routes/zhihu/timeline.ts
- lib/routes/zhihu/utils.ts
Close #9485 
```routes
/zhihu/timeline
```
Zhihu API use `verb` instead of `type`(default `feed`) to classify feeds. `verbs` includes:
```python
{('', '{}关注了问题'),
('MEMBER_ANSWER_QUESTION', '{}回答了问题'),
('MEMBER_ASK_QUESTION', '{}添加了问题'),
('MEMBER_COLLECT_ARTICLE', '{}收藏了文章'),
('MEMBER_CREATE_ARTICLE', '{}发表了文章'),
('MEMBER_CREATE_PIN', '{}发布了想法'),
('MEMBER_VOTEUP_ANSWER', '{}赞同了回答'),
('MEMBER_VOTEUP_ARTICLE', '{}赞同了文章'),
(None, None) # advertisement
}
```
I excluded categories about votes but don't know if `MEMBER_CREATE_PIN`(想法) should be included. demo see [private temp rsshub](http://18.189.188.195:1200/zhihu/timeline?key=ernest)
> fix(route): 知乎时间线 (#9485)

- lib/routes/baidu/tieba/search.ts
- lib/utils/got.test.ts
- lib/utils/got.ts
Close #15042, Close #15076, Close #15077
```routes
/ncc-cma/cmdp/image
/c114/roll
/txrjy/fornumtopic/1
/baidu/tieba/search/neuro
```
`buffer` responseType is not supported in the new `got.ts`, so all the routes are parsed as string, which results in encoding error. I add support for `buffer` responseType in this commit.
> fix(core): buffer responseType

- lib/routes/nymity/censorbib.ts
- lib/routes/nymity/namespace.ts
- lib/utils/got.ts
```routes
/nymity/censorbib
```
https://github.com/NullHypothesis/censorbib/issues/8
> feat(routes): Add censorbib

- lib/routes/minecraft/blockedservers.ts
- lib/routes/minecraft/java-runtime.ts
```routes
/minecraft/blockedservers
/minecraft/java-runtime
```
Based on #14941
> feat(routes): Add more routes related to Minecraft

- lib/views/atom.tsx
icon and logo field are missing from atom feed after it's migrated to tsx template. This PR adds them back.
Close #
```routes
NOROUTE
```
> fix(core): add icon and logo back to atom feed

- lib/routes/gcores/category.ts
Close #
```routes
/gcores/category/articles
/gcores/category/news
/gcores/category/videos
/gcores/category/radios
```
只对资讯、文章的路由进行了测试，有两个问题：
1. 作者输出带有日期
我想要的是 `无名氏` 这样的输出，实际输出是 `无名氏24分钟前`，`无名氏B3天前`这样的。
主要是我没太懂 cheerio 这个是怎么选择元素的。网页上应该是 `.avatar_text > .me-2`，但是我尝试了下面几种方式在输出的 RSS 里直接不显示 author 参数，只有 `.avatar_text` 能正常显示
- `.avatar_text > .me-2`
- `.avatar_text>.me-2`
- `.me-2>.avatar_text`
2. author 这行写了两遍
当我尝试 RSSHub 文档中 [制作路由](https://docs.rsshub.app/zh/joinus/new-rss/start-code#生成-rss-源-1) 的这部分代码，直接在 `const basicItem =` 这个代码块添加 `author: item.find('.avatar_text').text(),`，访问路由会提示报错:
```js
❯ pnpm dev
> rsshub@1.0.0 dev .../RSSHub
> cross-env NODE_ENV=dev tsx watch --no-cache lib/index.ts
info: 🎉 RSSHub is running on port 1200! Cheers!
info: 💖 Can you help keep this open source project …
```
> feat(route): add author in gcores

- lib/routes/threads/index.ts
- lib/routes/threads/utils.ts
Close #15183
```routes
/threads/zuck
```
> fix(route): threads

- lib/routes/apple/podcast.ts
Close #
```routes
/apple/podcast/id1559695855
```
新增 apple 播客 路由
> feat(route): add apple podcast route

- lib/routes/bilibili/cache.ts
Close #
```routes
NOROUTE
```
When I was reviewing the source code, I found that `getCookie` in `lib/routes/bilibili/cache.ts` created a `puppeteer` instance but did not close it. This could lead to a memory leak. I've added a `browser.close()` here to close the `puppeteer` instance.
> fix: bilibili cache issue and close puppeteer after getting cookie

- lib/errors/index.test.ts
- lib/routes/test/index.ts
- lib/setup.test.ts
- lib/utils/wechat-mp.test.ts
- lib/utils/wechat-mp.ts
#9674
```routes
/test/wechat-mp/__biz=Mzg4NTA1MTkwNA==&mid=2247533067&idx=1&sn=778653e5fee2c949581b552c38d4fd8f
/test/wechat-mp/FnjcMXZ1xdS-d6n-pUUyyw
/test/wechat-mp/__biz=Mzg4NTA1MTkwNA==&mid=2247532942&idx=1&sn=a84e4adbe49fdb39e4d4c1b5c12a4c3f
/test/wechat-mp/FY6yQC_e4NMAxK0FBr6jwQ
/test/wechat-mp/__biz=Mzg4NTA1MTkwNA==&mid=2247532936&idx=1&sn=7a98b4381483b61fd7832cea4eb67bec
```
```
APP_MSG_PAGE
APP_MSG_PAGE (w/ audio and video)
VIDEO_SHARE_PAGE
AUDIO_SHARE_PAGE
IMG_SHARE_PAGE
```
```
feat(core/utils/wechat-mp): major rewrite
* Support more `item_show_type`: `APP_MSG_PAGE`, `VIDEO_SHARE_PAGE`,
`AUDIO_SHARE_PAGE`, and `IMG_SHARE_PAGE`. Previously only the first one
could be parsed properly. There are still some other known types waiting
for live examples for further adaptation. If this …
```
> feat(core/utils/wechat-mp): major rewrite

- lib/routes/gov/stats/index.ts
Close #15273
```routes
/gov/stats/sj/zxfb/
```
Using the ofetch raw to get the cookie headers
> fix(route): fix the gov.cn stats using the ofetch.raw

- lib/setup.test.ts
- lib/utils/wechat-mp.test.ts
- lib/utils/wechat-mp.ts
OFF-TOPIC: `ofetch` cannot follow redirects while `got` can do it. I've already seen someone encountering a relevant regression: #15075
**I wrote a simple code snippet to follow redirects in `wechat-mp`. It'd be better implement it project-wide in the `ofetch` or `fakeGot` helper sometime.**
```routes
/test/wechat-mp/__biz=Mzg4NTA1MTkwNA==&mid=2247533067&idx=1&sn=778653e5fee2c949581b552c38d4fd8f
/test/wechat-mp/FnjcMXZ1xdS-d6n-pUUyyw
/test/wechat-mp/__biz=Mzg4NTA1MTkwNA==&mid=2247532942&idx=1&sn=a84e4adbe49fdb39e4d4c1b5c12a4c3f
/test/wechat-mp/FY6yQC_e4NMAxK0FBr6jwQ
/test/wechat-mp/__biz=Mzg4NTA1MTkwNA==&mid=2247532936&idx=1&sn=7a98b4381483b61fd7832cea4eb67bec
```
```
APP_MSG_PAGE
APP_MSG_PAGE (w/ audio and video)
VIDEO_SHARE_PAGE
AUDIO_SHARE_PAGE
IMG_SHARE_PAGE
```
``` …
```
> fix(core/utils/wechat-mp): empty description when request blocked by WAF

- .github/workflows/test.yml
- Dockerfile
This should help resolve https://github.com/DIYgod/RSSHub/pull/15244#issuecomment-2057906761. However, there are still some other dependency issues before #15244. This is not taken into consideration in this PR.
```routes
NOROUTE
```
CI `test.yml` is also updated to use an absolute path.
This PR can be safely merged now because no user-visible change is made.
> build(Dockerfile): set CHROMIUM_EXECUTABLE_PATH to absolute path

- lib/routes/telegram/channel.ts
- lib/routes/wechat/tgchannel.ts
Close #
```routes
/telegram/channel/RailTransit
```
```
fix(route/{telegram/channel,wechat/tgchannel}): broken links
route/telegram/channel:
Since 2024/4/20, t.me/s/ mistakenly have every '&' in **hyperlinks**
replaced by '&amp;'. The characteristic of a hyperlink is [onclick]
(pop-up confirmation), which is not present in ordinary links. This is a
workaround to fix the issue until Telegram fixes it.
route/wechat/tgchannel:
Since 2024/4/20, t.me/s/ mistakenly have every '&' in **hyperlinks**
replaced by '&amp;'. wechat-mp will take care of this, so no need to fix
it here. However, once the bug is eventually fixed, all guid will be
changed again. Considering that this is almost certain to happen, let's
break guid consistency now by using normalized URL from wechat-mp as
guid to avoid …
```
> fix(route/{telegram/channel,wechat/tgchannel}): broken links

- lib/setup.test.ts
- lib/utils/got.test.ts
- lib/utils/got.ts
Related #15238
```routes
NOROUTE
```
This restores the behaviour when posting with `option.form` like `got`.
https://github.com/sindresorhus/got/blob/88e623a0d8140e02eef44d784f8d0327118548bc/source/core/index.ts#L596-L604
https://github.com/sindresorhus/got/blob/88e623a0d8140e02eef44d784f8d0327118548bc/documentation/2-options.md?plain=1#L364-L370
> fix(core): posting form as `x-www-form-urlencoded` in got wrapper

- lib/routes/twitter/api/web-api/constants.ts
- lib/routes/twitter/api/web-api/utils.ts
- lib/routes/twitter/tweet.ts
Close #
```routes
/twitter/tweet/questflow/status/1771391133010333778/0
```
There was a problem with the original TweetDetail routing, which has now been fixed.
Docs: https://docs.rsshub.app/routes/social-media#tweet-details
Route: /twitter/tweet/:id/status/:status/:original?
> fix: tweet detail route not work

- lib/routes/douyu/room.ts
Close #
```routes
/douyu/room/2421040
```
use new api get room info when error with fallback to old api, can detect is video loop or real live.
> feat(route): douyu room api update with fallback

- .github/workflows/docker-test-cont.yml
- .github/workflows/docker-test.yml
Close #
```routes
/test/1
```
Compress time: [30s](https://github.com/DIYgod/RSSHub/actions/runs/8910280008/job/24469234135) -> [13s](https://github.com/DIYgod/RSSHub/actions/runs/8910501376/job/24469899374#step:8:1)
Size: [450MB](https://github.com/DIYgod/RSSHub/actions/runs/8910280008/job/24469234135#step:8:1) -> [373MB](https://github.com/DIYgod/RSSHub/actions/runs/8910501376/job/24469899374#step:8:30)
Decompress time: [30s](https://github.com/DIYgod/RSSHub/actions/runs/8910317628/job/24469348716) -> 2s
> chore: compress using zstd in docker test

- lib/routes/weekendhk/posts.ts
- lib/routes/wellcee/namespace.ts
- lib/routes/wellcee/rent.ts
- lib/routes/wellcee/support-city.ts
- lib/routes/wellcee/templates/house.art
- lib/routes/wellcee/types.ts
- lib/routes/wellcee/utils.ts
Close #14038
```routes
/wellcee/support-city
/wellcee/rent/北京
```
> feat(route): wellcee

- .github/workflows/build-assets.yml
- .github/workflows/comment-on-issue.yml
- .github/workflows/docker-test-cont.yml
- .github/workflows/format.yml
- .github/workflows/issue-command.yml
- .github/workflows/lint.yml
- .github/workflows/npm-publish.yml
- .github/workflows/test-full-routes.yml
- .github/workflows/test.yml
- Dockerfile
- package.json
- pnpm-lock.yaml
Close #
```routes
NOROUTE
```
lockfile v6 is deprecated by pnpm v9, and is now readonly.
https://github.com/pnpm/pnpm/issues/7934
> chore: bump pnpm lockfile

- lib/routes/github/wiki.ts
Close #14387
```routes
/github/wiki/flutter/flutter
```
> fix: broken url when not using optional :page parameter

- lib/routes/pornhub/category-url.ts
- lib/routes/pornhub/model.ts
- lib/routes/pornhub/pornstar.ts
- lib/routes/pornhub/users.ts
- lib/routes/pornhub/utils.ts
```routes
/pornhub/users/pornhubmodels
/pornhub/model/stacy-starando
/pornhub/pornstar/june-liu
/pornhub/category_url/video%3Fc%3D15%26o%3Dmv%26t%3Dw%26cc%3Djp
```
Make PornHub available
> fix: PornHub

- lib/routes/nudt/namespace.ts
- lib/routes/nudt/yjszs.ts
```routes
/nudt/yjszs
/nudt/yjszs/sszs
/nudt/yjszs/tzgg
```
增加了国防科技大学研究生院中的硕士招生和通知公告的rss源
> feat(route): 增加了国防科技大学研究生院中的硕士招生和通知公告的rss源

- lib/routes/bbc/index.ts
Close #15568
```routes
/bbc/world-asia
```
Replacing hostname should be enough for the moment.
> fix(route): BBC article

- lib/routes/pornhub/pornstar.ts
N/A
```routes
/pornhub/pornstar/natalie-lust
```
These changes should fix parsing of pornstar pages on PornHub.
At the moment they are broken, see: 
Page: https://www.pornhub.com/pornstar/natalie-lust
RSS:  https://rsshub.app/pornhub/pornstar/natalie-lust
> fix(route): PornHub pornstar pages

- lib/routes/6v123/latest-movies.ts
- lib/routes/6v123/latest-tvseries.ts
- lib/routes/6v123/utils.ts
latestMovies has some tv series data in list, use filter with reg skip it. 
```routes
/6v123/latestMovies
/6v123/latestTVSeries
```
> fix: /6v123/latestMovies filter tv series

- lib/routes/fanqienovel/namespace.ts
- lib/routes/fanqienovel/page.ts
Close #15655
```routes
/fanqienovel/page/6621052928482348040
```
> feat(route): fanqienovel

- lib/routes/cfr/index.ts
- lib/routes/cfr/namespace.ts
- lib/routes/cfr/types.ts
- lib/routes/cfr/utils.ts
Close #15542
```routes
/cfr/asia/china
/cfr/blog
/cfr/timelines
/cfr/books-reports
/cfr/videos
/cfr/podcasts/world-next-week
```
> feat(route): cfr

- lib/routes/imdb/chart.ts
- lib/routes/imdb/namespace.ts
- lib/routes/imdb/templates/chart.art
- lib/routes/imdb/types.ts
Close #15458
```routes
/imdb/chart
```
> feat(route): imdb top charts

- lib/routes/2048/index.ts
> fix: /2048 route down

- lib/routes/podwise/collections.ts
- lib/routes/podwise/episodes.ts
- lib/routes/podwise/namespace.ts
```routes
/podwise/explore
/podwise/explore/latest
/podwise/explore/all
```
当网站时间为的月份缩写(MMM)与浏览器地区不一致时， 需要指定parseDate的语言参数，如'en', 如果发现parseDate为Invalid Date时, 调用
```js
import localeData from 'dayjs/plugin/localeDate';
dayjs.extent(localeData); 
dayjs.monthShort();
```
来查看缩写是否与时间的月份一致
> feat: support  podwise.ai

- lib/index.ts
N/A
```routes
NOROUTE
```
Somehow the functionality is lost during Hono migration [1]. Let's add it back.
[1] https://github.com/DIYgod/RSSHub/commit/8e0154552ce3a5c2f9b88fa45447eb809d5ec252
> fix(core): restore LISTEN_INADDR_ANY functionality

- lib/routes/spotify/artist.ts
- lib/routes/spotify/artists-top.ts
- lib/routes/spotify/playlist.ts
- lib/routes/spotify/saved.ts
- lib/routes/spotify/show.ts
- lib/routes/spotify/tracks-top.ts
- lib/routes/spotify/utils.ts
Close #15648
```routes
/spotify/artist/6k9TBCxyr4bXwZ8Y21Kwn1
/spotify/top/artists
/spotify/playlist/4UBVy1LttvodwivPUuwJk2
/spotify/saved/50
/spotify/top/tracks
/spotify/show/5CfCWKI5pZ28U0uOzXkDHe
```
fix Spotify TypeError by replacing `got` with `ofetch`.
> fix(route): fix Spotify TypeError

- lib/routes/vice/topic.ts
Close #15736
```routes
/vice/topic/hacking
/vice/topic/cleveland
/vice/topic/assault
/vice/topic/millenial
/vice/topic/sex
```
Fixes a few issues with VICE route. NEXT_DATA has some roles that are currently unsupported. Problem is that these roles vary from article to article. Fortunately, however all these roles, so far have been internal ads pointing at other articles.
I have added extra routes for testing purposes in the PR
> fix(route): Vice component role fix

- lib/routes/pubscholar/explore.ts
- lib/routes/pubscholar/namespace.ts
- lib/routes/pubscholar/types.ts
- lib/routes/pubscholar/utils.ts
Close #14363
```routes
/pubscholar/explore
```
> feat(route): pubscholar

- .github/workflows/test.yml
N/A
```routes
NOROUTE
```
After this PR, future PR reviewers can inspect the build output, such as `assets/build/routes.json`. This helps reviewing routes whose description is calculated, instead of a simple string literal. Example: #15798.
Documentation: https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#uploading-build-and-test-artifacts
> ci(test): upload assets as GitHub CI artifacts

- lib/routes/bugzilla/bug.ts
- lib/routes/bugzilla/namespace.ts
(N/A)
```routes
/bugzilla/bug/apache/55899
/bugzilla/bug/apache.ooo/74164
/bugzilla/bug/apache.SpamAssassin/8091
/bugzilla/bug/mozilla/840640
/bugzilla/bug/webkit/251528
```
- Need to maintain a mapping from identifiers to site prefixes. A future PR may add a free-form site prefix parameter.
- `@/utils/parse-date` changed the timezone from UTC to GMT. They are assumed to be synonyms, but IMO we should label it as UTC, as it is the modern name for that timezone.
> feat(route): add Bugzilla

- lib/routes/guokr/utils.ts
Close #
```routes
/guokr/column/calendar
/guokr/column/institute
/guokr/column/beauty
/guokr/scientific
```
* 果壳现在会使用 `opacity: 0` 的内联 CSS 规则使得页面变成空白。此修改将对应的干扰内联 CSS 移除。
> fix(route): 修复果壳 RSS 订阅正文空白的问题

- .github/workflows/lint.yml
No issue currently
```routes
NOROUTE
```
Similar to https://github.com/DIYgod/RSSHub/commit/206b6d2c9978bf77746c529a7d386772efb51712, this skips running the "Pull Request Labeler" job when running on a forked repository. This avoids unnecessary traffic to the GitHub API when forks synchronize with this repository.
> chore: Skip pull request labeler for forked repositories

- .github/workflows/test.yml
N/A
```routes
NOROUTE
```
This should publish the JUnit report for human consumption. The raw XML is too long, so not as readable for PR reviewers.
Reference:
- https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28
> ci(test): enable the GitHub Actions reporter for Vitest

- lib/routes/bluearchive/namespace.ts
- lib/routes/bluearchive/news.ts
N / A
```routes
/bluearchive/news/jp/0
/bluearchive/news/jp/1
/bluearchive/news/jp/2
/bluearchive/news/jp/3
```
Only JP server is added in this commit, I may add support for the rest in the future.
> feat(route): introduce `/bluearchive/news`

- lib/routes/bluearchive/news.ts
N / A
```routes
/bluearchive/news/jp/1
/bluearchive/news/jp/3
```
Just realized the type id is not correct 😅.
> fix(route): bluearchive jp incorrect news type

- lib/routes/telegram/channel.ts
N / A
```routes
NOROUTE
```
It would be better to have a script like `dev:docs` for rendering & serving the doc locally.
> doc(route): fix incorrect MD syntax

- lib/routes/notion/release.ts
N / A
```routes
/notion/release
```
> feat(route): introduce `/notion/release`

- lib/routes/metacritic/index.ts
Close #16057
```routes
/metacritic/game/metascore/releaseYearMin=2024&releaseYearMax=2024
```
The release year filters were simply not being passed to the metacritic api.
> fix(route): adds release year filters to metacritic

- lib/routes/neea/index.ts
- lib/routes/neea/jlpt.ts
- lib/routes/neea/namespace.ts
Close #
```routes
/neea/local/cet
/neea/local/ncre
/neea/global/jlpt
```
完善了路由描述并添加了 radar 规则
为了解决 jlpt 路由的优先级问题修改了原有的路由规则：
```routes
/neea/:type? -> /neea/local/:type
/neea/jlpt(not working) -> /neea/global/jlpt
```
但我不太确定这是否是一个合适的改动 :disappointed_relieved:
> fix(route/neea): fix routing priority and improve descriptions

- lib/routes/duckdb/namespace.ts
- lib/routes/duckdb/news.ts
Close #
```routes
/duckdb/news
```
> feat(route): add route for DuckDB news

- lib/routes/twitter/home.ts
- lib/routes/twitter/keyword.ts
- lib/routes/twitter/likes.ts
- lib/routes/twitter/list.ts
- lib/routes/twitter/media.ts
- lib/routes/twitter/namespace.ts
- lib/routes/twitter/user.ts
This PR fixes the documentation on how to configure the  "X (Twitter)" route.
https://github.com/DIYgod/RSSHub/commit/dc0f22265805e27f370d3ebb6c55e4d15722b565 added `TWITTER_AUTH_TOKEN` and https://github.com/DIYgod/RSSHub/commit/1db30b3ad1f8ff79da986f4c6c792b4dbc286480 removed `TWITTER_COOKIE`. Both changes were not documented, resulting in wrong instructions.
Close #16184
```routes
NOROUTE
```
> fix(docs): update outdated twitter configuration documentation

- lib/routes/nyaa/main.ts
- lib/routes/nyaa/namespace.ts
#15787 
Close #15782 
```routes
/nyaa/search/bocchi
/nyaa/user/ANiTorrent
/nyaa/user/ANiTorrent/search/bocchi
/nyaa/sukebei/search/hentai
/nyaa/sukebei/user/milannews
/nyaa/sukebei/user/milannews/search/hentai
```
The ctx.routerPath is empty, which previously led to the error:
TypeError: Cannot read properties of undefined (reading 'split').
I have fixed this bug and slightly adjusted the logic to make it workable.
Additionally, I have added a description of the use case.
> fix(route/nyaa): fix Nyaa and added descriptions

- docker-compose.yml
Close #
```routes
```
when I run `docker compose up -d` with the `docker-compose.yml` file in the root directory of this repo. The following error happens: 
> docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
So I want to remove the `version` attribute.
> chore: remove version attribute

- lib/routes/cffex/announcement.ts
- lib/routes/cffex/namespace.ts
N/A
```routes
/cffex/announcement
```
我的第一个 PR !!!
> feat(route): add cffex/announcement

- lib/routes/spotify/show.ts
`itunes_duration` should be in unit "second".
> fix(spotify): show's `itunes_duration`

- lib/routes/apnews/utils.ts
Close #
```routes
/apnews/topics/ap-top-news?limit=2
/apnews/topics/2024-paris-olympic-games?limit=2
/apnews/topics/music-videos?limit=2
/apnews/topics/regional-ap-video-us-only-?limit=2
```
> feat(route/apnews): Enhance support for video pages

- lib/routes/fediverse/timeline.ts
None
```routes
/fediverse/timeline/Mastodon@mastodon.social
```
- According to RFC 7033, sending WebFinger queries with `Accept` other than `application/jrd+json` may result in a non-JRD response.
> The client MAY include the "Accept"
header to indicate a desired representation; representations other
than JRD might be defined in future specifications.
- Check for ActivityPub media types when looking for AP `Actor` document. The first RD with `type=self` may points to things other than AP `Actor` document.
- Use `application/ld+json; profile="https://www.w3.org/ns/activitystreams"` as accept type when retrieving AP documents, according to the current ActivityPub specification:
> The client MUST specify an Accept header with the application/ld+json; …
> fix(route/fediverse): Fixes for ActivityPub

- lib/routes/141jav/index.ts
- lib/routes/141ppv/index.ts
Close #15473
```routes
/141ppv/new
/141ppv/popular
/141ppv/popular/7
/141ppv/random
/141ppv/random/7
/141ppv/date/2024/08/03
/141jav/new
/141jav/popular
/141jav/popular/7
/141jav/random
/141jav/random/7
/141jav/date/2024/08/03
/141jav/tag/Married%20Woman
/141jav/actress/Futaba%20Reena
```
> fix(route): 「141jav」和「141ppv」路由失效

- lib/routes/people/index.ts
Close #16388 
```routes
/people
/people/sc
```
现首页和各省市页RSS能够使用正确编码显示。
现首页`/people`
```rss
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
<channel>
<title>首页头条--人民网</title>
<link>http://www.people.com.cn/GB/59476</link>
<atom:link href="http://localhost:1200/people" rel="self" type="application/rss+xml"/>
<description>首页头条--人民网 - Powered by RSSHub</description>
<generator>RSSHub</generator>
<webMaster>contact@rsshub.app (RSSHub)</webMaster>
<language>en</language>
<lastBuildDate>Wed, 07 Aug 2024 08:35:45 GMT</lastBuildDate>
<ttl>5</ttl>
<item>
<title>暑运以来全国铁路发送旅客超5亿人次</title>
<description><div class="bza"><span></span><p></p></div> <div class="box_pic"></div> <p>　　新华社北京8月7日电（记者樊曦）记者7日从中国国家铁路集团有限公司获悉，自暑运启动以来，7月1日至8月6日，全国铁路累计发送旅客5.13亿人次，同比增长5.4%，突破5亿人次大关，日均发送旅客1386万人次。</p> …
```
> fix(route): people,handle diff site encoding.

- lib/routes/sjtu/jwc.ts
Close #
```routes
/sjtu/jwc
```
部分已删除的通知没有从索引列表中移除，导致抓取页面的时候产生FetchError错误。
> fix(route/sjtu/jwc): handle error when fetching sjtu/jwc article

- docker-compose.yml
- lib/registry.ts
Close #
```routes
NOROUTE
```
Due to path `/` and `/metrics` will load debug routes info, health checks may become unavailable when high level requests.
Therefore, a /healthz endpoint is provided to return ok , also health checks  added in docker-compose file
> feat: add healthz route for server health check

- lib/routes/iwara/subscriptions.ts
Close #16462
```routes
/iwara/subscriptions
```
The parameter in got() was named `data` instead of `body`, causing the JSON body not to be sent to the server.
> fix(route/iwara): fix user login failure

- lib/routes/flashcat/blog.ts
Close #
```routes
/flashcat/blog
```
When checking docs, I found that example route is a full path with namespace
> fix: invalid example route of flashcat blog

- lib/routes/scut/gzic/media.ts
- lib/routes/scut/gzic/news.ts
- lib/routes/scut/gzic/notice.ts
Close #
```routes
/scut/gzic/media
/scut/gzic/news
/scut/gzic/notice
/scut/gzic/notice/xsyg
/scut/gzic/notice/jytz
/scut/gzic/notice/hwxx
/scut/gzic/notice/swtz
```
> feat(route): 新增 华南理工大学广州国际校区通知公告、新闻聚焦、媒体报道 路由

- lib/routes/zsxq/types.ts
- lib/routes/zsxq/utils.ts
Close #
```routes
/zsxq/group/88855458825252
/zsxq/user/2414218251
```
使用 blockquote 元素引用问答型消息的提问部分，使浏览效果更接近原版样式，提升可读性
补充提问人与回答人用户名，进一步提升可读性
原网站样式：
修改前样式（使用 Fluent Reader）：
修改后样式（使用 Fluent Reader）：
> fix(route/zsxq): 优化问答型消息可读性

- lib/routes/bilibili/dynamic.ts
None
```routes
/bilibili/user/dynamic/672328094/disableEmbed=1
/bilibili/user/dynamic/1437582453/disableEmbed=1
/bilibili/user/dynamic/8047632
```
Since 2024-09-04 20:09 (UTC+8), the bilibili dynamic API `https://api.bilibili.com/x/polymer/web-dynamic/v1/feed/space` suddenly keeps returning `{ "code": -352, "message": "-352", "ttl": 1 }` in my personal project.
After investigation, the browser sends requests with more parameters attached, where `dm_img_list`, `dm_img_str`, `dm_cover_img_str` become required, and they all seem to be fingerprints for tracking purposes.
Reference from the blog: [浅度剖析B站的新 -352 风控策略](https://im.salty.fish/index.php/archives/revengr-bilibili-352.html)
- `dm_img_list`: JSON object, probably mouse activities.
- `dm_img_str`: Base64 encoded string, WebGL version, …
> fix(bilibili): fix `-352` error by mocking new required parameters

- lib/routes/bilibili/cache.ts
- lib/routes/bilibili/utils.ts
- lib/routes/bilibili/video.ts
Close #16717
```routes
/bilibili/user/video/14583962
```
> feat(route/bilibili): add getRenderData to bypass the risk control mechanism

- lib/routes/twitter/api/web-api/constants.ts
- lib/routes/twitter/list.ts
Close #
```routes
/twitter/list/221172095
/twitter/list/221172095/includeRts=false
```
Used the already existing `utils.excludeRetweet` to remote retweets from obtained list of tweets.
> fix(route): Twitter list API new query path and support include_rts

- lib/routes/tencent/news/author.ts
```routes
/tencent/news/author/5933889
/tencent/news/author/8QMf2XpZ7oIVvzjR
```
The original param can't fetch non-digital users
> fix: Tencent news can't fetch non-digital users

- lib/routes/lofter/collection.ts
Close #
```routes
/lofter/collection/20460170
/lofter/collection/20763900
```
通过合集ID(collectionID)，获取Lofter的合集内容；
首次提交PR，有问题请见谅；
根据/lofter/user修改得到。
> feat(route): 添加Lofter的合集获取功能

- lib/views/rss.tsx
Close #16747 
```routes
/telegram/channel/tnews365
/telegram/channel/DNSPODT
/telegram/channel/xhqcankao
```
这个很难说是inoreader或者哪个客户端的问题，不同客户端对同一份rss有着不同的表现。
最简单的办法当然是直接把telegram频道的rss中的image去掉：
https://github.com/DIYgod/RSSHub/blob/de188c3aa8038086f28b5ce73a62a752651b4eeb/lib/routes/telegram/channel.ts#L206
但频道的logo有时候还是有点用的，于是搜了下网上的资料，这方面不太懂，欢迎指正。
https://github.com/DIYgod/RSSHub/blob/de188c3aa8038086f28b5ce73a62a752651b4eeb/lib/views/rss.tsx#L9
[Atom规约](https://datatracker.ietf.org/doc/html/rfc4287#section-4.2.8)中的atom:logo起到一个banner的作用，同时Atom中还有一个atom:icon的元素起到favicon的作用。但[RSS 2.0 规范](https://cyber.harvard.edu/rss/rss.html#ltimagegtSubelementOfLtchannelgt)中，只有笼统的一个image元素，起到一个banner的作用。
image元素的可选子元素包含width和height，有默认值88、31，本项目中没加入这两个可选元素： …
> fix: 部分Telegram频道的文章在inoreader中显示一个巨大的logo

- lib/routes/sdu/namespace.ts
Close #
```routes
NOROUTE
```
原namespace`山东大学（威海）`路径使用`/sdu`，现在其路径下除威海校区通知网站外，已发展出青岛校区及济南校区的部分学院的通知网站，因此需要将namespace改为`山东大学`以减少歧义。
> fix: sdu namespace

- lib/routes/weibo/namespace.ts
- lib/routes/weibo/user.ts
Close #
```routes
/weibo/user/1195230310/showRetweeted=0
```
Introduce a new feature to filter retweeted posts in Weibo RSS feeds. 
Users can now choose whether to display retweeted Weibo posts by setting the `showRetweeted` parameter.
This parameter defaults to `true`, ensuring retweeted posts are shown unless explicitly disabled.
- Updated `namespace.ts` to include `showRetweeted` in the parameter options.
- Modified `user.ts` handler to respect the `showRetweeted` setting, filtering 
out retweeted posts when set to `false`.
> feat(route/weibo): add option to filter retweeted posts

- lib/routes/the/index.ts
Close #
```routes
/the
/the/category/rawj7o4ypewv94
/the/category/rawbcvxkktdkq8
/the/category/rawtn8jpsc6uvv
/the/category/rawrsnh9zakqdx
/the/category/raw4krvx85dh27
```
> fix(route/the): Fix timezone

- lib/routes/qiche365/namespace.ts
- lib/routes/qiche365/recall.ts
Close #15270
```routes
/qiche365/recall/1
/qiche365/recall/2
/qiche365/recall/3
/qiche365/recall/4
```
> feat(route): add route of qiche365

- lib/routes/dockerhub/utils.ts
Close #
```routes
/dockerhub/build/library/node
```
```json5
// images input
[
{
"architecture": "amd64",
"features": "",
"variant": null,
"digest": "sha256:f729d1a1b8afd4df4a78f27c27ca7d32361ea333ff0affd09daef0bf6ded2650",
"os": "linux",
"os_features": "",
"os_version": null,
"size": 404143176,
"status": "active",
"last_pulled": "2024-09-20T14:42:20.24159Z",
"last_pushed": "2024-09-18T03:39:41.751866Z"
},
{
"architecture": "unknown",
"features": "",
"variant": null,
"digest": "sha256:7df929747dd34b70808f781be322ebe6cff1716b3fae2ce4da4f1e8770e874cc",
"os": "unknown",
"os_features": "",
"os_version": null,
"size": 15734086,
"status": "active",
"last_pulled": "2024-09-20T14:42:54.112116Z",
"last_pushed": "2024-09-18T03:39:41.8979Z"
},
{
"architecture": "arm",
"features": "",
"variant": …
```
> fix(route/dockerhub): hash images

- lib/routes/whu/cs.ts
- lib/routes/whu/gs/index.ts
- lib/routes/whu/news.ts
No related issue.
```routes
/whu/news/0
/whu/news/1
/whu/news/2
/whu/news/3
/whu/cs/0
/whu/cs/1
/whu/cs/2
/whu/cs/3
/whu/gs/0
/whu/gs/1
/whu/gs/2
/whu/gs/3
```
本 PR 修复了/whu 路由下几个 RSS 的问题：
此前内部的爬虫解析程序编写有问题，在运行的时候会抛出异常，导致无法获取数据。
本 PR 修复了此 bug，并能正确获取数据。
效果对比如下：
此前 `/whu/gs/` 下的 category 参数无法被正常解析，会全部定向到类别 0。
修复之后，能够正确定位到指定的类别下。
- 为路由添加了说明文档等
- 并增加了基于数字符号的用法（原始用法需要输入复杂的字符串），新方案兼容旧方案，但是更加易用
> fix(route/whu): Fix the failedness of whu route

- lib/routes/espn/namespace.ts
- lib/routes/espn/news.ts
- lib/routes/espn/templates/media.art
Close #
```routes
/espn/news/nba
/espn/news/tennis
/espn/news/wnba
/espn/news/golf
/espn/news/nfl
/espn/news/cricket
/espn/news/mlb
/espn/news/soccer
/espn/news/f1
/espn/news/nhl
/espn/news/ncb
/espn/news/mma
/espn/news/ncf
/espn/news/ufl
/espn/news/rugby
/espn/news/poker
```
> feat(route): add feed for ESPN News

- lib/routes/51cto/recommend.ts
```routes
/51cto/index/recommend
```
原本只能提供摘要，在原来的基础上增加了正文解析
Originally, only summaries could be provided.  And now, the text parsing has been added.
Before:
After:
> feat(route): Add 51CTO  text parsing

- lib/routes/sdu/gjsw.ts
- lib/routes/sdu/qd/xszxqd.ts
- lib/routes/sdu/ygb.ts
Close #
```routes
/sdu/gjsw/tzgg
/sdu/qd/xszxqd/xtyw
/sdu/qd/xszxqd/xttz-yjs
/sdu/qd/xszxqd/xttz-bks
/sdu/qd/xszxqd/xttz-tx
/sdu/qd/xszxqd/xttz-xl
/sdu/ygb/zytz
/sdu/ygb/glfw
/sdu/ygb/cxsj
```
`/sdu/qd/xszxqd/`需校园内网环境访问，经测试内网部署通过
> feat(route): add 山青学生在线、山大研工部、山大国际网站

- lib/routes/nicovideo/namespace.ts
- lib/routes/nicovideo/templates/video.art
- lib/routes/nicovideo/types.ts
- lib/routes/nicovideo/utils.ts
- lib/routes/nicovideo/video.ts
Close #
```routes
/nicovideo/user/16690815/video
```
> feat(route): nicovideo

- lib/routes/the/index.ts
> feat(route/the): Include publisher in the author property

- lib/routes/ncku/csie.ts
- lib/routes/ncku/namespace.ts
Close #
```routes
/ncku/csie
/ncku/csie/_all
/ncku/csie/jobs
```
國立成功大學資訊工程學系公告
> feat(route): NCKU CSIE News

- lib/routes/bilibili/followings-dynamic.ts
Close #16912 
```routes
/bilibili/followings/dynamic/123456789
```
Issue 中由于 parsed.origin 为 string 类型而解析失败，且之前在解析 parsed 时已经一并解析了 origin，于是删除二次解析的步骤，以下是解析成功的结果
```xml
<item>
<title>切片吃点好的 （约稿私企鹅</title>
<description>切片吃点好的 （约稿私企鹅</description>
<link>https://t.bilibili.com/980922770377408520</link>
<guid isPermaLink="false">https://t.bilibili.com/980922770377408520</guid>
<pubDate>Wed, 25 Sep 2024 01:21:20 GMT</pubDate>
<author>蒜蓉小龙虾Lesiry</author>
</item>
```
> fix(route): fix bilibili followings-dynamic parse error

- lib/routes/ceph/blog.ts
- lib/routes/ceph/namespace.ts
N/A
```routes
/ceph/blog/
/ceph/blog/a11y
```
为 ceph 博客添加 rss feed
> feat(routes/ceph): add ceph blog

- lib/routes/mi/crowdfunding.ts
- lib/routes/mi/templates/crowdfunding.art
- lib/routes/mi/types.ts
- lib/routes/mi/utils.ts
Close #
```routes
/mi/crowdfunding
```
1. refactor crowdfunding with ofetch and art-template
> feat(route/mi): refactor crowdfunding with ofetch and art-template

- lib/routes/sciencenet/user.ts
Close #17005
```routes
/sciencenet/user/周浙昆?limit=10
```
因为是通过科学网用户博客的官方 rss 来获取文章信息的，但官方的是正序排序的，所以这里改为倒序获取
> fix(route/sciencenet): 修复科学网 - 用户博客没有按照时间线倒序排序

- lib/routes/bilibili/vsearch.ts
Close #
```routes
/bilibili/vsearch/摄影/totalrank/false/0
```
hit_columns 可能返回 null，这里需要新增一个判空
> fix(route): bilibili vsearch

- lib/routes/misskey/utils.ts
Close #
```routes
/misskey/users/notes/mttb2ccp@misskey.io
```
Sorry, I didn't realize (#17068) that this API returns file attachments even without `withFiles: true`. The real issue affecting the reading experience is that renotes weren't properly handled, resulting in a lot of empty content.
> fix(misskey): Handle renotes properly to improve content display

- lib/routes/tvb/news.ts
Open #17097 
```routes
/tvb/news
```
将原来的link里面的二级域名inews-api更换为news即可修正问题
> fix(route): change url in `/tvb/news`

- lib/routes/aibase/discover.ts
- lib/routes/aibase/namespace.ts
- lib/routes/aibase/templates/description.art
- lib/routes/aibase/topic.ts
- lib/routes/aibase/util.ts
Close #16877
```routes
/aibase/discover
/aibase/topic/AI
```
> feat(route): add AIbase

- docker-compose.yml
- lib/routes/weibo/user.ts
Close #17090
```routes
```
微博Radar规则优化，由于[Radar规则生成的逻辑](https://github.com/DIYgod/RSSHub/blob/2de569b4d2f0c83ffdd4334b04f51950481242e4/lib/api/radar/rules/all.ts#L15-L18)，source列表中的所有元素必须为相同的hostname才有效
> fix(route/weibo): Solve the problem that Weibo Radar rules cannot be generated correctly

- lib/routes/nudt/yjszs.ts
Close #
```routes
/nudt/yjszs
/nudt/yjszs/2
/nudt/yjszs/1
/nudt/yjszs/8
/nudt/yjszs/12
/nudt/yjszs/16
/nudt/yjszs/17
/nudt/yjszs/23
/nudt/yjszs/25
```
- 稍微修改了以前的路由参数
- 增加了国防科技大学研究生院更多的RSS源
- 增加了radar
> feat(route/nudt): Add more RSS source about yjszs

- lib/routes/misskey/templates/note.art
- lib/routes/misskey/types.ts
- lib/routes/misskey/user-timeline.ts
- lib/routes/misskey/utils.ts
Close #
```routes
/misskey/users/notes/mttb2ccp@misskey.io
/misskey/users/notes/mttb2ccp@misskey.io/withRenotes=true
/misskey/users/notes/mttb2ccp@misskey.io/mediaOnly=true
```
- Add optional route parameters `withRenotes` and `mediaOnly`
- Update route documentation with new parameter descriptions and examples
- Modify `parseNotes` function to handle renotes
> feat(misskey): add withRenotes and mediaOnly options for user timeline

- lib/routes/douban/people/status.ts
```routes
/douban/people/29449961/status
```
同步 #17224 的修改
> fix(route): douban status item link

- lib/routes/10jqka/namespace.ts
- lib/routes/10jqka/realtimenews.ts
Close #17269
```routes
/10jqka/realtimenews
```
> feat(route): add 同花顺财经7×24小时要闻直播

- lib/middleware/anti-hotlink.ts
Close #12841
```routes
NOROUTE
```
将HOTLINK_TEMPLATE环境变量应用于音频和视频链接
> feat: HOTLINK_TEMPLATE environment variable applied to audio and video link

- lib/routes/dxy/board.ts
- lib/routes/dxy/profile/thread.ts
- lib/routes/dxy/special.ts
- lib/routes/dxy/types.ts
- lib/routes/dxy/utils.ts
Close #17248
```routes
/dxy/bbs/board/46
```
> feat(route): dxy board

- lib/routes/hko/earthquake.ts
#17297 
```routes
/hko/earthquake
```
修复issue #17297 问题，之前的parseDate方法中的格式参数使用错误了。
> fix: hko earthquake route pubDate issue fixing

- lib/routes/rsshub/transform/html.ts
Close #
```routes
/rsshub/transform/html/https%3A%2F%2Fllwslc.github.io%2Fgrammar-club%2Fcontent%2FPreface.html/title%3Dgrammar-club%26item%3D%20header%20%3E%20div.links%20%3E%20nav%20%3E%20div%20%26itemLink%3Da
/rsshub/transform/html/https%3A%2F%2Fbionumpy.github.io%2Fbionumpy%2Fmenu.html/itemLink%3Da
```
When the `href` link inside the element is a relative link, the original handling would obtain an incorrect full link
This is the official documentation for numpy `https://numpy.org/doc/stable/user/index.html`, where most `a` tags have relative links. Here is the code effect before and after modification based on this site
item href     |    ``` `${new URL(url).origin}${link}` ``` | ``` (new URL(link, url)).href  ```
---- | ----- | -----
`whatisnumpy.html` | …
> fix(route): get correct item link

- lib/routes/twitter/home-latest.ts
- lib/routes/twitter/home.ts
- lib/routes/twitter/likes.ts
- lib/routes/twitter/list.ts
- lib/routes/twitter/namespace.ts
- lib/routes/twitter/utils.ts
Close #
```routes
/twitter/home
/twitter/likes/DIYgod
/twitter/list/221172095
```
Add an option to only display tweets that contains a media. Effectively this excludes "text only" tweets, but as the filtering itself is mroe "keep only medias" I prefered to name it that way. I don't know your preferences about it.
Didn't add this option to the `user` route as there is the `media` route that basically does the same.
Added info in the params table, though as it isn't added to every route I'm not too sure (though same params in that list are not on all routes anyways).
> feat(twitter): only display tweets that contains a media

- lib/config.ts
- lib/routes/twitter/api/mobile-api/login.ts
- lib/routes/twitter/api/mobile-api/token.ts
Close #
```routes
```
- Implement the `LoginEnterAlternateIdentifierSubtask` task and added an environment variable `TWITTER_PHONE_OR_EMAIL` for this purpose.
增加对登录风控触发 `LoginEnterAlternateIdentifierSubtask` 时的处理，并为此增加了一个环境变量 `TWITTER_PHONE_OR_EMAIL`。
- Refactored the flow control of the login flow for easier maintenance.
重写了登录的工作流。
> feat(twitter): support LoginEnterAlternateIdentifierSubtask task and better login flow controll

- lib/routes/twitter/api/web-api/utils.ts
> fix(route/twitter): Prevent storing empty cookie if obtaining such from `auth_token` failed.

- lib/routes/bilibili/dynamic.ts
- lib/routes/bilibili/templates/description.art
fix #17414
Close #17414
```routes
/bilibili/user/dynamic/25876945
```
> fix(route): 修复 bilibili 动态路由在部分情况下出现空图片的问题

- lib/routes/twitter/api/web-api/utils.ts
Close #
```routes
NOROUTE
```
This PR fix the minor bug that we didn't `await` when we get cache.
Because of that, we will always get empty string when we call `token2Cookie`
> fix(route/twitter): await when get cache

- lib/routes/hamel/index.ts
- lib/routes/hamel/namespace.ts
Close #
```routes
/hamel/blog
```
Hamel Husain's blog ([hamel.dev](https://hamel.dev/)) delves into AI, data science, and machine learning with a strong focus on practical applications and open-source contributions. Hamel, a prominent figure in AI and GitHub development, shares tutorials, insights on AI tooling, and real-world case studies, offering valuable guidance for developers and data scientists alike.
Hamel Husain 的博客（[hamel.dev](https://hamel.dev/)）探讨了 AI、数据科学和机器学习领域，特别关注实际应用和开源项目。Hamel 作为 AI 和 GitHub 开发的知名人物，分享了工具教程、AI 实践见解和真实案例，为开发者和数据科学家提供了宝贵的指导。
> feat(route): add the hamel blog

- lib/routes/nytimes/rss.ts
Close #
```routes
/nytimes/HomePage
```
> feat(route/nytimes): Add support for EN version

- lib/middleware/access-control.ts
- lib/views/error.tsx
Close #
```routes
NOROUTE
```
- Fix line breaks in error messages to display properly
- Show the actual request path that generated the code (access-control)
|  ENV | Before | After |
|-------------|--------|-------|
| Dev | ![Dev Before](https://github.com/user-attachments/assets/5b724aed-56c7-45f4-84a8-8d7670a72c5f) | ![Dev After](https://github.com/user-attachments/assets/ad89f74a-bc63-4aae-a294-d6f4f40b2db5) |
| Prod | ![Prod Before](https://github.com/user-attachments/assets/7a4ac75f-4aa4-4430-ae62-a2871282240a) | ![Prod After](https://github.com/user-attachments/assets/1cbf5369-aa1e-491e-a398-5bf76c1b45f4) |
> feat: better error message display

- lib/config.ts
- lib/utils/ofetch.ts
- lib/utils/request-rewriter/fetch.test.ts
- lib/utils/request-rewriter/fetch.ts
Close #17496
```routes
/test/1
```
> chore: disable remote debugger by default

- lib/routes/last-origin/namespace.ts
- lib/routes/last-origin/news.ts
```routes
/last-origin/news
```
> feat(route): add LastOrigin日本官网公告

- lib/routes/discord/search.ts
Close #
```routes
/discord/search/302094807046684672/content=friendly&has=image,video
```
Related PR: #17522
Fix runtime error caused by missing `__dirname` definition in Discord search route.
> fix(route/discord): add missing `__dirname` definition in search route

- lib/routes/caixin/latest.ts
- lib/routes/caixin/utils-fulltext.ts
Close #
```routes
/caixin/latest
```
> feat(route/caixin): Add support for photos channel. Example: https://photos.caixin.com/2024-11-02/102252287.html

- lib/routes/misskey/utils.ts
Close #
```routes
NOROUTE
```
I'm currently unable to find any test users with renotes from non-Misskey instances for verifying the route
> fix(misskey): Use renote ID for cross-instance notes

- scripts/workflow/test-route/test.mjs
Close #
```routes
NOROUTE
```
There is a URL display issue in route test comments.
When URLs contain `&` (like `&not`), they are parsed as HTML entities by GitHub and displayed as special characters (like `¬`), as seen in #17500.
The fix is simple: convert `&` to `&amp;` when displaying URL text. This change only affects the display and doesn't change the actual URL functionality.
I have tested it here: https://github.com/SnowAgar25/RSSHub/pull/2
> chore: escape HTML entity in route test URL display

- lib/routes/wallstreetcn/calendar.ts
- lib/routes/wallstreetcn/hot.ts
- lib/routes/wallstreetcn/live.ts
- lib/routes/wallstreetcn/news.ts
Close #13933
```routes
/wallstreetcn/calendar
/wallstreetcn/calendar/report
```
> feat(route): wallstreetcn

- lib/routes/idolmaster/namespace.ts
- lib/routes/idolmaster/news.ts
Close #
```routes
/idolmaster/news
/idolmaster/news/brand=MILLIONLIVE&brand=SHINYCOLORS&category=GAME&category=ANIME
```
> feat(route): add idolmaster news

- lib/routes/xiaohongshu/user.ts
Reason for revert: The change did not meet the expected behavior or caused issues.
Close #17602 
```routes
/xiaohongshu/user/:user_id/notes/fulltext
/xiaohongshu/user/:user_id/:category
```
> revert(route/xiaohongshu): add current time as pubDate

- lib/middleware/cache.ts
…imit
Close #
```routes
/test/1
```
> fix(core/cache): update cache key generation to include query limit

- package.json
- pnpm-lock.yaml
```routes
NOROUTE
```
Slightly related to #14901, but not enough to solve it.
<https://github.com/SukkaW/nolyfill>
> chore: use some lighter dependencies

- lib/routes/cnki/author.ts
- lib/routes/cnki/utils.ts
Close #16927
```routes
/cnki/author/丁晓东/中国人民大学
```
需要使用国内或自建服务
> fix(cnki): deprecate author articles with `:code`, now use `:name` and `:company` instead

- lib/routes/dockerhub/repositories.ts
- 新增 DockerHub 仓库路由，支持获取指定用户的仓库列表
- 支持分页获取仓库信息，默认每页10条记录
Close #
```routes
/dockerhub/repositories/library
/dockerhub/repositories/DIYgod
```
> feat(dockerhub): 添加 DockerHub 仓库路由

- lib/routes/wallstreetcn/news.ts
修复 wallstreetcn 
```
TypeError: Cannot read properties of undefined (reading 'display_name')
```
```routes
/wallstreetcn/news/tmt
/wallstreetcn/news/global
```
> fix(wallstreetcn): crash when article delete

- lib/routes/parliament.uk/namespace.ts
- lib/routes/parliament.uk/petitions.ts
- lib/routes/parliament.uk/templates/description.art
Close #17708
```routes
/parliament.uk/petitions/all
```
> feat(route): add UK Parliament Petitions

- lib/routes/joneslanglasalle/index.ts
- lib/routes/joneslanglasalle/namespace.ts
- lib/routes/joneslanglasalle/templates/description.art
Close #17618
```routes
/joneslanglasalle/zh/trends-and-insights
```
> feat(route): add Jones Lang LaSalle Trends & Insights

- lib/routes/amz123/kx.ts
- lib/routes/amz123/namespace.ts
Close #
```routes
/amz123/kx
```
response example
```
{
"resource_id": 1375642,
"id": "JIFqoxf0",
"fid": 4,
"title": "越南法案正式通过，Shopee等平台明年4月起将代卖家申报纳税",
"title_open": false,
"thumb": "https://img.amz123.com/upload/image_cloud/202406/1718070662500543_%E6%88%B7%E5%A4%961.jpg",
"description": "AMZ123获悉，12月2日，据外媒报道，越南国会通过了《税务管理法》修正案，规定从2025年4月1日起，电商平台和具支付功能的数字平台管理者将承担为在其平台上运营的卖家代扣代缴税款的责任。\n据悉，该修正案在上周五获得了近93%的投票支持，新增了九项条款，要求国内外电商平台和数字服务提供商为其平台上的卖家申报并缴纳税款。若卖家不符合平台代扣代缴的条件，则需自行注册、申报并纳税。越南政府表示，将发布详细的纳税申报指南，明确平台与卖家在税务申报中的具体职责。",
"content": "",
"published_at": 1733132762,
"status": 1,
"tags": [],
"views": 107,
"favorites": 0,
"likes": 0,
"comments": 0,
"author": {
"uid": 0,
"username": "该用户已注销",
"avatar": "https://img.amz123.com/upload/avatar/default_avatar.png",
"introduction": "", …
```
> feat(route): add  amz123.com

- lib/routes/qweather/3days.ts
- lib/routes/qweather/now.ts
qweather route example inaccuracy
Close #
```routes
/qweather/now/北京
```
- [ x ] New Route / 新的路由
> fix: qweather route example inaccuracy.

- lib/routes/duckdb/news.ts
Close #
```routes
/duckdb/news
```
Due to the update of the DuckDB Blog page layout, the old way of fetching links is not working
> fix(route/duckdb): change blogs link and author

- lib/routes/whu/swrh.ts
Close #
```routes
/whu/swrh/2
```
> feat(route): add route for university: whu swrh

- lib/routes/gdufs/namespace.ts
- lib/routes/gdufs/news.ts
- lib/routes/gdufs/xwxy/xwxy-news.ts
Close #
```routes
/gdufs/news
/gdufs/xwxy-news
```
> feat(route): add GDUFS news route and GDUFS xwxy news

- lib/routes/kuaishou/profile.ts
Close #
```routes
NOROUTE
```
The extra indentation causes failure of parsing during Docs rendering. The parser will wrap the latter content until the next `:::` into tips
> docs: fix tip wrapper in document

- lib/routes/163/music/djradio.ts
- lib/routes/163/templates/music/djradio-content.art
None
```routes
/163/music/djradio/312
/163/music/djradio/312/0
```
in most cast,the djradio route was subscribe by some podcast app, and because the app support `enclosure` tag, the link in the description is duplicate, this PR aim to remove duplicate part for the route.
duplicate example:
update: this has changed to option
> fix(163/music/djradio): add option for info

- lib/routes/anthropic/namespace.ts
- lib/routes/anthropic/news.ts
Close #17959
```routes
```
This RSS is the latest news related to [Anthropic](https://www.anthropic.com/), a leading LLM developer.
> feat(route): Add RSS feed for latest news from Anthropic (a leading LLM developer).

- lib/routes/blizzard/news.ts
Close #17790
```routes
/blizzard/news
/blizzard/news/zh-tw
/blizzard/news/zh-tw/starcraft2
```
此次更换了 api 请求新闻的方式，api 接口里有个 newsUrl 指向网页，但有些网址会被重定向跳转，例如：
1. [接口返回的地址](https://news.blizzard.com/zh-tw/article/23762796/2-4) 实际上会被重定向：[真实地址](https://news.blizzard.com/zh-tw/article/23762796/ii-2-4)
2. [接口返回的地址](https://news.blizzard.com/zh-tw/article/24146047/%E9%87%8D%E6%BA%AB%E5%88%BA%E6%BF%80%E6%88%B0%E9%AC%A5) 实际上会被重定向：[真实地址](https://news.blizzard.com/zh-tw/article/24146047/%E5%9C%A8%E3%80%8A%E9%AC%A5%E9%99%A3%E7%89%B9%E6%94%BB%E3%80%8B%EF%BC%9A%E7%B6%93%E5%85%B8%E6%A8%A1%E5%BC%8F%E9%AB%94%E9%A9%97%E6%98%94%E6%97%A5%E7%BE%8E%E5%A5%BD)
但实际不影响使用，只是这类接口返回的地址可能会返回英文版的 description，我认为是小部分链接才会如此所以是可以接受的。我也观察了整个api接口数据以及页面结构数据，都是没有返回我提到的真实链接的…
> fix(blizzard): 新闻路由报错不能使用

- lib/routes/ali213/zl.ts
Close #
```routes
/ali213/zl
```
> feat(route): add 游侠网大侠号

- lib/routes/huggingface/blog.ts
Close #
```routes
/huggingface/blog
```
> feat(route): add huggingface english blog

- lib/routes/weibo/utils.ts
Close #
```routes
/weibo/user/3261134763
/weibo/user/1794603954
/weibo/user/7188709684
```
Because the wrong livePhoto type was used in the code, it failed to retrieve the correct information.
由于取源数据的 livePhoto 使用的类型错误的使用了 livephotos 字段，导致了数据的获取异常。
below is the source data  demo
下面是源数据 demo
**so the correct key should be livephoto , not livephotos .**
正确的 key 应该是 livephoto ，而不是 livephotos 。
> fix: weibo livephoto get wrong object key

- lib/routes/oschina/user.ts
None
```routes
oschina/u/6150560
```
fix wrong link in previous route, https://my.oschina.net/6150560 should be https://my.oschina.net/u/6150560
> fix(routes/oschina/user): fix wrong link for user

- lib/routes/chinacdc/index.ts
Close https://github.com/DIYgod/RSSHub/issues/17995
```routes
/chinacdc/zxyw
```
> fix(route/chinacdc/index): add link for index route

- lib/routes/hiring.cafe/jobs.ts
Close #
```routes
/hiring.cafe/jobs/sustainability
/hiring.cafe/jobs/python 
```
- Introduced `estimated_publish_date_millis` to `ProcessedJobData` interface.
- Removed the old `estimated_publish_date` from `JobResult` interface.
- Updated `transformJobItem` function to use the new `estimated_publish_date_millis` for publication date formatting.
> fix(hiringcafe): correct pubDate parsing

- lib/routes/msn/index.ts
Close #
```routes
/msn/zh-cn/新华社/sr-vid-769jkard8p2sjcwjkv264h2divi25i5qk62whg7yq8akhwk23p6a?mode=fulltext&format=json
/msn/zh-cn/人民网/sr-vid-jwtjursmmc5egygacdnch06pxwhgdhk4in2r85yucvdgfgyhnsbs?mode=fulltext&format=json
/msn/zh-cn/澎湃新闻/sr-vid-kr7w4fq563568erb38y3ae3gr34vqe8vt4fr4sk574d69hu9h73s?mode=fulltext&format=json
/msn/zh-cn/红星新闻/sr-vid-ed4u3ky0u6b59hu83thk3pyy0fn6dfbnsyxsb79fvvsj34d0yk0s?mode=fulltext&format=json
/msn/zh-hk/AFP/sr-vid-3kv7h73mtcdhywg28d4f9ihgi4xcniq2ubb83iikdu3qwmbd73pa?mode=fulltext&format=json
/msn/zh-tw/Bloomberg/sr-vid-08gw7ky4u229xjsjvnf4n6n7v67gxm0pjmv9fr4y2x9jjmwcri4s?mode=fulltext&format=json
```
> feat(route): fix images not displaying in msn news full text

- lib/routes/visionias/namespace.ts
- lib/routes/visionias/news-today.ts
- lib/routes/visionias/templates/description-sub.art
- lib/routes/visionias/templates/description.art
- lib/routes/visionias/utils.ts
- lib/routes/visionias/weekly-focus.ts
Close #
```routes
/visionias/newsToday
/visionias/weeklyFocus
/visionias/newsToday/all
```
> feat(add route): VisionIAS route for daily news

- lib/routes/dlnews/category.ts
- lib/routes/finology/bullets.ts
- lib/routes/finology/category.ts
- lib/routes/finology/most-viewed.ts
- lib/routes/finology/tag.ts
- lib/routes/finology/utils.ts
- lib/types.ts
Close #
```routes
/finology/bullets
/finology/category/success-stories
/finology/most-viewed
/finology/tag/airline-industry
```
> fix(Finology): fixed Finology routes to new standards

- lib/routes/30secondsofcode/category.ts
- lib/routes/30secondsofcode/namespace.ts
- lib/routes/30secondsofcode/new-and-popular.ts
- lib/routes/30secondsofcode/utils.ts
Close #
```routes
/30secondsofcode/latest
/30secondsofcode/category/react
/30secondsofcode/category/css/interactivity
```
> feat: Added Route for 30secondsofcode

- lib/routes/steam/curator.ts
- lib/routes/steam/templates/curator-description.art
Close #
```routes
/steam/curator/34646096-80-Days
/steam/curator/34646096-80-Days/curations=0
/steam/curator/34646096-80-Days/curations=0&tagids=19
```
- [ x ] Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
> feat(add route): Add steam curator reviews route

- lib/routes/chinaratings/credit-research.ts
- lib/routes/chinaratings/namespace.ts
Close #18057
```routes
/chinaratings/CreditResearch
```
> feat(route): add 中债资信评估有限责任公司中债研究

- lib/routes/iknowwhatyoudownload/daily.ts
- lib/routes/iknowwhatyoudownload/namespace.ts
- lib/routes/iknowwhatyoudownload/templates/daily.art
Close #
```routes
/iknowwhatyoudownload/stats/daily/CN
/iknowwhatyoudownload/stats/daily/US
```
> feat(route): add iknowwhatyoudownload daily stats

- lib/routes/scientificamerican/namespace.ts
- lib/routes/scientificamerican/podcast.ts
- lib/routes/scientificamerican/templates/description.art
Close #
```routes
/scientificamerican/podcast
```
> feat(route): add Scientific American Podcasts

- lib/routes/gamebase/news.ts
- lib/routes/gamebase/templates/description.art
Close #18124
```routes
/gamebase/news
```
> fix(route): 遊戲基地新聞

- lib/routes/geocaching/blogs.ts
- lib/routes/geocaching/templates/blogs.art
Close #18137
```routes
/geocaching/blogs
/geocaching/blogs/en
/geocaching/blogs/de
/geocaching/blogs/fr
/geocaching/blogs/es
/geocaching/blogs/nl
/geocaching/blogs/cs
/geocaching/blogs/all
```
Add language parameter to blogs route and update response structure.
> feat(route/geocaching): add lang param, update response structure

- lib/routes/txks/namespace.ts
- lib/routes/txks/news.ts
Close #
```routes
/txks/news
```
> feat(route/txks): add www.txks.org.cn (工信部全国通信专业技术人员职业水平考试)

- lib/routes/gcores/namespace.ts
- lib/routes/gcores/news.ts
- lib/routes/gcores/templates/description.art
- lib/routes/gcores/util.ts
Close #
```routes
/gcores/news
```
> feat(route): add 机核网资讯

- lib/routes/wohnnet/index.ts
- lib/routes/wohnnet/namespace.ts
Close #
```routes
/wohnnet/mietwohnungen/wien
/wohnnet/mietwohnungen/wien/unterregionen=g90101
/wohnnet/mietwohnungen/wien/unterregionen=g90101&merkmale=balkon
```
Date/time not available; https://wohnnet.at/immobilien unfortunately doesn't have any publish date information in its markup.
> feat(route): Add wohnnet.at real estate search engine

- lib/routes/publico/ciencias.ts
- lib/routes/publico/culturas.ts
- lib/routes/publico/economia.ts
- lib/routes/publico/internacional.ts
- lib/routes/publico/items-processor.ts
- lib/routes/publico/mujer.ts
- lib/routes/publico/namespace.ts
- lib/routes/publico/opinion.ts
- lib/routes/publico/politica.ts
- lib/routes/publico/public.ts
- lib/routes/publico/sociedad.ts
- lib/routes/publico/tremending.ts
- lib/routes/publico/vinetas.ts
Close #
```routes
/publico/ciencias
/publico/ciencias/investigacion
/publico/culturas
/publico/culturas/libros
/publico/economia
/publico/economia/vivienda
/publico/internacional
/publico/internacional/eeuu
/publico/mujer
/publico/mujer/igualdad
/publico/opinion
/publico/opinion/vinetas
/publico/politica
/publico/politica/gobierno
/publico/public
/publico/sociedad
/publico/sociedad/m-ambiente
/publico/tremending
```
> feat(route): add publico.es

- lib/routes/shopify/apps/[handle].reviews.ts
- lib/routes/shopify/apps/search.ts
- 修改 language 属性，统一将 'en-US' 更改为 'en-us'
- 改进 `/shopify/apps/search/:q` 路由参数校验逻辑，避免空查询返回无效值
```routes
/shopify/apps/flow/reviews
/shopify/apps/search/flow
```
> fix(routes): 修复 Shopify 路由语言代码不一致的问题

- lib/routes/meituan/tech.ts
Close #
```routes
/meituan/tech
```
> feat(routes/meituan): add full text support for meituan tech

- lib/routes/joshwcomeau/latest.ts
- lib/routes/joshwcomeau/namespace.ts
- lib/routes/joshwcomeau/popular.ts
- lib/routes/joshwcomeau/utils.ts
Close #
```routes
/joshwcomeau/latest/javascript
/joshwcomeau/latest
/joshwcomeau/popular
```
> feat(joshwcomeau): add new Routes josh w comeau

- lib/routes/zaobao/util.ts
Close #
```routes
/zaobao/realtime/singapore
/zaobao/realtime/world
```
This PR removes the `button` (and `div`) elements that are used for display Google Ads by Zaobao that are not sanitized properly. They are being displayed by some RSS readers as a dangling eye-sore.
Before:
```html
<p>知情人士称，美国将把驻华外交使团规模削减高达10%。</p><p>据香港《南华早报》星期四（2月20日）报道，关于此次史无前例的削减行动，驻中国大陆和香港的美国外交官以及当地雇员，可能最早会在星期五（21日）收到关于规模削减的通知。</p><p>报道引述要求匿名的知情人士称，驻北京的大使馆，驻广州、上海、沈阳和武汉的总领事馆，以及驻港澳总领事馆将受到削减行动的影响。</p><div id="dfp-ad-imu1-wrapper" class="bff-google-ad google-ad flex w-full flex-row justify-center overflow-x-hidden my-[16px]"> <button class="min-w-[300px]" id="dfp-ad-imu1"></button> </div><p>报道称，目前尚不清楚受削减行动影响的人员是否会被调派到外交部门的其他单位，但预计会有裁员行动。美国国务院尚未置评。</p><p>路透社上星期引述消息人士报道，作为总统特朗普努力整顿美国外交使团的一部分，特朗普政府 …
```
> fix(zaobao): remove google ads buttons

- lib/routes/instructables/projects.ts
Close #
```routes
/instructables/projects?limit=3
/instructables/projects/circuits?limit=3
/instructables/projects/workshop?limit=3
/instructables/projects/craft?limit=3
/instructables/projects/cooking?limit=3
/instructables/projects/living?limit=3
/instructables/projects/outside?limit=3
/instructables/projects/teachers?limit=3
```
从目标页面获取访问 API 需要的 key，添加 limit 参数。
> fix(route/instructables): get api key from #js-page-context

- lib/routes/toranoana/namespace.ts
- lib/routes/toranoana/news.ts
Close #18386
```routes
/toranoana/news
/toranoana/news/dojin
/toranoana/news/comic
/toranoana/news/media
/toranoana/news/hobby
/toranoana/news/fair
/toranoana/news/shop
/toranoana/news/tuhan
/toranoana/news/toragen
/toranoana/news/etc
/toranoana/news/ebook
/toranoana/news/campaign
/toranoana/news/exhibition
/toranoana/news/shop-fair
/toranoana/news/circle-introduction
/toranoana/news/%e3%81%a8%e3%82%89%e3%81%ae%e3%81%82%e3%81%aax%e9%9f%93%e5%9b%bd
/toranoana/news/pc%e3%82%b2%e3%83%bc%e3%83%a0
/toranoana/news/%e4%b8%80%e8%88%ac%e3%82%b2%e3%83%bc%e3%83%a0
/toranoana/news/joshi
/toranoana/news/%e3%82%a2%e3%83%97%e3%83%aa
/toranoana/news/bl%e5%88%9d%e5%bf%83%e8%80%85%e3%81%ab%e3%81%8a%e3%81%99%e3%81%99%e3%82%81%e3%82%b3%e3%83%9f%e3%83%83%e3%82%af
/toranoana/news/toramatsuri-2020-summer …
```
> feat(route): add news route for toranoana.jp

- lib/routes/nhentai/util.ts
```routes
/nhentai/index/language/chinese
```
有时候，源站的略缩图会带上冗余的`.webp`后缀，将转换得到错误的高清图片地址。这个patch临时修复了这一情况。
一个错误的rss.xml片段如下：
```
<?xml version="1.0" encoding="UTF-8"?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
<channel>
<title>nhentai - language - chinese</title>
<link>https://nhentai.net/language/chinese/</link>
<atom:link href="http://rsshub.i7mc.com/nhentai/index/language/chinese" rel="self"
type="application/rss+xml" />
<description>hentai - Powered by RSSHub</description>
<generator>RSSHub</generator>
<webMaster>contact@rsshub.app (RSSHub)</webMaster>
<language>en</language>
<lastBuildDate>Tue, 04 Mar 2025 11:13:23 GMT</lastBuildDate>
<ttl>5</ttl>
<item>
<title>[Wolfanine] Special Order (Tavern of Spear)翻译</title>
<description>&lt;img …
```
> fix nhentai

- lib/routes/bullionvault/gold-news.ts
- lib/routes/bullionvault/namespace.ts
Close #18732
```routes
/bullionvault/gold-news
```
> feat(route): add BullionVault Gold News

- lib/routes/readhub/daily.ts
- 修复了 `/readhub/daily` 路由 logo 显示不正确的问题
- 修复了 `/readhub/daily` 路由 标题 中出现重复的 ` - Readhub` 的问题
```routes
/readhub/daily
```
Readhub daily 这个路由下手动配置的 image 图片是一张长图，而非方形，导致 logo 显示不全，怪怪的，改成了官网的方形 icon 图。
> fix: 修复 `/readhub/daily` 路由 logo 和标题显示的问题

- lib/routes/hanime1/previews.ts
Close #
```routes
/hanime1/previews/202504
```
Hanime1 新番预览加载预览图修复
> fix(route): fix hanime1 previews video posters not displaying

- lib/routes/cosplaytele/article.ts
- lib/routes/cosplaytele/category.ts
- lib/routes/cosplaytele/latest.ts
- lib/routes/cosplaytele/popular.ts
- lib/routes/cosplaytele/tag.ts
Close #
```routes
/cosplaytele
/cosplaytele/category/cosplay
/cosplaytele/tag/aqua
/cosplaytele/popular/7
```
> fix(route/cosplaytele): revert to iterative content fetching due to WP JSON API being disabled

- lib/routes/hpoi/info.ts
Close #
```routes
/hpoi/info/all
/hpoi/info/confirm
/hpoi/info/official
/hpoi/info/preorder
/hpoi/info/delay
/hpoi/info/release
/hpoi/info/reorder
/hpoi/info/hobby
/hpoi/info/model
/hpoi/info/all/hobby
```
参照 PR #18996 下的[回复](https://github.com/DIYgod/RSSHub/pull/18996#discussion_r2071866392), 更新了页面的解析逻辑, 现在支持获取不同类型的情报; 原有的`hobby`、`model`选项 现在已经无效, 如果只想获取`hobby`、`model`类型的情况, 需要使用新的路由(e.g. /hpoi/info/all/hobby|model)；但`got.post`无法携带任何`payload`的问题仍然没有发现原因，所以使用`queryParams`来获取信息
> fix(route/hpoi/info): 更新了页面解析逻辑

- lib/routes/bilibili/utils.ts
- lib/routes/bilibili/video.ts
Close #
```routes
/bilibili/user/dynamic/7957044
/bilibili/user/video/7957044
```
I find that dynamic API may be less susceptible to anti-crawling restrictions. Please let me know if I am wrong.
The following is a comparison of the results at the same time
> fix(route/bilibili/video): fallback to dynamic api

- lib/routes/linkedin/posts.ts
Following up from PR https://github.com/DIYgod/RSSHub/pull/18799
```routes
/linkedin/company/google/posts
```
Adding `updated` tag so that feed can work properly with RSS connectors, see: https://learn.microsoft.com/en-us/connectors/rss/#known-issues-and-limitations
> RSS feeds that do not include an "updated" tag for feed items will not function with the trigger when the sinceProperty is set to "UpdatedOn" value.
> feat: add updated to linkedin company post items

- lib/routes/bbc/learningenglish.ts
Close #17990
```routes
/bbc/learningenglish
/bbc/learningenglish/take-away-english
/bbc/learningenglish/authentic-real-english
/bbc/learningenglish/take-away-english
/bbc/learningenglish/media-english
/bbc/learningenglish/lingohack
/bbc/learningenglish/english-in-a-minute
/bbc/learningenglish/phrasal-verbs
/bbc/learningenglish/todays-phrase
/bbc/learningenglish/q-and-a
/bbc/learningenglish/english-at-work
/bbc/learningenglish/storytellers
```
- 增加了BBC中学习英语频道的RSS源
> feat(route/bbc): support BBC Learningenglish chinese channel

- lib/routes/hupu/templates/description.art
Related to https://github.com/RSSNext/Folo/issues/3615
Correct the syntax for the video poster attribute in the template to ensure proper rendering of video posters.
Before
After
```routes
/hupu/all/topic-daily
```
> fix: video poster syntax in hupu template

- lib/routes/xiaoyuzhou/podcast.ts
Close #
```routes
/xiaoyuzhou/podcast/61dcea054b459868c4d04153
```
xiaoyuzhou is delete `shownotes` attribute, only left `description`, but this attribute only contains text, not HTML code:
they're only description text, not full HTML content. And that's why i temporary mark #19120 as WIP.
This PR is going to fetch shownotes from episode page.
Now should look good:
And the old code can't handle empty shownotes:
> fix(route/xiaoyuzhou): bring HTML description back

- lib/routes/kemono/const.ts
- lib/routes/kemono/index.ts
- lib/routes/kemono/types.ts
Close #
```routes
/kemono/patreon/11666662
/kemono/fanbox/24961447/announcements
/kemono/fanbox/24961447/fancards
```
Specifically, some of the server data appears to have formatting inconsistencies during storage. Taking Patreon user 11666662 as an example, here is some of the data retrieved through the `https://kemono.su/api/v1/patreon/user/11666662/posts` endpoint:
```
[
{
"id": "129116313",
"user": "11666662",
"service": "patreon",
"title": "Skrik_png+line_art",
"content": "",
"embed": "\"{}\"",
"shared_file": false,
"added": "2025-05-19T18:29:51.301674",
"published": "2025-05-16T14:59:37",
"edited": "2025-05-16T14:59:37",
"file": "\"{\\\"name\\\": \\\"s803_k_png.png\\\", \\\"path\\\": \\\"/d7/50/d750b24ec8e57fb751198c7e461cb5bb5b5dd3319b3e8d7b627b13591e2679ac.png\\\"}\"", …
```
> fix(route/kemono): improve JSON field parsing with nested string handling

- lib/utils/cache/index.ts
Make `tryGet` method can support generic return types. It will not eat the cache object type.
Before:
After:
```routes
NOROUTE
```
> feat(cache): enhance tryGet method to support generic return types

- lib/routes/konachan/post.ts
```routes
/konachan/post/popular_recent/1d
/konachan/post/popular_recent/1w
/konachan/post/popular_recent/1m
/konachan/post/popular_recent/1y
/konachan/sfw/post/popular_recent/1d
/konachan/sfw/post/popular_recent/1w
/konachan/sfw/post/popular_recent/1m
/konachan/sfw/post/popular_recent/1y
```
- 在原有 lib/routes/konachan/post.ts 基础上新增了 /sfw 前缀，用于切换至 konachan.net（无r18内容版本）站点。
- 原有 /konachan/post/popular_recent/:period? 路由保持不变，继续请求 konachan.com。
- 新增 /konachan/sfw/post/popular_recent/:period? 路由时，自动识别 /sfw 前缀并请求 konachan.net。
- 已在本地验证所有示例路由均可正确输出 RSS，符合脚本规范且无需额外第三方包。
> feat(konachan): add SFW option for konachan via /sfw prefix

- lib/routes/smartlink/index.ts
Close #
```routes
/smartlink/bloombergbusiness
```
image URL without query params does not work https://scontent-atl3-2.cdninstagram.com/v/t51.75761-15/504395160_18512643616057819_8198275713847525084_n.jpg
Need to preserve the whole URL
https://scontent-atl3-2.cdninstagram.com/v/t51.75761-15/504395160_18512643616057819_8198275713847525084_n.jpg?stp=dst-jpg_e35_tt6&_nc_cat=100&ccb=1-7&_nc_sid=18de74&_nc_ohc=Jw-gKsJFN7IQ7kNvwEMMWNO&_nc_oc=Adl3IajRRrqy_Ox8gYejkXzp7yBU1HKfZIGH2eH91QgDACxFvGq0VVx7SAdr2Lmg1q4&_nc_zt=23&_nc_ht=scontent-atl3-2.cdninstagram.com&edm=AM6HXa8EAAAA&_nc_gid=zJXfexst5YK6U6_UN6ydGw&oh=00_AfMbYEggCl_quY3GgpGSe4ghn2wvHMbi7WqKV3WRyRQC2Q&oe=684B8B49
> fix(route/smartlink): Preserve queryparams for image URL to work in smartlink

- lib/routes/twitter/api/web-api/utils.ts
Close #
```routes
NOROUTE
```
I found that all the results returned by my `twitter/media` route are empty.
After inspecting the packet capture, I discovered that the nested structure of `timeline_v2` appears to be `timeline_v2.timeline`, rather than `timeline.timeline_v2`. However, I'm unsure if the latter structure exists.
Related commit: 5048710a372b2a475a747882a5cc54645919bc3e
> fix(route/twitter): handle `timeline_v2` nested structure

- lib/routes/metacritic/index.ts
Apparently, `item.genres` is optional, which was breaking the whole feed.
Close #
```routes
/metacritic/tv
```
> fix: Guard against missing metacritic TV genre information

- lib/routes/18comic/album.ts
- lib/routes/18comic/namespace.ts
- lib/routes/18comic/search.ts
- lib/routes/18comic/utils.ts
None
```routes
/18comic/search/photos/all/test
/18comic/album/616448
```
The previous 18comic route returned a 403 error, likely due to 18comic's anti-bot detection.
To bypass this restriction, an API mode has been added to use API requests instead of fetching the website directly.
Currently it just support route of search
> fix(route): Fix 403 issue on 18comic route by using API calls instead of directly fetching the webpage.

- lib/config.ts
- lib/routes/reuters/common.ts
Close #
```routes
/reuters/world
/reuters/legal
```
- 修复reuters接口`https://www.reuters.com/pf/api/v3/content/fetch/*`会因为`User-Agent`报错401。排查后发现是`randUserAgent`生成的随机UA太老或不符合要求。
- 因为涉及到引用库以及UA版本号的问题，改为使用环境变量`REUTERS_UA`配置。同时提供暂时可用的默认UA`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0`
- 检查UA中的版本号，如`Chrome/63.0.3239.84`会因为太老报错
- 检查Windows的版本信息，已知`(Windows NT 10.0; Win64; x64) `是符合要求的，但`(Windows NT 6.2;en-US)`不行
> fix(route/reuters): 修复reuters因为ua报错401

- lib/routes/github/private-feed.ts
Close #14112 
```routes
/github/feed/yihong0618
/github/feed/yihong0618/all
/github/feed/yihong0618/star
/github/feed/yihong0618/push
/github/feed/yihong0618/pr
/github/feed/yihong0618/create
/github/feed/yihong0618/release
/github/feed/yihong0618/star,release
/github/feed/yihong0618/push,prcomm,pr
/github/feed/yihong0618/star,release,pr
/github/feed/RtYkk/push,fork,create
/github/feed/yihong0618/star
/github/feed/RtYkk/all
/github/feed/yihong0618/issuecomm,prcomm
/github/feed/RtYkk/release,public,member
/github/feed/yihong0618/fork,delete
/github/feed/RtYkk/star,push
```
Added a new GitHub route `/github/privatefeed/:user/:types?` that provides [GitHub user's received events feed](https://github.com/dashboard-feed) with optional filtering by event types.
Features:
- Supports filtering by …
> feat(github): add private feed route for user received events

- lib/routes/kovidgoyal/kitty/changelog.ts
- lib/routes/kovidgoyal/namespace.ts
- Create new route handler for Kitty terminal changelog
- Implement parsing of version history and change details
- Add namespace definition for Kitty terminal
The new route fetches and parses the detailed changelog from Kitty's website, providing structured data including version numbers, release dates, and change items in a format suitable for RSS consumption.
Close #
```routes
/kovidgoyal/kitty/changelog
```
> feat: add Kitty changelog route

- lib/routes/meteoblue/namespace.ts
- lib/routes/meteoblue/weathernews.ts
Close #
```routes
/meteoblue/weathernews
```
> feat(route/meteoblue): add namespace and weather news route

- lib/routes/huggingface/daily-papers.ts
Support fetching by different publication cycle and flitering by votes for Huggingfce papers.
```routes
/huggingface/daily-papers
/huggingface/daily-papers/month/50
/huggingface/daily-papers/week
/huggingface/daily-papers/week/10
```
> feat(routes): Support fetching by different publication cycle and flitering by votes for Huggingfce papers.

- lib/routes/natgeo/natgeo.ts
This PR updates the title selector so it doesn't include the website name in article titles.
Before (unnecessarily includes website name):
```
document.querySelector('title')
<title>​泰國收藏家為什麼要將270公斤巨魚當成寶貝？ - 國家地理雜誌官方網站｜探索自然、科學與文化的最佳權​</title>​
```
After (clean article title):
```
document.querySelector('h1.content-title')
<h1 class=​"content-title text-black">​ 泰國收藏家為什麼要將270公斤巨魚當成寶貝？ ​</h1>​
```
```routes
/natgeo/environment/article
```
> fix: title selector

- lib/routes/ehentai/ehapi.ts
Close #19496
```routes
/ehentai/favorites/6/favorited/0/bittorrent=true&embed_thumb=true
/ehentai/search/f_search=language%3Achinese%24+other%3A"full+color%24"+other%3Auncensored%24&advsearch=1&f_sto=on&f_spf=20&f_srdd=4/0/bittorrent=true&embed_thumb=true
```
> fix(route/ehentai): update thumbnail fetching and parsing logic

- lib/routes/wikipedia/current-events.ts
- lib/routes/wikipedia/namespace.ts
Add RSS feed for Wikipedia Portal:Current events providing the past 7 days of current events. Parses MediaWiki templates and converts wiki markup to HTML.
```routes
/wikipedia/current-events
```
> feat(route): add Wikipedia current events
