DIYgod/RSSHub

- lib/routes/manxiaosi/book.js
None
```routes
/manxiaosi/book/298
```
很久以前这个路由是正常的，现在报错 $().reverse is not a function
推测是cheerio包的返回类型变了
> fix(route): reverse is not a function

- docs/multimedia.md
- lib/v2/javbus/genre.js
- lib/v2/javbus/home.js
- lib/v2/javbus/label.js
- lib/v2/javbus/series.js
- lib/v2/javbus/star.js
- lib/v2/javbus/studio.js
- lib/v2/javbus/uncensored/genre.js
- lib/v2/javbus/uncensored/home.js
- lib/v2/javbus/uncensored/series.js
- lib/v2/javbus/uncensored/star.js
- lib/v2/javbus/util.js
- lib/v2/javbus/western/genre.js
- lib/v2/javbus/western/home.js
- lib/v2/javbus/western/series.js
- lib/v2/javbus/western/star.js
Close #9307
```routes
/javbus/home?domain=javsee.icu
```
> fix(route): add JavBus alternative domain

- lib/v2/eprice/rss.js
Close #
```routes
/eprice/hk
/eprice/tw
```
> fix(route): eprice hk

- docs/en/install/README.md
- docs/en/programming.md
- docs/install/README.md
- docs/programming.md
- lib/config.js
- lib/v2/bitbucket/commits.js
- lib/v2/bitbucket/maintainer.js
- lib/v2/bitbucket/radar.js
- lib/v2/bitbucket/router.js
- lib/v2/bitbucket/tags.js
Close #14
```route
/bitbucket/commits/:workspace/:repo_slug
/bitbcuket/tags/:workspace/:repo_slug
```
> feat(route): add bitbucket commits and tags

- lib/routes/gov/fmprc/utils.js
Close #
```routes
/gov/fmprc/fyrbt
```
> fix(route): gov/fmprc/fyrbt 修复发布日期提取

- lib/v2/app-center/templates/description.art
- lib/v2/picuki/profile.js
- lib/v2/picuki/templates/post.art
Close #
```routes
/app-center/release/cloudflare/1.1.1.1-windows/beta
/picuki/profile/bugcat_capoo
```
> fix(route): node.js 14 has no `replaceAll`

- docs/en/traditional-media.md
- docs/traditional-media.md
- lib/router.js
- lib/v2/rfa/index.js
- lib/v2/rfa/maintainer.js
- lib/v2/rfa/radar.js
- lib/v2/rfa/router.js
Close #
```routes
/rfa/mandarin
```
> fix(route): rfa missing url property

- docs/new-media.md
> docs: update modian zhongchou categories

- lib/v2/nikkei-cn/index.js
Close #
```routes
/nikkei-cn
/nikkei-cn/cn/rss
/nikkei-cn/cn/politicsaeconomy
/nikkei-cn/cn/china/cpolicssociety
/nikkei-cn/zh
/nikkei-cn/zh/rss
/nikkei-cn/zh/politicsaeconomy
/nikkei-cn/zh/china/cpolicssociety
```
> fix(route)(nikkei-cn): imprudent slice; selector lack; duplicated article

- docs/en/programming.md
- docs/programming.md
- lib/v2/github/maintainer.js
- lib/v2/github/pulls.js
- lib/v2/github/router.js
Close #9331
```routes
/github/pull/vuejs/vue
/github/pull/DIYgod/RSSHub
```
> fix(route): github pull requests

- lib/v2/bilibili/cache.js
- lib/v2/bilibili/video.js
Fetch Bilibili user avatar and use it as icon and logo for atom feed
```routes
/bilibili/user/videos
```
> feat(route): add icon and logo to Bilibili atom feed

- docs/en/install/README.md
- docs/en/programming.md
- docs/install/README.md
- docs/programming.md
- lib/v2/github/comments.js
- lib/v2/github/follower.js
- lib/v2/github/radar.js
- lib/v2/github/router.js
- lib/v2/github/star.js
- lib/v2/github/starred_repos.js
Close #
```routes
/github/comments/DIYgod/RSSHub/issues/8116
/github/comments/DIYgod/RSSHub/8116
/github/comments/DIYgod/RSSHub/9357
```
> fix(route): github comments use api

- lib/routes/gov/customs/list.js
- lib/routes/hkej/index.js
- lib/routes/ipsw/index.js
- lib/routes/telecompaper/news.js
- lib/routes/zcool/top.js
- lib/v2/95mm/utils.js
- lib/v2/agirls/index.js
- lib/v2/agirls/topic.js
- lib/v2/agirls/topic_list.js
- lib/v2/cbirc/index.js
- lib/v2/firefox/index.js
- lib/v2/gamer/hot.js
- lib/v2/hkej/index.js
- lib/v2/hket/index.js
Close #
```routes
NOROUTE
```
https://github.com/sindresorhus/got/blob/f582a091500702c88f80526a8d1fd6e040b1eee3/source/core/options.ts#L1910
The property name should be `headers` instead of `header`.
> fix(route): headers in got usage

- docs/en/programming.md
- docs/programming.md
- lib/v2/cncf/index.js
- lib/v2/cncf/maintainer.js
- lib/v2/cncf/radar.js
- lib/v2/cncf/reports.js
- lib/v2/cncf/router.js
Close #9769
```routes
/cncf/blog
/cncf/news
/cncf/announcements
/cncf/reports
```
> feat(route): add CNCF

- lib/v2/mdpi/journal.js
Close #
```routes
/mdpi/sensors
```
> fix(route): MDPI journal - avoid the replace() 'undefined' error

- docs/en/finance.md
- docs/finance.md
- lib/v2/seekingalpha/index.js
- lib/v2/seekingalpha/maintainer.js
- lib/v2/seekingalpha/radar.js
- lib/v2/seekingalpha/router.js
Close #7082
```routes
/seekingalpha/TSM/analysis
/seekingalpha/TSM/news
/seekingalpha/TSM/transcripts
/seekingalpha/TSM/press-releases
/seekingalpha/TSM/related-analysis
```
> feat(route): seekingalpha

- lib/v2/nextapple/realtime.js
Close #10696
```routes
/nextapple/realtime
/nextapple/realtime/new
/nextapple/realtime/entertainment
/nextapple/realtime/life
/nextapple/realtime/local
/nextapple/realtime/politics
/nextapple/realtime/international
/nextapple/realtime/finance
/nextapple/realtime/lifestyle
/nextapple/realtime/property
/nextapple/realtime/fashion
/nextapple/realtime/auto
/nextapple/realtime/health
/nextapple/realtime/sports
/nextapple/realtime/gadget
```
壹蘋新聞網會在文章列表中插入以下無用的文章需要跳過
```html
<div class="tenmax">
<article class="post-style3" itemscope="" itemprop="post">
<ins
class="rmax"
data-rmax-space-id="45d964b9294b45e9"
data-rmax-space-type="UNIVERSAL"
></ins>
</article>
</div>
```
> fix(route): 壹蘋新聞網獲取失敗

- lib/v2/gamme/category.js
- lib/v2/gamme/tag.js
again
Close #
```routes
/gamme/news
/gamme/news/hotchick
/gamme/news/tag/網友票選
/gamme/sexynews
/gamme/sexynews/hotchick
/gamme/sexynews/tag/老司機
```
> fix(route): gamme lazy load img

- docs/new-media.md
- lib/v2/ithome/maintainer.js
- lib/v2/ithome/radar.js
- lib/v2/ithome/router.js
- lib/v2/ithome/tw/feeds.js
Close #10770
```routes
/ithome/tw/feeds/news
/ithome/tw/feeds/big-data
/ithome/tw/feeds/cloud
/ithome/tw/feeds/devops
/ithome/tw/feeds/security
```
> feat(route): add iThome 台灣新聞

- docs/en/traditional-media.md
- docs/traditional-media.md
- lib/v2/cbnc/maintainer.js
- lib/v2/cbnc/radar.js
- lib/v2/cbnc/router.js
- lib/v2/cbnc/rss.js
Close #10883
```routes
/cbnc/rss
```
> feat(route): cbnc

- lib/v2/hackernews/index.js
```routes
/hackernews
/hackernews/best
```
[Hacker News](https://news.ycombinator.com/) change list title class name recently.
> fix(route): hacker news

- lib/v2/kemono/index.js
Close #11112
```routes
/kemono/fanbox/49494721
```
Fixed route's parsing error caused by html structure update
> fix(route): kemono.party parse failure (#11112)

- docs/new-media.md
- lib/v2/simpleinfo/index.js
- lib/v2/simpleinfo/maintainer.js
- lib/v2/simpleinfo/radar.js
- lib/v2/simpleinfo/router.js
- lib/v2/simpleinfo/templates/description.art
Close #8173
```routes
/simpleinfo
/simpleinfo/talk
/simpleinfo/work
/simpleinfo/news
```
> feat(route): add 簡訊設計

- docs/new-media.md
- lib/v2/verse/articles.js
- lib/v2/verse/maintainer.js
- lib/v2/verse/radar.js
- lib/v2/verse/router.js
Close #11432
```routes
/verse/articles
/verse/articles/verse-news
/verse/articles/figure
/verse/articles/culture
/verse/articles/new-ideas
/verse/articles/local
/verse/articles/eating
/verse/articles/features
```
> feat(route): add VERSE 文化媒體

- docs/en/other.md
- docs/other.md
- lib/v2/layoffs/index.js
- lib/v2/layoffs/maintainer.js
- lib/v2/layoffs/radar.js
- lib/v2/layoffs/router.js
Add RSS source for layoffs.fyi (routes and docs).
Close #11622
```routes
/layoffs
```
原网站的RSS源无人维护，所以新建了一个，用于追踪科技企业裁员情况。
> feat(route): add layoffs.fyi

- docs/traditional-media.md
- lib/v2/oncc/maintainer.js
- lib/v2/oncc/money18.js
- lib/v2/oncc/radar.js
- lib/v2/oncc/router.js
- lib/v2/oncc/templates/money18.art
Close #11822
```routes
/oncc/money18/exp
/oncc/money18/fov
/oncc/money18/industry
/oncc/money18/int
/oncc/money18/recagent
/oncc/money18/ntlgroup
/oncc/money18/pro
/oncc/money18/weainvest
/oncc/money18/ipo
/oncc/money18/tech
```
> feat(route): add 東網產經

- docs/en/bbs.md
- lib/v2/pikabu/community.js
- lib/v2/pikabu/maintainer.js
- lib/v2/pikabu/radar.js
- lib/v2/pikabu/router.js
- lib/v2/pikabu/templates/video.art
- lib/v2/pikabu/user.js
- lib/v2/pikabu/utils.js
Close #11235
```routes
/pikabu/user/@Eujenue
/pikabu/tag/Metallica
/pikabu/community/real_true_story
```
> feat(route): pikabu

- .dockerignore
- .puppeteerrc.js
- Dockerfile
Close #12066
```routes
/bluestacks/release/5
/picuki/profile/gudim_public
```
Related: https://github.com/puppeteer/puppeteer/pull/9095
> build(docker): put bundled chrome in node_modules

- docs/en/traditional-media.md
- docs/traditional-media.md
- lib/v2/theatlantic/maintainer.js
- lib/v2/theatlantic/news.js
- lib/v2/theatlantic/radar.js
- lib/v2/theatlantic/router.js
- lib/v2/theatlantic/templates/article-description.art
- lib/v2/theatlantic/utils.js
Close #
```routes
/theatlantic/latest
/theatlantic/technology
```
> feat(route): the atlantic

- lib/v2/wsj/utils.js
Close #
```routes
/wsj/en-us
```
> fix(route/wsj): content glitch

- docs/en/new-media.md
- docs/en/traditional-media.md
- docs/new-media.md
- docs/traditional-media.md
- lib/v2/techcrunch/maintainer.js
- lib/v2/techcrunch/news.js
- lib/v2/techcrunch/radar.js
- lib/v2/techcrunch/router.js
Close #
```routes
/techcrunch/news
```
enrich the feed content compared with original rss feed.
> feat(route): techcrunch

- lib/v2/sony/downloads.js
Close #
```routes
/sony/downloads/product/nw-wm1am2
```
> fix: duplicate guid for each item

- lib/v2/bilibili/cache.js
- lib/v2/bilibili/video-all.js
#12461
```routes
/bilibili/user/video/72647293
/bilibili/user/video-all/72647293
```
上文承接这个 PR https://github.com/DIYgod/RSSHub/pull/10886
1. 更新Cookie 机制：获取 Cookie 时，httpWrap 会自动加上 header `referer: https://www.bilibili.com`，当前这一 referer 已被限制；另外，B站返回多个 `set-cookie`，需要多做一步 Array to String 的处理
2. `video-all` 路由会需要大量请求B站分页接口，同IP+同UA容易被限，先用Hack的方法更新UA来绕过限制
> fix(route): Anti-Anti-Spider 哔哩哔哩，更新 cookie 处理机制

- docs/en/install/README.md
- docs/en/other.md
- docs/install/README.md
- docs/other.md
- lib/config.js
- lib/v2/notion/database.js
- lib/v2/notion/maintainer.js
- lib/v2/notion/radar.js
- lib/v2/notion/router.js
- package.json
- pnpm-lock.yaml
Close #
```routes
/notion/database/a7cc133b68454f138011f1530a13531e
```
使用说明：需要设置 NOTION_TOKEN 来集成 notion 读取权限
应用场景：Notion作为稍后阅读的存储载体，通过剪藏工具将页面添加至 Notion，读取 Notion 中保存页面列表及页面内容生成一个 feed
添加的新包：
1. @notionhq/client: notion 官方提供的 API SDK
2. notion-to-md：notion 的页面由 blocks 组成，各种类型的 block 解析比较复杂，借助这个包将 blocks 解析并组成 markdown 文本，最后借助 markdown-it 转换为 html
> feat(notion): support notion database

- docs/en/new-media.md
- lib/v2/techpowerup/index.js
- lib/v2/techpowerup/maintainer.js
- lib/v2/techpowerup/radar.js
- lib/v2/techpowerup/review.js
- lib/v2/techpowerup/router.js
- lib/v2/techpowerup/utils.js
Close #
```routes
/techpowerup
/techpowerup/review/4090
```
> feat(route): techpowerup

- lib/v2/nhentai/util.js
Close #
```routes
/nhentai/language/chinese
```
Credit: https://github.com/sinkaroid/jandapress/pull/23
> fix(route): nhentai

- docs/en/program-update.md
- docs/program-update.md
- lib/v2/winstall/maintainer.js
- lib/v2/winstall/radar.js
- lib/v2/winstall/router.js
- lib/v2/winstall/templates/desc.art
- lib/v2/winstall/update.js
Close #12609 
```routes
/winstall/ShareX.ShareX
/winstall/Mozilla.Firefox
```
> feat(route): winstall

- lib/v2/gov/news/index.js
Close #12534 
```routes
/gov/news/gd
/gov/news/yw
/gov/news/bm
/gov/news/gwy
```
1. 中国政府网没有正确拼接相对地址路径
2. 替换滚动新闻地址
> fix(route): 中国政府网没有正确拼接相对地址路径 && 替换滚动新闻地址

- docs/blog.md
- lib/v2/zhubai/maintainer.js
- lib/v2/zhubai/radar.js
- lib/v2/zhubai/router.js
- lib/v2/zhubai/templates/description.art
- lib/v2/zhubai/top20.js
Close #12610
```routes
/zhubai/top20
```
> feat(route): add 竹百TOP20

- lib/v2/domp4/detail.js
Close #12502
```routes
/domp4/detail/xw1i85000005
/domp4/detail/7DRkFXAAAAAX
```
原本是为了修复 #12502 这个 issue，但是这个 issue 已经被关闭了
domp4 页面有改版，有些页面无法读取 script 中的 js 片段，所以改为直接解析 dom
> fix: domp4 页面改版修复

- docs/en/traditional-media.md
- docs/traditional-media.md
- lib/v2/reuters/common.js
- lib/v2/reuters/maintainer.js
Close #12738
```routes
/reuters/graphics
```
> feat(route): add Reuters Graphics

- lib/v2/apnews/topics.js
Close #12733 
```routes
/apnews/topics/abortion
/apnews/topics/china
/apnews/topics/biology
/apnews/topics/trending-news
```
> fix(route): AP News获取方式调整

- docs/en/new-media.md
- lib/v2/grist/featured.js
- lib/v2/grist/index.js
- lib/v2/grist/maintainer.js
- lib/v2/grist/radar.js
- lib/v2/grist/router.js
- lib/v2/grist/series.js
- lib/v2/grist/topic.js
- lib/v2/grist/utils.js
Close #
```routes
/grist/
/grist/featured
/grist/series/best-of-grist
/grist/topic/climate-of-courage
```
> feat(route): add Grist

- lib/v2/zhihu/maintainer.js
- lib/v2/zhihu/radar.js
- lib/v2/zhihu/router.js
- lib/v2/zhihu/xhu/auth.js
- lib/v2/zhihu/xhu/topic.js
- website/docs/routes/social-media.md
#6784 #7207 
```routes
/zhihu/xhu/topic/19566035
```
- 缓存的思路是借鉴的 #7207 ，不确定是否为通用解决方案
- 关于反爬，实测短时间多次访问 API 会返回 403 Forbidden，不过未测定具体数据
- 目前只添加了 `/topic` 路由，之后大概会更新其他的
- （Pull Request 模板里的文档链接需要更新了）
> feat(route): add xhu

- lib/v2/zhihu/maintainer.js
- lib/v2/zhihu/radar.js
- lib/v2/zhihu/router.js
- lib/v2/zhihu/xhu/collection.js
- lib/v2/zhihu/xhu/question.js
- lib/v2/zhihu/xhu/topic.js
- lib/v2/zhihu/xhu/zhuanlan.js
- website/docs/routes/social-media.md
#6784 
```routes
/zhihu/xhu/collection/26444956
/zhihu/xhu/question/264051433
/zhihu/xhu/question/264051433/updated
/zhihu/xhu/zhuanlan/githubdaily
```
Add some commonly used route.
People-activity has not been added, because the people id for xhu API can only be found in F12 debug page of the browser.
> feat(route): add xhu collection, question and zhuanlan

- lib/v2/discourse/notifications.js
Close #
```routes
/discourse/0/notifications
```
> fix(route): Fix Discourse link

- lib/router.js
- lib/routes/cna/index.js
- lib/v2/cna/index.js
- lib/v2/cna/maintainer.js
- lib/v2/cna/radar.js
- lib/v2/cna/router.js
- website/docs/routes/traditional-media.md
Close #
```routes
/cna/
/cna/aopl
```
> fix(route): add `Spotlight News` into CNA list.

- lib/config.js
- lib/utils/logger.js
- website/docs/install/README.md
- website/i18n/zh/docusaurus-plugin-content-docs/current/install/README.md
Close #7882 
```routes
NOROUTE
```
The log in log files:
```
{"timestamp":"2023-08-30 13:46:52.519","level":"info","message":"Listening Port 1200"}
{"timestamp":"2023-08-30 13:46:52.521","level":"info","message":"🎉 RSSHub start! Cheers!"}
{"timestamp":"2023-08-30 13:46:52.522","level":"info","message":"💖 Can you help keep this open source project alive? Please sponsor 👉 https://docs.rsshub.app/support"}
```
The log in console after setting `SHOW_LOGGER_TIMESTAMP=true`:
> feat(core): add logger timestamp

- lib/v2/stheadline/std/realtime.js
Close #13171
```routes
/stheadline/std/realtime/即時
/stheadline/std/realtime/hongkong
/stheadline/std/realtime/international
/stheadline/std/realtime/china
```
> fix(route): Adapt to different pages on stheadline.

- lib/v2/udn/breaking-news.js
Close #
```routes
/udn/news/breakingnews/0
/udn/news/breakingnews/1
/udn/news/breakingnews/2
```
> fix(route): Fix typo(?) in udn.

- lib/v2/thepaper/utils.js
Close #
```routes
/thepaper/featured
```
> feat(route): refine category list for thepaper.

- lib/v2/kunchengblog/essay.js
- lib/v2/kunchengblog/radar.js
- lib/v2/kunchengblog/router.js
Close #13130
```routes
/kunchengblog/essay
```
> fix(route): Kun Cheng Essay

- lib/v2/dorohedoro/news.js
Close https://github.com/DIYgod/RSSHub/issues/12606#issuecomment-1694396973
```routes
/dorohedoro/news
```
> fix(route): dorohedoro xml error

- lib/v2/rfi/maintainer.js
- lib/v2/rfi/news.js
- lib/v2/rfi/router.js
- website/docs/routes/multimedia.md
Close #
```routes
/rfi/news/en
/rfi/news/cn
/rfi/news/fr
/rfi/news/
```
> feat(route): Add multi-language support for RFI.

- lib/v2/zodgame/forum.js
- lib/v2/zodgame/templates/forum.art
Close #
```routes
/zodgame/forum/13
```
Changed to using api to get content, and added fulltext fetching for Zodgame forum
> feat(route): Add Zodgame forum fulltext support

- lib/v2/news/whxw.js
Close #
```routes
/news/whxw
/news/whxw?limit=20
```
> feat(route): Add request throttling for news.cn

- lib/v2/rsshub/transform/html.js
- lib/v2/rsshub/transform/json.js
- website/docs/routes/other.md
update `lib/v2/rsshu:/transform/html.js`
update `lib/v2/rsshu:/transform/json.js`
Close None
```routes
/rsshub/transform/html/https%3A%2F%2Fwechat2rss.xlab.app%2Fposts%2Flist%2F/item=div%5Bclass%3D%27post%2Dcontent%27%5D%20p%20a&pubDate=%2E
/rsshub/transform/json/https%3A%2F%2Fapi.github.com%2Frepos%2Fginuerzh%2Fgost%2Freleases/title=Gost%20releases&itemTitle=tag_name&itemLink=html_url&itemDesc=body&itemPubDate=created_at
```
Couldn't find a suitable example URL to parse a date.
> feat(route): add pubDate Transformation/HTML

- lib/v2/japanpost/radar.js
> chore(route): japanpost: update radar rules

- website/i18n/zh/docusaurus-plugin-content-docs/current/joinus/new-radar.md
Close #
```routes
NOROUTE
```
Update zh doc,, Keep it consistent with this [document](https://docs.rsshub.app/joinus/new-radar)
> docs: update new-radar doc

- lib/v2/deltaio/blog.js
- lib/v2/deltaio/maintainer.js
- lib/v2/deltaio/radar.js
- lib/v2/deltaio/router.js
- website/docs/routes/blog.md
Close #
```routes
/deltaio/blog
```
添加Delta Lake Blog的路由
> feat(route): Add Delta Lake Blog

- lib/v2/apnews/topics.js
> feat(route): Add request throttling for apnews

- lib/v2/stheadline/std/realtime.js
Close #
```routes
/stheadline/std/realtime
/stheadline/std/realtime/china
/stheadline/std/realtime/hongkong
```
> feat(route): Add category to stheadline.

- lib/v2/latepost/index.js
- lib/v2/latepost/radar.js
Close #
```routes
/latepost
/latepost/3
```
> fix(route): 晚点报道

- lib/v2/mihoyo/bbs/official.js
Close #
```routes
/mihoyo/bbs/official/2/1
```
> fix(route): 修复 米游社 公告栏 template 错误

- lib/v2/stheadline/std/realtime.js
Close #
```routes
/stheadline/std/realtime
/stheadline/std/realtime/china
```
> fix(route): (Maybe) fix the stheadline feed occasionally dropping details. 

- lib/v2/cna/index.js
Close #
```routes
/cna/aall
/cna/aopl
/cna/aipl
```
> feat(route): add category to cna & other improvements

- lib/v2/toodaylab/index.js
- lib/v2/toodaylab/maintainer.js
- lib/v2/toodaylab/radar.js
- lib/v2/toodaylab/router.js
- website/docs/routes/new-media.md
Close #13192
```routes
/toodaylab/posts
/toodaylab/hot
/toodaylab/column/299
/toodaylab/field/308
/toodaylab/topic/309
```
> feat(route): add 理想生活实验室

- lib/v2/douyin/live.js
Close #13224
```routes
/douyin/live/685317364746
```
`roomInfo.stream_url.hls_pull_url` is also playable.
> fix(route): douyin live

- lib/v2/bjfu/grs.js
- lib/v2/bjfu/it/index.js
- lib/v2/bjfu/it/utils.js
- lib/v2/bjfu/jwc/index.js
- lib/v2/bjfu/jwc/utils.js
- lib/v2/bjfu/kjc.js
- lib/v2/bjfu/news/index.js
- lib/v2/bjfu/news/utils.js
Close #13218 
```routes
/bjfu/grs
/bjfu/kjc
/bjfu/news/lsyw
/bjfu/it/pydt
/bjfu/jwc/jwkx
```
> fix(route): fix bjfu encoding

- lib/v2/luxiangdong/archive.js
- lib/v2/luxiangdong/maintainer.js
- lib/v2/luxiangdong/radar.js
- lib/v2/luxiangdong/router.js
- website/docs/routes/blog.md
Close #
```routes
/luxiangdong/archive
```
> feat(route): add 土猛的员外 blog

- lib/v2/tfc-taiwan/index.js
- lib/v2/tfc-taiwan/maintainer.js
- lib/v2/tfc-taiwan/radar.js
- lib/v2/tfc-taiwan/router.js
- lib/v2/tfc-taiwan/templates/article.art
- lib/v2/tfc-taiwan/utils.js
- website/docs/routes/other.md
Close #8411
```routes
/tfc-taiwan/info
/tfc-taiwan/report
/tfc-taiwan/category/22/1204
/tfc-taiwan/topic/9557
```
> feat(route): tfc-taiwan

- lib/v2/abskoop/index.js
- lib/v2/abskoop/nsfw.js
- lib/v2/abskoop/radar.js
- lib/v2/abskoop/templates/description.art
- website/docs/routes/multimedia.md
Close #12840
```routes
/abskoop/ 
/abskoop/nsfw
```
> fix(route): fix A姐分享

- lib/v2/rsshub/routes.js
- website/docs/routes/program-update.md
8a58d7492269ebedf1db5828296b95e876b442de
```routes
/rsshub/routes
/rsshub/routes/zh
```
> fix(route): rsshub routes

- lib/v2/ustc/eeis.js
- lib/v2/ustc/sist.js
Close #
```routes
/ustc/eeis/tzgg
/ustc/eeis/xwxx
/ustc/sist/tzgg
/ustc/sist/zsgz
```
因网站改版，修改部分选择器
> fix(route): 中国科学技术大学

- lib/app.js
- lib/views/error.art
- lib/views/welcome.art
Follow up https://github.com/DIYgod/RSSHub/pull/12629#issuecomment-1592342498
```routes
/test/1
```
> fix: cache logo & subdirectory serving

- lib/v2/baidu/maintainer.js
- lib/v2/baidu/radar.js
- lib/v2/baidu/router.js
- lib/v2/baidu/templates/tieba_search.art
- lib/v2/baidu/tieba/search.js
- website/docs/routes/bbs.md
Close #
```routes
/baidu/tieba/search/rsshub
/baidu/tieba/search/neuro/kw=neurosama&only_thread=1&sm=2
/baidu/tieba/search/爬虫/rn=5&kw=编程
```
> feat(route): 添加百度贴吧搜索

- website/docs/.format/format.js
- website/docs/.format/slugId.js
> docs: slugify h4

- lib/v2/dn/maintainer.js
- lib/v2/dn/news.js
- lib/v2/dn/radar.js
- lib/v2/dn/router.js
- lib/v2/dn/templates/description.art
- website/docs/routes/new-media.md
Close #13221
```routes
/dn/en-us/news
```
> feat(route): add DN.com

- lib/v2/bilibili/dynamic.js
- website/docs/routes/social-media.md
#13197
```routes
/bilibili/user/dynamic/2267573
/bilibili/user/dynamic/2267573/directLink=1
```
由于 cache.getUsernameAndFaceFromUID 方法不稳定，可能会返回 undefined，所以采用一种稳定的方法
> fix(route): fix `/bilibili/user/dynamic` author undefined

- lib/v2/boc/whpj.js
Close #13259
```routes
/boc/whpj/xh?filter_title=英镑
```
> fix(route): boc whpj

- lib/v2/mixcloud/index.js
- lib/v2/mixcloud/queries.js
```routes
/mixcloud/dholbach
/mixcloud/dholbach/uploads
/mixcloud/dholbach/favorites
/mixcloud/dholbach/listens
/mixcloud/FirstEar/stream
```
update mixcloud queries
> fix(route): update mixcloud queries

- lib/v2/scut/maintainer.js
- lib/v2/scut/radar.js
- lib/v2/scut/router.js
- lib/v2/scut/smae/notice.js
- website/docs/routes/university.md
Close #
```routes
/scut/smae
/scut/smae/gwxx
/scut/smae/djgz
/scut/smae/rsgz
/scut/smae/xsgz
/scut/smae/kysys
/scut/smae/bksjw
/scut/smae/yjsjw
```
- [ x ] New Route / 新的路由
- [ x ] Follows [v2 Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [v2 路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
- [ x ] Documentation / 文档说明
- [ x ] CN / 中文文档
- [ x ] Full text / 全文获取
- [ x ] Use cache / 使用缓存
- [ x ] [Date and time](https://docs.rsshub.app/joinus/advanced/pub-date) / [日期和时间](https://docs.rsshub.app/zh/joinus/advanced/pub-date)
- [ x ] Parsed / 可以解析
添加了华南理工大学机械与汽车工程学院的通知公告，包括各子分类。
> feat(route): 华南理工大学 - 机械与汽车工程学院

- lib/v2/alternativeto/maintainer.js
- lib/v2/alternativeto/platform.js
- lib/v2/alternativeto/radar.js
- lib/v2/alternativeto/router.js
- lib/v2/alternativeto/software.js
- lib/v2/alternativeto/utils.js
- website/docs/routes/programming.md
Close #10979
```routes
/alternativeto/software/rsshub
/alternativeto/software/cpp/license=opensource&platform=windows
/alternativeto/platform/firefox
```
The website has Cloudflare challenge so I use Puppeteer.
> feat(route): add alternativeto.net

- lib/router.js
- lib/routes/cbc/topics.js
- lib/v2/cbc/maintainer.js
- lib/v2/cbc/radar.js
- lib/v2/cbc/router.js
- lib/v2/cbc/topics.js
- website/docs/routes/traditional-media.md
Close #
```routes
/cbc/topics/canada-toronto
```
> fix(route/cbc): Fix article content html tag

- lib/v2/xmut/jwc/bkjw.js
- lib/v2/xmut/jwc/yjs.js
- lib/v2/xmut/maintainer.js
- lib/v2/xmut/radar.js
- lib/v2/xmut/router.js
- website/docs/routes/university.md
```routes
/xmut/jwc/bkjw/jxyx
/xmut/jwc/bkjw/zhsw
/xmut/jwc/bkjw/xwgl
/xmut/jwc/bkjw/sjjx
/xmut/jwc/bkjw/jyjg
/xmut/jwc/yjjw/tzgg
/xmut/jwc/yjjw/xwdt
/xmut/jwc/yjjw/xstj
/xmut/jwc/yjjw/yjsjw
```
> feat(route): add 厦门理工大学教务处

- lib/v2/xinpianchang/index.js
- lib/v2/xinpianchang/maintainer.js
- lib/v2/xinpianchang/radar.js
- lib/v2/xinpianchang/rank.js
- lib/v2/xinpianchang/router.js
- lib/v2/xinpianchang/templates/description.art
- lib/v2/xinpianchang/util.js
- website/docs/routes/new-media.md
Close #13330
```routes
/xinpianchang/discover
/xinpianchang/rank
```
> feat(route): add 新片场

- lib/v2/kamen-rider-official/maintainer.js
- lib/v2/kamen-rider-official/news.js
- lib/v2/kamen-rider-official/radar.js
- lib/v2/kamen-rider-official/router.js
- lib/v2/kamen-rider-official/templates/description.art
- website/docs/routes/new-media.md
Close #13299
```routes
/kamen-rider-official/news
/kamen-rider-official/news/テレビ
```
> feat(route): add 仮面ライダ最新情報

- lib/v2/ainvest/article.js
- lib/v2/ainvest/maintainer.js
- lib/v2/ainvest/news.js
- lib/v2/ainvest/radar.js
- lib/v2/ainvest/router.js
- lib/v2/ainvest/utils.js
- package.json
- pnpm-lock.yaml
- website/docs/routes/finance.md
Close #11083
```routes
/ainvest/article
/ainvest/news
```
> feat(route): add ainvest

- lib/v2/reuters/common.js
Close #
```routes
/reuters/world
/reuters/world/africa
/reuters/business
/reuters/legal
/reuters/authors/jonathan-landay
```
> fix(route): Remove duplicate articles in reuters feed.

- lib/v2/udn/breaking-news.js
Close #
```routes
/udn/news/breakingnews/0
/udn/news/breakingnews/1
/udn/news/breakingnews/2
```
> fix(route): Refine category for udn feed.

- lib/v2/sourceforge/index.js
- lib/v2/sourceforge/maintainer.js
- lib/v2/sourceforge/radar.js
- lib/v2/sourceforge/router.js
- website/docs/routes/program-update.md
Close #12848 
```routes
/sourceforge/os=windows&sort=update&natlanguage=english
/sourceforge/topic=artificial-intelligence&os=windows&sort=update&natlanguage=english
```
本地测试时，若未指定操作系统，会自动跳转到 Mac 的软件
> feat(route): add sourceforge

- lib/v2/surfshark/blog.js
- lib/v2/surfshark/maintainer.js
- lib/v2/surfshark/radar.js
- lib/v2/surfshark/router.js
- lib/v2/surfshark/templates/description.art
- website/docs/routes/blog.md
Close #13324
```routes
/surfshark/blog
```
> feat(route): add Surfshark Blog

- lib/v2/economist/full.js
n/a
```routes
/economist/the-world-this-week
```
> fix(route): economist article body extraction

- lib/v2/ainvest/radar.js
- lib/v2/cas/radar.js
- lib/v2/finology/radar.js
- lib/v2/grist/radar.js
- lib/v2/icbc/radar.js
- lib/v2/liulinblog/radar.js
- lib/v2/lsnu/radar.js
- lib/v2/niaogebiji/radar.js
- lib/v2/oreno3d/radar.js
- lib/v2/sqmc/radar.js
- lib/v2/thwiki/radar.js
- lib/v2/xiaote/radar.js
- lib/v2/yyets/radar.js
> docs: fix radar `docs` links

- lib/v2/osu/beatmaps/packs.js
- lib/v2/osu/maintainer.js
- lib/v2/osu/radar.js
- lib/v2/osu/router.js
- website/docs/routes/game.md
Close #13359 
```routes
/osu/packs
/osu/packs/artist
```
我尝试爬取过每个曲包的 description，但是返回了 429 Too Many Requests，所以 description 是空的
> feat(route): add osu!

- lib/v2/bilibili/danmaku.js
Close #
```routes
/bilibili/video/danmaku/BV1nF41167DA/1
```
> feat(route): B站弹幕添加对应视频时间点

- lib/v2/radio-canada/latest.js
Close #13373
```routes
/radio-canada/latest/fr
/radio-canada/latest/en
/radio-canada/latest/es
/radio-canada/latest/zh-hans
/radio-canada/latest/zh-hant
/radio-canada/latest/ar
/radio-canada/latest/pa
/radio-canada/latest/tl
```
> Feat(route): fix radio canada international

- lib/v2/gogoanimehd/maintainer.js
- lib/v2/gogoanimehd/radar.js
- lib/v2/gogoanimehd/recent-releases.js
- lib/v2/gogoanimehd/router.js
- website/docs/routes/anime.md
Close #
```routes
/gogoanimehd/recent-releases
```
Get updates for recently released episodes that are added to gogoanimehd
> feat(route): add gogoanimehd

- website/docs/README.md
- website/docs/faq.md
- website/docs/joinus/new-rss/add-docs.md
- website/docs/joinus/quick-start.md
- website/docs/parameter.md
- website/docs/routes/other.md
- website/i18n/zh/docusaurus-plugin-content-docs/current/README.md
- website/i18n/zh/docusaurus-plugin-content-docs/current/faq.md
- website/i18n/zh/docusaurus-plugin-content-docs/current/joinus/quick-start.md
- website/i18n/zh/docusaurus-plugin-content-docs/current/parameter.md
- website/src/components/Route.tsx
- website/src/theme/MDXComponents.js
> docs: fix rendering

- lib/v2/hackyournews/index.js
- lib/v2/hackyournews/maintainer.js
- lib/v2/hackyournews/radar.js
- lib/v2/hackyournews/router.js
- website/docs/routes/programming.md
Close #
```routes
/hackyournews
```
HackYourNews.com, according to its description, it is AI summaries of the top HN stories.
> feat(route): added hackyournews

- lib/v2/gov/chongqing/gzw.js
- lib/v2/gov/maintainer.js
- lib/v2/gov/radar.js
- lib/v2/gov/router.js
- website/docs/routes/government.md
Close #13292
```routes
/gov/chongqing/gzw
```
> feat(route): add 重庆市国有资产监督管理委员会

- lib/v2/ft/myft.js
Close #
```routes
/ft/myft/12345678-abcd-4036-82db-vdv20db024b8
```
> fix(route): Add category to ft.com feed & Update full text mechanism.

- lib/v2/ft/myft.js
Close #
```routes
/ft/myft/12345678-abcd-4036-82db-vdv20db024b8
```
> fix(route): fix author field for ft.com

- lib/v2/bilibili/cache.js
- lib/v2/bilibili/video.js
#13398
```routes
/bilibili/user/video/2267573
```
> refactor(route): bilibili getCookie remove deadcode

- lib/v2/bilibili/fav.js
- lib/v2/bilibili/userFav.js
Close #13403
```routes
/bilibili/user/fav/2267573
/bilibili/fav/756508/50948568
```
访问自己的非公开收藏夹需要自建
> fix(route): bilibili 收藏夹可使用 config 中的 Cookie

- lib/v2/xiaohongshu/user.js
- lib/v2/xiaohongshu/util.js
Close #13295
```routes
/xiaohongshu/user/54f6a8a6a46e9635e2abb53c/notes
```
> fix(route): xiaohongshu

- lib/v2/netflav/index.js
- lib/v2/netflav/maintainer.js
- lib/v2/netflav/radar.js
- lib/v2/netflav/router.js
- lib/v2/netflav/templates/description.art
- website/docs/routes/multimedia.md
Close #
```routes
/netflav
```
> feat(route): netflav

- lib/v2/yuque/utils.js
Close #
```routes
/yuque/arvinxx/thinking-evolution
```
> fix(route): yuque 处理双向链接卡片

- lib/v2/zhubai/radar.js
- lib/v2/zhubai/templates/description.art
- lib/v2/zhubai/top20.js
- website/docs/routes/blog.md
Close #13424
```routes
/zhubai/top20
```
> fix(route): 竹白上周热门 TOP 20

- lib/v2/weibo/oasis/user.js
Close #13362
```routes
/weibo/oasis/user/7401125849
```
> fix(route): oasis

- lib/v2/udn/breaking-news.js
Close #
```routes
/udn/news/breakingnews/0
```
> fix(route): prevent `null` category in udn feed.

- lib/v2/2048/index.js
N/A
```routes
/2048/57
```
- 去除帖子标题中无关部分
- 修正帖子作者
- 修正发帖时间
- 补充遗漏的附件形式的图片
> fix(route): 2048

- lib/v2/china/news/military/news.js
Close #
```routes
/china/news/military
```
更新了页面上不正确的xpath
update xpath  don not work in military.
> fix(route): china.com military xpath

- lib/v2/scau/maintainer.js
- lib/v2/scau/radar.js
- lib/v2/scau/router.js
- lib/v2/scau/yjsy.js
- website/docs/routes/university.md
yjsy.js title and description
华南农业大学研究生院 通知公告
Close #
```routes
/scau/yjsy
```
> feat(route): add scau/yjsy 

- lib/v2/gcores/radio.js
Close #
```routes
/gcores/radios
/gcores/radios/45
```
过滤机核播客中需要会员的内容
> fix(route): remove gcores radios required privilege

- lib/v2/udn/breaking-news.js
Close #
```routes
/udn/news/breakingnews/0
/udn/news/breakingnews/1
/udn/news/breakingnews/2
/udn/news/breakingnews/3
```
> fix(route/udn): Remove control character to prevent JSON parser error.

- lib/v2/gcores/category.js
Close #
```routes
/gcores/category/articles
/gcores/tag/42/articles
/gcores/collections/64
/gcores/radios/45
```
> fix(route): Add pubDate to gcore.

- lib/v2/apple/apps.js
- lib/v2/apple/maintainer.js
- lib/v2/apple/router.js
- website/docs/routes/program-update.md
Close #13456
```routes
/apple/apps/update/us/id1596063349
/apple/apps/update/us/id1596063349/tvOS
```
> fix(route): Apple App Store Update with platform

- lib/v2/apnews/topics.js
> fix(route/apnews): filter out items with no link.

- lib/v2/pixiv/user.js
- lib/v2/pixiv/utils.js
Close #13288
```routes
/pixiv/user/15288095
```
> feat(route): pixiv user activity caption

- lib/v2/twitch/channel.js
- lib/v2/twitch/live.js
- lib/v2/twitch/maintainer.js
- lib/v2/twitch/radar.js
- lib/v2/twitch/router.js
- lib/v2/twitch/schedule.js
- lib/v2/twitch/video.js
- website/docs/routes/live.md
Close #12883
```routes
/twitch/live/riotgames
/twitch/video/riotgames/highlights
/twitch/schedule/riotgames
```
> feat(route): add twitch

- lib/v2/2048/index.js
> fix(route): 2048 headers

- lib/v2/npr/radar.js
- lib/v2/rfi/maintainer.js
- lib/v2/rfi/news.js
- lib/v2/rfi/radar.js
- lib/v2/rfi/router.js
- website/docs/routes/multimedia.md
- website/docs/routes/traditional-media.md
Close #7524
```routes
/rfi/cn
/rfi/en/live-news
```
> feat(route): generic rfi

- lib/v2/javbus/index.js
- website/docs/routes/multimedia.md
Close #13437
```routes
/javbus/studio/1
```
> fix(route): javbus redirection

- lib/v2/asiantolick/index.js
- lib/v2/asiantolick/maintainer.js
- lib/v2/asiantolick/radar.js
- lib/v2/asiantolick/router.js
- lib/v2/asiantolick/templates/description.art
- website/docs/routes/picture.md
Close #13508
```routes
/asiantolick/page/news
```
> feat(route): add Asian to lick News

- lib/v2/cna/index.js
Close #
```routes
/cna/aopl
```
> fix(route/cna): Remove (sporadic) subscription banner

- lib/v2/gov/maintainer.js
- lib/v2/gov/radar.js
- lib/v2/gov/router.js
- lib/v2/gov/zhejiang/gwy.js
- website/docs/routes/government.md
Close #13510
```routes
/gov/zhejiang/gwy/1
```
> feat(route): add 浙江省公务员考试录用网

- lib/v2/tableau/maintainer.js
- lib/v2/tableau/radar.js
- lib/v2/tableau/router.js
- lib/v2/tableau/viz-of-the-day.js
- website/docs/routes/study.md
Close #
```routes
/tableau/viz-of-the-day
```
> feat(route/tableau): Add route for Tableau viz of the day.

- lib/v2/zjuvag/blog.js
- lib/v2/zjuvag/maintainer.js
- lib/v2/zjuvag/radar.js
- lib/v2/zjuvag/router.js
- website/docs/routes/blog.md
Close #
```routes
/zjuvag/blog
```
> feat(route/zjuvag): Add zjuvag blog.

- lib/v2/github/topic.js
Close #13380
```routes
/github/topics/chrome-extension/o=desc&s=updated
/github/topics/osint/o=desc&s=updated
```
> fix(route): github topic description

- lib/v2/readhub/index.js
- lib/v2/readhub/maintainer.js
- lib/v2/readhub/radar.js
- lib/v2/readhub/router.js
- lib/v2/readhub/templates/description.art
- website/docs/routes/new-media.md
Close #13525
```routes
/readhub
/readhub/daily
```
> fix(route): Readhub

- lib/v2/kemono/index.js
N/A
```routes
/kemono/discord/1052415450337792061
```
See https://kemono.party/api/schema
> fix(route): kemono/discord

- lib/v2/kamen-rider-official/news.js
Close #13597
```routes
/kamen-rider-official/news/すべて
```
> fix(route): 仮面ライダ最新情報

- lib/v2/chinafactcheck/index.js
- lib/v2/chinafactcheck/maintainer.js
- lib/v2/chinafactcheck/templates/description.art
- lib/v2/chinafactcheck/utils.js
Close #13601
```routes
/chinafactcheck
```
> fix(route): chinafactcheck ua

- lib/v2/caixin/blog.js
Close #
```routes
/caixin/blog?limit=2
/caixin/blog
/caixin/blog/huyong
/caixin/blog/zhishifenzi
/caixin/blog/yashalong
```
> fix(route/caixin): Fix query

- lib/v2/thoughtco/index.js
- lib/v2/thoughtco/maintainer.js
- lib/v2/thoughtco/radar.js
- lib/v2/thoughtco/router.js
- lib/v2/thoughtco/templates/description.art
- website/docs/routes/new-media.md
Close #13579
```routes
/thoughtco/science-4132464
/thoughtco/math-4133545
```
> feat(route): add ThoughtCo

- lib/v2/people/index.js
- lib/v2/people/router.js
Close #13613
```routes
/people/opinion/8213/49160/49219
```
> fix(route): 人民网人民时评

- lib/v2/gov/maintainer.js
- lib/v2/gov/mem/sgcc.js
- lib/v2/gov/radar.js
- lib/v2/gov/router.js
- website/docs/routes/government.md
Close #13616
```routes
/gov/mem/gk/sgcc/tbzdsgdcbg
```
> feat(route): add 中华人民共和国应急管理部事故及灾害查处

- lib/v2/yomujp/level.js
- lib/v2/yomujp/maintainer.js
- lib/v2/yomujp/radar.js
- lib/v2/yomujp/router.js
- website/docs/routes/reading.md
Close #
```routes
/yomujp/
/yomujp/n1
```
> feat(route):  add yomujp route

- lib/v2/oschina/news.js
Close #
```routes
/oschina/news
```
> fix(route): oschina remove ads

- lib/v2/douban/other/list.js
- website/docs/routes/social-media.md
```routes
/douban/list/tv_korean
```
https://m.douban.com/subject_collection/tv_korean
这类热播剧榜单没有cover属性，抓取代码里面没有判断cover是否存在，直接获取了cover.url。导致了异常。
> fix(route): 豆瓣热播剧榜单

- website/docs/install/README.md
add comment for limitation of email route
Close #
```routes
```
> docs: update doc email route limitations 

- website/i18n/zh/docusaurus-plugin-content-docs/current/install/README.md
update doc about email route limitations
Close #
```routes
```
https://github.com/DIYgod/RSSHub/blob/ef7546d2725ce0f9c1e89aa18f441675bd1ea7ac/lib/v2/mail/imap.js#L28C36-L28C66
> docs: update zh doc for email route limitations

- lib/v2/scmp/index.js
- lib/v2/scmp/utils.js
Close #10384
```routes
/scmp/3
/scmp/318198
```
> fix(route): scmp full text

- lib/v2/aljazeera/index.js
Close #
```routes
/aljazeera/english/news
/aljazeera/chinese/news
/aljazeera/english/tag/science-and-technology
/aljazeera/english/rss
```
> fix(route/aljazeera): Fix time matching regex.

- lib/v2/douban/maintainer.js
- lib/v2/douban/other/doulist.js
- website/docs/routes/social-media.md
Close #
```routes
/douban/doulist/123699362
```
headers 添加 Referer 解决403问题，报文item数量应该通过通用参数控制
> fix(route): 豆瓣豆列403

- lib/v2/dlsite/ci-en/article.js
Close #
```routes
/dlsite/ci-en/1839/article
```
The route `/dlsite/ci-en/:id/article` is now empty. (For example <https://rsshub.app/dlsite/ci-en/1839/article>)
This PR has fixed the issue.
> fix(route): fix selector for articles on dlsite ci-en

- lib/v2/bnu/dwxgb.js
Close #13675 
```routes
/bnu/dwxgb/xwzx/tzgg
```
> fix(route): 北京师范大学 党委学生工作部 - Response code 404 (Not Found) & Invalid URL

- website/docs/routes/university.md
> docs: fix tag

- lib/v2/hebtv/maintainer.js
- lib/v2/hebtv/nong-bo-shi-zai-xing-dong.js
- lib/v2/hebtv/templates/description.art
- website/docs/routes/traditional-media.mdx
Close #
```routes
/hebtv/nbszxd
```
> feat(route): 河北网络广播电视台农博士在行动视频

- lib/v2/ouc/it.js
- lib/v2/ouc/maintainer.js
- website/docs/routes/university.mdx
Close #
```routes
/ouc/it/0
/ouc/it/1
/ouc/it/2
```
修复了网站更新导致的时间错误问题
> fix(route): 中国海洋大学 信息科学与工程学院 时间错误

- lib/v2/ouc/it-tx.js
- lib/v2/ouc/maintainer.js
- lib/v2/ouc/radar.js
- lib/v2/ouc/router.js
- website/docs/routes/university.mdx
Close #
```routes
/ouc/it/tx/xwdt
/ouc/it/tx/tzgg
/ouc/it/tx/21758
```
> feat(route): 中国海洋大学信息科学与工程学部团学工作

- lib/v2/creative-comic/book.js
- lib/v2/creative-comic/utils.js
Close #
```routes
/creative-comic/book/117
```
> fix(route): creative-comic update image host

- lib/v2/cnbeta/type.js
- lib/v2/cnbeta/utils.js
Close #13712
```routes
/cnbeta
/cnbeta/category/movie
```
> fix(route): cnbeta

- lib/v2/logclub/index.js
- lib/v2/logclub/maintainer.js
- lib/v2/logclub/radar.js
- lib/v2/logclub/report.js
- lib/v2/logclub/router.js
- lib/v2/logclub/templates/description.art
- website/docs/routes/new-media.mdx
Close #13687
```routes
/logclub/news
/logclub/news/30
/logclub/lc_report
```
> feat(route): add 罗戈网

- lib/v2/reuters/common.js
- lib/v2/reuters/maintainer.js
- lib/v2/reuters/migration_prompt.js
- lib/v2/reuters/router.js
- website/docs/routes/traditional-media.mdx
Close #13727
```routes
/reuters/world/china
```
> fix(route): reuters return fulfilled promises

- lib/v2/hostmonit/cloudflareyes.js
- lib/v2/hostmonit/maintainer.js
- lib/v2/hostmonit/radar.js
- lib/v2/hostmonit/router.js
- lib/v2/hostmonit/templates/description.art
- lib/v2/hostmonit/templates/title.art
- website/docs/routes/other.mdx
Close #13713
```routes
/hostmonit/cloudflareyes
/hostmonit/cloudflareyes/v6
```
> feat(route): add 全球主机监控CloudFlareYes

- lib/v2/douban/people/status.js
Close #13770
```routes
/douban/people/139444387/status
```
> fix(route): the attribute status.activity now can be empty(#13770)

- lib/v2/dongqiudi/special.js
- lib/v2/dongqiudi/utils.js
Close #13760, close #13760
```routes
/dongqiudi/daily
/dongqiudi/special/41
```
> fix(route): dongqiudi

- .devcontainer/devcontainer.json
- .github/workflows/npm-publish.yml
- .github/workflows/test.yml
- .nvmrc
- Dockerfile
> chore: bump to node 20

- lib/v2/cmpxchg8b/articles.js
- lib/v2/cmpxchg8b/maintainer.js
- lib/v2/cmpxchg8b/radar.js
- lib/v2/cmpxchg8b/router.js
- website/docs/routes/blog.mdx
- website/docs/routes/programming.mdx
Close #
```routes
/cmpxchg8b/articles
```
> feat(route): cmpxchg8b

- lib/v2/douban/maintainer.js
- lib/v2/douban/other/recommended.js
- lib/v2/douban/router.js
- website/docs/routes/social-media.mdx
Close #
```routes
/douban/recommended/movie
/douban/recommended/tv/score=7
```
> feat(route): add 豆瓣当月期待剧集/电影推荐

- lib/v2/cma/channel.js
- lib/v2/cma/maintainer.js
- lib/v2/cma/radar.js
- lib/v2/cma/router.js
- lib/v2/cma/templates/description.art
- website/docs/routes/forecast.mdx
Close #13697
```routes
/cma/channel/380
```
> feat(route): add 中国气象局天气预报频道

- lib/v2/bangumi/maintainer.js
- lib/v2/bangumi/radar.js
- lib/v2/bangumi/router.js
- lib/v2/bangumi/tv/other/followrank.js
- website/docs/routes/anime.mdx
Close #
```routes
/bangumi/tv/followrank
```
> feat(route): add Bangumi 成员关注动画榜

- lib/v2/javlibrary/maintainer.js
- lib/v2/javlibrary/maker.js
- lib/v2/javlibrary/router.js
- lib/v2/javlibrary/utils.js
- website/docs/routes/multimedia.mdx
Close #
```routes
/javlibrary/videos/maker/arlq/cn
```
> feat(route): add javlibrary maker type

- lib/v2/guangdiu/maintainer.js
- lib/v2/guangdiu/radar.js
- lib/v2/guangdiu/router.js
- lib/v2/guangdiu/search.js
- website/docs/routes/multimedia.mdx
- website/docs/routes/shopping.mdx
Close #
```routes
/guangdiu/search/q=笔记本
/guangdiu/search/q=洗发水
```
- [] EN / 英文文档
> feat(route): add 逛丢关键字搜索

- lib/v2/kemono/index.js
```routes
/kemono/patreon/44261000
/kemono/patreon/5437626
```
There's no new route in this PR
> feat(route): Include enclosures for mp3, mp4, and m4a files attached to kemono posts

- lib/v2/bossdesign/index.js
- lib/v2/bossdesign/maintainer.js
- lib/v2/bossdesign/radar.js
- lib/v2/bossdesign/router.js
- website/docs/routes/design.mdx
Close #13823 
```routes
/bossdesign
```
> feat(route): bossdesign

- lib/v2/bilibili/cache.js
Close #13814
```routes
/bilibili/user/video/451320374
```
> fix(route): use api provided buvid3 and local b_nut

- lib/v2/95mm/utils.js
Close #13810
```routes
/95mm/tab/最新
```
> fix(route/95mm): Update rootUrl in utils.js

- lib/v2/douban/maintainer.js
- lib/v2/douban/other/discussion.js
- lib/v2/douban/radar.js
- lib/v2/douban/router.js
- website/docs/routes/social-media.mdx
Close #13838
```routes
/douban/36328704/discussion
```
:id为书本id，可以从url中获取，仅获取论坛第一页文章与内容。
> feat(route): add 豆瓣网站中关于某书的论坛页面(#13838)

- lib/v2/threads/index.js
- lib/v2/threads/utils.js
- website/docs/routes/social-media.mdx
Close #
```routes
/threads/instagram
```
> feat(route/threads): ditch puppeteer

- lib/v2/qbitai/category.js
- lib/v2/qbitai/maintainer.js
- lib/v2/qbitai/radar.js
- lib/v2/qbitai/router.js
- lib/v2/qbitai/tag.js
- website/docs/routes/new-media.mdx
- website/docs/routes/programming.mdx
```routes
/qbitai/category/auto
/qbitai/tag/大语言模型
```
为 [量子位](https://www.qbitai.com/) 添加路由规则
> feat(route): add 量子位

- lib/v2/showstart/params.js
- lib/v2/showstart/router.js
- lib/v2/showstart/service.js
- lib/v2/showstart/utils.js
- website/docs/routes/shopping.mdx
Close #
```routes
/showstart/params/city
/showstart/params/style
```
> feat(route/秀动网): add '/params' route for route params look up, add more detail into '/event' feed item description

- lib/v2/google/alerts.js
- lib/v2/google/maintainer.js
- lib/v2/google/router.js
- website/docs/routes/other.mdx
Close #8126
```routes
/google/alerts/RSSHub
```
> feat(route/google): Add Google Alerts

- lib/v2/bilibili/maintainer.js
- lib/v2/bilibili/platform.js
- lib/v2/bilibili/radar.js
- lib/v2/bilibili/router.js
- website/docs/routes/social-media.mdx
Close #13618
```routes
/bilibili/platform/-1/全部类型
```
> feat(route): 添加bilibili会员购票务路由(#13618)

- lib/v2/gov/maintainer.js
- lib/v2/gov/mot/index.js
- lib/v2/gov/radar.js
- lib/v2/gov/router.js
- website/docs/routes/government.mdx
Close #13771
```routes
/gov/mot/jiaotongyaowen
/gov/mot/tongjishuju/gonglu
```
> feat(route): add 中华人民共和国交通运输部

- lib/router.js
- lib/routes/universities/harvard/health/blog.js
- lib/v2/harvard/health/blog.js
- lib/v2/harvard/maintainer.js
- lib/v2/harvard/radar.js
- lib/v2/harvard/router.js
- website/docs/routes/new-media.mdx
Close #
```routes
/harvard/health/blog
```
> fix(route/harvard): replace selector

- lib/v2/gdsrx/index.js
- lib/v2/gdsrx/maintainer.js
- lib/v2/gdsrx/radar.js
- lib/v2/gdsrx/router.js
- website/docs/routes/other.mdx
Close #13775
```routes
/gdsrx/10
```
> feat(route): add 广东省食品药品审评认证技术协会

- lib/v2/aliyun/notice.js
Close #13897
```routes
/aliyun/notice
/aliyun/notice/0
/aliyun/notice/1
/aliyun/notice/2
/aliyun/notice/3
/aliyun/notice/4
```
页面结构变化导致没有抓取到内容
> fix: issue 13897

- lib/v2/dongqiudi/utils.js
Close #
```routes
/dongqiudi/daily
```
> fix: dongqiudi in-text href

- website/src/components/InstanceList.tsx
> docs: Add Zeabur instance

- website/src/components/InstanceList.tsx
> feat: add new instances

- website/src/components/InstanceList.tsx
Close #
```routes
```
add [pseudoyu instance](https://rsshub.pseudoyu.com/) for public use
> docs: add pseudoyu instance

- lib/v2/instagram/templates/images.art
- lib/v2/instagram/templates/video.art
- lib/v2/instagram/web-api/index.js
- lib/v2/instagram/web-api/utils.js
- website/docs/routes/social-media.mdx
Close #
```routes
/instagram/2/user/stefaniejoosten
```
> feat(route): authless instagram

- lib/v2/bangumi/maintainer.js
- lib/v2/bangumi/radar.js
- lib/v2/bangumi/router.js
- lib/v2/bangumi/tv/user/wish.js
- website/docs/routes/anime.mdx
Close #
```routes
/bangumi/tv/user/wish/830573
```
> feat(route): 番组计划用户想看

- lib/v2/modb/maintainer.js
- lib/v2/modb/radar.js
- lib/v2/modb/router.js
- lib/v2/modb/topic.js
- website/docs/routes/programming.mdx
```routes
/modb/topic/44158
/modb/topic/658690
```
为 [墨天轮](https://www.modb.pro/) 添加路由规则
> feat(route): add 墨天轮

- lib/v2/gov/mot/index.js
Close #
```routes
/gov/mot/tongjishuju/minhang
```
> fix(route): 中华人民共和国交通运输部统计数据文件

- lib/v2/cna/maintainer.js
- lib/v2/cna/radar.js
- lib/v2/cna/router.js
- lib/v2/cna/web/index.js
- website/docs/routes/traditional-media.mdx
Close #13516
```routes
/cna/web/aall
/cna/web/aopl
/cna/web/acn
/cna/web/aipl
/cna/web/asoc
```
> feat(route/cna): Preserve web crawling method.

- lib/v2/brave/latest.js
Close #13932
```routes
/brave/latest
```
> fix(route): did no match the version and date

- lib/v2/instagram/common-utils.js
- lib/v2/instagram/templates/images.art
- lib/v2/instagram/web-api/index.js
- lib/v2/instagram/web-api/utils.js
Close #
```routes
/instagram/2/tags/yoasobi
```
> feat(route/instagram): authless tags

- lib/v2/cfachina/analygarden.js
- lib/v2/cfachina/maintainer.js
- lib/v2/cfachina/radar.js
- lib/v2/cfachina/router.js
- website/docs/routes/other.mdx
Close #13948
```routes
/cfachina/servicesupport/analygarden
/cfachina/servicesupport/analygarden/ysjsl
```
> feat(route): cfachina

- website/docs/install/README.md
- website/i18n/zh/docusaurus-plugin-content-docs/current/install/README.md
Close #
```routes
NOROUTE
```
Implement RSSHub helm deploy docs.
> feat(deploy): Implement helm chart deploy docs.

- lib/v2/ncu/radar.js
修复了radar
Close #
```routes
NOROUTE
```
> fix(router): 南昌大学

- lib/v2/routledge/book-series.js
- lib/v2/routledge/maintainer.js
- lib/v2/routledge/radar.js
- lib/v2/routledge/router.js
- lib/v2/routledge/templates/description.art
- website/docs/routes/journal.mdx
Close #9158
```routes
/routledge/Biological-Systems-in-Vertebrates/book-series/CRCBIOSYSVER
/routledge/Species-and-Systematics/book-series/CRCSPEANDSYS
```
> feat(route): routledge

- lib/v2/1point3acres/maintainer.js
- lib/v2/amazon/maintainer.js
- lib/v2/arcteryx/maintainer.js
- lib/v2/bellroy/maintainer.js
- lib/v2/ifi-audio/maintainer.js
- lib/v2/inoreader/maintainer.js
- lib/v2/leetcode/maintainer.js
- lib/v2/magazinelib/maintainer.js
- lib/v2/patagonia/maintainer.js
- lib/v2/snowpeak/maintainer.js
- lib/v2/sony/maintainer.js
- lib/v2/techcrunch/maintainer.js
- lib/v2/theatlantic/maintainer.js
- lib/v2/wechat/maintainer.js
- lib/v2/zagg/maintainer.js
- website/docs/routes/bbs.mdx
- website/docs/routes/new-media.mdx
- website/docs/routes/program-update.mdx
- website/docs/routes/programming.mdx
- website/docs/routes/reading.mdx
- website/docs/routes/shopping.mdx
- website/docs/routes/traditional-media.mdx
refs: https://github.com/DIYgod/RSSHub/pull/12087
Close #
```routes
NOROUTE
```
> docs: update github id

- lib/v2/gov/maintainer.js
- lib/v2/gov/radar.js
- lib/v2/gov/router.js
- lib/v2/gov/safe/business.js
- lib/v2/gov/safe/complaint.js
- lib/v2/gov/safe/templates/message.art
- lib/v2/gov/safe/util.js
- website/docs/routes/government.mdx
Close #13826
```routes
/gov/safe/business/beijing
/gov/safe/complaint/beijing
```
> feat(route): add 国家外汇管理局业务咨询 & 投诉建议

- lib/v2/imiker/jinghua.js
- lib/v2/imiker/maintainer.js
- lib/v2/imiker/radar.js
- lib/v2/imiker/router.js
- lib/v2/imiker/templates/description.art
- website/docs/routes/new-media.mdx
Close #13991
```routes
/imiker/ask/jinghua
```
> feat(route): add 米课圈精华

- lib/v2/yuque/book.js
- lib/v2/yuque/utils.js
语雀的一些新增卡片内容无法被正确处理，例如：https://rsshub.app/yuque/arvinxx/note
```routes
/yuque/arvinxx/note
```
修复已有不可用的语雀路由
> fix(route): fix Yuque book route

- lib/v2/apnews/topics.js
> fix(route/apnews): remove description.

- lib/v2/gov/maintainer.js
- lib/v2/gov/nea/ghs.js
- lib/v2/gov/radar.js
- lib/v2/gov/router.js
- website/docs/routes/government.mdx
Close #13941
```routes
/gov/nea/sjzz/ghs
```
- [x New Route / 新的路由
> feat(route): add 国家能源局发展规划司

- lib/utils/common-utils.js
- package.json
- pnpm-lock.yaml
- test/utils/common-utils.js
> feat: title case following The Chicago Manual of Style

- lib/v2/sspu/jwc.js
- lib/v2/sspu/maintainer.js
- lib/v2/sspu/radar.js
- lib/v2/sspu/router.js
- website/docs/routes/university.mdx
Close #14047
```routes
/sspu/jwc/897
/sspu/jwc/898
```
> feat(route): sspu

- lib/v2/threads/index.js
Close #14059
```routes
/threads/fgfoto_
```
> fix(route): threads profile pic

- lib/v2/zhihu/maintainer.js
- lib/v2/zhihu/radar.js
- lib/v2/zhihu/router.js
- lib/v2/zhihu/xhu/activities.js
- lib/v2/zhihu/xhu/answers.js
- website/docs/routes/social-media.mdx
#6784
```routes
/zhihu/xhu/people/activities/246e6cf44e94cefbf4b959cb5042bc91
/zhihu/xhu/people/answers/246e6cf44e94cefbf4b959cb5042bc91
```
由于 xhu 不支持知乎个性化 id，所以使用 16 进制 id。id 的获取方式已写在文档中。
> feat(route): add xhu people activities and answers

- lib/v2/sehuatang/index.js
- lib/v2/sehuatang/user.js
Close #
```routes
/sehuatang/36/368
```
`postmessage*` 和`.pattl` 中同时有数据，故去除原来 `postmessage` 中 `img` 数量为0的限制
> fix(router): append  images in `.pattl`

- lib/v2/reuters/common.js
Close #
```routes
/reuters/world?limit=100&sophi=true
/reuters/world/africa
/reuters/business
/reuters/legal
/reuters/authors/jonathan-landay
```
> fix(route/reuters): Suppress full text fetch

- lib/v2/zhihu/radar.js
- website/docs/routes/social-media.mdx
#14063 
```routes
NOROUTE
```
修改了匹配 id 的正则表达式，现在不会匹配到自己了
> fix(radar): 修复 xhu 用户动态匹配到自己的问题

- lib/views/rss3-ums.js
> fix: incorrect field name in UMS

- lib/v2/qweather/3days.js
None.
```routes
/qweather/3days/上海
```
该 PR 将主要天气信息直接展示在 RSS 标题中。
原标题示例：`预报日期: 2023-12-19`
修改后示例：`2023-12-19: 小雨转阴`
> feat(route): show weather info in qweather feed title

- lib/v2/gov/maintainer.js
- lib/v2/gov/mof/bond.js
- lib/v2/gov/radar.js
- lib/v2/gov/router.js
- website/docs/routes/government.mdx
Close #
```routes
/gov/mof/bond/
/gov/mof/bond/gzfxgzdt
/gov/mof/bond/gzfxzjs
/gov/mof/bond/gzfxdzs
/gov/mof/bond/difangzhengfuzhaiquan
```
https://gks.mof.gov.cn/ztztz/guozaiguanli/gzfxgzdt/
> feat(route): add mof (bond management) 中华人民共和国财政部-专题-政府债券管理

- lib/v2/consumer/maintainer.js
- lib/v2/consumer/radar.js
- lib/v2/consumer/router.js
- lib/v2/consumer/shopping-guide.js
- website/docs/routes/new-media.mdx
Close #14067
```routes
/consumer/shopping-guide
/consumer/shopping-guide/green-living
```
> feat(route): add consumer shopping-guide

- lib/v2/dcfever/utils.js
Close #
```routes
/dcfever/news
```
> fix(route): dcfever

- lib/v2/pkmer/maintainer.js
- lib/v2/pkmer/radar.js
- lib/v2/pkmer/recent.js
- lib/v2/pkmer/router.js
- website/docs/routes/bbs.mdx
Close #
```routes
/pkmer/recent
```
> feat(route): add PKMer

- lib/v2/gamme/category.js
- lib/v2/gamme/tag.js
Close #
```routes
/gamme/news
/gamme/news
```
> fix(route): gamme

- lib/v2/gov/caac/cjwt.js
- lib/v2/gov/caac/templates/description.art
- lib/v2/gov/maintainer.js
- lib/v2/gov/radar.js
- lib/v2/gov/router.js
- website/docs/routes/government.mdx
Close #14023
```routes
/gov/caac/cjwt
```
> feat(route): add 中国民用航空局公众留言

- lib/v2/gov/maintainer.js
- lib/v2/gov/moj/lfyjzj.js
- lib/v2/gov/radar.js
- lib/v2/gov/router.js
- website/docs/routes/government.mdx
Close #14099
```routes
/gov/moj/lfyjzj
```
Attachment link available in the feed.
> feat(route): add new route for moj of gov.cn

- lib/v2/bsky/maintainer.js
- lib/v2/bsky/posts.js
- lib/v2/bsky/radar.js
- lib/v2/bsky/router.js
- lib/v2/bsky/templates/post.art
- lib/v2/bsky/utils.js
- website/docs/routes/social-media.mdx
Close #
```routes
/bsky/profile/bsky.app
/bsky/profile/atproto.com
```
> feat: bluesky user posts

- lib/v2/qweather/3days.js
- lib/v2/qweather/maintainer.js
- lib/v2/qweather/templates/3days.art
Close #14135
```routes
/qweather/3days/上海
```
> feat: add air quality content in qweather 3days forecast feed

- lib/v2/sspu/maintainer.js
- lib/v2/sspu/pe.js
- lib/v2/sspu/radar.js
- lib/v2/sspu/router.js
- website/docs/routes/university.mdx
Close #14064
```routes
/sspu/pe
```
> feat(route): add 上海第二工业大学体育部

- lib/v2/douban/other/recommended.js
Close #
```routes
/douban/recommended/tv
/douban/recommended/movie
```
> fix(route): douban recommended two-digit month

- lib/v2/otobanana/cast.js
- lib/v2/otobanana/livestream.js
- lib/v2/otobanana/maintainer.js
- lib/v2/otobanana/radar.js
- lib/v2/otobanana/router.js
- lib/v2/otobanana/templates/description.art
- lib/v2/otobanana/timeline.js
- lib/v2/otobanana/utils.js
- website/docs/routes/multimedia.mdx
Close #13795
```routes
/otobanana/user/cee16401-96b1-420f-8188-abd4d33093f1
/otobanana/user/cee16401-96b1-420f-8188-abd4d33093f1/cast
/otobanana/user/cee16401-96b1-420f-8188-abd4d33093f1/livestream
```
> feat(route): add OTOBANANA

- lib/v2/utgd/category.js
- lib/v2/utgd/templates/description.art
- lib/v2/utgd/timeline.js
- lib/v2/utgd/topic.js
None
```routes
/utgd/timeline
/utgd/method
/utgd/opinion
/utgd/topic/在线阅读专栏
/utgd/topic/卡片笔记专题
```
给 Untag 的解析增加会员文章限定的标识符，避免访问网站后才发现仅供会员阅读的烦躁
> feat: add premium identification

- lib/v2/jiemian/lists.js
Close #14161
Close #14154
```routes
/jiemian/lists/280
/jiemian/lists/426
/jiemian/lists/459
```
> fix(route): 界面新闻重复文章视频

- lib/v2/backlinko/blog.js
- lib/v2/backlinko/maintainer.js
- lib/v2/backlinko/radar.js
- lib/v2/backlinko/router.js
- website/docs/routes/blog.mdx
Close #14036
```routes
/backlinko/blog
```
> feat(route): backlinko

- lib/v2/yicai/dt.js
Close #
```routes
/yicai/dt/report
```
> fix(route): 第一财经DT财经报告附件

- lib/v2/gofans/index.js
- lib/v2/gofans/maintainer.js
- lib/v2/gofans/radar.js
- lib/v2/gofans/router.js
- lib/v2/gofans/templates/description.art
- website/docs/routes/program-update.mdx
Close #14177 
```routes
/gofans
```
https://github.com/DIYgod/RSSHub/commit/589b587397ef7d60385472eca2b9a9835b09df5d
> feat(route): recover gofans

- lib/v2/domp4/detail.js
- lib/v2/domp4/utils.js
- website/docs/routes/multimedia.mdx
Close #14181
```routes
/domp4/detail/A8kjc4333334
/domp4/detail/A8kjc4333334?second=1
/domp4/detail/A8kjc4333334?second=1&domain=wemp4.com
```
- 新兼容下载地址二，用于两个下载地址资源不一致的情况
- 顺便删除一个不可用域名
> fix: domp4 supports secondary address (#14181)

- lib/v2/acpaa/index.js
- lib/v2/acpaa/maintainer.js
- lib/v2/acpaa/radar.js
- lib/v2/acpaa/router.js
- website/docs/routes/other.mdx
Close #14137
```routes
/acpaa
```
> feat(route): add 中华全国专利代理师协会

- lib/v2/saraba1st/digest.js
Close #
```routes
/saraba1st/digest/forum-4-1
```
> fix(route): saraba1st digest image

- lib/v2/huggingface/blog-zh.js
- lib/v2/huggingface/maintainer.js
- lib/v2/huggingface/radar.js
- lib/v2/huggingface/router.js
- website/docs/routes/programming.mdx
```routes
/huggingface/blog-zh
```
[Huggingface 中文博客](https://huggingface.co/blog/zh)
> feat(route): add huggingface zh blog

- lib/v2/ekantipur/issue.js
- lib/v2/ekantipur/maintainer.js
- lib/v2/ekantipur/radar.js
- lib/v2/ekantipur/router.js
- website/docs/routes/traditional-media.mdx
Close #
```routes
/ekantipur/news
```
Full text rss for ekantipur.com (Nepal), a news portal
> feat(route): Add ekantipur.com (Nepal)

- lib/v2/hoyolab/constant.js
- lib/v2/hoyolab/maintainer.js
- lib/v2/hoyolab/news.js
- lib/v2/hoyolab/radar.js
- lib/v2/hoyolab/router.js
- website/docs/routes/game.mdx
Close #14125
```routes
/hoyolab/news/zh-cn/2/2
/hoyolab/news/zh-tw/2/2
/hoyolab/news/ja-jp/2/2
/hoyolab/news/ko-kr/2/2
/hoyolab/news/en-us/2/2
/hoyolab/news/es-es/2/2
/hoyolab/news/fr-fr/2/2
/hoyolab/news/de-de/2/2
/hoyolab/news/ru-ru/2/2
/hoyolab/news/pt-pt/2/2
/hoyolab/news/es-mx/2/2
/hoyolab/news/id-id/2/2
/hoyolab/news/vi-vn/2/2
/hoyolab/news/th-th/2/2
/hoyolab/news/zh-cn/1/2
/hoyolab/news/zh-cn/2/2
/hoyolab/news/zh-cn/4/2
/hoyolab/news/zh-cn/5/2
/hoyolab/news/zh-cn/6/2
/hoyolab/news/zh-cn/8/2
/hoyolab/news/zh-tw/2/1
/hoyolab/news/zh-tw/2/2
/hoyolab/news/zh-tw/2/3
```
> feat(route): HoYoLAB

- lib/v2/gov/maintainer.js
- lib/v2/gov/safe/util.js
Close #14223
```routes
/gov/safe/business/beijing
```
> fix(route): 国家外汇管理局业务咨询 & 投诉建议链接

- lib/v2/tradingview/desktop.js
- lib/v2/tradingview/maintainer.js
- lib/v2/tradingview/radar.js
- lib/v2/tradingview/router.js
- website/docs/routes/program-update.mdx
Close #14052
```routes
/tradingview/desktop
```
> feat(route): add TradingView Desktop releases and release notes

- lib/v2/twitch/schedule.js
- lib/v2/twitch/video.js
- website/docs/routes/live.mdx
Close #
```routes
/twitch/video/riotgames/highlights
/twitch/video/miyune
/twitch/video/anny
/twitch/schedule/riotgames
```
Fix the following problems:
1. `/twitch/video/:login/:filter?` now has the right filter type matching
example: `/twitch/video/anny`
2. `/twitch/video/:login/:filter?` category may be null
example: `/twitch/video/miyune`
3. `/twitch/schedule/:login` schedule may be null
example: `/twitch/schedule/riotgames`
> fix(route): fix twitch

- lib/v2/tencent/news/author.js
- lib/v2/tencent/templates/news/image.art
Close #14233
```routes
/tencent/news/author/5933889
```
> fix(route): tencent author

- lib/v2/hoyolab/constant.js
- lib/v2/hoyolab/news.js
- lib/v2/hoyolab/radar.js
- lib/v2/hoyolab/templates/post.art
- lib/v2/hoyolab/utils.js
- website/docs/routes/game.mdx
Close #14227
```routes
/hoyolab/news/zh-tw/6/2
/hoyolab/news/zh-tw/8/3
```
> fix(route): hoyolab

- lib/middleware/access-control.js
- test/middleware/access-control.js
Close #
```routes
NOROUTE
```
Enables `ALLOWLIST` to be set to a IP range with CIDR notation, e.g. `172.64.0.0/13` or `103.21.244.0/22`.
> feat: support CIDR IP ranges in allowlist

- lib/v2/zhihu/maintainer.js
- lib/v2/zhihu/radar.js
- lib/v2/zhihu/router.js
- lib/v2/zhihu/xhu/posts.js
- website/docs/routes/social-media.mdx
Close #14150 
```routes
/zhihu/xhu/people/posts/246e6cf44e94cefbf4b959cb5042bc91
```
由于文章详细内容需要额外发送请求，这里只请求了文章的摘要 (excerpt)
> feat(route): 知乎 xhu 用户文章

- lib/v2/shuiguopai/index.js
- lib/v2/shuiguopai/maintainer.js
- lib/v2/shuiguopai/radar.js
- lib/v2/shuiguopai/router.js
- lib/v2/shuiguopai/templates/description.art
- website/docs/routes/new-media.mdx
442d68e1895e02f1b1580d9d7831a35a8a06e293
```routes
/shuiguopai
```
> feat: recover shuiguopai

- website/docs/install/README.md
- website/i18n/zh/docusaurus-plugin-content-docs/current/install/README.md
Close #
```routes
```
Add deploy to Sealos guidance documentation.
> docs: Add deploy to Sealos

- lib/v2/coolapk/utils.js
Close #14258
```routes
/coolapk/user/1529165/dynamic
```
> fix(route): coolapk publish time

- website/docs/routes/anime.mdx
- website/docs/routes/bbs.mdx
- website/docs/routes/live.mdx
Close #
```routes
/bangumi/tv/user/wish/sai
/dlsite/ci-en/7400/article
/pikabu/user/@bula.dragon
/baidu/tieba/post/686961453
/baidu/tieba/post/lz/529691897
/zhibo8/post/3050708
/twitch/schedule/riotgames
```
只修改了一部分，没有办法把所有的 notOperational 都测试一遍
> fix(docs): 修改部分显示为 notOperational 的路由

- lib/v2/google/citations.js
- lib/v2/google/maintainer.js
- website/docs/routes/journal.mdx
Close #14275
```routes
/google/citations/mlmE4JMAAAAJ
/google/citations/mlmE4JMAAAAJ&sortby=pubdate
```
1. Fix broken URLs in feed items
2. Minor change of channel/item information description
> fix(route): broken item URL in Google Scholar Author Citations

- lib/v2/jiemian/lists.js
Close #
```routes
/jiemian/lists/801
```
> fix: 修复界面标题重复

- lib/v2/secrss/author.js
- lib/v2/secrss/category.js
- lib/v2/secrss/maintainer.js
- website/docs/routes/programming.mdx
Close #
```routes
/secrss/category
/secrss/author/网络安全威胁和漏洞信息共享平台
```
> feat(secrss): full text support

- lib/v2/tencent/templates/news/image.art
Close #14249
```routes
/tencent/news/author/5637769
```
> fix(route): tencent gifs

- lib/v2/cfmmc/index.js
- lib/v2/cfmmc/maintainer.js
- lib/v2/cfmmc/radar.js
- lib/v2/cfmmc/router.js
- website/docs/routes/finance.mdx
Close #14095
```routes
/cfmmc/main/noticeannouncement/cfmmcnotice
```
> feat(route): add 中国期货市场监控中心

- lib/v2/gov/beijing/bjedu/gh.js
- lib/v2/gov/maintainer.js
- lib/v2/gov/radar.js
- lib/v2/gov/router.js
- website/docs/routes/government.mdx
Close #14168
```routes
/gov/beijing/bjedu/gh
/gov/beijing/bjedu/gh/bjghktsb
```
> feat(route): bjedu

- lib/v2/twitter/web-api/twitter-api.js
Close #14285
```routes
/twitter/user/bugcat_capoo_tw/excludeReplies=1
```
The postprocessing that removes replies accidentally removed all tweets except for the first one after the recent Twitter update.
> fix(route/twitter/web-api): excludeReplies=1

- lib/v2/laimanhua/index.js
- lib/v2/laimanhua/maintainer.js
- lib/v2/laimanhua/radar.js
- lib/v2/laimanhua/router.js
- website/docs/routes/anime.mdx
Close #14158
```routes
/laimanhua/tiandikangzhanjiVERSUS
```
> feat(route): laimanhua

- lib/routes/us/supremecourt/argument-audio.js
- lib/v2/kcna/news.js
- lib/v2/xueqiu/hots.js
- lib/v2/xueqiu/router.js
- lib/v2/xueqiu/stock-comments.js
- lib/v2/xueqiu/stock-info.js
- lib/v2/xueqiu/user.js
- website/docs/routes/finance.mdx
Close #
```routes
/us/supremecourt/argument_audio/2023
/kcna/en
/xueqiu/hots
```
> fix: codeql incomplete multi-character sanitization

- lib/v2/keepass/maintainer.js
- lib/v2/keepass/news.js
- lib/v2/keepass/radar.js
- lib/v2/keepass/router.js
- website/docs/routes/program-update.mdx
Close #
```routes
/keepass
```
> feat(route): keepass

- lib/v2/huanqiu/index.js
Close #14294
```routes
/huanqiu/news/china
```
> fix(route): huanqiu

- lib/v2/mrm/index.js
- lib/v2/mrm/maintainer.js
- lib/v2/mrm/radar.js
- lib/v2/mrm/router.js
- website/docs/routes/finance.mdx
Close #14310
```routes
/mrm
/mrm/zhengceguiding_list
```
> feat(route): mrm

- lib/v2/chuanliu/maintainer.js
- lib/v2/chuanliu/nice.js
- lib/v2/chuanliu/radar.js
- lib/v2/chuanliu/router.js
- lib/v2/chuanliu/templates/description.art
- website/docs/routes/blog.mdx
Close #14296
```routes
/chuanliu/nice
```
> feat(route): add 川流严选

- lib/v2/tencent/news/author.js
Close #
```routes
/tencent/news/author/5069188
```
> fix(route/tencent): Circumvent video type link.

- lib/middleware/parameter.js
- lib/v2/test/index.js
- test/middleware/parameter.js
> fix: use sanitize-html

- lib/v2/foresightnews/util.js
Close #14217
```routes
/foresightnews/column/435
```
> fix(route): Foresight News column

- lib/v2/firefox/release.js
- lib/v2/firefox/router.js
Close #14087
```routes
/firefox/release/beta
```
> fix(route): Firefox release notes

- lib/v2/javlibrary/utils.js
Close #
```routes
/javlibrary/genre/ardq/ja/2
```
Fix javlibrary genre route because some spans may not have class attr in individual pages
> fix: javlibrary genre route because some spans may not have class attr in individual pages

- lib/v2/guanhai/index.js
Close #14335
```routes
/guanhai
```
> fix(route): guanhai

- lib/v2/auto-stats/index.js
- lib/v2/auto-stats/maintainer.js
- lib/v2/auto-stats/radar.js
- lib/v2/auto-stats/router.js
- website/docs/routes/other.mdx
Close #14147
```routes
/auto-stats
```
> feat(route): add 中国汽车工业协会统计信息网

- lib/v2/modrinth/radar.js
- website/docs/routes/game.mdx
> fix(modrinth): correct the radar rules for working with

- lib/v2/modrinth/radar.js
> fix(modrinth): match index of projects

- website/docs/routes/game.mdx
> docs(modrinth): add query params & fix the route path

- lib/v2/jike/topic.js
Close #
```routes
/jike/topic/553870e8e4b0cafb0a1bef68
```
rss内容包含很多链接，让链接可点击
> feat: make url clickable

- lib/v2/caixin/weekly.js
Close #
```routes
/caixin/weekly
```
> feat(route): Optimize the title of Caixin Weekly | 优化《财新周刊》标题

- .github/PULL_REQUEST_TEMPLATE.md
- scripts/workflow/test-route/identify.js
Close #
```routes
NOROUTE
```
In `.github/PULL_REQUEST_TEMPLATE.md`, the code example in the routes section uses the wrong word. If a careless user (like me) copies directly from the example, the PR bot will not be able to pick the route value because the label is incorrect.
This PR fixes this. It also updated `identify.js` so that the "routes" example in the comments won't be consider as a match.
> chore: update the "routes" example in the pull request template to make it less confusing

- lib/v2/konghq/blog-posts.js
- lib/v2/konghq/maintainer.js
- lib/v2/konghq/radar.js
- lib/v2/konghq/router.js
- website/docs/routes/programming.mdx
Close #
```routes
/konghq/blog-posts
```
Kong is an open source API gateway provider, this PR adds a route that collects the latest blog posts on [the official website](https://konghq.com/blog/page/1), the posts include product news and API gateway related technical articles.
> feat(route): add new route "konghq/blog-posts"

- lib/v2/tass/maintainer.js
- lib/v2/tass/news.js
- lib/v2/tass/radar.js
- lib/v2/tass/router.js
- website/docs/routes/traditional-media.mdx
Close #12362
```routes
/tass
/tass/world
```
> feat(route): tass

- lib/v2/bsky/posts.js
Close #
```routes
/bsky/profile/rin7914.bsky.social
```
fixes `Cannot read properties of undefined (reading 'replaceAll')` when fetching posts from account without description set.
> fix(route): bsky empty description

- lib/v2/zhihu/maintainer.js
- lib/v2/zhihu/router.js
- lib/v2/zhihu/topic.js
- lib/v2/zhihu/utils.js
- website/docs/routes/social-media.mdx
Close #6839
```routes
/zhihu/topic/20088356/1
```
> feat(route): zhihu top topic

- lib/router.js
- lib/v2/cs/maintainer.js
- lib/v2/cs/radar.js
- lib/v2/cs/router.js
- lib/v2/cs/zzkx.js
- website/docs/routes/finance.mdx
Close #14420
```routes
/cs/zzkx
```
> feat(route): 中证网中证快讯

- lib/v2/chinamoney/channels.js
- lib/v2/chinamoney/maintainer.js
- lib/v2/chinamoney/notice.js
- lib/v2/chinamoney/radar.js
- lib/v2/chinamoney/router.js
- website/docs/routes/finance.mdx
Close #10880
```routes
/chinamoney
/chinamoney/2835
```
> feat(route): chinamoney

- lib/v2/wmc-bj/maintainer.js
- lib/v2/wmc-bj/publish.js
- lib/v2/wmc-bj/radar.js
- lib/v2/wmc-bj/router.js
- lib/v2/wmc-bj/templates/description.art
- website/docs/routes/other.mdx
Close #14391
```routes
/wmc-bj/publish/CRA-Reanalysis/2m-Temperature/6-hour/index.html
```
> feat(route): add World Meteorological Centre Beijing Publish

- lib/v2/huxiu/util.js
Close #
```routes
/huxiu/moment
```
> fix(route/huxiu): Prevent URL parsing error.

- pnpm-lock.yaml
> chore: bump deps

- lib/v2/cs/maintainer.js
- lib/v2/cs/radar.js
- lib/v2/cs/router.js
- lib/v2/cs/video.js
- website/docs/routes/finance.mdx
Close #
```routes
/cs/video/今日聚焦
```
> feat(route): add 中证网中证视频

- lib/v2/fansly/maintainer.js
- lib/v2/fansly/post.js
- lib/v2/fansly/radar.js
- lib/v2/fansly/router.js
- lib/v2/fansly/tag.js
- lib/v2/fansly/templates/media.art
- lib/v2/fansly/templates/poll.art
- lib/v2/fansly/templates/tip-goal.art
- lib/v2/fansly/utils.js
- website/docs/routes/social-media.mdx
Close #
```routes
/fansly/user/AeriGoMoo
/fansly/tag/free
```
> feat(route): fansly

- lib/v2/shoac/maintainer.js
- lib/v2/shoac/radar.js
- lib/v2/shoac/recent-show.js
- lib/v2/shoac/router.js
- lib/v2/shoac/templates/detail.art
- website/docs/routes/shopping.mdx
Close #14393
```routes
/shoac/recent-show
```
> feat(route): shoac

- lib/v2/playpcesor/maintainer.js
- lib/v2/playpcesor/radar.js
- lib/v2/playpcesor/router.js
- lib/v2/playpcesor/rss.js
- website/docs/routes/blog.mdx
Close #
```routes
/playpcesor
```
> feat(route): add 电脑玩物

- lib/v2/lofter/tag.js
Close #14438
```routes
/lofter/tag/i
/lofter/tag/i/new
/lofter/tag/i/date
/lofter/tag/i/week
/lofter/tag/i/month
/lofter/tag/i/total
```
直接从 `https://www.lofter.com/dwr/call/plaincall/TagBean.getCommonTagExcellentAuthors.dwr` 抓取 DWR 内容然后处理，这样就不需要 Cookie 了
> fix: lofter tag 绕过登录需求

- lib/router.js
- lib/v2/indienova/article.js
- lib/v2/indienova/column.js
- lib/v2/indienova/gamedb.js
- lib/v2/indienova/maintainer.js
- lib/v2/indienova/radar.js
- lib/v2/indienova/router.js
- lib/v2/indienova/usergames.js
- lib/v2/indienova/utils.js
- website/docs/routes/game.mdx
Close #14485
```routes
/indienova/article
/indienova/column/52
/indienova/gamedb/recent
/indienova/usergames
```
> feat(route): indienova

- lib/v2/instagram/common-utils.js
Close #14368
```routes
/instagram/user/englishwithronia
```
> fix(route): instagram null caption

- lib/v2/jjwxc/author.js
- lib/v2/jjwxc/book.js
- lib/v2/jjwxc/maintainer.js
- lib/v2/jjwxc/radar.js
- lib/v2/jjwxc/router.js
- lib/v2/jjwxc/templates/author.art
- lib/v2/jjwxc/templates/book.art
- website/docs/routes/reading.mdx
Close #14477
```routes
/jjwxc/author/4364484
/jjwxc/book/7013024
```
> feat(route): add 晋江文学城作者最新作品

- lib/v2/hitwh/today.js
Close #14507
```routes
/hitwh/today
```
> fix(route): hitwh

- lib/v2/qdu/houqin.js
- lib/v2/qdu/maintainer.js
- lib/v2/qdu/radar.js
- lib/v2/qdu/router.js
- website/docs/routes/university.mdx
Close #
```routes
/qdu/houqin
```
> feat(route): Add qdu houqin

- lib/v2/cna/web/index.js
Close #
```routes
/cna/web/aall
/cna/web/aopl
/cna/web/acn
/cna/web/aipl
/cna/web/asoc
```
> fix(route/cna): Rectify link.

- lib/v2/56kog/class.js
- lib/v2/56kog/maintainer.js
- lib/v2/56kog/radar.js
- lib/v2/56kog/router.js
- lib/v2/56kog/templates/description.art
- lib/v2/56kog/top.js
- lib/v2/56kog/util.js
- website/docs/routes/reading.mdx
Close #14476
```routes
/56kog/class/1_1
/56kog/top/weekvisit
```
> feat(route): add 明月中文网

- lib/v2/ft/myft.js
Close #
```routes
/ft/myft/12345678-abcd-4036-82db-vdv20db024b8
```
> fix(route/ft): Fix author name.

- lib/v2/pts/index.js
> fix(route/pts): Modify item parsing method.

- lib/v2/u9a9/index.js
Close #
```routes
/u9a9
/u9a9/on
/u9a9/search/新片速递
/u9a9/search/新片速递/on
```
当前读取的缓存没有返回，导致u9a9 相关的结果缺失预览图。 无相关issue
> fix(router/u9a9): return cache if need

- lib/v2/remnote/changelog.js
- lib/v2/remnote/maintainer.js
- website/docs/routes/program-update.mdx
Close #
```routes
/remnote/changelog
```
> fix(route/remnote): fix author name

- lib/v2/boc/radar.js
- lib/v2/cib/maintainer.js
- lib/v2/cib/radar.js
- lib/v2/cib/router.js
- lib/v2/cib/whpj.js
- lib/v2/iqnew/radar.js
- website/docs/routes/other.mdx
兴业银行外汇牌价
Close #14508
```routes
/cib/whpj/xh?filter_title=USD
```
兴业银行外汇牌价 rss
修正另外两个 radar 规则文档错误的问题
> feat(route): cib/whpj

- lib/v2/kemono/index.js
> fix(route): Kemono Posts published date

- lib/v2/bilibili/utils.js
该 PR 是为了提升 B站视频嵌入的观看，之前的嵌入方式，会很容易发起跳转到 B站，比如点击视频就会
PR 中的方式可以避免这种情况的发生，更加简洁
```routes
NOROUTE
```
> fix: 更改 B站嵌入方式来防止误点会导致跳转 B站

- lib/v2/bilibili/watchlater.js
Close #14395
```routes
/bilibili/watchlater/1755549
```
需要自建实例  
修正列表为空时的报错
> fix(route): bilibili/watchlater

- lib/v2/lala/maintainer.js
- lib/v2/lala/radar.js
- lib/v2/lala/router.js
- lib/v2/lala/rss.js
- website/docs/routes/blog.mdx
> feat(route): add 荒岛

- lib/v2/m4/index.js
- lib/v2/m4/maintainer.js
- lib/v2/m4/radar.js
- lib/v2/m4/router.js
- lib/v2/m4/templates/description.art
- website/docs/routes/new-media.mdx
Close #
```routes
/m4/news/china
/m4/mil/china
```
> feat(route): add 四月网

- lib/v2/unraid/community-apps.js
- lib/v2/unraid/maintainer.js
- lib/v2/unraid/radar.js
- lib/v2/unraid/router.js
- website/docs/routes/program-update.mdx
Close #
```routes
/unraid/community-apps
/unraid/community-apps?limit=50
```
add feed for [unraid community apps](https://unraid.net/community/apps), sorted by last updated
> feat(route): add unraid community apps

- lib/v2/u3c3/index.js
- lib/v2/u3c3/maintainer.js
- lib/v2/u3c3/router.js
- website/docs/routes/multimedia.mdx
Close #
```routes
/u3c3
/u3c3/U3C3
/u3c3/Videos
/u3c3/Photo
/u3c3/Book
/u3c3/Game
/u3c3/Software
/u3c3/Other
/u3c3/U3C3/preview
/u3c3/Videos/preview
/u3c3/Photo/preview
/u3c3/Book/preview
/u3c3/Game/preview
/u3c3/Software/preview
/u3c3/Other/preview
/u3c3/search/新片速递
/u3c3/search/新片速递/preview
```
路由基本和u9a9 保持一致
> feat(router/u3c3): support preview

- lib/v2/zrblog/maintainer.js
- lib/v2/zrblog/radar.js
- lib/v2/zrblog/router.js
- lib/v2/zrblog/rss.js
- website/docs/routes/blog.mdx
> feat(route): add 赵容部落

- lib/v2/tvtropes/featured.js
- lib/v2/tvtropes/maintainer.js
- lib/v2/tvtropes/radar.js
- lib/v2/tvtropes/router.js
- lib/v2/tvtropes/templates/description.art
- website/docs/routes/other.mdx
Close #14554
```routes
/tvtropes/featured/today
```
> feat(route): add TV Tropes Featured

- lib/v2/sfacg/maintainer.js
- lib/v2/sfacg/novel-chapter.js
- lib/v2/sfacg/radar.js
- lib/v2/sfacg/router.js
- website/docs/routes/reading.mdx
Close #
```routes
/sfacg/novel/chapter/672431
```
> feat(route): add sfacg

- lib/v2/hbooker/chapter.js
- lib/v2/hbooker/maintainer.js
- lib/v2/hbooker/radar.js
- lib/v2/hbooker/router.js
- website/docs/routes/reading.mdx
Close #
```routes
/hbooker/chapter/100113279
```
> feat(route): add 欢乐书客

- lib/v2/ciweimao/chapter.js
- lib/v2/ciweimao/maintainer.js
- lib/v2/ciweimao/radar.js
- lib/v2/ciweimao/router.js
- website/docs/routes/reading.mdx
Close #
```routes
/ciweimao/chapter/100043404
```
> feat(route): add 刺猬猫

- lib/v2/wmpvp/index.js
- lib/v2/wmpvp/maintainer.js
- lib/v2/wmpvp/radar.js
- lib/v2/wmpvp/router.js
- website/docs/routes/game.mdx
Close #
```routes
/wmpvp/news/1
/wmpvp/news/2
```
> feat(route): Add wmpvp

- lib/v2/tongji/bks.js
- lib/v2/tongji/maintainer.js
- lib/v2/tongji/radar.js
- lib/v2/tongji/router.js
- website/docs/routes/university.mdx
```routes
/tongji/bks
```
同济大学本科生院通知
> feat(route): tongji/bks

- lib/routes.test.ts
- lib/routes.ts
Close #
```routes
/favicon.ico
```
> fix: favicon not found

- lib/routes/github/notifications.js
Close #
```routes
/github/notifications
```
将通知link的api链接还原成原有的url,便于点击直接访问
> feat(route): Rewrite the API URL to original URL

- lib/routes/bilibili/like.js
- lib/routes/bilibili/maintainer.js
- lib/routes/bilibili/radar.js
- lib/routes/bilibili/router.js
- website/docs/routes/social-media.mdx
Close #
```routes
/bilibili/user/like/208259
/bilibili/user/like/208259/0
```
> feat(route): add bilibili UP 主点赞视频

- lib/routes/radio-canada/latest.js
…rect data
Close https://github.com/DIYgod/RSSHub/issues/14597
```routes
/radio-canada/latest/en
/radio-canada/latest/zh-hans
```
> fix(route): fix radio canada by fixinggular expression to match correct data

- lib/routes/zhujiceping/maintainer.js
- lib/routes/zhujiceping/radar.js
- lib/routes/zhujiceping/router.js
- lib/routes/zhujiceping/rss.js
- website/docs/routes/blog.mdx
Close #
```routes
/zhujiceping
```
> feat(route): add 国外主机测评

- lib/routes/baidu/radar.js
- lib/routes/baidu/tieba/forum.js
- lib/routes/baidu/tieba/post.js
Close #
```routes
/baidu/tieba/forum/neurosama
/baidu/tieba/forum/good/neurosama
/baidu/tieba/post/686961453
/baidu/tieba/post/lz/686961453
```
顺便修了一个 radar 的错误
> fix(route): 百度贴吧

- lib/routes/weibo/user.js
Close #14627
```routes
/weibo/user/2880438310/readable=1&showEmojiForRetweet=1&showTimestampInDescription=1&displayArticle=1&displayComments=1&showEmojiInDescription=0&showLinkIconInDescription=0
```
> fix(route/weibo/user): querystring

- website/docs/joinus/advanced/debug.md
- website/docs/parameter.md
- website/i18n/zh/docusaurus-plugin-content-docs/current/joinus/advanced/debug.md
- website/i18n/zh/docusaurus-plugin-content-docs/current/parameter.md
Close #14644
```routes
/furstar/characters/en?format=atom
```
> docs: update output format

- lib/errors/index.test.ts
- lib/errors/index.ts
- lib/middleware/debug.ts
- lib/utils/debug-info.ts
- lib/utils/git-hash.ts
- lib/views/error.art
- lib/views/index.tsx
> feat(index): add back hot stats

- website/docs/install/config.md
- website/i18n/zh/docusaurus-plugin-content-docs/current/install/config.md
> docs: fix Mastodon config documentation

- lib/router.js
- lib/routes/zhuwang/index.ts
- lib/routes/zhuwang/maintainer.ts
- lib/routes/zhuwang/radar.ts
- lib/routes/zhuwang/router.ts
- website/docs/routes/other.mdx
- website/docs/routes/shopping.mdx
Close #14662
```routes
/zhuwang/zhujia
```
> fix(route): recover zhuwang

- lib/middleware/anti-hotlink.test.ts
- lib/middleware/anti-hotlink.ts
- lib/middleware/parameter.test.ts
- lib/routes/test/index.ts
Close #
```routes
/test/complicated?image_hotlink_template=https%3A%2F%2Fi3.wp.com%2F%24%7Bhost%7D%24%7Bpathname%7D
```
> fix(anti-hotlink): skip base64 image

- lib/routes/scmp/index.ts
- lib/routes/scmp/utils.ts
> fix(route): scmp

- lib/routes/techflowpost/express.ts
- lib/routes/techflowpost/index.ts
- lib/routes/techflowpost/radar.ts
- website/docs/routes/finance.mdx
- website/docs/routes/new-media.mdx
Close #
```routes
/techflowpost
/techflowpost/express
```
> fix(route): techflowpost

- lib/routes/bloomberg/utils.ts
Close #
```routes
/bloomberg/markets
```
> fix(route): bloomberg video parsing

- lib/routes/casssp/maintainer.ts
- lib/routes/casssp/news.ts
- lib/routes/casssp/radar.ts
- lib/routes/casssp/router.ts
- website/docs/routes/government.mdx
Close #14588
```routes
/casssp/news/3
```
> feat(route): add 中国科学学与科技政策研究会研究会动态

- lib/routes/qust/jw.ts
- lib/routes/qust/maintainer.ts
- lib/routes/qust/radar.ts
- lib/routes/qust/router.ts
- website/docs/routes/university.mdx
No related issues
```routes
/qust/jw
```
This is the academic affairs notice of Qingdao University of Science and Technology.
> feat(route): add qust jw

- lib/routes/pku/scc/recruit.ts
- website/docs/routes/university.mdx
None
```routes
/pku/scc/recruit
/pku/scc/recruit/xwrd
/pku/scc/recruit/tzgg
/pku/scc/recruit/zpxx
/pku/scc/recruit/sxxx
/pku/scc/recruit/cyxx
```
1. 修了`link`不为字符串的问题
2.  原[`国防军工信息/gfjgxx`](https://scc.pku.edu.cn/home!recruitList.action?category=1&jobType=110002)已很久没有更新且在首页中隐藏，故删去
> fix(route): /pku/scc/recruit

- lib/routes/wenku8/volume.ts
- website/docs/routes/reading.mdx
```routes
/wenku8/volume/1973
```
> fix(route): wenku8 volume

- lib/routes/docschina/jsweekly.ts
- lib/routes/docschina/maintainer.ts
- lib/routes/docschina/radar.ts
- lib/routes/docschina/router.ts
- lib/routes/docschina/weekly.ts
- website/docs/routes/programming.mdx
Close #
```routes
/docschina/weekly
/docschina/weekly/js
/docschina/weekly/react
/docschina/weekly/node
```
> fix: 修复印记中文周刊rss feat: 为印记中文rss增加分类

- lib/routes/aeon/utils.ts
Close #
```routes
/aeon/essays
```
> fix(route): show correct author name (AEON)

- lib/middleware/access-control.ts
> fix: logo not showing with ACCESS_KEY

- assets/404.html
- assets/CNAME
- assets/index.html
Close #
```routes
NOROUTE
```
docs: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site
> chore: fix rsshub.js.org not working

- lib/routes/weibo/friends.ts
- lib/routes/weibo/group.ts
- lib/routes/weibo/keyword.ts
- lib/routes/weibo/oasis/user.ts
- lib/routes/weibo/super-index.ts
- lib/routes/weibo/timeline.ts
- lib/routes/weibo/user.ts
- lib/routes/weibo/utils.ts
Close #14738
```routes
/weibo/user/6827625527
```
> fix: weibo image regex

- lib/routes/cast/index.ts
Close #
```routes
NOROUTE
```
removed the custom interface `ResponseData`, added radar config
> refactor(router): cast

- lib/routes/aeaweb/index.ts
- lib/routes/annualreviews/index.ts
- lib/routes/nber/index.ts
- lib/routes/oup/index.ts
- lib/routes/trendingpapers/papers.ts
- lib/routes/uchicago/current.ts
Close #14758 
```routes
/aeaweb/aer
/annualreviews/anchem
/oup/journals/adaptation
/uchicago/journals/current/jpe
/nber/papers
/trendingpapers/papers
```
> fix(route): 添加language字段

- lib/routes/booru/mmda.ts
- website/docs/routes/picture.mdx
Close #
```routes
/booru/mmda/tags
/booru/mmda/tags/full_body
/booru/mmda/tags/full_body%20blue_eyes
/booru/mmda/tags/user:hsjsekdjd
```
> fix(route): fix MMDArchive example

- lib/routes/modrinth/versions.ts
- lib/utils/got.ts
Close #
```routes
/modrinth/project/sodium/versions
```
> fix(modrinth): fix the path & adapt to typescript

- lib/routes/wmpvp/index.ts
Close #
```routes
/wmpvp/news/1
/wmpvp/news/2
```
> fix(route): Update wmpvp news title

- lib/routes/jpxgmn/namespace.ts
- lib/routes/jpxgmn/search.ts
- lib/routes/jpxgmn/tab.ts
- lib/routes/jpxgmn/templates/description.art
- lib/routes/jpxgmn/utils.ts
- lib/routes/jpxgmn/weekly.ts
- website/docs/routes/picture.mdx
Close #
```routes
/jpxgmn/weekly
/jpxgmn/tab
/jpxgmn/tab/new
/jpxgmn/tab/Xiuren
/jpxgmn/search/candy
```
- [源网站](http://www.jpxgmn.com/)会重定向
- 名字有点土但不知道取什么合适
- ~不知道新规范下怎么更新文档，姑且手改的。运行`pnpm run build`可以更新文档但会有太多变化~
- radar调试不了就没有加。本地起临时服务器，手动更新后提示成功但没有变化
> feat(route): jpxgmn

- lib/routes/ouc/jwc.ts
```routes
/ouc/jwc
```
修复link中为其他网址链接是出现错误。
> fix(route): 中国海洋大学教务处

- lib/routes/booru/mmda.ts
- lib/routes/booru/templates/description.art
- website/docs/routes/picture.mdx
Close #
```routes
/booru/mmda/tags
/booru/mmda/tags/full_body
/booru/mmda/tags/full_body%20blue_eyes
/booru/mmda/tags/user:hsjsekdjd
```
> feat(route): /booru/mmda MMDArchive Better Reading Experience and add radar

- lib/routes/pianyivps/rss.ts
Close #
```routes
/pianyivps
```
增加文档的举例
> fix(route): Fix 便宜VPS网

- lib/router.js
- lib/routes/nosec/index.ts
- lib/routes/nosec/namespace.ts
Close #
```routes
/nosec/hole
```
迁移nosec路由
> fix(route): Fix nosec

- lib/routes/reactiflux/namespace.ts
- lib/routes/reactiflux/transcripts.ts
Close #14729
```routes
/reactiflux/transcripts
```
> feat(route): add Reactiflux Transcripts

- lib/routes/readhub/daily.ts
(cherry picked from commit b4aec4d3fd9943129d5fd4893aaad056b4b238de)
Close #
```routes
/readhub/daily
```
> fix(route): fix readhub/daily error

- lib/routes/bilibili/user-collection.ts
Close #14773
```routes
/bilibili/user/collection/489667127/249279/false/1/2
```
排序使用默认排序(从新到旧),之前使用的排序(从旧到新)确实没有继续使用的意义,故直接替换了  
新增支持page参数,此参数不影响正常使用
> fix(route): bilibili/user/collection

- lib/routes/web/series.ts
> fix(route): remove redundant whitespace (web)

- lib/routes/github/comments.ts
Close DIYgod/RSSHub-Radar#953
```routes
github/comments/DIYgod/RSSHub-Radar
github/comments/DIYgod/RSSHub-Radar/953
```
修正 Radar 规则
> fix DIYgod/RSSHub-Radar#953

- lib/routes/kemono/index.ts
> feat(route): Kemono Posts remove Ad

- lib/routes/lala/rss.ts
Close #
```routes
/lala
```
修改文档描述
> fix(route): Fix 荒岛

- lib/routes/cs/index.ts
- lib/routes/cs/namespace.ts
Close #14835
```routes
/cs/xwzx/hg
```
> fix: cs index path

- lib/routes/hicairo/rss.ts
Close #
```routes
/hicairo
```
修改文档描述
> fix(route): Fix HiFeng'Blog

- lib/routes/wmpvp/index.ts
Close #
```routes
/wmpvp/news/1
/wmpvp/news/2
```
Update wmpvp news description
> feat(route): Update wmpvp news description

- lib/routes/howtoforge/rss.ts
Close #
```routes
/howtoforge
```
修改文档描述
> fix(route): Fix howtoforge

- lib/routes/zjut/da/index.ts
- lib/routes/zjut/namespace.ts
Close #
```routes
/zjut/da/1
/zjut/da/2
/zjut/da/3
/zjut/da/4
/zjut/da/5
/zjut/da/6
```
> feat(route): Add 浙江工业大学设计与建筑学院通知

- lib/routes/zhujiceping/rss.ts
Close #
```routes
/zhujiceping
```
修改文档描述
> fix(route): Fix 国外主机测评

- lib/routes/ouc/hqsz.ts
Close #
```routes
/ouc/hqsz
```
> feat(route):  中国海洋大学后勤通知

- lib/routes/playpcesor/rss.ts
Close #
```routes
/playpcesor
```
修改文档描述
> fix(route): Fix 电脑玩物

- lib/routes/usenix/loginonline.ts
```routes
/usenix/loginonline
```
> feat(route): Add USENIX ;login:

- lib/routes/bulianglin/rss.ts
Close #
```routes
/bulianglin
```
修改文档描述
> fix(route): fix 不良林

- lib/routes/priconne-redive/news.ts
Close #
```routes
/priconne-redive/news
/priconne-redive/news/jp
/priconne-redive/news/zh-cn
/priconne-redive/news/zh-tw
```
恢复了公主连结国服和台服公告的路由，同时保留了原来的日服公告的可用性。
> feat(route): recover priconne-redive

- lib/routes/x6d/index.ts
Close #14811
```routes
/x6d/34
```
> fix(route): 小刀娱乐网

- lib/routes/loongarch/namespace.ts
- lib/routes/loongarch/post.ts
Close #
```routes
/loongarch/post
/loongarch/post/newest
/loongarch/post/top
```
> feat(route): Add LA UOSC社区

- lib/routes/36kr/index.ts
- lib/routes/kaopu/news.ts
Close #
```routes
/36kr/news
/36kr/newsflashes
/36kr/information/recommend
/36kr/information/life
/36kr/information/estate
/36kr/information/workplace
/36kr/search/articles/google
```
> fix(route): fix 36kr route & kaopu.news doc desc

- lib/router.js
- lib/routes/afdian/dynamic.ts
- lib/routes/afdian/explore.ts
- lib/routes/afdian/namespace.ts
Close #
```routes
/afdian/dynamic/@afdian
/afdian/explore/hot/所有
```
迁移爱发电路由
> fix(route): Fix afdian

- lib/routes/douban/book/latest.ts
Close #
```routes
/douban/book/latest
/douban/book/latest/fiction
/douban/book/latest/prose_poetry
/douban/book/latest/history
/douban/book/latest/biography
/douban/book/latest/science
/douban/book/latest/art
/douban/book/latest/business
/douban/book/latest/comics
```
udpate route's description to display correctly
> doc(route):/douban/book/latest

- lib/routes/3dmgame/game.ts
- lib/routes/3dmgame/news-center.ts
Close #14647
```routes
/3dmgame/news
/3dmgame/news/game
/3dmgame/news/acg
/3dmgame/news/next
/3dmgame/news/news_36_1
/3dmgame/games/witcher3
/3dmgame/games/witcher3/gl
```
route `/3dmgame/:name/:type?` will occupy route `/3dmgame/news` causing `/3dmgame/news` to not be captured by the router;
changed the route `/3dmgame/:name/:type?` to `/3dmgame/games/:name/:type?`
> fix(route):/3dmgame/news

- lib/routes/linovelib/namespace.ts
- lib/routes/linovelib/volume.ts
```routes
/linovelib/volume/8
```
> feat(route): linovelib volume

- lib/routes/ippa/namespace.ts
- lib/routes/ippa/rss.ts
> feat(route): add 子方有料

- lib/routes/2023game/index.ts
Close #
```routes
/2023game
/2023game/sgame
/2023game/sgame/topicList
```
> fix(route): fix 2023game route description

- .github/dependabot.yml
- lib/utils/got.ts
- lib/utils/request-wrapper.ts
- package.json
- pnpm-lock.yaml
> chore: upgrade got

- lib/routes/abc/index.ts
> fix(route): fix indentation issue in ABC news description

- lib/routes/bilibili/user-collection.ts
Close #
```routes
bilibili/user/collection/489667127/249279/true/1/2
bilibili/user/collection/489667127/249279/0/1/2
bilibili/user/collection/489667127/249279
```
修正向 disableEmbed 传递任意值都将关闭内嵌视频,导致使用后续参数就造成 disableEmbed 不可用的问题
> fix(route): bilibli/user/collection disableEmbed

- lib/routes/appstorrent/namespace.ts
- lib/routes/appstorrent/programs.ts
- lib/routes/appstorrent/templates/description.art
Close #
```routes
/appstorrent/programs
```
> feat(route): Add appstorrent

- lib/router.js
- lib/routes/blogread/index.ts
- lib/routes/blogread/namespace.ts
Close #
```routes
/blogread/newest
```
> feat(route): recover route blogread/newest

- lib/routes/163/dy2.ts
- lib/routes/163/utils.ts
Close #14939
```routes
/163/dy2/T1555591616739
```
> fix(route): /163/dy2/:id pic shows correctly

- lib/routes/bnu/jwb.ts
Close #14736 
```routes
/bnu/jwb
```
> feat(route): Add 北京师范大学教务部

- lib/routes/gamer520/index.ts
- lib/routes/gamer520/namespace.ts
Close #
```routes
/gamer520/switchyouxi
/gamer520/3ajuzuo
```
具有cloudflare保护，需要私人部署才行
> feat(route): Add gamer520(全球游戏交流中心)

- lib/routes/github/star.ts
- lib/routes/github/starred-repos.ts
Close #14928
```routes
/github/starred_repos/DIYgod
```
> fix: github user starred repos use reset api

- lib/routes/github/starred-repos.ts
- lib/utils/request-wrapper.ts
Close #
```routes
/github/starred_repos/DIYgod
```
> fix(core): accept header not working

- lib/routes/guokr/channel.ts
- lib/routes/guokr/scientific.ts
- lib/routes/guokr/utils.ts
Close #
```routes
/guokr/column/calendar
/guokr/scientific
```
> fix(route): guokr channel path

- lib/routes/smzdm/article.ts
Close #14921
```routes
/smzdm/article/9573871417
```
什么值得买用户主页可以正常显示
> fix(route): /smzdm/article/:uid

- lib/routes/aeon/category.ts
- lib/routes/aeon/type.ts
- lib/routes/aeon/utils.ts
Close #
```routes
/aeon/essays
```
> fix(route): use publishedAt (AEON)

- lib/routes/bjfu/namespace.ts
Close #14736 
```routes
NOROUTE
```
该Issue中提到的北京林业大学被错写成北京师范大学，导致文档中出现两个北京师范大学。
相关文档:
https://docs.rsshub.app/zh/routes/university#%E5%8C%97%E4%BA%AC%E5%B8%88%E8%8C%83%E5%A4%A7%E5%AD%A6
> fix(route):  fix the namespace for BJFU

- lib/routes/twreporter/category.ts
- lib/routes/twreporter/fetch-article.ts
Close #
```routes
/twreporter/category/world
```
> feat(route): support category and fix time (twreporter)

- lib/routes/ntdm/namespace.ts
- lib/routes/ntdm/utils.ts
- lib/routes/ntdm/video.ts
Close #
```routes
/ntdm/video/4309
```
added a new route for the ntdm anime website here.
> feat(route): add ntdm (animate)

- lib/routes/pts/index.ts
> fix(route/pts): Refine link selector.

- lib/routes/18comic/templates/description.art
- lib/routes/18comic/utils.ts
Close #
```routes
/18comic/all/a/mv
/18comic/all/a/mv?domain=jmcomic1.me
/18comic/all/a/mv?domain=jm-comic3.art
/18comic/all/a/mv?domain=jm-comic.club
/18comic/all/a/mv?domain=jm-comic2.ark
/18comic/all/a/mv?domain=18comic.org
/18comic/all/a/mv?domain=18comic.vip
```
> feat(route): 18comic add category to description

- lib/routes/docschina/weekly.ts
Close #
```routes
NOROUTE
```
fixed markdown table indentation in the document
修正文档中表格缩进
> fix(route/docschina): markdown table in doc

- lib/routes/github/file.ts
(none)
```routes
/github/file/DIYgod/RSSHub/master/README.md
```
fixed the missing params in new format
> fix(route): complete GitHub file params

- lib/routes/junhe/legal-updates.ts
- lib/routes/junhe/namespace.ts
Close #14880
```routes
/junhe/legal-updates
```
> feat(route): add 君合律师事务所君合法评

- lib/routes/ntdm/video.ts
Close #
```routes
/ntdm/video/4309
```
update right example id for documentation
> docs(route): /ntdm/video, update right example id

- lib/routes/twreporter/category.ts
- lib/routes/twreporter/fetch-article.ts
- lib/routes/twreporter/newest.ts
- lib/routes/twreporter/templates/image.art
- lib/routes/twreporter/templates/youtube.art
Close #
```routes
/twreporter/category/world
/twreporter/newest
```
> feat(route): migrate to v2 api (twreporter)

- lib/routes/gov/mot/index.ts
Close #14995 
```routes
/gov/mot/tongjishuju/tielu
/gov/mot/tongjishuju/youzheng
/gov/mot/fenxigongbao/yunlifenxi
```
> fix(route): 中华人民共和国交通运输部

- lib/routes/zhihu/daily.ts
Close #
```routes
/zhihu/daily
```
> fix(route): 修复 知乎日报路由

- lib/routes/gamer/gnn-index.ts
Close #13792 
```routes
/gamer/gnn/1
```
> fix(route): 巴哈姆特電玩資訊站-GNN 新聞

- lib/routes/modrinth/versions.ts
Close #
```routes
/modrinth/project/profundis/versions
```
> fix(modrinth): name could be null

- lib/routes/1lou/index.ts
- lib/routes/1lou/namespace.ts
Close #14985
```routes
/1lou/forum-2-1?tagids=0_97_0_0
```
> fix(route): BT之家1LOU站

- lib/routes/modrinth/versions.ts
Close #
```routes
modrinth/project/simple-voice-chat/versions
```
> fix(modrinth): avoid duplicating author id

- lib/routes/booru/mmda.ts
Close #
```routes
/booru/mmda/tags
/booru/mmda/tags/full_body
/booru/mmda/tags/full_body%20blue_eyes
/booru/mmda/tags/user:hsjsekdjd
```
> fix(router): MMDArchive fix __dirname

- lib/routes/linovelib/volume.ts
```routes
/linovelib/volume/8
```
> fix(route): linovelib volume

- lib/routes/bilibili/dynamic.ts
Close #
```routes
/bilibili/user/dynamic/1340190821
/bilibili/user/dynamic/1065315233
```
> fix(route): 修复 bilibili 动态路由 部分情况下缺失 title 的问题

- lib/router.js
- lib/routes/yande/namespace.ts
- lib/routes/yande/post.ts
Close #
```routes
/yande/post/popular_recent
/yande/post/popular_recent/1d
/yande/post/popular_recent/1w
/yande/post/popular_recent/1m
/yande/post/popular_recent/1y
```
> feat(route): recover route yande.re

- lib/routes/bilibili/dynamic.ts
Close #
```routes
/bilibili/user/dynamic/1340190821
/bilibili/user/dynamic/1065315233
```
> fix(route): 修复 bilibili 动态路由 缺失 live_rcmd 类型的问题; 修复 title 问题

- lib/routes-deprecated/index.js
- lib/utils/git-hash.ts
- package.json
- pnpm-lock.yaml
Close #15040 
```routes
/wrongpath
```
All Git Hash in error messages are unknown because `git-rev-sync` is incompatible with ESM.
I replace it with Node.js native method and Git Hash can be shown now.
I haven't tested the one in route-deprecated because I don't know how to test it.
> fix(core): fix Git Hash unknown

- lib/routes/bilibili/dynamic.ts
Close #
```routes
/bilibili/user/dynamic/1340190821
/bilibili/user/dynamic/1065315233
```
> fix(route): 优化 bilibili 动态路由的 <br> 符号处理

- lib/routes/nmc/weatheralarm.ts
Close #
```routes
/nmc/weatheralarm
/nmc/weatheralarm/河北省
```
> fix(route): 修复 全国气象预警 为空的问题

- lib/routes/aqicn/aqi.ts
- lib/routes/aqicn/namespace.ts
Close #
```routes
/aqicn/beijing
/aqicn/beijing/pm25,pm10
/aqicn/4258
```
> feat(route): add aqicn.org

- lib/routes/163/dy.ts
- lib/routes/163/dy2.ts
- lib/routes/163/utils.ts
Close #15074
```routes
/163/dy2/T1519034263171
```
remove iconv module, use data from got directly instead of decoding data with content-type
> fix(route): /163/dy2/:id, 网易号

- lib/routes/idaily/index.ts
Close #15084 
```routes
/idaily
```
Reference: #14652
> fix(route): idaily

- lib/routes/github/comments.ts
Close #15048
```routes
/github/comments/DIYgod/RSSHub/14990
```
> fix(route): github comments

- lib/routes/sehuatang/index.ts
Close #15065
```routes
/sehuatang/103
```
`cookieJar` is broken due to #14922
> fix(route): sehuatang

- lib/routes/medium/graphql.ts
Close #
```routes
/medium/following/acring4ever
/medium/for-you/acring4ever
/medium/tag/acring4ever/creativity
```
> fix(route): 修复 medium 订阅失效的问题

- lib/routes/ustc/math.ts
Close #
```routes
/ustc/math/xyxw
/ustc/math/tzgg
/ustc/math/xsjl
/ustc/math/xsbg
```
> feat(route): 中国科学技术大学-数学科学学院

- lib/routes/luolei/index.ts
- lib/routes/luolei/namespace.ts
Close #15092
```routes
/luolei
```
> feat(route): add 罗磊的独立博客

- lib/routes/europechinese/latest.ts
- lib/routes/europechinese/namespace.ts
Close #
```routes
/europechinese/latest
```
> feat(route): support europechinese

- lib/routes/binance/launchpool.ts
- lib/routes/binance/namespace.ts
Close #
```routes
/binance/launchpool
```
> feat(route): 添加Binance数字货币及交易对上新公告RSS

- lib/routes/nosec/index.ts
Close #
```routes
/nosec/hole
```
修复使用ofetch之后的nosec路由
> fix(route): 修复使用ofetch之后的nosec路由

- lib/routes/jpxgmn/search.ts
- lib/routes/jpxgmn/tab.ts
- lib/routes/jpxgmn/weekly.ts
Close #
```routes
/jpxgmn/weekly
/jpxgmn/tab
/jpxgmn/tab/Xiuren
/jpxgmn/search/vicky
```
This route involves redirecting, and it is needed to get the real url from response, which current `got`
imitated using `ofetch` does not support.
> fix(route): jpxgmn

- lib/routes/bilibili/dynamic.ts
Similar as #9353, but also add avatars as icon and logo for Bilibili dynamic route
Close #
```routes
/bilibili/user/dynamic/1340190821
/bilibili/user/dynamic/1065315233
/bilibili/user/dynamic/1340190821?format=atom
/bilibili/user/dynamic/1065315233?format=atom
```
> feat(route): add icon and logo to Bilibili dynamic

- lib/routes/rsshub/routes.ts
- lib/types.ts
Close #
```routes
/rsshub/routes
```
> fix(route): rsshub new docs link

- lib/routes/line/publisher.ts
- lib/routes/line/today.ts
- lib/routes/line/utils.ts
Close #
```routes
/line/today/th/publisher/101048
```
> fix(route): line publisher

- lib/routes/apnews/topics.ts
> fix(route/apnews): Refine link selector.

- lib/routes/huanqiu/index.ts
Close #15107 
```routes
/huanqiu/news/china
```
> fix(route): huanqiu (#15107)

- lib/routes/youtube/charts.ts
- lib/routes/youtube/community.ts
- lib/routes/youtube/custom.ts
- lib/routes/youtube/subscriptions.ts
- lib/routes/youtube/utils.ts
Close #
```routes
/youtube/community/@weathernewsarchive
```
> fix(route): youtube utils

- lib/routes/xueqiu/user.ts
Close #15138
```routes
/xueqiu/user/8116633596
```
use `ofetch.raw()` to get `set-cookie` in response.headers
> fix(route): xueqiu user

- lib/routes/xianbao/index.ts
- lib/routes/xianbao/namespace.ts
Close #11217 
```routes
/xianbao/douban
```
> feat(route): add 线报酷

- lib/routes/atptour/namespace.ts
- lib/routes/atptour/news.ts
Close #
```routes
/atptour/news/en
/atptour/news/es
```
`got` will receive 403 so I use puppeteer.
> feat(route): add atptour

- lib/routes/zhonglun/index.ts
- lib/routes/zhonglun/namespace.ts
- lib/routes/zhonglun/templates/description.art
Close #14877
```routes
/zhonglun/research/article/zh
```
> feat(route): add 中伦律师事务所中伦研究专业文章

- lib/routes/xianbao/index.ts
Close #
```routes
/xianbao/douban
```
> fix(route): fix xianbao typo and parse

- lib/routes/buaa/sme.ts
Close #
```routes
/buaa/sme
```
北京航空航天大学集成电路科学与工程学院适配新版路由规范。
> feat: buaa/sme适配新版路由规范

- lib/routes/reuters/common.ts
Close #
```routes
/reuters/world?limit=100&sophi=true
/reuters/world/africa
/reuters/business
/reuters/legal
/reuters/authors/jonathan-landay
```
> fix(route/reuters): Replace `got` with `ofetch`.

- lib/routes/nikkei/news.ts
Close #15094
```routes
/nikkei/technology
/nikkei/economy
/nikkei/news
```
> fix(route): 日本経済新聞News

- lib/routes/modrinth/versions.ts
Close #
```routes
/modrinth/project/lithosphere/versions
```
> fix(modrinth): switch to ofetch since it's not suppor `got.json()`

- lib/routes/hitcon/namespace.ts
- lib/routes/hitcon/templates/zeroday.art
- lib/routes/hitcon/zeroday.ts
Close #14487 
```routes
/hitcon/zeroday/vulnerability
/hitcon/zeroday/vulnerability/all
/hitcon/zeroday/vulnerability/closed
/hitcon/zeroday/vulnerability/disclosed
/hitcon/zeroday/vulnerability/patching
```
> feat(route): hitcon

- lib/routes/seekingalpha/index.ts
- lib/routes/seekingalpha/templates/summary.art
Close #15147
```routes
/seekingalpha/TSM/news
/seekingalpha/TSM/analysis
/seekingalpha/TSM/press-releases
/seekingalpha/TSM/related-analysis
```
> fix(route): seekingalpha

- lib/routes/freewechat/profile.ts
Close #
```routes
/freewechat/profile/MzI5NTUxNzk3OA==
```
the `got` response is not contain the `url`, use `item.link` instead
> fix(route): freewechat

- lib/routes/picnob/user.ts
Close #
```routes
/picnob/user/xlisa_olivex
```
爬取数据的来源更改为'pixwox.com'，但实际上'pixwox'和'picnob'是同一个网站
> fix(route): picnob. Change source to 'pixwox.com'.

- lib/routes/radio/album.ts
- lib/routes/radio/zhibo.ts
Close #15060
```routes
/radio/album/15845111305020
/radio/zhibo/1395528
```
Use the new api endpoints for radio.cn in album, also fix the wrong audio type when playing the m4a file.
> fix(route): the radio.cn in zhibo and album rss

- lib/routes/wechat/tgchannel.ts
Close #
```routes
/wechat/tgchannel/darhcenssr/%E5%8C%97%E6%9E%81%E6%98%9F%E5%88%86%E5%B8%83%E5%BC%8F%E5%85%89%E4%BC%8F/1
```
This is a regression introduced in 9787a92c.
Use `||` instead of `??` to prevent empty string being used as the feed title.
> fix(routes/wechat/tgchannel): title is not mpName

- lib/routes/591/list.ts
- lib/routes/apple/apps.ts
- lib/routes/bsky/posts.ts
- lib/routes/cebbank/all.ts
- lib/routes/cebbank/history.ts
- lib/routes/cngal/entry.ts
- lib/routes/dahecube/index.ts
- lib/routes/eprice/rss.ts
- lib/routes/gamer/hot.ts
- lib/routes/github/comments.ts
- lib/routes/github/notifications.ts
- lib/routes/gitpod/blog.ts
- lib/routes/hkej/index.ts
- lib/routes/hket/index.ts
- lib/routes/macupdate/app.ts
- lib/routes/nature/siteindex.ts
- lib/routes/nintendo/eshop-us.ts
- lib/routes/otobanana/cast.ts
- lib/routes/otobanana/livestream.ts
- lib/routes/otobanana/timeline.ts
- lib/routes/qbittorrent/news.ts
- lib/routes/taptap/review.ts
- lib/routes/taptap/topic.ts
- lib/routes/threads/utils.ts
- lib/routes/timednews/news.ts
- lib/routes/wechat/feeddd.ts
- lib/routes/youtube/subscriptions.ts
#14745
This is a regression introduced in #14718.
```routes
NOROUTE
```
> chore(routes/*): fix unreachable code

- lib/routes/dcfever/news.ts
- lib/routes/dcfever/reviews.ts
- lib/routes/dcfever/trading-search.ts
- lib/routes/dcfever/trading.ts
- lib/routes/dcfever/utils.ts
Close #
```routes
/dcfever/news
```
> fix(route): dcfever use ofetch instead of got utils

- lib/routes/esquirehk/namespace.ts
- lib/routes/esquirehk/tag.ts
- lib/routes/esquirehk/templates/subpages.art
Close #
```routes
/esquirehk/tag/Fashion
```
> feat(route): recover esquirehk

- lib/routes/xjtu/dean.ts
Close #
```routes
/xjtu/dean/jxxx/jxtz2
/xjtu/dean/jxxx/jxtz2/zhtz
/xjtu/dean/jxxx/jxdt
```
网页结构发生变化，修复下
route 较多且经常变化，仅放了几个示例
> fix(route): 西安交通大学 教务处

- lib/routes/deepin/homepage.ts
- lib/routes/deepin/namespace.ts
Close #
```routes
/deepin/homepage/78326
```
> feat: add deepin bss homepage

- lib/routes/luolei/index.ts
- lib/routes/luolei/templates/description.art
Close #15196
```routes
/luolei
```
> fix(route): 罗磊的独立博客显示原图

- lib/routes/baozimh/index.ts
Close #15220 
```routes
/baozimh/comic/jiazhongdeshouernupu-sawayakajiaoji
```
修改了 CSS 选择器，原先获取的是“章节目录”，现在获取的是“最新章节”
> fix(route): 包子漫画按最新章节获取内容

- lib/routes/njuferret/blog.ts
- lib/routes/njuferret/namespace.ts
Close #
```routes
/njuferret/blog
```
> feat(route): Add route for njuferret.github.io

- lib/routes/xueqiu/user-stock.ts
Close #
```routes
/xueqiu/user_stock/3607985463
```
1. use `ofetch.raw()` to get set-cookie in response.headers
2. use `ofetch` to get other responses
> fix(route): xueqiu user-stock

- lib/routes/papers/index.ts
- lib/routes/papers/namespace.ts
Close #15178
```routes
/papers/arxiv/cs.AI
```
> fix(route): Cool Papers

- lib/routes/hoyolab/news.ts
Close #
```routes
/hoyolab/news/zh-cn/2/2
/hoyolab/news/zh-cn/8/3
```
> fix(router): hoyolab news

- lib/routes/mixcloud/index.ts
- lib/routes/mixcloud/queries.ts
Close #15235
```routes
/mixcloud/dholbach
/mixcloud/dholbach/uploads
/mixcloud/dholbach/favorites
/mixcloud/dholbach/listens
/mixcloud/FirstEar/stream
/mixcloud/FirstEar/reposts
```
update graphql queries, fix radar, add sub route `reposts`
> fix(route): update mixcloud

- lib/routes/nju/jw.ts
Close #
```routes
/nju/jw/ggtz
/nju/jw/jxdt
```
Using `'application/x-www-form-urlencoded'` instead of default `'multipart/form-data'` as `Content-Type` since the server no longer accepts the latter.
> fix(route): 南京大学 本科生院教务

- lib/routes/zhihu/activities.ts
Close #15231
```routes
/zhihu/people/activities/laoduo6666
```
> fix(route): zhihu/activities

- lib/routes/mihoyo/bbs/official.ts
- lib/routes/mihoyo/templates/official.art
Close #
```routes
/mihoyo/bbs/official/2/3/20
/mihoyo/bbs/official/8/3
```
1. get full text post rather than abstracts.
2. add post hashtags as rss.item.category.
3. Set appropriate link.
> feat(route/mihoyo): enhance miyoushe official post

- lib/routes/bbc/index.ts
Close #15217
```routes
/bbc
```
> fix: BBC URL pathname check

- lib/routes/accessbriefing/index.ts
- lib/routes/accessbriefing/namespace.ts
- lib/routes/accessbriefing/templates/description.art
Close #15221
```routes
/accessbriefing/latest/news
```
> feat(route): add Access Briefing

- lib/routes/bing/daily-wallpaper.ts
> fix(route/bing): Replace `got`

- lib/middleware/template.tsx
Close #14940, Close #14943, Close #15262
```routes
/coolapk/tuwen
/juejin/trending/all/monthly
/ndss-symposium/ndss
```
https://github.com/DIYgod/RSSHub/blob/e0ccbb65e86a8b29344b3ec96f990e1f3b868f1e/lib/middleware/utf8.js#L1-L6 is removed accidentally during Koa -> Hono framework changes
> fix(core): remove unicode control characters in item description

- lib/config.ts
- lib/routes/qingting/podcast.ts
Close #15229
```routes
/qingting/podcast/293411
```
> fix(route): qingting

- lib/routes/0x80/index.ts
- lib/routes/0x80/namespace.ts
Close #
```routes
/0x80/blog
```
> feat(route): 0x80.pl

- lib/middleware/template.tsx
- lib/utils/render.ts
- lib/views/rss3.ts
Close #
```routes
NOROUTE
```
UMS has been renamed to RSS3 Protocol <https://github.com/RSS3-Network/REPs/blob/main/REPs/REP-11.md>
> feat: support .rss3 output type

- lib/routes/dehenglaw/index.ts
- lib/routes/dehenglaw/namespace.ts
- lib/routes/dehenglaw/templates/description.art
Close #14876
```routes
/dehenglaw/CN/paper
```
> feat(route): add 德恒律师事务所德恒探索

- lib/routes/sara/index.ts
- lib/routes/sara/namespace.ts
Close #
```routes
/sara/dynamic
/sara/announcement
/sara/industry
```
> feat(route): Add 上海业余无线电协会

- lib/config.ts
- lib/routes/twitter/api/mobile-api/login.ts
- lib/routes/twitter/namespace.ts
- lib/routes/twitter/user.ts
> feat(route): twitter add back 2fa

- lib/routes/cpcaauto/index.ts
- lib/routes/cpcaauto/namespace.ts
Close #15274
```routes
/cpcaauto/news
```
> feat(route): add 中国汽车流通协会汽车市场研究分会

- lib/routes/lofter/tag.ts
- lib/routes/lofter/user.ts
Close #15227
```routes
/lofter/tag/neuro
/lofter/tag/neuro/new
/lofter/tag/neuro/week
/lofter/user/nekomataneko
```
Thanks for suggestion from https://github.com/DIYgod/RSSHub/issues/15227#issuecomment-2065769187
> fix(route): broken lofter route

- lib/routes/byau/namespace.ts
- lib/routes/byau/xinwen/index.ts
Close #14824
```routes
/byau/news/3674
/byau/news/3676
```
> feat(route)：增加黑龙江八一农垦大学新闻网 RSS (#14824)

- lib/config.ts
- lib/routes/zsxq/group.ts
- lib/routes/zsxq/namespace.ts
- lib/routes/zsxq/types.ts
- lib/routes/zsxq/user.ts
- lib/routes/zsxq/utils.ts
Close #5751 
```routes
/zsxq/group/88855458825252
/zsxq/user/2414218251
```
demo see [private rsshub](http://18.181.146.236:1200/zsxq/group/88855458825252)
> feat(route): 知识星球

- lib/routes/gxmzu/ai.ts
- lib/routes/gxmzu/lib.ts
- lib/routes/gxmzu/utils/index.ts
- lib/routes/gxmzu/yjs.ts
- lib/routes/jou/utils/index.ts
- lib/routes/njxzc/utils/index.ts
Close #
```routes
/gxmzu/aitzgg
/gxmzu/libzxxx
/gxmzu/yjszsgg
/njxzc/tzgg
/njxzc/libtzgg
/jou/tzgg
/jou/yztzgg
```
1. lib/routes/gxmzu/ai.ts: 
- 修改了每则消息的content的id。【该id为更高层次的id，以便获取附件等信息】
2. lib/routes/gxmzu/utils/index.ts: 
- 对response.redirectUrls的存在进行条件判断，提高了处理URL的鲁棒性。
- 对每则消息content部分的html中a标签的href属性进行url处理，将相对URL转换为绝对URL。
3. lib/routes/gxmzu/yjs.ts:
- 修改了每则消息的content的id。【该id为更高层次的id，以便获取附件等信息】
1. lib/routes/njxzc/utils/index.ts:
- 对response.redirectUrls的存在进行条件判断，提高了处理URL的鲁棒性。
- 增加处理基于IP的访问限制逻辑。
- 删除 replaceAll 以改进内容中相对 URL 的管理方式，确保更可靠、更安全的 URL 处理。
1. lib/routes/jou/utils/index.ts:
- 对response.redirectUrls的存在进行条件判断，提高了处理URL的鲁棒性。
- 删除 replaceAll 以改进内容中相对 URL 的管理方式，确保更可靠、更安全的 URL 处理。
> feat: fix gxmzu rss support && fix njxzc rss support && fix jou rss support

- lib/routes/u3c3/index.ts
- lib/routes/u3c3/namespace.ts
- lib/routes/u9a9/index.ts
- lib/routes/u9a9/namespace.ts
Close #
```routes
NOROUTE
```
现状是u3c3 的namespace 变成了u9a9，u9a9 的namespace 没有指定
> fix(route): namespace issue

- lib/routes/tencent/news/author.ts
Close #
```routes
/tencent/news/author/5069188
```
> fix(route/tencent): Adapt to video pages.

- lib/routes/bnu/mba.ts
Close #15329
```routes
/bnu/mba/mbaxljz
```
> feat(route): add 北京师范大学经济与工商管理学院MBA

- lib/routes/colamanga/manga.ts
- lib/routes/colamanga/namespace.ts
Close #11692
```routes
/colamanga/manga-qq978758
```
漫画网站，反扒策略应该只是检测是否有js环境
> feat(route): add colamanga

- lib/routes/gov/pbc/namespace.ts
Close #15331
```routes
/gov/pbc/goutongjiaoliu
```
> fix(route): 中国人民银行

- lib/routes/ecnu/jwc.ts
- lib/routes/ecnu/namespace.ts
Close #
```routes
/ecnu/jwc
```
Because the official website does not support HTTPS, the data is transmitted via HTTP./因为官网不支持HTTPS，所以以HTTP传输数据
> feat(route): add jwc notice

- lib/routes/ieee-security/sp.ts
- lib/routes/sigsac/ccs.ts
- lib/routes/usenix/usenix.ts
Close #15312, close #14940
```routes
/usenix/usenix-security-sympoium
```
> fix(route): usenix

- lib/routes/caixin/weekly.ts
Close #14730
```routes
/caixin/weekly
```
> fix(route): caixin weekly

- lib/routes/lianxh/index.ts
- lib/routes/lianxh/namespace.ts
Close #14649
```routes
/lianxh
```
restore #11067 from f1a9223aacab29bae49c1d5d5b502c8ca1a25617
> feat(route): add back lianxh

- lib/routes/iehou/index.ts
- lib/routes/iehou/namespace.ts
Close #15291
```routes
/iehou
```
> feat(route): add 网猴线报

- lib/routes/stbu/jsjxy.ts
- lib/routes/stbu/xyxw.ts
Close #
```routes
/stbu/jsjxy
/stbu/xyxw
```
**Fixed** `Unknown` title of doc in route `/stbu/syxw`
**Fixed** Original site missing SSL certificate
> fix(route): 四川工商学院 - 学院新闻

- lib/routes/ollama/models.ts
- lib/routes/ollama/namespace.ts
Close #
```routes
/ollama/library
```
> feat(route): add ollama models

- lib/routes/sjtu/yzb/zkxx.ts
Close #
```routes
/sjtu/yzb/zkxx/sszs
```
> fix(route/sjtu/yzb): Correct title and date.

- lib/routes/hellogithub/index.ts
- lib/routes/hellogithub/report.ts
- lib/routes/hellogithub/volume.ts
- lib/routes/nmc/weatheralarm.ts
- lib/utils/readable-social.ts
Close #
```routes
/hellogithub/volume
/hellogithub/month
/hellogithub/ranking
/hellogithub/report
/hellogithub/article
```
> fix(route): 修复 hellogithub 路由错误

- lib/routes/sohu/mp.ts
Close #13640
```routes
/sohu/mp/MWJmNTdjZjYtMTRiMi00NWI2LWE2ZDMtY2I1NmRhNTNmNDQ0
/sohu/mp/119097
/sohu/mp/c29odXptdGhnbjZ3NEBzb2h1LmNvbQ==
```
> fix(route): sohu mp

- lib/routes/weibo/keyword.ts
Close #15396
```routes
/weibo/keyword/samsung
```
> fix(route): weibo

- lib/routes/daily/discussed.ts
- lib/routes/daily/index.ts
- lib/routes/daily/namespace.ts
- lib/routes/daily/templates/posts.art
- lib/routes/daily/upvoted.ts
- lib/routes/daily/user.ts
- lib/routes/daily/utils.ts
Close #
```routes
/daily/user/kramer
```
> feat(route): daily.dev user

- lib/routes/crossbell/feeds/following.ts
- lib/routes/crossbell/notes/character.ts
- lib/routes/crossbell/notes/utils.ts
Close #
```routes
/crossbell/feeds/following/10
/crossbell/notes/character/10
```
Previously, `undefined` would be parsed because `UPDATE_CHARACTER_METADATA`
Reactivate and serve new RSS `<item>`
> fix(route): fix crossbell character and the following output

- lib/routes/copernicium/index.ts
- lib/routes/copernicium/namespace.ts
Close #
```routes
/copernicium/环球视角
/copernicium/人文叙述
/copernicium/观点评论
```
> feat(route): Copernicium

- lib/routes/ttv/index.ts
- lib/routes/ttv/namespace.ts
Close #
```routes
/ttv
/ttv/realtime
/ttv/%E6%94%BF%E6%B2%BB
/ttv/%E9%AB%94%E8%82%B2
```
> feat(route): Create ttv

- lib/routes/yenpress/namespace.ts
- lib/routes/yenpress/series.ts
- lib/routes/yenpress/templates/series.art
Close #14581
```routes
/yenpress/series/alya-sometimes-hides-her-feelings-in-russian
```
> feat(route): yenpress

- lib/routes/copernicium/index.ts
Close #
```routes
/copernicium/专题报道
```
> fix(route/copernicium): Add category

- lib/routes/hackernews/index.ts
Close #
```routes
/hackernews
/hackernews/index/sources
```
> fix(radar): fix source for HackerNews

- lib/routes/linkedin/jobs.ts
- lib/routes/linkedin/namespace.ts
- lib/routes/linkedin/utils.ts
Close #
```routes
/linkedin/jobs/F/4
/linkedin/jobs/F/4/software%20engineer
/linkedin/jobs/F/4/software%20engineer/f_WT=2&geoId=91000003&f_TPR=r2592000
```
增加新的参数 `work_types, geo_id, time_posted_range`，使LinkedIn订阅更可用  
参数含义参考
https://github.com/marcothedeveloper123/jobseeker  
https://www.kaggle.com/code/hachemsfar/linkedin-jobs-scraper-job-description
```
Past_month="f_TPR=r2592000"
Past_week="f_TPR=r604800"
Past_24_hours="f_TPR=r86400"
onsite="f_WT=1"
remote="f_WT=2"
hybrid="f_WT=3"
```
> feat(route): add new LinkedIn route params

- lib/routes/xueqiu/cookies.ts
- lib/routes/xueqiu/favorite.ts
- lib/routes/xueqiu/hots.ts
- lib/routes/xueqiu/stock-info.ts
- lib/routes/xueqiu/today.ts
- lib/routes/xueqiu/user.ts
Close #15360
```routes
/xueqiu/hots
/xueqiu/today
/xueqiu/stock_info/NVDA
/xueqiu/favorite/8152922548
/xueqiu/user/8152922548
```
修复雪球获取token失效。
Fixed the issue of obtaining XueQiu token.
> fix(route/xueqiu): get token from cookies

- lib/routes/linkedin/utils.ts
Close #
```routes
/linkedin/jobs/F/3-4-5/("backend"%20OR%20"back-end"%20OR%20"golang"%20OR%20"python")/f_TPR=r604800&geoId=102772228
```
Prevent  `TypeError: Cannot read properties of undefined (reading 'split')`  due to missing job link classes
> fix(route/linkedin): handle missing elements in jobs parsing

- lib/routes/techcrunch/news.ts
Close #
```routes
/techcrunch/news
```
not a new route. just add some cleanup rules for better reading experience.
> chore: cleanup useless nav element

- lib/routes/ithome/templates/description.art
- lib/routes/ithome/zt.ts
Close #
```routes
/ithome/zt/xijiayi
```
> fix(route): IT之家专题

- lib/routes/theinitium/author.ts
- lib/routes/theinitium/channel.ts
- lib/routes/theinitium/follow.ts
- lib/routes/theinitium/full.ts
- lib/routes/theinitium/tags.ts
- lib/routes/theinitium/utils.ts
```routes
/theinitium/channel/latest
```
- Fix metadata.
- When the token expires, delete it in cache so RSSHub can re-login in the next request.
> fix(route/theinitium): Fix metadata & token expiration

- lib/routes/github/pulls.ts
Close #15451
```routes
/github/pull/DIYgod/RSSHub
```
> fix(route): github pulls

- lib/routes/apnews/rss.ts
- lib/routes/apnews/topics.ts
- lib/routes/apnews/utils.ts
Close #
```routes
/apnews/rss/
/apnews/rss/business
```
> feat(route/apnews): Support rss parsing.

- lib/routes/gq/namespace.ts
- lib/routes/gq/news.ts
Close #
```routes
/gq/news
```
> feat(route): gq

- lib/routes/newyorker/namespace.ts
- lib/routes/newyorker/news.ts
Close #
```routes
/newyorker/cartoons/daily-cartoon
/newyorker/everything
```
> feat(route): New Yorker

- lib/routes/newyorker/news.ts
Close #
```routes
/newyorker/everything
```
just cleanup
> chore(route/newyorker): cleanup author info

- lib/routes/69shu/article.ts
- lib/routes/69shu/namespace.ts
Close #
```routes
/69shu/article/47117
```
> feat(route): 69shu

- lib/routes/keylol/index.ts
无
```routes
/keylol/f161-1
/keylol/fid=234&typeid=875
```
试用现存路由时，发现每个项目第一张图都是广告，动手弄走把它，顺便加强了项目的读取
- 移除广告
- 找回原作者的使用教学
- 以作者名字取代编号 (如有)
- 支持显示包含目录帖文的全部内容，常用于特卖帖 (如示例中的 [`SEGA & D3PUBLISHER 春季特卖`](https://keylol.com/t939892-1-1))
另外 radar target function 写法是已弃用还是 bug 了?
现在好像都会变成 string
> feat(route/keylol): Update keylol

- lib/routes/digitalcameraworld/namespace.ts
- lib/routes/digitalcameraworld/news.ts
Close #
```routes
/digitalcameraworld/news
```
> feat(route): digitalcameraworld

- lib/routes/deepin/homepage.ts
Close #
```routes
/deepin/homepage/184827
```
Radar data for /deepin/homepage/184827 not wrapped with array.
> fix(route): Change radar response for /deepin/homepage/:user_id

- lib/routes/lrepacks/index.ts
- lib/routes/lrepacks/namespace.ts
- lib/routes/lrepacks/templates/description.art
Close #15472
```routes
/lrepacks
/lrepacks/repaki-sistemnyh-programm
```
> feat(route): add REPACK скачать

- lib/routes/bangumi/tv/other/followrank.ts
Close #
```routes
/bangumi/tv/followrank
/bangumi/anime/followrank
/bangumi/book/followrank
/bangumi/music/followrank
/bangumi/game/followrank
/bangumi/real/followrank
```
> feat(route/bangumi): support follow ranks for book/music/real pages

- lib/routes/economist/espresso.ts
```routes
/economist/espresso
```
Current route is crashing when paywalled content is returned. This filters out those articles.
> fix(route): economist espresso

- lib/routes/bilibili/api-interface.d.ts
- lib/routes/bilibili/dynamic.ts
Close #
```routes
/bilibili/user/dynamic/159370257
/bilibili/user/dynamic/159370257/showEmoji=1
```
> fix(route): 优化 bilibili 动态 转发带图评论时的图片显示

- lib/routes/bbc/index.ts
Close #
```routes
/bbc
```
The current `Section` in the title is mostly incorrect. It is no longer feasible to add a `[Section]` in the title as there are so many different link formats to keep up with.
> fix: incorrect section in title

- lib/routes/ncc-cma/cmdp.ts
- lib/routes/ncc-cma/namespace.ts
Close #
```routes
/ncc-cma/cmdp/image/RPJQWQYZ
```
> fix(route): 国家气候中心最新监测

- .devcontainer/devcontainer.json
- update base image to 22 to fit node version check
- install jre to sonarlint
- fix pnpm ENOENT: `no such file or directory` error
Close #
```routes
```
> fix(dev): can not start devcontainer

- lib/routes/apnews/rss.ts
Close #
```routes
/apnews/rss
```
> fix(route/apnews): typo in code

- lib/routes/sketis/isabelle-dev/blog/index.ts
- lib/routes/sketis/namespace.ts
```routes
/sketis/isabelle-dev/blog/1
/sketis/isabelle-dev/blog/2
```
> feat(route): Isabelle dev blog

- lib/routes/tsinghua/lib/zydt.ts
- lib/routes/tsinghua/namespace.ts
Close #15524
```routes
/tsinghua/lib/zydt
/tsinghua/lib/zydt/yg
```
> feat(route): add 清华大学图书馆资源动态

- lib/routes/telegram/channel.ts
Close #15519
```routes
/telegram/channel/NewlearnerChannel/showHashtagAsHyperlink=0
```
> feat(route/telegram/channel): allow trimming hyperlinks from hashtags

- lib/middleware/template.tsx
Close #
```routes
NOROUTE
```
`cacheModule.status.available` is true for memory but not yet for `redis` when initialising.
<details><summary>Screenshot</summary>
</details>
> fix(template): redis-backed instances always show ttl 1

- lib/routes/zju/cst/index.ts
Close #
```routes
/zju/cst/0
```
> fix(route): `/zju/cst`

- lib/routes/apnews/utils.ts
Close #
```routes
/apnews/rss
```
> feat(route/apnews): Extract data from ldjson.

- lib/routes/bilibili/followings-dynamic.ts
Close #
```routes
/bilibili/followings/dynamic/1
```
目前 bilibili 用户关注动态 会出现 4100000 错误，暂时没找到解决方案，故先增加错误提示
> fix(route): bilibili 路由增加 4100000 提示

- lib/routes/cuilingmag/index.ts
- lib/routes/cuilingmag/namespace.ts
- lib/routes/cuilingmag/templates/description.art
Close #15548
```routes
/cuilingmag
```
> feat(route): add 萃嶺网

- lib/routes/mihoyo/bbs/official.ts
Close #15558
```routes
/mihoyo/bbs/official/6/1
```
> fix(route/mihoyo/bbs/official): non-unique guid

- lib/routes/apple/apps.ts
Close #
```routes
/apple/apps
```
Typo
> fix(apple/apps): typo

- lib/routes/423down/index.ts
- lib/routes/423down/namespace.ts
- lib/routes/423down/templates/description.art
Close #
```routes
/423down
```
> fix(route): 423Down

- lib/config.ts
- lib/routes/yamibo/bbs/forum.ts
- lib/routes/yamibo/bbs/thread.ts
- lib/routes/yamibo/namespace.ts
- lib/routes/yamibo/utils.ts
Close #
```routes
/yamibo/bbs/forum/5/404
/yamibo/bbs/thread/541914
```
> feat(route): yamibo

- lib/routes/typst/namespace.ts
- lib/routes/typst/universe.ts
> feat(route): add route for Typst universe

- lib/routes/typst/universe.ts
> fix(route): date parsing in Typst universe

- lib/routes/whu/rsgis.ts
```routes
/whu/rsgis/index
/whu/rsgis/xyxw/all
/whu/rsgis/xyxw/xyyw
/whu/rsgis/xyxw/hzjl
/whu/rsgis/xyxw/mtjj
/whu/rsgis/xyxw/xgyw
/whu/rsgis/kxyj/all
/whu/rsgis/kxyj/xsbg
/whu/rsgis/kxyj/xsjl
/whu/rsgis/kxyj/kycg
/whu/rsgis/kxyj/sbxx
/whu/rsgis/tzgg/all
/whu/rsgis/tzgg/xytz
/whu/rsgis/tzgg/jxdt
/whu/rsgis/tzgg/xsdt
/whu/rsgis/tzgg/rcyj
```
> feat(route): add WHU-RSGIS news / 武汉大学遥感信息工程学院

- lib/routes/wechat/ershcimi.ts
Close #15474, Close #15563
```routes
/wechat/ershicimi/aj6L4DN3
/wechat/ershicimi/YQXJ9lOz
```
只是在 ershicimi 路由中添加了 try-catch 用于避免因出现错误而无法使用的情况，之后可能还需要改 utils/wechat-mp
> fix(route): `/wechat/ershicimi`

- lib/routes/pixiv/bookmarks.ts
- lib/routes/pixiv/search.ts
Close #
```routes
/pixiv/search/Nezuko/popular/2
/pixiv/user/bookmarks/15288095
```
> fix(route): 优化 pixiv 搜索/书签 路由的简介

- lib/routes/epicgames/index.ts
Close #15569
```routes
/epicgames/freegames
```
> fix(route): Epic Games Store -  Resolve issue #15569

- lib/routes/guangdiu/search.ts
Close #
```routes
/guangdiu/search
```
the query should be q=, not k=.
> fix(route): guangdiu

- lib/routes/qq/cfhd/index.ts
- lib/routes/qq/namespace.ts
Close #15590
```routes
/qq/cfhd/news
```
> feat(route): add 穿越火线CFHD专区资讯中心

- lib/routes/81/81rc/index.ts
- lib/routes/81/namespace.ts
Close #
```routes
/81/81rc/sy/gzdt_210283
```
> fix(route): 中国人民解放军专业技术人才网

- lib/routes/zhihu/activities.ts
- lib/routes/zhihu/answers.ts
- lib/routes/zhihu/collection.ts
- lib/routes/zhihu/daily-section.ts
- lib/routes/zhihu/daily.ts
- lib/routes/zhihu/hotlist.ts
- lib/routes/zhihu/posts.ts
- lib/routes/zhihu/question.ts
- lib/routes/zhihu/timeline.ts
- lib/routes/zhihu/topic.ts
- lib/routes/zhihu/utils.ts
- lib/routes/zhihu/zhuanlan.ts
Close #15566
```routes
/zhihu/posts/people/liustein
```
> fix(route): zhihu posts

- lib/routes/theblockbeats/index.ts
- lib/routes/theblockbeats/namespace.ts
- lib/routes/theblockbeats/templates/description.art
Close #15344
```routes
/theblockbeats/article
```
> fix(route): theblockbeats

- lib/routes/swpu/bgw.ts
- lib/routes/swpu/dean.ts
- lib/routes/swpu/dxy.ts
- lib/routes/swpu/scs.ts
Close #
```routes
/swpu/bgw/zytzgg
/swpu/bgw/bmtzgg
/swpu/bgw/bzhd
/swpu/dean/tzgg
/swpu/dean/xwbd
/swpu/dean/sdsy
/swpu/dxy/1156
/swpu/dxy/1122
/swpu/scs/tzgg
/swpu/scs/xwsd
```
更新源数据地址（办公网）；
更新学院名称（计算机科学学院 -> 计算机与软件学院）；
在缓存中保存解析结果，而非`cheerio`对象，避免下次从缓存获取数据时报错；
添加 TS 类型标识；
> fix(route): 西南石油大学 办公网、教务处、计算机与软件学院、电气信息学院

- lib/routes/zhihu/activities.ts
- lib/routes/zhihu/xhu/activities.ts
- lib/routes/zhihu/xhu/answers.ts
- lib/routes/zhihu/xhu/collection.ts
- lib/routes/zhihu/xhu/posts.ts
- lib/routes/zhihu/xhu/question.ts
- lib/routes/zhihu/xhu/topic.ts
Close #15622 
```routes
/zhihu/xhu/people/activities/246e6cf44e94cefbf4b959cb5042bc91
```
> fix(route): fix utils for /zhihu/xhu

- lib/routes/xiaoheihe/news.ts
Close #
```routes
/xiaoheihe/news
```
Fix xiaoheihe news
> fix(route): Fix xiaoheihe news

- lib/routes/worldofwarships/devblog.ts
- lib/routes/worldofwarships/namespace.ts
Close #
```routes
/worldofwarships/devblog
```
This route is used for getting development blog of the game *World of Warships* from the [official website](https://blog.worldofwarships.com/).
本路由用于从游戏 *战舰世界* 的[官方页面](https://blog.worldofwarships.com/)获取该游戏的开发者日志。
> feat(route): add route for dev blog of World of Warships

- lib/routes/finology/bullets.ts
- lib/routes/finology/category.ts
- lib/routes/finology/most-viewed.ts
- lib/routes/finology/tag.ts
- lib/routes/finology/utils.ts
Close #15629
```routes
/finology/success-stories
```
> fix(route): finology

- lib/routes/xueqiu/user-stock.ts
Close #
```routes
/xueqiu/user_stock/1247347556
```
> fix(route): xueqiu user_stock 雪球用户自选动态修改为使用登录后的cookie值，并限制自建使用

- lib/routes/chinaisa/index.ts
Close #15609
```routes
/chinaisa/e5070694f299a43b20d990e53b6a69dc02e755fef644ae667cf75deaff80407a
```
> fix(route): chinaisa

- lib/routes/github/notifications.ts
Close #15657 
```routes
/github/notifications
```
> fix(route): github notification

- lib/routes/alipan/files.ts
- lib/routes/alipan/namespace.ts
- lib/routes/alipan/types.ts
Close #14899
```routes
/alipan/files/jjtKEgXJAtC/64a957744876479ab17941b29d1289c6ebdd71ef
```
https://github.com/DIYgod/RSSHub/commits/master/lib/v2/aliyundrive
> feat(route): add back alipan

- lib/routes/domp4/detail.ts
- lib/routes/domp4/latest-movie-bt.ts
```routes
/domp4/latest_movie_bt
```
> feat: add route /domp4/latest_movie_bt 订阅最新电影bt

- lib/routes/pwc/sustainability.ts
Close #
```routes
/pwc/strategyand/sustainability
```
> fix(route): pwc ditch puppeteer

- lib/routes/jiuyangongshe/community.ts
- lib/routes/jiuyangongshe/namespace.ts
- lib/routes/jiuyangongshe/templates/community-description.art
Close #15607
```routes
/jiuyangongshe/community
```
> feat(route): jiuyangongshe

- lib/routes/nikkei/asia/index.ts
- lib/routes/nikkei/cn/index.ts
- lib/routes/nikkei/index.ts
- lib/routes/nikkei/namespace.ts
- lib/routes/nikkei/news.ts
Close #14748, Close #15191 
```routes
/nikkei/cn/rss
```
> fix(route): nikkei route paths

- lib/routes/javdb/index.ts
- lib/routes/javdb/utils.ts
Close #15663, Close #9332 
```routes
/javdb/series/aqWg
```
> fix(route): javdb

- lib/routes/69shu/article.ts
- lib/routes/69shu/namespace.ts
Close #
```routes
/69shu/article/47117
```
update new url
> fix(route): update 69shu url

- lib/routes/zhihu/utils.ts
> fix(route): zhihu `__zse_ck`

- lib/routes/typst/universe.ts
Close #
```routes
/typst/universe
```
CHANGELOG:
- Duplicated packages are removed in the data
- Image links are correct now, as shown on package pages.
> fix(route): Typst universe route removes duplicated packages and fix description

- lib/routes/newrank/utils.ts
Close #14645
```routes
/newrank/wechat/chijiread
```
该报错是因为 flatten 方法实现有问题，下方示例代码可复现
```js
// master 分支方法
const old_flatten = (arr) => arr.reduce((acc, val) => [...acc, ...(Array.isArray(val) ? old_flatten(val) : val)], []);
// 修复分支方法
const new_flatten = (arr) => arr.reduce((acc, val) => Array.isArray(val) ? [...acc, ...(new_flatten(val))] : [...acc, val], []);
var foo = [[{a: 1}]];
console.log('new_flatten', new_flatten(foo));
// 输出：[{a: 1}]
console.log('old_flatten', old_flatten(foo));
// 报错：Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value) is not iterable```
> fix(route): fix flatten function to work properly

- lib/routes/jingzhengu/namespace.ts
- lib/routes/jingzhengu/news.ts
- lib/routes/jingzhengu/types.ts
- lib/routes/jingzhengu/utils.ts
Close #15300
```routes
/jingzhengu/news
```
> feat(route): jingzhengu

- lib/errors/index.test.ts
- lib/middleware/cache.ts
- lib/routes/test/index.ts
> feat: retry requesting control

- lib/routes/ximalaya/album.ts
- lib/routes/ximalaya/types.ts
- lib/routes/ximalaya/utils.ts
Close #
```routes
/ximalaya/album/80989111/0/shownote
```
使用Web版本接口获取付费音频节目的地址，例如`/ximalaya/album/80989111/0/shownote`等播客，使用token后可以正确获取到enclosure url。
> fix(ximalaya): parse pay audio address

- lib/routes/vice/namespace.ts
- lib/routes/vice/templates/article.art
- lib/routes/vice/topic.ts
Close #15694
```routes
/vice/topic/politics/en
/vice/topic/politics
/vice/topic/internet
```
New route for vice.com (seriously messed up the last PR)
> feat: adds vice.com route #15694

- lib/routes/kadokawa/blog.ts
- lib/routes/kadokawa/namespace.ts
- lib/routes/kadokawa/templates/description.art
Close #15712
```routes
/kadokawa/blog
```
> feat(route): add 台灣角川角編新聞台

- lib/routes/stream-capital/namespace.ts
- lib/routes/stream-capital/search.ts
- lib/routes/stream-capital/types.ts
- lib/routes/stream-capital/utils.ts
Close #15426
```routes
/stream-capital/search
```
> feat(route): stream-capital

- lib/routes/apnews/topics.ts
Close #
```routes
/apnews/topics/ap-top-news 
```
> fix(route/apnews): Ensure the link can be fetched.

- lib/routes/apnews/utils.ts
Close #
```routes
/apnews/rss
```
> fix(route/apnews): Fix AP news time.

- lib/routes/weibo/utils.ts
Close #
```routes
/weibo/friends
/weibo/group/4541216424989965
/weibo/keyword/DIYgod
/weibo/super_index/1008084989d223732bf6f02f75ea30efad58a9/sort_time
/weibo/timeline/3306934123
```
给微博路由 提取了 话题 作为 category 字段
> feat(route): 微博路由 新增 category 字段

- lib/routes/twitter/utils.ts
Close #
```routes
/twitter/home 
/twitter/keyword/RSSHub 
/twitter/list/ladyleet/javascript 
/twitter/likes/DIYgod 
/twitter/media/DIYgod 
```
> feat(route): twitter 路由新增：将话题提取为 category

- lib/routes/dhu/jiaowu/news.ts
- lib/routes/dhu/namespace.ts
- lib/routes/dhu/xxgk/news.ts
Close #
```routes
/dhu/jiaowu/news/student
/dhu/jiaowu/news/teacher
/dhu/jiaowu/news/class
/dhu/jiaowu/news/fxzy
/dhu/xxgk/news
```
> fix(route): route jiaowu and xxgk for Donghua University

- lib/routes/twitter/utils.ts
Close #
```routes
/twitter/home 
/twitter/keyword/RSSHub 
/twitter/list/ladyleet/javascript 
/twitter/likes/DIYgod 
/twitter/media/DIYgod 
```
> fix(route): 修复 twitter 路由会匹配到 # 开头的颜色字符的问题

- lib/routes/bilibili/dynamic.ts
Close #
```routes
/bilibili/user/dynamic/401742377
```
> feat(route): bilibili 动态路由新增：将话题作为 category

- lib/routes/jlu/jwc.ts
- lib/routes/jlu/namespace.ts
Close #
```routes
/jlu/jwc
```
> feat: add jlujwc

- lib/views/error.tsx
- lib/views/index.tsx
N/A
```routes
NOROUTE
```
https://icons.ly/twitter 已失效
> fix: X icon

- lib/routes/weibo/user-bookmarks.ts
Close #
```routes
/weibo/user_bookmarks/1195230310
```
> add weibo/user-bookmarks 微博用户收藏动态 route

- lib/routes/twreporter/category.ts
- lib/routes/twreporter/fetch-article.ts
- lib/routes/twreporter/newest.ts
Related to #15763
```routes
/twreporter/newest
```
> fix(route/twreporter): Change to ofetch and other fix

- lib/routes/wired/namespace.ts
- lib/routes/wired/tag.ts
- lib/routes/wired/types.ts
Close #11376
```routes
/wired/tag/science
```
https://github.com/DIYgod/RSSHub/commits/master/lib/routes/wired
> fix(route): recover wired

- lib/routes/oschina/news.ts
Close #
```routes
/oschina/news
```
> fix(route): fetch articles from osc.cool

- lib/routes/gov/sh/fgw/index.ts
- lib/routes/gov/sh/rsj/ksxm.ts
- lib/routes/gov/sh/wgj/wgj.ts
- lib/routes/gov/sh/wsjkw/yqtb/index.ts
- lib/routes/gov/sh/yjj/index.ts
Close #
```routes
/gov/shanghai/wgj
```
> fix(route): restore /gov/shanghai

- lib/routes/alistapart/utils.ts
- lib/routes/chaping/newsflash.ts
- lib/routes/codeforces/contests.ts
- lib/routes/codeforces/recent-actions.ts
- lib/routes/dblp/publication.ts
- lib/routes/dlnews/utils.ts
- lib/routes/dushu/fuzhou/index.ts
- lib/routes/freebuf/index.ts
- lib/routes/gov/beijing/bphc/index.ts
- lib/routes/grist/utils.ts
- lib/routes/hrbeu/job/calendar.ts
- lib/routes/leetcode/articles.ts
- lib/routes/luogu/user-blog.ts
- lib/routes/modb/topic.ts
- lib/routes/npm/package.ts
- lib/routes/stockedge/utils.ts
- lib/routes/trending/all-trending.ts
- lib/routes/zjgtjy/index.ts
#15763
```routes
/alistapart
/chaping/newsflash
/codeforces/contests
/codeforces/recent-actions
/dblp/knowledge%20tracing
/dlnews
/dushu/fuzhou
/freebuf/articles/web
/gov/beijing/bphc/announcementList
/grist
/hrbeu/job/calendar
/leetcode/articles
/luogu/user/blog/ouuan
/modb/topic/44158
/npm/package/rsshub
/stockedge/daily-updates/news
/trending/唐山,打人/3
/zjgtjy
```
不保证所有的都正常工作（有一些不是 got json() 的问题）
有一些路由的反爬策略严格，本地测试被 403 ，最好能找到其他人再来确认一下
有一些代码里看上去不对，但 rsshub.app 的样例响应却没有问题，需要再进一步确认是缓存未失效还是代码未执行到
> fix: 使用 ofetch() 替换一些 got().json()

- lib/routes/ymgal/article.ts
Close #
```routes
/ymgal/article
/ymgal/article/news
/ymgal/article/column
```
> fix: fix ymgal article data fetching

- lib/routes/dataguidance/index.ts
- lib/routes/dataguidance/namespace.ts
```routes
/dataguidance/news
```
> feat: add dataguidance news

- lib/routes/javdb/series.ts
- lib/routes/javdb/videocodes.ts
Close #
```routes
/javdb/video_codes/SIVR
```
~虽然只是复制过来改改参数就成了~
> feat(route): javdb video codes

- lib/routes/npm/package.ts
Close #
```routes
/npm/package/node
```
> docs: fix npm

- lib/routes/psyche/namespace.ts
- lib/routes/psyche/templates/essay.art
- lib/routes/psyche/templates/video.art
- lib/routes/psyche/topic.ts
- lib/routes/psyche/type.ts
- lib/routes/psyche/utils.ts
Close #
```routes
/psyche/topic/therapeia
/psyche/type/ideas
```
> feat(route): support psyche.co

- lib/types.ts
> docs(types): mention the GitHub issue for the new design

- lib/routes/apnews/topics.ts
- lib/routes/apnews/utils.ts
Close #
```routes
/apnews/rss
```
AP is to blame...
> fix(route/apnews): Fix page

- lib/config.ts
- lib/routes/sspai/prime-community.ts
Close #
```routes
/sspai/prime/community
```
> feat(route): add SSPAI Prime Community feed route

- lib/routes/weibo/user.ts
Close #
```routes
/weibo/user/6827625527
```
radar适配微博pc站域名`www.weibo.com`
> fix: add www.weibo.com for weibo radar

- lib/routes/manyvids/namespace.ts
- lib/routes/manyvids/templates/video.art
- lib/routes/manyvids/types.ts
- lib/routes/manyvids/video.ts
Close #
```routes
/manyvids/profile/vids/1001213004
```
> feat(route): manyvids

- lib/config.ts
- lib/routes/theinitium/channel.ts
- lib/routes/theinitium/follow.ts
- lib/routes/theinitium/utils.ts
Close #13388 
```routes
/theinitium/channel/latest/zh-hans
```
- Remove authentication method by `INITIUM_IAP_RECEIPT`, as the iOS app no longer use header `X-IAP-Receipt` in its requests
- Fix authentication method by username and password login
- Add maintainer
> fix(route): update The Inithium authentication method

- Dockerfile
- package.json
> chore: docker bump base image

- lib/routes/beijingprice/index.ts
- lib/routes/beijingprice/namespace.ts
Close #15762
```routes
/beijingprice/jgzx/xwzx
```
> feat(route): add 北京价格

- lib/routes/2048/index.ts
Close #
```routes
/2048/18
```
> fix(route): url formatting in 2048

- lib/routes/my-formosa/index.ts
- lib/routes/my-formosa/namespace.ts
Close #
```routes
/my-formosa
```
> feat(route/my-formosa): Create route

- lib/routes/finviz/news.ts
Close #15786 
```routes
/finviz
```
> fix(route): finviz

- lib/routes/dangdang/namespace.ts
- lib/routes/dangdang/notice.ts
Close #
```routes
/dangdang/notice
```
> feat(route): 新增路由当当开放平台

- lib/routes/steam/sharefile-changelog.ts
Close #
```routes
/steam/sharefile-changelog/2851063440
/steam/sharefile-changelog/3255547370
/steam/sharefile-changelog/3255547370/l=schinese
```
> feat(route): add steam sharefile changelog route

- lib/routes/steam/sharefile-changelog.ts
Close #
```routes
/steam/sharefile-changelog/3255547370/l=schinese
```
> fix(route/steam): sharefile-changelog example route

- lib/routes/dewu/declaration.ts
- lib/routes/dewu/namespace.ts
- lib/routes/jinritemai/docs.ts
- lib/routes/jinritemai/namespace.ts
Close #
```routes
/dewu/declaration
/jinritemai/docs
```
新增了得物开放平台和抖店开放平台的订阅
> feat(route): 新增得物开放平台和抖店开放平台

- lib/routes/informedainews/docs.ts
- lib/routes/informedainews/namespace.ts
Close #
https://informedainews.com/zh-Hans/docs/ai-enthusiast-daily
```routes
/informedainews/zh-Hans/docs/world-news-daily
/informedainews/zh-Hans/docs/tech-enthusiast-weekly
/informedainews/zh-Hans/docs/ai-enthusiast-daily
```
> feat(route): 新增知闻AI资讯

- lib/routes/nmc/weatheralarm.ts
Close #15900
```routes
/nmc/weatheralarm/%E8%A5%BF%E8%97%8F%E8%87%AA%E6%B2%BB%E5%8C%BA
```
所测试的西藏自治区目前是没有预警信息的：
> fix(route): 允许全国气象预警生成空源不报错

- lib/routes/twreporter/category.ts
Close #15910
```routes
twreporter/category/world
twreporter/category/humanrights
twreporter/category/politics_and_society
twreporter/category/environment
twreporter/category/econ
twreporter/category/culture
twreporter/category/education
twreporter/category/podcast
twreporter/category/opinion
twreporter/category/photos_section
```
发现是个开源项目，所以新的修改信息基本是从这个项目获取而来的 [go-api](https://github.com/twreporter/go-api )
> fix(route): 「報導者」路由输出不完整

- lib/routes/sicau/jiaowu.ts
- lib/routes/sicau/namespace.ts
Close #
```routes
/sicau/jiaowu/jxtz
```
新增四川农业大学教务处教学通知的订阅
> feat(route): 新增四川农业大学教务处

- lib/routes/v2ex/topics.ts
Close #
```routes
/v2ex/topics/latest
/v2ex/topics/hot
```
> feat(route): support v2ex category

- lib/routes/zhubai/top20.ts
Close #
```routes
/zhubai/top20
```
> fix(route): item links in zhubai top20

- lib/routes/sicau/jiaowu.ts
Close #
```routes
NOROUTE
```
去除川农教务处反爬严格标签，添加雷达规则
> docs(route): 去除反爬严格标签，添加雷达规则

- lib/routes/cara/constant.ts
- lib/routes/cara/likes.ts
- lib/routes/cara/namespace.ts
- lib/routes/cara/portfolio.ts
- lib/routes/cara/templates/post.art
- lib/routes/cara/timeline.ts
- lib/routes/cara/types.ts
- lib/routes/cara/utils.ts
Close #15893
```routes
/cara/portfolio/fengz
/cara/timeline/fengz
/cara/likes/fengz
```
> feat(route): cara.app

- lib/routes/bjx/fd.ts
- lib/routes/bjx/namespace.ts
Close #15924 
```routes
/bjx/fd/yw
/bjx/fd/zc
/bjx/fd/sj
/bjx/fd/sc
/bjx/fd/mq
/bjx/fd/zb
/bjx/fd/js
/bjx/fd/bd
```
新增北极星风电网下的要闻、政策、数据、市场、企业、招标、技术、报道版块
> feat(route): 新增北极星风电网

- lib/views/rss3.test.ts
N/A
```routes
/views
```
add test for method of rss3
> test: add test for rss3

- lib/routes/bt0/mv.ts
- lib/routes/bt0/namespace.ts
Close #
```routes
/bt0/mv/25977027
/bt0/mv/25977027/3
```
只做了该网址下 /mv 路径的下的资源下载列表的rss订阅
> feat(route): Add bt0 (不太灵)

- lib/routes/sehuatang/index.ts
Close #15713 
```routes
/sehuatang
```
> fix(route): sehuatang 403报错

- lib/routes/kelownacapnews/namespace.ts
- lib/routes/kelownacapnews/news.ts
Close #15520 
```routes
/kelownacapnews/news
/kelownacapnews/local-news
/kelownacapnews/national-news
/kelownacapnews/world-news
/kelownacapnews/entertainment
/kelownacapnews/sports
/kelownacapnews/business
/kelownacapnews/trending-now
/kelownacapnews/opinion
```
Add Kelowna Capital News
> feat(route): Add Kelowna Capital News

- lib/routes/bc3ts/list.ts
- lib/routes/bc3ts/namespace.ts
- lib/routes/bc3ts/templates/media.art
- lib/routes/bc3ts/types.ts
Close #15907
```routes
/bc3ts/post/list
```
> feat(route): bc3ts

- .github/workflows/build-assets.yml
Close #
```routes
```
如果 `DOCS_API_TOKEN` 未设置则不执行 `Build assets` 中推送文件到 `RSSNext` 避免 fork 出来的分支 workflow  执行报错
> chore(dev): ignore build assets if `DOCS_API_TOKEN` not set

- lib/routes/apnews/topics.ts
- lib/routes/apnews/utils.ts
> fix(route/apnews): Remove duplicate

- lib/routes/bt0/tlist.ts
- lib/routes/bt0/util.ts
Close #
```routes
/bt0/tlist/1
/bt0/tlist/2
/bt0/tlist/3
/bt0/tlist/4
/bt0/tlist/5
```
Add new routes and refactor code.
> feat(routes): add bt0(不太灵)的最新资源列表

- lib/routes/fansly/post.ts
- lib/routes/fansly/tag.ts
- lib/routes/fansly/utils.ts
- lib/routes/myfans/namespace.ts
- lib/routes/myfans/post.ts
- lib/routes/myfans/templates/post.art
- lib/routes/myfans/types.ts
- lib/routes/myfans/utils.ts
Close #
```routes
/myfans/user/secret_japan
```
> feat(route): myfans

- lib/routes/alpinelinux/namespace.ts
- lib/routes/alpinelinux/pkgs.ts
Close #
```routes
/alpinelinux/pkgs/nodejs
/alpinelinux/pkgs/nodejs/branch=edge&repo=&arch=x86_64&maintainer=Jakub%20Jirutka
```
> feat(route): add Alpine Linux packages update route

- lib/routes/cccfna/index.ts
- lib/routes/cccfna/namespace.ts
- lib/routes/samd/namespace.ts
- lib/routes/samd/news.ts
Close #15953 Close #15858 
```routes
/cccfna/meirigengxin
/cccfna/maoyitongji/tongjikuaibao
/samd/news/440
/samd/news/438
/samd/news/434
```
> feat(routes): 新增深圳市医疗器械行业协会和中国食品土畜进出口商会

- lib/routes/alpinelinux/namespace.ts
- lib/routes/alpinelinux/pkgs.ts
Close #
```routes
/alpinelinux/pkgs/nodejs
/alpinelinux/pkgs/nodejs/branch=edge&repo=&arch=x86_64&maintainer=Jakub%20Jirutka
```
> fix(route): fix alpinelinux guid/link/description

- lib/routes/zhihu/zhuanlan.ts
Close #15913
```routes
/zhihu/zhuanlan/c_1434958074263638016
```
> fix(route): fetch zhihu column info with signed header

- lib/routes/discourse/notifications.ts
Close #
```routes
/discourse/0/notifications
```
> feat(route/discourse): Cache site information

- lib/routes/ollama/models.ts
Close #
```routes
/ollama/library
```
fix /ollama/library description, add pubDate
> fix(route): ollama library

- lib/routes/ollama/blog.ts
Close #
```routes
/ollama/blog
```
> feat(route): add ollama blog

- lib/routes/microsoft/mcr.ts
```routes
/microsoft/mcr/product/dotnet/framework/runtime
```
This PR will add the product tag name at the end of the items' links to fix the RSS output.
> fix(route): Microsoft Artifact Registry route

- lib/routes/meituan/namespace.ts
- lib/routes/meituan/tech.ts
Close #
```routes
/meituan/tech
```
https://tech.meituan.com 美团技术团队的博客文章。
> feat(route): add meituan tech blog

- lib/routes/3dmgame/news-center.ts
Close #
```routes
/3dmgame/news
```
Example: https://www.3dmgame.com/news/202406/3898333.html
Before this PR, the entry title of 3DM news would be appended with an extra string:
> 《哈利波特》第一部封面拍卖成功 高达190万美元刷新预期**哈利波特**
(The bold text is the extra string)
This pull request strips the extra string from the title, making it match the title of the webpage:
> 《哈利波特》第一部封面拍卖成功 高达190万美元刷新预期
> fix(route): strip tags from the title of the 3DM news route

- lib/routes/raycast/changelog.ts
- lib/routes/raycast/namespace.ts
N / A
```routes
/raycast/changelog
```
Force push for correcting typo.
> feat(route): introduce `/raycast/changelog`

- lib/routes/investor/index.ts
- lib/routes/investor/namespace.ts
Close #15773
```routes
/investor/information_release/news_release_from_authorities/zjhfb
```
> feat(route): add 中国投资者网

- lib/routes/asmr-200/index.ts
- lib/routes/asmr-200/namespace.ts
- lib/routes/asmr-200/templates/work.art
- lib/routes/asmr-200/type.ts
Close #
```routes
asmr-200/works
asmr-200/works/release/1/asc
asmr-200/works/price/1
```
新增 ASMR Online
> feat(route): 新增 ASMR Online

- lib/routes/utgd/category.ts
- lib/routes/utgd/timeline.ts
- lib/routes/utgd/topic.ts
- lib/routes/utgd/utils.ts
Close #
```routes
/utgd/category/method
```
> fix(route): utgd category

- lib/routes/asmr-200/index.ts
Close #
```routes
NOROUTE
```
修改路由错误
> docs(route): 修改路由错误

- lib/routes/deadbydaylight/index.ts
- lib/routes/deadbydaylight/namespace.ts
Close #
```routes
/deadbydaylight/blog
```
deadbydaylight.com/blog
1. 列出了所有文章（目前300+）
2. 脚本会每次获取所有文章内容，均为静态JSON
3. 使用了缓存
4. 本地测试~1分钟内可以完成
> feat(route): deadbydaylight.com latest blog

- lib/routes/investor/index.ts
Close #16030
```routes
/investor/information_release/news_release_from_authorities/hyxhfb
```
> fix(route): 中国投资者网返回空结果

- lib/routes/investor/index.ts
Close #16046
```routes
/investor/information_release/news_release_from_authorities/qhjysfb
```
> fix(route): 中国投资者网标题丢失

- lib/routes/nextjs/blog.ts
- lib/routes/nextjs/namespace.ts
N / A
```routes
/nextjs/blog
```
> feat(route): introduce `/nextjs/blog`

- lib/routes/react/blog.ts
- lib/routes/react/namespace.ts
N / A
```routes
/react/blog
```
> feat(route): add `/react/blog`

- lib/routes/mirrormedia/index.ts
- lib/routes/mirrormedia/namespace.ts
Close #
```routes
/mirrormedia
```
镜新闻自带RSS: https://www.mirrormedia.mg/rss/rss.xml ，此处获取列表方式与官方RSS不同。
> feat(route): Mirror Media

- lib/routes/bt0/mv.ts
- lib/routes/bt0/tlist.ts
- lib/routes/bt0/util.ts
Close #
```routes
/bt0/mv/36073279
/bt0/mv/35575567/2
/bt0/tlist/1
/bt0/tlist/2
/bt0/tlist/3
/bt0/tlist/4
/bt0/tlist/5
```
After the website update, a new API was used.
> fix(routes): bt0(不太灵) use new api

- lib/routes/buaa/jiaowu.ts
- lib/routes/buaa/news/index.ts
- lib/routes/buaa/sme.ts
N/A
```routes
buaa/jiaowu
```
Also fixed some lint & type warnings in `/buaa`.
> feat(route): add `/buaa/jiaowu`

- lib/routes/luolei/index.ts
Close #16039
```routes
/luolei
```
> fix(route): 罗磊的独立博客

- lib/routes/sjtu/yzb/zkxx.ts
Close #
```routes
/sjtu/yzb/zkxx/sszs
/sjtu/yzb/zkxx/bszs
/sjtu/yzb/zkxx/gatzs
/sjtu/yzb/zkxx/kdxx
/sjtu/yzb/zkxx/yxdt
```
> feat(route/sjtu/yzb): Full text fetch

- lib/routes/udn/breaking-news.ts
Close #
```routes
/udn/news/breakingnews/5
```
> fix(route/udn): Support udn Global when fetching `breakingnews`

- lib/routes/japanpost/namespace.ts
- lib/routes/japanpost/router.ts
- lib/routes/japanpost/track.ts
Close #
```routes
/japanpost/track/323434515246/ja
```
Split out route definition, add multi-language docs.
> docs(route): japanpost add multi-language docs

- lib/routes/xinhuanet/app.ts
- lib/routes/xinhuanet/namespace.ts
Close #16034
```routes
/xinhuanet/app
```
> feat(route): add 新华网客户端

- lib/routes/apnews/utils.ts
Close #
```routes
/apnews/topics
/apnews/rss
```
> fix(route/apnews): Tackle occasionally missing keywords in ld-json.

- lib/config.ts
- lib/routes/readwise/list.ts
- lib/routes/readwise/namespace.ts
N / A
```routes
/readwise/list
/readwise/list/location=new
/readwise/list/location=later&category=article
/readwise/list/tag=shortlist&tag=AI&tagStrategy=all
```
必须配置环境变量 `READWISE_ACCESS_TOKEN` 。
> feat(route): Add a route to fetch Readwise Reader documents.

- lib/routes/thoughtworks/index.ts
- lib/routes/thoughtworks/namespace.ts
无
```routes
/thoughtworks/blog
```
支持 thoughtworks blog 的RSS订阅，文档列表地址： https://www.thoughtworks.com/zh-cn/insights/blog
> feat: support RSS thoughtworks blog 

- lib/routes/github/activity.ts
Close #
```routes
/github/activity/DIYgod
```
The official RSS feed of GitHub has some issues:
1. The default title cannot distinguish subscribed users
2. The link in a item is not a full link
3. The format of the image is a non-standard format
```
<media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/u/8266075?s=30&amp;v=4"/>
```
> feat(route): github user activity

- lib/routes/j-test/namespace.ts
- lib/routes/j-test/news.ts
Close #
```routes
/j-test/news
```
> feat(route): add j-test.com

- lib/routes/bbc/index.ts
Close #16032
```routes
/bbc/world-asia
/bbc/world
```
> fix(route/BBC): 403 Forbidden Edge 5

- lib/routes/zhihu/utils.ts
Close #
```routes
/zhihu/zhuanlan/crossborder
```
> fix(route): Correctly obtain `d_c0` from response from Zhihu Zhuanlan

- lib/routes/fortunechina/index.ts
Close #16047
```routes
/fortunechina
/fortunechina/lingdaoli
/fortunechina/shangye
/fortunechina/keji
```
> fix(route/fortunechina): Fix

- lib/routes/zhuwang/index.ts
Close #15955
```routes
/zhuwang/zhujia
```
> fix(route): 「全国今日生猪价格」 接口地址变更

- lib/routes/huxiu/util.ts
Close #
```routes
/huxiu/article
```
Example link: https://www.huxiu.com/article/3259695.html
> fix(route/huxiu): Avoid reading property of undefined while handling premium article

- lib/routes/github/activity.ts
Close #
```routes
/github/activity/DIYgod
```
> fix(route): short title, use guid for github activities

- lib/routes/zhihu/utils.ts
Close #
```routes
/zhihu/people/answers/diygod
```
> fix(route/zhihu): Drop preceding string while extracting `d_c0`

- lib/routes/chlinlearn/daily-blog.ts
- lib/routes/chlinlearn/namespcae.ts
Close #
```routes
/chlinlearn/daily-blog
```
> feat(route): chlinlearn daily bolg

- lib/routes/autocentre/index.ts
- lib/routes/autocentre/namespace.ts
Close #
```routes
/autocentre
```
_Автоцентр_ - Automotive website N1 in Ukraine
> feat(route): add `/autocentre`

- lib/routes/v2ex/xna.ts
Close #
```routes
/v2ex/xna
```
VXNA, A new channel of v2ex: https://v2ex.com/xna
> feat(route): add v2ex xna

- lib/routes/inspirehep/author.ts
- lib/routes/inspirehep/literature.ts
- lib/routes/inspirehep/namespace.ts
- lib/routes/inspirehep/types.ts
- lib/routes/inspirehep/utils.ts
Close #16194
```routes
/inspirehep/literature/Physics
/inspirehep/authors/1696909
```
> feat(route): inspirehep

- lib/routes/sspai/author.ts
- lib/routes/sspai/column.ts
- lib/routes/sspai/index.ts
- lib/routes/sspai/matrix.ts
- lib/routes/sspai/series-update.ts
- lib/routes/sspai/tag.ts
- lib/routes/sspai/topic.ts
Close #
```routes
/sspai/matrix
/sspai/index
```
> fix: sspai image links

- lib/routes/yahoo/news/index.ts
- lib/routes/yahoo/news/listid.ts
- lib/routes/yahoo/news/utils.ts
N/A
```routes
/yahoo/news/list/hk/5a8a0aa0-0ab3-11e8-b3dc-d990c79d6cb1
/yahoo/news/list/hk/1cc44280-facb-11e9-ad7c-f3ba971275c8
/yahoo/news/list/hk/40023670-facc-11e9-9dde-9175ff306602
```
```
as some providers show no contents in archive …
```
> feat(route/yahoo/news): add HK-exclusive `listId` mode

- lib/routes/oschina/news.ts
Close #
```routes
/oschina/news
```
在获取到ajax页面后就去除ad-wrap，以避免ad条目作为cache key进行缓存查询，解决Cache key must be a string的问题。
> fix(route/oschina): Remove ads from entries

- lib/routes/bjx/fd.ts
Close #
```routes
/bjx/fd/yw
/bjx/fd/zc
/bjx/fd/sj
/bjx/fd/sc
/bjx/fd/mq
/bjx/fd/zb
/bjx/fd/js
/bjx/fd/bd
```
抓取全文
> fix(route): 抓取北极星风电网文章全文

- lib/routes/springer/journal.ts
Close #16262
```routes
/springer/journal/10902
```
网页发生变化，原有的代码失效，本次进行了更新
The webpage has changed, the original code is no longer valid, and it has been updated this time.
> fix(route/springer/journal): Update selectors in the web scraping code

- lib/routes/bilibili/dynamic.ts
Close #
```routes
/bilibili/user/dynamic/296909317
```
> fix(route): 优化 bilibili 动态路由的 category

- lib/routes/bjnews/cat.ts
Close #
```routes
/bjnews/cat/depth?limit=2
/bjnews/cat/diyikandian?limit=2
/bjnews/cat/news?limit=2
```
> fix(route/bjnews): Clarify feed title

- lib/config.ts
- lib/routes/keylol/index.ts
未登录或权限不足时
pubDate author 会使用列表页的数据
description 会显示错误讯息
Close #16280
```routes
/keylol/f161-1
```
> fix(route/keylol): 改进有阅读权限的帖子

- lib/routes/pixiv/search.ts
Close #
```routes
/pixiv/search/結城友奈は勇者である/date/no/no
```
Add parameter to `pixiv/search` to filter AI-generated contents
> feat(route): pixiv/search filter AI-generated content

- lib/routes/juejin/dynamic.ts
Close #
```routes
/juejin/dynamic/852876722177533
/juejin/dynamic/852876722177533?mode=fulltext
```
- [x Follows [Script Standard](https://docs.rsshub.app/joinus/advanced/script-standard) / 跟随 [路由规范](https://docs.rsshub.app/zh/joinus/advanced/script-standard)
> feat(route): 新增 掘金用户动态 路由

- lib/routes/discourse/notifications.ts
Close #
```routes
/discourse/0/notifications
```
> fix(route/discourse): Mark whether the notification is read.

- lib/routes/zhihu/namespace.ts
- lib/routes/zhihu/utils.ts
Close #16260 
```routes
/zhihu/people/answers/diygod
```
> feat(route/zhihu): Allow to set login cookies

- lib/routes/mcmod/index.ts
- lib/routes/mcmod/namespace.ts
- lib/routes/mcmod/templates/mod.art
Close #16205 
```routes
/mcmod/random
/mcmod/new
/mcmod/edit
```
新增MC百科路由，可抓取隨機，最新收錄和最近編輯的MOD動態
> feat(route): 新增MC百科路由

- lib/routes/twitter/api/web-api/utils.ts
- lib/routes/twitter/home.ts
- lib/routes/twitter/user.ts
fix #16193
Close #
```routes
/twitter/home
/twitter/keyword/RSSHub
/twitter/list/ladyleet/javascript
/twitter/trends/23424856
/twitter/tweet/DIYgod/status/1650844643997646852
/twitter/likes/DIYgod
/twitter/media/_RSSHub
/twitter/user/_RSSHub
```
该修复方案来自 [undici/proxy.mjs](https://github.com/3846masa/http-cookie-agent/blob/main/examples/undici/proxy.mjs)
> fix(route): fix bug where X (Twitter) router cannot go through proxy configuration

- lib/routes/github/search.ts
Close #16228
```routes
/github/search/rsshub/updated/desc
```
> fix: github search result

- lib/errors/index.tsx
To help better parse the error message on the client.
```routes
NOROUTE
```
> fix: return json error message when ?format=json

- lib/views/error.tsx
- lib/views/index.tsx
- lib/views/layout.tsx
Fix the layout css on the error page and index page.
Before: (footer position)
Now:
```routes
NOROUTE
```
> fix: error page layout

- lib/routes/aljazeera/index.ts
- lib/routes/cccfna/index.ts
- lib/routes/digitalcameraworld/news.ts
- lib/routes/gq/news.ts
- lib/routes/psyche/topic.ts
- lib/routes/psyche/type.ts
- lib/routes/psyche/utils.ts
- lib/routes/samd/news.ts
- lib/routes/sara/index.ts
Close #
```routes
/cccfna/meirigengxin
/digitalcameraworld/news
/gq/news
/psyche/topic/therapeia
/samd/news/440
```
> fix(route): ofetch usage
